### ISSUE TITLE
debian documentation is missleading 

### ISSUE THREAD

**Issue by icf20** [jaagr/polybar#1000]
> If you are using Debian, polybar is available from the GetDeb repository.

there is no release for debian only for ubuntu http://www.getdeb.net/app/Polybar

**Comment by keithieopia** [comment]
See the [Don't make a FrankenDebian](https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian) page on why using Ubuntu repos in Debian is bad. Honestly, the documentation should just say to build it from source for Debian.

**Comment by patrick96** [comment]
You two are right. I just opened a PR to change the Debian mention to Ubuntu.

**Comment by icf20** [comment]
I don't know if u got the time to look at this, but if I remember correctly Debian stable don't have the lib's version required only Debian unstable/testing have them

**Comment by patrick96** [comment]
Unfortunately I don't have that kind of time. But as far as I remember, no one has had problems locating the dependent packages on debian, so I think we're good. If someone does at some point, it might be worth adding it to the wiki
