### ISSUE TITLE
System tray transparency

### ISSUE THREAD

**Issue by archmerge** [jaagr/polybar#1001]
I have read the issue #382 and I wanted you to show and ask to reconsider to make transparency in the system tray with icons possible (top right in image). We made beautiful desktops with your bar and added 33 modules but once an ArchMerger asks for transparency we are stuck. I am correct in assuming this does not work yet?
![archmerge-polybar-transparent](https://user-images.githubusercontent.com/31759042/35770642-5de74306-091f-11e8-90e3-0f7369dae597.png)

**Comment by NBonaparte** [comment]
#595 should implement pseudo-transparency, which is the only way to make the tray "transparent".
