### ISSUE TITLE
Unable to open libjsoncpp

### ISSUE THREAD

**Issue by thunderactual** [jaagr/polybar#1005]
I get this error when I try to run polybar:
$ polybar: error while loading shared libraries: libjsoncpp.so.19: cannot open shared object file: No such file or directory

What should I do?

**Comment by avindra** [comment]
You should probably include what OS, kernel, etc you're using before someone can help you.

**Comment by NBonaparte** [comment]
Rebuild polybar so it builds against the new jsoncpp library. There have been many duplicate issues opened in the past few days; please search for existing issues before creating a new one.
