### ISSUE TITLE
Put libjsoncpp error in README

### ISSUE THREAD

**Issue by benoliver999** [jaagr/polybar#1006]
Is it worth putting a link to the libjsoncpp error on the 'Known Issues' wiki page in the readme?

I am almost on the verge of getting off the mailing list because every other issue is the same!

**Comment by NBonaparte** [comment]
To be honest, I don't think it won't change anything if we did put it there. It already refers to the wiki, and SUPPORT.md should show before creating a new issue which also suggests looking at the wiki. People just can't be arsed to read any of it.
