### ISSUE TITLE
Polybar Battery Module Not Working

### ISSUE THREAD

**Issue by ssaltwick** [jaagr/polybar#1008]
On Arch 4.15.1-2-ARCH (Antergos) and polybar 3.1.0-39-g26abd0f, my battery module is being stopped on run. It is the standard module from the example bar config, and worked as recent as last night. I have reinstalled polybar by removing all files and rebuilding the master, but it is still not working. The error I receive on crash is "error: module/battery: std::bad_alloc". None of the solutions I have seen for this issue are working.

**Comment by NBonaparte** [comment]
Are you still using commit 26abd0f or the latest (014ac82)?

**Comment by ssaltwick** [comment]
When I most recently cloned the 3.1.0 branch, I got commit bf16a4d #863 . Looks like that might be the issue...

**Comment by NBonaparte** [comment]
Does cloning from master (using commit 014ac82) still result in the error?

**Comment by ssaltwick** [comment]
That was it! Thank you. The issue was that the README says to clone branch 3.1.0, which gets you an older commit.
