### ISSUE TITLE
Compilation fails with ALSA disabled

### ISSUE THREAD

**Issue by jonhoo** [jaagr/polybar#1016]
Specifically, linking fails with:
```
[100%] Linking CXX executable polybar
CMakeFiles/polybar.dir/modules/alsa.cpp.o: In function `polybar::v3_1_0_45_gb37e4a0_git::modules::alsa_module::teardown()':
/home/jon/dev/others/polybar/src/modules/alsa.cpp:92: undefined reference to `snd_config_update_free_global'
CMakeFiles/polybar.dir/modules/alsa.cpp.o: In function `alsa_module':
/home/jon/dev/others/polybar/src/modules/alsa.cpp:50: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::mixer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:53: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::mixer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:56: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::mixer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:59: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::control::control(int)'
CMakeFiles/polybar.dir/modules/alsa.cpp.o: In function `polybar::v3_1_0_45_gb37e4a0_git::modules::alsa_module::has_event()':
/home/jon/dev/others/polybar/src/modules/alsa.cpp:98: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::wait(int)'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:101: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::wait(int)'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:104: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::wait(int)'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:107: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::control::wait(int)'
CMakeFiles/polybar.dir/modules/alsa.cpp.o: In function `polybar::v3_1_0_45_gb37e4a0_git::modules::alsa_module::update()':
/home/jon/dev/others/polybar/src/modules/alsa.cpp:120: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::process_events()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:123: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::process_events()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:126: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::process_events()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:129: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::control::process_events()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:139: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::get_normalized_volume()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:140: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::get_volume()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:141: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::is_muted()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:148: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::control::test_device_plugged()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:150: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::get_normalized_volume()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:151: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::get_volume()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:152: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::is_muted()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:160: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::get_normalized_volume()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:161: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::get_volume()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:162: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::is_muted()'
CMakeFiles/polybar.dir/modules/alsa.cpp.o: In function `polybar::v3_1_0_45_gb37e4a0_git::modules::alsa_module::input(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)':
/home/jon/dev/others/polybar/src/modules/alsa.cpp:233: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::get_name[abi:cxx11]()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:235: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::get_name[abi:cxx11]()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:235: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::get_sound_card[abi:cxx11]()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:234: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::mixer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:237: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::get_name[abi:cxx11]()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:239: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::get_name[abi:cxx11]()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:239: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::get_sound_card[abi:cxx11]()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:238: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::mixer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:241: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::get_name[abi:cxx11]()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:243: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::get_name[abi:cxx11]()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:243: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::get_sound_card[abi:cxx11]()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:242: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::mixer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:248: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::is_muted()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:248: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::set_mute(bool)'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:252: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::get_normalized_volume()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:252: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::set_normalized_volume(float)'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:253: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::get_volume()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:253: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::set_volume(float)'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:257: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::get_normalized_volume()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:257: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::set_normalized_volume(float)'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:258: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::get_volume()'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:258: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::set_volume(float)'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:265: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::wait(int)'
/home/jon/dev/others/polybar/src/modules/alsa.cpp:266: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::process_events()'
CMakeFiles/polybar.dir/modules/alsa.cpp.o: In function `polybar::v3_1_0_45_gb37e4a0_git::modules::alsa_module::teardown()':
/home/jon/dev/others/polybar/src/modules/alsa.cpp:92: undefined reference to `snd_config_update_free_global'
CMakeFiles/polybar.dir/modules/alsa.cpp.o: In function `__shared_count<polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer *>':
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/shared_ptr_base.h:588: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::~mixer()'
CMakeFiles/polybar.dir/modules/alsa.cpp.o: In function `std::_Sp_counted_ptr<polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer*, (__gnu_cxx::_Lock_policy)2>::_M_dispose()':
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/shared_ptr_base.h:376: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::mixer::~mixer()'
CMakeFiles/polybar.dir/modules/alsa.cpp.o: In function `__shared_count<polybar::v3_1_0_45_gb37e4a0_git::alsa::control *>':
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/shared_ptr_base.h:588: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::control::~control()'
CMakeFiles/polybar.dir/modules/alsa.cpp.o: In function `std::_Sp_counted_ptr<polybar::v3_1_0_45_gb37e4a0_git::alsa::control*, (__gnu_cxx::_Lock_policy)2>::_M_dispose()':
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/shared_ptr_base.h:376: undefined reference to `polybar::v3_1_0_45_gb37e4a0_git::alsa::control::~control()'
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/CMakeFiles/polybar.dir/build.make:1950: bin/polybar] Error 1
make[1]: *** [CMakeFiles/Makefile2:512: bin/CMakeFiles/polybar.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
** Failed to build project
```

Build log:
<details>
<pre>
** Fetching submodules
** Using compiler: clang++/clang
** Executing cmake command
-- The C compiler identification is Clang 5.0.1
-- The CXX compiler identification is Clang 5.0.1
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type specified; using RelWithDebInfo
-- Using supported compiler Clang-5.0.1
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Checking for module 'cairo-fc'
--   Found cairo-fc, version 1.15.10
-- Checking for module 'libcurl'
--   Found libcurl, version 7.58.0
-- Found Libiw: /usr/lib/libiw.so
-- Checking for module 'libpulse'
--   Found libpulse, version 11.1
-- Checking for module 'xcb-xkb'
--   Found xcb-xkb, version 1.12
-- Checking for module 'xcb-randr'
--   Found xcb-randr, version 1.12
-- Checking for module 'xcb-randr>=1.12'
--   Found xcb-randr, version 1.12
-- Checking for module 'xcb-xrm'
--   Found xcb-xrm, version 1.2
-- Checking for module 'xcb-cursor'
--   Found xcb-cursor, version 0.1.3
--  Build:
--    Type: RelWithDebInfo
--    CC: /usr/bin/clang  -O2 -g -DNDEBUG
--    CXX: /usr/bin/clang++  -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors -Wno-error=parentheses-equality -O2 -g -DNDEBUG
--    LD: /usr/bin/ld
--  Targets:
-- [X]   polybar-msg
-- [ ]   testsuite
--  Module support:
-- [ ]   alsa
-- [X]   curl
-- [ ]   i3
-- [ ]   mpd
-- [X]   network
-- [X]   pulseaudio
--  X extensions:
-- [X]   xcb-randr
-- [X]   xcb-randr (monitor support)
-- [ ]   xcb-render
-- [ ]   xcb-damage
-- [ ]   xcb-sync
-- [ ]   xcb-composite
-- [X]   xcb-xkb
-- [X]   xcb-xrm
-- [X]   xcb-cursor
-- Font not found: fixed:pixelsize=10
-- Font not found: unifont:fontformat=truetype
-- Font not found: siji:pixelsize=10
-- Checking for module 'xcb-proto'
--   Found xcb-proto, version 1.12
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.14", minimum required is "2.7")
-- XCB[XCB]: Found component XCB
-- Found XCB_XCB: /usr/lib/libxcb.so
-- XCB[ICCCM]: Found component ICCCM
-- Found XCB_ICCCM: /usr/lib/libxcb-icccm.so
-- XCB[EWMH]: Found component EWMH
-- Found XCB_EWMH: /usr/lib/libxcb-ewmh.so
-- XCB[UTIL]: Found component UTIL
-- Found XCB_UTIL: /usr/lib/libxcb-util.so
-- XCB[IMAGE]: Found component IMAGE
-- Found XCB_IMAGE: /usr/lib/libxcb-image.so
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so
-- Searching for xcbgen with python2
-- Searching for xcbgen with python2.7
-- Searching for xcbgen with python3
-- Found xcbgen in /usr/lib/python3.6/site-packages
-- XCB[RANDR]: Found component RANDR
-- Found XCB_RANDR: /usr/lib/libxcb-randr.so
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so;/usr/lib/libxcb-randr.so
-- XCB[XKB]: Found component XKB
-- Found XCB_XKB: /usr/lib/libxcb-xkb.so
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so;/usr/lib/libxcb-randr.so;/usr/lib/libxcb-xkb.so
-- xpp: including xcb proto randr.xml
-- xpp: including xcb proto xkb.xml
-- xpp: including xcb proto xproto.xml
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jon/dev/others/polybar/build
** Building project
Scanning dependencies of target xpp
[  1%] Linking CXX static library libxpp.a
[  4%] Built target xpp
Scanning dependencies of target polybar-msg
[  6%] Building CXX object bin/CMakeFiles/polybar-msg.dir/ipc.cpp.o
[  7%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/env.cpp.o
[  8%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/file.cpp.o
[  9%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/string.cpp.o
[ 10%] Linking CXX executable polybar-msg
[ 10%] Built target polybar-msg
Scanning dependencies of target polybar
[ 12%] Building CXX object bin/CMakeFiles/polybar.dir/adapters/net.cpp.o
[ 13%] Building CXX object bin/CMakeFiles/polybar.dir/adapters/pulseaudio.cpp.o
[ 14%] Building CXX object bin/CMakeFiles/polybar.dir/cairo/utils.cpp.o
[ 15%] Building CXX object bin/CMakeFiles/polybar.dir/components/bar.cpp.o
[ 17%] Building CXX object bin/CMakeFiles/polybar.dir/components/builder.cpp.o
[ 18%] Building CXX object bin/CMakeFiles/polybar.dir/components/command_line.cpp.o
[ 19%] Building CXX object bin/CMakeFiles/polybar.dir/components/config.cpp.o
[ 20%] Building CXX object bin/CMakeFiles/polybar.dir/components/controller.cpp.o
[ 21%] Building CXX object bin/CMakeFiles/polybar.dir/components/ipc.cpp.o
[ 23%] Building CXX object bin/CMakeFiles/polybar.dir/components/logger.cpp.o
[ 24%] Building CXX object bin/CMakeFiles/polybar.dir/components/parser.cpp.o
[ 25%] Building CXX object bin/CMakeFiles/polybar.dir/components/renderer.cpp.o
[ 26%] Building CXX object bin/CMakeFiles/polybar.dir/components/screen.cpp.o
[ 28%] Building CXX object bin/CMakeFiles/polybar.dir/components/taskqueue.cpp.o
[ 29%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/animation.cpp.o
[ 30%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/iconset.cpp.o
[ 31%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/label.cpp.o
[ 32%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/progressbar.cpp.o
[ 34%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/ramp.cpp.o
[ 35%] Building CXX object bin/CMakeFiles/polybar.dir/events/signal_emitter.cpp.o
[ 36%] Building CXX object bin/CMakeFiles/polybar.dir/events/signal_receiver.cpp.o
[ 37%] Building CXX object bin/CMakeFiles/polybar.dir/main.cpp.o
[ 39%] Building CXX object bin/CMakeFiles/polybar.dir/modules/alsa.cpp.o
[ 40%] Building CXX object bin/CMakeFiles/polybar.dir/modules/backlight.cpp.o
[ 41%] Building CXX object bin/CMakeFiles/polybar.dir/modules/battery.cpp.o
[ 42%] Building CXX object bin/CMakeFiles/polybar.dir/modules/bspwm.cpp.o
[ 43%] Building CXX object bin/CMakeFiles/polybar.dir/modules/counter.cpp.o
[ 45%] Building CXX object bin/CMakeFiles/polybar.dir/modules/cpu.cpp.o
[ 46%] Building CXX object bin/CMakeFiles/polybar.dir/modules/date.cpp.o
[ 47%] Building CXX object bin/CMakeFiles/polybar.dir/modules/fs.cpp.o
[ 48%] Building CXX object bin/CMakeFiles/polybar.dir/modules/github.cpp.o
[ 50%] Building CXX object bin/CMakeFiles/polybar.dir/modules/ipc.cpp.o
[ 51%] Building CXX object bin/CMakeFiles/polybar.dir/modules/memory.cpp.o
[ 52%] Building CXX object bin/CMakeFiles/polybar.dir/modules/menu.cpp.o
[ 53%] Building CXX object bin/CMakeFiles/polybar.dir/modules/meta/base.cpp.o
[ 54%] Building CXX object bin/CMakeFiles/polybar.dir/modules/network.cpp.o
[ 56%] Building CXX object bin/CMakeFiles/polybar.dir/modules/pulseaudio.cpp.o
[ 57%] Building CXX object bin/CMakeFiles/polybar.dir/modules/script.cpp.o
[ 58%] Building CXX object bin/CMakeFiles/polybar.dir/modules/systray.cpp.o
[ 59%] Building CXX object bin/CMakeFiles/polybar.dir/modules/temperature.cpp.o
[ 60%] Building CXX object bin/CMakeFiles/polybar.dir/modules/text.cpp.o
[ 62%] Building CXX object bin/CMakeFiles/polybar.dir/modules/xbacklight.cpp.o
[ 63%] Building CXX object bin/CMakeFiles/polybar.dir/modules/xkeyboard.cpp.o
[ 64%] Building CXX object bin/CMakeFiles/polybar.dir/modules/xwindow.cpp.o
[ 65%] Building CXX object bin/CMakeFiles/polybar.dir/modules/xworkspaces.cpp.o
[ 67%] Building CXX object bin/CMakeFiles/polybar.dir/utils/bspwm.cpp.o
[ 68%] Building CXX object bin/CMakeFiles/polybar.dir/utils/command.cpp.o
[ 69%] Building CXX object bin/CMakeFiles/polybar.dir/utils/concurrency.cpp.o
[ 70%] Building CXX object bin/CMakeFiles/polybar.dir/utils/env.cpp.o
[ 71%] Building CXX object bin/CMakeFiles/polybar.dir/utils/factory.cpp.o
[ 73%] Building CXX object bin/CMakeFiles/polybar.dir/utils/file.cpp.o
[ 74%] Building CXX object bin/CMakeFiles/polybar.dir/utils/http.cpp.o
[ 75%] Building CXX object bin/CMakeFiles/polybar.dir/utils/inotify.cpp.o
[ 76%] Building CXX object bin/CMakeFiles/polybar.dir/utils/io.cpp.o
[ 78%] Building CXX object bin/CMakeFiles/polybar.dir/utils/process.cpp.o
[ 79%] Building CXX object bin/CMakeFiles/polybar.dir/utils/socket.cpp.o
[ 80%] Building CXX object bin/CMakeFiles/polybar.dir/utils/string.cpp.o
[ 81%] Building CXX object bin/CMakeFiles/polybar.dir/utils/throttle.cpp.o
[ 82%] Building CXX object bin/CMakeFiles/polybar.dir/x11/atoms.cpp.o
[ 84%] Building CXX object bin/CMakeFiles/polybar.dir/x11/connection.cpp.o
[ 85%] Building CXX object bin/CMakeFiles/polybar.dir/x11/cursor.cpp.o
[ 86%] Building CXX object bin/CMakeFiles/polybar.dir/x11/ewmh.cpp.o
[ 87%] Building CXX object bin/CMakeFiles/polybar.dir/x11/extensions/randr.cpp.o
[ 89%] Building CXX object bin/CMakeFiles/polybar.dir/x11/extensions/xkb.cpp.o
[ 90%] Building CXX object bin/CMakeFiles/polybar.dir/x11/icccm.cpp.o
[ 91%] Building CXX object bin/CMakeFiles/polybar.dir/x11/registry.cpp.o
[ 92%] Building CXX object bin/CMakeFiles/polybar.dir/x11/tray_client.cpp.o
[ 93%] Building CXX object bin/CMakeFiles/polybar.dir/x11/tray_manager.cpp.o
[ 95%] Building CXX object bin/CMakeFiles/polybar.dir/x11/window.cpp.o
[ 96%] Building CXX object bin/CMakeFiles/polybar.dir/x11/winspec.cpp.o
[ 97%] Building CXX object bin/CMakeFiles/polybar.dir/x11/xembed.cpp.o
[ 98%] Building CXX object bin/CMakeFiles/polybar.dir/x11/xresources.cpp.o
[100%] Linking CXX executable polybar
</pre>
</details>

**Comment by patrick96** [comment]
This was just fixed a few minutes before you posted this. Please pull the latest commit.
