### ISSUE TITLE
i3 module disabled

### ISSUE THREAD

**Issue by lte246** [jaagr/polybar#1034]
I have polybar running smoothly, but I can't get the i3 module to load.
Whenever i run my bar i get the message
`error: Disabling module "i3" (reason: Missing parameter "module/i3.type")`

I'm running i3-gaps on arch
I had i3 on the system before polybar, have i3ipc-glib-git installed and I compiled polybar-git from the AUR with `-DENABLE_I3=ON`

It seems to be enabled
`polybar -v` gives me
`polybar 3.1.0-62-g0fd614b
Features: +alsa +curl +i3 -mpd +network +pulseaudio`

**Comment by patrick96** [comment]
You're missing `type = internal/i3` in your i3 module

**Comment by lte246** [comment]
haha damn, don't config drunk, ty though
