### ISSUE TITLE
Stats information are not displayed

### ISSUE THREAD

**Issue by commoner1945** [jaagr/polybar#1039]
Apologize for posting the issue here because I don't find forum like link on README page.

I follow wiki https://github.com/jaagr/polybar/wiki configuring polybar. However after launching polybar only displays sound adjustment icon. Other information are missed. It looks like picture at https://imgur.com/a/IQa67

Check by executing in console, only following error message get printed.
```
warn: No monitor specified, using "eDP-1"
error: Disabling module "bspwm" (reason: Could not find socket: /tmp/bspwm_0_0-socket)
error: module/mpd: Connection refused
error: module/xbacklight: Could not get data (err: XCB_NAME (15))
error: Disabling module "xbacklight" (reason: Not supported for "eDP-1")
warn: pulseaudio: using default sink alsa_output.pci-0000_00_1f.3.analog-stereo
error: module/mpd: Connection refused

```
OS is Debian version 9 with netinstall (TUXEDO InfinityBook Pro 13 v3). How can I fix this problem? Thanks

**Comment by patrick96** [comment]
You should definitely check out the [Font Wiki page](https://github.com/jaagr/polybar/wiki/Fonts), it seems like most of your icons are missing. A lot of your modules are getting disabled because they're either set up wrong or just don't work with your system. Have a look at the wiki pages for those modules, and either remove them, if you don't need them, or learn how to configure them correctly.

**Comment by commoner1945** [comment]
Following steps basically help display font, characters on my polybar panel. 

1. List fonts available by `fc-list`
2. Find related font format (string after **/path/to/font_name.ttf:** ) can be used in polybar config file (~/.config/polybar/config) by `fc-list | grep -i <font name>`

    /usr/share/fonts/truetype/freefont/FreeMono.ttf: FreeMono:style=Regular...
    /usr/share/fonts/truetype/msttcorefonts/andalemo.ttf: Andale Mono:style=Regular,Normal...

3. Replace or append to the font-{N} (where N is 0, 1, ...) list in the config file with format found in the second step. For instance, 

    font-0 = FontAwesome:style=Regular;1
    font-1 = FreeMono:style=Bold,...;0

Thanks for help!
