### ISSUE TITLE
Polybar drops some Unicode characters but not others

### ISSUE THREAD

**Issue by Montessquio** [jaagr/polybar#1042]
Polybar is dropping the following "unmatched characters" ▃ ▄ ▆ █ (u+2588, u+2585, etc) but not dropping other characters like the em dash or vertical line.

How to reproduce: Attempt to display one of the following characters in polybar: ▃ ▄ ▆ █ May also happen with similar bar characters.

Error in the terminal, which repeats until program termination:
```
warn: Dropping unmatched character ▂ (U+2582)
warn: Dropping unmatched character ▃ (U+2583)
warn: Dropping unmatched character ▅ (U+2585)
warn: Dropping unmatched character ▆ (U+2586)
warn: Dropping unmatched character ▂ (U+2582)
warn: Dropping unmatched character ▃ (U+2583)
warn: Dropping unmatched character ▅ (U+2585)
warn: Dropping unmatched character ▆ (U+2586)
```
Relevant Polybar Config:
```
font-0 = fixed:pixelsize=10;1
font-1 = "Unifont CSUR:fontformat=truetype:size=8:antialias=false;0"
font-2 = "Wuncon Siji:pixelsize=10;"

[module/wlan]
type = internal/network
interface = wlp2s0b1
interval = 3.0

format-connected = <ramp-signal> <label-connected>
format-connected-underline = #9f78e1
label-connected = %essid%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

ramp-signal-0 = "▂" 
ramp-signal-1 = "▂▃"
ramp-signal-2 = "▂▃▅"
ramp-signal-3 = "▂▃▅▆"
ramp-signal-4 = "▂▃▅▆█" 
amp-signal-foreground = ${colors.foreground-alt}
```
Other unicode symbols work fine, such as the full width vertical line ｜ (u+FF5C), it just seems to be these specific blocks.

fc-list confirms I have the appropriate fonts installed:

```
$ fc-list | grep CSUR   
/usr/share/fonts/TTF/Unifont_CSUR.ttf: Unifont CSUR:style=Medium
```
and
```
$ fc-list | grep siji 
/usr/share/fonts/misc/siji.pcf: Wuncon Siji:style=Regular
```

Here is my system information, if needed:
```
 Macbook Pro Mid-2012 (Only running Arch)
 OS: Arch Linux 
 Kernel: x86_64 Linux 4.15.3-2-ARCH
 Shell: zsh 5.4.2
 Resolution: 1280x800
 WM: i3
 CPU: Intel Core i5-3210M @ 4x 3.1GHz
```
Finally, the unicode characters in question *do* render correctly in urxvt/vim as well as my browser (firefox).

Thank you in advance for the support.

**Comment by patrick96** [comment]
You're missing the font these characters belong to, see [Debugging Font Issues](https://github.com/jaagr/polybar/wiki/Fonts#debugging-font-issues)
