### ISSUE TITLE
warn: Dropping unmatched character ─ (U+2500)

### ISSUE THREAD

**Issue by angarod** [jaagr/polybar#1043]
All my fonts are loaded properly, 
`Loaded font "mono:pixelsize=11,1" (name=Bitstream Vera Sans Mono, offset=0, file=/usr/share/fonts/TTF/VeraMono.ttf)`
`Loaded font "unifont:fontformat=truetype:size=9:antialias=false,0" (name=Bitstream Vera Sans, offset=0, file=/usr/share/fonts/TTF/Vera.ttf)`
`Loaded font "Wuncon Siji:pixelsize=11,1" (name=Wuncon Siji, offset=0, file=/usr/share/fonts/misc/siji.pcf)`

But polybar cannot display the U+2500 unicode character.

archlinux
polybar 3.1.0
Features: +alsa +curl +i3 +mpd +network

Using polybar for months without issues and experienced this last week end
Any help ?

**Comment by patrick96** [comment]
Unifont didn't load properly. Try capitalizing it

**Comment by angarod** [comment]
I capitalized "unifont", it didn't work. It's very strange because in gucharmap the font Bitstream Vera Sans have the U+2500 character

**Comment by patrick96** [comment]
Did you select `Show only glyphs from this font` in gucharmap? If not gucharmap will show the character, if it is contained in any font

**Comment by angarod** [comment]
you're right, i didn't select this option, and this font doesn't have the U+2500 character. So what font i should load in order to have this character ?

**Comment by patrick96** [comment]
When you deselect `Show only glyphs from this font` and hold right click on the icon, it should tell you which font has it. It's in unifont, you probably just don't have it installed

**Comment by angarod** [comment]
Installed and configured, now it works. Sorry for this stupid mistake.
Thanks for your time. :)
