### ISSUE TITLE
Volume/Backlight bar label not showing

### ISSUE THREAD

**Issue by ssaltwick** [jaagr/polybar#1044]
The volume and backlight sliders no longer show on my polybar setup. I can still scroll on them to change the values, but the bar does not appear. Under [module/backlight] I have 

`format = <label><bar>`

and under [module/volume] I have

`<label-volume> <bar-volume>`
Neither of these bars are showing up in my polybar even though they are clearly defined in the config.

**Comment by ssaltwick** [comment]
When I restart polybar via

`killall polybar & polybar bar`

this is the output:

```
warn: No monitor specified, using "eDP1"
warn: pulseaudio: using default sink alsa_output.pci-0000_00_1f.3.analog-stereo
warn: Dropping unmatched character ─ (U+2500)
warn: Dropping unmatched character ─ (U+2500)
warn: Dropping unmatched character ─ (U+2500)
warn: Dropping unmatched character ─ (U+2500)
warn: Dropping unmatched character ─ (U+2500)
```

**Comment by patrick96** [comment]
Something changed about your fonts, have a look at the font wiki page for
how to fix the unmatched character warnings

**Comment by Morganamilo** [comment]
The default polybar config has `font-0 = fixed:pixelsize=10;1`. It appears that `fc-match fixed` resolves to a different font than it used to. Manually changing from fixed to `DejaVuSans` fixes it.

**Comment by ssaltwick** [comment]
My config did not have DejaVuSans as a font. Adding it fixed this, thank you!
