### ISSUE TITLE
Cant run polybar

### ISSUE THREAD

**Issue by TPSC** [jaagr/polybar#1045]
Hello
I installed polybar from sources, and can't run

I used this config to run and test polybar
https://github.com/jaagr/polybar/blob/master/doc/config.cmake

aaaand this is it
"[adam@LNXLAP5 polybar]$ ./launch.sh 
Bars launched...
warn: No monitor specified, using "LVDS1"
error: Disabling module "@MODULES_LEFT@" (reason: Missing parameter "module/@MODULES_LEFT@.type")
error: Disabling module "@MODULES_CENTER@" (reason: Missing parameter "module/@MODULES_CENTER@.type")
error: Disabling module "@MODULES_RIGHT@" (reason: Missing parameter "module/@MODULES_RIGHT@.type")
error: No modules created

"

Linux gentoo, i3

**Comment by patrick96** [comment]
That's the wrong config. The right one is the one at 'doc/config' (this
file is generated, after you ran make), you can install it by calling 'make
userconfig'

**Comment by TPSC** [comment]
Thank  you, it works
