### ISSUE TITLE
Wireless Icon Sometimes Disappear

### ISSUE THREAD

**Issue by rusmelezi** [jaagr/polybar#1053]
I tried everything but still it is...

My config:  https://www.paste.org/91375

All fonts are working without any problems I checked several times.

**Comment by patrick96** [comment]
Can you also please the whole output of the polybar command.

**Comment by rusmelezi** [comment]
Yes sir, 

> error: module/backlight: Could not get data (err: XCB_NAME (15))
> error: Disabling module "backlight" (reason: Not supported for "eDP-1")
> error: Disabling module "wired-network" (reason: Invalid network interface "net0")
> error: Disabling module "battery" (reason: No suitable way to get current charge state)
> warn: Systray selection already managed (window=0x280000c)

**Comment by patrick96** [comment]
Is this the whole output *while* the wireless icon disappeared?

Btw, you also have the wrong interface set for your wired module

**Comment by rusmelezi** [comment]
I'll wait until wireless icon disappeared and post again. I don't get it what you mean at first sorry.

**Comment by rusmelezi** [comment]
Deleted ping-interval and problem solved
