### ISSUE TITLE
mpd module not updating

### ISSUE THREAD

**Issue by SuperPrower** [jaagr/polybar#1055]
```
[module/mpd]
type = internal/mpd

host = 127.0.0.1
port = 6600
password =

interval = 2

label-song-maxlen = 72

format-online =  <label-song>
format-playing-underline = ${colors.underline}
label-offline =  mpd is offline
```

```
]$ polybar -vvv
polybar 3.1.0-64-g4f6e374

Features: +alsa +curl +i3 +mpd +network +pulseaudio

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

I use Mopidy as my server.

Status, i.e. playing/paused, track name doesn't update and stay like that until I restart polybar. Polybar binary doesn't seem to say anything about this module - it just freezes like that.

Also, not configured here, but clicking on shuffle label seemed to cause huuge problems with my player ncmpcpp - it can't enable/disable shuffle mode anymore. Pressing pause (<toggle>) seemed to be very delayed.

**Comment by patrick96** [comment]
Do other modules still update (like the date module)? The pause button still works in polybar, even if the module is frozen.

**Comment by SuperPrower** [comment]
Hm, I have restarted Mopidy, because ncmpcpp also started acting weird, and problem seems to go away. I suspect it has something to do with Polybar's interaction with MPD - will try to add pause button back and click it, or do something else.

**Comment by SuperPrower** [comment]
So yeah, it has something to do with clickability of the module. I checked output of mopidy - it keeps getting incoming connections from local machine every few seconds, even after polybar hanged.

Here is proper steps to re-produce issue:

1. Have `<toggle>` and `<icon-random>` in `format-online`
2. (use mopidy as mpd server? is it causing the issue?)
3. tap random icon to enable random mode. It is reflected in ncmpcpp.
4. tap random icon again. nothing happens. (optional?)
5. tap pause button. Music pauses. Polybar module doesn't change at all. Everything else - time and stuff - keeps working.
6. tap (still) pause button. Nothing happens.
7. go to ncmpcpp and un-pause music. Nothing happens in Polybar module.
8. tap pause button. Music pauses.
9. restart polybar. mpd module now reflects current state of a music: pause button was replaced with play button. Pressing play button starts music, but polybar module doesn't change.

**Comment by patrick96** [comment]
Alright, so polybar stops outputting stuff, but the buttons still work.
I suspect, polybar hangs when tapping the 'random' button.
Can you try to see, if this happens, when you tap other buttons instead of 'random' 
`<icon-prev> <icon-stop> <icon-next> <icon-repeat>`

Also please run polybar with the `-l trace` flag while you're doing this and post the whole output here. (You may need to recompile polybar and add `-DCMAKE_BUILD_TYPE=Debug` to the `cmake` command to enable trace logging)

**Comment by SuperPrower** [comment]
With 'repeat' button it's a little different. It kinda worked - it changed color, but after I tapped it again, repeat status wasn't removed in player. Also some kind of delay appeared. When I pressed pause button, it hanged again - I could resume playing, but mpd module stopped updating.

About logging - sure, give me some time.

**Comment by denied404** [comment]
The same problem here: mopidy with `internal/mpd` module of polybar:
Each control button works, but the `artist-song` label sometimes stays unchanged.

**Comment by zj2423651950** [comment]
该mpd模块在显示歌曲信息时，无法显示中文，有解决方法吗

**Comment by SuperPrower** [comment]
@zj2423651950 I used google translate to translate your question. I have same problem with japanese symbols, but I suspect this is because neither of my fonts have them. Anyway, it's better to create new issue for this problem - this one discusses different issue.

**Comment by patrick96** [comment]
@SuperPrower any update on the logs?

**Comment by SuperPrower** [comment]
@patrick96 sorry, I was in the middle of midterms. 
Here is log. I started music, then I clicked 'random' button several times, then I paused music, then I started it again, after it, mpd module hanged. I only had i3 and mpd modules for this test. Unfortunately, I can't pinpoint exact locations of 'clicks' in log, but I hope it'll help:
```
* Loading config: /home/superprower/.config/polybar/config
- config: Current bar section: [bar/mpd_test]
* Loaded monitor eDP1 (1920x1080+0+0)
* Found matching X resource "background" (value=#2E3440)
* Found matching X resource "foreground" (value=#D8DEE9)
* Found matching X resource "color0" (value=#3B4252)
* Bar geometry: 1920x45+0+1035
- bar: Attach X event sink
- bar: Attach signal receiver
- controller: Install signal handler
- controller: Setup user-defined modules
* Found matching X resource "color4" (value=#81A1C1)
* Found matching X resource "color4" (value=#81A1C1)
* Found matching X resource "color4" (value=#81A1C1)
- mpdconnection.connect: 127.0.0.1, 6600, "", timeout: 15
* Starting application
- controller: Main thread id = 1
* Starting module/i3
* Starting module/mpd
- module/mpd: Thread id = 2
* Entering event loop (thread-id=1)
- controller: Attach config watch
* Eventqueue worker (thread-id=3)
- bar: Create renderer
- renderer: Get TrueColor visual
- renderer: Allocate colormap
- renderer: Allocate output window
- module/i3: Thread id = 4
- renderer: Allocate window pixmaps
- renderer: Allocate graphic contexts
- renderer: Allocate alignment blocks
- renderer: Allocate cairo components
- renderer: Load fonts
* Configured DPI = 120x120
* Loaded font "xos4terminus:size=14" (name=xos4 Terminus, offset=2, file=/usr/share/fonts/misc/ter-x14n.pcf.gz)
* Loaded font "FontAwesome:size=10" (name=FontAwesome, offset=2, file=/usr/share/fonts/TTF/fontawesome-webfont.ttf)
* Loaded font "xos4terminus:size=24:weight=bold" (name=xos4 Terminus, offset=2, file=/usr/share/fonts/misc/ter-x24b.pcf.gz)
* Loaded font "Material Design Icons:size=13" (name=Material Design Icons, offset=2, file=/usr/share/fonts/TTF/MaterialDesignIcons.ttf)
* Bar window: 0x4200002
- bar: Reconfigure window
- bar: Set window WM_NAME
- bar: Set window _NET_WM_WINDOW_TYPE
- bar: Set window _NET_WM_STATE
- bar: Set window _NET_WM_DESKTOP
- bar: Set window _NET_WM_PID
- bar: Map window
- bar: Draw empty bar
- bar: Setup tray manager
* Disabling tray manager (reason: missing `tray-position`)
* module/i3: Rebuilding cache
* module/mpd: Rebuilding cache
- bar: Force update
* Redrawing bar window
- bar: Received expose event
- renderer: flush(1 geom=715x42+0+0, falloff=0)
- bar: Received button press: 1 at pos(252, 22)
- Found matching input area
- mpdconnection.connect: 127.0.0.1, 6600, "", timeout: 15
* module/mpd: Rebuilding cache
* Redrawing bar window
- renderer: flush(1 geom=715x42+0+0, falloff=0)
* module/mpd: Rebuilding cache
- bar: Ignoring update (unchanged)
* module/mpd: Rebuilding cache
- bar: Ignoring update (unchanged)
* module/mpd: Rebuilding cache
- bar: Ignoring update (unchanged)
- bar: Received button press: 1 at pos(320, 27)
- Found matching input area
- mpdconnection.connect: 127.0.0.1, 6600, "", timeout: 15
* module/mpd: Rebuilding cache
* Redrawing bar window
- renderer: flush(1 geom=715x42+0+0, falloff=0)
* module/mpd: Rebuilding cache
- bar: Ignoring update (unchanged)
- bar: Received button press: 1 at pos(317, 26)
- Found matching input area
- mpdconnection.connect: 127.0.0.1, 6600, "", timeout: 15
* module/mpd: Rebuilding cache
* Redrawing bar window
- renderer: flush(1 geom=715x42+0+0, falloff=0)
* module/mpd: Rebuilding cache
- bar: Ignoring update (unchanged)
- bar: Received button press: 1 at pos(317, 26)
- Found matching input area
- mpdconnection.connect: 127.0.0.1, 6600, "", timeout: 15
* module/mpd: Rebuilding cache
* Redrawing bar window
- renderer: flush(1 geom=715x42+0+0, falloff=0)
* module/mpd: Rebuilding cache
- bar: Ignoring update (unchanged)
- bar: Received button press: 1 at pos(317, 26)
- Found matching input area
- mpdconnection.connect: 127.0.0.1, 6600, "", timeout: 15
* module/mpd: Rebuilding cache
* Redrawing bar window
- renderer: flush(1 geom=715x42+0+0, falloff=0)
- bar: Received button press: 1 at pos(245, 25)
- Found matching input area
- mpdconnection.connect: 127.0.0.1, 6600, "", timeout: 15
* module/mpd: Rebuilding cache
* Redrawing bar window
- renderer: flush(1 geom=715x42+0+0, falloff=0)
- bar: Received button press: 1 at pos(250, 26)
- Found matching input area
- mpdconnection.connect: 127.0.0.1, 6600, "", timeout: 15
- bar: Received button press: 1 at pos(310, 23)
- Found matching input area
- mpdconnection.connect: 127.0.0.1, 6600, "", timeout: 15
^C
warn: Termination signal received, shutting down...
- controller: Uninstall sighandler
- controller: Detach signal receiver
- controller: Stop modules
* module/i3: Disconnecting from socket
* module/i3: Stopping
- module/i3: Release sleep lock
- module/i3: Deconstructing
* Deconstruction of module/i3 took 1 ms.
* module/mpd: Stopping
- module/mpd: Release sleep lock
- module/mpd: Deconstructing
* Deconstruction of module/mpd took 0 ms.
- controller: Joining threads
* Waiting for spawned processes to end
* Reached end of application...
```

**Comment by patrick96** [comment]
So, I set up mopidy on my VM and was able to reproduce this. I don't think this is actually polybar's fault.

Having mopidy running in the terminal, I noticed that the following exception was thrown by mopidy, exactly as the polybar button stopped working:
```
ERROR    Unhandled exception in MpdFrontend (urn:uuid:abc157d0-a598-46ab-a711-949de6ec7c4d):
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/actor.py", line 84, in on_event
    self.send_idle(_CORE_EVENTS_TO_IDLE_SUBSYSTEMS[event])
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/actor.py", line 88, in send_idle
    listener.send(session.MpdSession, subsystem)
  File "/usr/lib/python2.7/site-packages/mopidy/listener.py", line 27, in send
    'kwargs': kwargs,
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 437, in tell
    raise _ActorDeadError('%s not found' % self)
    ActorDeadError: MpdSession (urn:uuid:feb3d781-13b2-4394-84be-afff630079df) not found
```

From there on, it was impossible to change the `random` setting with polybar or ncmpcpp (using `mpc` still works though), polybar still sends the correct commands to mpd but it somehow doesn't get accepted by mopidy (and also doesn't produce an error). That's why I believe that this is a mopidy bug rather than a polybar bug.

I'm going to close this, as there is nothing more to be done from our side. If you open a mopidy issue, please link it here.
