### ISSUE TITLE
Building under Debian Stretch

### ISSUE THREAD

**Issue by mietzen** [jaagr/polybar#1058]
I've successfully build polybar 3.1 from source under:
Debian Stretch Stable Kernel 4.9.82-1+deb9u2 (2018-02-21) x86_64 GNU/Linux
using the following command (since GetDeb won't work for me):

git clone --branch 3.1.0 --recursive https://github.com/jaagr/polybar
mkdir polybar/build
cd polybar/build
sudo apt-get install python-xcbgen libxcb-icccm4-dev libxcb1-dev xcb-proto libxcb-image0-dev libxcb-randr0-dev libalsaplayer-dev wireless-tools libcurlpp-dev  libcairo2-dev libjsoncpp-dev libxcb-util0-dev libxcb-xkb-dev libxcb-ewmh-dev cmake
cmake ..
sudo make install

**Comment by patrick96** [comment]
Thanks for reporting. Most packages were already in the [Compiling](https://github.com/jaagr/polybar/wiki/Compiling), I have added the libjsoncpp and libcurlpp ones to the list
