### ISSUE TITLE
bspwm: Hide emtpy workspaces

### ISSUE THREAD

**Issue by binaryplease** [jaagr/polybar#1061]
Hello,
I haven't found a way to hide empty workspaces in bspwm. The i3 module does that.
Is there a way to configure that in the bspwm module?
The empty workspaces are "grayed out" in the default bspwm module config, I would like to hide those altogether.

Thanks,

Pablo

**Comment by binaryplease** [comment]
Nevermind,  found the solution:
Setting

`label-empty =
`
to an empty string does the trick.

**Comment by ChuckD3ath** [comment]
Hey can you please put an example of how you did it? I want to do it but not really sure what to do with ''label-empty".
Thanks!

**Comment by Lomadriel** [comment]
You just have to add `label-empty = ` under the config of the bspwm module.
See https://github.com/polybar/polybar/wiki/Module:-bspwm for more information.

Please note that the issue tracker isn't a place to ask information, see https://github.com/polybar/polybar/blob/master/SUPPORT.md
You have better chance to have an answer on reddit/the IRC/… than here.
