### ISSUE TITLE
Variables inside %{F}

### ISSUE THREAD

**Issue by Yatekii** [jaagr/polybar#1062]
Hi!

Can I make this work as in here:  %essid% %{F${colors.gren}}%{F-} %signal%% %{F${colors.gren}} %{F-} %upspeed% %{F${colors.gren}}%{F-} %downspeed% %{F${colors.gren}}%{F-} %local_ip%

Atm this will fail. Is there a way to do this, other than environment variables?

Best, Yatekii

**Comment by patrick96** [comment]
No, for now a `${...}` reference has to be alone inside a parameter defintion, so you'll have to use an environment variable containing the whole string.
