### ISSUE TITLE
polybar-msg -p $pid cmd show multi-monitors bug

### ISSUE THREAD

**Issue by Berjou** [jaagr/polybar#1066]
Hi,

I have the following setup:

- 2 bars by monitor (top and bottom)
- 2 monitors

To launch my bars on the good monitor, I use the environment variable MONITOR.

My bar config is:

```
[bar/abstract]
monitor = ${env:MONITOR:}
width = 100%
height = 20
radius = 0
fixed-center = false

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 0
border-size = 0

padding-left = 0
padding-right = 2

module-margin-left = 1
module-margin-right = 2

font-0 = Monaco:size=8;0
font-1 = Hack:fontformat=truetype:size=8;0
font-2 = FontAwesome:pixelsize=8;0
font-3 = WunconSiji:pixelsize=8;0
font-4 = fixed:pixelsize=8;0
font-5 = unifont:fontformat=truetype:size=8:antialias=false;0
font-6 = DejaVu Sans:size=8;0

tray-position = right
tray-padding = 2

cursor-click = pointer
cursor-scroll = ns-resize

[bar/bottom]
inherit = bar/abstract

bottom = true

modules-left = i3
modules-right = fs_root fs_data load-average memory cpu temperature vpn wlan xbacklight volume battery date

[bar/top]
inherit = bar/abstract

enable-ipc = true

modules-left = updates-arch updates-arch-timer
modules-center = mpd
```

And there is my launch.sh:

```
#!/bin/sh

killall -q polybar
rm /tmp/polybar.pids

while pgrep -u $UID -x polybar > /dev/null; do sleep 1; done

for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
  MONITOR=$m polybar --reload bottom &
  MONITOR=$m polybar --reload top &
  echo "$!" >> /tmp/polybar.pids
done
```

This works well.

However, I try to write scripts that can dynamically hide and show my top bars using ipc and `polybar-msg`.

The following script works as intented, hiding the top bars on my 2 monitors:

```
#!/bin/sh

while IFS='' read -r pid; do
  polybar-msg -p $pid cmd hide
done < /tmp/polybar.pids
```

However, this one is buggy:

```
#!/bin/sh

while IFS='' read -r pid; do
  polybar-msg -p $pid cmd show
done < /tmp/polybar.pids
```

This shows the 2 bars, but on the same monitor, not one on each monitor.

I tried to hardcode the monitor in the config rather than getting it from the environment, but nothing changed.

Is there any way to achieve that, hide and show a bar without losing its associated monitor?

**Comment by NBonaparte** [comment]
Does hiding and showing work individually (with only one bar running)?

**Comment by Berjou** [comment]
Yes, the only problem is the fact that with multiple monitors, when sending the show command, the bars do not appear on their original monitor.

All the bars appear on the last connected display listed by xrandr.

**Comment by Berjou** [comment]
This is my xrandr output:

```
Screen 0: minimum 8 x 8, current 1920 x 1968, maximum 32767 x 32767
LVDS1 connected primary 1366x768+0+1200 (normal left inverted right x axis y axis) 340mm x 190mm
   1366x768      60.00*+
   1280x720      59.74  
   1024x768      60.00  
   1024x576      60.00    59.90    59.82  
   960x540       60.00    59.63    59.82  
   800x600       60.32    56.25  
   864x486       60.00    59.92    59.57  
   640x480       59.94  
   720x405       59.51    60.00    58.99  
   680x384       60.00  
   640x360       59.84    59.32    60.00  
DP1 disconnected (normal left inverted right x axis y axis)
HDMI1 connected 1920x1200+0+0 (normal left inverted right x axis y axis) 520mm x 320mm
   1920x1200     59.95*+
   1920x1080     60.00    50.00    59.94  
   1600x1200     60.00  
   1680x1050     59.88  
   1600x900      60.00  
   1280x1024     60.02  
   1440x900      59.90  
   1280x800      59.91  
   1280x720      60.00    50.00    59.94  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       60.00    59.94  
VGA1 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```

Even when launching only one bar on the LVDS1 monitor, when hiding and showing it, it appears on the HDMI1 monitor.

**Comment by patrick96** [comment]
I also have two monitors and this doesn't happen for me, so this appears to be an issue with how polybar interacts with either the WM or the X server. Can you run the bar that doesn't work properly manually with `-l trace`, `hide` and `show` it and then post the output of the `polybar` command here.

**Comment by patrick96** [comment]
Just tested this under i3 and i3 repositions the window when it appears again. You can fix this by setting `override-redirect = true`.

I don't really know, if we can do anything against that on the polybar side, because if `override-redirect` is set to `true`, the WM can always reposition the window, if it wants to. What do you think @NBonaparte?

**Comment by NBonaparte** [comment]
Yeah, this was what I was suspecting. I've seen and had numerous issues with i3 not respecting docking/struts/positioning in general, so we can't really avoid it except by using `override-redirect`.

**Comment by Berjou** [comment]
Thank you, that was it. Setting `override-redirect` to true fixed the problem for problem for me.
