### ISSUE TITLE
Installed polybar but doesn’t run(i3wm)

### ISSUE THREAD

**Issue by DrDonkey** [jaagr/polybar#1068]
I am using Manjaro Linux with i3-gaps as wm.
Installed polybar and did put `exec_always --no-startup-id ~/.config/polybar/launch.sh` to `~/.config/i3/config`
But nothing happens. I even tried bash `~/.config/polybar/launch.sh` but got the error as: 
`error: Failed to set foreground (reason: X resource "color7" not found (no fallback set))`
`Bars launched...`

But again nothing happens. Rebooting doesn’t have any effect.

edit: tried installing from aur too but nothing happens.

**Comment by patrick96** [comment]
There is an issue in your config file: `reason: X resource "color7" not found (no fallback set)` most likely you have a `${xrdb:color7}` somewhere and have not set `color7` in `.Xresources`

**Comment by DrDonkey** [comment]
And what am I supposed to do here?

**Comment by DrDonkey** [comment]
I know I am dumb. I got it finally. Defined a bunch of colours in .Xresources and is cool now.
