### ISSUE TITLE
[Feature Request] Access colour of any module element.

### ISSUE THREAD

**Issue by NamedKitten** [jaagr/polybar#1069]
I think a way for you to access the colour of a element such as a animated bar or ramp would be a nice feature.
Then you could have, for example, RAM usage ramp with label same colour as ramp.
Would be nice to have.

**Comment by patrick96** [comment]
You can already reference any value of any section in your config with `key = ${section.key}`, see [Wiki](https://github.com/jaagr/polybar/wiki/Configuration)
