### ISSUE TITLE
System tray does not always appear on primary monitor

### ISSUE THREAD

**Issue by HactarCE** [jaagr/polybar#1070]
When I start my computer or restart Polybar, my system tray appears appears seemingly randomly on one of my two bars. (I have a bar at the bottom of each monitor.) Ultimately, I'd like the tray icons to consistently appear only on my primary monitor (HDMI-0 in the `xrandr` output).

[Here are my Polybar files and xrandr output.](https://gist.github.com/HactarCE/0e9ec8209e416d0475a5eaa70d893f19)

**Comment by patrick96** [comment]
If both bars want to display the tray, then it is first come, first served, whichever bar first tries to acquire the tray will get it. So either make sure that one bar will *always* first fully start up and acquire the tray, or remove the `tray-position` key from the bar where you *don't* want the tray to appear

**Comment by HactarCE** [comment]
Thanks. I wrote a script to pass the tray position as an environment variable (like `MONITOR`) and then used `tray-position = ${env:TRAY_POS}`.

**Comment by g3n35i5** [comment]
I'm not quite sure how your script works, I can't use e.g. "eDP-1" as tray-position variable but only {left, right, ...}.
The "first come first serve" principle is correct so far, but I noticed that loading the tray seems to be asynchronous. For this reason I have adapted my script to always display the tray on the primary monitor by waiting a second after loading the first bar on the primary monitor. For those who still have the same problem, this is the relevant section from my launch script:

```bash
BAR_NAME=main
BAR_CONFIG=/home/$USER/.config/polybar/config.ini

PRIMARY=$(xrandr --query | grep " connected" | grep "primary" | cut -d" " -f1)
OTHERS=$(xrandr --query | grep " connected" | grep -v "primary" | cut -d" " -f1)

# Launch on primary monitor
MONITOR=$PRIMARY polybar --reload -c $BAR_CONFIG $BAR_NAME &
sleep 1

# Launch on all other monitors
for m in $OTHERS; do
 MONITOR=$m polybar --reload -c $BAR_CONFIG $BAR_NAME &
done
```

**Comment by HactarCE** [comment]
@g3n35i5 `tray-position` is the position of the tray within a given bar (i.e. left side vs. right side), not the monitor whose bar has the tray. My script sets `TRAY_POS` to the desired value (either `left` or `right`) on the primary monitor, or an empty string on any other monitor (which disables the tray on that bar).

**Comment by g3n35i5** [comment]
@HactarCE Ahh, I got it, I got your post wrong. This is of course a more elegant solution, thank you very much!

**Comment by simpleauthority** [comment]
Sorry for gravedigging this but this issue came up in search results on Google. I liked @HactarCE's idea and was a bit disappointed to see the script wasn't shared. I'm not too excellent at bash-foo, but, here's what I came up with and it seems to work!

```bash
#!/bin/bash                                                                        
                                                                                   
# Terminate already running bars                                                   
killall -q polybar                                                                 
                                                                                   
# Launch new polybar(s)                                                            
if type "xrandr"; then                                                             
    IFS=$'\n'  # must set internal field separator to avoid dumb                   
    for entry in $(xrandr --query | grep " connected"); do                         
        mon=$(cut -d" " -f1 <<< "$entry")                                          
        status=$(cut -d" " -f3 <<< "$entry")                                       
                                                                                   
        tray_pos=""                                                                
        if [ "$status" == "primary" ]; then                                        
            tray_pos="right"                                                       
        fi                                                                         
                                                                                   
        MONITOR=$mon TRAY_POS=$tray_pos polybar -r topbar 2>&1 | tee -a /tmp/polyb\
ar-monitor-"$mon".log & disown                                                     
    done                                                                           
    unset IFS  # avoid mega dumb by resetting the IFS                              
else                                                                               
    polybar -r topbar 2>&1 | tee -a /tmp/polybar.log & disown                      
fi                                                                                 
                                                                                   
echo "Polybar launched..."
```

This should be able to detect the primary display with xrandr and set the tray position to "right" (change to "left" if needed) for that display and otherwise leave it empty.

If xrandr isn't detected for whatever reason it will just fall back to running a single polybar.

Then in the polybar config set your `tray_position =` to `${env:TRAY_POS:}`.
