### ISSUE TITLE
network monitor and link status

### ISSUE THREAD

**Issue by Celedhrim** [jaagr/polybar#1072]
Hi ,

I have compile polybar on debian testing up2date.
I have an issue I can't explain.

First my polybar : 

```
~$ polybar -v
polybar 3.1.0-67-g692e6d9

Features: -alsa +curl +i3 -mpd +network -pulseaudio
```

Next my ifconfig : 

```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.12.13.1  netmask 255.255.255.0  broadcast 10.12.13.255
        inet6 fe80::feaa:14ff:fe0e:8165  prefixlen 64  scopeid 0x20<link>
        ether fc:aa:14:0e:81:65  txqueuelen 1000  (Ethernet)
        RX packets 3757312  bytes 316276057 (301.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12232439  bytes 17755133968 (16.5 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.2.2  netmask 255.255.255.0  broadcast 192.168.2.255
        inet6 fe80::205:5dff:fe03:6e1a  prefixlen 64  scopeid 0x20<link>
        ether 00:05:5d:03:6e:1a  txqueuelen 1000  (Ethernet)
        RX packets 11767137  bytes 16934827321 (15.7 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6317911  bytes 457302570 (436.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

This machine is a gateway !
Lan behind eth0 and wan behind eth1

Now the issue : 

my polybar config

```
...
[module/wired-network]
type = internal/network
interface = eth0
interval = 3.0

label-connected = TOTO
label-disconnected = TITI
...
```

in the bar , TOTO is display.

Now I change eth0 to eth1 in config , now polybar display TOTO

How polybar guess an interface is connect or not ?

ethtool output : 

```
~# ethtool eth0 ; ethtool eth1
Settings for eth0:
	Supported ports: [ TP MII ]
	Supported link modes:   10baseT/Half 10baseT/Full 
	                        100baseT/Half 100baseT/Full 
	                        1000baseT/Half 1000baseT/Full 
	Supported pause frame use: No
	Supports auto-negotiation: Yes
	Advertised link modes:  10baseT/Half 10baseT/Full 
	                        100baseT/Half 100baseT/Full 
	                        1000baseT/Half 1000baseT/Full 
	Advertised pause frame use: Symmetric Receive-only
	Advertised auto-negotiation: Yes
	Link partner advertised link modes:  10baseT/Half 10baseT/Full 
	                                     100baseT/Half 100baseT/Full 
	                                     1000baseT/Half 1000baseT/Full 
	Link partner advertised pause frame use: Symmetric Receive-only
	Link partner advertised auto-negotiation: Yes
	Speed: 1000Mb/s
	Duplex: Full
	Port: MII
	PHYAD: 0
	Transceiver: internal
	Auto-negotiation: on
	Supports Wake-on: pumbg
	Wake-on: g
	Current message level: 0x00000033 (51)
			       drv probe ifdown ifup
	Link detected: yes
Settings for eth1:
	Supported ports: [ TP MII ]
	Supported link modes:   10baseT/Half 10baseT/Full 
	                        100baseT/Half 100baseT/Full 
	Supported pause frame use: No
	Supports auto-negotiation: Yes
	Advertised link modes:  10baseT/Half 10baseT/Full 
	                        100baseT/Half 100baseT/Full 
	Advertised pause frame use: No
	Advertised auto-negotiation: Yes
	Link partner advertised link modes:  10baseT/Half 10baseT/Full 
	                                     100baseT/Half 100baseT/Full 
	Link partner advertised pause frame use: Symmetric Receive-only
	Link partner advertised auto-negotiation: Yes
	Speed: 100Mb/s
	Duplex: Full
	Port: MII
	PHYAD: 8
	Transceiver: internal
	Auto-negotiation: on
	Supports Wake-on: pumbg
	Wake-on: d
	Current message level: 0x00000000 (0)
			       
	Link detected: yes
```
unfortunately I want to display eth1 up and down speed :)

thx for help !

**Comment by patrick96** [comment]
The code that checks if a wired interface is connected first checks if `/sys/class/net/INTERFACE_NAME/operstate` contains 'up' and then sends a `ETHTOOL_GLINK` request to the ethtool interface which checks if the interface and the physical port are up

```c
/usr/include/linux/ethtool.h
----------------------------
/* Get link status for host, i.e. whether the interface *and* the
 * physical port (if there is one) are up (ethtool_value). */
#define ETHTOOL_GLINK		0x0000000a
```

From the source code of [`ethtool`](https://www.kernel.org/pub/software/network/ethtool/) I gather that this is the same as checking if `Link detected: yes` appears in the output of `ethtool INTERFACE_NAME`, as it does for both of your interfaces.

I don't see what your problem is, polybar behaves as expected, since both of your interfaces are connected, if you want the up and down speeds of `eth1` then set `interface = eth1`

**Comment by Celedhrim** [comment]
Ok ! thx , so i look and eth1 operstate is .... unknow :(

As it is explained in Documentation/networking/operstates.txt in kernel sources:

IF_OPER_UNKNOWN (0):
 Interface is in unknown state, neither driver nor userspace has set
 operational state. Interface must be considered for user data as
 setting operational state has not been implemented in every driver.

I think polybar should assume UP if operstate is unknow no ?

**Comment by patrick96** [comment]
> Now I change eth0 to eth1 in config , now polybar display TOTO

I guess you meant to say it displays `TITI`?

Considering operstate unknown as up was already proposed in #457. I'm going to close this in favor of that issue.

**Comment by Celedhrim** [comment]
Yes , it say TITI , sorry :)

Ok for the other issue , thx for your time !
(the network card is an old dlink card , but working like a charm)

**Comment by Celedhrim** [comment]
Trying to compile after apply the changes from NBonaparte

Work like a charm !
