### ISSUE TITLE
No built-in support for 'internal/network' in Gentoo Linux

### ISSUE THREAD

**Issue by Maximilian73** [jaagr/polybar#1078]
I have a problem. I use Gentoo. The package of Gentoo is named wireless-tools instead wireless_tools. And I have (reason: No built-in support for 'internal/network')...

**Comment by patrick96** [comment]
My (now deleted) answer from #354:
polybar doesn't actually look for wireless_tools (or wireless_tools for that matter), it searches for libiw.so and iwlib.h, so make sure you have those files on your system and also that you built polybar after those files were installed.

**Comment by Maximilian73** [comment]
Thanks Patrick. But I did not find libiw.so or iwlib.h in my gentoo, although wireless-tools and net-wireless/iw was installed. I will deal with this. In everything else Polybar is excellent!!!

**Comment by patrick96** [comment]
I don't have a gentoo distro ready, so I pulled the sources from https://packages.gentoo.org/packages/net-wireless/wireless-tools and compiled it on my arch system and it generated the `libiw.so`. What files are installed by the `wireless-tools` package?

**Comment by Maximilian73** [comment]
In which folder is the file libiw.so in your Arch?

**Comment by Maximilian73** [comment]
/usr/lib64?

**Comment by patrick96** [comment]
For me its at `/usr/lib/libiw.so`

**Comment by Maximilian73** [comment]
I dont find libiw.so in /usr/lib or /usr/lib64

**Comment by patrick96** [comment]
Well it should be part of the `wireless-tools` package, so if you print the list of files provided by that package, you should be able to find it.

**Comment by Maximilian73** [comment]
Ok. I'll try to rebuild the `wireless-tools` package and polybar. Thank You!

**Comment by patrick96** [comment]
You should be able to list all files by `wireless-tools` with `equery f wireless-tools`

**Comment by patrick96** [comment]
I don't know how it works on gentoo, but on my system I use `systemctl poweroff` and because of polkit it doesn't prompt for a password. What command do you normally use in your terminal to shut down the computer w/o a password?

Does that mean, you were able to compile polybar with network support?

**Comment by Maximilian73** [comment]
I understood. You use systemd. I use openrc, they are different. I saw dotfiles with `systemctl poweroff`. In gentoo without systemd I use the command `poweroff` on admin and `sudo poweroff`, but with xfce on my other pc I dont have this problem on user profile.

**Comment by Maximilian73** [comment]
Many thanks, I'll think how to solve these problems.

**Comment by kajzersoze** [comment]
I'm on Gentoo as well and I have no problems with wireless-tools, internal/network is working fine.

```
$ eix wireless-tools                                                                                                                                                                                                              
[I] net-wireless/wireless-tools
     Available versions:  30_pre9 {multicall}
     Installed versions:  30_pre9(07:11:25 PM 02/07/2018)(-multicall)
     Homepage:            http://www.hpl.hp.com/personal/Jean_Tourrilhes/Linux/Tools.html
     Description:         A collection of tools to configure IEEE 802.11 wireless LAN cards

$ locate libiw.so                                                                                                                                                                                                              
/lib64/libiw.so
/lib64/libiw.so.30

```

**Comment by Maximilian73** [comment]
Yes, in /lib, but not /usr/lib. I installed internal/network with module/eth and module/wlan in config. Its work. Thank You.

**Comment by Maximilian73** [comment]
kajzersoze, what are You using: systemd or openrc?

**Comment by kajzersoze** [comment]
openrc

**Comment by Maximilian73** [comment]
What config You use for reboot and power off from user (not admin)? Please, see my message 5 days ago to Patrick.

**Comment by kajzersoze** [comment]
I'm not using shutdown, but I guess you can google it how to do it via dbus (I think it's "stop" instead of "Restart", the rest of the line is the same as for reboot), anyway here's mine :

```
[module/powermenu]
type = custom/menu
format-spacing = 1
label-open = 
label-open-foreground = ${colors.secondary}
;label-close = cancel
label-close =  cancel
label-close-foreground = ${colors.secondary}
label-separator = |
label-separator-foreground = ${colors.foreground-alt}
format-padding = 1
menu-0-0 = log out
menu-0-0-exec = menu-open-1
menu-0-1 = reboot
menu-0-1-exec = menu-open-2
menu-1-0 = log out
menu-1-0-exec = i3-msg exit
menu-1-1 = cancel
menu-1-1-exec = menu-open-0
menu-2-0 = reboot
menu-2-0-exec = dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart
menu-2-1 = cancel
menu-2-2-exec = menu-open-0

```

**Comment by Maximilian73** [comment]
Thank You. I'll try.

**Comment by NBonaparte** [comment]
Closing as the issue has been resolved.

**Comment by mfoncho** [comment]
I am on Arch linux and there is no libiw.so by default not even in the lib64 i couln't figure out why i kept getting the "No built-in support for internal/network" message and while it worked flowlessly on my dekestop with i3status preinstalled installed. i3status requires wireless_tools which pulls libiw.so and header files. So do i have to install wireless_tools just to pull in the lib before rebuiling polybar?

**Comment by anselal** [comment]
Had the same issue on openSUSE. After installing libiw-devel polybar compiled with internal/network support !!

Maybe we should update the dependencies in the README ???

**Comment by NBonaparte** [comment]
"wireless_tools required by internal/network"

**Comment by anselal** [comment]
@NBonaparte I had wireless-tools installed but I needed to install `libiw-devel` to get this working.
Anyway I added build instruction for openSUSE in the wiki so feel free to check them out if you are on the same distro facing the same problem !!!
