### ISSUE TITLE
battery module issues

### ISSUE THREAD

**Issue by peet1234** [jaagr/polybar#1080]
Battery not update and when i run in terminal error show below:
error: module/battery: Error while creating inotify watch (what: Failed to attach inotify watch (reason: No space left on device))
error: module/battery: Error while creating inotify watch (what: Failed to attach inotify watch (reason: No space left on device))
error: module/battery: Error while creating inotify watch (what: Failed to attach inotify watch (reason: No space left on device))
error: module/battery: Error while creating inotify watch (what: Failed to attach inotify watch (reason: No space left on device))
error: module/battery: Error while creating inotify watch (what: Failed to attach inotify watch (reason: No space left on device))
![2018-03-05-21 22 46](https://user-images.githubusercontent.com/37007880/36979907-72985dae-20bb-11e8-9be2-738a0b56da18.png)

my space:
$ df -h
Filesystem              Size    Used     Avail      Use%     Mounted on
dev                          3.9G     0         3.9G        0%          /dev
run                           3.9G   1.2M      3.9G        1%         /run
/dev/sdb1                 46G    32G      12G         73%       /
tmpfs                        3.9G    237M   3.7G         7%        /dev/shm
tmpfs                        3.9G     0         3.9G          0%        /sys/fs/cgroup
tmpfs                        3.9G    2.3M    3.9G          1%       /tmp
/dev/sdb2                  92G     63G     25G         72%      /home
/dev/sda3                 732G   698G   33G          96%      /media/EXT
tmpfs                       787M    20K      787M         1%      /run/user/1000

**Comment by patrick96** [comment]
Try to [increase the inotify watch limit](https://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached) on your system.
