### ISSUE TITLE
Referencing more than one variables on the same line doesn't work

### ISSUE THREAD

**Issue by gpakosz** [jaagr/polybar#1084]
Hello,

I'm using `polybar 3.1.0-67-g692e6d9` and here's an excerpt from my configuration:

```
[module/date]
  foo = foo
  bar = bar
  label = ${self.foo} ${self.bar} baz
```

Doing so displays `${self.foo} ${self.bar} baz` verbatim instead of `foo bar baz`.
Doing `label = ${self.foo}` correctly expands the variable though.

**Comment by NBonaparte** [comment]
See #954.
