### ISSUE TITLE
Pulseaudio module doesn't detect a new default sink

### ISSUE THREAD

**Issue by fdw** [jaagr/polybar#1086]
(Note: This is similar to #693, but using the new pulseaudio module)

When I connect my bluetooth headphones, pulseaudio automatically switches to that sink as default. However, polybar doesn't notice this switch and still displays the volume for the previous sink.

Is there any way to make the module automatically aware of this change?

**Comment by NBonaparte** [comment]
Do you have the sink option specified in your config?

**Comment by fdw** [comment]
No, this is the extent of the configuration:
```
[module/pulseaudio]
type = internal/pulseaudio

format-volume = <ramp-volume> <label-volume>
label-muted = "  0%"
label-volume = %percentage%%
ramp-volume-0 = " "
ramp-volume-1 = " "
ramp-volume-2 = " "
format-muted-background = ${colors.blue}
format-muted-foreground = ${colors.background}
format-volume-background = ${colors.blue}
format-volume-foreground = ${colors.background}
```

**Comment by NBonaparte** [comment]
Right now, polybar only switches to the default sink if the old one is removed. I'll have to implement an all-default case where it uses the default sink at all times.

For now, if your desired non-bluetooth sink is the default when the headphones aren't connected, you could set the `sink` option to the bluetooth sink, so it would use the default when they aren't connected and switch to the bluetooth headphones if they are connected.

**Comment by fdw** [comment]
Thank you, it works perfectly! :)

Maybe this should also be in the wiki?

**Comment by NBonaparte** [comment]
What exactly does your script do?

**Comment by indeedwatson** [comment]
It changes the default sink, so I can keep speakers and headphones plugged to 2 different sound cards and switch with a bind.

https://gist.github.com/47cfe7ca5f83a77ccdd6b970581daeca
