### ISSUE TITLE
Adding support for iw in addition to wireless_tools

### ISSUE THREAD

**Issue by lokesh-krishna** [jaagr/polybar#1094]
Is it possible to support `iw` in addition to `wireless_tools`?  
`wireless_tools` has been deprecated, as stated in the [official Linux Wireless wiki](https://wireless.wiki.kernel.org/en/users/Documentation/iw).  

Presently, attempting to use the network module with only iw installed results in the following error:
  
`error: Disabling module "wlan" (reason: No built-in support for 'internal/network')`

Would be really nice if we could use the network module without requiring `wireless_tools`.

**Comment by NBonaparte** [comment]
See #1009.
