### ISSUE TITLE
offset-{x,y} offsets tray, not bar

### ISSUE THREAD

**Issue by Doshirae** [jaagr/polybar#1101]
The title pretty much says it

offset-x offsets the tray icons, and not the bar (and tray-offset-x does that too, but that's normal)

Is there some other parameters of the bar that are incompatible with offset ?

EDIT : `polybar -v` gives me this, maybe it could be useful ?
```
polybar 3.1.0-40-g2f11344

Features: +alsa +curl +i3 -mpd +network +pulseaudio
```

Reinstalled the "normal" version (polybar package instead of polybar-git) : `polybar -v`
```
polybar 3.1.0-git

Features: +alsa +curl +i3 -mpd +network
```

**Comment by NBonaparte** [comment]
Are you using `override-redirect = true`? If not, try using it and see if it helps.

**Comment by Doshirae** [comment]
That solved the offset problem, but created a new one : now my bar is floating, it is over my window :/

**Comment by NBonaparte** [comment]
Try `wm-restack = i3`.

**Comment by Doshirae** [comment]
Nothing happened :/

**Comment by Doshirae** [comment]
The bar is no longer over my window
It is now behind it :joy:

**Comment by NBonaparte** [comment]
i3 is very finicky with padding. I think usually people have a dummy bar/window/conky behind it and have polybar floating over it to fix this issue.

**Comment by NBonaparte** [comment]
Just realized you could also have a transparent border (`border-color = #00000000`) and `border-{left,right}-size` as your x offset and `border-{top,bottom}-size` as your y offset.

**Comment by Doshirae** [comment]
That kind of does the trick yes, but it's really tedious

**Comment by patrick96** [comment]
Just tested this a little. It seems this is another quirk of i3, this doesn't happen in hlwm. So I think, there is really not much we can do about this.
