### ISSUE TITLE
mpd模块歌曲信息，无法显示中文

### ISSUE THREAD

**Issue by zj2423651950** [jaagr/polybar#1105]

**Comment by patrick96** [comment]
Sorry, I don't understand chinese, so I used google translate. You say the mpd module doesn't display chinese characters. Does polybar output `Dropping unmatched character` warnings with the various chinese characters in the terminal? If so you need to specify a font that supports those characters in your config (for example unifont). If you don't get those warnings, please provide your config as well as the output when you run polybar with the `-l info` parameter.

**Comment by zj2423651950** [comment]
n: Dropping unmatched character 模 (U+6a21)
warn: Dropping unmatched character 块 (U+5757)
warn: Dropping unmatched character 歌 (U+6b4c)
warn: Dropping unmatched character 曲 (U+66f2)
warn: Dropping unmatched character 信 (U+4fe1)
warn: Dropping unmatched character 息 (U+606f)
warn: Dropping unmatched character ， (U+ff0c)
warn: Dropping unmatched character 无 (U+65e0)
warn: Dropping unmatched character 法 (U+6cd5)
warn: Dropping unmatched character 显 (U+663e)
warn: Dropping unmatched character 示 (U+793a)
warn: Dropping unmatched character 中 (U+4e2d)
warn: Dropping unmatched character 文 (U+6587)
warn: Dropping unmatched character 问 (U+95ee)
warn: Dropping unmatched character 题 (U+9898)
warn: Dropping unmatched character ＃ (U+ff03)
warn: Dropping unmatched character 朴 (U+6734)
warn: Dropping unmatched character 树 (U+6811)
warn: Dropping unmatched character 清 (U+6e05)
warn: Dropping unmatched character 白 (U+767d)
warn: Dropping unmatched character 之 (U+4e4b)
warn: Dropping unmatched character 年 (U+5e74)
warn: Dropping unmatched character 朴 (U+6734)
warn: Dropping unmatched character 树 (U+6811)
warn: Dropping unmatched character 清 (U+6e05)

**Comment by patrick96** [comment]
Yeah, the fonts in your config don't provide chinese characters. Have a look at the [wiki](https://github.com/jaagr/polybar/wiki/Fonts#debugging-font-issues) for how to find a font that does.

**Comment by zj2423651950** [comment]
4 font-0 = source han sans:pixelsize=12;2
 75 font-1 = source han sans:size=10;2
 76 font-2 = source han sans:pixelsize=10;3
 77 font-3 = "Font Awesome 5 Free:style=Regular:pixelsize=12;2"
 78 font-4 = "Font Awesome 5 Free:style=Solid:pixelsize=12;2"
 79 font-5 = "Font Awesome 5 Brands:pixelsize=12;2"
 80 font-6 = ttf-liberation-sans:fixed:pixelsize=12;1
 81 font-7 = "material icons:pixelsize=12;2"

**Comment by patrick96** [comment]
Have a look at Noto Sans Mono CJK TC (or SC) or unifont
