### ISSUE TITLE
Dropping unmatched character   (U+f0c2)

### ISSUE THREAD

**Issue by zachschultz** [jaagr/polybar#1106]
Hi there, first off, thanks so much for polybar! It's taking some time but I'm getting used to it.

I'm trying to get glyphs to display in my bar, but I'm getting the error `warn: Dropping unmatched character   (U+f0c2)` for quite a few of them.

My font setup in my polybar config looks like:

```
font-0 = Iosevka Medium:antialias=true:pixelsize=9;1 
font-1 = Font Awesome 5 Free:pixelsize=10;0
font-2 = Wuncon Siji:pixelsize=10;1
```

I've verified with fc-match that each of these lines matches up with the desired font, so I'm not sure what is causing the issue.

**Comment by patrick96** [comment]
The dropped character is not available in any of the fonts you listed, see the [Wiki](https://github.com/jaagr/polybar/wiki/Fonts#debugging-font-issues) for how to find the font that provides this character

**Comment by Twix53791** [comment]
I just share it my recent experience, as it could help some noobies like me. I got the same error trying to use an icon from weather icons (nerd fonts). I was trying the unicode got from the nerd site ([https://www.nerdfonts.com/cheat-sheet?set=nf-weather-](url)), but in fact, on my computer the code was different, as I simply saw in Libbre Office Writer, which display properly all my icons...
