### ISSUE TITLE
Kubuntu Installation

### ISSUE THREAD

**Issue by iiPlasma** [jaagr/polybar#1108]
I tried using the installation method for Ubuntu from the GitHub mainpage but it said that polybar couldn't be found. Where can I install polybar?

**Comment by patrick96** [comment]
What do you mean by 'installation method for Ubuntu from the GitHub mainpage'? [This](https://github.com/jaagr/polybar/wiki/Compiling) page should have all the information you need.

**Comment by iiPlasma** [comment]
Oh thanks, I was talking about https://github.com/jaagr/polybar

**Comment by iiPlasma** [comment]
Sorry for bothering again, but I'm kind of confused by the instructions on the page you sent. It says to run commands in the folder where I installed the files but all I've done is get the apt-get dependencies. Thanks

**Comment by iiPlasma** [comment]
Wait nvm, that was only for people that had problems compiling. Sorry
