### ISSUE TITLE
i3 module suddenly freezes

### ISSUE THREAD

**Issue by gianlucanotaro** [jaagr/polybar#1115]
When i start polybar, the i3 modules seems to work fine

However with time, the i3 module suddenly freezes and does not update when i change workspace/create new workspace etc. It just stays how it is.

I do not know what is causing this to happen and i did not change anything on the bar. I am using the example bar.

I am also using the i3 default bar and that seems to work fine.

**Comment by patrick96** [comment]
Did you by any chance reload i3 when this happened?

**Comment by gianlucanotaro** [comment]
yes

i am constantly tweaking thigs in my i3 config so i am always restarting i3.

is there a fix for this?

**Comment by patrick96** [comment]
This was already reported in #762, killing and restarting polybar in your i3 config should, work. There is also a seemingly working patch in #1099, will probably merge this on the weekend
