### ISSUE TITLE
Custom scripts and custom tags / formats

### ISSUE THREAD

**Issue by victordiaz** [jaagr/polybar#1116]
I've look around the wiki and haven't seen a way I can add custom tags to format the output. 

I would like to display the content of my custom script using a custom format such 
`format = <one-label><another-label>`

Is is possible already? How should I format the output of my script? 

Thx!

**Comment by patrick96** [comment]
I don't understand exactly what you want to achieve.
The script module has a `format` and a `label` parameter where you can set colors and so on. They also accept the formatting tags described [here](https://github.com/jaagr/polybar/wiki/Formatting#format-tags).

**Comment by victordiaz** [comment]
I updated the previous comment, the tags were not included.
I try to formulate my question again here:

I want to know how I should format the output of my script in other to select only the tags I want to display inside the module config
Something like

```
[module/mycustommodule]
type = custom/script
format = <one-label><another-label><ramp>
...
```

**My question goes here** how should I format the output of my script to have those labels?
I guess should be something similar to the following, but I dont really know how
 
`print('<one-label>data1</one-label><another-label>data2<another-label><ramp>2</ramp>')
`

**Comment by NBonaparte** [comment]
I think you're misunderstanding the functionality of the script module. It only has `<label>` which contains the token `%output%` by default, which is replaced by whatever the output of the script is. There are no multiple labels or ramps defined in the module.

**Comment by victordiaz** [comment]
ok, I see :) I though I could create a module with the same behaviour as the included ones. 
I think is quite beautiful the way Polybar modules work, just tweaking a bit the conf you can configure the bar so much without tweaking scripts! 

Would it be difficult to add that function? Would it make sense to have it?

Thanks anyway!

**Comment by patrick96** [comment]
I don't think it would be that easy. We'd have to write another parser for the command output and then dynamically instantiate the different draw types. While it would be possible, I don't think that right now we have the capacity for it.
