### ISSUE TITLE
Pulseaudio module max volume

### ISSUE THREAD

**Issue by kajzersoze** [jaagr/polybar#1125]
With alsa module 100% was max volume I could go to, with pulseaudio I can go way higher, is there a way to cap it at 100% (or some other configurable value in the config)  ?

**Comment by patrick96** [comment]
Polybar also caps the pulse module at 100%, you can't set the volume any higher than that using polybar. How are you changing the volume?

**Comment by NBonaparte** [comment]
The maximum is currently set as `PA_VOLUME_UI_MAX` (~153%) as recommended by the documentation. We could implement a setting for the maximum volume.

**Comment by patrick96** [comment]
Hmm, on my system that is actually 100%, even though `PA_VOLUME_UI_MAX/PA_VOLUME_NORM` is `1.52`

**Comment by patrick96** [comment]
Oh, I see. The `volup`, `voldown`, etc events from the pulse module are caught by the alsa module (if one is specified)

**Comment by kajzersoze** [comment]
I'm changing the volume using the mouse wheel via the bar in polybar.
There's also visually problem with this, when I reach 100 bar indicator is at max, while the numbers and actual volume goes higher to 150, so the bar indicator doesn't move above 100
![20180327-124102](https://user-images.githubusercontent.com/11412353/37962803-8b5d259c-31bc-11e8-8e0f-7e91b1d6d87d.png)

Yes, configuration setting for this would be nice.

**Comment by patrick96** [comment]
The bar indicator can't really move any higher than 100%, because, well, it's already at 100%. But I agree, a config option for a max value makes sense.

**Comment by kajzersoze** [comment]
Yeah, but in this case maximum is at 150%
So, the bar indicator should be from 0 to the value specified in config.
There's another way, with no config for this and make it to not increase volume above 100%

**Comment by patrick96** [comment]
I think it would be quite unintuitive to have the progressbar go further than 100%, besides you can still increase the volume even more, if you don't use polybar to do it.

>  There's another way, with no config for this and make it to not increase volume above 100%

What way is this?

**Comment by kajzersoze** [comment]
To change [this](https://github.com/jaagr/polybar/blob/3af3aea5349d9ec7e9bc0f1769d140d137496f66/src/adapters/pulseaudio.cpp#L179) :
`if (pa_cvolume_max(&cv) + vol <= PA_VOLUME_UI_MAX) {`

to :
`if (pa_cvolume_max(&cv) + vol <= 100) {`

maybe ?

Anyway, what I meant was capping it in code.
But yeah, there's a problem, I guess, if you increase the volume not using polybar.

**Comment by patrick96** [comment]
Yeah, it would be something along those lines, however `PA_VOLUME_UI_MAX` is not a percentage value but just some number, I think something like `99500` on my system. We'd have to convert the percentage cap to whatever unit pulseaudio is using for the volume

**Comment by kajzersoze** [comment]
Yeah, found something about that [here](https://github.com/lxqt/pavucontrol-qt/blob/1164b1aa8eabb4790869712475603fa0e7058a06/src/channel.cc#L31-L41), looks like it's doing just that.

**Comment by kajzersoze** [comment]
Okay, I managed to cap it at 100% by replacing `PA_VOLUME_UI_MAX` with `PA_VOLUME_NORM`

So, my problem is solved, you can add config for this if you like, cap it at 100% or do something else (maybe nothing?) and eventually close this issue.
Thanks.

**Comment by patrick96** [comment]
I think we're going to leave this open until we implement the cap

**Comment by kajzersoze** [comment]
I made it like this, new config option `max-volume` , it's a bool defaulting to true, when true `PA_VOLUME_UI_MAX` is used, when false `PA_VOLUME_NORM` is used.

Tested, works, I can make a PR but I don't know if this way is okay with you.
