### ISSUE TITLE
Inherit not working properly.

### ISSUE THREAD

**Issue by bbaserdem** [jaagr/polybar#1128]
I have my setup with bars defined in general, and then specific bars inherit them "Differentiating monitors between work and home computes"

I'm getting a random error, where a bar works fine (named [bar/top]) and the only line in another bar is `inherit = bar/top` (this is [bar/htop]). However launching `polybar htop` fails to load fonts and colors; while launching `polybar top` loads the bar correctly.

I have other bars that use this functionality but they are fine. I checked my config for typos but couldnt find anything. I also copy pasted lines from working bars but same failure is there.

My config: https://github.com/bbaserdem/dotfiles/blob/master/polybar/config#73

Screetshot: https://imgur.com/a/OhCfJ

**Comment by NBonaparte** [comment]
Explain.

**Comment by patrick96** [comment]
Does `hbot` work?

**Comment by bbaserdem** [comment]
hbot works just fine. I tried rebooting but it didnt change anything.

**Comment by patrick96** [comment]
Really strange bug. Consider the following minimal config:

```dosini
[bar/base]
width = 100%
height = 32
modules-left = text

[bar/t]
inherit = bar/base

[bar/htop]
inherit = bar/t

[module/text]
type = custom/text
content = Test
```

Here polybar complains: `error: No modules created`

Now, with only changing the name of the middle section from `bar/t` to `bar/b`, it starts to work:
```dosini
[bar/base]
width = 100%
height = 32
modules-left = text

[bar/b]
inherit = bar/base

[bar/htop]
inherit = bar/b

[module/text]
type = custom/text
content = Test
```

**Comment by NBonaparte** [comment]
Is this related to the alphabetical order issue we found a while back?

**Comment by patrick96** [comment]
Just looked at the trace log and it appears to be.

inheritance for `bar/htop` is done before `bar/i` because it comes before it in the alphabet, so `bar/htop` contains an inheritance key that is never 'evaluated' because we only do a single pass to copy inheritance.
I don't remember this occuring before though, is there an open issue for that?

**Comment by NBonaparte** [comment]
I'll close this in favor of #412 because it appears to be identical.

**Comment by bbaserdem** [comment]
Seems to be so. Changing names fixed it.

Although I had no problems with this yesterday, and I did not run any updates in the meantime. Seems weird it failed just today.
