### ISSUE TITLE
Show current mpv song?

### ISSUE THREAD

**Issue by herohamp** [jaagr/polybar#1130]
Is it possible to display on polybar the current song I am playing through mpv?

**Comment by x70b1** [comment]
Typically you can do this with your own [scripts](https://github.com/jaagr/polybar/wiki/Module:-script). There is a repository with many ready-to-run scripts for the most use cases: [x70b1/polybar-scripts](https://github.com/x70b1/polybar-scripts).

We have already something for [mpv](https://github.com/x70b1/polybar-scripts/tree/master/polybar-scripts/player-mpv). Unfortunately this is in a [bad condition](https://github.com/x70b1/polybar-scripts/issues/16) and we need someone to improve it.

**Comment by patrick96** [comment]
Thanks for posting @x70b1. Right now there is no internal module for mpv, you have to use a script module
