### ISSUE TITLE
Does not detect second external monitor

### ISSUE THREAD

**Issue by SteveHNH** [jaagr/polybar#1131]
I cannot get polybar to recognize that I have a second external monitor connected. It shows the laptop and one of my external monitors, but not the third.

```
$ xrandr | grep -w connected
eDP-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 309mm x 173mm                                                    
DP-2-1 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 476mm x 268mm                                               
DP-2-2 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 476mm x 268mm 
```
```
$ polybar -m
DP-2-1: 1920x1080+1920+0                                                                                                                 
eDP-1: 1920x1080+0+0
```
```
$ polybar -vv                                                                                                                            
polybar 3.1.0-75-gd007539                                                                                                                

Features: +alsa +curl +i3 +mpd +network +pulseaudio

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/lib64/ccache/g++
Compiler flags:  -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: 
```

I'm trying to get polybar to show up on DP-2-2, but having no luck getting it to recognize it.

**Comment by SteveHNH** [comment]
It's a separate monitor and not mirrored. It's actually coming out of a docking station of a Lenovo Thinkpad. That docking station has two DisplayPorts on it, each with a monitor plugged in. I hope that information helps some.

**Comment by NBonaparte** [comment]
In the xrandr output, it shows eDP-1 and DP-2-2 with the exact same coordinates (`1920x1080+0+0`). Maybe try setting DP-2-2 with `--left-of <other monitor>` or `--right-of <other monitor>` (depending on your setup)?

**Comment by SteveHNH** [comment]
This is the command I have in my i3 config:
`xrandr --output DP-2-1 --left-of DP-2-2 --auto --primary`

That definitely positions the monitors appropriately. The eDP-1 connection is my laptop which I keep closed, but it may be affecting the other monitor somehow. I'll test a few more things

**Comment by SteveHNH** [comment]
I fixed it. Looks like eDP-1 was actually on despite my laptop being closed. I had to run `xrandr --output eDP-1 --off` and then the monitor showed up in `polybar --list-monitors`

Thanks for the help and getting my mind going in the right direction. I'll go ahead and close this issue, but hopefully it helps others who might be in this same situtation.
