### ISSUE TITLE
Free memory report doesn't match system's

### ISSUE THREAD

**Issue by nivaca** [jaagr/polybar#1137]
I've found (in two machines) that the `%gb_used%` (or the `%gb_used%`) variable report doesn't match my system's report of used memory.
If I compare Polybar's report, it's almost 200MB higher than my system's (using `htop` or `free`). My total

![screenshot-2018-04-01_10-00-21](https://user-images.githubusercontent.com/2309005/38174591-25f231ca-3595-11e8-9dd8-98d5dd603107.png)

The total amount of memory (reported using `%gb_total%`), however, does coincide with the system's.

Am I missing something here?

This is the relevant part of my polyconf:

```

[module/memory]
type = internal/memory
interval = 5
format-prefix = " "
label = %gb_used%

```

**Comment by patrick96** [comment]
The used values polybar displays are actually consistent with free's output. It is the same as when you run `free -k`, and calculate `(total - available) / 1024^2`.
As to why `free` and `htop` don't show the same value (and thus polybar also doesn't), read [this SO answer](https://unix.stackexchange.com/questions/247210/how-to-interpreted-top-htop-memory-usage).

I think the current way used memory is calculated is appropriate.

**Comment by nivaca** [comment]
Thanks for your answer. I makes sense now.

**Comment by nabil48** [comment]
same on my device 
part of my polybar configuration
```
[module/memory]
type = internal/memory
interval = 1
format = <label>
format-prefix = " "
format-suffix = "%"
format-padding = 1
```
![screenshot_20181209_053241](https://user-images.githubusercontent.com/37516576/49691494-29c09600-fb76-11e8-90e9-800c91c3a04a.png)

**Comment by KaueTheTrekker** [comment]
> same on my device
> part of my polybar configuration
> 
> ```
> [module/memory]
> type = internal/memory
> interval = 1
> format = <label>
> format-prefix = " "
> format-suffix = "%"
> format-padding = 1
> ```
> 
> ![screenshot_20181209_053241](https://user-images.githubusercontent.com/37516576/49691494-29c09600-fb76-11e8-90e9-800c91c3a04a.png)

http://www.criticalreading.com/interpretation.htm
This might help you.

**Comment by hfel** [comment]
Would it be possible to add the htop display method of discounting buffered and cached memory as used as an option in the module?

**Comment by patrick96** [comment]
@hfel See #2028

**Comment by Fxzzi** [comment]
Hi, it seems my polybar memory module isn't even the same as `free -k(h)` as mentioned in the above post.


![](https://i.imgur.com/GmTuoBy.png)

You can see here as an example that polybar is showing higher than the output of `free -kh`

**Comment by Samueru-sama** [comment]
I am using this, which doesn't involve creating a separate script, it can all be saved to the polybar config.

[module/RAM]
type = custom/script
label = %{F#F0C674}RAM %{F-} %output%
exec = free -h | awk 'FNR == 2 {print $3"B / "$2"B"; exit}'
interval = 3
format-padding = 1
click-left = xfce4-terminal -e htop

Here is how it looks on my bar: https://imgur.com/zHULhOK.png

Also by left clicking on it it opens htop if you use the xfce4-terminal, change it to your liking if you use a different terminal.
