### ISSUE TITLE
Tray displays on bottom left of the screen

### ISSUE THREAD

**Issue by Yakoot** [jaagr/polybar#1140]
![archlabs_2018-04-02-13_1920x1080](https://user-images.githubusercontent.com/4795345/38215023-0652c074-36cf-11e8-9884-8a3ee6345e3a.png)
here is my config
`;=====================================================
;     File Includes
;=====================================================

[section/base]
include-file = /home/yakoot/.config/polybar/master.conf
include-file = /home/yakoot/.config/polybar/modules.conf

;=====================================================
;     Openbox Bars
;=====================================================

[bar/openbox-bar]
inherit = bar/master

; Use $ xrandr -q | grep " connected" | cut -d ' ' -f1
monitor =

modules-left   = jgmenu workspaces
modules-center = window_switch clock
modules-right  = xkeyboard pkg memory network volume

tray-position = right
tray-padding = 2
tray-background = ${root.background}

;=====================================================
;     i3 Bars
;=====================================================

[bar/i3-bar]
inherit = bar/master

; Use $ xrandr -q | grep " connected" | cut -d ' ' -f1
monitor =

modules-left   = jgmenu i3 menu
modules-center = clock
modules-right  = pkg memory temperature coreuse network volume

;=====================================================
;     Bspwm Bars
;=====================================================

[bar/bspwm-bar]
inherit = bar/master

; Use $ xrandr -q | grep " connected" | cut -d ' ' -f1
monitor =

modules-left   = bspwm menu
modules-center = clock
modules-right  = pkg memory temperature coreuse network volume
`

**Comment by patrick96** [comment]
What's the output of polybar in the terminal?

**Comment by Yakoot** [comment]
➜  ~ polybar openbox-bar
warn: No monitor specified, using "HDMI-0"
error: Disabling module "xkeyboard" (reason: Missing parameter "module/xkeyboard.type")
warn: Systray selection already managed (window=0x0c0001f)

**Comment by Yakoot** [comment]
I've fixed all except systray warn
`➜  ~ polybar openbox-bar
warn: Systray selection already managed (window=0x0c0001f)
`

**Comment by Yakoot** [comment]
Hm, tray still displays after killing polybar

**Comment by Yakoot** [comment]
I found a problem, it's trayer, polybars displays tray after killing him

**Comment by patrick96** [comment]
Yeah, that's what I thought ;)
