### ISSUE TITLE
Polybar workspace selection with mouse inserts null workspace

### ISSUE THREAD

**Issue by d3signr** [jaagr/polybar#1142]
Hi,

Thanks for Polybar by the way, it's a great tool. Recently though, and i'm not sure if it is my config or a bug but if i activate workspaces with $mod [num] absolutely no problems creating / switching workspaces.

However, let's say i have two active workspaces 1, 2 and mouse click on 1, polybar inserts another 1 before the existing 1 that is empty. So i get 1, 1, 2. Clicking any of these at this point results in all workspaces appearing empty.

 I must then use $mod [num] and switch back and forth to remedy which removes the bogus workspace and normality resumes.

Any suggestions as to why this behaviour is being exhibited?

Thanks

**Comment by d3signr** [comment]
Actually i think i just found the issue in my config, closing.

**Comment by anamyk** [comment]
i have the same problem. how did you fix it?
