### ISSUE TITLE
New reddit notifications module

### ISSUE THREAD

**Issue by su8** [jaagr/polybar#1145]
Can you add a new module that parses all unread [reddit notifications](https://www.reddit.com/prefs/feeds/) e.g the JSON pointing to everything 
![reddit](https://user-images.githubusercontent.com/29376083/38391257-0a3a8c74-3924-11e8-8438-4196697d0ae4.png)
?

Here's a link to my account that has 3 unread notifications - `curl -s -A "bottob" 'https://www.reddit.com/message/inbox/.json?feed=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&user=XXXXXXXX` , just parse the **"new": true** field and count the matches.

Cheers

**Comment by patrick96** [comment]
I have removed the identifiers from the URL, as they can be used to access much of your information on reddit.

We'll look into adding such a module at some point, for now, I've added it to our todo list. I bet with the curl command you provided, it wouldn't be a big challenge to write a script to use in the `internal/script` module.

**Comment by x70b1** [comment]
There is a script for the reddit-inbox: [polybar-scripts/inbox-reddit](https://github.com/x70b1/polybar-scripts/tree/master/polybar-scripts/inbox-reddit).

**Comment by su8** [comment]
One could use `grep` as in `curl -A "botreq" 'https://www.reddit.com/message/inbox/.json?feed=LONG_SHA&user=USER' -s|grep -o '"new": true'|wc -l`

My request is to be added this to be internal function to polybar instead using scripts.

**Comment by patrick96** [comment]
Seems a little overkill to add a module for something that can be done quite trivially with a script.

**Comment by su8** [comment]
Okay.
