### ISSUE TITLE
%percentage_swap_used% is not recognized

### ISSUE THREAD

**Issue by crocket** [jaagr/polybar#1146]
polybar-3.1.0

```
[module/memory]
type=internal/memory
interval=3
label=%percentage_used:3%%

[module/swap]
type=internal/memory
interval=3
label = %percentage_swap_used:3%%
```

In the above configuration, `%percentage_swap_used%` is not replaced with actual swap usage. I see `%percentage_swap_used%%` in polybar.

**Comment by patrick96** [comment]
`%percentage_swap_used%` is not in a release yet. Please build against the latest polybar commit, if you want to use it.

**Comment by crocket** [comment]
Thank you

**Comment by gaabster** [comment]
Can I hijack this and ask If this is true only for `percentage_swap` or any of the swap options ?
