### ISSUE TITLE
Creating custom labels

### ISSUE THREAD

**Issue by ljukas** [jaagr/polybar#1157]
Hi

I'd like to create custom labels for different modules. The issues I have is that in the battery module I want one font for the icon that shows if its charging and one font for the text next to it. My thought was to create to labels and show both with:
format-charging = <label-percentage> <label-charging>

But it seems like this doesn't work since polybar -l info says:
<label-percentage> is not a valid format tag for <format-charging>

Is there any way to create custom labels? Or in any way split a label into multiple so I can use different fonts?

Thanks for an amazing bar.

**Comment by patrick96** [comment]
There seems to be some stuff missing in this text, but nonetheless, you cannot make up new labels, they have to be already defined by polybar. If you want to use different fonts in different places in the same label, have a look at [Formatting tags](https://github.com/jaagr/polybar/wiki/Formatting#format-tags)
