### ISSUE TITLE
Polybars don't hide on ipc command

### ISSUE THREAD

**Issue by timonstampfli** [jaagr/polybar#1158]
When i execute "polybar-msg cmd hide" the polybars I'm running won't hide. According to the output, the command has been written to the ipc pipeline.

output:
polybar-msg: Successfully wrote "cmd:hide" to "/tmp/polybar_mqueue.1898"
polybar-msg: Successfully wrote "cmd:hide" to "/tmp/polybar_mqueue.1900"
polybar-msg: Successfully wrote "cmd:hide" to "/tmp/polybar_mqueue.1902"

**Comment by patrick96** [comment]
What WM are you running?

Have you confirmed that `1898`, `1900` and `1902` were the PIDs of your polybar instances when you ran the `polybar-msg` command?

What was the output of the polybar processes?

**Comment by timonstampfli** [comment]
> What WM are you running?

I'm running i3 version 4.14.1 (2017-09-24)

> Have you confirmed that 1898, 1900 and 1902 were the PIDs of your polybar instances when you ran the polybar-msg command?

$ pidof polybar
1902 1900 1898

> What was the output of the polybar processes?

I actually don't have the output of that process.
However, I just killed all my automatically started polybars and launched manually a new one. 
This one logs:
warn: "hide" is not a valid ipc command

I'm not sure why it logs that.

This might also be helpful:

polybar --version
polybar 3.0.5
Features: +alsa -curl +i3 -mpd +network

Thanks for your help

**Comment by patrick96** [comment]
>  polybar 3.0.5

Update your polybar. The `hide` command was introduced in `3.1.0`
