### ISSUE TITLE
SIGFPE (Floating point exception) when using xworkspaces module with 2bwm

### ISSUE THREAD

**Issue by tmthydvs** [jaagr/polybar#1159]
I've definitely narrowed it down to being caused by xworkspaces, however I can't find where.
I tried debugging with gdb and I was only able to find that the issue was in `polybar::v3_1_0_83_gd31570f::modules::xworkspaces_module::rebuild_desktops()`.

Here are the relevant parts of my config:
```
[colors]
    background = #f8282a36
    background-alt = #f83b3e4f
    foreground = #fff8f8f2
    accent = #ffff79c6

    
[base]
    font-0 = Hack:size=8;1
    font-1 = MaterialIcons:size=8;2
    font-2 = MaterialIcons:size=14;3
    font-3 = Monospace:size=8;2
    font-4 = FontAwesome:size=8;1

    bottom = true
    
    monitor = eDP1

    width = 100%
    height = 24

    background = ${colors.background}
    foreground = ${colors.foreground}
    line-size = 2

    fixed-center = true

    module-margin = 1


[settings]
    format-padding = 1
    format-foreground = ${colors.foreground}
    format-background = ${colors.background-alt}


[bar/twobwm]
    inherit = base

    modules-left = twobwm


[module/twobwm]
    type = internal/xworkspaces

    format = <label-state>

    label-active = 
    label-active-padding = ${settings.format-padding}
    label-active-foreground = ${colors.foreground}
    
    label-occupied = 
    label-occupied-padding = ${settings.format-padding}
    label-occupied-foreground = ${colors.background}
    
    label-urgent = 
    label-urgent-padding = ${settings.format-padding}
    label-urgent-foreground = ${colors.background}
    
    label-empty = 
    label-empty-padding = ${settings.format-padding}
    label-empty-foreground = ${colors.background}
```

Sorry for weird format, I have multiple bars that do the same thing defined.
If I remove the twobwm module it works fine.

**Comment by patrick96** [comment]
What WM are you using?

**Comment by tmthydvs** [comment]
I'm using 2bwm, it may just be an issue with that, however I'm pretty sure it's EMWH compliant

**Comment by patrick96** [comment]
Probably WM related, doesn't happen on hlwm. Can you compile polybar in debug mode (add `-DCMAKE_BUILD_TYPE=Debug` to `cmake`) and then run it inside polybar. When the crash happens you can run `bt full` to get a backtrace.

**Comment by tmthydvs** [comment]
In the `rebuild_desktops()` method division by 0 isn't checked, so it's most likely that 2bwm doesn't support the Atoms queried and return 0. I can cope with it for now, I'll look for a fix later though. Closing this for now
