### ISSUE TITLE
stalonetray is positioned above polybar

### ISSUE THREAD

**Issue by amilkov3** [jaagr/polybar#1162]
Based on the tray docs, I'm not sure how to place stalonetray specifically in polybar. It always starts up above the polybar

**Comment by NBonaparte** [comment]
How does this relate to polybar specifically? This sounds like a stalonetray problem.

**Comment by patrick96** [comment]
Create a text module with whitespaces only (`content = "    "`) where stalonetray appears, this way it will be above polybar but not overlapping anything important
