### ISSUE TITLE
Detect network interface removal

### ISSUE THREAD

**Issue by pfouto** [jaagr/polybar#1163]
I am using a USB to Ethernet adapter, since my laptop does not have an ethernet port.

If I disconnect the ethernet cable from the adapter, the state of the network interface is set to down, which changes the polybar network module normally.

However, if I disconnected the adapter from the laptop without first disconnecting the ethernet cable from the adapter (i.e, the network interface disappears, without first changing its state do down) the polybar network module stops updating itself, continuing to display the last state before the adapter was removed instead of displaying the disconnected format.

**Comment by patrick96** [comment]
What does the current behaviour look like in the polybar output? Does polybar issue some kind of warning when you do that?

**Comment by pfouto** [comment]
Yes, it seems to be executing the following code:

https://github.com/jaagr/polybar/blob/0a8a326730248131880430596c83a8529c0ffe38/src/modules/network.cpp#L87-L90

I'm not familiar with the code, but I suppose setting _m_connected_ to false inside this code block is what I'm looking for. I'm not sure what that _return false_ implies though.

**Comment by patrick96** [comment]
Yeah most likely that's what we need to do. As far as I can tell, the return value of the `update` function is never used. I'll open a PR

**Comment by edward-shen** [comment]
It looks like it might not have been solved. I'm current running v.3.2.1 and the behavior still exists.

I'm currently using a USB Type-C to Ethernet adapter that shows up as a `enp62s0u1`. Connecting it before starting polybar will have it show properly up. Disconnecting the adapter will have polybar emit a "Failed to query interface" message, and will continue to render the interface despite no longer having access to it.

When the device is reconnected, polybar will correctly recognize that the interface and resume proper behavior.

**Comment by MTBorg** [comment]
I'm still experiencing this, any fix?

**Comment by origamisith** [comment]
I still have this issue with a USB-C to ethernet adapter on my laptop. The log outputs "Failed to query interface 'enp0s20fu7'" but polybar doesn't update
