### ISSUE TITLE
When pulseaudio's default sinks changes, the volume bar doesn't truly reflect the volume although the mouse bindings work

### ISSUE THREAD

**Issue by doronbehar** [jaagr/polybar#1167]
The title is a bit long but I hope it was informative. Very similar to what @indeedwatson has [pointed out](https://github.com/jaagr/polybar/issues/1086#issuecomment-380833286), the problem I'm experiencing is this:

If I change pulseaudio's default sink with a script like [@indeedwatson's](https://gist.github.com/47cfe7ca5f83a77ccdd6b970581daeca) or through any another API (like [this](https://github.com/stefano-m/lua-pulseaudio_dbus) in my case), and I put the mouse on the volume bar and scroll up or down in order to raise or lower the volume, the default sink's volume is truly the one that is changed thanks to https://github.com/jaagr/polybar/pull/1118 (I guess) but the volume bar doesn't really change it's appearance and it **looks** like the volume doesn't really change although one can hear it change.

**Comment by doronbehar** [comment]
Correct.

**Comment by patrick96** [comment]
@doronbehar Can you check out #1168 and see, if this now works correctly for you.

**Comment by doronbehar** [comment]
Checked out #1168 and I the `<volume-bar>` still doesn't change.

**Comment by NBonaparte** [comment]
Does the volume label work correctly though?

**Comment by doronbehar** [comment]
According to [this Wiki article](https://github.com/jaagr/polybar/wiki/Module:-volume#additional-formatting), I've commented out `label-volume` in `[module/volume]` so it will show the percentage of the current default sink and it doesn't change either.

**Comment by indeedwatson** [comment]
I just updated polybar-git from aur and it has not been fixed for me either.

If I have my integrated soundcard as default (speakers) everything works as intended. If I switch to external card (headphones) then my keybinds to control the volume work as intended on the headphones, but the volume bar doesn't do anything; but if I use the mousewheel, the bar does visually move, but the volume of the headphones doesn't change.

**Comment by NBonaparte** [comment]
@indeedwatson it’s not in master yet, use the changes in #1168.

**Comment by doronbehar** [comment]
Hey guys, thanks for making the effort in solving this issue but I think it wasn't resolved. It took me a while to come back to my computer after a small vacation and test it. I've pulled the latest changes and used the new `build.sh` script to build it and there is no change in the behavior of the volume bar. It doesn't represent the volume of the actual default sink just like before.

Could there be a problem blocking you guys from testing it on your machines? How can I debug this so I can help you solve this? Please.

Thanks.

**Comment by NBonaparte** [comment]
Could you thoroughly describe your setup and how you reproduce this bug? I used pactl as well as pavucontrol to change the default sink and it seemed to work fine with the fix.

**Comment by doronbehar** [comment]
My setup uses this configuration for the volume module:
```ini
[module/volume]
type = internal/volume

format-volume = <label-volume> <bar-volume>
; other irrelevant formats and labels...
```
I have 2 sinks available on my machine - HDMI and analog and I'm reproducing this bug this way:

- I put some music which goes through the HDMI output while it is the default sink as well.
- I run `alsamixer` which by default changes the volume of the default pulseaudio sink.
- I press the arrow keys in order to change the volume of the default sink which is the HDMI sink right now. I see the volume bar changes (as well as hearing it goes louder or quieter of-course).
- I run `pactl set-default-sink <analog-sink-name>`.
- I close `alsamixer` and I open it again but now it changes the new default sink which the analog one.
- I change the volume of the default sink with `alsamixer` with the arrow keys (the sound shouldn't be changed because we haven't moved the sink-source of the music player to the default sink).
- Expecting to see the volume bar changes, it doesn't change.

The same behavior goes when I perform the same actions through a different API like this: https://github.com/stefano-m/lua-pulseaudio_dbus .

**Comment by NBonaparte** [comment]
Are you not using `internal/pulseaudio` or is that a typo?

**Comment by doronbehar** [comment]
Wow man I'm sorry :( fool me.. With `internal/pulseaudio` it works like a charm! Thank you so much.
