### ISSUE TITLE
i3 module's label-separator isn't functioning

### ISSUE THREAD

**Issue by arkostin** [jaagr/polybar#1169]
i3 module section of config:

>[module/i3]
>type = internal/i3
>format = <label-state> <label-mode>
>index-sort = true
>wrapping-scroll = false
>
>; Only show workspaces on the same output as the bar
>;pin-workspaces = true
>
>label-active-font = 2
>label-mode-padding = 1
>label-mode-foreground = #FF0
>label-mode-background = #FF0
>
>; focused = Active workspace on focused monitor
>label-focused = %index%
>label-focused-foreground = #FFF
>label-focused-background = ${colors.i3-focused-color}
>label-focused-underline = ${module/bspwm.label-focused-underline}
>label-focused-padding = 2
>
>; unfocused = Inactive workspace on any monitor
>label-unfocused = %index%
>label-unfocused-background = #6897e2
>label-unfocused-padding = 2
>
>; visible = Active workspace on unfocused monitor
>label-visible = %index%
>label-visible-background = ${self.label-focused-background}
>label-visible-underline = ${self.label-focused-underline}
>label-visible-padding = ${self.label-focused-padding}
>
>; urgent = Workspace with urgency hint set
>label-urgent = %index%
>label-urgent-background = ${module/bspwm.label-urgent-background}
>label-urgent-padding = ${module/bspwm.label-urgent-padding}
>
>; separate the labels, set to be comically large to show inactivity
>label-separator = |
>label-separator-padding = 20
>label-separator-foreground = #F00
>
>ws-icon-0 = 1;
>ws-icon-1 = 2;
>ws-icon-2 = 3;
>ws-icon-3 = 4;
>ws-icon-4 = 5;
>ws-icon-5 = 6;
>ws-icon-6 = 7;
>ws-icon-7 = 8;
>ws-icon-8 = 9;
>ws-icon-9 = 10;
>
>strip-wsnumbers = false

That shows the following:
![2018-04-15-160427_1920x1080_scrot](https://user-images.githubusercontent.com/15898224/38784457-e4549a90-40c6-11e8-8eab-67b435123adb.png)

Putting this up as the label-separator seems to only have been implemented recently, and so may have limited functionality.

**Comment by patrick96** [comment]
What is your polybar version (`polybar -vvv`)?

**Comment by 1ntronaut** [comment]
@arkostin 

I've encountered the exact same problem, despite reading and adhering to the [documentation](https://github.com/jaagr/polybar/wiki/Module:-i3) (see: Additional formatting).

It won't show up, no matter how I edit it. Below, I use "%{T2}" as my icon font (FontAwesome), which does work in other modules:
```
;   <label-seperator>
; Separator in between workspaces
label-separator = "%{T2}%{T-}"
label-separator-padding = 0
label-separator-foreground = ${colors.magenta}
label-separator-background = ${colors.oldbackground}
```
 I've also noticed this:
> ; separate the labels, set to be comically large to show inactivity
It seems as if the module is broken. However, I am quite new to polybar (actually, quite new to i3 and modifying it; as for Linux, a little bit less so, but still relatively new), so I might be mistaken, I haven't been able to find anything that works though.

I'm curious though, why is your 'format' (in line 3 of your quote) empty?
```
format = 
```
@patrick96 
"$ polybar -vvv" gives me "polybar 3.1.0-git"; my package manager (pamac-manager, on Manjaro Linux) states "polybar 3.1.0-4".

As of my own, I've been having this issue with the workspace %index%; as soon as I change them (anything other than the default config file), the index will display "-1" on all of my workspace labels.
Any guesses to what it may be or how I could fix it? Else I'll maybe post myself sometime soon.

**Comment by patrick96** [comment]
As I suspected, @1ntronaut you are using the latest polybar release, however the separator feature was only implemented recently and is not released yet. Compile against the latest commit to use it (you can use `polybar-git` on arch). I suspect this is also the reason why OPs config doesn't work, can you confirm @arkostin?

> I'm curious though, why is your 'format' (in line 3 of your quote) empty?
format = 

I don't think it's actually empty, it's just that github removes 'HTML Tags' from the comments (and the formatting tags like `\<label-state\>` look like HTML tags).

As for your other question, please open a new issue and provide your config as well as the exact steps you take to get this wrong behaviour.

**Comment by 1ntronaut** [comment]
@patrick96 
I wasn't really aware of the separator being an unreleased feature. However, I also didn't really expect the polybar from Arch (3.1.0-3) to be of an earlier release than the one from the Manjaro packages.

Thank you for the response! I will be trying your solution for both the separator issue and my own.

> I don't think it's actually empty, it's just that github removes 'HTML Tags' from the comments (and the formatting tags like \<label-state\> look like HTML tags).
Ah right, I hadn't even thought about that; as you can probably sense, quite new to GitHub as well. Thanks for pointing it out.

**Comment by arkostin** [comment]
You're right @patrick96, `polybar -vvv` returns polybar 3.1.0-git among other things.
After recompiling using most recent commit, issue fixed itself and my config looks as ugly as it should :+1: thank you
