### ISSUE TITLE
Ugly fonts in polybar

### ISSUE THREAD

**Issue by kaytrance** [jaagr/polybar#1170]
My polybar fonts fools ugly. Terminal uses `Terminess` font and it looks great, but if I try to use it in polybar, it just does not look right (click on a link for crisp png image):

![](https://i.imgur.com/QgVfzdT.png)

Notice how different looks polybar numbers and the same numbers written in terminal. It seems that as if the numbers in polybar are compressed.

Any advices what may be wrong?

Thank you!

**Comment by patrick96** [comment]
Have you confirmed that the font is loaded correctly? Also maybe turning off antialiasing for that font caused this.

**Comment by kaytrance** [comment]
@patrick96 I have trued to turn on `antialias` and off. With its enabled number are very blurry, so I turned it off.

When it comes to font I copy/pasted the exact same thing as outputed with `fc-list` so it should be loaded fine. How can I doublecheck?

**Comment by patrick96** [comment]
When you run polybar with `-l info`, it will show you the fonts it's tried to load and which fonts it actually loaded in brackets.

**Comment by kaytrance** [comment]
Here's an output regarding fonts
```
* Starting application
* Starting module/i3
* Starting module/filesystem
* Starting module/xkeyboard
* Starting module/memory
* Starting module/cpu
* Starting module/eth
* Starting module/date
* Starting module/powermenu
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=10)
* Configured DPI = 96x96
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 8: unknown element "description"
* Loaded font "TerminessTTFNerdFontMono:fontformat=truetype:size=11:antialias=false" (name=TerminessTTF Nerd Font Mono, offset=0, file=/usr/share/fonts/TTF/Terminess (TTF) Nerd Font Complete Mono.ttf)
* Loaded font "unifont:fontformat=truetype:size=8:antialias=false" (name=Bitstream Vera Sans, offset=0, file=/usr/share/fonts/TTF/Vera.ttf)
* Loaded font "siji:pixelsize=10" (name=Bitstream Vera Sans, offset=1, file=/usr/share/fonts/TTF/Vera.ttf)
* Bar window: 0x2400002
* Activating tray manager
* Tray window: 0x2400006
* module/i3: Rebuilding cache
* module/filesystem: Rebuilding cache
* module/xkeyboard: Rebuilding cache
* module/memory: Rebuilding cache
* module/cpu: Rebuilding cache
* module/eth: Rebuilding cache
* module/date: Rebuilding cache
* module/powermenu: Rebuilding cache
* Redrawing bar window
```
so it seems that the font was loaded correctly.

**Comment by patrick96** [comment]
Yeah, seems it loaded fine. You seem to have some fontconfig errors in `/etc/fonts/conf.d/70-no-bitmaps.conf`, but I don't think this is related. Can you try to remove the `fontformat=truetype` option and see if that fixes it.

**Comment by patrick96** [comment]
I was able to reproduce this now with actually installing nerd fonts. However, I was not able to fix it, with this particular font. What I have found, is that the [unpatched version](https://files.ax86.net/terminus-ttf/) (the unpatched versions are named Terminus) as well as the unpatched non-truetype [original version](http://terminus-font.sourceforge.net/) and the patched original version in [powerline fonts](https://github.com/powerline/fonts) all don't have this problem (The TTF terminus font had the problem, but only because of the font size, `size=12` fixed this). I would recommend using any of these three fonts instead.

**Comment by kaytrance** [comment]
Thanks a lot for your help, @patrick96, I will try to install and use terminus then instead of nerd fonts. I will let you know how it went.

**Comment by kaytrance** [comment]
I have a small question: can polybar use only ttf fonts? It seems that I cannot use [bitmap](https://github.com/kaytrance/bitmap-fonts) fonts..

**Comment by patrick96** [comment]
Polybar should be able to use any font listed by `fc-list`, however from your log above, I have seen you have the `70-no-bitmaps.conf` in `/etc/fonts/conf.d/`, which disables bitmap fonts. The page you listed actually tells you how to enable bitmap fonts in your system.

Were you able to solve your other problem?

**Comment by kaytrance** [comment]
I have deleted that file that seems to disable bitmap fonts, then added `proggy` fonts, rebooted and then I was able to specify bitmap fonts, and they rendered sharp and crisp! 
Thanks for all the help, closing this as resolved.
