### ISSUE TITLE
No built-in support for 'internal/network' in Archlinux Linux

### ISSUE THREAD

**Issue by mfoncho** [jaagr/polybar#1173]
Arch linux default builds lack libiw.so and its header file. I built polybar and not once did it fail but after configurations i still get these errors

```
error: Disabling model "wlan" (reason: No built-in support for 'internal/network')
error: Disabling model "eth" (reason: No built-in support for 'internal/network')
```

**Comment by patrick96** [comment]
Did you have `wireless_tools` installed during the build?

**Comment by mfoncho** [comment]
No wireless_tools is now deprecated and thus was not included in my build

**Comment by patrick96** [comment]
Well there is your problem, polybar requires wireless_tools for network module support. So you'll have to have it installed when you build and run polybar

**Comment by mfoncho** [comment]
Do both wired and wireless module depend on the same lib? So i cant get just the wired status for now patching polybar?

**Comment by patrick96** [comment]
From what I can tell, only the support for wireless interfaces depends on wireless_tools (as the name suggests). So you'd probably be able to remove all wireless functionality from polybar and force-enable the network module during compilation to get only wired functionality

**Comment by NBonaparte** [comment]
Waiting on #1009 to apply suggested fixes, which should completely fix this issue as it replaces wireless_tools with nl80211. If it is not fixed in a reasonable amount of time, I might do the changes myself.

**Comment by mfoncho** [comment]
I have used up my free time today reading the source. Tried replacing wireless_tools and i broke the bar thats the flaw with objected oriented programing. Thinking of a  rewrite for both modules but if you can patch it @NBonaparte please publish in yaourt so i can version build.
