### ISSUE TITLE
Backlight not updating correctly

### ISSUE THREAD

**Issue by Jarwain** [jaagr/polybar#1180]
When I change my brightness, it looks like polybar is updating the stored value, but not actually printing it until I change the brightness again. This results in a value that is behind by an update.

Say, if my brightness is 45%. I increment it by 5%, and I see my screen get brighter. However, the value stays at 45%. 
brightness(+5%) = Actual: 55%, Polybar: 50%
brightness(+5%) = Actual: 60%, Polybar: 55%
brightness(-20%) = Actual: 40%, Polybar: 60%
brightness(+10%) = Actual: 50%, Polybar 40%

Restarting polybar prints the correct value.

I am running a Lenovo Yoga 2 Pro on Fedora 27. 
I'm using internal/backlight, because xbacklight is not supported on my system. 
`card = intel_backlight`
I have a bash script that updates `/sys/class/backlight/intel_backlight/brightness` with an x% change, bound to function keys via i3

This is pretty unimportant, but it's a silly bug and I figured I'd file an issue. I may try digging through the source to resolve this after I'm finished setting up this laptop.

**Comment by patrick96** [comment]
> When I change my brightness, it looks like polybar is updating the stored value

What do you mean by this? Does polybar actually update its internal `m_percentage` value not print it?


This looks similar to one of the issues in #712, does running `cat /sys/class/backlight/intel_backlight/brightness` update the brightness in polybar when it is one step behind?

**Comment by Jarwain** [comment]
I'm not sure if its internal `m_percentage` is being updated; I still need to relearn how to gdb. It was an attempt at guessing what's happening. A better way to phrase it might be that it looks like when the brightness is changed, the update is added to a queue, but only gets popped/read by polybar after another update has been pushed. 

I read #712 before, it didn't sound quite right because polybar *was* displaying a mostly accurate number, and *does* change on update.
Having read to the end, as well as googling inotify, it sounds similar if not the same; an inotify issue in Fedora. 
The `cat` command updates the brightness in polybar when it is one step behind, unless the command is run Immediately after the file update. 

**backlight.sh**
```
# Same issue
echo $val > path/brightness; 
cat path/brightness;

# Value updates accurately after short delay (wow what a surprise)
echo $val > path/brightness; 
sleep 1;
cat path/brightness;
```
Running the echo only, followed by a `cat` in the terminal, updates the brightness (unless I'm too fast; although 'too fast' feels like a variation of milliseconds)

**Comment by patrick96** [comment]
So this would mean that polybar receives an `inotify_event` but the new value in `/sys/class/backlight/...` is not observed immediately. Seems like very weird behaviour, but maybe the filesystem is only eventually consistent or something like this (which would explain that we receive the inotify event before the file is actually updated for us). Adding a forced timeout seems very hacky to me, there has to be a better way.

> I read #712 before, it didn't sound quite right because polybar was displaying a mostly accurate number, and does change on update.

My theory is that because you increase the brightness, your script first has to read the `backlight` file and thus polybar is updated, but always one step behind. Is polybar still always one step behind, even when you just pipe values into the `backlight` file without actually reading it? Also does polybar receive an inotify event when you do this (run with `-l trace`)?

**Comment by x70b1** [comment]
I can confirm this behavior. Polybar is always one step behind.
This sets the value correctly:

```
cat /sys/class/backlight/intel_backlight/brightness
```

If I write the value without reading it, it works immediately without delay. 

```
echo "400" > /sys/class/backlight/intel_backlight/brightness
```

**Comment by NBonaparte** [comment]
I think that sysfs files don't actually work with inotify, as the file contents are generated on the fly whenever they are accessed. In all logs I usually see it fall back to polling.

**Comment by M-Lewinski** [comment]
I had the same problem when I had to switching from intel to modesetting and xbacklight stopped working. In my custom bash script I was first reading from file _brigthness_ and than writing to it (similar as @x70b1). When I modified it so that I read value from file _actual_brightness_ then polybar status changed immediately without using sleep or any other kind of delay. I hope it helps somebody.

**Comment by dylnmc** [comment]
I'm experiencing this for `module/backlight` (it is displaying the previous backlight percentage).

Also, it seems like `module/xbacklight` is only displaying in increments of 5, which I find annoying, but at least it seems to update properly.

btw, I have git pulled, recompiled, and reinstalled *just now*.

**Comment by Jarwain** [comment]
@dylnmc It looks like `light` is making a similar mistake; they are reading from `brightness` then storing the value back into `brightness`. 

Btw I can confirm @M-Lewinski's fix works. Reading the value from `actual_brightness`, then writing to `brightness` results in instantaneous updating in polybar.

**Comment by Lomadriel** [comment]
> I think that sysfs files don't actually work with inotify, as the file contents are generated on the fly whenever they are accessed. In all logs I usually see it fall back to polling.

Yeah, I read the man page and I found a relevant section:
> Inotify reports only events that a user-space program triggers through the filesystem API.  As a result, it does not  catch  remote  events  that  occur  on  network  filesystems.
>        (Applications  must  fall back to polling the filesystem to catch such events.)  Furthermore, various pseudo-filesystems such as /proc, /sys, and /dev/pts are not monitorable with
>        inotify.

I will try to check if they is an API to do the job.

**Comment by Lomadriel** [comment]
Hello, I tried to fix this bug in #1689. On my laptop it fixes the bug, could someone confirm that my PR fixes the bug please. (file in sysfs are quite tedious to manipulate...)

**Comment by patrick96** [comment]
@x70b1 Can you check if #1689 fixes this issue for you?

**Comment by x70b1** [comment]
@patrick96 Works for me!

**Comment by eadwu** [comment]
> @dylnmc It looks like `light` is making a similar mistake; they are reading from `brightness` then storing the value back into `brightness`.
> 
> Btw I can confirm @M-Lewinski's fix works. Reading the value from `actual_brightness`, then writing to `brightness` results in instantaneous updating in polybar.

This no longer works, but instead causes the problem again. What's the correct way to update the `brightness` now?

```shell
bl_intel=/sys/class/backlight/intel_backlight
steps=15
tick=1

case $1 in
  -)
    new=$(( $(cat $bl_intel/actual_brightness) - $(cat $bl_intel/max_brightness) / ( $steps * $tick ) ))
    if (( $new < 0 )); then
      echo "0" | tee $bl_intel/brightness
      exit 1
    fi
    ;;
  +)
    new=$(( $(cat $bl_intel/actual_brightness) + $(cat $bl_intel/max_brightness) / ( $steps * $tick ) ))
    if (( $new > $(cat $bl_intel/max_brightness) )); then
      echo "$(cat $bl_intel/max_brightness)" | tee $bl_intel/brightness
      exit 1
    fi
    ;;
esac

echo "$new" | tee $bl_intel/brightness
```
