### ISSUE TITLE
i3 module ignores transparency if color is black

### ISSUE THREAD

**Issue by amisevsk** [jaagr/polybar#1183]
If I set the background colour for the i3 module to `#00000000` it is opaque. Setting it to anything other than zero causes it to behave as expected. Other modules / the bar itself do not have this problem.

`#00000000` -> opaque black
`#00010101` -> fully transparent
`#01000000` -> (pretty much) fully transparent

Version: Built locally off tag 3.1.0
System: Fedora 27

**Comment by patrick96** [comment]
Do you use gradients in you bar background?
What does polybar output when you run it with `-s`?
Please also post the offending config file (as minimal as possible).

**Comment by amisevsk** [comment]
Sorry, I was busy for awhile and forgot about this issue.

A minimal config should be:

```
[bar/min]
modules-left=i3-min
background = #00000000

[module/i3-min]
type=internal/i3
label-focused-background=#00000000
```
Here the focused workspace background is opaque black while the regular background is transparent. No gradients involved. 

The output with `-s` is (focused workspace is 4 -- didn't realize until later that this might be confusing)
```
%{l}%{A5:i3wm-wsprev: A4:i3wm-wsnext: A1:i3wm-wsfocus-1:} 1%{A A1:i3wm-wsfocus-2:} 2%{A A1:i3wm-wsfocus-3:} 3%{A A1:i3wm-wsfocus-4: B#000} 4%{B- A A1:i3wm-wsfocus-10:} 10%{A A A}
```
Changing `label-focused-background` to `#00000001` causes the `-s` output to be
```
%{l}%{A5:i3wm-wsprev: A4:i3wm-wsnext: A1:i3wm-wsfocus-1:} 1%{A A1:i3wm-wsfocus-2:} 2%{A A1:i3wm-wsfocus-3:} 3%{A A1:i3wm-wsfocus-4: B#00000001} 4%{B- A A1:i3wm-wsfocus-10:} 10%{A A A}
```
It looks like it's shortening `#00000000` to `#000`

**Comment by amisevsk** [comment]
Looking at it a bit further, it looks like this occurs whenever the color is `#xxxxxxxx` -- it gets shortened to `#xxx`, ignoring the alpha component.

**Comment by patrick96** [comment]
Yeah, for some weird reason it is doing that, no idea what the purpose of that would be. I'm going to open a PR to fix this.

**Comment by amisevsk** [comment]
@patrick96 Thanks!
