### ISSUE TITLE
Is it possible to add shadow? 

### ISSUE THREAD

**Issue by shelbym5** [jaagr/polybar#1185]
I feel like this is a dumb question but in trying to find a solution I only find people trying to get rid of shadow caused by compton. I'm actually trying to add a shadow on my polybar using compton. Am I missing an option somewhere? I'm using the stock compton config with some blur added. But even before adding the blur I still had no shadow with the stock config.

**Comment by patrick96** [comment]
Not really polybar related. I don't really use compton anymore but from peeking at the config, you probably have `no-dock-shadow = true;` set, which disables shadow for all dock-type windows (which polybar is one of).
