### ISSUE TITLE
${env:VARIABLE} not working in date module's label

### ISSUE THREAD

**Issue by leewdch** [jaagr/polybar#1186]
I'm on arch, using the latest polybar version from AUR. I tried following the wiki trying [the suggested workaround](https://github.com/jaagr/polybar/wiki/Formatting#format-tags-inside-polybar-config) for nested variables but it didn't work. This is the date module:
```
[module/date]
type = internal/date
interval = 1.0
date = %H:%M
date-alt = %H:%M:%S %A, %d %B %Y
format = <label>
label = ${env:BAR_DATE_LABEL:#ff0000} %date% %time%
label-font = 2
```
and this is the relevant .zshrc part:
```
# Define pywal colors variables for shell use
. "$HOME/.cache/wal/colors.sh"

# Custom colored icons for polybar
export BAR_DATE_LABEL="%{F$color6}%{F-}"
```

![bspwm](https://user-images.githubusercontent.com/11262717/39085975-4bbc7f4a-458b-11e8-9024-29decf7a01f4.png)

**Comment by NBonaparte** [comment]
`%date% %time%` should also be part of `BAR_DATE_LABEL`, as the variable must be exactly the value (cannot add text after it).

**Comment by NBonaparte** [comment]
That might help. Rofi probably hasn’t reloaded .zshrc.

**Comment by leewdch** [comment]
Logging out and in fixed the issue. Thanks for the help!
