### ISSUE TITLE
[FR] - make it possible to hide net-wireless when wired is connected

### ISSUE THREAD

**Issue by laur89** [jaagr/polybar#1189]
_Ususally_ wired connection is the default one, so it might be desirable to hide wireless-network module to decrease the real estate occupied by network modules.

Additionally/alternatively, perhaps we could use a common network module that covers both? (eg for displaying up and down bandwidth metrics for selected network interfaces, ie wired+wireless)

**Comment by x70b1** [comment]
You can already do this. Create modules for each interface. When an interface is down you can hide it. 

There is a Polybar option that offers you to display the traffic for all interfaces:
[`accumulate-stats = true`](https://github.com/jaagr/polybar/wiki/Module:-network)

**Comment by laur89** [comment]
> When an interface is down you can hide it.

That'd be via `format-disconnected` right? Ye that'd work, but with external logic that disconnects wifi when wired. To be fair, it _does_ sounds like something that shouldn't be in polybar anyways.

**Comment by patrick96** [comment]
> That'd be via format-disconnected right?

Correct, just set it to an empty string and the module will disappear.

If both interfaces are up and running polybar will of course display both modules, and I don't think that we should make polybar hide modules for interfaces that are still connected.

> Additionally, would accumulate-stats also include loopback adapter?

Yes

**Comment by patrick96** [comment]
Thinking a little more about this, I really don't think, different modules should influence each other this way
