### ISSUE TITLE
Can't disable ellipsis

### ISSUE THREAD

**Issue by M1dgard** [jaagr/polybar#1194]
From my MPD module config:
```ini
label-song          = %artist% - %title%
label-song-maxlen   = 22
label-song-ellipsis = false
```

But the ellipsis is still shown: ![screenshot_2018-04-26_01-28-48](https://user-images.githubusercontent.com/4283376/39278025-72f9bce6-48e0-11e8-9722-66de7b1e6290.png)

**Comment by patrick96** [comment]
Thanks for reporting.
Looking at the code, we never actually check the ellipsis setting, seems this was forgotten
