### ISSUE TITLE
General warnings on high utilization values

### ISSUE THREAD

**Issue by languitar** [jaagr/polybar#1196]
With i3 status there is a feature to change the color of a notification in case a value like CPU usage or filesystem usage exceed a threshold. This gives a pretty overview of critical system values. Is there anything similar for polybar apart from the temperature module? It would be pretty handy if colors could be adjusted based on numerical values and thresholds.

**Comment by patrick96** [comment]
This is currently not possible. But it is on our TODO list and has already been requested in #570 and #956.
