### ISSUE TITLE
How can I make my polybar transparent?

### ISSUE THREAD

**Issue by j4cobgarby** [jaagr/polybar#1197]
The title says it all, really. Is this possible?

**Comment by patrick96** [comment]
And then set `background = #00000000` in the bar section

**Comment by boanergepro** [comment]
Ya he instalado compton y en ubuntu y le he colocado background = #00000000 a la barra pero aun no veo la transparencia.
Debo hacer algo mas.?

**Comment by OmarRoman29** [comment]
Creo que agregando una seccion llamada dim-value y poniendo del 0.0 al 1.0 se coloca
