### ISSUE TITLE
undefined behavior for atoi

### ISSUE THREAD

**Issue by su8** [jaagr/polybar#1201]
https://github.com/jaagr/polybar/blob/ff39c9d09fd2c584a38264968244cf56966d37dc/src/modules/temperature.cpp#L53

What happens when `atoi` overflows - we get undefined behavior. Use one of the strto* functions instead as adviced in https://wiki.sei.cmu.edu/confluence/display/c/ERR34-C.+Detect+errors+when+converting+a+string+to+a+number

**Comment by patrick96** [comment]
You will probably never have temperatures above 2 million degrees celsius, but fair enough. I have switched over all our ato* cals to strto* calls, so at least we don't have any undefined behaviour anymore.
