### ISSUE TITLE
How to config hide, autohide or inteligent authide ? 

### ISSUE THREAD

**Issue by MoiRouhs** [jaagr/polybar#1225]
Hi there!

I'm trying to set up Polybar and I can't congure it, can you please help me with that?
Thanks in advance.

**Comment by patrick96** [comment]
Polybar doesn't support autohide as a config option. But you can use [Inter Process Messaging](https://github.com/jaagr/polybar/wiki/Inter-process-messaging) to send the `hide` and `show` commands to polybar using `polybar-msg`. For any sort of autohide feature you would have to write a script that calls `polybar-msg cmd hide` at appropriate times.

**Comment by arkeane** [comment]
Try my script https://github.com/arkeane/polybar_autohide.git

**Comment by ivanjermakov** [comment]
> A script that calls `polybar-msg cmd` hide at appropriate times

How can I send that call right after Polybar start?
Is there is a way to detect that Polybar started?

**Comment by GOKOP** [comment]
> > A script that calls `polybar-msg cmd` hide at appropriate times
> 
> How can I send that call right after Polybar start?
> Is there is a way to detect that Polybar started?

You can launch polybar in a script that sends the call after starting polybar

**Comment by rahatzamancse** [comment]
Try [hideit.sh](https://awesomeopensource.com/project/tadly/hideIt.sh). This does exactly what you want.

**Comment by tusqasi** [comment]
setting th

> Polybar doesn't support autohide as a config option. But you can use [Inter Process Messaging](https://github.com/jaagr/polybar/wiki/Inter-process-messaging) to send the `hide` and `show` commands to polybar using `polybar-msg`. For any sort of autohide feature you would have to write a script that calls `polybar-msg cmd hide` at appropriate times.

If you needed it to toggle between states of showing up and hidden. try
some key combination executing this  `polybar -msg cmd toogle`

**Comment by negativeExponent** [comment]
> setting th
> 
> > Polybar doesn't support autohide as a config option. But you can use [Inter Process Messaging](https://github.com/jaagr/polybar/wiki/Inter-process-messaging) to send the `hide` and `show` commands to polybar using `polybar-msg`. For any sort of autohide feature you would have to write a script that calls `polybar-msg cmd hide` at appropriate times.
> 
> If you needed it to toggle between states of showing up and hidden. try
> some key combination executing this `polybar-msg cmd toggle`

kinda related, but where can i get comple commands for polybar-msg? i have just recently discovered **cmd toggle** to hide bar, and **cmd restart** which i used to run as a different command using script (killall polybar for e.g.)

**Comment by patrick96** [comment]
@negativeExponent When you compile polybar, it will also compile polybar-msg.

**Comment by marrrrko** [comment]
I tried all kinds of things using `hideIt.sh` and never got it to behave how I wanted. In the end `xdotool` is what worked best

```
#!/bin/bash

# 1. Save this file as $HOME/bin/bottom-edge.sh and make it executable
# 2. Put following in i3 config
# exec --no-startup-id xdotool behave_screen_edge --delay 300 --quiesce 300 bottom exec "$HOME/bin/bottom-edge.sh"

polybar-msg cmd show

CURSOR_STILL_NEAR_BOTTOM=1

# We want polybar to stay open until cursor moves away from its top edge
# You can use `xdotool getmouselocation` to figure out that position.
TOP_OF_BOTTOM_EDGE=2080

while [ "$CURSOR_STILL_NEAR_BOTTOM" -eq 1 ]; 
do
    Y_POS=$(xdotool getmouselocation | cut -d " " -f2 | cut -d ":" -f2)
    Y_POS=$(($Y_POS))
    if [ "$Y_POS" -lt "$TOP_OF_BOTTOM_EDGE" ]; then 
        CURSOR_STILL_NEAR_BOTTOM=0
    fi
done

polybar-msg cmd hide
```

**Comment by bandundu** [comment]
Hi everyone,

I wanted to share a script I've created that successfully implements an autohide feature for Polybar. This script uses xinput to monitor key presses and polybar-msg for showing/hiding the bar. It's been tested and works well for my setup. Here's the script:

```bash
#!/bin/bash

# Threshold for inactivity in milliseconds (e.g., 300000ms = 5 minutes)
IDLE_THRESHOLD=2000

# ID of the keyboard device (replace with your keyboard ID)
KEYBOARD_ID=12

# Keycode for the Windows key (replace with the correct keycode)
WINDOWS_KEYCODE=133

# Temporary file for storing the last active time
LAST_ACTIVE_FILE="/tmp/last_active_time"

# Function to monitor Windows key press
monitor_windows_key() {
    xinput test $KEYBOARD_ID | grep --line-buffered "key press   $WINDOWS_KEYCODE" | while read -r line; do
        # Show Polybar silently
        polybar-msg cmd show > /dev/null 2>&1
        # Update the last active time
        echo $(date +%s%3N) > "$LAST_ACTIVE_FILE"
    done
}

# Start monitoring the Windows key in the background
monitor_windows_key &

# Initialize LAST_ACTIVE time
echo $(date +%s%3N) > "$LAST_ACTIVE_FILE"

while true; do
    CURRENT_TIME=$(date +%s%3N)
    # Read the last active time from the file
    LAST_ACTIVE=$(cat "$LAST_ACTIVE_FILE")
    IDLE_TIME=$((CURRENT_TIME - LAST_ACTIVE))

    # Show/Hide Polybar based on idle time
    if [ "$IDLE_TIME" -gt "$IDLE_THRESHOLD" ]; then
        # Hide Polybar silently
        polybar-msg cmd hide > /dev/null 2>&1
    fi
    # Check every 0.1 seconds
    sleep 0.1
done
```

Feel free to try it out and customize it for your needs. I hope this helps those looking for an autohide solution!
