### ISSUE TITLE
Font without unicode (e. g. Material icons)

### ISSUE THREAD

**Issue by Weegle99** [jaagr/polybar#1227]
It doesn't appear to be possible to use Material Icons in polybar as all icons does not have a unicode. For example signal_wifi_0_bar cannot be displayed.

https://material.io/tools/icons/?style=baseline

Are there any solution ?

Thanks

**Comment by patrick96** [comment]
If it's part of a font then it has a unicode codepoint. The webpage just doesn't give you the icon as a character but as an icon. Use [gucharmap](https://github.com/jaagr/polybar/wiki/Fonts#gnome-character-map) to finds the font icon to use inside polybar.

**Comment by Weegle99** [comment]
Thanks for your response.

Actually I have gucharmap installed and it does not show the glyph

**Comment by patrick96** [comment]
So you have gucharmap open, you have selected material icons in the top left, you have selected `View > By Unicode Block + Show only glyphs from this font`, you have navigated to the 'Private Use Area' section on the left and gucharmap doesn't display any glyphs?
Then you have probably not properly installed material icons, this is totally unrelated to polybar.

**Comment by Weegle99** [comment]
It must be a probelm with the font itself then, sorry for the issue

Do you know by any chance if it's possible to display svg icon rather than font icon in polybar ?

**Comment by patrick96** [comment]
You can't display non-font icons in polybar (yet). And just fyi, I use Material Icons in my bar, so there is nothing inherently wrong with the font, the problem is most likely with the installation

**Comment by Weegle99** [comment]
All I'm saying is that I installed (and reinstalled three times) the material font from AUR and some icon are missing from the font like for example the signal_wifi_0_bar
https://material.io/tools/icons/?search=wifi&icon=signal_wifi_0_bar&style=sharp

As I want to use the ramp-signal with material design it's (for me) currently not possible

**Comment by Weegle99** [comment]
Oh ok sorry for the misunderstanding (my english is not that good). Thank you for taking the time to search and answer me.

I guess I'll juste use standard wifi logo then

**Comment by patrick96** [comment]
No worries. Maybe also consider using the (confusingly named) [Material Design icons](https://materialdesignicons.com/) (not associated with google), it has a set of wifi icons.
