### ISSUE TITLE
Icon-Logo design proposal

### ISSUE THREAD

**Issue by Tobaloidee** [jaagr/polybar#1231]
Hi Sir @jaagr , I am a graphic designer and I want to contribute to your project by proposing an icon/logo design. If you like  & wanna use it, i will be gladly sending you the files as a gift for free. 

Here's my design Sir:

icon
![polybar-01](https://user-images.githubusercontent.com/36028424/39958898-230ddeec-563c-11e8-8318-d658c63ddf22.png)

logotype A
![polybar-02](https://user-images.githubusercontent.com/36028424/39958887-06ad7a5a-563c-11e8-9300-9f0b3d73ec09.png)

logotype B
![polybar-03](https://user-images.githubusercontent.com/36028424/39958889-0aeef882-563c-11e8-9c21-4b93654fde34.png)

If you have any suggestions or modifications please let me know.

Thanks and best regards,
-Tobaloidee

**Comment by patrick96** [comment]
Wow, thanks for the effort! I like it :smiley:
What do you guys think @jaagr, @NBonaparte, @skystrife ?

**Comment by Tobaloidee** [comment]
I'll wait for your opinions Sirs

**Comment by jaagr** [comment]
Looks awesome! 😄 Good job.

**Comment by Tobaloidee** [comment]
Im glad that you liked it Sir @jaagr :)

**Comment by patrick96** [comment]
So I guess, we use this as our logo ;)

@Tobaloidee do you have those images in an svg format (or another vector format)?

**Comment by Tobaloidee** [comment]
Yes Sir I will prepare it now and send the link to my files here for download..

**Comment by Tobaloidee** [comment]
here's the link to my drive where you can get all the needed files which I am gladly sending to this amazing project as my gift for free. 

https://drive.google.com/drive/u/0/folders/19I-JjSMbZvj8Tx_P6PfmjDqCySG30-bs

The drive includes all of SVG - Ai - ready to use PNG files 

I made a monochrome versions of the designs also and will update it with different color variations asap

summary of the files in the drive
![present](https://user-images.githubusercontent.com/36028424/40194075-c7ebd524-5a3b-11e8-89e7-f712ea7e03a8.png)

It is going to be rewarding for me to see this designs in your project's Readme and implementations.

Thanks so much for welcoming me to contribute!

Best regards,
-Tobaloidee

**Comment by Tobaloidee** [comment]
uploaded the SVG files in PR #1241 Sir. Thanks so much!

**Comment by patrick96** [comment]
@Tobaloidee thank you very much. I have now merged the PR to put the banner into the README. I have also saved all the other files to my machine locally and we will store them in an appropriate repository, once we get it setup. We will give you props in the `CONTRIBUTORS.md` file, once I create it (will try to open a PR today)

**Comment by Tobaloidee** [comment]
Thanks so much for your positive responses Sir's and for accepting my proposal.. Best regards to you all! :)
