### ISSUE TITLE
IPv6 support in net module

### ISSUE THREAD

**Issue by sqwishy** [jaagr/polybar#1234]
It might be nice to show IPv6 addressing status with a `%local_ip6%` label or something. `%local_ip%` only displays IPv4 addresses. One way is to use `getnameinfo` for AF_INET6 addresses, as is done with AF_INET currently, and ignore link local addresses. But I don't believe it's terribly uncommon to have multiple global IPv6 addresses on an interface and it's not entirely clear how to pick the "best" one.

i3status [creates a UDP socket](https://github.com/i3/i3status/blob/master/src/print_ipv6_addr.c) to determine the address that the operating system wants to use to reach some global address. That might be a good approach.

**Comment by patrick96** [comment]
Good idea, we should probably do this. I don't have any ipv6 addresses on any of my interfaces right now (except for loopback), but I'd like to get this done definitely by the next major release, maybe earlier.

**Comment by sqwishy** [comment]
I put [a commit](https://github.com/sqwishy/polybar/commit/f0639ab5eb5d2035c077982f13afe7485ec0405b) together to try to implement this. I don't really know if it does the right thing in other environments and it looks a bit goofy. I can fix up the styling and make a pull request if the implementation seems sound. Otherwise, whoever else does this might find it useful as a reference.

**Comment by patrick96** [comment]
Thanks for the effort. I just configured my interface to also have an ipv6 address and it seems to work fine for me. I think with a little bit of cleaning up, this could be merged. Would you be willing to work a little more on this? If so, please add that commit to a PR, I will look at it a little more thorough and see what we need to change before merging.

**Comment by sqwishy** [comment]
https://github.com/jaagr/polybar/pull/1239 Let me know what your suggestions are. I also put some of my own concerns in the description.
