### ISSUE TITLE
changing colors makes i3 module disappear

### ISSUE THREAD

**Issue by CarlosSaraviaJ** [jaagr/polybar#1235]
Hi there, I recently changed my polybar colors with pywal and the i3 workspaces module just disappears. Here's the changes I made:

```
[colors]
;background = #222
;background-alt = #444
;foreground = #dfdfdf
;foreground-alt = #555
;primary = #ffb52a
;secondary = #e60053
;alert = #bd2c40
background = ${xrdb:color0:#222}
foreground = ${xrdb:color7:#222}
foreground-alt = ${xrdb:color7:#222}
primary = ${xrdb:color1:#222}
secondary = ${xrdb:color2:#222}
alert = ${xrdb:color3:#222}
```

The commented settings show the i3 module normally, the new ones don't. I've no idea why, all other modules work fine.

**Comment by patrick96** [comment]
This is weird. Does the module disappear while polybar is running or does it just not appear when you restart the bar? Does the bar print any errors on the command line?

**Comment by CarlosSaraviaJ** [comment]
Fixed it. I ran polybar on a terminal and it gave me this:

`error: Disabling module "i3" (reason: The reference ${colors.background-alt} does not exist (no fallback set))`

Changed the reference and now it runs.

**Comment by ptnghi** [comment]
Hi @CarlosSaraviaJ what did you change it into ?

**Comment by patrick96** [comment]
He changed the reference to a key that exists in his config (see https://github.com/jaagr/polybar/wiki/Configuration#referencing-values)

**Comment by ptnghi** [comment]
Thanks for the reply. Ah I see, I misread his comment.
In my case, I double check that my key does exist in the color section still the does not exist message appear.
