### ISSUE TITLE
no workspace (i3) shown

### ISSUE THREAD

**Issue by skeebolt** [jaagr/polybar#1240]
Hello,

I have i3 with polybar running on a Thinkpad X220 - workspaces working.
On a T460s I dont get workspaces ('1' '2' '3') to show.
What am I missing ?
[config.txt](https://github.com/jaagr/polybar/files/2014578/config.txt)

Thank you for any help you can provide.

**Comment by patrick96** [comment]
You're using i3 but don't have the i3 module in your bar (it's in the config, but not added to `modules-(left|center|right)`).
