### ISSUE TITLE
Can't get mpd to work

### ISSUE THREAD

**Issue by ross-weir** [jaagr/polybar#1243]
Hi guys. Trying to get mpd to work, not getting any buttons on the bar and can't really see any reason why from my configs and logs, hopefully you guys might see something I'm missing. 

Relevant files:

- [Polybar Log](https://gist.github.com/ross-weir/ab61023f662777d14550755cba1f2ee1)
- [Polybar Config](https://gist.github.com/ross-weir/f8d30ad98fa30f3d7467345c609fbd35)
- [Polybar Build Logs](https://gist.github.com/ross-weir/0bae1728ede5fc91ba57ca8d06b16830)
- [Mpd Config](https://gist.github.com/ross-weir/14c85eafd82700ddb9ad720e2243f858)
- [Results from ALSA log](http://www.alsa-project.org/db/?f=55e17cd3667e60d087341129f9482588117482ee)

Any advice/direction would be great not really sure where to go from here. Thanks.

**Comment by patrick96** [comment]
> * module/mpd: Hiding module since queue is empty

The mpd module didn't produce any output. Most likely because mpd is offline (and by default `label-offline` is an empty string). You can confirm this by setting `label-offline = Offline`.

**Comment by ross-weir** [comment]
Possibly a silly question but first time using polybar/mpd.

How do I add to queue? Can I do this with polybar? I thought having mp3s in my music folder/playlist folder was enough?

**Comment by patrick96** [comment]
Oh it's actually the mpd queue that is empty and not an internal polybar queue. You cannot add songs to the queue with polybar, use some proper mpd client like mpc or ncmpcpp

**Comment by ross-weir** [comment]
Awesome. Thanks for your time
