### ISSUE TITLE
Can't scale PCF

### ISSUE THREAD

**Issue by SamHH** [jaagr/polybar#1244]
I can't seem to scale my font if I set it to [scientifica](https://github.com/NerdyPepper/scientifica) (PCFs via [this](https://aur.archlinux.org/packages/scientifica-bdf/) AUR package).

It loads the correct font, but no `size` or `pixelsize` setting or combination thereof changes the size.

What am I missing? :smile:

**Comment by patrick96** [comment]
From what I can tell, the font doesn't seem to have any other size than 11 (see https://github.com/NerdyPepper/scientifica/issues/6 and https://github.com/NerdyPepper/scientifica/issues/15). There seems to be a double script in the repo that can increase the font size for high dpi displays.

**Comment by SamHH** [comment]
Ah that's disappointing. Thanks for looking at it for me, I'm clueless about fonts. :+1:
