### ISSUE TITLE
error: tray: Failed to put tray above 0x1200002 in the stack

### ISSUE THREAD

**Issue by finpluto** [jaagr/polybar#1245]
Hello, when I run polybar with the example config first time, it throw me an error like
```
error: tray: Failed to put tray above 0x1200002 in the stack (XCB_MATCH (8))
```
Why did it happend and how to fix it ? Thanks for your help!

**Comment by patrick96** [comment]
But is polybar working properly otherwise? The error was added because I think it's the cause for #425, it means that the polybar tray window is not directly above the polybar window, which may cause the tray to overlap with fullscreen windows. What WM are you using?

I haven't been able to fix this though.

**Comment by finpluto** [comment]
Yes the polybar still working with this warning. I'm using the i3wm, and I disabled the tray temporary. Now everything works fine. Thanks for your work!

**Comment by annata83** [comment]
Hey, I am reopening this just to ask if is possible to fix it?
here is my output:

`error: tray: Failed to put tray above 0x1000002 in the stack (XCB_MATCH (8)).
`


$`polybar -vvv`
```
Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/sbin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

polybar installed thru AUR.

**Comment by patrick96** [comment]
@annata83 See  #425. This is being worked on
