### ISSUE TITLE
Font `size` ineffective for NotoEmoji

### ISSUE THREAD

**Issue by FliiFe** [jaagr/polybar#1248]
Whatever I do and no matter the font order, NotoEmoji is always rendered in huge font (huge as in close to 10 times the bar's height), and none of `size` and `pixelsize` change the font size.

It works fine for other fonts.
The vertical offset does work.

**Comment by patrick96** [comment]
Duplicate of #905 

I wasn't able to fix it for myself, others seem to have managed though
