### ISSUE TITLE
xpp/event.hpp - no such file or dir?

### ISSUE THREAD

**Issue by issueWithLife** [jaagr/polybar#1254]
Apologies is this a bad question but just can't seem to get this working for the life of me!

Heres the error i'm getting
 
  

> [  6%] Building CXX object bin/CMakeFiles/polybar.dir/components/bar.cpp.o
    In file included from /.config/include/components/bar.hpp:14:0,
                 from /.config/src/components/bar.cpp:3:
    /.config/include/x11/types.hpp:3:10: fatal error: xpp/event.hpp: No such file or directory
     #include <xpp/event.hpp>
          ^~~~~~~~~~~~~~~
    compilation terminated.
>

i've tried googling the issue but can't seem to find a fix for it - if anyone could point me in the right direction it'd be much appreciated

**Comment by patrick96** [comment]
Hmm looks like some issue with the xpp submodule. Can you post the output when you ran `cmake` and also the whole `make` output.

**Comment by issueWithLife** [comment]
Can do - 

cmake: https://pastebin.com/1R06RfyD
make: https://pastebin.com/iJ4ejQpv

Thanks for replying so fast - really want to get this working!

**Comment by patrick96** [comment]
Looks like a different error message than the original one, but that one's probably the root cause and we know how to fix it, see [Known-Issues](https://github.com/jaagr/polybar/wiki/Known-Issues)
