### ISSUE TITLE
using polybar on android tablet as multiple monitor

### ISSUE THREAD

**Issue by DrDonkey** [jaagr/polybar#1256]
Hello, 
I am using my tablet as 2nd monitor.
I did it using following commands:
```
xrandr --newmode "1368x1024_60.00"  116.52  1368 1456 1600 1832  1024 1025 1028 1060  -HSync +Vsync
xrandr --addmode VGA-0 1368x1024_60.00
xrandr --output VGA-0 --mode 1368x1024_60.00 --right-of LVDS
x11vnc -clip 1368x1024+1369+0
```

Then I connect android using a vnc client.
I want to show polybar on that extended one.

Is that possible?

When I do `xrandr` I get the following
``` 
Screen 0: minimum 320 x 200, current 2734 x 1024, maximum 8192 x 8192
LVDS connected primary 1366x768+0+0 (normal left inverted right x axis y axis) 309mm x 174mm
   1366x768      59.99*+  39.94  
   1280x720      59.97  
   1152x768      59.95  
   1024x768      59.95  
   800x600       59.96  
   848x480       59.94  
   720x480       59.94  
   640x480       59.94  
HDMI-0 disconnected (normal left inverted right x axis y axis)
VGA-0 disconnected 1368x1024+1366+0 (normal left inverted right x axis y axis) 0mm x 0mm
   1368x1024_60.00  60.00*
```
But when I do polybar -m I get the following:
```
VGA-0: 1368x1024+1366+0 (XRandR monitor)
LVDS: 1366x768+0+0
```
Polybar lists out the VGA-0 monitor but xrandr says its disconnected.

Any solutions?

**Comment by patrick96** [comment]
I'm assuming VGA-0 is the android tablet. What happens, if you specify `monitor = VGA-0` in your bar config? Does it not show up on the tablet?

**Comment by DrDonkey** [comment]
I am so sorry for not being able to reply.
But I tried it already but didn't work that time.
Yes, it **works(Had to relaunch the bar).**
