### ISSUE TITLE
Blank bar on Debian

### ISSUE THREAD

**Issue by bbaserdem** [jaagr/polybar#1257]
I have a working config, which works perfectly for Arch.

I built polybar from git for a machine with Debian 9 (squeeze). On bspwm.

* Have all the dependencies, compiles without errors
* Did not have to do the debian xcb-proto fix. (Trying to compile with downgraded version gives errors anyway)
* Confirmed with FC_DEBUG=1 that it is not a font rendering issue, my fonts are picked out. fc-match also finds my fonts just fine. (Thought it was due to fonts; I installed them locally)

I only see the systemtray, and nothing else. The bar is only its background color. The modules are not disabled; just not there. There are no errors being thrown by polybar to the terminal.

**Comment by SeraphyBR** [comment]
I had the same problem in my funtoo.....

**Comment by NBonaparte** [comment]
Is there any difference in the output when you run with trace logging?

**Comment by patrick96** [comment]
Do you get any dropping unmatched character warnings?

Could be similar to #706, can you make sure that none of your fonts contain the `pixelsize` parameter

**Comment by bbaserdem** [comment]
Turns out its a duplicate. Using `size` instead of `pixelsize` fixed it.
