### ISSUE TITLE
Module doesn't update label

### ISSUE THREAD

**Issue by amstramgram** [jaagr/polybar#1267]
Hi, 
i have strange unknow problem. 
So, i have custom module script for weather and network. When i launch polybar no problem that displayed correctly the label, but polybar doesn't refresh/update label (if my network change or if weather change) and i don't know why?

I search in lot of forum, in wiki but nothing. So i hope you can help me.

Thank you

---

weather.conf
```
[module/weather]
type = custom/script
interval = 900
format = <label>
exec = ~/.config/i3/scripts/weather.sh
```
weather.sh
```
if ping -c 1 176.34.131.233 &> /dev/null; then
	echo "My weather"
else
	echo "waiting..."
fi
```
network.conf
```
[module/network]
type = custom/script
interval = 3
tail = true
exec = ~/.config/i3/scripts/network.sh
click-left = kill -USR1 %pid%
```
network.sh
```
t=0
ICON=

if ping -c 1 176.34.131.233 &> /dev/null; then
	IP=$(curl -s http://whatismyip.akamai.com)
	SSID=$(iwgetid -r)
else
	IP="no IP"
	SSID=" WIFI off"
fi

toggle(){
	t=$(((t + 1) % 2 ))
}

trap "toggle" USR1

while true; do
	if [ $t -eq 0 ]; then
		echo "${ICON} ${SSID}"
	else
		echo "${ICON} ${IP}"
	fi
	sleep 1 &
	wait
done
```

**Comment by patrick96** [comment]
The interval on your weather script is 900 seconds, so it will only get updated every 15 minutes.
In your network script, you only update IP and SSID when the script starts but not after

**Comment by amstramgram** [comment]
ok so for weather script i need to add exec-if? But how can add default text if not exec?
for network i have interval of 3, why he doesn't update after?
