### ISSUE TITLE
New app Icons won't open unless previous opened ones closed

### ISSUE THREAD

**Issue by SirSharanChakradhar** [jaagr/polybar#1273]
I'm a newbie, I have added application icons to bottom polybar such as chrome, terminal, thunar --etc. The problem is whenever I click on the icon, it opens the application and when I click the other icon to open, it doesn't. When I close the first clicked application then the second application opens. May I know how to resolve it?

**Comment by NBonaparte** [comment]
Use `&` at the end of every command: `chromium &`

**Comment by SirSharanChakradhar** [comment]
Thanks, It works well now. 

One more, How to show the app name when I place mouse arrow on the icon?

**Comment by NBonaparte** [comment]
If you're asking for a tooltip, it's been requested (#534) but not implemented yet.

**Comment by SirSharanChakradhar** [comment]
How about entire bar autohide and bar placing at left or right side of the screen!

![image](https://user-images.githubusercontent.com/40011522/41143579-182037da-6b3d-11e8-9b19-8cfc26144282.png)

**Comment by patrick96** [comment]
Both have already been discussed (#1269, #1225), both isn't possible right now
