### ISSUE TITLE
Transparency not working for bottom bar

### ISSUE THREAD

**Issue by Chostakovitch** [jaagr/polybar#1277]
Hi,

Maybe I just misunderstood how transparency/polybar works, sorry in advance if so.

My problem is that transparency (set with ARGB) works individually with a top or a bottom bar, but together the bottom bar has no transparency.

Minimal config with screenshot below : 
```
[colors]
background = #bb2f343f

[bar/common]
monitor = ${env:MONITOR:HDMI-0}
background = ${colors.background}
modules-center = xwindow

[bar/chostytopbar]
inherit = bar/common

[bar/chostybottombar]
inherit = bar/common
bottom = true

[module/xwindow]
type = internal/xwindow
label = %title%
```
![polybar](https://user-images.githubusercontent.com/12672619/41253978-4968548a-6dc2-11e8-8dfc-4fdec0af741e.jpg)

System configuration : 
* OS : 4.16.13-2-ARCH 
* Polybar v3.1.0-69-g0a8a326
* i3 version 4.15.0.1 (and compton with no extra config)

Do not hesitate to ask for more details.

Thanks in advance !

**Comment by lebarondemerde** [comment]
Are you sure that is not working on the bottom bar? The wallpaper does not seem to have anything but a solid cream color at the bottom. :)

**Comment by Chostakovitch** [comment]
Wow. I must be really tired, obviously you're right. Sorry for that... :)
