### ISSUE TITLE
[mpd] <icon-repeatone> ---> <icon-single>

### ISSUE THREAD

**Issue by lebarondemerde** [jaagr/polybar#1279]
Hi.

Unless I am experiencing somehow (FreeBSD) something different the `<icon-repeatone>` parameter actually match with the single play. I mean, when the `<icon-repeatone>` is ON the option enabled on mpd is the one to play the track one time (and stop).

In order to get an actual 'repeat one', in a meaning of to have one track repeating indefinitely, `<icon-repeat>` and `<icon-repeatone>` (single) should both be ON.

Please, consider renaming` <icon-repeatone>` to `<icon-single>` to avoid a misleading behavior.

Thanks!

**Comment by patrick96** [comment]
You're right. On my machine `<icon-repeatone>` doesn't affect the repeating behaviour at all as well. Going to open a PR to deprecate `<icon-repeatone>` and replace it with `<icon-single>`

**Comment by lebarondemerde** [comment]
Thanks!
