### ISSUE TITLE
<animation-discharging> is not a valid format tag for "format-discharging"

### ISSUE THREAD

**Issue by leewdch** [jaagr/polybar#1280]
polybar 3.1.0-git
Features: +alsa +curl -i3 +mpd +network

```
[module/battery]
type = internal/battery
full-at = 99
battery = BAT0
adapter = AC
poll-interval = 5
format-charging = <animation-charging> <label-charging>
format-discharging = <animation-discharging> <label-discharging>
label-charging = %percentage%%
label-discharging = %percentage%%
label-full = 
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750
animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
animation-discharging-framerate = 500
```

> ; Available tags:
> ;   \<label-discharging> (default)
> ;   \<bar-capacity>
> ;   \<ramp-capacity>
> ;   \<animation-discharging>

This is the console output when I manually launch polybar in the terminal

> error: Disabling module "battery" (reason: \<animation-discharging> is not a valid format tag for "format-discharging")

**Comment by patrick96** [comment]
`animation-discharging` isn't part of a release yet, you'll have to compile against the latest commit to get it. I have added a note to the wiki
