### ISSUE TITLE
Polybar blinking from time to time

### ISSUE THREAD

**Issue by Draiken** [jaagr/polybar#1283]
Every few minutes the bar blinks on the highlighted area. The entire area becomes white, then back to normal. I have two monitors and it seems to blink independently on both bars.

I recently switched from the stable Polybar to the git version to get pulseaudio support and this started to happen.

Screenshot
![deepinscreenshot_select-area_20180614072456](https://user-images.githubusercontent.com/287889/41406984-5dccea74-6fa4-11e8-961d-7e7be57aa3bd.png)

Polybar version
```
polybar 3.1.0-145-gd1d307d

Features: +alsa +curl +i3 -mpd +network +pulseaudio

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```
Using Xorg with i3

**Comment by SirSharanChakradhar** [comment]
Hey, How did you get those 4 colour icons at the end? Can you share the code for that?

**Comment by NBonaparte** [comment]
That's the systray.

**Comment by patrick96** [comment]
I have never seen this happen before. Can you please also post the config you are using.

**Comment by Draiken** [comment]
My polybar config: https://gist.github.com/Draiken/11876260505a9cdefc21b5cb5ecd7ad6

Sorry I haven't had time to test the single module, I'll see if I can do that today
@SirSharanChakradhar the colors are there... I just used two colors and changed the icons to use that

**Comment by patrick96** [comment]
Is this still happening?

**Comment by Draiken** [comment]
I deactivated some of my elements and it stopped happening.
Not sure if it got fixed on an update or I'm not using the cuplrit, tho.

I'll reopen this if it happens again.
