### ISSUE TITLE
mpd and unix socket

### ISSUE THREAD

**Issue by soywod** [jaagr/polybar#1285]
Is there a way to set a unix socket path instead of a host / port ? I tried but no way to get this working, maybe I'm missing sth obvious ?

**Comment by patrick96** [comment]
Hmm, setting the `host` to the full path to the socket should work, according to the mpd documentation in `mpd/connection.h`:
```c
/*
...
 * @param host the server's host name, IP address or Unix socket path.
 * If the resolver returns more than one IP address for a host name,
 * this functions tries all of them until one accepts the connection.
 * NULL is allowed here, which will connect to the default host
 * (using the MPD_HOST environment variable if present).
...
 */

What exactly did you try?
```

**Comment by soywod** [comment]
I've found the solution, in fact, we just need to put the full path to the socket (I was trying with `sock:/` or `socket://` in front of the path). Maybe a little add in the doc could be nice (or an example). Sorry for the disagreement !
