### ISSUE TITLE
polybar order

### ISSUE THREAD

**Issue by benbuch** [jaagr/polybar#1290]
is there a way to control polybar order? lets say i have two polybar's on top, how would i control which would be top and which bottom?

at the moment its randomly loading their position and i have to reload launch.sh and hope it gets to the right position.

**Comment by patrick96** [comment]
There is no built in way. If you put a big enough waiting period between launching the bars, the order 
should always be the same. So you should be able to do that inside the launch script, it depends on the WM though

**Comment by benbuch** [comment]
yup that worked! thanks.
