### ISSUE TITLE
Switching to workspaces and moving container to (same) workspace map to different workspaces

### ISSUE THREAD

**Issue by mor3dr3ad** [jaagr/polybar#1300]
Hey all,

this problem has me stumped: 

I am running i3-gaps version 4.15.0.1 on Arch linux with polybar. 

My i3 config has the following workspacewise: 
       
        bindsym $mod+grave workspace h0me
        bindsym $mod+1 workspace term1nal
        bindsym $mod+2 workspace co2e
        bindsym $mod+3 workspace teleg3am
        bindsym $mod+4 workspace edi4or
       
        bindsym $mod+Shift+grave move container to workspace h0me
        bindsym $mod+Shift+1 move container to workspace term1nal
        bindsym $mod+Shift+2 move container to workspace co2e
        bindsym $mod+Shift+3 move container to workspace teleg3am
        bindsym $mod+Shift+4 move container to workspace edi4or

My polybar has the following:

        ws-icon-0 = h0me;a
        ws-icon-1 = term1nal;b
        ws-icon-2 = co2e;c
        ws-icon-3 = teleg3am;d
        ws-icon-4 = edi4or;e

Where a through e are icons. 

I would expect polybar to display the items next to the name, both when I switch to a new workspace and when I move a container there (polybar is configured accordingly).

However, polybar does only display both icon and name, when I move a container to a new workspace. This workspace is then not mapped to `$mod+1`; I can only swtich to that workspace by searching or cycling through all workspaces. 

When I switch to a workspace, I get a new workspace with the same name, but no icon.

This behaviour only holds for workspaces 1 through 3, all others work accordingly. 

Any ideas what might be happening here? 

If I can provide more information, please let me know.

![2018-06-27-144015_1920x1080_scrot](https://user-images.githubusercontent.com/26748179/41978188-917c5026-7a21-11e8-8aa7-6c1f913a600c.png)

**Comment by orestisf1993** [comment]
This can be closed here since it's an i3 bug/feature: https://github.com/i3/i3/issues/3316#issuecomment-405120134
