### ISSUE TITLE
Polybar can't load all the unicode characters from Font Awesome 5

### ISSUE THREAD

**Issue by leewdch** [jaagr/polybar#1301]
At first I tried using the ttf-font-awesome package (from the Arch package manager), since it failed showing all the icons I uninstalled it and manually added the otf fonts from the Font Awesome website.
Now polybar can only load the flag and clock icon. This is the console output:

> warn: internal/volume is deprecated, use internal/alsa instead
> warn: Dropping unmatched character  (U+f001)
> warn: Dropping unmatched character  (U+f1eb)
> warn: Dropping unmatched character  (U+f025)
> warn: Dropping unmatched character  (U+f240)
> warn: Dropping unmatched character  (U+f001)
> warn: Dropping unmatched character  (U+f076)
> warn: Dropping unmatched character  (U+f1eb)
> warn: Dropping unmatched character  (U+f025)
> warn: Dropping unmatched character  (U+f240)

![test](https://user-images.githubusercontent.com/11262717/41999077-c5c4d412-7a5c-11e8-889b-57691dfbe131.png)

This is the relevant config part:
```
font-0 = DejavuSansMono:size=10;4
font-1 = NotoSansCJKJP:size=10;4
;font-2 = FontAwesome:size=10;4
font-2 = Font Awesome 5 Free:size=10;4
```

**Comment by JohannMartinet** [comment]
Update your config : 
```
font-1 = FontAwesome5Free:style=Solid:size=10;4
font-2 = FontAwesome5Free:style=Regular:size=10;4
font-3 = FontAwesome5Brands:style=Regular:size=10;4
```
you can list font with 
`fc-list | grep Awesome`

**Comment by leewdch** [comment]
Same result, unmatched characters

![test](https://user-images.githubusercontent.com/11262717/42065191-d988e29e-7b39-11e8-8c7e-24e4d361f6ad.png)

**Comment by patrick96** [comment]
Please read the [Font Wiki page](https://github.com/jaagr/polybar/wiki/Fonts). It should have everything you need to debug this issue yourselves. Fonts can have different names on different systems, so not all solutions other people propose will work one-to-one. Also make sure the icon you are trying to display is actually available in the fonts you loaded.

**Comment by leewdch** [comment]
I found the solution. The archive you can download from the Font Awesome website (the free version one) offers 3 different fonts containing each different portions of the +1000 free icons. The difference with Font Awesome 4 is that it's a single font file, on the other hand you need to load the three font awesome 5 fonts if you want to be 100% sure your characters will be correctly displayed on the bar.

This is the fc-list matching the fonts I downloaded from the website:

> $ fc-list |grep ".local/share/fonts"
> /home/leewdch/.local/share/fonts/Font Awesome 5 Free-Solid-900.otf: Font Awesome 5 Free,Font Awesome 5 Free Solid:style=Solid
> /home/leewdch/.local/share/fonts/Font Awesome 5 Free-Regular-400.otf: Font Awesome 5 Free,Font Awesome 5 Free Regular:style=Regular
> /home/leewdch/.local/share/fonts/Font Awesome 5 Brands-Regular-400.otf: Font Awesome 5 Brands,Font Awesome 5 Brands Regular:style=Regular

and this is the relevant part in my polybar config:

> font-0 = DejavuSansMono:size=10;4
> font-1 = NotoSansCJKJP:size=10;4
> ;font-2 = FontAwesome:size=10;4
> font-2 = Font Awesome 5 Free Regular:size=10;4
> font-3 = Font Awesome 5 Free Solid:size=10;4
> font-4 = Font Awesome 5 Brands Regular:size=10;4

The commented line is the previous Font Awesome 4 file I used to display the icons. As you can see I just added all the different font files using the names displayed on the very right with fc-list

**Comment by i386angel** [comment]
> Update your config :
> 
> ```
> font-1 = FontAwesome5Free:style=Solid:size=10;4
> font-2 = FontAwesome5Free:style=Regular:size=10;4
> font-3 = FontAwesome5Brands:style=Regular:size=10;4
> ```
> 
> you can list font with
> `fc-list | grep Awesome`

Thanks, you can fix my error.

**Comment by betkyss** [comment]
sudo pacman -S ttf-font-awesome

**Comment by Rodieche** [comment]
> > Update your config :
> > ```
> > font-1 = FontAwesome5Free:style=Solid:size=10;4
> > font-2 = FontAwesome5Free:style=Regular:size=10;4
> > font-3 = FontAwesome5Brands:style=Regular:size=10;4
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > you can list font with
> > `fc-list | grep Awesome`
> 
> Thanks, you can fix my error.

I had the same problem, this solved it
