### ISSUE TITLE
Make polybar quit when its screen is detached

### ISSUE THREAD

**Issue by memeplex** [jaagr/polybar#1302]
There are some suggestions to make polybar work with multiple monitors in https://github.com/jaagr/polybar/issues/763. That's fine, I already have a shell function to enable/disable dual screen using xrandr, I only have to `killall polybar` and reenable it for all attached screens after calling xrandr.

But it could be better, it could avoid killing and restarting N-1 bars just for the sake of the detached one. Now, the specific process could be identified and properly killed, but passing `MONITOR` as an environment variable doesn't make it an easy target for pkill or killall. Maybe one could be more explicit, pass a different bar name in the command line, then use section inheritance or some trick like that, so that the process is more easily identifiable from its command invocation. Or one could keep its PID somewhere. Etc.

But all this would be cleaner if polybar killed itself once its screen is no longer there. It seems a sensible behavior to me, I wouldn't even add an option for this but make it the default and only behavior.

**Comment by x70b1** [comment]
The solution you are looking for is `autorandr`: [phillipberndt/autorandr](https://github.com/phillipberndt/autorandr)

This way you have a central point to configure everything like this. You can predefine desktop setups with autorandr.
Define a bar for every display. With `autorandr` you can set and destroy them.

**Comment by memeplex** [comment]
Great tip, thanks! I didn't know about autorandr, I'm going to take a look at it.

Still, I feel fond of my super simple solution and, anyway, don't you think it's sensible to make an instance without screen kill itself?

**Comment by x70b1** [comment]
That should decide a developer :wink:
Unless you manage your displays with something like `autorandr` you dont need it.

**Comment by patrick96** [comment]
If you have `screenchange-reload = true` wouldn't polybar just fail to restart on the monitor if that monitor disconnects, which would effectively be polybar killing itself when the screen is no longer connected?

**Comment by memeplex** [comment]
That's a good idea, I didn't know about reloading when I reported this, will give it a try and let you know.
