### ISSUE TITLE
Hiding Module on External Display

### ISSUE THREAD

**Issue by SethGower** [jaagr/polybar#1307]
Is there any way that I can hide a certain module on my bar on an external display? In order to project, I use `mons`, I would like it to be hidden when I use `mons -d`. Both of my bars show up, but I have a module for my ip address, and I don't want that projected to the entire class, since it is a public IP. My config file can be found [here](https://gitlab.com/SethGower/dotfiles/blob/master/.config/polybar/config)

**Comment by BVollmerhaus** [comment]
The only way to do that currently is to create another bar definition for the secondary screen and assign a different set of modules to it, leaving out the ones you don't want. For example, if you wanted to remove some modules from your top bar when it's on the secondary screen, you could do:

```ini
[bar/top]
monitor = <your primary monitor>
inherit = bar/base

tray-position = right
tray-padding = 2

modules-left = ip hostname linkspeed user
modules-center = date
modules-right = volume xbacklight xkeyboard memory cpu battery wlan
```

```ini
[bar/top-secondary]
monitor = <your secondary monitor>
inherit = bar/top

; Tray can only be on one bar at a time, so it has to be removed from the secondary one.
tray-position =

; Override the displayed modules, leaving out the ones you don't want.
modules-right = volume memory cpu wlan
```

If you don't want to hardcode the monitors and instead launch the primary bar on the screen which has the `xrandr` primary flag and the secondary bar on all other screens, you need to write a shell script which queries `xrandr` and launched the appropriate bars. You can find an example [here](https://github.com/jaagr/polybar/issues/763#issuecomment-331604987), but you'll have to extend the loop to `grep` whether the current monitor is primary or not and launch the correct bar.

**Comment by NBonaparte** [comment]
I'll close this as it seems @BVollmerhaus has sufficiently answered the question.
