### ISSUE TITLE
AUR: Mess-up with jsoncpp

### ISSUE THREAD

**Issue by adri326** [jaagr/polybar#1308]
Trying to build `polybar-git` off AUR, it wanted me to upgrade jsoncpp - I had to downgrade it for some reason - to 1.8.4-2, what I did.

The build succeeded, and I tried running polybar, which then spit out to me that it couldn't find `libjsoncpp.so.19`, which is the shared library issued by `jsoncpp-1.8.4-1`.

Downgrading jsoncpp back to `1.8.4-1` fixes the issue and polybar runs flawlessly.

I don't have the error message anymore, but it was the common "couldn't load shared library" error, with the file I mentioned earlier.

**Comment by NBonaparte** [comment]
`jsoncpp-1.8.4-2` uses `libjsoncpp.so.20` for me. Did you compile polybar after upgrading jsoncpp?

**Comment by patrick96** [comment]
See [Known-Issues](https://github.com/jaagr/polybar/wiki/Known-Issues#error-while-loading-shared-libraries-libjsoncpp). As @NBonaparte mentioned, you will need to recompile polybar.
