### ISSUE TITLE
No text is being displayed with bar.

### ISSUE THREAD

**Issue by iamriles** [jaagr/polybar#1311]
I spent about 2 hours yesterday searching through forums and trying to figure out poly bar is not displaying any sort text. The only thing being displayed on the bar is the volume and brightness sliders. I removed all the unicode characters from the config file to see if that was causing problems. Im on debian stable with i3 and im using Nerd Fonts Patched fonts. I also built from source using all the optional dependencies (using both GCC and Clang).

**Comment by NBonaparte** [comment]
Did you try using a different font?

**Comment by iamriles** [comment]
I tried multiple both from nerdfonts and system fonts I'm doing a fresh system install off Debian unstable to see if that does anything. What is really strange is the volume and brightness sliders change.
