### ISSUE TITLE
After reboot volume indicator not working

### ISSUE THREAD

**Issue by Alezzzander** [jaagr/polybar#1313]
![1531576477_1654_14072018_602x37](https://user-images.githubusercontent.com/29925387/42725100-e5db9bfa-8786-11e8-960d-fc2da048b485.png)
![1531576672_1657_14072018_733x25](https://user-images.githubusercontent.com/29925387/42725122-4099d124-8787-11e8-9f32-5dc940a98af6.png)

Hi!
After executing `polybar example`  ,there is volume indicator   on the bar, but after system or i3 reboot ,it disappearing.
` killall polybar`  and  `polybar example`  - Volume indicator is on the bar.
Have no errors after starting
Polybar Version 3.1.0-git
How to fix this problem?

**Comment by su8** [comment]
https://github.com/jaagr/polybar/wiki/Module:-pulseaudio , https://github.com/jaagr/polybar/issues/1176

**Comment by NBonaparte** [comment]
Which volume module are you using?

**Comment by Alezzzander** [comment]
Im using volume module now,but i have pulseaudio installed. How to add this module to polybar? 
Im having "Disabling module "pulseaudio" (reason: unknown module: internal/pulseaudio)" error.

**Comment by NBonaparte** [comment]
Since this is fixed, I'll close it. If you want to use the pulseaudio module, you should rebuild polybar from the newest commit (polybar-git on AUR if you use arch)
