### ISSUE TITLE
Don't create window with polybar -s

### ISSUE THREAD

**Issue by eadwu** [jaagr/polybar#1314]
Is there any way I can remove the empty window or maybe set `monitor` to null? Trying to get the output onto `xsetroot -name` for dwm. Besides the window, polybar adds `%{r}` to the beginning and `module/alsa` outputs `%{A1:volmute: A4:volup: A6:voldown:} ... %{A A A}` which isn't really desired for the statusbar (or at least for me). For the text, manipulating it with `sed` and `cut` is working fine though the window is the problem. 

Looks like `polybar -s` does its intended behavior as it only says it won't draw it to the window. So my question is better worded as is there a way to prevent the window from being created while using `polybar -s`.

**Comment by NBonaparte** [comment]
There isn't a way to do that right now.

Just curious, why are you using polybar as a text output rather than a complete bar?

**Comment by eadwu** [comment]
Since `dwmstatus` reads from stdout while I don't seem be able to get xworkspaces to work.

**Comment by NBonaparte** [comment]
Does this help? 6d934373b0dcc5e1646f88d0d5e796f252af7636

**Comment by eadwu** [comment]
Sorry for the late response, but the commit does stop the window from being created but at the same time, nothing is being outputted to stdout (https://imgur.com/t6uj8vB).

**Comment by NBonaparte** [comment]
This should work now: 757545f

**Comment by eadwu** [comment]
Just tested it and it works, thanks! I'll leave this open until the pull request is merged.
