### ISSUE TITLE
Build fails on OpenBSD

### ISSUE THREAD

**Issue by hubbcaps** [jaagr/polybar#1316]
Hello,

I'm attempting to build Polybar on the current OpenBSD.

cmake goes well, and then the build attempt is where it gets sticky. I receive three errors, two about *this not being a pointer in the file.cpp and one about an int not being an int.

The int one was easily solved by changing the signing of the int to the correct signing that OpenBSD is looking for, but I'm having trouble figuring out the pointer portion. Here are the relevant errors:

/home/hubcaps/usr/src/c/polybar/src/utils/file.cpp:47:10: error: member reference type 'const polybar::v3_1_0_161_g028b141_git::file_ptr' is not a pointer; did you mean to use '.'?
  return fileno(*this);
         ^~~~~~~~~~~~~
/usr/include/stdio.h:406:36: note: expanded from macro 'fileno'
#define fileno(p)       (!__isthreaded ? __sfileno(p) : (fileno)(p))
                                         ^~~~~~~~~~~~
/usr/include/stdio.h:397:26: note: expanded from macro '__sfileno'
#define __sfileno(p)    ((p)->_file)
                         ~~~^
/home/hubcaps/usr/src/c/polybar/src/utils/file.cpp:47:10: error: no member named '_file' in 'polybar::v3_1_0_161_g028b141_git::file_ptr'
  return fileno(*this);
         ^~~~~~~~~~~~~
/usr/include/stdio.h:406:36: note: expanded from macro 'fileno'
#define fileno(p)       (!__isthreaded ? __sfileno(p) : (fileno)(p))
                                         ^~~~~~~~~~~~
/usr/include/stdio.h:397:28: note: expanded from macro '__sfileno'
#define __sfileno(p)    ((p)->_file)
                         ~~~  ^
2 errors generated.
*** Error 1 in . (bin/CMakeFiles/polybar-msg.dir/build.make:111 'bin/CMakeFiles/polybar-msg.dir/utils/file.cpp.o': cd /home/hubcaps/usr/src/...)
*** Error 1 in . (CMakeFiles/Makefile2:459 'bin/CMakeFiles/polybar-msg.dir/all')
*** Error 1 in /home/hubcaps/usr/src/c/polybar/build (Makefile:130 'all')

As far as I can tell with my limited c++ knowledge, it's pointers all the way down. You can see OpenBSD's stdio.h and the relevant lines here:

https://github.com/openbsd/src/blob/933383cde7adfd440b8f1052bc37ab77601942e7/include/stdio.h#L397

https://github.com/openbsd/src/blob/933383cde7adfd440b8f1052bc37ab77601942e7/include/stdio.h#L406

Any help or direction would be appreciated in how to get past these errors.

**Comment by hubbcaps** [comment]
I've gotten past the above by actually linking correctly, pretty much the above is useless due to my own incompetency. I'm going to blame the learning curve of a new OS.

**Comment by NBonaparte** [comment]
I’ll close this then. Feel free to reopen or make a new issue if you come across any more problems.
