### ISSUE TITLE
Config parameter and module issues.

### ISSUE THREAD

**Issue by Tixle** [jaagr/polybar#1318]
warn: The config parameter `bar/Bar.dock` is deprecated, use `bar/Bar.override-redirect` instead.
error: Disabling module "i3" (reason: Could not find socket: <empty>)
error: Disabling module "battery" (reason: No suitable way to get current charge state)
[1]    17755 segmentation fault  polybar Bar

Just reinstalled my system, got Polybar install and got my config moved over but I get this error anytime I try to launch it.

**Comment by NBonaparte** [comment]
Post your config.

**Comment by Tixle** [comment]
;:set syn=dosini

[global/wm]
margin-top = 5
margin-bottom = 5

override-redirect = false

[colors]
white = #477673
gray = #585858
black = #090909
red = #c795ae
blue = #95aec7
yellow = #c7ae95
green = #aec795
pink = #00000000

[bar/Bar]
monitor = ${env:MONITOR:HDMI-0}
bottom = false
dock = false
wm-restack = i3
width = 100%
height = 22

enable-ipc = true

padding-left = 0
padding-right = 1

module-margin-right = 1
module-margin-left = 0

modules-right = updates filesystem battery date menu0
modules-center =  title
modules-left = i3 cpu memory

background = #00000000
foreground = ${colors.white}

underline-size = 2
underline-color = ${colors.white}

tray-detached = false
tray-position = right
tray-offset-x = 
tray-maxsize = 
tray-padding = 

font-0 = Hack:size=10.7;0
font-1 = FontAwesome:size=10;0
font-2 = TakaoGothic:weight=bold:size=10;0
font-3 = FontAwesome:size=8;0

[module/title]
type = internal/xwindow
label =  %title%
label-maxlen = 30


[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /
;mount-1 = /home
;mount-2 = /invalid/mountpoint

label-mounted =  %free%
label-mounted-underline = ${colors.pink}
label-mounted-padding = 1

label-unmounted =
label-unmounted-foreground = ${colors.black}


[module/bspwm]
type = internal/bspwm
ws-icon-default = x

label-focused = 
;label-active = %index%
label-active-background = #ee333333
label-active-underline= #cc333333
label-active-padding = 2

label-unfocused = 
;label-occupied = %index%
label-occupied-padding = 2

label-urgent = 
;label-urgent = %index%
label-urgent-background = #bd2c40
label-urgent-padding = 2

label-visible = 
;label-empty = %index%
label-empty-foreground = #55
label-empty-padding = 2


[module/i3]
type = internal/i3
format = <label-mode> <label-state>
index-sort = true

label-focused-font = 4
label-unfocused-font = 4
label-urgent-font = 4
label-visible-font = 4 

label-focused = 
;label-focused = %index%
;label-focused-background = ${colors.gray}
label-focused-padding = 1

label-unfocused = 
;label-unfocused = %index%
label-unfocused-padding = 1
;label-unfocused-background = ${colors.black}
label-unfocused-underlinde = ${colors.white}

label-urgent = 
;label-urgent = %index%!
;label-urgent-background = ${colors.red}
label-urgent-padding = 1
label-urgent-foreground = ${colors.red}

label-visible = 
;label-visible = %index%
label-visible-foreground = ${colors.white}
label-visible-padding = 1


[module/backlight]
type = internal/xbacklight

format = <label> <bar>
label = BL

bar-width = 10
bar-indicator = │
bar-indicator-foreground = #ff
bar-indicator-font = 2
bar-fill = ─
bar-fill-font = 2
bar-fill-foreground = #9f78e1
bar-empty = ─
bar-empty-font = 2
bar-empty-foreground = #55


[module/cpu]
format-label = internal/cpu

format = <label>

ramp-coreload-0 = ▁
ramp-coreload-1 = ▂
ramp-coreload-2 = ▃
ramp-coreload-3 = ▄
ramp-coreload-4 = ▅
ramp-coreload-5 = ▆
ramp-coreload-6 = ▇
ramp-coreload-7 = █
ramp-coreload-underline = ${colors.white}

type = internal/cpu
interval = 1
label = %{F${colors.white}  %percentage% %{F-}
label-underline = ${colors.pink}
padding= 2


[module/memory]
type = internal/memory
interval = 1

label = %{F${colors.white}  %percentage_used% %{F-}
label-underline = ${colors.pink}
label-foreground = ${colors.white}


[module/date]
type = internal/date
date-alt =   %A %H:%M 
date =   %b/%d/%y %H:%M 
interval = 5
format-underline = ${colors.pink}
;format-background = ${colors.black}
format-foreground = ${colors.white}
format-padding = 1


[module/volume]
type = internal/volume

format-volume = <bar-volume>

label-volume = VOL
label-volume-foreground = ${root.foreground}

label-muted =  sound muted
label-muted-foreground = ${colors.gray}

bar-volume-width = 10
bar-volume-foreground-0 = ${colors.green}
bar-volume-foreground-1 = ${colors.green}
bar-volume-foreground-2 = ${colors.green}
bar-volume-foreground-3 = ${colors.green}
bar-volume-foreground-4 = ${colors.yellow}
bar-volume-foreground-5 = ${colors.red}
bar-volume-gradient = false
bar-volume-indicator = 
bar-volume-indicator-font = 4
bar-volume-indicator-foreground = ${colors.white}
bar-volume-fill = 
bar-volume-fill-font = 4
bar-volume-empty = 
bar-volume-empty-font = 4
bar-volume-empty-foreground = ${colors.gray}


[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 98

format-charging = <animation-charging> <label-charging>
format-charging-underline = ${colors.green}
format-charging-padding = 1

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-underline = ${colors.yellow}
format-discharging-padding = 1

format-full =   <label-full>
format-full-underline = ${self.format-charging-underline}
format-full-overline = ${self.format-charging-underline}
format-full-padding = 1

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-foreground = ${colors.white}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = ${colors.white}
animation-charging-framerate = 500


[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 65

format = <label>
format-underline = ${colors.white}
format-warn = <label-warn>
format-warn-underline = ${colors.red}

format-padding = 1
format-warn-padidng = 1

label =  %temperature%
label-warn =  %temperature%

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = #55


[module/menu0]
type = custom/menu

format = <label-toggle> <menu>
format-underline = ${colors.pink}
format-padding = 1

menu-0-0 =  shutdown
menu-0-0-exec = shutdown now
menu-0-1 =  restart
menu-0-1-exec = shutdown -r now
menu-0-2 =   cancel


label-open =   
label-close =

[module/updates]
type = custom/script

exec = echo 


[module/powermenu]
type = custom/menu

label-open =  power
label-open-foreground = #e60053
label-close =  cancel
label-close-foreground = #e60053
label-separator = |
label-separator-foreground = #55

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = sudo reboot

menu-2-0 = power off
menu-2-0-exec = sudo poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0

; vim:ft=dosini

**Comment by NBonaparte** [comment]
No need for gdb then. You _do_ have i3 running and a battery, right?

**Comment by Tixle** [comment]
Not using i3 and I do not have a battery. I've never had issues running polybar in Herbstluftwm before this though.

**Comment by NBonaparte** [comment]
Probably would be better to disable those modules anyways, to avoid cluttering the log.

In that case, try running gdb (`gdb --args polybar <whatever arguments you use>`, then `run`) and post what you get from the segfault on here (run `bt` within gdb).

**Comment by Tixle** [comment]
Running gdb and going into that prompt, trying to run bt with either anything or nothing else just outputs it saying no stack.

**Comment by NBonaparte** [comment]
Did you do `run` first after entering the gdb shell?

**Comment by Tixle** [comment]
(gdb) run polybar
Starting program:  polybar
No executable file specified.
Use the "file" or "exec-file" command.
(gdb) --bt polybar Bar run
Undefined command: "--bt".  Try "help".
(gdb)

**Comment by NBonaparte** [comment]
```
gdb --args polybar <args>
...
(gdb) run
<wait until segfault>
(gdb) bt
```

**Comment by Tixle** [comment]
Starting program: /usr/bin/polybar Bar
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3827700 (LWP 16495)]
warn: The config parameter `bar/Bar.dock` is deprecated, use `bar/Bar.override-redirect` instead.
error: Disabling module "i3" (reason: Could not find socket: <empty>)
error: Disabling module "battery" (reason: No suitable way to get current charge state)
[New Thread 0x7ffff3026700 (LWP 16498)]
[New Thread 0x7fffebfff700 (LWP 16499)]
[New Thread 0x7ffff2825700 (LWP 16500)]
[New Thread 0x7ffff2024700 (LWP 16501)]
[Thread 0x7ffff2825700 (LWP 16500) exited]
[New Thread 0x7ffff1823700 (LWP 16503)]
[New Thread 0x7ffff1022700 (LWP 16504)]
[New Thread 0x7ffff0821700 (LWP 16505)]
[Thread 0x7ffff0821700 (LWP 16505) exited]
[New Thread 0x7fffeb7fe700 (LWP 16506)]

Thread 10 "polybar" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeb7fe700 (LWP 16506)]
0x00007ffff7897e00 in ?? () from /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
(gdb) bt
#0  0x00007ffff7897e00 in ?? () from /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
#1  0x00007ffff788a62a in FcDefaultSubstitute () from /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
#2  0x000055555566ef83 in polybar::v3_0_5::cairo::make_font(_cairo*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, double, double, double) ()
#3  0x000055555567097e in polybar::v3_0_5::renderer::renderer(polybar::v3_0_5::connection&, polybar::v3_0_5::signal_emitter&, polybar::v3_0_5::config const&, polybar::v3_0_5::logger const&, polybar::v3_0_5::bar_settings const&) ()
#4  0x00005555556725f0 in polybar::v3_0_5::renderer::make(polybar::v3_0_5::bar_settings const&) ()
#5  0x0000555555621f4e in polybar::v3_0_5::bar::on(polybar::v3_0_5::signals::eventqueue::start const&) ()
#6  0x000055555565d731 in polybar::v3_0_5::controller::process_eventqueue() ()
#7  0x00007ffff7f0badf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff5c8d5aa in start_thread (arg=0x7fffeb7fe700) at pthread_create.c:463
#9  0x00007ffff59c2cbf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by NBonaparte** [comment]
Might be the same issue as #855, could you try doing what Patrick suggested?

**Comment by NBonaparte** [comment]
This is probably the same as #1337 as well, we can continue tracking this issue over there.
