### ISSUE TITLE
Text module padding right/left

### ISSUE THREAD

**Issue by memeplex** [jaagr/polybar#1319]
The text module supports content-padding but it doesn't seem possible to pad it right or left.

**Comment by NBonaparte** [comment]
Left and right padding isn't implemented for formats currently.

**Comment by memeplex** [comment]
What I'm saying is that it is supported for labels, for example:

[module/date]
...
label = %date% %time%
label-font = 4
label-padding-right = 1

The only module for which I'm unable to do that is text. If it's not supported for formats, why not making the content a label?
