### ISSUE TITLE
Can't change font in example config

### ISSUE THREAD

**Issue by TheDevKiller** [jaagr/polybar#1321]
Hello ! I have still the example configuration, modified a little bit.

I have tried to change the font-1 line to set ubuntu font instead of the default font (I don't rember what is it) but it's doesn't work. When i launch polybar, the font is still the default font ...

The line is now `font-1 = ubuntu:fontformat=truetype:size=8:antialias=false;0`

**Comment by TheDevKiller** [comment]
I have quickly read this, not completely all

**Comment by NBonaparte** [comment]
Yeah, it looks like it should work... did you check gucharmap for Ubuntu, and if you remove all the other font settings, what font does it use?

**Comment by TheDevKiller** [comment]
By default, the gucharmap uses the "Sans" font

**Comment by NBonaparte** [comment]
Did you set the dropdown menu in the top left to Ubuntu?

By font settings, I mean `font-N` (use `font-0=ubuntu...` and remove `font-1` and `font-2`)

**Comment by TheDevKiller** [comment]
I'm on i3

**Comment by NBonaparte** [comment]
I meant the dropdown menu in gucharmap.

**Comment by TheDevKiller** [comment]
use font-0=ubuntu... and remove font-1 and font-2 works but I have no icons because missing sili and the bar, for example the volume bar don't work

**Comment by NBonaparte** [comment]
Use siji as `font-1` and keep ubuntu as `font-0`.

**Comment by TheDevKiller** [comment]
Now, I have the icons and no bars

**Comment by TheDevKiller** [comment]
And I set fixed as the font-2 and It's good, I have all :) with the ubuntu font

**Comment by NBonaparte** [comment]
OK, great :+1: I'll close this issue now.
