### ISSUE TITLE
Click event on mpd module

### ISSUE THREAD

**Issue by h0ttentot** [jaagr/polybar#1324]
I have a script to show the cover of the current album playing above the mpd module when i click on the info of the song playing. But it just says:

> warn: No matching input area found (btn=1)

There's no possibility to use click-left in the mpd module?

**Comment by NBonaparte** [comment]
No, but you can insert lemonbar tags manually: https://github.com/jaagr/polybar/wiki/Formatting#action-a

**Comment by h0ttentot** [comment]
Oh, nice. Thanks. I'm closing this.
