### ISSUE TITLE
Ramps don't evenly distribute states

### ISSUE THREAD

**Issue by memeplex** [jaagr/polybar#1328]
I defined a volume ramp with three states but the volume is mapped to these states as follows:

0-25% -> state 1
25%-75% -> state 2
75%-100% -> state 3

I would have expected one third of the range to be assigned to each state.

**Comment by memeplex** [comment]
If this is like that by design I don't think it's the right choice since the user could get the same results, if he/she so desires, by just repeating states.

**Comment by memeplex** [comment]
This code in ramp.cpp is problematic:

```
size_t index = percentage * (m_icons.size() - 1) / 100.0f + 0.5f;
```

For example, if `m_icons.size() == 3` then `percentage` should at least 75% in order to get 2 as the index, `75 * (3 - 1) / 100 + 0.5 == 150 / 100 + 0.5 == 1.5 + 0.5 == 2`.

The interval [0, 100] should be mapped to the entire [0, 3) interval, the problem is just in the upper bound (one interval is closed the other is not) so you can simply take `min(n - 1, n * p / 100.0)` where `n == m_icons.size()` and `p == percentage`.

**Comment by patrick96** [comment]
This is definitely not intentional. If you want, we would really appreciate a PR for this.

**Comment by memeplex** [comment]
Ok, I will submit one later.

**Comment by patrick96** [comment]
Thanks!

**Comment by memeplex** [comment]
There you have. There was no need to take the min since the index was already being capped (from below and from above) in the following line.
