### ISSUE TITLE
Slightly different font rendering in polybar vs i3 titlebars / rofi

### ISSUE THREAD

**Issue by memeplex** [jaagr/polybar#1329]
I'm reporting this here since I noticed there are consistency between the other applications but not between them and polybar. Maybe it's a problem with the different backends and not with polybar itself, but I would like to understand the cause.

I'm using the xwindow polybar module so I get the same text in polybar and in the current window titlebar. The configured font is DejaVu Sans in both cases, one using a pango descriptor "DejaVu Sans Bold 10", the other using a fontconfig descriptor "DejaVu Sans-10:weight=bold". I've exactly the same fontconfig configuration in both ~/.Xresources and ~/config/fontconfig/fonts.xml (quite standard settings for hinting, antialiasing, etc). Now, the rendering is almost the same but not exactly the same. Using xmag I'm able to verify the fonts in the titlebar are slightly taller than the ones in polybar. i3 uses pango, polybar uses cairo, but AFAIK it should ultimately amount to the same, shouldn't it? Do you have any idea why this might be happening?

**Comment by memeplex** [comment]
Maybe this is related: https://github.com/jaagr/polybar/issues/84. The first item in the list is about moving to pango.

**Comment by NBonaparte** [comment]
Yeah, right now the renderer uses xft but i3 and rofi use Pango. Cairo is for graphics and is mostly independent of both font libraries.

**Comment by memeplex** [comment]
@NBonaparte  is it ok if I open an issue for moving to pango since that catch-all issue was closed with the suggestion to open independent tickets? I mean, is it at least slightly probable that you might consider it? It surprises me a bit that the idea to use pango was at the top of that list.

**Comment by memeplex** [comment]
Another thing: I noticed that the font sizes change more continuously in i3, for example I get subtle variations from 9.7 to 9.8 to 9.9 to 10. Instead, in rofi what I get is a discrete jump from, say, 10=10.1=10.2 to 10.3=10.4=... which is considerably larger than the previous size. Is this an unavoidable effect of using cairo as the backend? Maybe if it weren't the case it would be possible to more closely align fonts for both apps without changing the backend altogether.

**Comment by NBonaparte** [comment]
It’s already on our todo list, you don’t need to add it. 

IIRC both i3 and rofi should use both cairo and pango, not sure why they differ though.

**Comment by memeplex** [comment]
I'm pretty sure it's because of a rounding issue (based on the evidence stated in my previous comment). What I'm less sure about is whether this rounding happens in polybar or in fc/ft/cairo.

**Comment by memeplex** [comment]
Here is an screenshot in which you can compare:

![image](https://user-images.githubusercontent.com/2845433/43023266-9fcb1b04-8c40-11e8-9a71-f900389914b8.png)

The text at the left is from polybar size=10, in the middle is i3 size=10, at the top polybar size=10.2. The second one is taller than the first one, the third one is wider than the second one. There is no way to get something in the middle since polybar yields the same font from 10 to 10.3 (exclusive) and then abruptly changes. Instead, i3 allows more fine grained control. That's why I'm speculating it's due to internal size rounding.

**Comment by memeplex** [comment]
Last thing and I'm not bothering you again with this, but maybe it's relevant to help understanding what's happening and if getting this right involves a major surgery (moving to pango) or just some stitches: using `width=condensed` the 10.3 font is almost the same than the 10 i3/rofi one, although the `fi` ligature is not that tight the overall width of the `config` word is the same in both cases. If you look at the middle and top screenshots above horizontal spacing is the most obvious difference, much more than font width.

**Comment by jallbrit** [comment]
Is there any update on this behavior? With the same font settings in `urxvt`, `st`, and `polybar`, `polybar` has different-looking text. It's different and also takes up more horizontal space for the same exact monospace text.
