### ISSUE TITLE
KeyError: 'eventstruct'

### ISSUE THREAD

**Issue by JsonFn** [jaagr/polybar#1330]
Following the instruction to build from source, but build.sh script `build.sh -f` fails with 

    Scanning dependencies of target xpp
    [  1%] Linking CXX static library libxpp.a
    Traceback (most recent call last):
      File "/home/jason/github.com/polybar/lib/xpp/generators/cpp_client.py", line 3163, in <module>
        from xcbgen.state import Module
      File "/usr/lib/python2.7/dist-packages/xcbgen/state.py", line 7, in <module>
        from xcbgen import matcher
      File "/usr/lib/python2.7/dist-packages/xcbgen/matcher.py", line 12, in <module>
        from xcbgen.xtypes import *
      File "/usr/lib/python2.7/dist-packages/xcbgen/xtypes.py", line 1221, in <module>
        class EventStruct(Union):
      File "/usr/lib/python2.7/dist-packages/xcbgen/xtypes.py", line 1239, in EventStruct
        out = __main__.output['eventstruct']
    KeyError: 'eventstruct'
    make[2]: *** [lib/xpp/CMakeFiles/xpp.dir/build.make:70: lib/xpp/libxpp.a] Error 1
    make[1]: *** [CMakeFiles/Makefile2:403: lib/xpp/CMakeFiles/xpp.dir/all] Error 2
    make: *** [Makefile:130: all] Error 2
    ** Failed to build project

How to fix this error? 

All modules are answered with Y 

    ** Include support for "internal/i3" (requires i3) ------------------- [Y/n]: Y
    ** Include support for "internal/volume" (requires alsalib) ---------- [Y/n]: Y
    ** Include support for "internal/network" (requires wireless_tools) -- [Y/n]: Y
    ** Include support for "internal/mpd" (requires libmpdclient) -------- [Y/n]: Y
    ** Include support for "internal/github" (requires libcurl) ---------- [Y/n]: Y
    ** Build "polybar-msg" used to send ipc messages --------------------- [Y/n]: Y

And targets configured

    --  Targets:
    -- [X]   polybar-msg
    -- [ ]   testsuite
    --  Module support:
    -- [X]   alsa
    -- [X]   curl
    -- [X]   i3
    -- [X]   mpd
    -- [X]   network
    --  X extensions:
    -- [X]   xcb-randr
    -- [X]   xcb-randr (monitor support)
    -- [ ]   xcb-render
    -- [ ]   xcb-damage
    -- [ ]   xcb-sync
    -- [ ]   xcb-composite
    -- [X]   xcb-xkb
    -- [ ]   xcb-xrm
    -- [ ]   xcb-cursor
    -- Font not found: fixed:pixelsize=10
    -- Font not found: unifont:fontformat=truetype
    -- Font not found: siji:pixelsize=10

Edit:

git commit is `commit bf16a4d415ea7d8845f578544de0c71e56ad314e (HEAD, tag: 3.1.0)`

**Comment by patrick96** [comment]
See [Known-Issues](https://github.com/jaagr/polybar/wiki/Known-Issues)

**Comment by JsonFn** [comment]
I am sorry, but following the instruction described in Kknown-Issues about eventstruct error. Compiling with `build.sh -f` still throws the same error message.

The error message is 

    Traceback (most recent call last):
      File "/home/jason/github.com/polybar/lib/xpp/generators/cpp_client.py", line 3163, in <module>
        from xcbgen.state import Module
      File "/usr/lib/python2.7/dist-packages/xcbgen/state.py", line 7, in <module>
        from xcbgen import matcher
      File "/usr/lib/python2.7/dist-packages/xcbgen/matcher.py", line 12, in <module>
        from xcbgen.xtypes import *
      File "/usr/lib/python2.7/dist-packages/xcbgen/xtypes.py", line 1221, in <module>
        class EventStruct(Union):
      File "/usr/lib/python2.7/dist-packages/xcbgen/xtypes.py", line 1239, in EventStruct
        out = __main__.output['eventstruct']
    KeyError: 'eventstruct'

The only difference I found between Known Issue and mine is python version. When building from source, my environment refers to python 2.7 whereas what described in Know Issues page is 3.x. 

The rest of steps to compile source is exactly the same as instruction.

1. `git clone --branch 3.1.0 --recursive https://github.com/jaagr/polybar`
2. `cd lib/xpp` do `git checkout master` then `rm `
3. `build.sh -f`

Anything I miss?

**Comment by patrick96** [comment]
I don't think this works with `build.sh` because it resets the submodules.

If you do
```bash
mkdir build
cd build
cmake ..
make
```
and optionally `sudo make install`, it should work.

I have updated the section on the Known Issues page to include this information.
