### ISSUE TITLE
Zero padding

### ISSUE THREAD

**Issue by memeplex** [jaagr/polybar#1332]
Specially for the cpu module that tends to be below 10% and even with `:2:3` looks inconsistent side-to-side other modules:

![image](https://user-images.githubusercontent.com/2845433/43031555-4868c778-8c7a-11e8-815a-c8522a97a33e.png)

Here, the spacing between the icon and the percentage appears a bit like the margin between modules so it's not only unaesthetic but also confusing. The alternative of not reserving space for a second digit is distracting when the glyphs are frequently moving back and forth.

The real solution is to zero pad that percentage.

Then the **real** solution is to support printf-style format strings but zero-padding is the most important use case AFAICS.

**Comment by memeplex** [comment]
Here is a suggestion for a very simple syntactical extension: using `%value:02` instead of `%value:2% will left zero pad `%value`, in general using `%value:0n` will zero pad to fill at least n positions.

This is not a general padding mechanism, it adds only left zero padding. But since:

1. Left zero padding is by far the most common case for aligning numerical fields and left space padding is the most common case for text fields (and also desirable for numerical fields), so both important cases will be covered.

2. Eventually printf-style format strings will generalize this anyway.

I think is a worthy simple addition.

**Comment by memeplex** [comment]
@patrick96 now that I'm on that, would you accept a PR for this too?

**Comment by NBonaparte** [comment]
What is your font order in your config? If your icon font is first, it might be using the space from that which is not monospace. For me, I have my mono font first and then the icon font, and I use `%label:3%` without any problems.

**Comment by memeplex** [comment]
@NBonaparte the problem is with whitespace-padding, font is monospeced and that's working fine, I just want `0` instead of ` `.

I've submitted a very simple PR to add the functionality described above. I could add a couple of lines to the documentation also.

Btw, what's the best way to quick dump some debug info while developing? cout and cerr shows nothing and it's a bit cumbersome to add and remove a logger just for that. I ended up writing to a file but I guess you have better ways.

**Comment by NBonaparte** [comment]
Deleted comment because I misread it, sorry.

**Comment by memeplex** [comment]
Could you help me understand why adding a couple of lines is reducing coverage by 50% (!!!!)?

I think that's due to adding the zpad field to label but I fail to see a lot to test here.

**Comment by patrick96** [comment]
I agree, printf style tokens are the way to go eventually. Your suggestion sounds fine for the moment.

`cout` and `cerr` should work (they do for me). You can also use the logger, by just typing `logger::make.err(...)`.

The test coverage reduces this much because of #1198 it's not your PRs fault. I think codecov has some inconsistencies from which commits it takes the coverage numbers to compare.

**Comment by memeplex** [comment]
> cout and cerr should work (they do for me). You can also use the logger, by just typing logger::make.err(...).

That's weird, I was getting no output at all, maybe I should have flushed the stream, will try that the next time.

**Comment by patrick96** [comment]
For me it worked w/o flushing the stream, but I always printed newlines at the end, so maybe it was that.

**Comment by NBonaparte** [comment]
printf works as well if you want to use that, although it's not c++.

**Comment by s3rj1k** [comment]
Is there a possibility to use another font for zero padded text?
