### ISSUE TITLE
Cannot find Font

### ISSUE THREAD

**Issue by SiddharthKhatsuriya** [jaagr/polybar#1333]
`-- Font not found: fixed:pixelsize=10`
`-- Font not found: unifont:fontformat=truetype`
`-- Font not found: siji:pixelsize=10`

How do i add these fonts i have siji on my system but still it says font not found

**Comment by memeplex** [comment]
Have you already followed the instructions here https://github.com/jaagr/polybar/wiki/Fonts?

Please check if your fonts are included in the output of `fc-list`.

**Comment by patrick96** [comment]
This warning during the build process isn't really consequential, it only affects the font names in the example configuration that polybar generates. You can ignore it. As long as you follow the instructions, as @memeplex mentioned, in https://github.com/jaagr/polybar/wiki/Fonts when setting up your own config you should have no problems
