### ISSUE TITLE
Border appears above/below underline

### ISSUE THREAD

**Issue by Sigma-One** [jaagr/polybar#1334]
If you set a top or bottom border to a bar, and then under/overlines for modules, the under/oveline appears above or below the border line, whereas I would like it to appear overlapping the border line. Is this a thing that I cannot see, or is it not possible? Or is it possible to have a module that fills the remaining space and applies a line there to avoid using border?

**Comment by patrick96** [comment]
That's not possible. The border is separate from the under/overline.

Vertically polybar's box model looks like this:
```
+---------
  border
+---------
 overline
+---------

 content

+---------
 underline
+---------
  border
+---------
