### ISSUE TITLE
KeyError: 'eventstruct' error when trying to compile

### ISSUE THREAD

**Issue by EgbertMedia** [jaagr/polybar#1335]
I'm getting an KeyError when I try to build using the build script.
The fix in the known issues list is not working for me, I'm still getting the same error.

[  1%] Linking CXX static library libxpp.a
Traceback (most recent call last):
  File "/home/egbert/Downloads/polybar/lib/xpp/generators/cpp_client.py", line 3163, in <module>
    from xcbgen.state import Module
  File "/usr/lib/python2.7/site-packages/xcbgen/state.py", line 7, in <module>
    from xcbgen import matcher
  File "/usr/lib/python2.7/site-packages/xcbgen/matcher.py", line 12, in <module>
    from xcbgen.xtypes import *
  File "/usr/lib/python2.7/site-packages/xcbgen/xtypes.py", line 1221, in <module>
    class EventStruct(Union):
  File "/usr/lib/python2.7/site-packages/xcbgen/xtypes.py", line 1239, in EventStruct
    out = __main__.output['eventstruct']
KeyError: 'eventstruct'
make[2]: *** [lib/xpp/CMakeFiles/xpp.dir/build.make:70: lib/xpp/libxpp.a] Error 1
make[1]: *** [CMakeFiles/Makefile2:403: lib/xpp/CMakeFiles/xpp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
** Failed to build project

**Comment by patrick96** [comment]
See [Known-Issues](https://github.com/jaagr/polybar/wiki/Known-Issues)

**Comment by EgbertMedia** [comment]
Like I said, git checkout in the lib/xpp folder didn't fix the issue for me.
I'm using fedora.

**Comment by EgbertMedia** [comment]
Like I said, git checkout in the lib/xpp folder did not fix the issue for me.
Is there something else I should try? I'm using fedora.

**Comment by patrick96** [comment]
Did you also exectue `rm include/xpp/proto/*` in the `lib/xpp` folder?

**Comment by patrick96** [comment]
#1330 had the same problem. The fix described doesn't work when you use `build.sh`.

**Comment by EgbertMedia** [comment]
Thanks! I have compiled it manually now and it does work fine now.
