### ISSUE TITLE
Polybar returns nothing but "polybar: symbol lookup error: polybar: undefined symbol: _ZN4Json5ValueC1ERKSs" on execution

### ISSUE THREAD

**Issue by Chili-Bebber** [jaagr/polybar#1336]
I noticed my bar didn't start today and decided to try running polybar from the terminal. 
``polybar: symbol lookup error: polybar: undefined symbol: _ZN4Json5ValueC1ERKSs`` 
was the only output and the bar did not start. I updated before my last reboot, so I would assume this is a compatibility issue with a newer package, however I could be completely wrong. Interestingly, I can't even check polybar's version as it still spits out the same error, but I still know that I'm running 3.1.0 from the Void Linux repository. Any help is appreciated, here's to hoping that this is just the result of a mistake I made.

**Comment by patrick96** [comment]
Please try to build polybar from source, as described [here](https://github.com/jaagr/polybar/wiki/Compiling). If you the executable you compiled yourself works fine, then it's a problem with the build file for void linux and you should report it there. In any case, please report back your findings.

**Comment by Chili-Bebber** [comment]
building from source fails returning 
``/home/dexter/polybar/lib/i3ipcpp/include/i3ipc++/ipc.hpp:12:10: fatal error: 
      'i3/ipc.h' file not found
#include <i3/ipc.h>
         ^~~~~~~~~~
``
but I think this is unrelated.

**Comment by Chili-Bebber** [comment]
So I tried building without the i3 module and it worked, but I kind of depend on that module as I use i3-gaps. I saw somewhere else that you said that this could be a result of cmake incorrectly detecting which version of i3 I have installed. Is there a workaround to this beyond disabling the i3 module?

**Comment by patrick96** [comment]
That error shouldn't occur when you actually have i3 installed. Chances are that the variant of polybar that you built using the void linux build file didn't have i3 enabled either. Make sure that the `i3-gaps` package provides a `ipc.h` file (probably in `/usr/include/i3/ipc.h`)

For the original error, I think it is related to jsoncpp. Is it possible that in the last update jsoncpp was updated but it was updated after polybar was updated? If so, this could explain it. Try to rebuild polybar using the void linux template, this will make polybar compile against the latest jsoncpp version.

**Comment by Chili-Bebber** [comment]
So the i3-gaps package in the Void repository doesn't appear provide ``ipc.h`` for some reason, so I ended up just building i3-gaps from source. After doing so I was able to successfully build Polybar. Thanks for your help!

**Comment by patrick96** [comment]
@shizonic this is error is not jsoncpp related. 
See [Known-Issues](https://github.com/jaagr/polybar/wiki/Known-Issues)

**Comment by shizonic** [comment]
@patrick96 Thanks! I see you are using voidlinux too. So did you find a way to change the xbps-src template file to fix this is issue and to successful build it?

**Comment by shizonic** [comment]
Yes there is a `pre_build` function. The problem is that the xbps package isn't build from the git version. Instead it uses the release tarbal and I can not execute a `git checkout`. So do you have any idea to fix it using the release tarbals instead of the git version?

**Comment by patrick96** [comment]
You can use the xpp tarball at `https://github.com/jaagr/xpp/archive/00165e1a6d5dd61bc153e1352b21ec07fc81245d.zip` instead of using the one that depends on `_i3ipcpp_version`

**Comment by shizonic** [comment]
@patrick96 Perfect. Thank you! I will give this a try.
