### ISSUE TITLE
Allow to change font using format tags

### ISSUE THREAD

**Issue by memeplex** [jaagr/polybar#1345]
This would be very useful and will ameliorate the need to split each format in many labels that can be separately configured. Nevertheless if you're moving to pango I believe most of current format tags will be redundant after the inclusion of pango markup.

**Comment by patrick96** [comment]
There is already a `%{T}` tag where you can specifiy the font that is used after it. See the [Wiki](https://github.com/jaagr/polybar/wiki/Fonts#fonts) for an example.

When/If we move to pango, we will not deprecate the lemonbar format tags because they are very widely used.

**Comment by memeplex** [comment]
Cool! Do you want me to add some doc to https://github.com/jaagr/polybar/wiki/Formatting? After reading that I got the impression that the tag list was exhaustive and T is missing there.

**Comment by memeplex** [comment]
Done https://github.com/jaagr/polybar/wiki/Formatting#font-t
