### ISSUE TITLE
XCB_REQUEST (1) When trying to run 'polybar example'

### ISSUE THREAD

**Issue by edleeman** [jaagr/polybar#1349]
I keep getting XCB_REQUEST (1) error when running 'polybar example'.

Cloned repo, built from source following instructions on ReadMe.

Installed all dependencies including the optional recommendations

Running xfce.

![image](https://user-images.githubusercontent.com/10074046/43261464-a77d320e-90d4-11e8-80d0-5abd23a8b8b0.png)

**Comment by patrick96** [comment]
Can you run polybar with the `-l trace` option and post the whole output.

Are you somehow running wayland?

Also, does running `polybar -m` and `polybar -vvv` work?

**Comment by edleeman** [comment]
I don't think I'm running wayland. But I am connecting via remote desktop. X11 maybe?

I'll doule check.

Run the log flags and just got this
![image](https://user-images.githubusercontent.com/10074046/43284077-a6ddf1e2-9112-11e8-933b-1affa5444c68.png)
I'm probably just being an idiot.

'polybar -m'
![image](https://user-images.githubusercontent.com/10074046/43284121-c14af246-9112-11e8-95aa-f15c4266b640.png)

'polybar -vvv'
![image](https://user-images.githubusercontent.com/10074046/43284142-d272acd0-9112-11e8-9358-ad0e83feab70.png)

Many thanks

**Comment by edleeman** [comment]
X11
![image](https://user-images.githubusercontent.com/10074046/43284252-1efb6cf4-9113-11e8-8320-cae548f96868.png)

**Comment by patrick96** [comment]
I meant, you should add the `-l trace` argument, so you should run `polybar -l trace example` ;)

So you remote desktop into your computer? How? Does the computer have any actual displays connected? What is the output of `xrandr`?

**Comment by edleeman** [comment]
Jeeze my bad ;)

![image](https://user-images.githubusercontent.com/10074046/43284522-f84c135a-9113-11e8-836d-ff537592f4b0.png)

'xrandr'
![image](https://user-images.githubusercontent.com/10074046/43284542-0b6a9934-9114-11e8-888b-f02cc26ffe27.png)

Connecting via Windows RDP over VPN and IP. Host machine has a single screen. RDP machine is hosted in AWS

**Comment by patrick96** [comment]
Oh, so the machine you want to run polybar on, doesn't have a physical display connected. A few months back, someone on [reddit](https://www.reddit.com/r/Polybar/comments/8igoh0/run_polybar_with_no_displays_connected/), had a similar problem, but they logged onto the machine with vnc. Also, for them `polybar -m` just didn't find any monitors and didn't error. They fixed the error by attaching a screen to the machine, but you obviously can't do that.

Best guess right now is that the X server your RDP server provides doesn't behave the same as the xorg X server. Don't know how to fix that though.

Also, your `xrandr` output looks very different to mine, what is the output of `xrandr -v`?
Can you please also post the cmake output you got when building, I'm curious if there is any more information there.

To clarify a few things:
* The RDP machine is actually running linux and not the linux subsystem for windows on Win10, right?
* What RDP server do you use?
* What linux distro does the RDP machine on AWS run?

**Comment by edleeman** [comment]
cmake output
` stepstoneuk@ed   ~/polybar/polybar     3.2  3.2.0  cmake .                                            20:37  
-- Trying to enable ccache
-- Couldn't locate ccache, disabling ccache...
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type specified; using RelWithDebInfo
-- Using supported compiler GNU-5.4.0
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Checking for module 'cairo-fc'
--   Found cairo-fc, version 1.14.6
-- Found Libiw: /usr/lib/x86_64-linux-gnu/libiw.so  
-- Checking for module 'xcb-randr'
--   Found xcb-randr, version 1.11.1
--  Build:
--    Type: RelWithDebInfo
--    CC: /usr/bin/cc  -O2 -g -DNDEBUG
--    CXX: /usr/bin/c++  -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors -O2 -g -DNDEBUG
--    LD: /usr/bin/ld  
--  Targets:
-- [X]   polybar-msg
-- [ ]   testsuite
--  Module support:
-- [X]   alsa (1.1.0)
-- [ ]   curl
-- [X]   i3
-- [X]   mpd (2.9)
-- [X]   network
-- [X]   pulseaudio (8.0)
-- [X]   xkeyboard (1.11.1)
--  X extensions:
-- [X]   xcb-randr (1.11.1)
-- [ ]   xcb-randr (monitor support)
-- [ ]   xcb-render
-- [ ]   xcb-damage
-- [ ]   xcb-sync
-- [ ]   xcb-composite
-- [X]   xcb-xkb (1.11.1)
-- [ ]   xcb-xrm
-- [X]   xcb-cursor (0.1.1)
--  Log options:
-- [X]   Trace logging
-- Font not found: fixed:pixelsize=10
-- Font not found: unifont:fontformat=truetype
-- Font not found: siji:pixelsize=10
-- Checking for module 'xcb-proto'
--   Found xcb-proto, version 1.11
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.12", minimum required is "2.7") 
-- XCB[XCB]: Found component XCB
-- Found XCB_XCB: /usr/lib/x86_64-linux-gnu/libxcb.so  
-- XCB[ICCCM]: Found component ICCCM
-- Found XCB_ICCCM: /usr/lib/x86_64-linux-gnu/libxcb-icccm.so  
-- XCB[EWMH]: Found component EWMH
-- Found XCB_EWMH: /usr/lib/x86_64-linux-gnu/libxcb-ewmh.so  
-- XCB[UTIL]: Found component UTIL
-- Found XCB_UTIL: /usr/lib/x86_64-linux-gnu/libxcb-util.so  
-- XCB[IMAGE]: Found component IMAGE
-- Found XCB_IMAGE: /usr/lib/x86_64-linux-gnu/libxcb-image.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so  
-- Searching for xcbgen with python2
-- Found xcbgen in /usr/lib/python2.7/dist-packages
-- XCB[RANDR]: Found component RANDR
-- Found XCB_RANDR: /usr/lib/x86_64-linux-gnu/libxcb-randr.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so;/usr/lib/x86_64-linux-gnu/libxcb-randr.so  
-- XCB[XKB]: Found component XKB
-- Found XCB_XKB: /usr/lib/x86_64-linux-gnu/libxcb-xkb.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so;/usr/lib/x86_64-linux-gnu/libxcb-randr.so;/usr/lib/x86_64-linux-gnu/libxcb-xkb.so  
-- xpp: including xcb proto xproto.xml
-- xpp: including xcb proto xkb.xml
-- xpp: including xcb proto randr.xml
-- Checking for module 'jsoncpp>=1.7.7'
--   
-- Could not find jsoncpp>=1.7.7 -- building static lib...
-- JsonCpp Version: 1.7.7
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.12", minimum required is "2.6") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/stepstoneuk/polybar/polybar
`

xrandr -v
` stepstoneuk@ed   ~/polybar/polybar     3.2  3.2.0    xrandr -v                                      20:40  
xrandr program version       1.5.0
Server reports RandR version 1.1
`

RDP is running full linux
Think it's using XRDP
RDP is running XFCE 4.12

**Comment by patrick96** [comment]
Alright, so your xrandr is up-to-date, but it reports the X Server uses version RandR 1.1. That could be the problem that the X server provided by xrdp is using a very old protocol (I couldn't find an exact date, but RandR 1.1 probably came out before 2006) and that is causing problems.

I couldn't find any information on whether xrdp is using its own x server or is somehow interfacing with xorg. What xrdp version are you running?

xfce is your desktop environment, not your linux distribution. On which linux distribution does the machine on AWS run?

There is a good chance that there is some fundamental limitation that makes it impossible to run polybar on an xrdp session, even if we get everything to the newest version.

**Comment by edleeman** [comment]
Thanks,

Will get back to you soon with the versions

**Comment by edleeman** [comment]
My Linux Distro is Ubuntu 16.04.4 LTS

xrdp version is 0.6.1-2

Thanks,

**Comment by patrick96** [comment]
The only possible solution I can think of, is maybe upgrading to the newest xrdp version, which is, I think, 0.9.7

**Comment by edleeman** [comment]
I shall give that a try, thanks

**Comment by edleeman** [comment]
I'll give that a try

**Comment by edleeman** [comment]
I'm afraid that didn't work. Maybe my setup won't work. Thanks very much for your help. Much appreciated!
