### ISSUE TITLE
bspwm workspaces font

### ISSUE THREAD

**Issue by karasuma-chitose** [jaagr/polybar#1356]
How do I set the font for bspwm workspaces?
I tried `format-font = 3`, `label-focused-font = 3`, `label-occupied-font = 3`, etc but nothing works.
It just uses font 0.

**Comment by patrick96** [comment]
Unfortunately there is no built-in font property for formats. `label-occupied-font` and `label-focused-font` should work, however the `-font` property is a 1-based index, so `label-focused-font = 3` will use `font-2`.

What you could also do, is wrap the `format` value in [Font Tags](https://github.com/jaagr/polybar/wiki/Formatting#font-t) which will probably be less work.

**Comment by NBonaparte** [comment]
Depending on your use case, you could also try reordering the fonts and moving font 3 to font 0.

**Comment by karasuma-chitose** [comment]
> the -font property is a 1-based index
Oh.
