### ISSUE TITLE
Underline spacing

### ISSUE THREAD

**Issue by rien333** [jaagr/polybar#1357]
Is it possible to (re)define the space between the underline and a module? For example, I would prefer a thin underline in the i3 module,  but setting `underline-size = 1` leaves a lot of whitespace between the desktop labels and the underline. In my case, the underline extends well beyond any other part of the bar.  I tried a variety of educated guesses (e.g. `underline-offset-y`) after reading the formatting wiki, but nothing seems to work.

**Comment by patrick96** [comment]
There is no explicit space between the module and the underline, modules and the two lines occupy the same space, the whole height of the bar, the overline always sticks to the top and grows down, the underline sticks to the bottom and grows up, the module text is put somewhere in the middle.
So a smaller bar height should reduce the gap between the text and the line. You could also use the font offset to move the text further down.

>In my case, the underline extends well beyond any other part of the bar.

What do you mean by that?

**Comment by rien333** [comment]
Ah, so you have some control over it with the height variable. This can be closed then.
