### ISSUE TITLE
Undefined bar: exemple

### ISSUE THREAD

**Issue by amanAnkh** [jaagr/polybar#1366]
Hi, I have a little problem with polybar.
When I try to lancee polybar in the console with the example bar I receive an error message. So I tried to use the more recent version by recompiling and nothing nor done.

OS: `Arch Linux x86_64`
Shell: `zsh 5.5.1` 
WM: `i3` 
Polybar `3.2.0-12-gfba8722`
Features: `+alsa +curl +i3 -mpd +network +pulseaudio +xkeyboard`
Config path: `~/.config/polybar`
Config file: [config.txt](https://github.com/jaagr/polybar/files/2267233/config.txt) (the name of file is `config` not `config.txt`)

Test performed
\> polybar exemple
`error: Undefined bar: exemple`

\> polybar -l info exemple 
```
* Loading config: /home/anthony/.config/polybar/config
error: Undefined bar: exemple
* Waiting for spawned processes to end
* Reached end of application...
```
is there any way to get more information about what polybar does and why he can't find my bar example?
Thank you in advance and if you need more information

**Comment by patrick96** [comment]
For some reason your config file uses DOS line-endings (CR LF) instead of unix line-endings (LF). Polybar doesn't support that (yet). Please [convert the config file to unix line-endings](https://www.cyberciti.biz/faq/howto-unix-linux-convert-dos-newlines-cr-lf-unix-text-format/) and it will work.

**Comment by amanAnkh** [comment]
Thanks for your time. Problem fixed
