### ISSUE TITLE
Touch screen support 

### ISSUE THREAD

**Issue by nealot** [jaagr/polybar#1368]
Currently none of the mouse events work on a touch screen laptop. I suggest that touch support be enabled for hardware which supports it.

**Comment by patrick96** [comment]
Does click-left not work? I would have guessed that X handles the touchscreen interactions and just sends normal key codes to its windows.

I don't have a touchscreen device to test this on. Could you please run your bar with `-l trace`, try to click in a few places with the touchscreen, then shut down the bar and post the whole output polybar produced in the terminal here. This will give us some info as to what kind of events polybar actually receives when you use the touchscreen.

**Comment by nealot** [comment]
Hey, sorry for the delay! After investigating I found the problem to be unrelated to polybar so I'll close this issue.

**Comment by patrick96** [comment]
So, polybar works with a touchscreen?

**Comment by nealot** [comment]
I don't notice any deficiencies when testing it on my convertible laptop, so yes. Although [this](https://github.com/ssmolkin1/i3touchmenu#rotation.) problem still makes polybar uncomfortable when rotating.

**Comment by patrick96** [comment]
Yeah, polybar doesn't auto-adjust when the screen size changes. I think we would need some quite big architectural changes for that. But I'm sure you can externally detect when a screen changes and restart polybar from the outside with `polybar-msg cmd restart`.

**Comment by NBonaparte** [comment]
So `screenchange-reload = true` doesn’t work with rotations?

**Comment by patrick96** [comment]
I totally forgot about this. I never tested it but theoretically it should. @nealot, try adding `screenchange-reload = true` to the `[settings]` section in your config and see if polybar automatically reloads when you rotate.

**Comment by nealot** [comment]
I actually already have that setting enabled. The problem with rotation isn't that polybar remains in its original vertical/horizontal state, but rather how the modules are not dynamically adjusting to the rotation. In other words, polybar itself works fine but some modules are cut off from view. The solution to this would be to create a second polybar with fewer/more modules and activate it when rotating to account for the dimensions being reversed.

**Comment by patrick96** [comment]
I don't think I follow. Is there still space on the bar and the modules are not using it or is there just so much text on the bar that it couldn't possibly fit?

**Comment by nealot** [comment]
So this is what it looks like after rotating vertically 
![image](https://user-images.githubusercontent.com/36805289/44633572-4801dd80-a95b-11e8-86a8-71c84349c38c.png).

**Comment by patrick96** [comment]
Yeah, that's going to be expected if not all of the modules fit.
