### ISSUE TITLE
Use alt labels on the battery module

### ISSUE THREAD

**Issue by LucasHMS** [jaagr/polybar#1372]
Similarly to the data module, is there some way to create alternative labels to the battery time displaying? Specifically, what I want is to be able to show the time left , while discharging, only when there is a mouse click over the percentage.
Here is the configuration I imagined:
```
....
format-discharging-prefix = " "
format-discharging-prefix-foreground = ${colors.foreground-alt}
time-format = %H:%M
label-discharging = %percentage%%
label-discharging-alt = %percentage%% (%time%)
format-discharging =  <label-discharging>
.....
```

**Comment by patrick96** [comment]
There is already a PR for this in #1051. It's not ready to merge yet, and it may be some time before it is, but this is being worked on.
