### ISSUE TITLE
Move to a different PPA to host for Ubuntu

### ISSUE THREAD

**Issue by Trevortds** [jaagr/polybar#1373]
I am not personally experienced enough to know why the ubuntu repositories were not used in the first place, or why a different self-hosted PPA was not chosen, but I do know that GetDeb has a history of unreliability and as of August 11, has been down for weeks.

**Comment by patrick96** [comment]
The packaging for Ubuntu was not done by us, but by some independent third party (as it is done for all distros except for arch). We simply list the various places where polybar is available in the README but are not directly involved in the packaging. If polybar should be available through another PPA, someone would need to take intiative themselves and package and publish it. We don't have that kind of time to package polybar for multiple distros.
