### ISSUE TITLE
using multiple fonts on label

### ISSUE THREAD

**Issue by GoingFast** [jaagr/polybar#1376]
hello. I'm using the openweather map script however I have a problem. If I dont specify label-font to weather icons then the weather icons display some other shit and the text font is my main one, but if I specify the weather icon font using label-font then the text goes fucked up and is not in sync with the rest of bar. stands really out and bad. How do I specify multiple fonts to a label? Or how would I fix this issue? thanks

**Comment by patrick96** [comment]
You can use [font tags](https://github.com/jaagr/polybar/wiki/Formatting#font-t) to switch fonts within the same label
