### ISSUE TITLE
custom/menu documentation incorrect?

### ISSUE THREAD

**Issue by nathanchere** [jaagr/polybar#1387]
https://github.com/jaagr/polybar/wiki/Module:-menu

This lists `label-open` as "Additional formatting" suggesting it is an optional setting. But creating a module without `label-open` specified gives:

> error: Disabling module "menu" (reason: Missing parameter "module/menu.label-open")

Is it OK to update the documentation to reflect that being required?

**Comment by patrick96** [comment]
Sure, go ahead. Close this when you're done.

**Comment by patrick96** [comment]
Thanks! I had to make a small change, because `label-close` is truly optional
