### ISSUE TITLE
Way to remove spacing between cores in power module

### ISSUE THREAD

**Issue by nathanchere** [jaagr/polybar#1389]
The power module's `<ramp-coreload>` option is really cool, but it takes up way more space on the bar than is needed to get its point across. For example on a 16-core machine:

```
 CPU: ▂ ▄ ▄ ▂ ▂ ▂ ▇ ▄ ▂ ▂ ▂ ▂ ▄ ▂ ▂ (17%)`
```
it would be so much more space efficient to display without those gaps (and look better in many instances!):
```
 CPU: ▂▄▄▂▂▂▇▄▂▂▂▂▄▂▂ (17%)`
```
`ramp-coreload-margin` works for increasing the gap but not removing it entirely. The only solution I've found so far is to use a pixel offset in the format of each individual core label, e.g:

```
ramp-coreload-0 = "%{O-12}%{F#999}▁"
ramp-coreload-1 = "%{O-12}%{F#977}▂"
ramp-coreload-2 = "%{O-12}%{F#955}▃"
ramp-coreload-3 = "%{O-12}%{F#931}▄"
ramp-coreload-4 = "%{O-12}%{F#900}▅"
ramp-coreload-5 = "%{O-12}%{F#B00}▆"
ramp-coreload-6 = "%{O-12}%{F#D00}▇"
ramp-coreload-7 = "%{O-12}%{F#F00}█"
```

but this pixel-specific approach doesn't work with things like changing fonts and breaks other workarounds like having a common bar format with standard resolution and "hi-DPI" bars inheriting from that.

I'm thinking `<ramp-coreload-padding>` would be the most consistent place to implement this? Or maybe even a more global or bar-wide setting to define the spacing between ramp glyphs in this kind of widget?

[edit: oops, `<tags>` need to be escaped or don't show up]

**Comment by patrick96** [comment]
I agree the spacing should be customizable.

The `ramp-coreload` is a bit special, when building the output, it simply duplicates the content as many times as you have cores (see [`cpu.cpp:98`](https://github.com/jaagr/polybar/blob/master/src/modules/cpu.cpp#L98)), nothing else in polybar does this I think, so global settings wouldn't make sense here.
`ramp-coreload-padding` actually already works to increase padding but the base spacing of one character is always there. Also `padding` adds spacing on both sides, so a padding of 1 effectively adds two characters in between the cores.
Maybe we could create a new key `ramp-coreload-spacing` where the user can set the spacing.

Would you be willing to work on this?

**Comment by nathanchere** [comment]
I likely won't have any serious time to dedicate to this for a couple more weeks but it seems like it should be an easy enough thing to knock over in a weekend as a first contribution.

**Comment by patrick96** [comment]
That would be fine, if we implemented it, it would take way longer than that because there are lots of other things to be done around here.

**Comment by nathanchere** [comment]
This was going to be one of my Hacktoberfest PRs :(
But great to see it implemented either way :)

**Comment by patrick96** [comment]
Sorry about that. Didn't know there was still a PR coming since it's been two months. I'm sure you will find something else to contribute, bug fixes are always welcome ;)
