### ISSUE TITLE
Network module doesn't work properly with wlp1s0 interface

### ISSUE THREAD

**Issue by lucasdavidferrero** [jaagr/polybar#1398]
It seems like the network module has some problems and here goes another one. The issue is that the module (somehow) doesn't recognize that I'm connected to a Wi-Fi network and instead It always displays what "format-disconnected" says.
Basically, It never shows the "format-connected" output even though I'm connected to a Wi-Fi network. I'm using wlp1s0 interface.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```config file
[color]
white = #ffffff
black = #000000

[bar/awesomeBarTOP]
bottom = false
width = 100%
height = 26
line-size = 2
background = ${color.black}
foreground = ${color.white}
padding-left = 2
padding-right = 2
font-0 = Ubuntu:size=10;2
font-1 = Font Awesome 5 Brands:style=Solid:size=12;3
font-2 = Font Awesome 5 Free:style=Solid:size=12;3
modules-left = i3
modules-right = wireless-network battery
modules-center = date
module-margin = 1.5
separator = |
locale = es_AR.UTF-8


[module/i3]
include-file = /home/whitewizard/.config/polybar/modules/i3

[module/wireless-network]
include-file = /home/whitewizard/.config/polybar/modules/networkWireless
```

```networkfile
type = internal/network
interface = wlp1s0
interval = 3.0
format-connected = <label-connected>
label-connected = %signal% OK

format-disconnected = disconnected :c

```

Polybar Log:
It shows nothing.

![networkproblem](https://user-images.githubusercontent.com/15804058/44623346-b5a9fd00-a8ba-11e8-9a20-72660e474e22.png)

## Environment:
* WM: i3wm
* Output of `polybar  3.2.0-20-g0ae4de7

Features: +alsa -curl +i3 -mpd +network +pulseaudio -xkeyboard

X extensions: +randr (-monitors) -render -damage -sync -composite -xkb -xrm -xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags:  -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags:`:

**Comment by patrick96** [comment]
What's the SSID of the network you're connected to? In the past this kind of issue was almost always related to this.

**Comment by lucasdavidferrero** [comment]
@patrick96 There is an image above showing the SSID. current SSID= "---------______________---------"

**Comment by lucasdavidferrero** [comment]
problem solved. Seems like there is a problem with some SSID.

**Comment by patrick96** [comment]
Yeah, SSIDs with 32 characters seem to be a problem, at least for the legacy wireless backend. If you compile with `-DWITH_LIBNL=ON` (in `cmake`), it should use the new implementation which doesn't have that problem.
