### ISSUE TITLE
Setting module background color

### ISSUE THREAD

**Issue by hallonfras** [jaagr/polybar#1401]
Hi!
I was wondering if its possible to set a different background color for each module kind of like how the system tray can have a different background color.
Is it possible?

**Comment by patrick96** [comment]
Yes you can. Each module generally defines one or more `format*` keys. Those formats define what your modules display, if you set the background of those formats, it will set the background for the whole module (see [here](https://github.com/jaagr/polybar/wiki/Formatting#formats)).
