### ISSUE TITLE
Have configs that matches the screenshots showed in the README

### ISSUE THREAD

**Issue by daltonmatos** [jaagr/polybar#1403]
Hello all,

The README file shows 4 examples of polybar configurations as shown by the screenshots.

Do you still have the configs that were used to produce these screenshots? I'm specially interested in the first one.

[![sample screenshot](http://i.imgur.com/xvlw9iHt.png)](http://i.imgur.com/xvlw9iH.png)

Would be awesome to have these configs available along with the project's source code.

Thanks,

**Comment by TonCherAmi** [comment]
You can find them [here](https://github.com/jaagr/dots/tree/master/.local/etc/themer/themes).

**Comment by daltonmatos** [comment]
Thank you very much @TonCherAmi. Do you tink it would be a good idea do add this info to the project docs? Or at least in the README, below the example images.

@jaagr, what do you think about this?

Thanks!

**Comment by TonCherAmi** [comment]
@daltonmatos I don't think it's a bad idea personally. You could open a PR if you'd like, but it will be up to the maintainers whether it's merged or not.

**Comment by daltonmatos** [comment]
Sure! That's why a mentioned @jaagr, to know upfront if this PR has a chance to be accepted.

Let's see what he thinks.

Thanks,

**Comment by NBonaparte** [comment]
Go ahead and make a PR, we'll merge it. I'm pretty sure this question has been asked before, so it would be great if it was already in the README.
