### ISSUE TITLE
Custom script appears to be broken on fish (with polybar running as a service)

### ISSUE THREAD

**Issue by JonathanReeve** [jaagr/polybar#1405]
## Describe the issue
*A clear and concise description of what the bug is.*

When I run polybar as a service (i.e. through systemctl --user), in the spot where I hope to see the output of my custom script, I see: `/nix/store/...../bin/bash: env: command not found`, where /nix/store/...../bin/bash is just the path to my BASH 

**Expected behavior:**

I expected to see the output of my script. 

**Actual behavior:**

I see `/nix/store/...../bin/bash: env: command not found`. 

## To Reproduce
*A minimal but complete config with which the problem occurs:*

Here's the relevant part of my config: 

```dosini
[module/org-clock]
type = custom/script
interval = 10
exec = /home/jon/Dotfiles/scripts/org-clock.sh
click-left = emacsclient --eval '(org-clock-out)' && echo " Stopped!"
```

And here's my script: 

```fish
#!/run/current-system/sw/bin/fish

# Debugging
echo "Hey! Shell: $SHELL PWD: $PWD User: $USER DesktopSession: $DESKTOP_SESSION" >> /tmp/org-clock

set CLOCKSTRING (emacsclient --eval '(if (org-clocking-p)(org-clock-get-clock-string) -1)' 2>&1 )

echo $CLOCKSTRING >> /tmp/org-clock

switch "$CLOCKSTRING"
case "*can\'t find socket*"
    echo " Emacs off!"
case "-1"
    echo " Emacs off!"
case "*server-start*"
    echo " Emacs off!"
case "*ERROR*"
    echo " Off-clock!"
case "*function definition*"
    echo " Off-clock!"
case "*"
    echo (echo $CLOCKSTRING | cut -d\" -f2 | head -c35)
end

echo "DONESO!" >> /tmp/org-clock

```

And here's what /tmp/org-clock looks like (I'm only creating this, and the debug messages, so I can be sure the whole script is running: 

```
Hey! Shell: /run/current-system/sw/bin/fish PWD: /home/jon User: jon DesktopSession: 
*ERROR*: Symbol’s function definition is void: org-clocking-p
DONESO!
```

So what's weird is that: 
 - I'm using fish, so why is it trying to run BASH? And why does BASH not think that `env` exists? 
 - Why does this happen only when I run polybar as a systemd service, but it's apparently running with the same user (me, `jon`), and with the same shell (fish). 

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*

When I run polybar from a terminal, it works fine. No output. It's just when I run it as a service that it doesn't work (and it's only the custom script module that doesn't work). 

## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM: bspwm
* Output of `polybar -vvv`: 
polybar 3.2.1

Features: +alsa -curl -i3 -mpd +network -pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: Release
Compiler: /nix/store/jlbpa06dm81jvbb9jklf5dgvxxad6lgd-gcc-wrapper-7.3.0/bin/g++
Compiler flags:  -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: 

## Additional context
*Add any other context that you think is necessary about the problem here.*

I'm running NixOS. Launching polybar using `polybar main_bar &`. I also tried launching polybar with `polybar main_bar`, but no change. 

If I change my custom script to read: 

```sh
#!/path/to/sh
echo "Hey!"
```

...it works as expected.

This sounds very similar to #323.

**Comment by JonathanReeve** [comment]
Some more relevant info:

The service file that starts polybar is: 

```
[Install]
WantedBy=graphical-session.target

[Service]
Environment=PATH=/nix/store/kgm4jii9kc5sjwvcw4nzzicp0ajky0q2-polybar-3.2.1/bin
ExecStart=/nix/store/ap6w9yhw1ij9yk1k6vvzh6i7l5pw86aa-polybar-start/bin/polybar-start
Type=forking

[Unit]
After=graphical-session-pre.target
Description=Polybar status bar
PartOf=graphical-session.target
X-Restart-Triggers=/nix/store/75kdazr9z48vlwvdir31svz6004qckvn-polybar.conf
```
Maybe it's missing something in the PATH? This is generated here: https://github.com/rycee/home-manager/blob/master/modules/services/polybar.nix

**Comment by JonathanReeve** [comment]
I'm guessing this happens because polybar doesn't have the binaries in the path necessary to find utilities like `head` and even `emacsclient`, so it bails. I rewrote my script in BASH, made sure not to use external utilities, and gave the full path (`/run/current-system/sw/...`) to emacsclient, and now it works.

**Comment by c33s** [comment]
just for reference: for me the problem was that i am behind a proxy server and internet access was only allowed through the proxy. you have to configure the proxy also for systemd. you can do that directly in the unit file or set it globally:

proxies have also be set in both files:
/etc/systemd/user.conf.d/proxy.conf
/etc/systemd/system.conf.d/proxy.conf
```
[Manager]
DefaultEnvironment="HTTP_PROXY=http://proxy.example.at:1080"
DefaultEnvironment="HTTPS_PROXY=http://proxy.example.at:1080"
DefaultEnvironment="NO_PROXY=localhost,127.0.0.1"
DefaultEnvironment="http_proxy=http://proxy.example.at:1080"
DefaultEnvironment="https_proxy=http://proxy.example.at:1080"
DefaultEnvironment="no_proxy=localhost,127.0.0.1"
```

then you have the reload the systemd daemon for system an for the user.

```bash
#user
systemctl --user show-environment | grep PROXY
#root
systemctl show-environment | grep PROXY
```

after that my script worked without problems. 

it is really confusing if your run the bash script in your shell and it works but it doesn't work as systemd unit. but well, proxy stuff.

hope this helps someone.
