### ISSUE TITLE
Unable to get rid of transparency

### ISSUE THREAD

**Issue by Nano-Sec** [jaagr/polybar#1411]
I have the background set to ff252a36, but the bar is still semi transparent (around 80% opacity)
As i understand the notation, the first hex is supposed to represent opacity. I'm not sure what the problem is here. I've attached my config file below.

[issue.txt](https://github.com/jaagr/polybar/files/2346141/issue.txt)

**Comment by Nano-Sec** [comment]
polybar 3.1.0-140-g067aac1 is the version.
Yeah i'm running compton. I have inactive window transparency but that's a different value. Changing that doesn't affect polybar. I've tried. I can attach the compton config if you require it.
Just 252a36 doesn't help either. The opacity still seems to be around 80% or so.

**Comment by patrick96** [comment]
Yes, please post the compton config as well, I suspect it's causing this.

**Comment by Nano-Sec** [comment]
[compton.txt](https://github.com/jaagr/polybar/files/2346231/compton.txt)

**Comment by Nano-Sec** [comment]
The polybar rule was the one i added to force opacity. I didn't notice the _NET_WM_STATE_STICKY. Changing that value did the job. Thank you so much!
