### ISSUE TITLE
Support for randr primary output

### ISSUE THREAD

**Issue by larkery** [jaagr/polybar#1412]
## Is your feature request related to a problem? Please describe.
I use my laptop with different screens which use different outputs. The monitor and monitor-fallback options only let me choose two levels of fallback (e.g. DP1 and LVDS0), whereas practically I would like DP1 or HDMI1, then LVDS0 in the worst case.

I don't always have the main screen on the same side (depends on the desk).
Xrandr has the notion of a primary display, which is supposed to communicate which one is the most important.

## Why does polybar need this feature?
It will make it easier to have a polybar that always appears on the main display, regardless of which socket the display is plugged into.

## Describe the solution you'd like
For polybar to support something like `monitor = PRIMARY` or `monitor-primary = true` in monitor selection. I did look at writing a patch but my x programming skills aren't good enough.

## Describe alternatives you've considered
Ehh, at the moment I can grep this out of the randr config and then patch the config file and restart polybar on randr events. This obviously disappoints.

**Comment by unai-ndz** [comment]
As a better workaround, this is what I use to run polybar on my desktop and on my laptop using the same config files, you can edit this to your needs:

```
#You can also use polybar --list-monitors but AFAIK xrandr outputs them in left to right order
MONITOR1="$(xrandr --listmonitors | grep "0:" | cut -d ' ' -f6)"
MONITOR2="$(xrandr --listmonitors | grep "1:" | cut -d ' ' -f6)"

killall -q polybar
while pgrep -x polybar >/dev/null; do sleep 0.1; done

if [[ -n "$MONITOR1" ]]; then
    MONITOR="$MONITOR1" polybar main &
fi

if [[ -n "$MONITOR2" ]]; then
        MONITOR="$MONITOR2" polybar other &
fi
```

And every bar to be spawned like that needs `monitor = ${env:MONITOR:fallback-value}` on his config.

You also have this setting:
```
[settings]
; Reload upon receiving XCB_RANDR_SCREEN_CHANGE_NOTIFY events
screenchange-reload = false
```
Sadly it's probably not going to work when using `${env:MONITOR}`, same as `polybar --reload` (I only checked the latter though)

**Comment by patrick96** [comment]
Neat idea! The way to do it would probably be to use `monitor-primary`, I'm not a fan of using magic strings.

I could imagine the following process:
* If `monitor-primary = true` use the current primary monitor (this shouldn't handle reloading).
* If `monitor-primary = false` or the primary monitor could not be determined, use the current process to determine the monitor.

This would make `monitor-primary` override all other `monitor-*` settings.

A PR would of course be appreciated, but if you don't feel up to it, we'll get to it when we get to it (I don't immediately see a way to do this).
