### ISSUE TITLE
Which fonts are required?

### ISSUE THREAD

**Issue by hringriin** [jaagr/polybar#1417]
## Describe the issue
There are many explanations on how to configure the fonts to be used and, if you know what font you want, how to find with `fc-cache` or whatever, but the icons in the config, shipped by default, are not mentioned anywhere and neither to which font-package they belong to. If I only missed something, I'm sorry, but I could not find a clue. Installing *every* nerd-font seems to be silly.  
The example bar (and config) is just incomplete this way.

**Expected behavior:**

it would be nice to have the fonts used in the default config as a clear dependency

**Comment by patrick96** [comment]
The `font-0`, `font-1`, and `font-2` keys in the config give you the name of the fonts used. But you're right that they are not listed explicitly anywhere else on here. Some distros will list them as optional dependencies (e.g. [Arch](https://aur.archlinux.org/packages/polybar)).

I have added a note to the [Wiki](https://github.com/jaagr/polybar/wiki/Fonts), but I have some plans to make the documentation more clear in this regard.
