### ISSUE TITLE
polybar example not working.

### ISSUE THREAD

**Issue by HaginCodes** [jaagr/polybar#1418]
## Describe the issue
Trying to configure polybar but when I run `polybar example` I get this error
`Monitor "DP-3" not found or disconnected`

**Expected behavior:**
I expect to see a bar on top that I can start to configure
**Actual behavior:**
`Monitor "DP-3" not found or disconnected`

*What actually happens*
nothing happens

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
it's stock and reinstalled out of the gate no edits.
```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
Monitor "DP-3" not found or disconnected

```

## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM: i3-gaps
* Output of `polybar -vvv`:
polybar 3.2.1

Features: +alsa +curl +i3 -mpd +network +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now

## Additional context
*Add any other context that you think is necessary about the problem here.*

**Comment by patrick96** [comment]
What is the `monitor` key in the bar section `[bar/example]` set to?
In the sample config the `monitor` key is not set but you said the only thing in the polybar output was
```
Monitor "DP-3" not found or disconnected
```
and the combination of those two also requires the warning message 
```
No monitor specified, using "DP-3"
```
in the polybar output. So something's not right here. Did you compile polybar yourself or did you get it prepackaged? While you're at it, please also post the ouptut of `xrandr` and `polybar -m`.

**Comment by HaginCodes** [comment]
polybar -m `eDP1: 1600x900+0+0`
xrandr `Screen 0: minimum 8 x 8, current 1600 x 900, maximum 32767 x 32767
eDP1 connected primary 1600x900+0+0 (normal left inverted right x axis y axis) 310mm x 170mm
   1600x900      60.01 +  59.82  
   1400x900      59.96    59.88  
   1368x768      60.00    59.88    59.85  
   1280x800      59.81    59.91  
   1280x720      59.86    60.00    59.74  
   1024x768      60.00  
   1024x576      60.00    59.90    59.82  
   960x540       60.00    59.63    59.82  
   800x600       60.32    56.25  
   864x486       60.00    59.92    59.57  
   800x450       60.00  
   640x480       59.94  
   720x405       59.51    60.00    58.99  
   640x360       59.84    59.32    60.00  
DP1 disconnected (normal left inverted right x axis y axis)
DP2 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
VGA1 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
  1600x900 (0x4b) 108.068MHz -HSync -VSync
        h: width  1600 start 1648 end 1680 total 1940 skew    0 clock  55.71KHz
        v: height  900 start  903 end  908 total  926           clock  60.16Hz
`

I got it from the aur prepackaged.

**Comment by patrick96** [comment]
You need to set `monitor = eDP1` in the config, currently it's set to `DP-3`.

> I got it from the aur prepackaged.

If you got it from the AUR it's not prepackaged. Did you compile it yourself? If so, there is no way that the monitor is set to `DP-3` in the sample config. You probably have not copied the sample configuration into `~/.config/polybar/config` and the config that is there right now has `monitor = DP-3` set.
