### ISSUE TITLE
Different [under/over]line and background colors per i3wm workspace

### ISSUE THREAD

**Issue by kgilmer** [jaagr/polybar#1428]
## Is your feature request related to a problem? Please describe.
* I would like to provide a different background color for each i3 workspace in my bar *

## Why does polybar need this feature?
* To better support various UIs. *

## Describe the solution you'd like
I would like to declare an array of colors like this:

```
bkg-color-0 = #b58900
bkg-color-1 = #cb4b16
bkg-color-2 = #dc322f
```
and then use them in my i3 module like this:

```
label-focused-background = ${bkg-color-%index%}
```

## Describe alternatives you've considered
*If there is already a way of doing this (dereferencing the workspace index in the list name) I would just use that. *

**Comment by NBonaparte** [comment]
As a workaround, you could use `ws-icon-n` and have each icon be the index wrapped in whatever color formatting you like:
```
ws-icon-0 = 1;%{B#b58900}1%{B-}
```

**Comment by kgilmer** [comment]
@NBonaparte thanks!  I am able to use that technique to get what I want.  Very helpful :)
