### ISSUE TITLE
Multi monitors workspaces reordered after moving desktops

### ISSUE THREAD

**Issue by A1phaZer0** [jaagr/polybar#1432]
Hi, I use bspwm module to show desktops, when I move desktops between two monitors, polybar will show desktops in a different order. e.g. 
```bash
Originally, 4 desktops:

bspc query -D --names
1
2
a
b
polybar : | 1 2 a b |

When hotplug a new monitor with moving a b to that monitor, 
bspwm will give us a new order of desktops like:

bspc query -D --names
a
b
1
2
polybar : | a b 1 2 |
```
So, is there a way to use fixed order in polybar?

**Comment by NBonaparte** [comment]
You should be able to do this from bspwm alone, this is not a polybar issue. Try reassigning desktops 1 and 2 to the original monitor and then move a and b to the second monitor:
```
bspc monitor $ORIGINAL -d 1 2
bspc monitor $NEW -d a b
```

**Comment by A1phaZer0** [comment]
@NBonaparte But that will make all the windows/nodes opened in a/b collapse into desktop 1.

**Comment by NBonaparte** [comment]
You can use `bspc wm --reorder-monitors $ORIGINAL $NEW` after moving the desktops to `$NEW` with your current method: https://github.com/baskerville/bspwm/issues/686
