### ISSUE TITLE
Menu module does not launch apps that start with errors

### ISSUE THREAD

**Issue by lillemets** [jaagr/polybar#1434]
## Description of the issue
When an app starts with an error, it is not started at all by menu module. When I run e.g. `spotify &` in terminal, I get an error but it starts and works perfectly fine. However, menu module does not start the app at all. I've narrowed down the problem to apps that throw errors when run from terminal.

**Expected behavior:** 
All apps run just as if they were started from terminal.

**Actual behavior:**
When an app starts with an error, it is not started at all.

## To Reproduce

```dosini
[bar/top]
width = 100%
height = 22
modules-left = menu

[module/menu]
type = custom/menu
expand-right = false
label-open = Menu
label-close = x
label-separator = "  "

menu-0-0 = Spotify 
menu-0-0-exec = spotify &
```
**Steps to reproduce**

1. Have an app in menu that throws an error when launched
2. Click on *Menu*
3. Click on the app

## Polybar Log

There is no output from Polybar.

## Environment:
* WM: i3-gaps
* Output of `polybar -vvv`:
```
polybar 3.2.1

Features: +alsa +curl +i3 -mpd +network +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment]
See [Known-Issues](https://github.com/jaagr/polybar/wiki/Known-Issues#click-commands-are-not-executed)
