### ISSUE TITLE
Extra invisible border in Openbox.

### ISSUE THREAD

**Issue by JesMJM** [jaagr/polybar#1439]
## Describe the issue

There is a transparent space above polybar where openbox does't put windows.

**Expected behavior:**

The bar uses the space that visibly occupies.

**Actual behavior:**

The bar acts like a window with a extra transparent border on top (or bottom if the bar is on top's screen) and maximized windows doens't cover this space, clicking this area acts as a desktop click and the "resistance to overlap" feature in Openbox works with this invisible border. I tried configuring Polybar with `override-redirect = true` but then the bar never disappears even on fullscreen apps.

## To Reproduce

Occurs with default Polybar and Openbox config.

## Polybar Log
I think there is no useful output in the log, and my own config runs without any error/warning.
```
warn: No monitor specified, using "VGA-1"
error: Disabling module "bspwm" (reason: Could not find socket: /tmp/bspwm_0_0-socket)
error: module/xbacklight: Could not get data (err: XCB_NAME (15))
error: Disabling module "xbacklight" (reason: Not supported for "VGA-1")
warn: pulseaudio: using default sink alsa_output.pci-0000_00_1b.0.analog-stereo
error: Disabling module "battery" (reason: No suitable way to get current chargestate)
error: tray: Failed to put tray above 0x0a00002 in the stack (XCB_MATCH (8))
warn: Dropping unmatched character ─ (U+2500)
warn: Dropping unmatched character ─ (U+2500)
warn: Dropping unmatched character ─ (U+2500)
...
```

## Screenshots
The red area is what i am referring to.
![image](https://user-images.githubusercontent.com/30764221/45935982-438f0b80-bf7f-11e8-860d-64a511d2df68.png)

## Environment:
* WM: Openbox
* Output of `polybar -vvv`: 
```
polybar 3.2.0-31-g2fba443
Features: +alsa +curl -i3 -mpd +network(libnl) +pulseaudio +xkeyboard
X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor
Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

## Additional context

I tried with polybar and polybar-git.
(Sorry if i has bad grammar, English is not my native language)

**Comment by patrick96** [comment]
Can you try setting `margin-bottom = 0` and `margin-top = 0` in the `[global/wm]` section of your config. Those two values should be responsible for this behaviour.

**Comment by JesMJM** [comment]
Guess i didn't check that part on the docs...

Many thanks!, you can close this issue now.
