### ISSUE TITLE
xkeyboard render hex code instead of color

### ISSUE THREAD

**Issue by euri10** [jaagr/polybar#1443]
## Describe the issue
*A clear and concise description of what the bug is.*

The reference to a color defined in the [colors] section isn't interpreted in the xkeyboard module but renderd as its hex code, it's not the case in the workspaces sections for instance where an actual color is renderd

edit actually it does that too in the menu on the far right powermenu

**Expected behavior:**
I would have thought a color instead of it's hex code would appear, maybe it's a wrong usage / configuration on my side

*What actually happens*
see image
![Imgur](https://i.imgur.com/gQpXs7h.png)

## To Reproduce
*A minimal but complete config with which the problem occurs:*
all the colors in xkeyboard modules reference the one in colors section, which are sources from my .Xresources file

.Xresources relevant parts
```
#define S_base00        #839496
*color11:                 S_base00
```

.config/polybar/config relevant parts, foreground-alt aka color11 isn't rendered as you can see in image

```dosini

[colors]
background = ${xrdb:color8}
background-alt = ${xrdb:color3}
foreground = ${xrdb:color7}
foreground-alt = ${xrdb:color11}
primary = ${xrdb:color2}
secondary = $(xrdb:color9}
alert = ${xrdb:color1}

 [module/xkeyboard]
 type = internal/xkeyboard
 ;blacklist-0 = num lock
 
 format-prefix = " "
 format-prefix-foreground = ${colors.foreground-alt}
 format-prefix-underline = ${colors.secondary}

```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```

```

## Screenshots
*If applicable, add screenshots to help explain your problem.*

see above

## Environment:
* WM: i3
* Output of `polybar -vvv`:
```
➜  ~ polybar -vvv
polybar 3.2.0-31-g2fba443

Features: +alsa +curl +i3 +mpd -network(wireless-tools) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags:  -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags:
```
## Additional context
*Add any other context that you think is necessary about the problem here.*

**Comment by patrick96** [comment]
Does this happen too, if you put `format-prefix-foreground = #839496`?
In any case, please post the output when you run polybar additonally with the `-s` argument (let it run for a few seconds and then kill it)

**Comment by euri10** [comment]
same behavior if the hex code is `format-prefix-foreground = #839496`
here's the output of `-s`

`
➜  ~ polybar barright -s
warn: pulseaudio: using default sink alsa_output.usb-Burr-Brown_from_TI_USB_Audio_DAC-00.analog-stereo
%{r}%{A1:volmute: A4:volup: A5:voldown: F#268bd2}VOL%{F-} %{T2}|%{T- F#dc322f T2}─────────%{T- F- A A A}   %{A1:pa_volmute: A4:pa_volup: A5:pa_voldown: F#268bd2}VOL 98%%{F-} %{F#f55 T2}─────────%{T- F- T2}|%{T- A A A}   %{u$(xrdb:color9} +u F#839496} %{F- -u u$(xrdb:color9} +u}gb%{-u u- u-}   %{u#4bffdc +u F#dc322f} %{F- u#4bffdc}37%%{-u u-}   %{u#f90000 +u F#dc322f} %{F- u#f90000} 0%%{-u u-}   %{u#f50a4d +u u#f50a4d F#dc322f}%{F-} %temperature-c%%{-u u-}   %{u#0a6cf5 +u F#dc322f}%{F- u#0a6cf5 A1:datetoggle:}%date% %time%%{A -u u-}   %{A1:menu-open-0: F$(xrdb:color9}}%{F- A}
%{r}%{F#0a81f5}/%{F-}: 92%   %{A1:volmute: A4:volup: A5:voldown: F#268bd2}VOL%{F-} %{T2}|%{T- F#dc322f T2}─────────%{T- F- A A A}   %{A1:pa_volmute: A4:pa_volup: A5:pa_voldown: F#268bd2}VOL 98%%{F-} %{F#f55 T2}─────────%{T- F- T2}|%{T- A A A}   %{u$(xrdb:color9} +u F#839496} %{F- -u u$(xrdb:color9} +u}gb%{-u u- u-}   %{u#4bffdc +u F#dc322f} %{F- u#4bffdc}37%%{-u u-}   %{u#f90000 +u F#dc322f} %{F- u#f90000} 0%%{-u u-}   %{u#f50a4d +u u#f50a4d F#dc322f}%{F-} 28°C%{-u u-}   %{u#0a6cf5 +u F#dc322f}%{F- u#0a6cf5 A1:datetoggle:}%date% %time%%{A -u u-}   %{A1:menu-open-0: F$(xrdb:color9}}%{F- A}
%{l}%{A5:i3wm-wsprev: A4:i3wm-wsnext: A1:i3wm-wsfocus-1\:dev:}    %{A A1:i3wm-wsfocus-2\:www: u#859900 +u B#859900}    %{B- -u A A1:i3wm-wsfocus-3\:chat:}    %{A A1:i3wm-wsfocus-4\:terminal: u#859900 +u B#859900}    %{B- -u A A1:i3wm-wsfocus-5\:bordel:}    %{A A A u-}%{r}%{F#0a81f5}/%{F-}: 92%   %{A1:volmute: A4:volup: A5:voldown: F#268bd2}VOL%{F-} %{F#f55 T2}─────────%{T- F- T2}|%{T- A A A}   %{A1:pa_volmute: A4:pa_volup: A5:pa_voldown: F#268bd2}VOL 98%%{F-} %{F#f55 T2}─────────%{T- F- T2}|%{T- A A A}   %{u$(xrdb:color9} +u F#839496} %{F- -u u$(xrdb:color9} +u}gb%{-u u- u-}   %{u#4bffdc +u F#dc322f} %{F- u#4bffdc}37%%{-u u-}   %{u#f90000 +u F#dc322f} %{F- u#f90000} 0%%{-u u-}   %{u#f50a4d +u u#f50a4d F#dc322f}%{F-} 28°C%{-u u-}   %{u#0a6cf5 +u F#dc322f}%{F- u#0a6cf5 A1:datetoggle:} 09:19%{A -u u-}   %{A1:menu-open-0: F$(xrdb:color9}}%{F- A}
%{l}%{A5:i3wm-wsprev: A4:i3wm-wsnext: A1:i3wm-wsfocus-1\:dev:}    %{A A1:i3wm-wsfocus-2\:www: u#859900 +u B#859900}    %{B- -u A A1:i3wm-wsfocus-3\:chat:}    %{A A1:i3wm-wsfocus-4\:terminal: u#859900 +u B#859900}    %{B- -u A A1:i3wm-wsfocus-5\:bordel:}    %{A A A u-}%{r}%{F#0a81f5}/%{F-}: 92%   %{A1:volmute: A4:volup: A5:voldown: F#268bd2}VOL%{F-} %{F#f55 T2}─────────%{T- F- T2}|%{T- A A A}   %{A1:pa_volmute: A4:pa_volup: A5:pa_voldown: F#268bd2}VOL 98%%{F-} %{F#f55 T2}─────────%{T- F- T2}|%{T- A A A}   %{u$(xrdb:color9} +u F#839496} %{F- -u u$(xrdb:color9} +u}gb%{-u u- u-}   %{u#4bffdc +u F#dc322f} %{F- u#4bffdc}37%%{-u u-}   %{u#f90000 +u F#dc322f} %{F- u#f90000} 0%%{-u u-}   %{u#f50a4d +u u#f50a4d F#dc322f}%{F-} 28°C%{-u u-}   %{u#0a6cf5 +u F#dc322f}%{F- u#0a6cf5 A1:datetoggle:} 09:19%{A -u u-}   %{A1:menu-open-0: F$(xrdb:color9}}%{F- A}
%{l}%{A5:i3wm-wsprev: A4:i3wm-wsnext: A1:i3wm-wsfocus-1\:dev:}    %{A A1:i3wm-wsfocus-2\:www: u#859900 +u B#859900}    %{B- -u A A1:i3wm-wsfocus-3\:chat:}    %{A A1:i3wm-wsfocus-4\:terminal: u#859900 +u B#859900}    %{B- -u A A1:i3wm-wsfocus-5\:bordel:}    %{A A A u-}%{r}%{F#0a81f5}/%{F-}: 92%   %{A1:volmute: A4:volup: A5:voldown: F#268bd2}VOL%{F-} %{F#f55 T2}─────────%{T- F- T2}|%{T- A A A}   %{A1:pa_volmute: A4:pa_volup: A5:pa_voldown: F#268bd2}VOL 98%%{F-} %{F#f55 T2}─────────%{T- F- T2}|%{T- A A A}   %{u$(xrdb:color9} +u F#839496} %{F- -u u$(xrdb:color9} +u}gb%{-u u- u-}   %{u#4bffdc +u F#dc322f} %{F- u#4bffdc}37%%{-u u-}   %{u#f90000 +u F#dc322f} %{F- u#f90000}16%%{-u u-}   %{u#f50a4d +u u#f50a4d F#dc322f}%{F-} 28°C%{-u u-}   %{u#0a6cf5 +u F#dc322f}%{F- u#0a6cf5 A1:datetoggle:} 09:19%{A -u u-}   %{A1:menu-open-0: F$(xrdb:color9}}%{F- A}
%{l}%{A5:i3wm-wsprev: A4:i3wm-wsnext: A1:i3wm-wsfocus-1\:dev:}    %{A A1:i3wm-wsfocus-2\:www: u#859900 +u B#859900}    %{B- -u A A1:i3wm-wsfocus-3\:chat:}    %{A A1:i3wm-wsfocus-4\:terminal: u#859900 +u B#859900}    %{B- -u A A1:i3wm-wsfocus-5\:bordel:}    %{A A A u-}%{r}%{F#0a81f5}/%{F-}: 92%   %{A1:volmute: A4:volup: A5:voldown: F#268bd2}VOL%{F-} %{F#f55 T2}─────────%{T- F- T2}|%{T- A A A}   %{A1:pa_volmute: A4:pa_volup: A5:pa_voldown: F#268bd2}VOL 98%%{F-} %{F#f55 T2}─────────%{T- F- T2}|%{T- A A A}   %{u$(xrdb:color9} +u F#839496} %{F- -u u$(xrdb:color9} +u}gb%{-u u- u-}   %{u#4bffdc +u F#dc322f} %{F- u#4bffdc}37%%{-u u-}   %{u#f90000 +u F#dc322f} %{F- u#f90000}16%%{-u u-}   %{u#f50a4d +u u#f50a4d F#dc322f}%{F-} 28°C%{-u u-}   %{u#0a6cf5 +u F#dc322f}%{F- u#0a6cf5 A1:datetoggle:} 09:19%{A -u u-}   %{A1:menu-open-0: F$(xrdb:color9}}%{F- A}
%{l}%{A5:i3wm-wsprev: A4:i3wm-wsnext: A1:i3wm-wsfocus-1\:dev:}    %{A A1:i3wm-wsfocus-2\:www: u#859900 +u B#859900}    %{B- -u A A1:i3wm-wsfocus-3\:chat:}    %{A A1:i3wm-wsfocus-4\:terminal: u#859900 +u B#859900}    %{B- -u A A1:i3wm-wsfocus-5\:bordel:}    %{A A A u-}%{r}%{F#0a81f5}/%{F-}: 92%   %{A1:volmute: A4:volup: A5:voldown: F#268bd2}VOL%{F-} %{F#f55 T2}─────────%{T- F- T2}|%{T- A A A}   %{A1:pa_volmute: A4:pa_volup: A5:pa_voldown: F#268bd2}VOL 98%%{F-} %{F#f55 T2}─────────%{T- F- T2}|%{T- A A A}   %{u$(xrdb:color9} +u F#839496} %{F- -u u$(xrdb:color9} +u}gb%{-u u- u-}   %{u#4bffdc +u F#dc322f} %{F- u#4bffdc}37%%{-u u-}   %{u#f90000 +u F#dc322f} %{F- u#f90000}18%%{-u u-}   %{u#f50a4d +u u#f50a4d F#dc322f}%{F-} 28°C%{-u u-}   %{u#0a6cf5 +u F#dc322f}%{F- u#0a6cf5 A1:datetoggle:} 09:19%{A -u u-}   %{A1:menu-open-0: F$(xrdb:color9}}%{F- A}
warn: Termination signal received, shutting down...
warn: module/i3: Attempting to reconnect socket (reason: Unexpected EOF while reading header)
`

**Comment by patrick96** [comment]
I think this line messes things up

```dosini
secondary = $(xrdb:color9}
```

Because you have unmatched curly brackets which fool the parser into thinking the formatting tag is closed earlier than it is supposed to be

**Comment by euri10** [comment]
ok, in the end, I fixed it by deleting this line and replacing it with the exact same one and it works, so weird !

maybe I had an invisible character in the config file, I used the one generated after compile, my vim statusline doesn't show anything wrong in the hex codes so really I don;t get how that happens, I can Ctrl+R and reproduce the error, then rechange the line and all is ok.

well thanks for the help anyway

**Comment by patrick96** [comment]
Are you sure you added the exact same line and did not change the opening parenthesis to a curly bracket?

**Comment by euri10** [comment]
omg, you're right, I didn't even notice in your answer that I had a parenthesis instead of a curly brace.
Time to buy a new pair of glasses, and to install InputMono on vim too.
Sorry  for that
