### ISSUE TITLE
Unable to get playback volume

### ISSUE THREAD

**Issue by koxu1996** [jaagr/polybar#1448]
I am using ALSA module with percentage format. The problem is that I am seeing 0% after volume update which is totally incorrect, because `amixer` shows another value:
![1538338064](https://user-images.githubusercontent.com/6506780/46262182-d559c400-c4fd-11e8-8134-1678cb888284.png)

I investigated the problem and _snd_mixer_selem_get_playback_dB()_ in https://github.com/jaagr/polybar/blob/master/src/adapters/alsa/mixer.cpp#L129 return error code -22 (~EINVAL), which is not handled. I also checked _snd_mixer_selem_get_playback_volume()_ and it surprisingly works.

## Environment:
* WM: i3-gaps
* Output of `polybar -vvv`:
```
polybar 3.2.1

Features: +alsa +curl +i3 +mpd +network +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/sbin/c++
Compiler flags:  -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags:
```

## Additional context
I am using _GENIUS SW 2.1_ speakers connected to rear panel. Output of `amixer`:
```
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 16385 [25%] [on]
  Front Right: Playback 16385 [25%] [on]
Simple mixer control 'Capture',0
  Capabilities: cvolume cswitch cswitch-joined
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 65536
  Front Left: Capture 30421 [46%] [on]
  Front Right: Capture 30421 [46%] [on]
```

**Comment by NBonaparte** [comment]
What does `alsamixer` show?

**Comment by koxu1996** [comment]
**default device**
![default](https://user-images.githubusercontent.com/6506780/46270257-f7c3ff80-c546-11e8-9a8c-6e5c441d0d06.png)
**0 HDA Intel PCH**
a) playback
![intel-playback](https://user-images.githubusercontent.com/6506780/46270262-feeb0d80-c546-11e8-9e12-a2cdecb38ca8.png)
b) capture
![intel-capture](https://user-images.githubusercontent.com/6506780/46270265-014d6780-c547-11e8-9cca-028150348111.png)
**1 HDA NVidia**
![nvidia](https://user-images.githubusercontent.com/6506780/46270270-04485800-c547-11e8-989d-e66270a8920d.png)

**Comment by NBonaparte** [comment]
It looks like you're using Pulseaudio, why don't you use the `pulseaudio` module instead?

**Comment by koxu1996** [comment]
These are two different working workarounds:
 - removing _pulseaudio-alsa_
 - replacing _alsa_ module with _pulseaudio_

I found [old post](https://lists.freedesktop.org/archives/pulseaudio-discuss/2008-July/002012.html) stating that dB scale does not work with pulseaudio, however _polybar_ should handle error code from `snd_mixer_selem_get_playback_dB()` and at least log error message. Fallback mechanism would be nice, but I do not think it is necessary.
