### ISSUE TITLE
Xworkspaces module creates floating point exception on 2BWM

### ISSUE THREAD

**Issue by abraxous** [jaagr/polybar#1462]
Polybar can be used without the xworkspaces module on 2BWM, or with it on i3 (I have not tested other WMs). When the xworkspaces module is used in 2BWM, polybar fails with message "Floating Point Exception". I suspect this is a result of _NET_DESKTOP_NAMES not being properly handled by 2BWM. I didn't see the floating point exception mentioned in the other issue request mentioning _NET_DESKTOP_NAMES, however, so I decided it would be worth putting in an issue for documentation's sake at the very least.

Here's a sample config for testing

*A minimal but complete config with which the problem occurs:*
```dosini
[colors]
;background = ${xrdb:color0:#222}
;background = #222
;background-alt = #444
;foreground = ${xrdb:color7:#222}
;foreground = #dfdfdf
;foreground-alt = #555
;primary = #ffb52a
;secondary = #e60053
;alert = #bd2c40
background = ${xrdb:color0:#222}
background-alt = ${xrdb:color0:#222}
foreground = ${xrdb:color7:#222}
foreground-alt = ${xrdb:color7:#222}
primary = ${xrdb:color1:#222}
secondary = ${xrdb:color2:#222}
alert = ${xrdb:color3:#222}

[module/ewmh]
type = internal/xworkspaces

[bar/test]
bottom = false
dock = false
width = 100%
height = 25
offset-x = 0
offset-y = 0
override-redirect = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3
line-color = #f00

border-left-size = 10
border-right-size = 10
border-top-size = 10
border-bottom-size = 0
border-color = #00000000

padding-left = 2
padding-right = 2

module-margin-left = 2
module-margin-right = 2

font-0 = fixed:pixelsize=10;1
font-1 = unicode:fontformat=truetype:size=8:antialias=false;0
font-2 = "Wuncon siji:pixelsize=10;1"

modules-left =
modules-center = ewmh
modules-right =
tray-position = right
tray-padding = 2

cursor-click = pointer
```

**Comment by patrick96** [comment]
Can confirm.

SIGFPE happens here: https://github.com/jaagr/polybar/blob/master/src/modules/xworkspaces.cpp#L166

It's because 2bwm doesn't set `_NET_DESKTOP_NAMES` while having `_NET_NUMBER_OF_DESKTOPS` set to 10. This is a polybar bug, the standard specifies that `_NET_DESKTOP_NAMES` can have fewer names than `_NET_NUMBER_OF_DESKTOPS`:

>  Note: The number of names could be different from _NET_NUMBER_OF_DESKTOPS. If it is less than _NET_NUMBER_OF_DESKTOPS, then the desktops with high numbers are unnamed. If it is larger than _NET_NUMBER_OF_DESKTOPS, then the excess names outside of the _NET_NUMBER_OF_DESKTOPS are considered to be reserved in case the number of desktops is increased. 
https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm140200472706208

This bug will happen on any WM that sets `_NET_NUMBER_OF_DESKTOPS > 0` and `count(_NET_DESKTOP_NAMES) = 0`

The PR #904 already touched on this. It was also suggested to properly handle this way back in #248.

Seems we need to give that PR more priority.

**Comment by frstrikerman** [comment]
this pull request seams to patch this issue on the 2bwm side : https://github.com/venam/2bwm/pull/33 
![image](https://user-images.githubusercontent.com/19488257/50537437-ccf64100-0b5f-11e9-91ce-40aa07280d8d.png)

**Comment by kronn** [comment]
I think I solved this in #882, but https://github.com/jaagr/polybar/pull/882/commits/a6fde5be9773b8dc05881db61ec58b7faa1f0ae5 could be cherry-picked to help resolve this issue. If it helps, I can prepare a PR to resolve this issue with the aforementioned commit.

**Comment by patrick96** [comment]
@kronn We would be happy about a PR, thanks. I desperately need to get around to review your PR though as well, but I think a separate PR would be the fastest way to get this fixed.

**Comment by frstrikerman** [comment]
I made my own fix today if your interested : https://github.com/frstrikerman/polybar/commit/84fd9e74ba077d9d39c6c53d0eeec8f00ab4927a
