### ISSUE TITLE
index-sort isn't working properly [i3]

### ISSUE THREAD

**Issue by makmm** [jaagr/polybar#1467]
## Describe the issue
when using `index-sort` under the `internal/i3` module, setting it to true won't change anything and still sorts by the order the workspaces appear.

**Expected behavior:**
sort via index eg: [1] [2] [3]

**Actual behavior:**
sorted by when the workspaces are used eg: [1] [3] [2]

## To Reproduce
```dosini
[bar/bar1]
modules-left = i3

[module/i3]
type = internal/i3
index-sort = true
```

## Environment:
* WM: `i3wm`
* Output of `polybar -vvv`:
```
~$ polybar -vvv
polybar 3.2.1

Features: -alsa +curl +i3 +mpd +network +pulseaudio -xkeyboard

X extensions: +randr (+monitors) -render -damage -sync -composite -xkb -xrm -xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags:  -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: 
```

**Comment by patrick96** [comment]
I'm having a hard time reproducing this. With and without `index-sort = true` my workspaces appear in order (1 2 3). Do you have anything special set in your i3 config to make this happen? Are you using multiple monitors?

Can you reproduce the problem on your end with the minimal config and the post the output of the following command here please:
```bash
i3-msg -t get_workspace
```
or if you have `jq` installed
```bash
i3-msg -t get_workspace | jq
```

**Comment by makmm** [comment]
yes, the problem still happens with the minimal config. is it possible that because i renamed my workspaces (eg [1] -> [z]) polybar can't identify it? now that i think about it, yeah, that's probably it. i'll try in a few minutes with the workspaces called 1-2-3-etc.

```
~/.config/polybar$ i3-msg -t get_workspace 
Unknown message type
Known types: run_command, get_workspaces, get_outputs, get_tree, get_marks, get_bar_config, get_binding_modes, get_version, get_config, send_tick
~/.config/polybar$ i3-msg -t get_workspace | jq
parse error: Invalid numeric literal at line 1, column 8
```

**Comment by makmm** [comment]
yup, by setting all the workspaces named with numbers they order correctly. close this issue?\\

1 quick question: is it possible to show certain workspaces even if i didn't yet put anything on them?

**Comment by patrick96** [comment]
Oh, I actually wanted to write `i3-msg -t get_workspaces | jq` (notice the s at the end), please run this again.

We can probably close this once I can confirm that there is nothing else fishy going on.

>1 quick question: is it possible to show certain workspaces even if i didn't yet put anything on them?

That's not possible. In i3 if a workspace doesn't have anything in it, it doesn't exist.

**Comment by makmm** [comment]
```
~$ i3-msg -t get_workspaces | jq
[
  {
    "num": 1,
    "name": "1",
    "visible": true,
    "focused": true,
    "rect": {
      "x": 0,
      "y": 24,
      "width": 1366,
      "height": 744
    },
    "output": "eDP",
    "urgent": false
  },
  {
    "num": 3,
    "name": "3",
    "visible": false,
    "focused": false,
    "rect": {
      "x": 0,
      "y": 24,
      "width": 1366,
      "height": 744
    },
    "output": "eDP",
    "urgent": false
  },
  {
    "num": 4,
    "name": "4",
    "visible": false,
    "focused": false,
    "rect": {
      "x": 0,
      "y": 24,
      "width": 1366,
      "height": 744
    },
    "output": "eDP",
    "urgent": false
  },
  {
    "num": 5,
    "name": "5",
    "visible": false,
    "focused": false,
    "rect": {
      "x": 0,
      "y": 24,
      "width": 1366,
      "height": 744
    },
    "output": "eDP",
    "urgent": false
  }
]
```

>That's not possible. In i3 if a workspace doesn't have anything in it, it doesn't exist.
huh. i'm pretty sure i have seen it in some rices. or maybe they just put windows in the workspaces for the rice too look good. i don't know, but i wish i could do it (and put the workspaces that don't have anything on them grayed out.)

**Comment by patrick96** [comment]
Is that the output when the workspaces are in the wrong order?

We had the same question before and I'm sure that in i3 the notion of an empty workspace doesn't exist. We also decided on not extending the i3 module to support this. (The relevant issue was #274).
Maybe you have seen rices of people using other WMs like bspwm.

**Comment by makmm** [comment]
@patrick96 nope, that's after i set the names to numbers to properly order

> Maybe you have seen rices of people using other WMs like bspwm.

oh, okay. i tried bspwm but found it really hard to use.

**Comment by patrick96** [comment]
Well then the output shouldn't show anything out of the ordinary. I think we can close this. If you want ordered non numerical workspaces, you can use names like this "2: actual name" and then set `strip-wsnumbers` to true.
