### ISSUE TITLE
Clicking on custom script module doesn't updates the values in bar

### ISSUE THREAD

**Issue by rudevdr** [jaagr/polybar#1471]
Here is the script I am using:
```bash
	function get_task {
			request=$(" <api get requests here, it works fine")
			data=$(echo $request | jq -r ".get_data")
			new_data=$data
			old_data=$(cat /tmp/get_data.txt)
			difference=$(echo "$old_data- $new_data" | bc)
			#echo $old_data"(+"$difference")="$new_data
			echo $new_data > /tmp/get_data.txt

	}

	case "$1" in
		--full)
			get_task
			echo $old_data"(+"$difference")="$new_data
			;;
		*)
			get_task
			echo $data
			;;
	esac
```
and here is its entry in polybar config:

```
	[module/script1]
	type = custom/script
	interval = 300
	label = %output%
	exec = ~/.config/polybar/script1.sh
	format-prefix = ". "
	click-left = ~/.config/polybar/script1.sh --full
	click-right = ~/.config/polybar/script1.sh 
```

On left clicking the script the value should update. But it doesn't in this case.
If I exec the module with `exec = ~/.config/polybar/script1.sh --full` then `case --full` runs but then the other one doesn't work. I am not able to wrap my head around it. Is the script designed in a bad way or there is some bug in polybar?

**Comment by patrick96** [comment]
So, on click you want the `--full` case to be displayed on the bar?

This isn't how you do that. The `click-left` command is executed when you click the module, but its output is not displayed in the bar, polybar still displays the output of the `exec` command. This is intended behavior. If you want the output to change upon clicking the bar, then you will have to do it a bit more complicated. You somehow need to tell the `exec` command that you want it to display something different. You can either do that by writing to some file that the script then reads from. Or you can do it similar to the [example with the `%pid%` token](https://github.com/jaagr/polybar/wiki/Module:-script#examples) and use a tailing script.
