### ISSUE TITLE
Pulseaudio module underline not working

### ISSUE THREAD

**Issue by 132ikl** [jaagr/polybar#1479]
## Describe the issue
When using the pulseaudio module, `format-underline` has no effect. It works fine on all other modules, however.

**Expected behavior:**
The pulseaudio module will have a underline with the color of #0c9aff.

**Actual behavior:**
The pulseaudio module has no underline under it, however the rest of the formatting works fine.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
Mini-config: https://fs.ikl.sh/config2.file
My full config: https://fs.ikl.sh/config.file

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
$ polybar main
warn: pulseaudio: using default sink alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo
error: tray: Failed to put tray above 0x0800002 in the stack (XCB_MATCH (8))
```

## Screenshots
*If applicable, add screenshots to help explain your problem.*
Full config
![](https://fs.ikl.sh/selif/sh1euwkm.png)
Mini config
![](https://fs.ikl.sh/selif/e7zyfngd.png)

## Environment:
* WM: i3wm
* Output of `polybar -vvv`: https://fs.ikl.sh/37phy6tx.txt

**Comment by patrick96** [comment]
The pulseaudio module doesn't have a `format` key, so `format-underline` doesn't exists either. You will have to set `format-volume-underline` and `format-muted-underline`

**Comment by 132ikl** [comment]
Oh, okay. Thanks!
