### ISSUE TITLE
Number of modules ignore background setting

### ISSUE THREAD

**Issue by abraxeas** [jaagr/polybar#1481]
I'm certain that this is an issue with my configuration because I'm ignorant of something or other, but I couldn't find answers anywhere. In short, my modules, in this order, are battery, date, wlan, xbacklight, pulseaudio, xkeyboard, script, and mpd. all of these are set to the same module background color, different from the bar background color, except the script module. battery, wlan, pulseaudio, and mpd ignore the module background setting in favor of the bar background setting. I can't seem to find the commonality here, it seems arbitrary which ones work and which don't.

My configuration is at https://pastebin.com/raw/z772nedU

No errors other than a "no monitor specified" warning and a "pulseaudio: using default sink" warning are output.

Screenshot: https://i.imgur.com/X8Xidf9.png

I appreciate whoever takes time out of their day to diagnose my weird configuration problem, thanks a lot.

**Comment by patrick96** [comment]
The [battery](https://github.com/jaagr/polybar/wiki/Module:-battery), [network](https://github.com/jaagr/polybar/wiki/Module:-network), [pulseaudio](https://github.com/jaagr/polybar/wiki/Module:-pulseaudio), and [mpd](https://github.com/jaagr/polybar/wiki/Module:-mpd) modules all don't have the `format` key, so `format-background` will have no effect there. They all define multiple `format-*` keys and you will need to set the background for each of these formats, see the [formatting wiki page](https://github.com/jaagr/polybar/wiki/Formatting) and #1479
