### ISSUE TITLE
Thermal zone path rather than id

### ISSUE THREAD

**Issue by Alkeryn** [jaagr/polybar#1483]
On one of my pc, my thermal zone id change at every reboot for some reason
would be fixable if i could tell polybar to rather use a symlink to the thermal zone that i made with another script

Rather than it failing 2 out of 3 times
would be happy with any other solution ^

**Comment by patrick96** [comment]
Since it only changes at reboot and you seem to have a way to actually figure out the thermal zone id would it work to export the actual id as an environment variable right before you start polybar and then set the `thermal-zone` key to something like this?
```dosini
thermal-zone = ${env:THERMAL_ZONE}
```

**Comment by patrick96** [comment]
Polybar also supports loading contents of a file into a key and can also access values in your `.Xresources` file.

See [Referencing Values](https://github.com/jaagr/polybar/wiki/Configuration#referencing-values)
