### ISSUE TITLE
Battery capacity 0 label color

### ISSUE THREAD

**Issue by klarinetkid** [jaagr/polybar#1486]
I can make the battery icon red with 

```
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

ramp-capacity-0-foreground = #ff0000
```
This will make the icon red, but "10%" label is still white. Is there any way to change the label colour when it is using ramp-capacity-0, so that the icon+percentage are all red.

**Comment by patrick96** [comment]
Already answered on [stackexchange](https://unix.stackexchange.com/questions/477662/linux-polybar-battery-capacity-0-label-color/477738#477738).

Please don't post the same questions in multiple places at once.
