### ISSUE TITLE
Environment variable is not read by polybar

### ISSUE THREAD

**Issue by carbonaroece** [jaagr/polybar#1487]
I defined a environment variable `export POLYBAR_COLOR=#FF88FF`.
I set `icon_color = ${colors:POLYBAR_COLOR}` in polybar config.
The problem is that the module doesn't even charge the module that use the `icon_color`.

I've read that polybar does understand env variables but I can't seem to use them. 
Do you know why ?

**Comment by TonCherAmi** [comment]
If you mean to access an environment variable the syntax for that is `${env:ENVIRONMENT_VARIABLE}`, meaning you would need to change that line to:
```ini
icon_color = ${env:POLYBAR_COLOR}
```

**Comment by carbonaroece** [comment]
That is what I did. Sorry I didn't mention it

**Comment by patrick96** [comment]
Can you please post your entire config as well as the polybar output (with the `-l info` argument) when you run the bar.

**Comment by carbonaroece** [comment]
The thing is it works when I use `polybar name_of_bar`. It doesn't work at startup when i3 is launching the bar

**Comment by patrick96** [comment]
That's probably because the env variable doesn't exist in the context where you start polybar in i3. You best export the env variable a launch script which you call from i3 and which also starts polybar

**Comment by carbonaroece** [comment]
I works now ! Thank you very much
