### ISSUE TITLE
How do you change workspace names in i3?

### ISSUE THREAD

**Issue by catzybluphish** [jaagr/polybar#1488]
I've read the i3 page of the wiki but still cannot figure out how to do it. Here's my workspace section of i3 config:

```
set $ws1 "1;一"
set $ws2 "2;二"
set $ws3 "3;三"
set $ws4 "4;四"
set $ws5 "5;五"
set $ws6 "6;六"
set $ws7 "7;七"
set $ws8 "8;八"
set $ws9 "9;九"
set $ws10 "10;十"

bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10

bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10
```

And here's my i3 module for polybar config:

```
[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}
label-focused = %index%
label-focused-background = ${module/bspwm.label-focused-background}
label-focused-foreground = #ffffff
label-focused-underline = ${module/bspwm.label-focused-underline}
label-focused-padding = ${module/bspwm.label-focused-padding}
label-unfocused = %index%
label-unfocused-foreground = #a9a9a9
label-unfocused-padding = ${module/bspwm.label-occupied-padding}
label-visible = %index%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}
label-urgent = %index%
label-urgent-background = #ff0000
label-urgent-foreground = #ffffff
label-urgent-padding = ${module/bspwm.label-urgent-padding}

ws-icon-0 = 1;一
ws-icon-1 = 2;二
ws-icon-2 = 3;三
ws-icon-3 = 4;四
ws-icon-4 = 5;五
ws-icon-5 = 6;六
ws-icon-6 = 7;七
ws-icon-7 = 8;八
ws-icon-8 = 9;九
ws-icon-9 = 10;十
```

I'm probably missing a simple step but what the hell?
Cheers.

**Comment by patrick96** [comment]
What exactly do you want to change your workspace names to? In your i3 config the workspaces are already named `1;一` and so on.

**Comment by catzybluphish** [comment]
I'm not sure how it works but I'm trying to have the workspace names as
numbers in Chinese characters instead of 1, 2, 3, etc. It's possible with
the other bars that integrate with the i3wm config like i3status but I'm
confused about how the "labels and icons" are meant to be the same as
stated in the wiki page. I thought the 1 designates the the workspace and
the 一 after is displayed.

**Comment by patrick96** [comment]
What you probably want here is to set the workspaces names in your i3 config to `1:一` and so on (the semicolon `;` was replaced with a colon `:`) and in your polybar config set `strip-wsnumbers = true` and remove all `ws-icon-X` keys.

In i3 workspace names with a colon have a special meaning, the number before the colon is the workspace number and everything after it is the workspace name.

Also in your labels in the i3 module, you will have to use the `%name%` token and not the `%index%` token.

**Comment by catzybluphish** [comment]
Cheers dude! Just added the font and everything works fine now.

**Comment by patrick96** [comment]
@autoteelar https://i3wm.org/docs/userguide.html#_strip_workspace_numbers_name
