### ISSUE TITLE
Build errors on Fedora 28/29

### ISSUE THREAD

**Issue by jfchevrette** [jaagr/polybar#1492]
## Build Process
Fedora 29 released today and it looks like polybar 3.2.1 refuses to build on F29

## Build Log
RPM spec here: https://github.com/jfchevrette/copr/blob/master/polybar/polybar.spec
Build log here: https://copr-be.cloud.fedoraproject.org/results/jfchevrette/misc/fedora-29-x86_64/00816986-polybar/builder-live.log

## Environment:
* Distro (with Version): Fedora 29

**Comment by patrick96** [comment]
So this isn't related to fedora 29 in particular.

Were you able to build polybar on fedora on older versions?

**Comment by jfchevrette** [comment]
@patrick96 I used to be able to build 3.1 on Fedora 28. Bumped to 3.2.1 today and it fails with the same errors on both 28 and 29

**Comment by patrick96** [comment]
Alright.

Can you try to compile 3.1 on your updated fedora 29 machine

Also try to compile 3.2.1 with `gcc` and `g++` instead of clang.

**Comment by jfchevrette** [comment]
Looks like 3.2.1 builds fine with gcc/g++ on Fedora 28 & 29 as you can see in the build log here: https://copr-be.cloud.fedoraproject.org/results/jfchevrette/misc/fedora-29-x86_64/00817038-polybar/builder-live.log

3.2.1 fails with clang on both fedora 28 and 29. See this f29 build log (f28 is basically the same): https://copr-be.cloud.fedoraproject.org/results/jfchevrette/misc/fedora-29-x86_64/00817055-polybar/builder-live.log

3.1.0 with clang/clang++ used to work and now produces these errors: https://copr-be.cloud.fedoraproject.org/results/jfchevrette/misc/fedora-29-x86_64/00817049-polybar/builder-live.log
Note this is a python error so it may be unrelated to polybar. I'm not too concerned about 3.1.0 personally.

In the end I'm fine with bulding 3.2.1 with gcc/c++ and I'm happy to help troubleshoot this further to see why 3.2.1 with clang doesn't work on fedora 28 & f29.

**Comment by patrick96** [comment]
I was able to reproduce this on a VM:

Compilation works fine with the latest version and `gcc`.

A bisect showed that in 3afc341c7bf19beead996a66edf06ec8b89135f7 the clang build on fedora was broken. Will have to do some more investigating

**Comment by patrick96** [comment]
The error in 3.1.0 is caused by the `xpp` submodule being outdated. Otherwise the build would work except for another error in `src/x11/extensions/xkb.cpp` which is easy to fix (the compiler tells you how).

If you are familiar with C++, you're welcome to checkout commit 3afc341c7bf19beead996a66edf06ec8b89135f7 and figure out why it broke everything.

**Comment by patrick96** [comment]
Fixed it! Fix will be up shortly

**Comment by jfchevrette** [comment]
@patrick96 amazing! Thanks!

To be honest I don't really know the benefits from building with clang vs gcc/g++. As an end-user should I care?

**Comment by patrick96** [comment]
clang has lots of tooling, that's why many advanced linters and code completion engines are built with it. But as an end user it really doesn't matter.
