### ISSUE TITLE
Can’t uninstall polybar

### ISSUE THREAD

**Issue by Antonio05200** [jaagr/polybar#1495]
Hi, 
I have an issue with polybar. I installed it on my gentoo with the script build.sh now I would like to uninstall it, but I can’t. What should I do?
Edit: I noticed that if I run make uninstall it doesn't work because there are no rules. I ran it in /polybar directory

**Comment by Antonio05200** [comment]
> #
# Polybar development tasks
#
BUILDDIR  ?= build
GENERATOR ?= $(shell for c in ninja make; do command -vp $$c; done | xargs basename | sed "s/ninja/Ninja/;s/make/Unix Makefiles/")

all: configure build link

help:
        @echo "Available targets:"
        @awk -F':' '/^\w*:/ {print "  "$$1;}' Makefile

configure:
        @echo "\033[32;1m**\033[0m Configuring..."
        @mkdir -p $(BUILDDIR)
        @cd $(BUILDDIR) && cmake -G "$(GENERATOR)" ..

build:
        @echo "\033[32;1m**\033[0m Building..."
        @cmake --build $(BUILDDIR)

install:
        @echo "\033[32;1m**\033[0m Installing..."
        @cmake --build $(BUILDDIR) --target install

link:
        @echo "\033[32;1m**\033[0m Linking executable..."
        @if [ -x $(BUILDDIR)/bin/polybar ]; then ln -sfv $(BUILDDIR)/bin/polybar; fi
        @if [ -x $(BUILDDIR)/bin/polybar-msg ]; then ln -sfv $(BUILDDIR)/bin/polybar-msg; fi

clean:
        @echo "\033[32;1m**\033[0m Cleaning up..."
        @if [ -d $(BUILDDIR) ]; then rm -rf $(BUILDDIR); fi
        @if [ -L polybar ]; then rm -v polybar; fi
        @if [ -L polybar-msg ]; then rm -v polybar-msg; fi

.PHONY: configure build link clean help

# vim:ts=2 sw=2 noet nolist

**Comment by patrick96** [comment]
Running `make uninstall` inside the `build` directory should work

**Comment by Antonio05200** [comment]
Hi, in polybar folder where I ran./build.sh there’s an empty folder named build. Obv it doesn’t work

**Comment by patrick96** [comment]
Did you do anything to the folder you ran build.sh in, after you compiled polybar? The build folder should contain all build data after you compiled polybar.

**Comment by Antonio05200** [comment]
I ran only build.sh. I’m going to run it again and I’ll check

**Comment by Antonio05200** [comment]
It worked. Thank you so much
