### ISSUE TITLE
Building polybar for arch linux, xcbgen autodetection fails

### ISSUE THREAD

**Issue by giulioprovasi** [jaagr/polybar#1496]
I have tried to install polybar with the following: `yay -S polybar{-git}` and it failed all the time with this error:

```
CMake Error at lib/xpp/CMakeLists.txt:55 (message):
  Missing required python module: xcbgen
```

So I pulled the sources and tried to see what's was going on, because a simple check showed that xcbgen is available for python 3.7 (I have a clean arch install):
 ```
$ ls /usr/lib/python3.7/site-packages/ |grep xcb
drwxr-xr-x 3 root root 4,0K  1 nov.  09:14 xcbgen/
```

So when looking at the cmake file I added a debug line `message(STATUS "status: " ${_xcbgen_status)` and it showed this:
```
-- Searching for xcbgen with python2
-- status: 1
-- Searching for xcbgen with python2.7
-- status: 1
-- Searching for xcbgen with python3
-- status: Child aborted
-- Searching for xcbgen with python
-- status: Child aborted
```

And when ran manually in a terminal:

```
$ python3 -c "import re,xcbgen;print(re.compile('/xcbgen/__init__.py.*').sub('',xcbgen.__file__))" && echo $?
/usr/lib/python3.7/site-packages
0
```

So I replaced the lib detection with this in cmake.txt `set(PYTHON_XCBGEN "/usr/lib/python3.7/site-packages" CACHE STRING "Location of python module: xcbgen ")` and build was successful.

My question is why detection fails ? Ideally I would like to being able to install polybar with `yay`

**Comment by patrick96** [comment]
Does this only happen when you try to install with yay? Or does it also happen when you compile from source manually?

It's very strange that the command `python3 -c "import re,xcbgen;print(re.compile('/xcbgen/__init__.py.*').sub('',xcbgen.__file__))"` fails in cmake but succeeds in the shell.

Could you go into `lib/xpp/CMakeLists.txt` and remove the `ERROR_QUIET` from the `execute_process` call. This should print out the stderr the failing command prints out.

**Comment by patrick96** [comment]
@giulioprovasi Are you still getting this error?

**Comment by mcginty** [comment]
If it helps, I had this problem and it was because I was running a venv (virtualfish) that threw its own python3 in in the front of PATH, and it wasn't looking in the system `site-packages`.

**Comment by patrick96** [comment]
Yeah, that's probably the issue here as well (or something similar)
