### ISSUE TITLE
How to change desktop names in bspwm?

### ISSUE THREAD

**Issue by catzybluphish** [jaagr/polybar#1502]
Back at it again but in bspwm. Here's my module:

```dosini
[module/bspwm]
type = internal/bspwm

label-focused = %name%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2

label-occupied = %name%
label-occupied-padding = 2

label-urgent = %name%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %name%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 2

ws-icon-0 = 1;一
ws-icon-1 = 2;二
ws-icon-2 = 3;三
ws-icon-3 = 4;四
ws-icon-4 = 5;五
ws-icon-5 = 6;六
ws-icon-6 = 7;七
ws-icon-7 = 8;八
ws-icon-8 = 9;九
ws-icon-9 = 10;十
```

And here's my bspwmrc:
`bspc monitor -d 1:一 2:二 3:三 4:四 5:五 6:六 7:七 8:八 9:九 10:十`

I've changed in my bspwmrc to have semicolons but then the desktops wouldn't be recognized. Thanks in advance.

**Comment by patrick96** [comment]
bspwm doesn't have the same feature as i3 where a workspace prefixed with `X:` where `X` is a number is treated as workspace X. Either set your bspwm workspace names in bspwmrc to only the numbers and leave the polybar config or remove the `wc-icon-*` from the config and set the workspace names in bspwmrc to the chinese characters.
