### ISSUE TITLE
the error when build tests dirctory

### ISSUE THREAD

**Issue by lamar-studio** [jaagr/polybar#1503]
## Build Process
*Describe how you build polybar, list the exact commands you are using:*
cd polybar/tests
mkdir build
cd build
cmake ..
make

**If you build polybar directly from this repository:**

* Output of `git describe --tags`:

**If you use some other way (like the AUR):**

*List exactly where you are building from and which version you are building.*

## Build Log
*Post everything that is output to the terminal while building polybar below. This HAS to include the output of the `cmake` and `make` commands, if you used them.*
```
LaMar# make
[  5%] Built target gtest
[ 11%] Built target gmock
[ 17%] Built target gmock_main
[ 20%] Building CXX object CMakeFiles/unit_test.utils_math.dir/unit_tests/utils/math.o
In file included from /usr/include/c++/5/tuple:35:0,
                 from /home/lamar/linzr/polybar/tests/build/googletest-src/googletest/include/gtest/internal/gtest-port.h:275,
                 from /home/lamar/linzr/polybar/tests/build/googletest-src/googletest/include/gtest/internal/gtest-internal.h:40,
                 from /home/lamar/linzr/polybar/tests/build/googletest-src/googletest/include/gtest/gtest.h:60,
                 from /home/lamar/linzr/polybar/tests/common/test.hpp:13,
                 from /home/lamar/linzr/polybar/tests/unit_tests/utils/math.cpp:1:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
/home/lamar/linzr/polybar/tests/unit_tests/utils/math.cpp:2:26: fatal error: utils/math.hpp: No such file or directory
compilation terminated.
CMakeFiles/unit_test.utils_math.dir/build.make:62: recipe for target 'CMakeFiles/unit_test.utils_math.dir/unit_tests/utils/math.o' failed
make[2]: *** [CMakeFiles/unit_test.utils_math.dir/unit_tests/utils/math.o] Error 1
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/unit_test.utils_math.dir/all' failed
make[1]: *** [CMakeFiles/unit_test.utils_math.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

## Environment:
* Distro (with Version):

## Additional context
*Add any other context that you think is necessary about the problem here.*

**Comment by patrick96** [comment]
That's not how we compile the tests.

You compile the tests in the `polybar/build` directory, just as you would when compiling polybar regularly. But you add the `-DBUILD_TESTS=ON` argument to `cmake`. `make` should then build polybar and its tests. If you only want to build the tests run `make all_unit_tests`.

We should start to write documentation for that though.
