### ISSUE TITLE
Polybar shows thin gap underneath it

### ISSUE THREAD

**Issue by catzybluphish** [jaagr/polybar#1504]
## Describe the issue
A thin gap appears underneath the bar.

**Expected behavior:**
For the windows and bar to be in contact. There shouldn't be any space.

## To Reproduce
Start the launch script from my bspwmrc.

## Polybar Log
![2018-11-09-200401_960x527_scrot](https://user-images.githubusercontent.com/40843060/48256226-ae76a200-e45a-11e8-9078-c5dc901aa09a.png)

## Screenshots
![scrot](https://user-images.githubusercontent.com/40843060/48256265-cfd78e00-e45a-11e8-98a0-2318f776f677.png)
(you can see a thin blue bar underneath polybar which is my blue wallpaper. I've purposefully made poly black so it can be seen better)

## Environment:
* WM: bspwm
* Output of `polybar -vvv`:
![2018-11-09-200606_960x527_scrot](https://user-images.githubusercontent.com/40843060/48256310-ef6eb680-e45a-11e8-9142-3eaeb406fab2.png)

## Additional context
This occurs whenever I start polybar. If I start without it, the windows (e.g. Spotify) won't show a gap at the top and instead uses all of the screen space as it should.

### polybar config
[colors]
background = #ffa9a9a9
background-alt = #00000000
foreground = #ffffff
foreground-alt = #ffffff
primary = #00000000
secondary = #e60053
alert = #ff0000

[bar/catsik]
width = 100%
height = 20
radius = 0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 0
line-color = #f00

border-size = 0

padding-left = 1
padding-right = 1

module-margin-left = 1
module-margin-right = 2

font-0 = SF Pro Display:size=10;2
font-1 = Noto Sans CJK JP:size=10;2

modules-left = bspwm
modules-center = spotify
modules-right = pulseaudio wlan date time

tray-position = right
tray-padding = 0

cursor-click = pointer

[module/bspwm]
type = internal/bspwm

label-focused = %name%
label-focused-padding = 2
label-focused-foreground = #ffffff

label-occupied = %name%
label-occupied-padding = 2
label-occupied-foreground = #44ffffff

label-urgent = %name%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty =

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}
label-focused = %name%
label-focused-background = ${module/bspwm.label-focused-background}
label-focused-foreground = #ffffff
label-focused-underline = ${module/bspwm.label-focused-underline}
label-focused-padding = ${module/bspwm.label-focused-padding}

label-unfocused = %name%
label-unfocused-foreground = #a9a9a9
label-unfocused-padding = ${module/bspwm.label-occupied-padding}

label-visible = %name%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}
label-urgent = %name%
label-urgent-background = ${module/bspwm.label-focused-background}
label-urgent-foreground = #ff0000
label-urgent-padding = ${module/bspwm.label-urgent-padding}
strip-wsnumbers = true

[module/xbacklight]
type = internal/xbacklight

[module/wlan]
type = internal/network
interface = wlp2s0
label-connected = %essid% %signal%%
format-disconnected = no connection

[module/date]
type = internal/date
date = %d/%m/%Y
label = %date%

[module/time]
type = internal/date
time = %H:%M
label = %time%

[module/pulseaudio]
type = internal/pulseaudio
label-volume = vol %percentage%%
label-muted = muted

[module/spotify]
type = custom/script
exec = python ~/.config/polybar/spotify_status.py

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
;compositing-border = over

[global/wm]
margin-top = 5
margin-bottom = 5

### bspwmrc
#! /bin/sh

xrdb ~/.Xresources &
~/.fehbg &
firefox &
~/.config/polybar/launch &
compton &
sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width         0
bspc config window_gap           0
bspc config top_padding 	 0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle true

**Comment by catzybluphish** [comment]
Solved. This should be my last post so I won't be harassing you anymore. Cheers.

**Comment by philippludwig** [comment]
I have this issue with polybar 3.2.1 and i3; setting margins to 0 does not solve this. Anything else to try? 

The gaps are not only below the bar, but on every side.

**Comment by patrick96** [comment]
@philippludwig Maybe you have transparent borders or have an offset set in your bar section. If that doesn't help, try asking on [reddit](https://www.reddit.com/r/polybar)

**Comment by mmastrapasqua** [comment]
> @philippludwig Maybe you have transparent borders or have an offset set in your bar section. If that doesn't help, try asking on [reddit](https://www.reddit.com/r/polybar)

Worked for me. I would like to add this (*bar placed on top):
**
[i3]
gaps = 6 # example

border-left = ${i3.gaps}
border-right = ${i3.gaps}
border-top = ${i3.gaps}
border-bottom = 0
**

**Comment by thisisnotatrash** [comment]
Om my side it was

```ini
# ~/.config/polybar/config.ini

[bar/top] # top is the name of the bar
radius = 0

border-size = 0pt
```
