### ISSUE TITLE
cmus + zscroll isn't working

### ISSUE THREAD

**Issue by BillyTheMotherBoard** [jaagr/polybar#1506]
**## Describe the issue
*A clear and concise description of what the bug is.***
Hello,
first of all, thank you for Polybar, it's an amazing tool.
I made a custom script to display my cmus title and artist in a dedicated bar, pretty simple until here. I noticed that some of my songs have a title lenght that don't fits entirely in the bar, so I decided to make it scroll, a bit like in iPhones with iTunes you see what I mean?

I decided to use this program: https://github.com/noctuid/zscroll
This is my script for cmus:
```
#!/bin/bash

cmus=$(cmus-remote -Q | grep status)
case "$cmus" in
"status stop"*)
    echo "No music!"
    ;;
"status paused"*)
    echo "Song paused"
    ;;
'status playing'*)
    title=$(cmus-remote -Q | grep tag\ title\ )
    print="${title:10}"

    artist=$(cmus-remote -Q | grep tag\ artist\ )
    print+=" - ${artist:11}"

    echo "$print"
    ;;
"")
    echo "No music!"
    ;;
esac
```

and this is the actual wrapper to pipe it through zscroll to make it scrolling in Polybar:

```
> #!/bin/sh
> 
> cmustatus | zscroll -l 20 -d 0.1
> 

and my cmus module in polybar
 
[module/cmus]
type         = custom/script
 
exec         = cmuswrapper
exec-if      = pgrep cmus > /dev/null
 
interval     = 0.01
 
click-left   = cmus-remote --prev
click-middle = cmus-remote --pause
click-right  = cmus-remote --next
scroll-up    = cmus-remote --volume +5%
scroll-down  = cmus-remote --volume -5%
 
format-foreground = ${colors.foreground}
format-background = ${colors.background}
 
format-prefix	  = ""
format-prefix-foreground = ${colors.background}
format-prefix-background = ${colors.green}
format-prefix-padding    = 2
 
format-padding    = 0
label-padding = 2
```

**Expected behavior:**

*A clear and concise description of what you expected to happen.*

I expected to get the title and author scroll, from right to left, just like in the gif of the README of zscroll (see link above)

**Actual behavior:**
https://imgur.com/a/VFAKhtx 
see the empty bar at bottom right? that is the one that should contain the scrolling cmus status

*What actually happens*

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[colors]
foreground                    = #d5c4a1
background                    = #1d2021
modb                          = #1d2021
modb1                         = #1d2021
modb2                         = #1d2021

red                           = #fb4934
orange                        = #fe8019
yellow                        = #fabd2f
green                         = #b8bb26
cyan                          = #8ec07c
blue                          = #83a598
magenta                       = #d3869b
white                         = #d65d0e


[bar/musicbar]
bottom                        = true
width                         = 12%
height                        = 40
offset-x                      = 76.5%
offset-y                      = 1%

monitor						  = HDMI-0

background                    = ${colors.background}
foreground                    = ${colors.foreground}

font-0                        = Tewi:pixelsize=10;1
font-1                        = unifont:fontformat=truetype:size=8:antialias=false;0
font-2                        = siji:pixelsize=10;1

modules-left                  = cmus
modules-center                =
modules-right                 =


[module/cmus]
type         = custom/script

exec         = cmuswrapper
exec-if      = pgrep cmus > /dev/null

interval     = 0.01

click-left   = cmus-remote --prev
click-middle = cmus-remote --pause
click-right  = cmus-remote --next
scroll-up    = cmus-remote --volume +5%
scroll-down  = cmus-remote --volume -5%

format-foreground = ${colors.foreground}
format-background = ${colors.background}

format-prefix	  = ""
format-prefix-foreground = ${colors.background}
format-prefix-background = ${colors.green}
format-prefix-padding    = 2

format-padding    = 0
label-padding = 2

[settings]
screenchange-reload           = true
;compositing-background       = xor
;compositing-background       = screen
;compositing-foreground       = source
;compositing-border           = over

[global/wm]
margin-top                    = 0
margin-bottom                 = 0
override-redirect             = true
enable-ipc					  = true
```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*

```
#!/usr/bin/env bash

killall -q polybar

while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

polybar datebar   -r &
polybar wlanbar   -r &
polybar sysbar    -r &
polybar musicbar  -r &

```
I actually use this script to run polybar and 1 time on 2, it doesnt' output anything and bars are drawn correctly (the zscroll doesn't work but the bars are displayed) and the other 1 time on 2, only the empty bar where cmus and zscroll should play together is drawn and I get these messages in terminal:

```
warn: Termination signal received, shutting down...
warn: Termination signal received, shutting down...
warn: Termination signal received, shutting down...
warn: Termination signal received, shutting down...

```
## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM: bspwm
* Output of `polybar -vvv`:

```
polybar 3.2.1
 
 Features: +alsa +curl -i3 -mpd +network +pulseaudio +xkeyboard
 
 X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm xcursor
 
 Build type: RelWithDebInfo
 Compiler: /usr/bin/c++
 Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
 Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

## Additional context
*Add any other context that you think is necessary about the problem here.*

**Comment by patrick96** [comment]
The problem here is that `zscroll` doesn't terminate. And the script module (without `tail = true`) will wait for the command to terminate before it prints its output, that's probably why you see an empty bar.

Adding `tail = true` to the script module will fix that issue. But now polybar will just let `cmuswrapper` run forever and the output of `cmustatus` will never change (since it's only called when polybar starts). Fixing that is more involved. You need to somehow determine when cmus' status changes, and then restart the zscroll process with a new input.

In #353 the same thing was done but with `mpc`. It relied on `mpc idle` being able to block until an mpd event occured, if cmus can do the same, then the script could be easily adapted. If not, implementing this will probably be quite difficult.

**Comment by BillyTheMotherBoard** [comment]
Hello 

> The problem here is that `zscroll` doesn't terminate. And the script module (without `tail = true`) will wait for the command to terminate before it prints its output, that's probably why you see an empty bar.
> 
> Adding `tail = true` to the script module will fix that issue. But now polybar will just let `cmuswrapper` run forever and the output of `cmustatus` will never change (since it's only called when polybar starts). Fixing that is more involved. You need to somehow determine when cmus' status changes, and then restart the zscroll process with a new input.
> 
> In #353 the same thing was done but with `mpc`. It relied on `mpc idle` being able to block until an mpd event occured, if cmus can do the same, then the script could be easily adapted. If not, implementing this will probably be quite difficult.

Hello, thank you for your detailed answer, it helped me a lot, now zscroll seems to be working but I have the problem that once the title has finished to scroll from right to left, it redraws the entire module, so the prefix is also redrawn which is a thing I would avoid because aesthetically it's not fitting in my needs, I'd like the prefix to be totally detached of the zscroll object, I don't know if I'm expressing myself well but here we go ^^

**Comment by patrick96** [comment]
I don't think I follow. What prefix is redrawn? `format-prefix`? If so how is it redrawn that is not aesthetically pleasing?

**Comment by BillyTheMotherBoard** [comment]
the prefix icon disappear for a second then is redrawn when the zscroll object has finished scrolling and is ready to scroll another time, I don't know if it's clear but... Tell me a recording software if you know any and I'll record to show you.

Anyway, for the updating feature, I don't think it's natively available...

I actually have these two scripts that work together:

cmustatus:
```
#!/bin/bash

cmus=$(cmus-remote -Q | grep status)
case "$cmus" in
"status stop"*)
    echo "No music!"
    ;;
"status paused"*)
    echo "Song paused"
    ;;
'status playing'*)
    title=$(cmus-remote -Q | grep tag\ title\ )
    print="${title:10}"

    artist=$(cmus-remote -Q | grep tag\ artist\ )
    print+=" - ${artist:11}"

    echo "$print"
    ;;
"")
    echo "No music!"
    ;;
esac
```

and this other one; cmuswrapper which is actually ran by polybar:
```

#!/bin/sh

cmustatus | zscroll -l 20 -d 0.25

```
Do you think it's possible to design and implement a homemade replacement to catch when the title is being updated? I thought of doing that with a Python scripts that keep the last title read from cmustatus and then read the actual title every X seconds and if it's diferent we do something, you got me?

**Comment by patrick96** [comment]
Seems you can make cmus call some script on every status change: https://github.com/cmus/cmus/blob/master/Doc/cmus.txt#L1120

You could probably use this to notify your script that it needs to update its input to scroll.

> I also found this reddit post which may help us: https://www.reddit.com/r/Polybar/comments/8tp3t2/help_with_spotifyzscrollplayerctl_script/

Yeah they had the exact same issue, just for playerctl. Also, I was the main commenter on this thread ;)
They never reported back, how they were able to fix this. The problem is not trivial

**Comment by BillyTheMotherBoard** [comment]
> Seems you can make cmus call some script on every status change: https://github.com/cmus/cmus/blob/master/Doc/cmus.txt#L1120
> 
> You could probably use this to notify your script that it needs to update its input to scroll.
> 
> > I also found this reddit post which may help us: https://www.reddit.com/r/Polybar/comments/8tp3t2/help_with_spotifyzscrollplayerctl_script/
> 
> Yeah they had the exact same issue, just for playerctl. Also, I was the main commenter on this thread ;)
> They never reported back, how they were able to fix this. The problem is not trivial

Hello man, sorry for the late reply I was studying for exams;

I see thank you for your advice but I don't really see how to combine this cmus function and my bash cmus script...

I'm a bit lost at the moment, I checked the example in /usr/share/doc/cmus/examples but it didn't get me anywhere

**Comment by patrick96** [comment]
The solution will likely be a bit more involved. You could use `status_display_program` to run a script that can signal your running bash cmus script that an update happened. That signaling can either be done with unix signals or fifos (or lots of other ways, but these two are probably the easiest).

`[command]` is the name of your script that cmus will call whenever cmus' status changes
The script at `/usr/share/doc/cmus/examples/cmus-status-display` is an example script that you can pass to `status_display_program`. In the comments at the top, it tells you in what kind of argument cmus passes to it.

If you are not that familiar with shell scripting, all this might be quite challenging.

**Comment by BillyTheMotherBoard** [comment]
Well, I'm not familiar with bash scripting ^^
This being said I think I can learn to deal with it :)

So we would need a script executed by the cmus-display-program that notifies my cmus polybar script through a linux signal, does that mean by polybar script has to run as a daemon in the background to be ready to get the signal?

The default example in ```/usr/share/doc/cmus/examples/cmus-status-display``` is bloated with other flags I don't need like album duration of the song etc so we should modify it to only send the title and author to the script, is that possible with linux signals or do I need to echo this data to a file and notify the polybar script that something new has been added to the file and let it read and format everything?

I also tried passing the example script to cmus using:
`set status_display_program=cmus-status-display /usr/share/doc/cmus/examples/cmus-status-display`
and this way:
`set status_display_program=cmus-status-display sh /usr/share/doc/cmus/examples/cmus-status-display`

none of these worked when I changed the music in cmus, I know this because this example script echoes the harvested data to a file so it means when I swipe music it should create the file and write to it but for a reason I don't know at the moment it doesn't act like expected.

It's challenging but this issue will be a goldmine for other people encountering something similar ;)

**Comment by BillyTheMotherBoard** [comment]
Well, I'm not familiar with bash scripting ^^
This being said I think I can learn to deal with it :)

So we would need a script executed by the cmus-display-program that notifies my cmus polybar script through a linux signal, does that mean by polybar script has to run as a daemon in the background to be ready to get the signal?

The default example in ```/usr/share/doc/cmus/examples/cmus-status-display``` is bloated with other flags I don't need like album duration of the song etc so we should modify it to only send the title and author to the script, is that possible with linux signals or do I need to echo this data to a file and notify the polybar script that something new has been added to the file and let it read and format everything?

I also tried passing the example script to cmus using:
`set status_display_program=cmus-status-display /usr/share/doc/cmus/examples/cmus-status-display`
and this way:
`set status_display_program=cmus-status-display sh /usr/share/doc/cmus/examples/cmus-status-display`

none of these worked when I changed the music in cmus, I know this because this example script echoes the harvested data to a file so it means when I swipe music it should create the file and write to it but for a reason I don't know at the moment it doesn't act like expected.

It's challenging but this issue will be a goldmine for other people encountering something similar ;)

**Comment by patrick96** [comment]
> does that mean by polybar script has to run as a daemon in the background to be ready to get the signal?

Not quite. When you have a script that never terminates, you can use `tail = true` in the config to get polybar to continuously update the module with the scripts output. This is similar to a daemon but you don't start it separately, polybar starts it for you and stays attached to it.

> modify it to only send the title and author to the script

I would have suggested to only use the `cmus-status-display` script to signal your polybar script that there were changes and your polybar script will update its output by calling `cmus-remote` again.

I don't know how those cmus settings work, I don't use it, so you're on your own here.

When you have a working script for this, you could go over to [`x70b1/polybar-scripts`](https://github.com/x70b1/polybar-scripts) and propose adding it to the repo.
