### ISSUE TITLE
Workspace Icons on opposite monitors

### ISSUE THREAD

**Issue by Try431** [jaagr/polybar#1512]
## Describe the issue
When I run polybar on my laptop monitor and an external HDMI monitor, the workspace icons are on the wrong monitor.

**Expected behavior:**

I have my Chrome and Terminal workspace open on my laptop, and my Music workspace open on my external monitor. I'm currently looking at my browser. I expect that the laptop monitor shows my Chrome workspace as focused and Terminal workspace un-focused *on my laptop screen*, and the Music workspace icon *on my external monitor screen*.

**Actual behavior:**

The focusing works fine (i.e., the Chrome workspace is focused when I'm looking at my browser), but the Chrome and Terminal workspace icons are on my external monitor, and the Music workspace icon is on my laptop monitor. They're flipped.

## To Reproduce
launch.sh
```
#!/usr/bin/env sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload primary &
  done
else
  polybar --reload primary &
fi

echo "Bars launched..."
```
config (only relevant parts included)
```
[bar/primary]
width = 100%
height = 41
top = true

border-top-size = 1  # creating top border space
offset-y = -3   # aligning tray icons with rest of bar
monitor = ${env:MONITOR:}

background = #000f0f0f # This is the hexcode for transparency (also used in powermenu)
foreground = #382d39


fixed-center = false

font-0 = FontAwesome:pixelsize=10;0
font-1 = PragmataPro Nerd Font:pixelsize=10;0
font-2 = "Font Awesome 5 Free:style=Regular:pixelsize=10;1"
font-3 = "Font Awesome 5 Free:style=Solid:pixelsize=10;1"
font-4 = "Font Awesome 5 Brands:pixelsize=10;1"

modules-left = i3
modules-center = date
modules-right = wired-network wireless-network cpu memory filesystem filesystem2 temperature pulseaudio backlight battery powermenu

tray-position = right
tray-background = #000f0f0f
tray-foreground= #000f0f0f

scroll-up = i3wm-wsnext
scroll-down = i3wm-wsprev

[module/i3]
type = internal/i3

pin-workspaces = true
strip-wsnumbers = true
index-sort = true
enable-scroll = false

format = <label-state> 
format-padding-right = 2

label-unfocused-foreground = #382d39
label-unfocused-padding = 1

# This is light-blue/cyan color below
label-focused-foreground = #00ffff 
label-focused-padding = 1

label-urgent-foreground = #e4b226
label-urgent-padding = 1
```

## Screenshots
It's a bit hard to see unless you click on the image and zoom to full-size, but you'll see that the Chrome and Terminal icons are on the top monitor (my external HDMI) and the Music icon is on the bottom monitor (my laptop). It should be the other way around.

![2 _127](https://user-images.githubusercontent.com/25510761/48640914-00548600-e98d-11e8-8bb5-8c0e9a2a4a86.png)

## Environment:
* WM: i3wm
* Output of `polybar -vvv`: 
```
polybar 3.1.0-129-g930be72

Features: +alsa +curl +i3 +mpd +network +pulseaudio

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags:  -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: 
```

## Additional context
Running Ubuntu 18.04 on an MSI GE63 Stealth 8RE, with an NVIDIA GTX 1060

**Comment by patrick96** [comment]
So all icons are flipped? If you have a workspace associated with your external monitor, it will display on the bar on the laptop monitor and vice-versa?

I will try to reproduce this once I get to my dual monitor system. 

In the meantime, can you add the `%output%` token to all the different labels in the i3 modules (`label-(focused|unfocused|visible|urgent)`), reproduce the issue again and post a screenshot here. I suspect i3 is moving the bars around.

**Comment by Try431** [comment]
![image](https://user-images.githubusercontent.com/25510761/48665419-b5a53d80-ea62-11e8-8fd8-6b9fb1e104b7.png)

**Comment by patrick96** [comment]
Ha, I knew there was a similar issue around: #980. Turns out that was you too :smile: 

The core issue is the same: i3 seems to reposition your bars, making them appear on the wrong monitor. i3 does some weird things with polybar sometimes. The fix should still be setting `override-redirect = true` in the bar section. With this comes again the issue of the bar overlapping the windows. We have since created an entry in the [Know Issues page](https://github.com/jaagr/polybar/wiki/Known-Issues#override-redirect-in-i3) for these i3 issues.

**Comment by Try431** [comment]
Ah damn, I was hoping to avoid having to deal with `override-redirect`. Oh well, thanks for the help!

**Comment by patrick96** [comment]
I don't think you can get around that on multi-monitor i3 unfortunately

**Comment by Try431** [comment]
Just wanted to leave an update on this ticket. I never really got around to ironing this out, but today decided to tackle it again and I've finally found a solution that works perfectly for my setup. Figured I should post here in case some other person stumbles upon this with a similar issue (which in my research, seems to be quite common).

As discussed above, setting `override-redirect = true` and `wm-restack = i3` did address the issue of polybar appearing on the wrong monitors, but that didn't quite work for me because i3 then didn't know to allocate space for it. What I ended up doing is modifying my i3-gaps settings to create space at the top for the bar (`gaps top`), and I commented out smart-gaps so that single-window workspaces would have that space as well.

_I should note that the [other common workaround](https://github.com/polybar/polybar/wiki/Known-Issues#override-redirect-in-i3) is to create a dummy transparent polybar that takes up the same length as one's primary bar, but without the `override-redirect` or `wm-restack` settings so that i3 knows to allocate space for it. I already used i3-gaps, so I found that solution much simpler and cleaner_
````
### i3-gaps config ###

# Disabling windows for i3-gaps
for_window [class="^.*"] border pixel 1

gaps inner 13
#smart_gaps on
gaps top 25
gaps left -11
gaps right -11
gaps bottom -12


# Colors
# class                 border  backgr. text    indicator
client.focused          #BEBEBE #BEBEBE #2D2D2D #BEBEBE
client.focused_inactive #2d2d2d #2d2d2d #dcdcdc #484e50
client.unfocused        #808080 #808080 #dcdcdc #808080
client.urgent           #2D2D2D #2D2D2D #dcdcdc #900000
````

You'll also see that I forced the left, right, and bottom edges of the windows out to create more space.

So, this addressed the issues for any non-transparent windows (text editors, browsers, etc.), but I really like working with transparent terminals, and when going fullscreen in one of those, I could still see my polybar through the transparent window, and it muddled the text in the terminal. Luckily, polybar has a [feature](https://github.com/polybar/polybar/wiki/Module:-ipc) wherein you can send commands to the bar if you have `enable-ipc = true` set in your [bar/<name>] settings. **Note - you don't have to actually need to have a separate module, that's only for if you want to interact with said module via ipc messages**

Now that my bar can take message, I tweaked my fullscreen bindsym to also toggle hiding the polybar: `bindsym $mod+f fullscreen; exec polybar-msg cmd toggle`

And now we're good! On a multi-monitor setup, both bars are in their correct positions and are properly hidden away by both non- and fully-transparent windows.
