### ISSUE TITLE
Add non-normalized cpu %percentage%

### ISSUE THREAD

**Issue by BigRedEye** [jaagr/polybar#1516]
## Is your feature request related to a problem? Please describe.
Sometimes the normalized processor load (0% - 100%) is not very informative, especially in systems with a large number of cores.

## Why does polybar need this feature?
Consider a system with 16 cores, then 100% load of one core will be drawn as 6% and each core has ~6 load levels. For example, both top and htop displays 100% as full load of only one core, therefore in such system full cpu usage will be displayed as 1600%. I think that this number may be better in some situations.

## Describe the solution you'd like
Just add a "normalize-load" option to the config that defaults to true, for example: https://github.com/BigRedEye/polybar/commit/8c7b4e400659bf7550c473f0247afc146d6b8132

## Describe alternatives you've considered
To implement this functionality I have to use a script module that simply copy-pastes code from cpu.cpp with a few modified lines, but it looks like a useful feature that can be easily implemented.

**Comment by patrick96** [comment]
Good idea! Could you please open a PR for those changes?
