### ISSUE TITLE
Bridge Interface Error - Failed to query interface 'br0'

### ISSUE THREAD

**Issue by dR3b** [jaagr/polybar#1522]
## Describe the issue
The network interface "br0" is not displayed. But it works with a physical network adapter e.g. "eno1".

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
modules-right = network

[module/network]
type = internal/network
interface = "br0"
label-connected = "%ifname% %linkspeed%"
label-disconnected = disconnected
```

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
warn: module/network: Failed to query interface 'br0'
warn: module/network: Failed to query interface 'br0'
warn: module/network: Failed to query interface 'br0'
warn: module/network: Failed to query interface 'br0'
warn: module/network: Failed to query interface 'br0'
```

## Environment:
* WM: i3
* PB: polybar 3.2.1

**Comment by patrick96** [comment]
Hmm, I don't even know if polybar was built to support bridge interfaces.

Can you run the following commands for me so that I can figure out, if the current implementation can support bridge interfaces.
```bash
ethtool -i br0
ethtool br0
cat /sys/class/net/br0/operstate
```

**Comment by spsarolkar** [comment]
Hi,

I am facing the similar issue,

below is output of commands mentioned above

$ cat /sys/class/net/br0/operstate
up
$ ethtool br0
Settings for br0:
Cannot get wake-on-lan settings: Operation not permitted
        Link detected: yes
$ sudo ethtool br0
Password: 
Settings for br0:
        Link detected: yes

**Comment by dR3b** [comment]
```
cat /sys/class/net/br0/operstate
up
```

**Comment by dR3b** [comment]
Thanks!
