### ISSUE TITLE
Modules doesn't work

### ISSUE THREAD

**Issue by maramekoukou** [jaagr/polybar#1525]
## Describe the issue
Hello all, i'm sure i have installed all dependencies for polybar and modules, but they still doesn't work.

When i'm launching polybar with this command line : polybar -l info white (white is the name of my polybar), i have theses results endlessly :

* Bar window: 0x0800002
* module/volume: Rebuilding cache
* module/battery: Rebuilding cache
* module/mpd: Rebuilding cache
* module/mpd: Hiding module since queue is empty
* module/i3: Rebuilding cache
* module/wlan: Rebuilding cache
* module/cpu: Rebuilding cache
* module/date: Rebuilding cache
* module/time: Rebuilding cache
* module/powermenu: Rebuilding cache
* Redrawing bar window
* Redrawing bar window
* Redrawing bar window
* module/battery: Polling values (inotify fallback)
* module/battery: Rebuilding cache
* module/cpu: Rebuilding cache
* Redrawing bar window
* module/battery: Rebuilding cache
* module/cpu: Rebuilding cache
* module/time: Rebuilding cache
* Redrawing bar window
* module/battery: Rebuilding cache
* module/cpu: Rebuilding cache
* Redrawing bar window
* module/battery: Polling values (inotify fallback)
* module/battery: Rebuilding cache
* Redrawing bar window
* module/battery: Rebuilding cache
* module/cpu: Rebuilding cache
* module/battery: Rebuilding cache
* module/wlan: Rebuilding cache
* module/cpu: Rebuilding cache
* module/battery: Polling values (inotify fallback)

I'm working on Ubuntu 18.04 with i3-gaps

Thanks for any helpful informations

**Comment by patrick96** [comment]
Could you please post the entire output of `polybar -l info white`, not just the last few lines. Any errors you get often appear at the beginning.

Also what is the output of `polybar -vvv`?

**Comment by maramekoukou** [comment]
polybar -vvv
polybar 3.2.0-66-gd3e3791

Features: +alsa +curl +i3 +mpd +network(libnl) -pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags:  -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: 



polybar -l info white
* Loading config: /home/florian/.config/polybar/config
* Loaded monitor eDP-1 (1920x1080+0+0)
* Bar geometry: 1920x30+0+0
* Starting application
* Starting module/volume
* Starting module/battery
* Starting module/mpd
* Starting module/i3
* Starting module/wlan
* Starting module/cpu
* Starting module/date
* Starting module/time
* Starting module/powermenu
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=11)
* Configured DPI = 96x96
* Loaded font "Hack:size=10" (name=Hack, offset=3, file=/usr/share/fonts/truetype/hack/Hack-Regular.ttf)
* Loaded font "FontAwesome:style=Regular:pixelsize=12" (name=FontAwesome, offset=3, file=/usr/share/fonts/opentype/font-awesome/FontAwesome.otf)
* Loaded font "FontAwesome:style=Regular:pixelsize=12" (name=FontAwesome, offset=3, file=/usr/share/fonts/opentype/font-awesome/FontAwesome.otf)
* Loaded font "FontAwesome:pixelsize=12" (name=FontAwesome, offset=3, file=/usr/share/fonts/opentype/font-awesome/FontAwesome.otf)
* Bar window: 0x2000002
* module/volume: Rebuilding cache
* module/battery: Rebuilding cache
* module/mpd: Rebuilding cache
* module/mpd: Hiding module since queue is empty
* module/i3: Rebuilding cache
* module/wlan: Rebuilding cache
* module/cpu: Rebuilding cache
* module/date: Rebuilding cache
* module/time: Rebuilding cache
* module/powermenu: Rebuilding cache
* Redrawing bar window
* Redrawing bar window
* Redrawing bar window
* module/battery: Polling values (inotify fallback)
* module/battery: Rebuilding cache
* module/cpu: Rebuilding cache
* Redrawing bar window
* module/battery: Rebuilding cache
* module/cpu: Rebuilding cache
* Redrawing bar window
* module/battery: Rebuilding cache
* module/cpu: Rebuilding cache
* Redrawing bar window
* module/battery: Polling values (inotify fallback)

**Comment by maramekoukou** [comment]
I'm on Ubuntu 18.04 and i use i3-gaps
The problem is if i click on wifi modules for example, nothing happens.
I except that i i could see all wifi networks around me.
Also if i click on the shutdown button, i can see reboot and power off buttons but nothing happens if click on them.

**Comment by patrick96** [comment]
But the bar actually displays correctly?

> The problem is if i click on wifi modules for example, nothing happens.
I except that i i could see all wifi networks around me.

Polybar doesn't have that feature built-in

> Also if i click on the shutdown button, i can see reboot and power off buttons but nothing happens if click on them.

Well, it depends on how you configured them. If you used the sample config, the commands tied to those buttons are `sudo reboot` and `sudo poweroff`. This often requires you to enter a password. You'll probably have to reconfigure the powermenu module to use reboot and poweroff commands that work on your system without entering a password.

**Comment by maramekoukou** [comment]
Yes bar displays correctly, but it's oblige me to disconnect from i3 to use a wlan network..
Ok i will dig it, thanks for your help! :)

**Comment by maramekoukou** [comment]
Ok i just found the command nmtui which let me see all wlan networks.
You can close the ticket :)

**Comment by patrick96** [comment]
> but it's oblige me to disconnect from i3 to use a wlan network..

Why? Connecting to a wifi network should be *completely* indepent of polybar.

I will close this as it seems the bar is actually working correctly.
