### ISSUE TITLE
Make tray a module

### ISSUE THREAD

**Issue by fakheet** [jaagr/polybar#1526]
So, basically, why not just handle the systray as a module, rather than a separate window layered on top? 

Right now tray is kind of wonky because it really only has 3 placement options and they are all meh in terms of aesthetics. And If you want to put the tray somewhere else, you better hope that no icons are added or removed, otherwise it will either overlap with neighboring elements or leave unnecessary gaps. Some people might prefer to have the tray at some particular place (e.g. between battery and clock). 

I don't see how making tray a module could interfere with the design, since tray already scales to bar's size and adheres to some of the rules, but I'm new to polybar so there may be some reason, why it can't be done, that I am unaware of. If so, please correct me.

**Comment by patrick96** [comment]
> just

It's unfortunately not that easy. Currently the tray uses XEMBED which is a protocol to position windows inside other windows, this means each tray icon you see is actually a window that is handled by whatever application provides the icon and polybar doesn't have much control over that window (other than positioning). This is the reason the tray has to be a separate window.

NBonaparte is doing some work on a proper systray module (see #913), which uses a new tray specification. StatusNotifierItem. But the whole endeavour is far from finished.

**Comment by fakheet** [comment]
I see, thank you for your answer.
