### ISSUE TITLE
Offset doesn't work

### ISSUE THREAD

**Issue by zandimna** [jaagr/polybar#1527]
Describe the issue
*A clear and concise description of what the bug is.*
offset-x and offset-y options are does not work
**Expected behavior:**
the bar should shift by {} pixels to the right and {} pixels down
**Actual behavior:**
the bar itself didn't move, but the tray icons did
## To Reproduce
default config, with offset-x and offset-y uncommented

## Polybar Log
```
warn: No monitor specified, using "DP-1"
warn: pulseaudio: using default sink alsa_output.pci-0000_00_1f.3.analog-stereo
error: tray: Failed to put tray above 0x3000002 in the stack (XCB_MATCH (8))

```

## Screenshots
https://imgur.com/a/MJfQ7rF
## Environment:
WM: i3
Output of `polybar -vvv`:
```
polybar 3.2.1
Features: +alsa +curl +i3 -mpd +network +pulseaudio +xkeyboard
X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor
Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by zandimna** [comment]
> See #1101, you need to set `override-redirect` to `true`.

Okay thanks. I encountered the same issues as described there. I'll just use border-size-top instead.

**Comment by patrick96** [comment]
i3 is the worst when it comes to bar positioning :sweat_smile:
