### ISSUE TITLE
Polybar running in the wrong monitor

### ISSUE THREAD

**Issue by inhame** [jaagr/polybar#1532]
## Describe the issue
The application doesn't run in the right monitor.

```config```:
```
[bar/bottom]
monitor = ${env:MONITOR}
...
```

```polybar -m```:
```
HDMI2: 1360x768+0+0
DP1: 1280x1024+4480+824
HDMI-2: 1920x1080+2560+768
HDMI-0: 2560x1080+0+768
```

Polybar can't see the difference over HDMI2 and HDMI-2, as it won't start in HDMI-2, only in HDMI2.

The ```polybar -l info``` at the command ```MONITOR=HDMI2 polybar -l info bottom``` shows:
```* Loaded monitor HDMI2 (1360x768+0+0)```

The ```polybar -l info``` for ```MONITOR=HDMI-2 polybar -l info bottom``` also shows:
```* Loaded monitor HDMI2 (1360x768+0+0)```

**Expected behavior:**
Polybar is expected to load in the right monitor.

**Actual behavior:**
Polybar loads in the wrong monitor.

## To Reproduce
1. Have a output named HDMI2
2. Have another output named HDMI-2
3. Try to run polybar in both outputs

## Additional context
If I remove the replace at the source file ```x11/extensions/randr.cpp```, line 23, it works as expected, but I don't know if it has any other implications in the overall functionality.

**Comment by patrick96** [comment]
Seems like a polybar bug to me.

`monitor-strict = true` in your bar section should fix this for you. But line 23 in `randr.cpp` seems like some workaround that jaagr used because he had different monitor names depending on driver he was using. I'm going to remove it.

**Comment by inhame** [comment]
```monitor-strict = true in your bar section should fix this for you.```
Yep, it works flawlessly now.

Thanks for the help @patrick96!
