### ISSUE TITLE
[question][bspwm] have polybar take no tiling space and spawn above all windows

### ISSUE THREAD

**Issue by cancercufasole** [jaagr/polybar#1535]
Is it possible to make polybar spawn above all windows and take no tiling space ?
I've looked at other issues and documentation and I feel like I'm missing something.

What i'm trying to is is configure polybar to only show above everything when the super key is pressed.The second part was done with a few lines in sxhkd.

Super_L
        polybar-msg cmd show
@Super_L
        polybar-msg cmd hide

Sorry if this is the wrong place to place this question.

**Comment by cancercufasole** [comment]
That's it! I ignored that because I thought for some reason it was available to i3wm only.
The only problem I have now is that polybar shows under and not above.

**Comment by TonCherAmi** [comment]
`wm-restack = bspwm` might help though I'm not at all sure.

**Comment by cancercufasole** [comment]
I did this using override-redirect and xdo.

Super_L
  xdo show -N "Polybar"; xdo raise -N "Polybar"
@Super_L
  xdo hide -N "Polybar"

Thanks for the help. This is not really an issue so i'll close this.
