### ISSUE TITLE
On dual monitors, when a module has a long loading time, it will only load on one monitor. 

### ISSUE THREAD

**Issue by zjeffer** [jaagr/polybar#1544]
## Describe the issue

I found this with the `updates-arch-combined` module from https://github.com/x70b1/polybar-scripts/. When using two (or more?) monitors and using the same bar on each monitor, if there's a module that has a long loading time, polybar will only load that module on 1 monitor. In my case, with `updates-arch-combined`, it has a 2 second delay before appearing on 1 monitor, but after the set interval (mine is 600 seconds), the module will be loaded on my second monitor. 

**Expected behavior:**

The module will load at the same time, on both bars.

**Actual behavior:**

The module loads on 1 bar, and after the interval set in the polybar config, it will load it on the other bar. 

## To Reproduce

1) Use a module that has a long loading time (like `updates-arch-combined`, where it needs to contact update servers).
2) Have 2 monitors and load the same bar on each of them.
3) Reload polybar. The module will load on only 1 bar.
4) After x seconds (where `interval=x` in config), the module will also load on the other bar. Set x to 10 or something to debug. 

## Polybar Log

Nothing in log.

## Environment:
* WM: bspwm
* Output of `polybar -vvv`:

```
polybar 3.2.1

Features: +alsa +curl -i3 -mpd +network +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: **-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now**
```

**Comment by x70b1** [comment]
More background: https://github.com/x70b1/polybar-scripts/issues/108

**Comment by x70b1** [comment]
More Background: https://github.com/x70b1/polybar-scripts/issues/108

**Comment by zjeffer** [comment]
A consequence of this is that information is not the same on 2 monitors. 
For instance, with `updates-arch-combined`, one monitor might show a different amount of updates than the other monitor(s), because the information is not called at the same time.

**Comment by patrick96** [comment]
Are you sure this happens with any long running command? I suspect that whichever bar runs first locks the pacman database and in the other bar the `checkupdates` command fails, so the `updates-arch-combined` script doesn't output anything. To confirm this, try running `updates-arch-combined` in two terminals side-by-side at the same time and see if one of the commands doesn't output anything

**Comment by zjeffer** [comment]
I can confirm that one `checkupdates` fails when running it twice at the same time. How can I make sure the second module loads right after the first one is done?

**Comment by patrick96** [comment]
I have already talked to x70b1 about changes to the script, until then, you could change the `exec` key to:
```dosini
exec = CHECKUPDATES_DB=$(mktemp -d) ~/polybar-scripts/updates-arch-combined.sh
```

This would prevent the two calls to `checkupdates` from interfering with each other.

Closing this as it's not a polybar issue.

**Comment by x70b1** [comment]
I add this solution as workaround to our `polybar-scripts` repo.
