### ISSUE TITLE
Weird CLI Output with cli->get()

### ISSUE THREAD

**Issue by Dentrax** [jaagr/polybar#1548]
`It issue is not a related problem with Polybar.`

## Describe the issue

I took Polybar's CLI parsing algorithm for testing and educational purposes under MIT licence.

That are:
[command_line.hpp](https://github.com/jaagr/polybar/blob/master/include/components/command_line.hpp)
[command_line.cpp](https://github.com/jaagr/polybar/blob/master/src/components/command_line.cpp)

[cli.Get()](https://github.com/jaagr/polybar/blob/master/include/components/command_line.hpp#L54) output is not readable.

**Expected behavior:**

After you have used the required CLI files, build the project.

1. `cmake .`
2. `make`
3. `./app -t test`

**Actual behavior:**

My output is:

```
�Z���

(null)
1: 
2: 
3: 
```

## To Reproduce

**Initialization:**

```
//https://github.com/jaagr/polybar/blob/master/include/components/command_line.hpp
// clang-format off
  const command_line::options opts{
      command_line::option{"-h", "--help", "Display this help and exit"},
      command_line::option{"-v", "--version", "Display build details and exit"},
      command_line::option{"-t", "--test", "Test"},
  };
  // clang-format on

    vector<string> args{argv + 1, argv + argc};

command_line::parser::make_type cli{command_line::parser::make(move(argv[0]), move(opts))};
cli->process_input(args);
```
`cli.has()` **works well**

```
if(cli->has("test")){
   //OK
}
```

My testing code:

```
  if(cli->has("test")){
      m_options.delimiter = cli->get("test").c_str()[0];
      printf("%s\n", cli->get("test").data());
      printf("%s\n", cli->get("test").c_str());
      printf("%c\n", cli->get("test").c_str()[0]);
      cout << "1: " << cli->get("test") << endl;
      cout << "2: " << cli->get("test").c_str() << endl;
      cout << "3: " << cli->get("test").c_str()[0] << endl;
      //None of all the above does not create a output
    }
```

Everything is compiling without any errors. But why does the  `cli.get()` command returns null? I didn't change anything. What exactly did I miss?

Thanks in advance...

**Comment by patrick96** [comment]
> `command_line::option{"-t", "--test", "Test"}`

This specifies `--test` as an command line argument just like `--help`, but you try to pass an additional value (`--test=test`), you need to define your `option` differently if you want to support that, here is how `main.cpp` does it:
```cpp
command_line::option{"-l", "--log", "Set the logging verbosity (default: WARNING)", "LEVEL", {"error", "warning", "info", "trace"}},
...
command_line::option{"-p", "--png", "Save png snapshot to FILE after running for 3 seconds", "FILE"},
```

You give a 4th argument to the `option` constructor which is the name that is printed when the command line usage is displayed.  For example, with the following option:
```cpp
command_line::option{"-t", "--test", "Test", "TEST"},
```
`cli->usage()` displays:
```
  -t, --test=TEST   Test
```
