### ISSUE TITLE
Pulseaudio and ALSA module input config

### ISSUE THREAD

**Issue by chelmich** [jaagr/polybar#1551]
I would like to be able to individually enable and disable scroll and click handling for Pulseadio or ALSA. Although there is already a `handle-events` option, I would like to keep the click to mute without the scrolling. Setting `interval = 0` works but feels hacky. I think a new config option would be the best solution. To do this config options for `enable-scroll` and `enable-click` should be added to both modules. I can easily add these features, but I wanted some input before I made a pull request. Also, I noticed alsa and pulseaudio are the only modules that use the `handle-events` option. Should it be replaced or added to more modules?

**Comment by patrick96** [comment]
I have some thoughts on this, will have to wait until after Christmas to respond.

**Comment by patrick96** [comment]
I have written a bit about something similar in #1524. When we implement that proposal, it would be possible to selectively disable or even override certain click actions. This would remove the need for having separate config options for this. This would make the config a little less cluttered.

I actually didn't know about `handle-events` until now, it's not even documented anywhere. It's probably useful to leave it and have it to disable all actions without having to specify each mouse action seperately.
