### ISSUE TITLE
incorrect "marked" node flag in bspwm

### ISSUE THREAD

**Issue by MrYakobo** [jaagr/polybar#1552]
## Describe the issue
bspwm's "marked" node flag is messed up

**Expected behavior:**
When setting the node flag to `marked`, `label-marked` should be drawn. In given config, this is set to 'M'

**Actual behavior:**
`label-locked` is drawn. In given config, this is set to 'L'.

## To Reproduce
config:
```dosini
[general]
padding = 2

[bar/example]
bottom = true
monitor= eDP1
width = 100%
height = 33
radius = 0

background = #ee190e18
foreground = #f9f7cc
line-size = 3
line-color = #f00

border-size = 0
border-color = #00000000

padding-left = 0
padding-right = 2

font-0 = monospace:pixelsize=12;1

modules-left = bspwm

[module/bspwm]
type = internal/bspwm

format = <label-state> <label-mode>

label-tiled=-
label-monocle=M
label-fullscreen=F
label-floating=P
label-locked = L
label-sticky = S
label-private = P

label-focused = O
label-focused-padding = ${general.padding}

label-occupied = o
label-occupied-padding = ${general.padding}
label-empty = ∙

label-empty-padding = ${general.padding}

[global/wm]
margin-top = 0
margin-bottom = 0
```
Run `bspc node -g locked && bspc node -g marked`, this is mapped to `Ctrl+Super+{X,M}` in the default config for sxhkd.

## Polybar Log
`warn: module/bspwm: Undefined G => 'M'`

## Screenshots
*If applicable, add screenshots to help explain your problem.*
![bugreport](https://user-images.githubusercontent.com/11942597/50306909-12977780-0497-11e9-9140-cbcf020450a1.png)

## Environment:
* WM: bspwm
* Output of `polybar -vvv`:
```
polybar 3.2.1
Features: +alsa +curl +i3 -mpd +network +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment]
There is no `label-marked` ;)

Marked nodes were added to bspwm earlier this year and polybar doesn't support them yet (that's why you get the warning).

I have added support for marked nodes in #1557
