### ISSUE TITLE
polybar partially covered by default top bar

### ISSUE THREAD

**Issue by lastaidkit** [jaagr/polybar#1560]
I have installed polybar, but when I rune "polybar example: my default top bar in Ubuntu is still there with polybar behind it and partially hidden. Not sure how to solve this. Thank you.
![screenshot from 2018-12-26 20-01-58](https://user-images.githubusercontent.com/42901036/50465303-3d784480-094b-11e9-9b72-3805f6ce2bd6.png)

**Comment by 0xfederama** [comment]
I have the same issue. How did you solve this?

**Comment by Kratacoa** [comment]
Why is this a polybar issue? Remove GNOME's bar.
