### ISSUE TITLE
Show class name (not the title) of the focused window in polybar.

### ISSUE THREAD

**Issue by impascal** [jaagr/polybar#1561]
For example, I want to show on my polybar "urxvt" when I'm using urxvt, "firefox" when I'm using firefox etc.. it possible? If yes, how?

**Comment by patrick96** [comment]
There is no built-in functionality for this.

You could use the [script module](https://github.com/jaagr/polybar/wiki/Module:-script) and use `xdotool` and `xprop` to somehow get the window class.
