### ISSUE TITLE
Backlight doesn't work on Dell Latitude E6420 laptop

### ISSUE THREAD

**Issue by SpaceboyRoss01** [jaagr/polybar#1564]
## Describe the issue
A display called LVDS-0 doesn't work with the backlight module because it couldn't get data `(err: XCB_NAME (15))`

**Expected behavior:**
The backlight module to load

**Actual behavior:**
The backlight module is disabled

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[module/backlight]
type = internal/xbacklight
enable-scroll = true
ramp-0 = 🌕
ramp-1 = 🌔
ramp-2 = 🌓
ramp-3 = 🌒
ramp-4 = 🌑
format = <ramp>
```
Use this on a Dell Latitude E6420.

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
warn: No monitor specified, using "LVDS-0"
error: module/backlight: Could not get data (err: XCB_NAME (15))
error: Disabling module "backlight" (reason: Not supported for "LVDS-0")
```

## Environment:
* WM: i3
* Output of `polybar -vvv`:
```
polybar 3.3.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment]
Your monitor doesn't support this way of gathering the brightness. Try to use the [backlight module](https://github.com/jaagr/polybar/wiki/Module:-backlight).

**Comment by SpaceboyRoss01** [comment]
But xbacklight works, I can run the command.

**Comment by patrick96** [comment]
And the `xbacklight` changes the brightness of your monitor? Are you running on multiple monitors?

**Comment by SpaceboyRoss01** [comment]
Single monitor and the backlight changes

**Comment by patrick96** [comment]
Dang, polybar uses basically the same code as `xbacklight`, really don't know why this doesn't work.

My best guess is that polybar tries to load the backlight info from the wrong monitor, because that's about the only difference to `xbacklight` which loops through all monitors. Could you please post the output of `xrandr` and `polybar -m`.

If you are familiar with `gdb`, you could also help us track down what exactly fails during the xbacklight module initialization. You can compile polybar with debug symbols by using `cmake -DCMAKE_BUILD_TYPE=Debug ..`

The error `Disabling module "backlight" (reason: Not supported for "LVDS-0")` is caused by an exception which is caught [here](https://github.com/jaagr/polybar/blob/master/src/modules/xbacklight.cpp#L45). It would be useful to know which code line causes that exception.

**Comment by SpaceboyRoss01** [comment]
```
spaceboyross@RX-178_Gundam_Mk-II ~/b/c/bluelight> xrandr
Screen 0: minimum 8 x 8, current 1366 x 768, maximum 16384 x 16384
VGA-0 disconnected primary (normal left inverted right x axis y axis)
LVDS-0 connected 1366x768+0+0 (normal left inverted right x axis y axis) 309mm x 174mm
   1366x768      60.00*+  40.00  
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-0 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
spaceboyross@RX-178_Gundam_Mk-II ~/b/c/bluelight> polybar -mpolybar -m
LVDS-0: 1366x768+0+0
```

I installed polybar via `yarout` so I don't think I can use cmake without conflicts.

**Comment by patrick96** [comment]
Hmmmm. This doesn't make sense :expressionless:

There isn't really any more troubleshooting I can do without having a machine that reproduces this issue.

> I installed polybar via yarout so I don't think I can use cmake without conflicts.

You will need to [compile from source](https://github.com/jaagr/polybar#building-from-source)

**Comment by SpaceboyRoss01** [comment]
I think using xrandr will be better for changing the backlight. The backlight wouldn't change using xbacklight but I didn't get any errors nor any output. The backlight changed when I used xrandr to do it.

**Comment by patrick96** [comment]
> The backlight wouldn't change using xbacklight but I didn't get any errors nor any output.

Oh. Then it really just isn't supported. It's the same on my laptop. Does the [backlight](https://github.com/jaagr/polybar/wiki/Module:-backlight) module work for you? It doesn't support changing the brightness though. I use [illum](https://github.com/jmesmon/illum) to change the brightness.

**Comment by SpaceboyRoss01** [comment]
The backlight module works.

**Comment by patrick96** [comment]
Alright, awesome. That's cleared up then.
