### ISSUE TITLE
Bar borders don't get rounded with bar corners

### ISSUE THREAD

**Issue by Sigma-One** [jaagr/polybar#1566]
## Issue Description
Bar borders do not get rounded with the bar corners, when using the `radius` field.

## To Reproduce
These settings will make a bar have this issue. Colors set to ones that show the issue as clearly as possible.
```dosini
background = #0f0

radius = 10px

border-size = 2px
border-color = #f00
```

## Environment:
* WM: i3-gaps
* Polybar Version: 3.3.0-1
* OS: Arch Linux

**Comment by patrick96** [comment]
Hey, thanks for reporting. I think we stumbled upon this before, but I can't for the life of me find the issue for it. But I think the consensus was that this isn't really possible to do right now, at least not in a way that requires lots of big changes. If you can find a solution to this that isn't a major change to the code, I'd welcome a PR, but I'm going to mark this as wontfix for now
