### ISSUE TITLE
Set border size values using percentages

### ISSUE THREAD

**Issue by douglasrizzo** [jaagr/polybar#1567]
## Is your feature request related to a problem? Please describe.
I am trying to set border size values using percentages. I use the same config file for multiple monitors, but since they have different resolutions, setting the border in pixels is not very useful.

## Why does polybar need this feature?
Dimensions and offset can already be set using percentages, but the border cannot. This feature will be useful in the same way the aforementioned ones are, making configuration more flexible and specially useful for users with multiple monitors with different dimensions.

## Describe the solution you'd like
To be able to set the values of `border-{left|right|top|bottom}-size` using percentages, for example:

    border-left-size = 12%
    border-right-size = 12%
    border-top-size = 1
    border-bottom}-size = 1

Percentages can be relative to the current dimensions of the bar or the display size.

## Describe alternatives you've considered
I tried using the percentages, but currently they are treated as pixel values, _e.g._ `border-left-size = 30%` has the same behavior as `border-left-size = 30`.

## Additional context
I have a display which is 1920 pixels wide and another one which is 1440 pixels wide. In the larger one, I set `border-left-size` and `border-right-size` to 300, but in the smaller one, these borders are too large. Using percentages instead of pixel values might help mitigate this problem.

**Comment by patrick96** [comment]
Good idea.

I think this could be done quite easily. If we are already doing this, we could also add support for mixed percent/pixel values like we added for `width` and `height` in #1224 and #701 (e.g. `border-size = 10%:-1`).

All the changes would need to be made in `src/components/bar.cpp`.
We would appreciate a PR from you if you can, otherwise this will just go onto our backlog.
