### ISSUE TITLE
Moving bar due to text

### ISSUE THREAD

**Issue by Maddogruss** [jaagr/polybar#1568]
## Describe the issue
**A clear and concise description of what the bug is.**
Whenever a module has "dynamic" text (i.e: Changing, like the system clock, or internet speed), it moves left and right.
I tried changing the fonts I use, used the default ones, but nothing worked. Obviously it might still be a font problem, I haven't tried them all...

**Expected behavior:**
The bar should stay static regardless of the output.

**Actual behavior:**
Well, if my upload speed is 200KB/s for instance, the remaining text on the bar will move a bit to the left to accommodate for the additional characters.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[colors]
background = #222
background-alt = #444
foreground = #dfdfdf
foreground-alt = #555
primary = #ffb52a
secondary = #e60053
alert = #bd2c40

[bar/mybar]
monitor = ${env:MONITOR:}
width = 100%
height = 20
radius = 0.0
fixed-center = false
bottom = true
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 2
line-color = #f00
border-size = 0
border-color = #00000000
padding-left = 2
padding-right = 2
module-margin-left = 2
module-margin-right = 2
font-0 = Cantarell:pixelsize=10;1
font-1 = fixed:pixelsize=10;1
font-2 = unifont:fontformat=truetype:size=8:antialias=false;0
font-3 = Wuncon Siji:pixelsize=10;1
modules-left = i3 mpd
modules-right = root home internal memory cpu temperature internet vpn date
tray-position = right
tray-padding = 3
scroll-up = i3wm-wsnext
scroll-down = i3wm-wsprev
cursor-click = pointer
cursor-scroll = ns-resize
separator = |

[module/i3]
type = internal/i3
pin-workspaces = true
strip-wsnumbers = false
index-sort = false
enable-click = false
enable-scroll = true
wrapping-scroll = false
reverse-scroll = true
format = <label-state> <label-mode>
label-mode = %mode%
label-mode-padding = 2
label-mode-background = #e60053
label-focused = %name%
label-focused-foreground = #ffffff
label-focused-background = #3f3f3f
label-focused-underline = #fba922
label-focused-padding = 2
label-unfocused = %name%
label-unfocused-padding = 2
label-visible = %index%
label-visible-underline = #555555
label-visible-padding = 2
label-urgent = %name%
label-urgent-foreground = #000000
label-urgent-background = #bd2c40
label-urgent-padding = 2
label-separator-padding = 2
label-separator-foreground = #ffb52a

[module/root]
type = internal/fs
mount-0 = /
interval = 1
format-mounted = <label-mounted>
label-mounted = %{F#28bed8}Root:%{F#FFFFFF}  %free%

[module/home]
type = internal/fs
mount-0 = /home
interval = 1
format-mounted = <label-mounted>
label-mounted = %{F#28bed8}Home:%{F#FFFFFF}  %free%

[module/games]
type = internal/fs
mount-0 = /home/henry/games
interval = 1
fixed-values = true
format-mounted = <label-mounted>
label-mounted = %{F#28bed8}Games:%{F#FFFFFF}  %free%

[module/mpd]
type = internal/mpd
format-online = <label-song> - <label-time>
label-song = %artist% - %title%
label-song-maxlen = 64
label-song-ellipsis = true

[module/cpu]
type = internal/cpu
interval = 1
format = "<label>%"
format-prefix = " CPU: "
format-prefix-foreground = #4bffdc
label = %percentage%

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60
hwmon-path = /home/henry/.config/polybar/hwmon/temp1_input
format = <label>
format-prefix = " TMP: "
format-prefix-foreground = #4bffdc
format-warn = <label-warn>
format-warn-prefix = " TMP: "
format-warn-prefix-foreground = #ff0000
label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = #ff0000

[module/memory]
type = internal/memory
interval = 1
format-prefix = " RAM: "
format-prefix-foreground = #4bffdc
label = %gb_used%

[module/internet]
type = internal/network
interface = enp2s0
interval = 1
label-connected = " E: %local_ip% ( D: %downspeed% | U: %upspeed% )"
label-connected-foreground = #55aa55
udspeed-minwidth = 3
label-disconnected = "  E: Offline"
label-disconnected-foreground = #ff0000

[module/vpn]
type = internal/network
interface = tun0
interval = 1
label-connected-foreground = #55aa55
label-connected = " VPN: On"
label-disconnected = " VPN: Off "
label-disconnected-foreground = #ff0000

[module/date]
type = internal/date
interval = 1
label = %time% %date% 
date = "%A  %d/%m/%y"
time = " %H:%M -"
format-prefix = 
format-prefix-foreground = #0a6cf5

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
;compositing-border = over

[global/wm]
margin-top = 5
margin-bottom = 5
; vim:ft=dosini
```
**List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.**
Not much really, download something, make your CPU heat up or whatever, the numbers need to change. On the other hand, you could just add %s to the time in my date module, since it also happens when the clock changes.

## Environment:
* WM: `i3`
* Output of `polybar -vvv: 

```polybar 3.3.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

## Additional context

Issue is similar to #82 but affects pretty much any text that changes (Clock, CPU usage and temp, download speed, etc)
I tried doing what was recommended here with no success.

**Comment by patrick96** [comment]
If you actually want modules with static width, you need to make sure that no token that you use can ever change its width. You can do that by having their max and minwidth [properties](https://github.com/jaagr/polybar/wiki/Formatting#tokens) to the same value, this way they always stay the same width.

You also need to make sure that your fonts are all monospaced because the max and minwidth values are all measured in spaces and having a non-monospaced font can have the same number of characters take a different amount of space. I'm pretty sure `Cantarell` is not monospaced, use something like `DejaVu Sans Mono` or `Noto Sans Mono`

**Comment by rieje** [comment]
@patrick96 This might be a different problem then, but I'm having the same issue. I am using a monospaced font (Inconsolata):

[module/pulseaudio]
type = internal/pulseaudio

use-ui-max = false

format-volume = <label-volume>
label-volume = VOL %percentage:3:3%

label-muted = MUTE %percentage%
label-muted-foreground = #666


When changing the volume so the number of digits in its values change (e.g. 0 to 50 and then to 100), it shifts all the modules to the left (this pulseaudio module is defined at `module-right`). I've tried setting the max/minwidth to 2, 3, and 4. Obviously setting it to 1 would not cause any shifting, but is not useful at all.

**Comment by lopezdylan** [comment]
I'm having the same issue. I'm using a monospaced font and I set the max and min width to the same value.

**Comment by patrick96** [comment]
@lopezdylan If you think this is an issue with your config and want help fixing it, please ask on [Gitter](https://gitter.im/polybar/polybar) or one of our other [support sites](https://github.com/polybar/polybar/blob/master/SUPPORT.md). If you think this is a bug in polybar, please open a new issue.

**Comment by danjenson** [comment]
This also doesn't work for me unless I 0 pad the number. It doesn't seem to respect min width without a pad value.

**Comment by patrick96** [comment]
@danjenson Tokens are space padded by default. But if you use a non-monospaced font spaces take less space than a regular character would and so you have shifting. First make sure you didn't accidentally use a non-monospaced font.

Even if you meant to use a monospaced font, it's possible that polybar [failed to load it](https://github.com/polybar/polybar/wiki/Fonts#debugging-font-issues)
