### ISSUE TITLE
Question/Feature Request: States for Custom Modules

### ISSUE THREAD

**Issue by DomHudson** [jaagr/polybar#1570]
## Summary

Hi, I don't actually know if this is a feature request or if the functionality I describe is already present in polybar.

What I am looking for is a way to have different "states" (Is this the right terminology? Does a different term already exist for this?) for custom modules. 

Many of the internal modules already have different "states", for example in the `internal/i3` module, there are `focused`, `unfocused`, `visible`. These can be configured differently and have different styling.

The module `internal/network` has different states for `connected` and `disconnected`.

## Description

What I wish to be able to achieve is configuration of the the format, underline, prefix etc based on different states. This would enable you to (for example) write a custom VPN module where the underline is grey if it is disconnected or in a given colour if it is connected.

If I'm not mistaken, the only way to achieve this currently is to output the colour to stdout, which means that some of your colour configuration is in whatever script produces this stdout and some is in the polybar configuration.

Any thoughts are much appreciated; many thanks,
Dom

**Comment by patrick96** [comment]
Hi, something similar has been requested already in #1116. It's not something we will implement in the near future. The main issue is that the script somehow needs to tell polybar which states exist and which state is currently active. Which is not easy because we would need to define a totally new syntax for this. What I do on my system is I have all my colors as environment variables and use them in all my polybar scripts and use them in polybar like this:

```dosini
[colors]
background = ${env:BAR_BG}
background-alt = #444
foreground = ${env:BAR_FG}
foreground-alt = #55

linecolor = ${env:ACTBG}

primary = ${env:ACTBG}
secondary = ${env:IACTBG}
alert = ${env:URGBG}

color0= ${env:COLOR0}
color1= ${env:COLOR1}
color2= ${env:COLOR2}
color3= ${env:COLOR3}
color4= ${env:COLOR4}
color5= ${env:COLOR5}
color6= ${env:COLOR6}
color7= ${env:COLOR7}
color8= ${env:COLOR8}
color9= ${env:COLOR9}
color10= ${env:COLOR10}
color11= ${env:COLOR11}
color12= ${env:COLOR12}
color13= ${env:COLOR13}
color14= ${env:COLOR14}
color15= ${env:COLOR15}
```
