### ISSUE TITLE
Xfce + Polybar won't launch

### ISSUE THREAD

**Issue by jonestristand** [jaagr/polybar#1572]
I'm using a launch.sh file as described, and have a .desktop file that references it in my ~/.config/autostart directory. Running the .desktop file manually results in polybar operating as expected, however when logging in (via lightDM) it fails with the error "X connection error" (I redirected the polybar stderr output to a file to see this). I assume that xfce is trying to launch polybar before the x server is running properly, but I'm not sure how to fix this...

**Comment by jonestristand** [comment]
I added the 'sleep' command and polybar began working. I then removed it to try to reproduce the error but it continued to work on reboot without any issues. Sorry!

**Comment by patrick96** [comment]
If it happens again, let us know what error message polybar produces
