### ISSUE TITLE
Impossible to get systray work

### ISSUE THREAD

**Issue by JoseAntonioTorre** [jaagr/polybar#1581]
Hi! I am trying to use i3wm with kde and I have succeeded .
When I have tried to use polybar as a KDE panel replacement I have been having problems with the systray.
Polybar is telling that another window has the ownership of the systray manager. I guest that it could be relates with kde session.
Have any of you make it works?
Thanks In advance

**Comment by hanschen** [comment]
See https://github.com/jaagr/polybar/issues/471#issuecomment-327070610.

Did you remove the system tray widget from the Plasma panel? (I assume you let i3 kill Plasma during startup, but maybe the Plasma widget grabs the XEMBED tray icons before it's killed.)

**Comment by JoseAntonioTorre** [comment]
@hanschen yes, I have removed it. I am using the same i3config from this post: https://www.reddit.com/r/unixporn/comments/64mihc/i3_kde_plasma_a_match_made_in_heaven/

I have read before the post that you metioned but I does not seem to have the solution.

**Comment by hanschen** [comment]
Hm that's strange. I used to have the same problem (running polybar + i3-gaps + KDE Plasma, started out from a similar config to the one you linked to), and I think I got it working after removing the panel, including the system tray widget, from my Plasma configuration.

Sorry I can't help more.

**Comment by hanschen** [comment]
@JoseAntonioTorre:

I don't think I've done anything special with my dotfiles. Here's the relevant section from my `~/.config/i3/config` (note that I use i3-gaps rather than i3):

```
#------------------------------------------------------------------------------
# Plasma integration
#------------------------------------------------------------------------------
# Source: https://gitlab.com/SlavMetal/dotfiles/blob/master/.config/i3/config

# Try to kill the wallpaper set by Plasma (it takes up the entire workspace and
# hides everything)
exec --no-startup-id wmctrl -c Plasma
for_window [title="Desktop — Plasma"] kill; floating enable

# Window rules

# Avoid tiling Plasma popups, dropdown windows, etc.
# For the first time, manually resize them, i3 will remember the setting for
# floating windows
for_window [class="Klipper"] floating enable
for_window [class="Kmix"] floating enable
for_window [class="kruler"] floating enable
for_window [class="krunner"] floating enable
for_window [class="Plasma"] floating enable
for_window [title="plasma-desktop"] floating enable
for_window [class="plasmashell"] floating enable;
for_window [class="Plasmoidviewer"] floating enable
for_window [class="yakuake"] floating enable;

# Avoid tiling for non-Plasma stuff
for_window [window_role="pop-up"] floating enable
for_window [window_role="bubble"] floating enable
for_window [window_role="task_dialog"] floating enable
for_window [window_role="Preferences"] floating enable
for_window [window_role="About"] floating enable

for_window [window_type="dialog"] floating enable
for_window [window_type="menu"] floating enable
```

Here's my `~/.config/plasma-org.kde.plasma.desktop-appletrc`:

```
[ActionPlugins][0]
MidButton;NoModifier=org.kde.paste
RightButton;NoModifier=org.kde.contextmenu
wheel:Vertical;NoModifier=org.kde.switchdesktop

[ActionPlugins][1]
RightButton;NoModifier=org.kde.contextmenu

[Containments][1]
activityId=404c756d-44b8-4c05-a870-3e03232b9c74
formfactor=0
immutability=1
lastScreen=0
location=0
plugin=org.kde.plasma.folder
wallpaperplugin=org.kde.image

[Containments][1][Configuration]
PreloadWeight=0

[Containments][1][General]
ToolBoxButtonState=topright
ToolBoxButtonX=1890

[Containments][15][General]
extraItems=org.kde.plasma.devicenotifier,org.kde.plasma.mediacontroller,org.kde.plasma.clipboard,org.kde.plasma.notifications,org.kde.plasma.battery,touchpad
knownItems=org.kde.plasma.devicenotifier,org.kde.plasma.battery,org.kde.plasma.mediacontroller,org.kde.plasma.clipboard,org.kde.plasma.notifications

[Containments][2]
activityId=404c756d-44b8-4c05-a870-3e03232b9c74
formfactor=0
immutability=1
lastScreen=1
location=0
plugin=org.kde.plasma.folder
wallpaperplugin=org.kde.image

[Containments][2][Configuration]
PreloadWeight=0

[Containments][3]
activityId=404c756d-44b8-4c05-a870-3e03232b9c74
formfactor=0
immutability=1
lastScreen=2
location=0
plugin=org.kde.plasma.folder
wallpaperplugin=org.kde.image

[Containments][3][Configuration]
PreloadWeight=0

[Containments][3][General]
ToolBoxButtonState=topright
ToolBoxButtonX=1890
pressToMoveHelp=false

[Containments][9][General]
extraItems=org.kde.plasma.devicenotifier,org.kde.plasma.battery,org.kde.plasma.mediacontroller,org.kde.plasma.clipboard,org.kde.plasma.notifications
knownItems=org.kde.plasma.devicenotifier,org.kde.plasma.battery,org.kde.plasma.mediacontroller,org.kde.plasma.clipboard,org.kde.plasma.notifications

[General]
immutability=1

[ScreenMapping]
itemsOnDisabledScreens=
```

I start the session with a special `/usr/share/xsessions/plasma-i3.desktop`, which looks like this:

```
[Desktop Entry]
Name=Plasma-i3
Comment=Plasma with i3-gaps
Exec=/usr/local/sbin/plasma-i3
TryExec=/usr/local/sbin/plasma-i3
Type=Application
X-LightDM-DesktopName=plasma-i3
DesktopNames=plasma-i3
Keywords=tiling;wm;windowmanager;window;manager;
```

And here's my `/usr/local/sbin/plasma-i3`:

```
#!/bin/sh

export KDEWM=/usr/bin/i3
exec /usr/bin/startkde
```

**Comment by patrick96** [comment]
I am going to close this because this isn't polybar's fault.

You can still discuss in here, but I don't want this cluttering up the open issues list.

**Comment by hanschen** [comment]
Recently I've encountered this issue where some system tray icons don't show up in polybar, most noticeably KDE applications. Somewhat ironically I found this thread again when searching for a solution. Although I haven't found a solution yet, I figured I could share a workaround I found.

You can open the Plasma system tray widget in a separate window using the following command:

    plasmawindowed org.kde.plasma.systemtray

Using the i3 window manager, I've added this command to autostart, made the window floating and moved it to the scratchpad. Example:

    for_window [title="System Tray"] floating enable
    for_window [title="System Tray" window_type="normal"] move scratchpad
    bindsym $mod+Shift+s [title="System Tray"] scratchpad show, resize set 64 64, move position center
    exec --no-startup-id "plasmawindowed org.kde.plasma.systemtray"

This way, I can access the system tray using `$mod+Shift+s`.

The issue itself seems to be due to `plasmashell` somehow grabbing the system tray. The polybar system tray works fine in a pure i3 session, but once I run `plasmashell` some system tray icons disappear.
