### ISSUE TITLE
Bar fails to load: background_manager unable to get root pixmap for background

### ISSUE THREAD

**Issue by Stewie410** [jaagr/polybar#1585]
## Describe the Issue
When trying to start polybar (as user or root), polybar fails to load with the following error:
``error: background_manager: Failed to get the root pixmap for background (realloc=<val>)``
``<val>`` Changes on every launch, else I would list it here as well.

I've noticed issue #1582 which may be related.

**Expected behavior:**
Successfully launched bar

**Actual behavior:**
Configuration is loaded with no errors or warnings until the following is stated in the log:
``error: background_manager: Failed to get the root pixmap for background (realloc=<val>)``

At this time, polybar fails to be displayed, but the application itself continues running (hanging).

## To Reproduce
*A minimal but complete config with which the problem **occurs:**
```dosini
; vim:ft=dosini
[xres]
color0 = 				${xrdb:color0:#161616}
color1 =				${xrdb:color1:#A94744}
color2 =				${xrdb:color2:#608B4E}
color3 =				${xrdb:color3:#D69831}
color4 =				${xrdb:color4:#569CD6}
color5 =				${xrdb:color5:#B06386}
color6 =				${xrdb:color6:#218693}
color7 =				${xrdb:color7:#B0B0B0}
color8 =				${xrdb:color8:#3C3C3C}
color9 =				${xrdb:color9:#E09690}
color10 =				${xrdb:color10:#8FBF7F}
color11 =				${xrdb:color11:#F8BC41}
color12 =				${xrdb:color12:#9CDCFE}
color13 =				${xrdb:color13:#D2879B}
color14 =				${xrdb:color14:#77DFD8}
color15 =				${xrdb:color15:#F7F7F7}

[fonts]
fixed = 				        fixed:pixelsize=10;1
unifont = 				unifont:fontformat=true:size=10:antialias=false;0
siji = 					siji:pixelsize=10;1
awesome = 				FontAwesome:fontformat=true:pixelsize=10:antialias=true;1
weather-icons = 			Weather Icons:pixelsize=12;1

[vars]
monitor = 				${env:MONITOR:eDP-1}
width = 				100%
height = 				16
module-padding =			0
tray-padding = 				2
tray-position = 			right
border-size = 				0
line-size = 				0
margin-size = 				1
global-margin-size = 			5
pulse-sink =				alsa_output.pci-0000_00_1f.3.analog-stereo
font-0 = 				${fonts.fixed}
font-1 = 				${fonts.siji}
font-2 = 				${fonts.awesome}
font-3 = 				${fonts.weather-icons}
modules-top-left = 			
modules-top-center = 			xwin
modules-top-right = 			date
background =				${xres.color0}
background-alt = 			${xres.color8}
foreground = 				${xres.color7}
foreground-alt = 			${xres.color15}
border-color = 				${xres.color8}
primary = 				${xres.color4}
secondary = 				${xres.color3}
tertiary = 				${xres.color2}
alert = 				${xres.color1}
alert-alt = 				${xres.color9}

[bar/topbar]
monitor = 				${vars.monitor}
width = 				${vars.width}			
height = 				${vars.height}
fixed-center = 				${vars.true}
bottom =				false
background =				${vars.background}
foreground = 				${vars.foreground}
border-size = 				${vars.border-size}
border-color = 				${vars.border-color}
padding-left = 				${vars.module-padding}
padding-right = 			${vars.module-padding}
tray-padding = 				${vars.tray-padding}
tray-background = 			${vars.background}
tray-position = 			${vars.tray-position}
font-0 = 				${vars.font-0}
font-1 = 				${vars.font-1}
font-2 = 				${vars.font-2}
modules-margin-left = 			${vars.margin-size}
modules-margin-right = 			${vars.margin-size}
modules-left = 				${vars.modules-top-left}
modules-center = 			${vars.modules-top-center}
modules-right = 			${vars.modules-top-right}

[global/wm]
margin-top = 				${vars.global-margin-size}
margin-bottom = 			${vars.global-margin-size}

[settings]
screenchange-reload = 			true

[module/xwin]
type = 					internal/xwindow
format = 				<label>
format-background = 			${vars.background}
format-foreground = 			${vars.foreground}
label = 				%title:0:30:...%

[module/date]
type = 					internal/date
interval = 				1.0
format = 				<label>
format-background = 			${vars.background}
format-foreground = 			${vars.foreground}
label = 				%date% %time%
date = 					
date-alt = 				%Y-%m-%d
time = 					%I:%M %p
time-alt = 				%H:%M:%S

```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*
None, unfortunately.

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
[user@localhost ~]$ polybar topbar
error: background_manager: Failed to get the root pixmap for background (realloc=<val>)
```
## Environment:
* WM: ``i3-gaps 4.16-1``
* Output of `polybar -vvv`:
```
polybar 3.3.0

Features: +alsa +curl +i3 -mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

## Additional context
* Output of `polybar topbar -l info`:
```
* Loading config: /home/alex/.config/polybar/config
* Environment var ${MONITOR} is undefined, using defined fallback valye "eDP-1"
* Loaded monitor eDP-1 (1920x1080+0+0)
* Found matching X resource "color0" (value=#161616)
* Found matching X resource "color7" (value=#b0b0b0)
* Found matching X resource "color8" (value=#3c3c3c)
* Bar geometry = 1920x16+0+0
* Found matching X resource "color7" (value=#b0b0b0)
* Found matching X resource "color0" (value=#161616)
* Found matching X resource "color7" (value=#b0b0b0)
* Found matching X resource "color0" (value=#161616)
* Starting application
* Starting module/xwin
* Starting module/date
* Entering event loop (thread-id=1
* Eventqueue worker (thread-id=4)
* Configured DPI = 96x96
Loaded font "fixed:pixelsize=10" (name=DejaVu Sans, offset=1, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
* Loaded font "siji:pixelsize=10" (name=DejaVu Sans, offset=1, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
* Loaded font "FontAwesome:fontformat=true:pixelsize=10:antialias=true" (name=DejaVu Sans, offset=1, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
error: background_manager: Failed to get the root pixmap for background (realloc=<val>)
```

**Comment by patrick96** [comment]
The `realloc` part of the mesage is something we forgot to remove, we don't actually set its value ever

Same Q for you as over in #1582, did it work before you updated polybar? Or are you installing polybar for the first time on that machine?

**Comment by Stewie410** [comment]
First time install on a fresh installation of Arch.

For reference, if there might be some wonk thing going on with hardware:

**Dell XPS15 9570**
- Intel Core i7-8750H
- 16GB (2x8) DDR4 RAM
- 500GB Samsung 970 EVO (M.2/NVMe) --> Arch is the only OS present
- NVidia GeForce GTX 1050-Ti Max-Q
- 1920x1080 IPS (apparently running over a DP connection, "eDP-1"); **Internal Only**
- No connected external devices

**Comment by patrick96** [comment]
Hmm, can you also try it when using the newest commit (`polybar-git` package).
And could you also run polybar with `-l trace` which gives us some more info as well as the output of `xrandr`.

**Comment by bennofs** [comment]
I am trying to reproduce this, what compositing manager + options are you using (if any) and what are you using to set the desktop background?

**Comment by Stewie410** [comment]
Alright, I've changed over to ``polybar-git`` as requested:

```polybar -vvv:
polybar 3.3.0-11-gb728fea5

Features: +alsa +curl +i3 -mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

Likewise, here's what I'm getting with the ``trace`` log level:

```polybar -l trace topbar
polybar|info:  Loading config: /home/alex/.config/polybar/config
polybar|trace: config: Current bar section: [bar/topbar]
polybar|info:  Environment var ${MONITOR} is undefined, using defined fallback value "eDP-1"
polybar|info:  Loaded monitor eDP-1 (1920x1080+0+0)
polybar|info:  Found matching X resource "color0" (value=#161616)
polybar|info:  Found matching X resource "color7" (value=#b0b0b0)
polybar|info:  Found matching X resource "color8" (value=#3c3c3c)
polybar|info:  Bar geometry: 1920x16+0+0
polybar|trace: bar: Attach X event sink
polybar|trace: bar: Attach signal receiver
polybar|trace: controller: Install signal handler
polybar|trace: controller: Setup user-defined modules
polybar|info:  Found matching X resource "color7" (value=#b0b0b0)
polybar|info:  Found matching X resource "color0" (value=#161616)
polybar|info:  Found matching X resource "color7" (value=#b0b0b0)
polybar|info:  Found matching X resource "color0" (value=#161616)
polybar|info:  Starting application
polybar|trace: controller: Main thread id = 1
polybar|info:  Starting module/xwin
polybar|info:  Starting module/date
polybar|info:  Entering event loop (thread-id=1)
polybar|trace: module/date: Thread id = 2
polybar|info:  Eventqueue worker (thread-id=3)
polybar|trace: bar: Create renderer
polybar|trace: renderer: Get TrueColor visual
polybar|trace: module/xwin: Thread id = 4
polybar|trace: renderer: Allocate colormap
polybar|trace: renderer: Allocate output window
polybar|trace: renderer: Allocate window pixmaps
polybar|trace: renderer: Allocate graphic contexts
polybar|trace: renderer: Allocate alignment blocks
polybar|trace: renderer: Allocate cairo components
polybar|trace: renderer: Load fonts
polybar|info:  Configured DPI = 96x96
polybar|info:  Loaded font "fixed:pixelsize=10" (name=DejaVu Sans, offset=1, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
polybar|info:  Loaded font "siji:pixelsize=10" (name=DejaVu Sans, offset=1, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
polybar|info:  Loaded font "FontAwesome:fontformat=true:pixelsize=10:antialias=true" (name=FontAwesome, offset=1, file=/usr/share/fonts/awesome-terminal-fonts/fontawesome-regular.ttf)
polybar|trace: Activate root background manager
```
After several minutes, I manually stopped polybar, which produced the following:
```polybar|warn:  Termination signal received, shutting down...
polybar|trace: controller: Uninstall sighandler
polybar|trace: controller: Detach signal receiver
polybar|trace: controller: Stop modules
polybar|info:  module/xwin: Stopping
polybar|trace: module/xwin: Release sleep lock
polybar|trace: module/xwin: Deconstructing
polybar|info:  Deconstruction of module/xwin took 0 ms.
polybar|info:  module/date: Stopping
polybar|trace: module/date: Release sleep lock
polybar|trace: module/date: Deconstructing
polybar|info:  Deconstruction of module/date took 0 ms.
polybar|trace: controller: Joining threads
polybar|info:  Waiting for spawned processes to end
polybar|info:  Reached end of application...
```

As for xrandr:

```xrandr
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 8192 x 8192
eDP-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 194mm
   1920x1080     60.00*+  59.97    59.96    59.93  
   1680x1050     59.95    59.88  
   1400x1050     59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     60.02  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1280x800      59.99    59.97    59.81    59.91  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   640x400       59.88    59.98  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
```

I'm no longer receiving the error message -- though, the bar isn't being drawn at all.  Looking into htop, I can see four individual ``polybar -l trace topbar`` processes running -- which, killing polybar kills all four of them; so presumably that's expected in some capacity.

So, on the plus the error message is not longer being displayed -- but the bar still isn't loading/being drawn.

------

As to bennofs' questions:

- I'm not currently using a compositing manager -- ``compton`` is *installed*, but in no way configured or running
- In this case, I'm not setting the desktop background/wallpaper to anything:
![capture_0](https://user-images.githubusercontent.com/24593067/50946894-a2fb2380-1469-11e9-90de-241d6c515a82.png)


This is a very, very fresh install; to say the least.

**Comment by bennofs** [comment]
I can reproduce this error now, by starting an i3 session and not setting any background image. I'll investigate why this happens.

**Comment by bennofs** [comment]
@Stewie410 the current error is due to #1593 (`${vars.true}` is an error, use just `true` instead). If you correct the syntax, do you still have the problem with the background?

**Comment by Stewie410** [comment]
Oh my gosh, I feel like such a *user* -- ``${vars.true}`` wasn't a defined variable -- which is probably where all of this started...though, maybe still a bug?

Anyway, with the "minimal" config posted above:

- Defining ``vars.fixed-center = true``; and referencing it correctly within the bar definition (``${vars.fixed-center}``) draws the bar; however I'm still getting the original error ``Failed to get root pixmap for background (realloc=<num>)``; even though it doesn't appear to be breaking anything.
- Defining ``fixed-center = true`` within the bar definition, rather than using a variable draws the bar; however I'm still getting the original error ``Failed to get root pixmap for background (realloc=<num>)``; even though it doesn't appear to be breaking anything.

With my original config (custom/scripts removed for unrelated reasons (they're so badly written)):

- Defining ``vars.fixed-center = true``; and referencing it correctly within the bar definition (``${vars.fixed-center}``) draws the bar; however I'm still getting the original error ``Failed to get root pixmap for background (realloc=<num>)``; even though it doesn't appear to be breaking anything.
- Definining ``fixed-center = true``  within the bar definition rather than using a variable draws the bar; however I'm still getting the original error ``Failed to get root pixmap for background (realloc=<num>)``; even though it doesn't appear to be breaking anything.
 
I've attached the trace logs from each of the above four scenarios -- there's one additional warning, noting that the systray is already managed -- this is because I've been using i3blocks as a stopgap during the debugging process:
[polybar-full-bool.log](https://github.com/jaagr/polybar/files/2748019/polybar-full-bool.log)
[polybar-full-var.log](https://github.com/jaagr/polybar/files/2748020/polybar-full-var.log)
[polybar-minimal-bool.log](https://github.com/jaagr/polybar/files/2748021/polybar-minimal-bool.log)
[polybar-minimal-var.log](https://github.com/jaagr/polybar/files/2748022/polybar-minimal-var.log)

Likewise, here's a screencap of the bar being drawn correctly, even without a wallpaper, during one of the test runs -- all subsequent runs had no variations in the appears of the bar, beyond what modules were enabled.
![capture_1](https://user-images.githubusercontent.com/24593067/51012770-d94da700-152c-11e9-9cd9-dd289db6852b.png)

While I don't understand what the root pixmap is -- I can deduce not setting a wallpaper at all, nor having another process to define the wallpaper is causing a wrench in that part of polybar.  Knowing now that ``realloc`` isn't a used value; that at least adds some relief.

Here's hoping one day I can take the time to look into c++, so I can hopefully provide some more useful information in future reporting.

---

I'll revert back to v3.3.0 (stable?) and provide details of how that goes tomorrow (approx. 24h from time of post), as well.

I can also provide the full, functional configuration file; should there be something else in there that would help in debugging efforts for #1593, or otherwise.

**Comment by bennofs** [comment]
Thanks for the details! So everything looks to be working correctly, except that you're getting an error message? I think the error in this case is safe to ignore, we should change the severity for that.

**Comment by patrick96** [comment]
@bennofs Is there any other reason why we would get `Failed to get root pixmap for background` except for no background being set?

**Comment by bennofs** [comment]
@patrick96 I have no idea. Probably best to log it with info or trace level and fill the pixmap with black?

**Comment by moonrisewarrior** [comment]
I have recently started getting the same issue (bar is drawn, but the x offsets etc. don't get applied, and I get the error message about the background pixmap) after setting `[global/wm]`'s `margin-bottom` variable to a non-zero value, also on i3. Could this be a possible cause for it?
