### ISSUE TITLE
Ubuntu18.10 build error

### ISSUE THREAD

**Issue by omohikane** [jaagr/polybar#1588]
## Build Process
*Describe how you build polybar, list the exact commands you are using:*
$ sudo apt install cmake cmake-data libcairo2-dev libxcb1-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-randr0-dev libxcb-util0-dev libxcb-xkb-dev pkg-config python-xcbgen xcb-proto libxcb-xrm-dev i3-wm libasound2-dev libmpdclient-dev libiw-dev libcurl4-openssl-dev libpulse-dev
$git clone https://github.com/jaagr/polybar.git
$cd polybar && ./build.sh

**If you build polybar directly from this repository:**

* Output of `git describe --tags`:3.3.0-2-g7256366

**If you use some other way (like the AUR):**

*List exactly where you are building from and which version you are building.*

## Build Log
*Post everything that is output to the terminal while building polybar below. This HAS to include the output of the `cmake` and `make` commands, if you used them.*
```
sudo ./build.sh 
** Fetching submodules

** A build dir already exists (pass -f to replace)

** Setting build options

** Use GCC even if Clang is installed ----------------------------- [y/N]: y
** Include support for "internal/i3" (requires i3) ---------------- [y/N]: y
** Include support for "internal/alsa" (requires alsalib) --------- [y/N]: y
** Include support for "internal/pulseaudio" (requires libpulse) -- [y/N]: y
** Include support for "internal/network" (requires libnl/libiw) -- [y/N]: y
** Include support for "internal/mpd" (requires libmpdclient) ----- [y/N]: y
** Include support for "internal/github" (requires libcurl) ------- [y/N]: y
** Build "polybar-msg" used to send ipc messages ------------------ [y/N]: y
** Executing cmake command

-- Trying to enable ccache
-- Couldn't locate ccache, disabling ccache...
-- No build type specified; using RelWithDebInfo
-- Using supported compiler GNU-8.2.0
-- Checking for module 'xcb-composite'
--   No package 'xcb-composite' found
CMake Error at /usr/share/cmake-3.12/Modules/FindPkgConfig.cmake:436 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.12/Modules/FindPkgConfig.cmake:602 (_pkg_check_modules_internal)
  cmake/common/utils.cmake:95 (pkg_check_modules)
  cmake/03-libs.cmake:20 (querylib)
  CMakeLists.txt:34 (include)


-- Configuring incomplete, errors occurred!

```

## Environment:
* Distro (with Version):4.18.0-13-generic #14-Ubuntu  18.10

## Additional context
*Add any other context that you think is necessary about the problem here.*

**Comment by The-Twisted-Samurai** [comment]
You don't have a required package, apparently Have you installed all the hard dependencies for polybar and the optional ones from [here](https://github.com/jaagr/polybar/wiki/Compiling)?

**Comment by patrick96** [comment]
Yep, as @The-Twisted-Samurai said, you're missing the `libxcb-composite0-dev` package.

**Comment by darkristy** [comment]
Thank you kind sir

**Comment by greekbookhero** [comment]
thx solved my ploblem)
