### ISSUE TITLE
Integer %mb_used% value in memory widget instead of floating point value

### ISSUE THREAD

**Issue by gvlasov** [jaagr/polybar#1598]
## Is your feature request related to a problem? Please describe.
Hundredths of a megabyte is excessive precision I don't care about, and it takes up some space on the polybar.

## Why does polybar need this feature?
I don't see any reason to display floating point values for megabytes of RAM rather than integer values. At least would be nice to have a way to do so.

## Describe the solution you'd like
Use integer value for %mb_used%. For those who like decimal values, introduce %mb_used_decimal% or %mb_used_float%.

## Describe alternatives you've considered
Not caring about memory display. Didn't work.

## Additional context
None

**Comment by patrick96** [comment]
Hi. This feature was already requested in #1063 but not yet implemented. My idea for this was to have printf style modifiers to control the floating point behavior.

**Comment by gvlasov** [comment]
@gvlasov My suggestion is quite different. #1063 is about custom formatting. What I suggest is to just use only whole megabytes currently with %mb_used% directve. Because it is just plain better than decimal with two digits after a point. I guess none (or maybe a tiniest minority) of polybar users care about whether they have 4000 mb or 4000.45 mb or RAM used. Fully custom formatting can be added later.

**Comment by patrick96** [comment]
Both this and #1063 ask for the ability to remove the decimal places from the memory module. But fair enough, no one is going to need that precision with megabytes, I will open a PR.

When we introduce more comprehensive formatting for tokens we'll need to deprecate all these size specific tokens anyway.
