### ISSUE TITLE
Manage the sound level of a distant mpd instance

### ISSUE THREAD

**Issue by Spheerys** [jaagr/polybar#1601]
I have a mpd server on a raspberry pi and I manage it from polybar on my main computer without problem.
But I also want to manage the volume level of this distant mpd from polybar.
I already have a alsa module, but it's obviously managing the local sound level, not the mpd one's...

Any idea ?

**Comment by patrick96** [comment]
Interesting use case. I think you can connect to pulseaudio over the network: [ArchWiki](https://wiki.archlinux.org/index.php/PulseAudio/Examples#PulseAudio_over_network), and maybe that exposes a new sink that polybar can use. Don't know about alsa.

The mpd module doesn't support viewing or controling mpd's volume, but you can rig something with mpc:

```dosini
[module/mpd-vol]
type = custom/script
exec = mpc --host HOST -p PORT volume
scroll-up = mpc --host HOST -p PORT volume +5
scroll-down = mpc --host HOST -p PORT volume -5
```

**Comment by Spheerys** [comment]
Good idea ! I will try this :)
I think it will be difficult to have a visual ramp, but I with an icon it could be enough for the purpose :)

**Comment by patrick96** [comment]
For a ramp you'll definitely need to write a dedicated script. Something I used in my scripts for ramps is the following:
```bash
level=$((curVol / $((100 / VOLUME_RAMP_NUM))))
if [ "$level" -ge "$VOLUME_RAMP_NUM" ]; then
    level=$((VOLUME_RAMP_NUM - 1))
fi
name="VOLUME$level"
icon=${!name}
```

Where `curVol` is the volume in percent, `VOLUME_RAMP_NUM` the number of volume icons you have `VOLUME0`, `VOLUME1` ... are the actual icons for the different ramps.

**Comment by Spheerys** [comment]
Thanks !
