### ISSUE TITLE
polybar fails to load

### ISSUE THREAD

**Issue by andersfylling** [jaagr/polybar#1607]
## Describe the issue
executing `polybar example` in the terminal fails with the error: `polybar: error while loading shared libraries: libjsoncpp.so.20: cannot open shared object file: No such file or directory`

**Expected behavior:**
The polyboar loads the example configuration.

**Actual behavior:**
I get the error mentioned above, and nothing else.

**Was it working before?**
Just installed polybar 3.3.0 from AUR.

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
➜ polybar example
polybar: error while loading shared libraries: libjsoncpp.so.20: cannot open shared object file: No such file or directory
```

## Environment:
* OS: `arch linux 4.19.13-1-lts`
* WM: `i3 4.16, with gaps 4.16-1`
* Output of `polybar -vvv`: `polybar: error while loading shared libraries: libjsoncpp.so.20: cannot open shared object file: No such file or directory`

**Comment by patrick96** [comment]
See [Known-Issues](https://github.com/jaagr/polybar/wiki/Known-Issues#error-while-loading-shared-libraries-libjsoncpp)
