### ISSUE TITLE
caffeine script produces wrong output and eventually freezes polybar

### ISSUE THREAD

**Issue by Jamie-505** [jaagr/polybar#1613]
## Describe the issue
I'm trying to use a custom script to serve as an indicator of [caffeine-ng](https://github.com/caffeine-ng/caffeine-ng) but the output in polybar seems to be random. It sometimes switches every second without me interacting with it. I have a multi-monitor setup which both use the same bar but even the two are often not in sync (One displays a different output for the caffeine-module than the other) but the issue also happens when I'm using a single monitor.

**Expected behavior:**
when caffeine-ng is running the output should be:  (steaming coffee)
when caffeine-ng is running the output should be:  (coffee cup without steam)
when clicking on the icon caffeine should either be started if not already running or killed if running

**Actual behavior:**
Caffeine toggle works but the state is not reflected in the bar. Sometimes it reflects the change once but freezes afterwards or it doesn't change at all.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
run this config together with the caffeine script and click on the caffeine icon to toggle the caffeine state

**~/.config/polybar/conf**
```dosini
;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/jaagr/polybar
;
;   The README contains alot of information
;
;==========================================================

[bar/white]
;------------;
; DIMENSIONS ;
;------------;
width = 100%
height = 20
offset-y = 0
offset-x = 0

border-top-size = 10
border-bottom-size = 0
border-right-size = 10
border-left-size = 10

;----------;
; LOCATION ;
;----------;
bottom = true
override-redirect = false

;-------;
; FONTS ;
;-------;
font-0 = xft:Droid Sans Mono:size=10;3
font-1 = "Font Awesome 5 Free:style=Solid:pixelsize=10;3"
font-2 = "Font Awesome 5 Free:style=Regular:pixelsize=10;3"
font-3 = "Font Awesome 5 Brands:pixelsize=10;3"

;--------;
; COLORS ;
;--------;
background = 0
foreground = #c5a9f9
border-color = 0

;---------------;
; MISCELLANEOUS ;
;---------------;
fixed-center = true
padding-left = 2
padding-right = 2
module-margin = 1.5
modules-center = caffeine

;---------;
; MODULES ;
;---------;

[module/caffeine]
type = custom/script
tail = true
exec = ~/.config/polybar/scripts/coffee.sh
; Click Events for Caffeine
click-left = ~/.config/polybar/scripts/coffee.sh -t
```
**~/.config/polybar/scripts/coffee.sh**
```sh
#!/bin/bash
#
# Show caffeine status

coffee=$(pgrep -f caffeine)

if [ -z "$coffee" ]; then
	echo "  "
else
	echo "  "
fi

case "$1" in
	-t)
		if [ -z "$coffee" ]; then
			caffeine -a
		else
			caffeine kill
		fi
		;;
	*)
esac
```

*caffeine-ng needs to be installed and font awesome is needed to display the icon. The script for the caffeine module needs to be placed in ~./config/polybar/scripts/coffee.sh and made executable*

*run polybar white*

## Polybar Log
no output except for the warning that no monitor was specified

## Screenshots
how it should look when caffeine is running
![image](https://user-images.githubusercontent.com/8363431/51349797-bc722000-1aa6-11e9-81d7-ea4d7d8648fb.png)
how it should look when caffeine is not running
![image](https://user-images.githubusercontent.com/8363431/51349828-de6ba280-1aa6-11e9-9930-8b888fe53080.png)

## Environment:
![image](https://user-images.githubusercontent.com/8363431/51349757-90569f00-1aa6-11e9-9c23-8c621e21bbb5.png)

* WM: i3
* Output of `polybar -vvv`:
```
polybar 3.3.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment]
I suggest setting `trail = false`, because with `trail = true` polybar expects the script to produce output continuously.

On my machine I noticed that toggling doesn't work and displaying the state works properly (even with tailing enabled). The issue is that when executing the click action, polybar waits for the command to return, but `caffeine-ng -a` doesn't terminate, it keeps on running. The way I fixed it was to change the script by adding `&` to the `caffeine -a` command: `caffeine -a &`.

This will put the program in the background and polybar can continue normally.

For the future, this isn't really the place to ask for help debugging your scripts, a better place would be [reddit](https://www.reddit.com/r/polybar)
