### ISSUE TITLE
Capture error messages when running inside i3

### ISSUE THREAD

**Issue by sheijk** [jaagr/polybar#1614]
## Is your feature request related to a problem? Please describe.
Given a broken config file the error messages about it printed by polybar seem to not get caught inside i3's log.

Using this little module (missing the ramp-used-N items) to reproduce an error and adding it to modules-right:
> [module/memory]
> type = internal/memory
> format = <label> <ramp-used>

If I'm starting this in a shell I see the following error message:

> error: Disabling module "memory" (reason: Missing parameter "module/memory.ramp-used-0")

I've enabled shmlog and print the log using i3-dump-log but I do not see the above error message or anything related at all.

## Describe the solution you'd like
Seeing the error message in i3 log would be nice. I'm not sure this has to be changes in i3 or polybar. Alternatively it might be worth considering not just hiding modules which failed but showing a small indicator that something went wrong in their place

**Comment by patrick96** [comment]
I don't think i3 supports capturing the output of `exec` scripts and there isn't anything polybar can do about that. Even for debugging i3's own i3bar, they suggest redirecting the output to a logfile: https://i3wm.org/docs/debugging.html#_debugging_i3bar.

That's also how I start my bar, by running `polybar top >/path/to/log/file.log 2>&1`
