### ISSUE TITLE
Compatibility with Xephyr

### ISSUE THREAD

**Issue by NBonaparte** [jaagr/polybar#1616]
This is a fairly low-priority issue, but it would be nice if polybar launched correctly with Xephyr displays. Rather than having to re-login into a different wm for testing, for example, another X display can be launched from within the current X server.

Currently it seems rendering isn't working properly as the window is black without compton, and completely empty with compton.
With the `i3-icons` branch it crashes with `XCB_RANDR_BAD_OUTPUT (147)` for some reason.

**Comment by patrick96** [comment]
I actually don't have any issues running polybar (`polybar 3.3.0-18-gf74c524f`) in Xephyr with or without compton. Does it also crash in the master branch for you?

**Comment by patrick96** [comment]
Not really, only `Xephyr -screen 1920x1080 :1`
