### ISSUE TITLE
HOW TO ADD CLICK-LEFT TO WIRELESS-NETWORK MODULE ?

### ISSUE THREAD

**Issue by rusmelezi** [jaagr/polybar#1617]
I wrote down a script for monitoring and connecting to a wifi network I want to add click-left option for wireless-network module to execute that script, how should I edit this module to add click-left option ?

**Comment by patrick96** [comment]
This has been asked before, see https://github.com/jaagr/polybar/issues/273#issuecomment-270056088. The trick is to wrap the entire label or format in an [action tag](https://github.com/jaagr/polybar/wiki/Formatting#action-a). Polybar will wait for the click script to finish, so make sure to add `&` to the command to put it in the background.
