### ISSUE TITLE
There is no information on the panel, only the background

### ISSUE THREAD

**Issue by xxxvik-xakerxxx** [jaagr/polybar#1618]
Debian 9.6 and polybar compiled from sources, all fonts are installed, there are no errors at startup, but the panel does not display information WM = i3-gaps
 
![6](https://user-images.githubusercontent.com/19531907/51604459-8b19aa00-1f15-11e9-9fc0-9e83f898048a.jpg)
![5](https://user-images.githubusercontent.com/19531907/51604480-9a005c80-1f15-11e9-83a6-1194749d83fd.jpg)

 Config https://gist.github.com/xxxvik-xakerxxx/0704865295773883f1b161a9f86d93e9#file-polybar-conf

**Comment by patrick96** [comment]
Please post your config, we can't help you otherwise

**Comment by xxxvik-xakerxxx** [comment]
@patrick96 add config file

**Comment by patrick96** [comment]
Try to remove the `pixelsize` property from all the fonts, we had issues with that on debian systems

**Comment by xxxvik-xakerxxx** [comment]
@patrick96 helped thanks
