### ISSUE TITLE
XCB_RANDR_BAD_OUTPUT when attemping to run polybar

### ISSUE THREAD

**Issue by eadwu** [jaagr/polybar#1620]
## Describe the issue
*A clear and concise description of what the bug is.*
```
Jan 23 09:06:09 nixos polybar-start[2926]: polybar|error: XCB_RANDR_BAD_OUTPUT (147)
```
**Expected behavior:**

*A clear and concise description of what you expected to happen.*
Text to be outputted to stdout, like `}[  Wed Jan 23 ][  09:17 AM ]`.

**Actual behavior:**

*What actually happens*
`error: XCB_RANDR_BAD_OUTPUT` with nothing outputted to stdout.

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar?
* If no, what was the last version where this worked correctly?
Latest revision built is 46b8bb84edce683e75672b2c0c9ff58cfb3f9f68 before 1145681cf5f0fd6b1c977ae55fa61213a91525bb.

Just built b03f14400ae840f1b1057a4b9db2c3fbfe43a905 and it seems like it still works, so 1145681cf5f0fd6b1c977ae55fa61213a91525bb might be the problem?

## To Reproduce
*A minimal but complete config with which the problem occurs:*
Basically any configuration but I'll remove all modules besides one from mine.
```dosini
[bar/data]
enable-ipc=true
modules-right=temperature0

[section/temperature]
format=[ <ramp> <label> ]
format-warn=[ <ramp> <label-warn> ]
interval=1
ramp-0=
ramp-1=
ramp-2=
ramp-3=
ramp-4=
thermal-zone=0
type=internal/temperature
warn-temperature=80

[module/temperature0]
hwmon-path=/sys/devices/platform/coretemp.0/hwmon/hwmon0/temp1_input
inherit=section/temperature
```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

Tested via `polybar -r -s data` and via my systemd service which runs
```bash
#!/nix/store/i82x3x0yiijkgyqkzh8ni87gspas0f48-bash-4.4-p23/bin/bash

/nix/store/gz0ybzf9rydmrmghvgfm3r8ywxsrdw77-polybar-3.3.0/bin/polybar -r -s data | \
  while IFS= read -r line;
  do
    /nix/store/ljfgwr4d3va82xjjrlisw1qwfb7pk4l8-xsetroot-1.1.2/bin/xsetroot -name "$(printf "%s" "$line" | \
      /nix/store/hp6bsml2b0vzxd2y8vwz060m8w373bd7-perl-5.28.1/bin/perl -pe 's/%\{.+?\}//g')";
  done &
```

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
Jan 23 09:06:09 nixos polybar-start[2926]: polybar|error: XCB_RANDR_BAD_OUTPUT (147)
```

## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM: dwm
* Output of `polybar -vvv`:
```
polybar 3.3.0

Features: +alsa +curl -i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: Release
Compiler: gcc-wrapper-7.4.0/bin/g++
Compiler flags:  -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags:
```
## Additional context
*Add any other context that you think is necessary about the problem here.*

**Comment by patrick96** [comment]
Yep the PR #1426 is probably the issue. We slightly changed the semantics of not specifying a monitor. Before it meant, use the first monitor you find and now it means, use the primary monitor. I suspect that polybar picks up some bogus primary monitor and tries to use that. Could you please post the output of `polybar -m` and `xrandr`

**Comment by eadwu** [comment]
`polybar -m`
```
polybar|error: XCB_RANDR_BAD_OUTPUT (147)
```

`xrandr`
```
Screen 0: minimum 8 x 8, current 3840 x 2160, maximum 32767 x 32767
eDP-1-1 connected 3840x2160+0+0 (normal left inverted right x axis y axis) 344mm x 194mm
   3840x2160     60.00*+  59.98    59.97  
   3200x1800     59.96    59.94  
   2880x1620     59.96    59.97  
   2560x1600     59.99    59.97  
   2560x1440     59.99    59.99    59.96    59.95  
   2048x1536     60.00  
   1920x1440     60.00  
   1856x1392     60.01  
   1792x1344     60.01  
   2048x1152     59.99    59.98    59.90    59.91  
   1920x1200     59.88    59.95  
   1920x1080     60.01    59.97    59.96    59.93  
   1600x1200     60.00  
   1680x1050     59.95    59.88  
   1400x1050     59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     60.02  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1280x800      59.99    59.97    59.81    59.91  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   640x400       59.88    59.98  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
DP-1-1 disconnected (normal left inverted right x axis y axis)
DP-1-2 disconnected (normal left inverted right x axis y axis)
DP-1-3 disconnected (normal left inverted right x axis y axis)
```

**Comment by patrick96** [comment]
Oh, so the crash happens earlier than I thought. Not when connecting to the monitor but probably already when gathering them.Can you run `polybar -l trace -m` and post the output of that, it should give us some more info about where the error happens

**Comment by eadwu** [comment]
```
➜ result/bin/polybar -r -s data -l trace -m
error: XCB_RANDR_BAD_OUTPUT (147)
* Waiting for spawned processes to end
* Reached end of application...
```

**Comment by eadwu** [comment]
Just built `polybar` off master with the patch and can verify that it works again, or at least using `polybar -r -s data`.
