### ISSUE TITLE
Linking problem undef reference 'xcb_prefetch_maximum_request_length'

### ISSUE THREAD

**Issue by jubalh** [jaagr/polybar#1628]
It seems when I compile polybar with `CMAKE_EXE_LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now"`
The build aborts with:

```
libpoly.a(bar.cpp.o): undefined reference to symbol 'xcb_prefetch_maximum_request_length'
```

## Build Process

Using 3.3.0 [tarball](https://github.com/jaagr/polybar/releases/download/3.3.0/polybar-3.3.0.tar).

We have a general cmake macro which expands to:
```
    find . -name CMakeLists.txt \
        -exec sed -i -re '/^[[:blank:]]*[sS][eE][tT][[:blank:]]*\([[:blank:]]*(CMAKE_BUILD_TYPE|CMAKE_COLOR_MAKEFILE|CMAKE_INSTALL_PREFIX|CMAKE_VERBOSE_MAKEFILE).*\)/{s/^/#IGNORE /}' {} + 
    mkdir -p build 
    cd build 
    /usr/bin/cmake $OLDPWD/. \
%if "/usr/bin/make" == "/usr/bin/make" 
        -G"Unix Makefiles" \
%else 
        -GNinja \
%endif 
        -DCMAKE_INSTALL_PREFIX:PATH=/usr \
        -DINCLUDE_INSTALL_DIR:PATH=/usr/include \
        -DLIB_INSTALL_DIR:PATH=/usr/lib64 \
        -DSYSCONF_INSTALL_DIR:PATH=/etc \
        -DSHARE_INSTALL_PREFIX:PATH=/usr/share \
        -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DCMAKE_C_FLAGS="${CFLAGS:--O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables} -DNDEBUG" \
        -DCMAKE_CXX_FLAGS="${CXXFLAGS:--O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables} -DNDEBUG" \
        -DCMAKE_Fortran_FLAGS="${FFLAGS:--O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables} -DNDEBUG" \
        -DCMAKE_EXE_LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now" \
        -DCMAKE_MODULE_LINKER_FLAGS="-Wl,--as-needed" \
        -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now" \
%if "lib64" == "lib64" 
        -DLIB_SUFFIX=64 \
%endif 
        -DCMAKE_SKIP_RPATH:BOOL=ON \
        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
        -DBUILD_SHARED_LIBS:BOOL=ON \
        -DBUILD_STATIC_LIBS:BOOL=OFF \
        -DCMAKE_COLOR_MAKEFILE:BOOL=OFF \
        -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF \
        -DCMAKE_MODULES_INSTALL_DIR=/usr/share/cmake/Modules
```

After that:

```
make
make install
```

but we don't get to that.

## Build Log
Complete build log can be found [here](https://build.opensuse.org/package/live_build_log/home:jubalh:branches:home:sysek/polybar/openSUSE_Tumbleweed/x86_64)

## Environment:
openSUSE Tumbleweed OBS

## Additional context
I'm in the process to update syseks spec file so polybar can become part of the official distribution. All building happens in the OpenBuildSystem.
I tried to explain the steps taken above independent of the OBS.

The modified spec file can be seen [here](https://build.opensuse.org/package/view_file/home:jubalh:branches:home:sysek/polybar/polybar.spec?expand=1)

sysek's spec file calls, `mkdir build; cd build; cmake ..` which builds find fine.
To get polybar into official devel repositories and then into the distro we should use the macros. My guess is that `CMAKE_EXE_LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now` create trouble. Maybe something isn't defined in the CMakeList.txt, like `-lxcb` might be missing.

The diff between his package and my attempt to clean it up can be seen [here](https://build.opensuse.org/package/rdiff/home:jubalh:branches:home:sysek/polybar?opackage=polybar&oproject=home%3Asysek&rev=5)

**Comment by patrick96** [comment]
Alright, was finally able to track down the issue. The issue is the `-DBUILD_SHARED_LIBS:BOOL=ON` setting. This messes up how the `xpp` submodule is built because it's now built as a shared library (before it was static). I'm able to fix this on our end inside the xpp submodule by explicitly specifying the library type but it will be a while until that gets into a release (the PR needs to be merged into the submodule repo and then we need a PR to update the submodule reference and we need to create a new release), but we should be able to get it into 3.3.1 or 3.3.2. Until then, if `-DBUILD_SHARED_LIBS:BOOL=ON` is not strictly necessary, consider dropping it for the build.

**Comment by jubalh** [comment]
Thanks. I created a [submit request](https://build.opensuse.org/request/show/668987) to syseks home with a patch that contains your fix.

**Comment by jubalh** [comment]
Thanks. I created a [submit request](https://build.opensuse.org/request/show/668987) to syseks home with a patch that contains your fix.

**Comment by patrick96** [comment]
Awesome, I hope this gets into the official repos :)
