### ISSUE TITLE
Dropping unmatched characters (and other issues)

### ISSUE THREAD

**Issue by thurmantruong** [jaagr/polybar#1632]
## Build Process
*Describe how you build polybar, list the exact commands you are using:*

Default config file with the following adjustments:
```
font-0 = Font Awesome 5 Free:style=Regular
font-1 = Noto Sans Symbols2:style=Regular
font-2 = Nimbus Sans:style=Regular
font-3 = Bitstream Vera Sans:style=Roman
font-4 = Material Icons:style=Regular
```

*List exactly where you are building from and which version you are building.*
Installed polybar from the Arch Repository

## Build Log
*Post everything that is output to the terminal while building polybar below. This HAS to include the output of the `cmake` and `make` commands, if you used them.*

Output of `polybar -l info example`
```
warn: No monitor specified, using "eDP1"
error: Disabling module "bspwm" (reason: Could not find socket: /tmp/bspwm_0_0-socket)
error: module/mpd: Connection refused
warn: pulseaudio: using default sink alsa_output.pci-0000_00_1b.0.analog-stereo
error: Disabling module "wlan" (reason: Invalid network interface "net1")
error: Disabling module "eth" (reason: Invalid network interface "eno1")
error: tray: Failed to put tray above 0x3800003 in the stack (XCB_MATCH (8))  
warn: Systray selection already managed (window=0x0c0000c)

warn: Dropping unmatched character  (U+e202)
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
```

## Environment:
Manjaro Linux

## Additional context
I've been trying to get the default polybar up and running for the past few days now to no avail. To fix the font issues, I used gucharmap to determine the base fonts and added them to the config. These remaining issues however (primarily the fonts) have persisted despite putting in the 'Bitstream Vera Sans' as a font. Thought I could figure it out myself, but it seems I've hit a wall. Any help would be appreciated!

**Comment by patrick96** [comment]
Those unmatched characters are not from any of the fonts you listed, they're from siji.
