### ISSUE TITLE
Wiki page possibly outdated (default interval value)

### ISSUE THREAD

**Issue by iamdiogo** [jaagr/polybar#1635]
I was looking around the wiki page regarding the creation of custom scripts (https://github.com/jaagr/polybar/wiki/Module:-script) and noticed that, inside the section *Basic settings*, exists a comment saying that the default interval value is 2.

I tried a basic printing of the current time, without any interval value defined, and observed that the time updates every 5 seconds, instead of 2.

Could it be outdated?

**Comment by patrick96** [comment]
Thanks for pointing this out. I just checked the code and it has always been 5 seconds. I fixed the wiki page
