### ISSUE TITLE
Custom script always into else-statement when executed from Polybar

### ISSUE THREAD

**Issue by TomaLars** [jaagr/polybar#1641]
## Script has if-statement always false when launched from Polybar
I have written a simple script that runs correctly when I launch it from the terminal but when I run it from Polybar through the click-* command it only goes into the else-statement. The if-statement results always false.
I am a newbie for what concerns shell scripting but I have checked and debugged the code several times and I cannot find the issue. Please have a look and let me know.

Polybar 3.3.0 on Manjaro with i3-gaps

Here a portion of the Polybar config file
```dosini
[module/firewall]
type = custom/script
exec = $HOME/.config/polybar/firewall_icon.sh 
interval = 1
click-left = $HOME/.config/polybar/firewall.sh
format-background = ${colors.bg}
format-foreground = ${colors.cyan}
```

And here the script firewall.sh
```dosini
#!/bin/sh
if [ "$( sudo ufw status | grep -wi status | awk '{print $2}' )" = "active" ]; then
    urxvt -e sudo ufw disable
    echo "echo " > "$HOME"/.config/polybar/firewall_icon.sh
else
    urxvt -e sudo ufw enable
    echo "echo " > "$HOME"/.config/polybar/firewall_icon.sh
fi
```

**Expected behavior:**

If the firewall has its status active it is then turned off.
If the firewall has its status inactive it is then turned on.
The command needs sudo privileges.

**Actual behavior:**
When the code is launched from Polybar the if-statement results always false and the firewall is only turned on.

**Comment by patrick96** [comment]
You use `sudo` in your script. `sudo` has no way to get a password from you when running it from polybar. That's likely the issue

**Comment by guygastineau** [comment]
You can configure the `sudoers` file to allow password essentially invocation of `ufw`.
This will allow all of the sudo commands in your script to run in a non-interactive shell.

I am surprised that your test statement works at all when you use `=` instead of `==` to test the equivalence of strings.  Maybe that was a typo copying your file to your comment?

I would actually suggest that you run the process substitution that is in your test before the test, and you can stuff it in a variable.

It would look like:
``` bash
readonly fw_status="$( sudo utw status | grep -wi status | awk '{print $2}' )"
If [ "$fw_status" == 'active' ]; then
# your code here
else
# other code here
fi
```

Finally, I am not sure why you pass the `ufw <enable/disable>` commands through a new instance of your terminal program.
Is that to avoid the output of the commands?
If so, you can redirect the output from those commands to dev null with `&>/dev/null`.

Let me know if this helped., Or if you have any questions.  I teach bash, and I am willing to help you refactor this script.

**Comment by patrick96** [comment]
Thanks @guygastineau!

I will close this, as it seems everything has been said.

By the way `=` for string comparison is the way to go when using `[ .. ]` (see `man test`). You can use `==` in the bash extension `[[ .. ]]` though (`=` works there too).

**Comment by guygastineau** [comment]
I see. I have used `==` for so long, and `=` is almost always exclusively an assignment operator in other languages.  I forgot and assumed ;)

By the way, is this for older/lighter shells, or is /bin/sh a symbolic link for /bin/bash on your system?

**Comment by patrick96** [comment]
On my system `sh` is symlinked to `bash`, yes. But `[` is POSIX, so it should be supported in any compliant shell. Even more interesting `[` is a built-in in most shells, but there exists an executable `/usr/bin/[` which has the same behavior.

**Comment by guygastineau** [comment]
You are right. `[` is also synonymous with `test` I believe.

Well, good luck with positive.  My personal opinion is, if you are just making scripts for yourself then use bash if it is what your system has.  If you really need the portability for getting it to a broader audience, then I get it.

I say that without judgement.  I just really hate making tools that can run on `sh` and `dash`.  I respect those lighter shells for their speed, but for higher level custom scripts I really need the extra builtins from bash 4.x - like associative arrays (or arrays in general).

Have a good day ;)

**Comment by patrick96** [comment]
Curiously, on my system `[` is not symlinked to `test` or vice-versa.

I try to use bash as well, but I generally use `[` just because I can quickly get the manpage for it ;)

**Comment by guygastineau** [comment]
Interesting. There may be a change of which I was unaware.

I used `[` for a long time with bash too.
Then when I had to do some messy regex tests I fell in love with `[[` now I even like `||` and `&&` inside the braces too.

BTW, if you like working in shell you should check out the bash track at exercism.io.  You can login with your GitHub account, and you don't have to remember new credentials.

**Comment by patrick96** [comment]
That's cool, I'll check it out.
