### ISSUE TITLE
Bar filling from right to left

### ISSUE THREAD

**Issue by Mladia** [jaagr/polybar#1649]
I'd like to have my module's progress bar to be able to fill from right to left (as apposed only from left to right). 

This is part of my current config
> [bar/example]
modules-center = memory time cpu 
.
.
[module/memory]
type = internal/memory
format = \<bar-used\>
.
.
[module/cpu]
type = internal/cpu
format = \<bar-used\>
.
.
>
![polybar-progressbar](https://user-images.githubusercontent.com/15912404/52522909-9a298780-2c8b-11e9-8394-c5d746a530b7.png)
With this new feature, there will be symmetry between the memory and cpu bar on the two sides of the time module (in my case)

**Comment by patrick96** [comment]
You can already arange the different elements of the progressbar yourself, see the [Progressbar section](https://github.com/jaagr/polybar/wiki/Formatting#progressbar) on the wiki.

In your case, you could set `bar-used-format = %empty%%indicator%%fill%`
