### ISSUE TITLE
Power off icon can't be clicked, and font looks weired

### ISSUE THREAD

**Issue by akirakanano** [jaagr/polybar#1654]
## Describe the issue
*A clear and concise description of what the bug is.*

Apologize as I feel this might not be a bug. But after searching issue, reading doc (https://github.com/jaagr/polybar/blob/master/SUPPORT.md), and so on, I don't find forum, or irc like place for asking question. So report it here. 

I followed the step https://github.com/jaagr/polybar/issues/392#issuecomment-444688869 for fixing unmatched character problems. After configuring with command `dpkg-reconfigure fontconfig-config`, two issues raises. 

1. The font now looks without anti-alias (https://imgur.com/a/uZK7cDo). Original font (before configuring with siji font) looks smoother. 
2. Clicking power off icon (then click `power off` string again) displayed on polybar (https://imgur.com/a/oJA4Sl2) doesn't shutdown laptop, it just returns back to display power off icon. 

**Expected behavior:**
1. When clicking power off icon, I expect to turn off laptop
2. Font should  be displayed smoother even with siji  configured. 

*A clear and concise description of what you expected to happen.*

**Actual behavior:**
1. Clicking power off icon, polybar simply displays power off icon again.
2. Font looks like without anti-alias 

*What actually happens*
1. Clicking power off icon, polybar simply displays power off icon again.
2. Font looks like without anti-alias 

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar? 
Didn't correctly configure polybar previously with siji font. 
* If no, what was the last version where this worked correctly?
N/A 
## To Reproduce
1. git clone polybar repos
2. run  ./build.sh
3. follow https://github.com/jaagr/polybar/issues/392#issuecomment-444688869 executing related commands 

*A minimal but complete config with which the problem occurs:*
```dosini
# config setting is nearly the same as default one except the following custom ones.  

# Pulse Audio controls
bindsym XF86AudioRaiseVolume exec pactl set-sink-volume 0 +5% #increase sound volume
bindsym XF86AudioLowerVolume exec pactl set-sink-volume 0 -5% #decrease sound volume
bindsym XF86AudioMute exec pactl set-sink-mute 0 toggle # mute sound

# sys tray
exec_always --no-startup-id volumeicon
exec_always --no-startup-id nm-applet
exec_always --no-startup-id xfce4-power-manager
#exec_always --no-startup-id light-locker
exec --no-startup-id feh --bg-scale /usr/share/backgrounds/gnome/Road.jpg
# launch polybar
exec_always --no-startup-id /home/jason/.config/polybar/launch

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
#bar {
#        status_command i3status
#}

```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
error: Disabling module "bspwm" (reason: Could not find socket: /tmp/bspwm_0_0-socket)
error: module/xbacklight: Could not get data (err: XCB_NAME (15))
error: Disabling module "xbacklight" (reason: Not supported for "eDP-1")
warn: pulseaudio: using default sink alsa_output.pci-0000_00_1f.3.analog-stereo

```

## Screenshots
*If applicable, add screenshots to help explain your problem.*
1. https://imgur.com/a/uZK7cDo
2. https://imgur.com/a/oJA4Sl2
## Environment:
* WM: i3 
* Output of `polybar -vvv`:
```
polybar 3.3.0-26-gf148f16

Features: +alsa +curl +i3 +mpd +network(wireless-tools) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/g++
Compiler flags:  -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: 
```
## Additional context
*Add any other context that you think is necessary about the problem here.*
N/A

**Comment by jstamant** [comment]
I'm sure this is a polybar configuration issue, and/or an issue of your system not matching your font properly. I'm pretty sure we can rule out your window manager entirely.

I think we need your configuration. I take it you're using the menu module? What command is your power-off menu-item executing?

**Comment by patrick96** [comment]
The point about smooth fonts looks to me like your system (or at least your browser) now uses a bitmap font as the default font. This seems completely unrelated to polybar on its own, right? I think this can be solved by properly setting default fonts for your browser or whatever toolkit your browser uses for rendering (gtk or qt most likely).

The issue with poweroff is most likely that the command you set for that button is not executed properly. If you are using the sample config, this could be because `sudo poweroff` is used and requires a password (which you have no way to type). This can be solved by changing this to a command that turns of the computer without requiring a password. Simply `poweroff` could work. The other way of solving it is to explicitly make `sudo poweroff` not require a password (see [here](https://askubuntu.com/a/168885/454032)). To confirm this is actually the problem, we will need to see your polybar config.

**Comment by akirakanano** [comment]
> I'm sure this is a polybar configuration issue, and/or an issue of your system not matching your font properly. I'm pretty sure we can rule out your window manager entirely.
> 
> I think we need your configuration. I take it you're using the menu module? What command is your power-off menu-item executing?

My polybar configuration is as below or https://paste.debian.net/1069203/

I do not change any power off related configuration. So I am sure what command the power-off menu item execute. Thanks for help.  

```
;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/jaagr/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
;background = ${xrdb:color0:#222}
background = #222
background-alt = #444
;foreground = ${xrdb:color7:#222}
foreground = #dfdfdf
foreground-alt = #555
primary = #ffb52a
secondary = #e60053
alert = #bd2c40

[bar/example]
;monitor = ${env:MONITOR:HDMI-1}
width = 100%
height = 27
;offset-x = 1%
;offset-y = 1%
radius = 6.0
fixed-center = false

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3
line-color = #f00

border-size = 4
border-color = #00000000

padding-left = 0
padding-right = 2

module-margin-left = 1
module-margin-right = 2

font-0 = fixed:pixelsize=10;1
font-1 = unifont:fontformat=truetype:size=8:antialias=false;0
font-2 = siji:pixelsize=10;1

modules-left = bspwm i3
modules-center = mpd
modules-right = filesystem xbacklight alsa pulseaudio xkeyboard memory cpu wlan eth battery temperature date powermenu

tray-position = right
tray-padding = 2
;tray-background = #0063ff

;wm-restack = bspwm
;wm-restack = i3

;override-redirect = true

;scroll-up = bspwm-desknext
;scroll-down = bspwm-deskprev

;scroll-up = i3wm-wsnext
;scroll-down = i3wm-wsprev

cursor-click = pointer
cursor-scroll = ns-resize

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-prefix-underline = ${colors.secondary}

label-layout = %layout%
label-layout-underline = ${colors.secondary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.secondary}

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#0a81f5}%mountpoint%%{F-}: %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.foreground-alt}

[module/bspwm]
type = internal/bspwm

label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2

label-occupied = %index%
label-occupied-padding = 2

label-urgent = %index%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %index%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 2

; Separator in between workspaces
; label-separator = |

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

; Only show workspaces on the same output as the bar
;pin-workspaces = true

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-background = ${module/bspwm.label-focused-background}
label-focused-underline = ${module/bspwm.label-focused-underline}
label-focused-padding = ${module/bspwm.label-focused-padding}

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-padding = ${module/bspwm.label-occupied-padding}

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${module/bspwm.label-urgent-background}
label-urgent-padding = ${module/bspwm.label-urgent-padding}

; Separator in between workspaces
; label-separator = |


[module/mpd]
type = internal/mpd
format-online = <label-song>  <icon-prev> <icon-stop> <toggle> <icon-next>

icon-prev = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 

label-song-maxlen = 25
label-song-ellipsis = true

[module/xbacklight]
type = internal/xbacklight

format = <label> <bar>
label = BL

bar-width = 10
bar-indicator = |
bar-indicator-foreground = #fff
bar-indicator-font = 2
bar-fill = ─
bar-fill-font = 2
bar-fill-foreground = #9f78e1
bar-empty = ─
bar-empty-font = 2
bar-empty-foreground = ${colors.foreground-alt}

[module/backlight-acpi]
inherit = module/xbacklight
type = internal/backlight
card = intel_backlight

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #f90000
label = %percentage:2%%

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #4bffdc
label = %percentage_used%%

[module/wlan]
type = internal/network
interface = wlp2s0
interval = 3.0

format-connected = <ramp-signal> <label-connected>
format-connected-underline = #9f78e1
label-connected = %essid%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
ramp-signal-foreground = ${colors.foreground-alt}

[module/eth]
type = internal/network
interface = enp0s31f6
interval = 3.0

format-connected-underline = #55aa55
format-connected-prefix = " "
format-connected-prefix-foreground = ${colors.foreground-alt}
label-connected = %local_ip%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

[module/date]
type = internal/date
interval = 5

date =
date-alt = " %Y-%m-%d"

time = %H:%M
time-alt = %H:%M:%S

format-prefix = 
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #0a6cf5

label = %date% %time%

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume> <bar-volume>
label-volume = VOL %percentage%%
label-volume-foreground = ${root.foreground}

label-muted = 🔇 muted
label-muted-foreground = #666

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

[module/alsa]
type = internal/alsa

format-volume = <label-volume> <bar-volume>
label-volume = VOL
label-volume-foreground = ${root.foreground}

format-muted-prefix = " "
format-muted-foreground = ${colors.foreground-alt}
label-muted = sound muted

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 98

format-charging = <animation-charging> <label-charging>
format-charging-underline = #ffb52a

format-discharging = <animation-discharging> <label-discharging>
format-discharging-underline = ${self.format-charging-underline}

format-full-prefix = " "
format-full-prefix-foreground = ${colors.foreground-alt}
format-full-underline = ${self.format-charging-underline}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-foreground = ${colors.foreground-alt}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-foreground = ${colors.foreground-alt}
animation-charging-framerate = 750

animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-foreground = ${colors.foreground-alt}
animation-discharging-framerate = 750

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60

format = <ramp> <label>
format-underline = #f50a4d
format-warn = <ramp> <label-warn>
format-warn-underline = ${self.format-underline}

label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.secondary}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground-alt}

[module/powermenu]
type = custom/menu

expand-right = true

format-spacing = 1

label-open = 
label-open-foreground = ${colors.secondary}
label-close =  cancel
label-close-foreground = ${colors.secondary}
label-separator = |
label-separator-foreground = ${colors.foreground-alt}

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = sudo reboot

menu-2-0 = power off
menu-2-0-exec = sudo poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
;compositing-border = over
;pseudo-transparency = false

[global/wm]
margin-top = 5
margin-bottom = 5

; vim:ft=dosini

```

**Comment by akirakanano** [comment]
> The point about smooth fonts looks to me like your system (or at least your browser) now uses a bitmap font as the default font. This seems completely unrelated to polybar on its own, right? I think this can be solved by properly setting default fonts for your browser or whatever toolkit your browser uses for rendering (gtk or qt most likely).
> 
> The issue with poweroff is most likely that the command you set for that button is not executed properly. If you are using the sample config, this could be because `sudo poweroff` is used and requires a password (which you have no way to type). This can be solved by changing this to a command that turns of the computer without requiring a password. Simply `poweroff` could work. The other way of solving it is to explicitly make `sudo poweroff` not require a password (see [here](https://askubuntu.com/a/168885/454032)). To confirm this is actually the problem, we will need to see your polybar config.

It looks like working now. The steps I use to configure for shutting down thrown clicking power off icon include:

- Following the link (https://askubuntu.com/a/168885/454032) suggested by  @patrick96 Adding a line `<user name> ALL=(ALL) NOPASSWD: /sbin/poweroff, /sbin/reboot, /sbin/shutdown`, where user name is my login user. Then logout/ login or reboot to let sudoers take effect 

- Edit `~/.config/polybar/config` file. Changing **sudo poweroff** and **sudo reboot** to `/sbin/poweroff` and `/sbin/reboot` respectively. Then logout/ login or reboot if needed. 

This should fix the problem that clicking icon doesn't actually shutdown system. 

But I still do not know how to fix font problem. I understand this is more related to font configuration because it's caused by executing `dpkg-reconfigure fontconfig-config` command (First choose `Autohinter`; then `Full`; next `Automatic`; finally `Enable Bitemap font` or something). But without the last step (enable bitmap font) the polybar menu won't display icon such as power off. So It's a bit inconvenience because I need the icon (though I am accustomed to use command line, but not everyone who uses my laptop understands how to execute commands in terminal), and also want to have better font display. Any pointer like doc that I can check for such issue? 

Anyway thanks for all your kindly help!

**Comment by patrick96** [comment]
When you disable bitmap fonts again does font rendering return to normal?

On my Debian VM, the only way I get good font rendering is to set `Native` in the first screen. So maybe try that. Other than that I don't know how to fix this.

**Comment by akirakanano** [comment]
> When you disable bitmap fonts again does font rendering return to normal?
> 
> On my Debian VM, the only way I get good font rendering is to set `Native` in the first screen. So maybe try that. Other than that I don't know how to fix this.

In the first screen choosing Native does the trick. Though the font display at some some sites looks still not very smooth, it's a lot improved for many other sites. I consider this is fixed. Thank you very much for all your help!
