### ISSUE TITLE
xkeyboard displaying incorrect information and crashing

### ISSUE THREAD

**Issue by arjvik** [jaagr/polybar#1660]
## Describe the issue
I recompiled polybar from source today, and I noticed that the xkeyboard module is totally misbehaving. When I reloaded my polybar, I noticed that it showed I had both my Capslock and Scroll lock keys on, which I definitely did not (now that I think about it, k don't even have a scroll lock key). I tried pressing Capslock a few times, and polybar crashed. I tried again a few times, and it seemed that pressing Capslock a few times causes it to crash repeatedly.

**Expected behavior:**
Polybar's xkeyboard module should only show the Capslock and Scroll lock indicators when the respective keys are on. In addition, polybar should not crash when the caps lock key is hit a few times.

**Actual behavior:**
Polybar always shows the Capslock and Scroll lock indicators. In addition, it crashes when Capslock is hit a few times.

**Was it working before?**
I last compiled polybar from commit ca4426a9, which worked fine. Now, it fails on commit db9a83a8. (Curiously, this commit is about xkeyboard related stuff.)

## To Reproduce
My configuration is basically the stock example configuration. I haven't made any changes to xkeyboard. I will test out a sample MVE config tomorrow.

Launch polybar. Note Capslock and Scroll lock indicators. Press Capslock a few times. Note crash.

## Polybar Log
I will try to add this tomorrow.

## Screenshots
I will try to add this tomorrow.

## Environment:
* WM: i3-gaps
* Output of `polybar -vvv`: I will try to add this tomorrow.

**Comment by patrick96** [comment]
Dang, #1559 really introduced some bugs. Strange that we didn't notice that before. Will try to track this down.

**Comment by patrick96** [comment]
Fix is submitted in #1661. Was just a minor oversight (with quite large implications)

**Comment by arjvik** [comment]
Awesome! Whenever this PR is merged I will test it out.

**Comment by arjvik** [comment]
I just tested the PR out, and it works great! Thanks @patrick96 for fixing this so quickly!

**Comment by iljapanic** [comment]
Has the fix been merged into the master branch?

I'm experiencing the same issue.
