### ISSUE TITLE
bspwm module undefined tag

### ISSUE THREAD

**Issue by kzuu** [jaagr/polybar#1667]
## Describe the issue
*A clear and concise description of what the bug is.*
when you start polybar bspwm module warns about undefined tags
**Expected behavior:**
no warnings :)
*A clear and concise description of what you expected to happen.*
polybar to start and get behind
**Actual behavior:**
if you start polybar from terminal, it floods terminal with warnings about undefined tag => 's', 'w', 'g' etc
*What actually happens*

**Was it working before?**
Just installed bspwm, can't tell. Problem doesn't show up if you don't start polybar from terminal, so it doesn't really stop using it but something is not right.
* Did you also experience this bug in an earlier version of polybar?
* If no, what was the last version where this worked correctly?

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
;;;;;;;;;;;;;;;;;;;;;
;;bspwm Workspaces ;;
;;;;;;;;;;;;;;;;;;;;;
[module/bspwm]
type = internal/bspwm
pin-workspaces = false
inline-mode = false
enable-click = false
enable-scroll = false
reverse-scroll = false
fuzzy-match = false

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-7 = 8;
ws-icon-8 = 9;
ws-icon-9 = 10;

format = <label-state>
label-monitor = %name%
label-mode-padding = 1
label-focused = %icon%
label-focused-padding = 3
label-occupied = %icon%
label-occupied-padding = 3
label-urgent = %icon%
label-urgent-padding = 3
label-empty = %icon%
label-empty-padding = 3
;label-dimmed-foreground = ${colors.purple}
;label-dimmed-underline = ${colors.purple}
;label-dimmed-focused-background = ${colors.purple}
label-focused-foreground = ${colors.green}
label-focused-underline = ${colors.green}
label-occupied-foreground = ${colors.purple}
;label-occupied-underline = ${colors.purple}
label-urgent-foreground = ${colors.urgent}
label-urgent-underline = ${colors.urgent}
; The following labels will be used to indicate the layout/mode
; for the focused workspace. Requires <label-mode>
;label-sticky-foreground = ${colors.purple}
;label-locked-foreground = ${colors.moderate}
;label-private-foreground = ${colors.urgent}

```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
 ./launch.sh
Bars launched...
warn: module/bspwm: Undefined tag => 't'
warn: module/bspwm: Undefined tag => 'w'
warn: module/bspwm: Undefined tag => 'g'
warn: module/bspwm: Undefined tag => 's'
warn: module/bspwm: Undefined tag => 't'
warn: module/bspwm: Undefined tag => 'w'
warn: module/bspwm: Undefined tag => 'g'
warn: module/bspwm: Undefined tag => 's'

```

## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM: bspwm
* Output of `polybar -vvv`:
 polybar -vvv
polybar 3.3.0-31-gca4426a
![polybar](https://user-images.githubusercontent.com/47418500/53685499-1f044000-3d24-11e9-82ad-3cf534dcdc2d.png)

Features: +alsa +curl +i3 +mpd +network(wireless-tools) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags:  -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags:

## Additional context
*Add any other context that you think is necessary about the problem here.*

**Comment by patrick96** [comment]
Hmm, maybe bspwm added some new features or changed its reporting format that polybar doesn't support yet. Can you post the output of `bspc report`

**Comment by kzuu** [comment]
These are from another computer, but the symptoms are exactly the same.

bspc subscribe report:
WMHDMI-0:f1:terminals:O2:web:f3:media:o4:misc:LT:TT:G

polybar -l info bspwm-bar &
[1] 1792
* Loaded /home/-/.config/polybar/config
* Environment var ${MONITOR} is undefined, using defined fallback value "HDMI-0"
* Loaded monitor HDMI-0 (1280x720+0+0)
* Found matching X resource "foreground" (value=#e64521)
* Found matching X resource "foreground" (value=#e64521)
* Bar geometry: 1280x23+0+0
* Found matching X resource "foreground" (value=#e64521)
* Found matching X resource "foreground" (value=#e64521)
* Found matching X resource "color8" (value=#272a2c)
* Found matching X resource "foreground" (value=#e64521)
* Found matching X resource "color9" (value=#ff2940)
* Found matching X resource "color10" (value=#c9e584)
* Found matching X resource "color10" (value=#c9e584)
* Found matching X resource "color15" (value=#8aa58f)
* Found matching X resource "foreground" (value=#e64521)
* Found matching X resource "color15" (value=#8aa58f)
* Found matching X resource "foreground" (value=#e64521)
* Found matching X resource "foreground" (value=#e64521)
* Environment var ${POLYBAR_MODULES} is undefined, using defined fallback value "coreuse temperature memory wired-network"
* Found matching X resource "foreground" (value=#e64521)
* Found matching X resource "color15" (value=#8aa58f)
* Found matching X resource "color15" (value=#8aa58f)
* Found matching X resource "color1" (value=#ff2940)
* Found matching X resource "color1" (value=#ff2940)
* Found matching X resource "color10" (value=#c9e584)
* Found matching X resource "color10" (value=#c9e584)
* Found matching X resource "foreground" (value=#e64521)
* Found matching X resource "foreground" (value=#e64521)
* Found matching X resource "color10" (value=#c9e584)
* Found matching X resource "color12" (value=#6c8ccc)
* Found matching X resource "color12" (value=#6c8ccc)
* Found matching X resource "color1" (value=#ff2940)
* Found matching X resource "color1" (value=#ff2940)
* Found matching X resource "color10" (value=#c9e584)
* Found matching X resource "foreground" (value=#e64521)
* Found matching X resource "foreground" (value=#e64521)
* Found matching X resource "color15" (value=#8aa58f)
* Found matching X resource "foreground" (value=#e64521)
* Starting application
* Starting module/bspwm
* Starting module/xwindow
* Starting module/clock
* module/bspwm: Parsing socket data: :MHDMI-0:f1:terminals:O2:web:f3:media:o4:misc:LT:TT:G
* Starting module/coreuse
warn: module/bspwm: Undefined tag => 't'
warn: module/bspwm: Undefined tag => 'w'
* Starting module/temperature
* Starting module/memory
* Starting module/wired-network
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=8)
* Configured DPI = 96x96
* Loaded font "Bitstream Vera Mono:style=Roman:size=8" (name=DejaVu Sans, offset=1, file=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf)
* Loaded font "FontAwesome:pixelsize=11" (name=FontAwesome, offset=1, file=/usr/share/fonts/opentype/font-awesome/FontAwesome.otf)
* Loaded font "MaterialIcons:size=10:antialias=false" (name=Material Icons, offset=2, file=/home/tpakkila/.fonts/MaterialIcons-Regular.ttf)
* Loaded font "icomoon:size=10:antialias=false" (name=icomoon, offset=2, file=/home/tpakkila/.fonts/TTF/AL icomoon.ttf)
* Loaded font "Ubuntu Mono Nerd Font:size=10:antialias=false" (name=UbuntuMono Nerd Font, offset=2, file=/home/tpakkila/.fonts/TTF/AL Ubuntu Mono Nerd Font Complete.ttf)
* Bar window: 0x0e00002
* Disabling tray manager (reason: missing `tray-position`)
* module/bspwm: Rebuilding cache
* module/xwindow: Rebuilding cache
* module/clock: Rebuilding cache
* module/coreuse: Rebuilding cache
* module/temperature: Rebuilding cache
* module/memory: Rebuilding cache
* module/wired-network: Rebuilding cache
* Redrawing bar window
* module/coreuse: Rebuilding cache
* module/temperature: Rebuilding cache
* module/memory: Rebuilding cache
* Redrawing bar window
* module/wired-network: Rebuilding cache
* module/coreuse: Rebuilding cache
* module/temperature: Rebuilding cache
* module/memory: Rebuilding cache
* Redrawing bar window
^C
* module/coreuse: Rebuilding cache
* module/temperature: Rebuilding cache
* module/memory: Rebuilding cache
* Redrawing bar window
* module/wired-network: Rebuilding cache
* module/coreuse: Rebuilding cache
* module/temperature: Rebuilding cache
* module/memory: Rebuilding cache
* Redrawing bar window

**Comment by patrick96** [comment]
You seem to have colons in your desktop names, bspwm disallows that and it's why polybar gives those warnings

**Comment by kzuu** [comment]
Yes that's it... I just copied the workspace names as they were on i3 and feel like a dumbass.
