### ISSUE TITLE
Question about volume module

### ISSUE THREAD

**Issue by fwanky** [jaagr/polybar#1677]
Is the volume module only supportive of alsa? Because I can't get it to work with pulseaudio. I want to have the volume going up and down rather than having to use the pulse audio module which takes up space.

**Comment by patrick96** [comment]
Yes, the alsa module only works with alsa. Why don't you want to use the pulseaudio module? You can configure it to look just the same as the alsa module

**Comment by fwanky** [comment]
With the volume going up as it does with the volume module?
https://0x0.st/zHoD.png

How would I go about doing that, i'm a brainlet =_=

**Comment by patrick96** [comment]
What do you mean, going up and down?

You can use `ramp-volume` to display different icons depending on the volume. If you just want the percentage, you can use `label-volume = %percentage%%`

See also the [pulseaudio wiki page](https://github.com/jaagr/polybar/wiki/Module:-pulseaudio)
