### ISSUE TITLE
How do I have the icon change when clicking the date module?

### ISSUE THREAD

**Issue by fwanky** [jaagr/polybar#1688]
My date conf 
I want to have the icon change when I click the module, how do I do that?

```

[module/date]
type = internal/date
interval = 5

date =
date-alt = "%A, %d %b %Y" 

time = %I:%M
time-alt = %I:%M %p 

label = %date% %time%

format-prefix = 
format-prefix-foreground = ${colors.foreground-prefix}
format-warn-prefix-foreground = ${colors.foreground-prefix}
```

**Comment by Lomadriel** [comment]
You can do it like that
```ini
[module/date]
type = internal/date
interval = 1.0

date = [icon-1]
date-alt = [icon-2] %Y-%m-%d%


time = %I:%M
time-alt = %I:%M %p 
label = %date% %time%
```

**Comment by fwanky** [comment]
How do I mkae it so that it uses my format-prefix-foreground = ${colors.foreground-prefix}
 colours?

**Comment by Lomadriel** [comment]
Hum, I think the only solution for this moment is doing something like:
```ini
date = %{F#f00}[icon-1]%{F-}%
```
But you can't use `${colors.foreground-prefix}`. You can refer to the section "Format tags" of this page:
https://github.com/jaagr/polybar/wiki/Formatting

Maybe adding a `format-alt` for this module could be a good idea, I will propose a PR when I have some time.

**Comment by patrick96** [comment]
Yep, that's the only way.

Being able to reference colors within other text is on our TODO list.

If you add `format-alt`, you can probably also add `label-alt`
