### ISSUE TITLE
[feature request] Allow tray to be positioned left of module-right and vice versa

### ISSUE THREAD

**Issue by rieje** [jaagr/polybar#1691]
Feature request: Allow tray to be positioned left of module-right and vice versa.

When a tray is displayed because for example I plug my USB drive and udiskie starts up with its icon, the tray is currently created either at leftmost or rightmost part of the status bar, depending on whether tray-position is defined as left or right, respectively. This causes all modules defined in modules-left and modules-right to shift to create room for the tray (with `tray-detached = true`). 

For 99% of the time, the tray may not be on the status bar (e.g. I don't usually have an attached external drive, so no tray gets created). So when it does get created, I don't want it affecting all the positioning of my other modules on the same side as where the tray gets created (e.g. shifting the display of all the modules to the left if a tray gets created in modules-right). Information that is always shown on polybar should be "locked" in terms of their position and never change, as that's where expect the information is shown when we take a glance at the status bar.

A simple solution would be defining an option like `tray-relative-position = true|false` as a complement to `tray-position` where if true, a tray is displayed at the leftmost position of `tray-position = right` or rightmost position of `tray-position = left`. 

Something to consider how icons for the tray gets shown when they are created. For example, assuming `tray-relative-position` gets implemented, if it's true and `tray-position = right`, then when udiskie is the first application to be shown in the tray, then another application like networkmanager should show its icon on the tray to the left of udiskie icon, e.g. newest icons on the tray should be created to the left as you would expect following the behavior of the example I've described.

**Comment by Lomadriel** [comment]
The tray will be refactored in a module, see https://github.com/jaagr/polybar/issues/314. However the tray refactor may take some time because polybar need to be modified to allow icons (pictures) to be drawn in the bar. When this refactor will be finished you will be able to put the systray wherever you like.

At the moment the systray is another window which is above the bar.

**Comment by patrick96** [comment]
There is also `tray-position = center`, which could work in some situations.

But yeah, until we finish the new tray implementation tray configuration is quite limited

**Comment by firvida** [comment]
This is still an issue in Jan 2022. I manage to solve it with:

```
tray-position = center
tray-detached = false
tray-maxsize = 16
tray-offset-x = 580
```
