### ISSUE TITLE
Tray background is always transparent

### ISSUE THREAD

**Issue by jonathashenriques** [jaagr/polybar#170]
![2016-11-16-185053_1366x768_scrot](https://cloud.githubusercontent.com/assets/21113681/20365335/bc2faf84-ac2d-11e6-943e-110af2505415.png)

**Comment by jaagr** [comment]
Are you using `tray-transparent = true`? See the notes on the wiki

**Comment by jonathashenriques** [comment]
I was able to fix the problem, so closing the issue. Thank you :)

**Comment by elliot-wasem** [comment]
Howw did you fix the problem?

**Comment by patrick96** [comment]
@elliot-wasem This should never happen since version 3.3.0 as long as you have set `tray-background` to the same color as the bar background
