### ISSUE TITLE
Dropping unmatched character (U+0020)

### ISSUE THREAD

**Issue by zbigniewzolnierowicz** [jaagr/polybar#1707]
## Describe the issue

**Expected behavior:**

There should be spaces in-between modules, in module padding and in text in the modules themselves.

**Actual behavior:**

There are no spaces in Polybar between modules, in module padding and inside of the modules themselves. The log keeps posting `Dropping unmatched character   (U+0020)`. 

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
font-0 = Siji:size=10
font-1 = creep:size=10
```
## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
warn: Dropping unmatched character   (U+0020)
```

## Screenshots

![Screenshot](https://i.imgur.com/NbsDCA2.png)

## Environment:
* WM: bspwm
* Distro: Arch Linux
* Output of `polybar -vvv`:

```
polybar 3.3.0

Features: +alsa +curl -i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment]
The `creep` font does not provide the space character. Add another font that does.

Please also read the [Font wiki page](https://github.com/jaagr/polybar/wiki/Fonts)
