### ISSUE TITLE
Polybar claiming space below bar in i3 gaps tiled layout

### ISSUE THREAD

**Issue by klarinetkid** [jaagr/polybar#1711]
I usually have my i3 title bars turned off (`new_window pixel 3`), but when I went to turn them on today, I noticed a weird issue. 
If I have a window open in tiled mode that has a title bar, polybar claims a bunch of space below it. If I have it in tabbed layout however, it always works fine. What is really weird is that the height of the windows doesn't change in tabbed or tiled layout, yet it creates the problem.

[Album of images](https://imgur.com/a/NDwUJaE)
[i3 config](https://pastebin.com/D5X80CLB)
[polybar config](https://pastebin.com/GxZHUGZZ)

I have tried playing with some settings such as `wm-restack` and `override-redirect` for polybar.

**Comment by patrick96** [comment]
> polybar claims a bunch of space below it

Do you mean that black bar that appear beneath the window?

I was able to reproduce this black bar, as well as the weird black box in your second last screenshot.

*With Compton:*
![2019-03-26-231007_3840x1080_scrot](https://user-images.githubusercontent.com/2452038/55036916-582a8a00-501c-11e9-969d-4a392ae07065.png)

*Without Compton:*
![2019-03-26-231018_3840x1080_scrot](https://user-images.githubusercontent.com/2452038/55036917-582a8a00-501c-11e9-93d5-e4acdc5013f9.png)

However, I can reproduce all of this without polybar running. I was not able to get any undesired behavior that I wasn't also able to get without polybar running, so this is unrelated to polybar and more of an i3 (maybe gaps) problem.

**Comment by klarinetkid** [comment]
I'm so dumb! I should have tested if the problem was actually with polybar. thanks a ton!
