### ISSUE TITLE
Polybar displaying rainbow colours and not working

### ISSUE THREAD

**Issue by Ashe** [jaagr/polybar#1720]
## Describe the issue
I can't get polybar to work but I can't find the cause, and I feel like it would be good to get an answer here in case people also get this problem in the future. Many updates have happened since I last used polybar so I don't know if poly has changed or something else. I'm using polybar-git from the AUR.

**Expected behavior:**
It used to work like in the following screenshot:
![expected](https://raw.githubusercontent.com/Ashe/dotfiles/master/.dotfilesPreview.png)

**Actual behavior:**
When I call my script now, it just displays rainbow lines. [Here is my script](https://github.com/Ashe/dotfiles/blob/bee3104f36bb686c2ed0d47ddee396a9e07b5d43/.scripts/poly), and this is what happens when I call it:
![Image of problem](https://i.imgur.com/ieU8rTX.png)

I've never experienced this before, nor do I know what is causing polybar to do this. Maybe try using my script with [my config](https://github.com/Ashe/dotfiles/blob/c2c5785dd21060e562ee3a084536202b01ba497a/.config/polybar/config) to see what happens?

## Polybar Log
```
~ ::  master > 3:45:08
$ poly
GL_RENDERER   = GeForce GTX TITAN X/PCIe/SSE2
GL_VERSION    = 4.6.0 NVIDIA 418.56
GL_VENDOR     = NVIDIA Corporation
```

```
## Environment:
* WM: BSPWM
* Distro: Arch
* Output of `polybar -vvv`:

~ ::  master > 3:45:51
$ polybar -vvv
polybar 3.3.0-45-g31a25af3

Features: +alsa +curl -i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```
### Thank you

**Comment by patrick96** [comment]
That rainbow image is what displays when you run `poly` which is not polybar but from `mesa-demos`. Are you sure you don't run `poly` by accident?

**Comment by Ashe** [comment]
You are indeed correct, the name of my script was named `poly` which seems to have been pushed aside by the `poly` you mentioned. Thank you for the swift reply, I would never have guessed. Hopefully this issue helps someone in the future.
