### ISSUE TITLE
Can't seem to get icons to appear

### ISSUE THREAD

**Issue by hurani** [jaagr/polybar#1727]
I am trying to use [this theme](https://github.com/adi1090x/polybar-themes). It uses icomoon font for the icons and Ubuntu Condensed for the text. Ubuntu Condensed is showing up fine, but the icons won't show up, even though they show up in my editor. This is my first time using polybar so I am sure this is probably something I missed. Any tips on how to get the icons working?

**Comment by Lomadriel** [comment]
Without further information, we can't really help you.
However you can check the wiki (https://github.com/jaagr/polybar/wiki/Fonts) if you have an issue with fonts.
Moreover, if you need help please use the IRC, Reddit… (see https://github.com/jaagr/polybar/blob/master/SUPPORT.md). It is more convenient for us to help you.

**Comment by hurani** [comment]
The whole issue was a typo in the font name that I spent hours looking for and couldn't find. My bad for posting here.
