### ISSUE TITLE
Interaction with autorandr 

### ISSUE THREAD

**Issue by Kazy** [jaagr/polybar#173]
I'm using [autorandr](https://github.com/phillipberndt/autorandr) to automatically switch between monitors configuration. When I'm switching from two monitors to only one, the remaining screen gets the two bars. The solution I tried was to use autorandr `postswitch` script, which is executed right after each screen change, and execute the `launch.sh` script I'm using when starting i3.

While the `lanch.sh` works great on its own, when triggered by autorandr the bar isn't displayed. Using a debug build of polybar + log to `trace`, I get the following and then nothing. 
```
polybar|trace  config: Loaded ~/.config/polybar/config
polybar|trace  config: Current bar section: [bar/bottom_bar]
polybar|trace  controller: Initialize X atom cache
polybar|trace  controller: Query X extension data
polybar|trace  controller: Create IPC handler
polybar|trace  controller: Listen for events on the root window
polybar|trace  controller: Setup bar
polybar|trace  bar: Create monitor from matching X RandR output
```
Polybar version: 
```
polybar 2.3.0-8-g88c8bbd
Built with: +alsa +i3 +mpd +network
```

**Comment by jaagr** [comment]
I've added logic b9ff9c5 that will reload the bar upon receiving a XCB_RANDR_SCREEN_CHANGE_NOTIFY event (needs to be turned on in the conf). This will solve issues where the bar size/pos doesn't match after a randr update.

**Comment by davewongillies** [comment]
@jaagr what's the option that needs to be turned on in the conf for this to work?

**Comment by jaagr** [comment]
~~~dosini
[settings]
screenchange-reload = true
~~~

**Comment by davewongillies** [comment]
:ok_hand: excellent, works perfectly

**Comment by Kazy** [comment]
I had some issues when I tried it, but now it's working, thanks a lot ! I just need to recreate the bar when I'm plugging a monitor, but that's alright. Quick question though: anyway to make the systray reappear ?

**Comment by jaagr** [comment]
@Kazy Make sure you only have one bar with the tray setting enabled. If another one is launched it will override the other one, and I've disabled re-activation when that happens. Otherwise you could just restart all bars.

**Comment by Kazy** [comment]
I can't restart all bar with autorandr, that was my original issue. Nothing's happening. 
And the tray doesn't show up some time for some reason, but I had the same issue with others bars, I don't think it's related to polybar. I think we can close the issue, thanks again :)

**Comment by jaagr** [comment]
That's odd.. I used postswitch + udev with autorandr to launch and it worked fine when it got fired..
Added `notify-send -u low "autorandr: restarting polybar"` to get notified when it got triggered...

**Comment by Kazy** [comment]
Well, now it works, I can kill and recreate the bar inside postswitch. No idea what changed, but the issue is completely resolved :+1:

**Comment by jaagr** [comment]
Great!

**Comment by languitar** [comment]
Somehow, for me the bars do not launch correctly in the postswitch hook. If I trigger autorandr manually, everything works well, but when using udev after changes connections, the new bars do not start correctly. Any idea what could be causing this?

**Comment by patrick96** [comment]
@languitar: Does polybar give any errors? And what do you mean by 'not correctly'?

**Comment by languitar** [comment]
It looks like it would be starting for a second because the windows temporarily shift down but in the end no bars appear. As autorandr is called from udev I have tried to send all output (for three bars) to a log file. This is what I see:
```
polybar|error: Disabling module "i3" (reason: Could not find socket: <empty>)
polybar|warn:  Termination signal received, shutting down...
polybar|error: Disabling module "i3" (reason: Failed to connect to i3: errno 111 (Connection refused))
polybar|error: module/i3: Failed to connect to i3: errno 111 (Connection refused)
polybar|warn:  Stopping 'module/i3'...
polybar|error: Disabling module "i3" (reason: Failed to connect to i3: errno 111 (Connection refused))
polybar|warn:  Termination signal received, shutting down...
polybar|warn:  Termination signal received, shutting down...
polybar|warn:  Termination signal received, shutting down...
```
My launch file first kills existing bars, so I am not sure whether these are actually expected outputs.

**Comment by patrick96** [comment]
Please only try it with a single bar, otherwise it is impossible to distinguish what message came from which bar. Also please run polybar with `-l info` and apply the following patch and compile again:
```patch
diff --git a/src/components/controller.cpp b/src/components/controller.cpp
index 2f93c96..7fd6a89 100644
--- a/src/components/controller.cpp
+++ b/src/components/controller.cpp
@@ -30,6 +30,7 @@ sig_atomic_t g_terminate{0};
 void interrupt_handler(int signum) {
   g_terminate = 1;
   g_reload = (signum == SIGUSR1);
+  logger::make().err("Received signal: %s (%d)", strsignal(signum), signum);
   if (write(g_eventpipe[PIPE_WRITE], &g_terminate, 1) == -1) {
     throw system_error("Failed to write to eventpipe");
   }
```

This should give some more insight to what's actually happening. I don't think polybar is doing anything wrong here, whatever script you are using to restart the bar probably has some unintended side-effects when you trigger it via udev.

**Comment by languitar** [comment]
I did not apply the patch yet, but this is the log of a single bar being launched from autorandr, which disappears immediately:
```
polybar|info:  Loading config: /home/languitar/.config/polybar/config
polybar|info:  Environment var reference ${MONITOR} found (value=eDP1)
polybar|info:  Loaded monitor eDP1 (1920x1080+0+0)
polybar|info:  Bar geometry: 1920x22+0+0
polybar|error: Disabling module "i3" (reason: Could not find socket: <empty>)
polybar|info:  Starting application
polybar|info:  Starting module/xbacklight
polybar|info:  Starting module/volume
polybar|info:  Starting module/cpu
polybar|info:  Starting module/memory
polybar|info:  Starting module/swap
polybar|info:  Starting module/battery
polybar|info:  Starting module/filesystem
polybar|info:  Starting module/xkeyboard
polybar|info:  Starting module/date
polybar|info:  Starting module/powermenu
polybar|info:  Entering event loop (thread-id=1)
polybar|info:  Eventqueue worker (thread-id=11)
polybar|info:  Configured DPI = 96x96
polybar|info:  Loaded font "DejaVu Sans Mono:pixelsize=9" (name=DejaVu Sans Mono, offset=1, file=/usr/share/fonts/TTF/DejaVuSansMono.ttf)
polybar|info:  Loaded font "Material Icons:pixelsize=10" (name=Material Icons, offset=2, file=/usr/share/fonts/TTF/MaterialIcons-Regular.ttf)
polybar|info:  Bar window: 0x1a00002
polybar|info:  Activating tray manager
polybar|info:  Tray window: 0x1a00006
polybar|warn:  Termination signal received, shutting down...
polybar|info:  module/xbacklight: Stopping
polybar|info:  Deconstruction of module/xbacklight took 0 ms.
polybar|info:  module/volume: Stopping
polybar|info:  Deconstruction of module/volume took 1 ms.
polybar|info:  module/cpu: Stopping
polybar|info:  Deconstruction of module/cpu took 0 ms.
polybar|info:  module/memory: Stopping
polybar|info:  Deconstruction of module/memory took 0 ms.
polybar|info:  module/swap: Stopping
polybar|info:  Deconstruction of module/swap took 0 ms.
polybar|info:  module/battery: Stopping
polybar|info:  Deconstruction of module/battery took 169 ms.
polybar|info:  module/filesystem: Stopping
polybar|info:  Deconstruction of module/filesystem took 0 ms.
polybar|info:  module/xkeyboard: Stopping
polybar|info:  Deconstruction of module/xkeyboard took 0 ms.
polybar|info:  module/date: Stopping
polybar|info:  Deconstruction of module/date took 0 ms.
polybar|info:  module/powermenu: Stopping
polybar|info:  Deconstruction of module/powermenu took 0 ms.
polybar|info:  Notifying pending tray clients
polybar|info:  Deactivating tray manager
polybar|info:  Waiting for spawned processes to end
polybar|info:  Reached end of application...
```

**Comment by NBonaparte** [comment]
Could you post your postswitch script?

**Comment by languitar** [comment]
I think I have finally found the reason for this problem. In case the display configuration is changed, the autorandr udev rule starts the `autorandr.service` systemd unit. This unit then calls `/usr/bin/autorandr --batch --change --default default`, which dispatches autorandr to all user sessions and effectively results in calling all postswitch hooks for the user sessions, which then start the new polybar instances. The culprit here is that a systemd unit is used. The default behavior of systemd units is to clean up all spawned processes in the control group of the original `autornadr --batch` call, which also includes the newly spawned polybar instances.
