### ISSUE TITLE
Documentation and example configuration isn't created with build.sh

### ISSUE THREAD

**Issue by angerborn** [jaagr/polybar#1733]
Since documentation generation was made optional here https://github.com/jaagr/polybar/commit/754673bff8f3cbd90b1eb0fd622fe332613053bf, it's not generated automatically using `build.sh` (and there's no way to get documentation running this script afaict). This means that installing the example configuration will fail since the `doc/config` file is not created.

**Comment by patrick96** [comment]
Oh dang. I always forget about build.sh. Will fix this soon, for now installing [Sphinx](http://www.sphinx-doc.org/en/master/) should automatically enable building the documentation
