### ISSUE TITLE
Compiled latest git, now no modules work at all!

### ISSUE THREAD

**Issue by alan12345678** [jaagr/polybar#1737]
## Describe the issue
*A clear and concise description of what the bug is.*
So, I started from scratch, reading through your wiki following the steps. Have begun with a clean file. I've only written three modules - date, memory, network. Initially the time and date were displayed on my bar. Now, after issues getting the others to work at all, I now have none at all!
**Expected behavior:**
Expected to load bar, and see three crude modules appear.
*A clear and concise description of what you expected to happen.*

**Actual behavior:**
No bar even appears now. It did show up, but with just date and time. Now no bar at all
*What actually happens*

**Was it working before?**
It was working in the package compiled for pacman, Manjaro i3.
* Did you also experience this bug in an earlier version of polybar?
In the official package, date worked.
* If no, what was the last version where this worked correctly?

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[bar/mybar]
monitor = DVI-I-2
modules-right = date network
modules-left = memory
monitor-strict = false
enable-ipc = false
bottom = true
fixed-center = true
padding = 2
module-margin = 2
locale = en_GB.UTF-8
#font-0 = NotoSans-Regular:size8;2

[module/datetime]
type = internal/date
date = %a %d %b %Y
time = %H:%M:%S

format = 🕓 <label>

[module/wireless-network]
type = internal/network
interface = wlp6s0
ping-interval = 60

format-connected = <ramp-signal> <label-connected>
format-disconnected = <label-disconnected>
format-packetloss = <animation-packetloss> <label-connected>
label-connected = %{A1:nm-connection-editor:}%essid%%{A} %downspeed% %upspeed%
label-connected-foreground = #eefafa
label-disconnected = not connected
label-disconnected-foreground = #66ffff

ramp-signal-0 = 😱
ramp-signal-1 = 😠
ramp-signal-2 = 😒
ramp-signal-3 = 😊
ramp-signal-4 = 😃
ramp-signal-5 = 😈

; Only applies if <animation-packetloss> is used
animation-packetloss-0 = ⚠
animation-packetloss-0-foreground = #ffa64c
animation-packetloss-1 = 📶
animation-packetloss-1-foreground = #000000
; Framerate in milliseconds
animation-packetloss-framerate = 500

[module/memory]
format = <label> <bar-used>
label = RAM %gb_used%/%gb_free%

bar-used-indicator =
bar-used-width = 50
bar-used-foreground-0 = #55aa55
bar-used-foreground-1 = #557755
bar-used-foreground-2 = #f5a70a
bar-used-foreground-3 = #ff5555
bar-used-fill = ▐
bar-used-empty = ▐
bar-used-empty-foreground = #444444


















[global/wm]
; Adjust the _NET_WM_STRUT_PARTIAL bottom value
;   Used for bottom aligned bars
margin-top = 0
```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*
? I installed the Manjaro i3 .iso. Have been tinkering with the config, but mostly colours etc. Was working fine until about ten minutes ago ;)
## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
[alan@MalanJaro ~]$ polybar mybar
error: Disabling module "memory" (reason: Missing parameter "module/memory.type")
error: Disabling module "date" (reason: Missing parameter "module/date.type")
error: Disabling module "network" (reason: Missing parameter "module/network.type")
error: No modules created

```

## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM:i3
* Distro: Manjaro, with a bit of xfce
* Output of `polybar -vvv`:
[alan@MalanJaro ~]$ polybar -vvv
polybar 3.3.0-77-gd5112c9b

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now

## Additional context
*Add any other context that you think is necessary about the problem here.*

**Comment by Lomadriel** [comment]
These modules doesn't exist:
```ini
modules-right = date network
```
With the correct names:
```ini
modules-right = datetime wireless-network
```

Moreover the type is missing for the `memory` module, you must add the type:
```ini
[module/memory]
type = internal/memory
format = <label> <bar-used>
```

With these corrections, it seems to work as intended.

**Comment by alan12345678** [comment]
palm smacks forehead!!

Thank you!!

Just a note: when I say I'd read the documentation - I believed I was following the latest. I'd seen `[module/wireless-network]` but then elsewhere the earlier [module/network], likewise with time.

I'll double check in future that I'm reading the correct docs!

Many thanks - it's an awesome bar :D

*alan ansell figurative painting
Itzac
France*

**We are what we repeatedly do. Excellence is therefore not an act but a habit.
 Aristotle**




----- Original message -----

**Comment by patrick96** [comment]
You can give modules arbitrary names, so you could have `[module/dostuff]`, the name of the module would then be `dostuff` and needs to be referred to as such in `modules-left` and so on. `network` and `wireless-network` are both valid module names.
