### ISSUE TITLE
Siji Font: Followed doc but does not work :(

### ISSUE THREAD

**Issue by etienne-monier** [jaagr/polybar#1738]
Hi,

### Abstract
I have `Dropping unmatched character 🔈 (U+1f508)` warning.
I followed the [doc about font](https://github.com/jaagr/polybar/wiki/Fonts) to solve it.
I did not succeed.
Consequence: I'm getting mad :(

### Config
I have Ubuntu 16.04 LTS with i3wm.

### Font config in `config`file

```
font-0 = Font Awesome 5 Free Regular:size=10;4
font-1 = Font Awesome 5 Free Solid:size=10;4
font-2 = Font Awesome 5 Brands Regular:size=10;4
font-3 = Noto\ Sans\ CJK\ SC,Noto\ Sans\ CJK\ SC\ Light:style=Light,Regular:size=9;0
font-4 = MaterialDesignIcons:style=Regular:size=11;2
font-5 = Terminus:style=Regular:size=14;0
font-6 = Siji:style=Regular:pixelsize=11;1
```

#### Are the fonts correctly installed ?
The fonts are correcty installed as `fc-list | grep Awesome` (and the same for all other fonts) give me right answer.

#### Do `polybar` loads it correctly ?

Here is my conf (again).

```
font-0 = Font Awesome 5 Free Regular:size=10;4
font-1 = Font Awesome 5 Free Solid:size=10;4
font-2 = Font Awesome 5 Brands Regular:size=10;4
font-3 = Noto\ Sans\ CJK\ SC,Noto\ Sans\ CJK\ SC\ Light:style=Light,Regular:size=9;0
font-4 = MaterialDesignIcons:style=Regular:size=11;2
font-5 = Terminus:style=Regular:size=14;0
font-6 = Siji:style=Regular:pixelsize=11;1
```

Here is what polybar -l info gives me.

```
* Loaded font "Font Awesome 5 Free Regular:size=10" (name=Font Awesome 5 Free, offset=4, file=/home/etienne/.local/share/fonts/Font Awesome 5 Free-Regular-400.otf)
* Loaded font "Font Awesome 5 Free Solid:size=10" (name=Font Awesome 5 Free, offset=4, file=/home/etienne/.local/share/fonts/Font Awesome 5 Free-Solid-900.otf)
* Loaded font "Font Awesome 5 Brands Regular:size=10" (name=Font Awesome 5 Brands, offset=4, file=/home/etienne/.local/share/fonts/Font Awesome 5 Brands-Regular-400.otf)
* Loaded font "Noto\ Sans\ CJK\ SC,Noto\ Sans\ CJK\ SC\ Light:style=Light,Regular:size=9" (name=Noto Sans CJK SC, offset=0, file=/usr/share/fonts/opentype/noto/NotoSansCJK-Light.ttc)
* Loaded font "MaterialDesignIcons:style=Regular:size=11" (name=MaterialDesignIcons, offset=2, file=/usr/share/fonts/truetype/materialdesignicons-webfont/materialdesignicons-webfont.ttf)
* Loaded font "Terminus:style=Regular:size=14" (name=Terminus, offset=0, file=/usr/local/share/fonts/terminus/ter-x14n.pcf.gz)
* Loaded font "Siji:style=Regular:pixelsize=11" (name=Siji, offset=1, file=/home/etienne/.local/share/fonts/siji.pcf)
```

So, `polybar` loads the fonts correctly.

#### The glyph is in Siji
The glyph `🔈 (U+1f508)` is in Siji, so it should be ok. I checked with `gucharmap` with the option that keeps only the glyphs from Siji but it displays nothing at all.

I checked with `xfd -fa siji` but this one shouwed be all the Siji glyphs.

#### Is my Siji correctly installed ?

This is the only remaining question I have. I followed the [first paragraph doc about fonts](https://github.com/jaagr/polybar/wiki/Fonts) as I have Ubuntu. I made
```
sudo rm /etc/fonts/conf.d/70-no-bitmaps.conf
sudo ln -s /etc/fonts/conf.avail/70-yes-bitmaps.conf /etc/fonts/conf.d/70-yes-bitmaps.conf
```

Beside, the siji installation asks to add a small script to a startup file (before xlogin) but I did not understand why it was required. I executed the "required" commands in my command but that did not solve the problem.

Help !

**Comment by patrick96** [comment]
Can you explain again how you checked the icon was in siji? It's possible that our documentation isn't clear enough because that icon is an emoji and not in siji. For that icon you need an emoji font like `noto-emoji`

**Comment by etienne-monier** [comment]
Ok !

I finally found the right loudspeaker icon in siji whose code is U+E204. The same kind of icon is in MaterialDesignIcon.

I had the wrong icon in my conf file.

*Note to me: an icon that looks like a Loudspeaker for a font does not for another font.*

I'm sorry. I thought that this loudspeaker glyph had its place in the Unicode tabular and that all fonts placed it at this place, but that's not the case. As a consequence, my gegit editor displays a strange Japanese glyph where MaterialDesign font sees a loudspeaker. Hummm.

But the font problem is solved.
Sorry for the spam, but it could be useful for you who have the same problem. Issues are also made for that.

Closing and thanks patrick96 coming from ... dagnabbit ! That's not a code for a French region :s

**Comment by patrick96** [comment]
Fonts are very tricky to get right, especially if there are multiple glyphs from multiple fonts that look similar. We try our best to make the documentation as clear as possible so that if you carefully follow the steps, you should never have problems. It seems we have failed, since you did that and still had issues. I guess we need to make step 2 clearer. I actually have plans to rewrite the font documentation and take a more rigorous approach.
