### ISSUE TITLE
Histogram modules?

### ISSUE THREAD

**Issue by imiric** [jaagr/polybar#1740]
Hi, thanks for the great tool.

One thing I'm not seeing in the documentation (or elsewhere online, strangely enough) is mention of histogram modules. With Conky I was used to `cpugraph`, which shows CPU usage in a histogram, which is very intuitive to see at a glance. Whereas Polybar's CPU module shows individual per-core ramps, without past data and is much less useful for me.

Are histograms not possible in Polybar or a module that does it simply hasn't been implemented yet?

Thanks,

Ivan

**Comment by patrick96** [comment]
This is not implemented and I'm not aware of any script that does this.

You're welcome to write a script that shows a histogram ;)

The main issue I see is that polybar can only display characters, so each data point in a histogram would be 1 character wide, making histograms use a lot of space.

For the next time, the issue tracker is meant for bug reports and feature requests. Please don't ask support questions here, read our [Support page](https://github.com/jaagr/polybar/blob/master/SUPPORT.md) for a list of resources where you can ask questions.
