### ISSUE TITLE
error: Disabling module "alsa" (reason: No built-in support for 'internal/alsa')

### ISSUE THREAD

**Issue by Nekenlight** [jaagr/polybar#1741]
Hey,

I have some trouble running alsa volume control on polybar i get this message when I try to run it on my Logitech Headset :

`error: Disabling module "alsa" (reason: No built-in support for 'internal/alsa')`

This my trouble shooting state :

`polybar --version` output :  

`polybar 3.3.0`
`Features: -alsa +curl +i3 -mpd -network(wireless-tools) -pulseaudio +xkeyboard`

`amixer scontrols` output :

`Simple mixer control 'Master',0 `
`Simple mixer control 'Capture',0`

`amixer -c 1 scontrols` normaly my headphone headset :

`Simple mixer control 'Headphone',0`
`Simple mixer control 'Mic',0`

`cat /proc/asound/cards` output :

 `0 [PCH            ]: HDA-Intel - HDA Intel PCH`
                      `HDA Intel PCH at 0xdf240000 irq 133`
 `1 [Headset        ]: USB-Audio - Logitech G430 Gaming Headset`
                      `Logitech Logitech G430 Gaming Headset at usb-0000:03:00.0-2, full speed`

My alsa configuration :

`[module/alsa]`
`type = internal/alsa`

`master-soundcard = hw:1`

`format-volume = <label-volume> <bar-volume>`
`label-volume = VOL`
`label-volume-foreground = ${root.foreground} `

`format-muted-prefix = " "`
`format-muted-foreground = ${colors.foreground-alt}`
`label-muted = sound muted`

`bar-volume-width = 10`
`bar-volume-foreground-0 = #55aa55`
`bar-volume-foreground-1 = #55aa55`
`bar-volume-foreground-2 = #55aa55`
`bar-volume-foreground-3 = #55aa55`
`bar-volume-foreground-4 = #55aa55`
`bar-volume-foreground-5 = #f5a70a`
`bar-volume-foreground-6 = #ff5555`
`bar-volume-gradient = false`
`bar-volume-indicator = |`
`bar-volume-indicator-font = 2`
`bar-volume-fill = ─`
`bar-volume-fill-font = 2`
`bar-volume-empty = ─`
`bar-volume-empty-font = 2`
`bar-volume-empty-foreground = `${colors.foreground-alt}`

**Comment by Lomadriel** [comment]
> `polybar --version` output :
> 
> `polybar 3.3.0`
> `Features: -alsa +curl +i3 -mpd -network(wireless-tools) -pulseaudio +xkeyboard`
> 

`-alsa` signifies you forgot to install `alsa-lib` before compiling polybar.
See https://github.com/jaagr/polybar/wiki/Compiling#optional-dependencies

**Comment by Nekenlight** [comment]
There are already install : 

```[root@blabla~]# rpm -qa | grep alsa
alsa-utils-1.1.8-2.fc29.x86_64
alsa-lib-1.1.8-1.fc29.x86_64
alsa-plugins-pulseaudio-1.1.8-1.fc29.x86_64
qemu-audio-alsa-3.0.0-3.fc29.x86_64
alsa-ucm-1.1.8-1.fc29.noarch
alsa-lib-devel-1.1.8-1.fc29.x86_64
```

**Comment by Nekenlight** [comment]
It's ok now I had to recompile polybar with `cmake -DENABLE_ALSA=ON` and make install. 

Now it's OK : 

`Features: +alsa +curl +i3 -mpd -network(wireless-tools) +pulseaudio +xkeyboard
