### ISSUE TITLE
Polybar system tray unresponsive

### ISSUE THREAD

**Issue by shatterball** [jaagr/polybar#1744]
## Description
Polybar system tray becomes unresponsive randomly...
sometimes it will work other times it simply doesn't ... no matter if i restart it.
The tray was working fine a couple of days ago... Can anyone help?

[My Polybar Config]
[colors]
;background = ${xrdb:color0:#222}
background = #1d2021
background-alt = #3c3836
;foreground = ${xrdb:color7:#222}
foreground = #dfdfdf
foreground-alt = #555
primary = #555
secondary = #e60053
alert = #bd2c40

[bar/bar]
enable-ipc = true
;monitor = ${env:MONITOR:HDMI-1}
width = 100%
height = 20
;offset-x = 1%
;offset-y = 1%
radius = 0.0
fixed-center = true
bottom = true
background = ${colors.background}
foreground = ${colors.foreground}

line-size = 0
line-color = #f00

border-size = 10
border-top-size = 0
border-color = #00000000

padding-left = 0
padding-right = 0

module-margin-left = 1
module-margin-right = 1

font-0 = xos4 Terminus:size=9;2
font-1 = FontAwesome:size=12;1

modules-left = i3
modules-right = pulseaudio s cpu s memory s date

tray-position = right
tray-padding = 2

scroll-up = i3wm-wsnext
scroll-down = i3wm-wsprev

[module/bspwm]
type = internal/bspwm

label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2

label-occupied = %index%
label-occupied-padding = 2

label-urgent = %index%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %index%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 2

[module/i3]

type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

label-mode-padding = 0
label-mode-foreground = #000
label-mode-background = ${colors.primary}

label-focused = Workspace %index%
label-focused-background = ${module/bspwm.label-focused-background}
label-focused-underline = ${module/bspwm.label-focused-underline}
label-focused-padding = ${module/bspwm.label-focused-padding}

label-unfocused = %index%
label-unfocused-padding = ${module/bspwm.label-occupied-padding}

label-visible = V %index%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-background}
label-visible-padding = ${self.label-focused-padding}

label-urgent = %index%!
label-urgent-background = ${module/bspwm.label-urgent-background}
label-urgent-padding = ${module/bspwm.label-urgent-padding}

[module/cpu]
type = internal/cpu
interval = 1
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #555
label = "CPU: %percentage%%"

[module/memory]
label-mode-padding = 0
type = internal/memory
interval = 2
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #555
label = "Mem: %percentage_used%%"

[module/date]
type = internal/date
interval = 1

date = "%Y-%m-%d"

time = "%l:%M:%S %p"

format-prefix-foreground = ${colors.foreground-alt}
format-underline = #555

label = "%date% %time% "

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = true
interval = 5
format-volume = <label-volume>
format-volume-underline = #555
label-volume ="Vol: %percentage%%"

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
;compositing-border = over

[global/wm]
margin-top = 2
margin-bottom = 2

[module/s]
type = custom/text
content = |
; vim:ft=dosini

[ Environment]
WM: i3wm
Distro: Arch (vanilla)

[Output of 'polybar -vvv' ]
polybar 3.3.1

Features: +alsa +curl +i3 -mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /sbin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now

**Comment by patrick96** [comment]
@shatterball were you able to solve it?

We had reports in the past that the tray becomes stuck sometimes (#1440). But I don't think it ever persisted across restarts.

**Comment by shatterball** [comment]
The tray randomly starts to get unresponsive... Ive read the linked issue but that's not the problem with me though... Icons work fine.. But Its the system tray which doesn't respond when clicked on.

**Comment by ivohulsman** [comment]
I am having the same exact problem. I have noticed though that tray usually freezes when my computer wakes up from sleep.

**Comment by shatterball** [comment]
> I am having the same exact problem. I have noticed though that tray usually freezes when my computer wakes up from sleep.

This also happens when polybar doesn't get focus for more than 10 minutes.

**Comment by shatterball** [comment]
I think there was some problem with the config... replaced it with defaults and works fine now. CLOSING

**Comment by krkhan** [comment]
I was facing this issue in all four of my Linux distros (Gentoo, Arch, Fedora, Ubuntu). I *was* using the same configs on all four (it's i3 + polybar) so it's likely that something from my config was triggering this behavior. The bar would become unresponsive randomly, and mostly after I restarted i3.

Interestingly, I stumbled upon a workaround that works remarkably well. If I open a floating window and close it when the bar goes into this situation the systray becomes responsive again.

In fact, I added a command to open floating alacritty terminal which just `sleep`s one second and exits. That fixed the issue on all the distros.

**Comment by crunchymetal** [comment]
Can confirm a floating window fixes the issue for me as well.

**Comment by Morantxu** [comment]
Same thing for me, any actual normal fit?

**Comment by ysl2** [comment]
Hey guys, I just found out it maybe caused by this:

```text
bottom = true
```

If `bottom = true`, polybar will show under the monitor. When I commented this, my system tray became normal.
