### ISSUE TITLE
Fonts don't display as they should

### ISSUE THREAD

**Issue by Franc160th** [jaagr/polybar#1746]
Hi there,
I'm using the example config of polybar and playing around with it. While changing some fonts I noticed that they don't behave as they should. Here's and example of how my clock is showing up:
[<a href="https://imgbb.com/"><img src="https://i.ibb.co/4jQSfJ8/2019-04-15-203404-1920x1080-scrot.png" alt="2019-04-15-203404-1920x1080-scrot" border="0"></a>](url)
And how the real characters are in gucharmap:
[<a href="https://imgbb.com/"><img src="https://i.ibb.co/4tYTRqw/2019-04-15-203655-1920x1080-scrot.png" alt="2019-04-15-203655-1920x1080-scrot" border="0"></a>](url)

In my config file there are these fonts:
`font-0 = "fixed:pixelsize=10;1"`
`font-1 = "unifont:fontformat=truetype:size=8:antialias=false;0"`
`font-2 = "siji:pixelsize=10;1"`
`font-3 = "DejaVu Sans Mono:style=Book:size=10:antialias=true;2"`

And in the date module I wrote:
`label = %date% %time%`
`label = %date% %time%`
'cause I wanted the DejaVu Sans Mono to be the clock's font.
Where am I wrong?
I'm running Polybar on Openbox in KDE Neon 15

**Comment by Lomadriel** [comment]
Your links don't work. However did you think to activate the option "Show only glyphs from this font"
![image](https://user-images.githubusercontent.com/10365269/56160603-979e2380-5f95-11e9-94c4-5037b9900fac.png)
See https://github.com/jaagr/polybar/wiki/Fonts#gnome-character-map for more information.

**Comment by patrick96** [comment]
Did you follow the [debugging font issues](https://github.com/jaagr/polybar/wiki/Fonts#debugging-font-issues) guide on the wiki?

**Comment by Franc160th** [comment]
> Your links don't work. However did you think to activate the option "Show only glyphs from this font"
> ![image](https://user-images.githubusercontent.com/10365269/56160603-979e2380-5f95-11e9-94c4-5037b9900fac.png)
> See https://github.com/jaagr/polybar/wiki/Fonts#gnome-character-map for more information.
> 
> EDIT:
> You can also use `label-font = 4` to select the "DejaVu Sans Mono" font.

There you go, links updated, sorry for the mistake. No, I didn't think to do so, but in Gucharmap the preview is still different from what I see. I'll try to put label-font = 4, thanks for the advice.



> Did you follow the [debugging font issues](https://github.com/jaagr/polybar/wiki/Fonts#debugging-font-issues) guide on the wiki?

Yep I did, but still no result

**Comment by patrick96** [comment]
The `-font` property is 1-indexed, so putting 4 will use the 4th font (`font-3`)
