### ISSUE TITLE
script: click not working because there is no /usr/bin/env sh

### ISSUE THREAD

**Issue by prankousky** [jaagr/polybar#1748]
Hi everybody,

I have a custom module like this

```
[module/test]
type = custom/script
exec = echo "test"
click-left = echo left %counter%
click-middle = echo middle %counter%
click-right = echo right %counter%
```

This is not the actual module I use, but it is easier to explain like this... This will display `test` in my polybar, which works. However, when I click on it, nothing happens. I took this example from the wiki. Also tried `click-left = notify-send test` to see whether or not I would get a test notification. Did not work. 

Wiki states that all click commands will be executed in `/usr/bin/env sh -c <command>`. For some reason, I cannot use this. When I type `/usr/bin/env sh -c notify-send test` in the terminal, I get `zsh: file or directory not found: /usr/bin/env sh -c bash notify-send test`.

I do have `sh`: `$ which sh` => `/usr/bin/sh`. 

I launch polybar like this

```
#!/usr/bin/env bash
if (pidof polybar); then
		killall polybar
fi

if [ "$MY_MONS" = "3" ]; then
	MONITOR=DP-1 polybar top &
	MONITOR=DP-2 polybar top &
	MONITOR=DP-3 polybar top
elif [ "$MY_MONS" = "1" ]; then
	MONITOR=DP-2 polybar -c $HOME/.config/polybar/config top
fi
```

This script works. It gets run by `i3` upon starting, and I can manually call it via keybinding. 

What am I doing wrong? Thanks for your support :+1:

**Comment by patrick96** [comment]
Some of the info on the wiki is a little unclear and/or misleading.

While the `click-*` command is executed, its output is not shown on the bar, so `click-left = echo left %counter%` will not have any effect, but `click-left = notify-send test` should.

Secondly, the wiki states that commands are executed with `/usr/bin/env sh -c [command]`, but that's not true, polybar executes `/bin/sh -c "[command]"` and optionally replaces `/bin/sh` with the contents of the environment variable `POLYBAR_SHELL`.

Nevertheless `/usr/bin/env sh -c notify-send test` should not give a shell error (it will give you an error from `notify-send`: `No summary specified`).

Two things you should try:

1. `/usr/bin/env sh -c "echo test"` should print `test` in your terminal and not give an error. If not, you have some weird shell setup. This is not a polybar issue.
2. Try running `/bin/sh -c "notify-send test"` if this gives you an error, this will also be the reason why polybar cannot execute it.

Finally what distribution are you running and what packages provide `/usr/bin/sh` and `/usr/bin/env`?

I will update the wiki to be more precise and correct.

**Comment by prankousky** [comment]
Thank you @patrick96 

I have tried your two suggested commands, and both of them work. I then tried to use `click-left = notify-send test` once more, and it worked. I don't know why, because I had not changed anything else in my config. But I had rebooted since the last time I tried. Maybe this was a temporary misbehaving.

So everything works fine now :) I am running `Arch 5.0.7-arch1-1-ARCH` and am actually not sure which packages provide these (nor how to find out).

**Comment by patrick96** [comment]
Great!

It's possible that your system was in some kind of a limbo state. The error message `zsh: file or directory not found: /usr/bin/env sh -c bash notify-send test` really is very strange. I myself couldn't reproduce any error message that is similar to it, I would only get `zsh:  no such file or directory: ...`

**Comment by prankousky** [comment]
I am German and my terminal output set accordingly. The output I quoted was manually translated by myself, so `zsh: no suche file or directory: ...` is probably what I would have gotten if my output was English.

**Comment by patrick96** [comment]
Ah, I see. Anyway if it works now it shouldn't matter too much.
