### ISSUE TITLE
Battery module not working

### ISSUE THREAD

**Issue by akofke** [jaagr/polybar#177]
The battery module no longer appears on my bar, giving the message 

```
error: Disabling module "battery" (error: The file '/sys/class/power_supply/BAT0/charge_now' does not exist)
```

I'm guessing it is [this commit](https://github.com/jaagr/polybar/commit/38f9ba81cdddf27c751b00653532baee25a313b8#diff-ff499b07bbc238b1a9f67ca7458184d8R74) which breaks it. On my laptop, an ASUS F556UA running Arch Linux, there is only

```
$ ls /sys/class/power_supply/BAT0 | sort
alarm
capacity
capacity_level
cycle_count
device
energy_full
energy_full_design
energy_now
manufacturer
model_name
power
power_now
present
serial_number
status
subsystem
technology
type
uevent
voltage_min_design
voltage_now
```

I found [this thread](http://comments.gmane.org/gmane.linux.acpi.devel/51602) which seems like a similar problem caused by Lenovo firmware so that may be related.

**Comment by jaagr** [comment]
Hi, I'll patch it by testing each possible filename

**Comment by jaagr** [comment]
Please verify if it works with the latest commit

**Comment by akofke** [comment]
It works now with this commit, thanks
