### ISSUE TITLE
New title module problem

### ISSUE THREAD

**Issue by Vintodrimmer** [jaagr/polybar#179]
Until I open my first programm, the bar that has only the title module is fully transparent. It is there, since compton draws the shadow, but invisible.

![polybar](https://raw.githubusercontent.com/Vintodrimmer/docs/master/polybar.png)

**Comment by jaagr** [comment]
6e35bcd should fix the issue, please verify

**Comment by Vintodrimmer** [comment]
Fixed, thanks!

**Comment by Vintodrimmer** [comment]
Happens again with the latest two versions.

**Comment by jaagr** [comment]
Do you get an error when starting?

**Comment by Vintodrimmer** [comment]
A couple of them, actually, but mostly about deprecated parameters. However I do launch it from terminal, which is a window, so the issue doesn't appear in such a case.
```
❰eichhorn❙~/.config/polybar❱✔≻ ./launch.sh ❰eichhorn❙~/.config/polybar❱✔≻ ./launch.sh 
Bars launched...
warn: The config parameter `bar/right.lineheight` is deprecated, use `{underline,overline}-size` instead.
warn: The config parameter `bar/middle.lineheight` is deprecated, use `{underline,overline}-size` instead.
warn: Disabling tray manager (reason: disabled in config)
warn: The config parameter `module/bspwm.label-active` is deprecated, use `label-focused and label-dimmed-focused` instead.
warn: Disabling tray manager (reason: disabled in config)
```
I will fix them, reboot and look again.

**Comment by Vintodrimmer** [comment]
Didn't help.

![screenshot](https://raw.githubusercontent.com/Vintodrimmer/docs/master/2016-12-02-14%3A57%3A32.png)

**Comment by jaagr** [comment]
Was able to reproduce it. Will try to find the commit that caused the issue to reappear.

**Comment by jaagr** [comment]
Found it. The problem was actually that the background color wasn't filled for the empty draw call.

**Comment by Vintodrimmer** [comment]
Works now, thanks!
