### ISSUE TITLE
i3 Module stops updating when i use a custom script

### ISSUE THREAD

**Issue by jonathashenriques** [jaagr/polybar#183]
My current config:

> ;==================================================;
;						   ;
;   To learn more about how to configure Polybar   ;
;   go to https://github.com/jaagr/polybar	   ;
;						   ;
;   The README contains alot of information	   ;
;						   ;
;==================================================;

[settings]

[bar/Bar]
bottom = false
dock = false
width = 100%
height = 24
padding-left = 3
padding-right = 1
module-margin-right = 2
modules-left = i3 Spotify
modules-center = Xtitle
modules-right = Wifi Volume Rofi Clock Shutdown
background = #00ffffff
foreground = #ffffff
tray-detached = true
tray-position = right
tray-offset-x = -286
tray-maxsize = 12
tray-padding = 22
font-0 = lemon-7,49262:syle=Regular;0
font-1 = -wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1;1

[module/i3]
type = internal/i3
label-focused = 
label-focused-padding = 2
label-unfocused = 
label-unfocused-padding = 2
label-unfocused-foreground = #4dffffff
label-urgent = 
label-urgent-padding = 2
label-visible = 
label-visible-padding = 2

[module/Spotify]
type = custom/script
exec = ~/.config/polybar/Scripts/Spotify/Spotify.sh
ellipsis = true
interval = 5
maxlen = 60
click-left = xdotool key super+z
click-right = xdotool key super+0
scroll-up = xdotool key super+0
scroll-down = xdotool key super+z
format-padding = 1

[module/Xtitle]
type = custom/script
exec = xtitle -s
ellipsis = true
tail = true
maxlen = 40

[module/Wifi]
type = internal/network
interface = wlp7s0
interval = 3.0
format-connected = <ramp-signal>
format-connected-padding = 2
ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
label-disconnected = 
format-disconnected-foreground = #4dffffff
format-disconnected-padding = 2

[module/Volume]
type = internal/volume
master-mixer = Master
speaker-mixer = Speaker
headphone-mixer = Headphone
headphone-id = 1
format-volume = <ramp-volume>
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-3 = 
ramp-headphones-0 = 
ramp-headphones-1 = 
format-volume-padding = 2
format-muted = <label-muted>
label-muted = 
format-muted-padding = 2

[module/Rofi]
type = custom/script
exec = echo ""
;click-left = echo "" | rofi -dmenu -p "Search:" -font "lemon 7" -width 350 -location 3 -xoffset -192 -yoffset 18 | xargs -I{} xdg-open https://www.google.com.br/search?q={}
click-left = ~/.config/polybar/Scripts/Search/Search.sh
format-padding = 2

[module/Clock]
type = internal/date
date = %a, %d %b | %H:%M
interval = 5
format-padding = 2

[module/Shutdown]
type = custom/script
exec = echo "    "
click-left = shutdown now
click-right = reboot
click-middle = xdotool key super+shift+e
format-padding = 1

**Comment by jonathashenriques** [comment]
Please, note that if i try use it in the click-left function, it do not work too.

**Comment by jaagr** [comment]
Just fixed an issue with click actions that probably fixes the click-left issue.. shouldn't affect the i3 updates tho

**Comment by jonathashenriques** [comment]
Sorry, the error still happening.

**Comment by jaagr** [comment]
yeah haven't fixed anything except actions (they didn't work at all between two commits)

**Comment by jonathashenriques** [comment]
I realized that a "done" command was missing in my script. Now everything is working fine. Closing the issue.

**Comment by jaagr** [comment]
ok nice!

**Comment by jonathashenriques** [comment]
Ok, looks like i3-module only updates when Chrome is already open. If i use the script when the browser is already closed, it do not updates at all until i kill Chrome process or reload i3.

**Comment by jaagr** [comment]
That's beacuse the bar is still waiting for the script to finish.

**Comment by jonathashenriques** [comment]
Your tip fixed the issue. Thank you !

**Comment by jaagr** [comment]
Will add it to the wiki
