### ISSUE TITLE
Click events broken for certain modules

### ISSUE THREAD

**Issue by NBonaparte** [jaagr/polybar#186]
Click events no longer work on the `script` and `date` modules (outputs `warn: No matching input area found`), but they still work on the `menu`, `bspwm`, and `mpd` modules. Others may or may not work; I have not tested them.

**Comment by jaagr** [comment]
Are they all aligned the same? Could be a problem with the content shifting. Try putting all in `modules-left`

**Comment by jaagr** [comment]
Should be fixed, could you verify

**Comment by NBonaparte** [comment]
Works now, thanks!
