### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by jhaasdijk** [jaagr/polybar#188]
- Every time I try to run the battery module it returns with: Disabling module "battery" (error: The file '/sys/class/power_supply/BAT0/charge_now' does not exist). It so happens that the i3status status bar finds the correct configuration of my battery and how to display it without a hassle. Would you happen to know what I need to adjust to be able to start using the "battery" module? I tried changing the name of another file in /sys/class/power_supply/BAT0/ to /sys/class/power_supply/BAT0/charge_now to see what happens but that didn't work as I was denied permissions to do this. (even as root)

- When I run nm-applet to configure my network settings the nm-applet icon stays present on the most right side of the Polybar status bar. Would you happen to know what causes this and (possibly) how to fix this? (Even after I shut down the bar and restart it)

Eagerly awaiting a response as the Polybar status bar looks really sleek. Good job!

**Comment by jaagr** [comment]
Hi and thanks.

What version of polybar are you running? `polybar -vv`

I'm not sure what you mean about the nm-applet icon. Do you not want to show it or is it positioned wrong?

**Comment by jhaasdijk** [comment]
Hi.

I'm currently running Polybar version 2.3.1

I do not want to show the icon. I wanted to connect to a new network, therefore I ran nm-applet, but after I'm done with this configuration the icon keeps showing on the right side of my bar. I have neither configured this nor do I actually want it to be there. It just somehow does not disappear. The icon disappears after a reboot so when automatically connecting to already known networks this is not an issue.

**Comment by jaagr** [comment]
You would need to update your version to `2.3.2`. This will fix the issue you are having with the battery module, since the code used to guess the correct file handle was added a few days ago.

The reason you see the nm-applet is because it's running in the background (`pgrep nm-applet` to the process id). You could terminate it using `killall nm-applet`.

If you want to disable support for system tray icons, you could remove the setting `tray-position` from the polybar configuration.

**Comment by jhaasdijk** [comment]
It did the trick.
Running the command `polybar -vv ` actually returned 2.3.1 for me while `version.sh` returned 2.3.2 .
Anyhow I did a fresh clone from github, rebuild the project and the battery module displayed just nicely. Thanks!

As for the nm-applet icon, this now displays an updated icon which I like much better. It has earned a permanent spot on my bar.
Thanks for the quick response and have a nice day :+1:

**Comment by jaagr** [comment]
`polybar -v` print the version of the binary and `./version.sh` prints the version of the source.

Thank you, and please report any other issues you may bump in to.
