### ISSUE TITLE
Crashes cinnamon

### ISSUE THREAD

**Issue by DrPandemic** [jaagr/polybar#189]
**Problem**
Launching polybar 2.3.2 crashes my cinnamon window manager. The application bars (the one used to move/close/expand the windows) disappear and I'm unable to do anything releated to the windows.

I tried to use the example config and it also crashes cinnamon.

**What's working**
I successfully ran polybar
- 2.2.8
- 2.3.0
- 2.3.1

**Setup**
- Arch 4.8.10-1-ARCH
- Cinnamon 3.2.1
- Polybar 2.3.2 https://aur.archlinux.org/packages/polybar/

**Comment by jaagr** [comment]
Do you get any error message or something to indicate why it crashes?

**Comment by DrPandemic** [comment]
I had difficulties finding meaningful logs. The only thing I found was by saving the console output of  Xorg launch.

```
(cinnamon:7580): Cogl-WARNING **: shmget failed

(cinnamon:7580): Gdk-WARNING **: cinnamon: Fatal IO error 25 (Inappropriate ioctl for device) on X server :0.

Traceback (most recent call last):
  File "/usr/bin/cinnamon-launcher", line 42, in <module>
    os.execvp(FALLBACK_COMMAND, (FALLBACK_COMMAND,) + FALLBACK_ARGS)
  File "/usr/lib/python3.5/os.py", line 615, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.5/os.py", line 660, in _execvpe
    raise last_exc.with_traceback(tb)
  File "/usr/lib/python3.5/os.py", line 650, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

There's other logs around, but I don't think they would be useful.

**Comment by jaagr** [comment]
Does it work if you disable the network module?

**Comment by DrPandemic** [comment]
No, but polybar produced 
```
error: Invalid _XEMBED_INFO for window 0x360003f
```

**Comment by jaagr** [comment]
I'll install cinnamon and have a look

**Comment by jaagr** [comment]
Had no problem launching it under cinnamon. Could you show me your cinnamon init script?

**Comment by DrPandemic** [comment]
I'm not sure what you are referencing by `cinnamon init script`. But my `~/.xinitrc` is really generic.

```bash
#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[ -f /etc/xprofile ] && source /etc/xprofile
[ -f ~/.xprofile ] && source ~/.xprofile

exec cinnamon-session
#exec gnome-session
```

I tried to start cinnamon without any auto starting application and the crash is still happening. I also tried with a minimal amount of module on my polybar.

When I'll have some time (someday next week), I'll try to find which commit is the issue.

**Comment by jaagr** [comment]
It's really hard without any debug info. Have you tried the latest version by the way? You could also try to disable the system tray to see if it's causing any trouble by removing the `tray-position` parameter in the config.

**Comment by DrPandemic** [comment]
I tried to remove `tray-position`. Also, I was finally able to get some logs. While crashing cinnamon produce
```
(cinnamon:6750): Cogl-WARNING **: shmget failed

(cinnamon:6750): Gdk-WARNING **: cinnamon: Fatal IO error 22 (Invalid argument) on X server :0.
```

But, I just compiled the last master `polybar 2.3.5-2-g6f6c5b7-git` and it's not crashing anymore! Thanks for your time
