### ISSUE TITLE
Mpd Icons Not Displayed

### ISSUE THREAD

**Issue by cj360** [jaagr/polybar#190]
There is space on the bar for them but the icons are not shown and clicking the area gives "warn: No matching input area found."  
[screenshot](https://goo.gl/photos/t2mzDFrujEdV5tWPA)

`[module/mpd]`
`type = internal/mpd`

`host     = 127.0.0.1`
`port     = 6600`
`interval = 2`

`format-online = <icon-prev> <icon-seekb> <icon-stop> <toggle> <icon-seekf> <icon-next>  <icon-repeat>` `<icon-random>  <label-time>  <label-song>`

`label-song    = %artist% - %title%`
`label-offline = ---`

`icon-prev = `
`icon-seekb = `
`icon-stop = `
`icon-play = `
`icon-pause = `
`icon-next = `
`icon-seekf = `

`icon-random = `
`icon-repeat = `

`toggle-on-foreground = #e60053`
`toggle-off-foreground = #66`

Is it my config that's incorrect? I don't see any errors relating to mpd when I launch the config in termite.

**Comment by jaagr** [comment]
Does the mpd playlist contain any songs?

**Comment by cj360** [comment]
Yeah 414.

**Comment by jaagr** [comment]
Try replacing the `icon-<name> = ...` settings to see if it's a font issue.

**Comment by cj360** [comment]
D'oh! Would help if I told the bar to load the font wouldn't it...

`font-0 = fixed:pixelsize=12;0`
`;font-1 = unifont:size=6:heavy:fontformat=truetype;-2`
`;font-2 = siji:pixelsize=12;0`

`font-1 = unifont:size=6:heavy:fontformat=truetype;-2`
`font-2 = FontAwesome:pixelsize=12;0`

**Comment by jaagr** [comment]
Did it fix the problem?

**Comment by cj360** [comment]
Yup

**Comment by jaagr** [comment]
Great
