### ISSUE TITLE
Script action block unclosed

### ISSUE THREAD

**Issue by NBonaparte** [jaagr/polybar#192]
**Steps to reproduce error:**
Create script module and declare any `click-*` or `scroll-*` option

**Expected result:**
Actions work normally

**Actual result:**
`error: Failed to parse contents (reason: 1 unclosed action block(s))`, performing the action results in `warn: No matching input area found`

Actions seem to work on the rest of my blocks (bspwm, mpd, volume, date).
EDIT: I think it's missing `cmd_close()`.

**Comment by jaagr** [comment]
Could you try with the latest commit? Forgot to update some of the modules when I changed the builder.

**Comment by NBonaparte** [comment]
Fixed, thanks!
