### ISSUE TITLE
NOT AN ISSUE, JUST A SUGESTION

### ISSUE THREAD

**Issue by jonathashenriques** [jaagr/polybar#193]
Hi, Jaagr. So, i've see on the wiki, that the volume module only supports AlSA. But i'm using it for a long time with pulseaudio with no problems. Seems like it only shows some erros if i install the pulseaudio-alsa lib, otherwise everything works just fine. Maybe you should put this info on the wiki.

**Comment by jaagr** [comment]
Thanks, I've added a note about it to the wiki.

**Comment by jonathashenriques** [comment]
No problem, but please note that if you install an alsa backend to pulseaudio it will not work. Seems like is wrong on the wiki or maybe i didn't made myself clear.

**Comment by jaagr** [comment]
You can update the wiki page if you want to change it. I'm not using pulseaudio myself so I'm not too familiar with it.

**Comment by jonathashenriques** [comment]
Wiki updated.

**Comment by jaagr** [comment]
oh, it was the exact opposite of what i wrote then ;)

**Comment by jonathashenriques** [comment]
Haha, it's my fault, i and my bad english ;)
