### ISSUE TITLE
xdo no effect on panel

### ISSUE THREAD

**Issue by sg3des** [jaagr/polybar#194]
Early, on **lemonbuddy**, i'm used **xdo** *raise*/*lower* to hide or show panel. But now, this is not work...

**Comment by jaagr** [comment]
What WM are you using?

**Comment by sg3des** [comment]
WM: bspwm
on tint2 and lemonbar xdo works normally

**Comment by jaagr** [comment]
There's no need for xdo. Just set the config option `wm-restack = bspwm`

**Comment by sg3des** [comment]
not exactly, you did not understand me.
`wm-restack` - It is making so that the panel has always been above other windows.

I want differently - bar is always hidden/lower, below all windows. 
when key(super) is pressed, bar appears - `xdo raise -a polybar`
when key is released, bar hides again. - `xdo lower -a polybar`

**Comment by jaagr** [comment]
`wm-restack` should put the window under all other windows except the root window.

**Comment by jaagr** [comment]
Just tried `xdo lower 0x1a00003` and `xdo raise 0x1a00003` and it works fine for me.

**Comment by jaagr** [comment]
It requires `dock = true` because it doesn't work if I remove if.

**Comment by jaagr** [comment]
try `xdo lower -N Polybar` and `xdo raise -N Polybar`

**Comment by jaagr** [comment]
To clarify: the `-a` compares the `WM_NAME` value which is `polybar-(top|bottom)_(monitor)` by default

**Comment by sg3des** [comment]
yes, you right! thx!
also works full name: `xdo raise -a polybar-mainbar_HDMI-0`
