### ISSUE TITLE
Panel frickers periodically.

### ISSUE THREAD

**Issue by Vintodrimmer** [jaagr/polybar#195]
On my right panel there are 5 modules: volume, battery, RAM, CPU and time.

From time to time it looks as if it reloads. The panel disappears and instantly reappears.

**Comment by jaagr** [comment]
I'll have a look.. been moving around alot of code that deals with the drawing.

**Comment by Vintodrimmer** [comment]
Thanks. It looks like the panel with titles module is also affected.

**Comment by jaagr** [comment]
Are you launching the bar with the `--reload` flag by the way?

**Comment by jaagr** [comment]
Could you also post your config and `$ polybar -vv`

**Comment by Vintodrimmer** [comment]
It seems that panel just becomes invisible after some time. And it stays invisible, until I do something like opening browser or change desktop.

I did not specify `--reload` explicitly

[My config](https://paste.pound-python.org/show/1zpzcIwdAw995yBZ8aIY/)

```
❰eichhorn❙~❱✔≻ polybar -vv
polybar 2.3.4 

Features: +alsa -i3 -mpd -network 

Build type: Release
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -Wall -Wextra -Werror -O3 -pedantic -pedantic-errors -fno-stack-protector -ffunction-sections -fdata-sections
Linker flags:  -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,--gc-sections

ALSA_SOUNDCARD              default
BSPWM_SOCKET_PATH           /tmp/bspwm_0_0-socket
BSPWM_STATUS_PREFIX         W
BUILDER_SPACE_TOKEN         %__
CONNECTION_TEST_IP          8.8.8.8
PATH_ADAPTER                /sys/class/power_supply/%adapter%
PATH_BACKLIGHT_MAX          /sys/class/backlight/%card%/max_brightness
PATH_BACKLIGHT_VAL          /sys/class/backlight/%card%/brightness
PATH_BATTERY                /sys/class/power_supply/%battery%
PATH_CPU_INFO               /proc/stat
PATH_MEMORY_INFO            /proc/meminfo
PATH_TEMPERATURE_INFO       /sys/class/thermal/thermal_zone%zone%/temp
```

**Comment by jaagr** [comment]
Been running it for an hour now and I haven't had any issues. What WM are you using?

**Comment by jaagr** [comment]
Not sure if this will make any difference, but I removed an unnecessary clear call c4822b7

**Comment by Vintodrimmer** [comment]
Strange, I'm using bspwm with nothing more.

Will try the new version. It mostly happened while my laptop is idle, for example, when I read the same pdf page in zathura for 5 minutes.

**Comment by Vintodrimmer** [comment]
Looks like it worked. Thanks.

**Comment by jaagr** [comment]
Great
