### ISSUE TITLE
escape sequence in click-left action in custom/script

### ISSUE THREAD

**Issue by applejo** [jaagr/polybar#197]
I'm using a module with "type = custom/script" with "exec = $HOME/.polybar/bin/updates" which works perfectly. 
But in the "click-left" action in the same module my "$HOME/.polybar/bin/updates -d" gets executed as "* Executing shell command: \$HOME/.polybar/bin/updates -d" which does not work due to the escape sequence.
As a workaround I'm currently using the absolute path but I thought this behavior is not expected.

polybar 2.3.5 on Archlinux with i3wm

**Comment by jaagr** [comment]
Until it's been fixed you could use `~/` instead

**Comment by jaagr** [comment]
Fixed by https://github.com/jaagr/polybar/commit/e9db3fab3a84a4ef8f360de15c60f052ef3dd56e
