### ISSUE TITLE
Error: unclosed action blocks

### ISSUE THREAD

**Issue by cdubthecoolcat** [jaagr/polybar#198]
I get an error which says that all of my action blocks are unclosed, yet they are closed.  It was working in version 2.3.2 but stopped working in 2.3.3.  I have not changed my scripts since then.  I'm on arch on bspwm.

**Comment by NBonaparte** [comment]
This was fixed in 2.3.4; try updating and seeing if the issue persists.

**Comment by cdubthecoolcat** [comment]
I've tried both 2.3.4 and 2.3.5 and they give me the same error.

**Comment by jaagr** [comment]
What version are you running? `polybar -v`

**Comment by cdubthecoolcat** [comment]
I had gone back to 2.3.2 because that's the last version that was working.  2.3.3, 2.3.4, and 2.3.5 all give me the same error.

**Comment by cdubthecoolcat** [comment]
Well somehow reformatting my config file fixed it. I'm not sure what I did but it works now. Thanks!
