### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by Jayanth-kumar5566** [jaagr/polybar#199]
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Found X11_XCB: /usr/lib/x86_64-linux-gnu/libX11-xcb.so  
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
CMake Error at /usr/local/share/cmake-3.7/Modules/FindPkgConfig.cmake:470 (message):
  pkg-config tool not found
Call Stack (most recent call first):
  /usr/local/share/cmake-3.7/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  src/CMakeLists.txt:41 (pkg_check_modules)

-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
CMake Error at /usr/local/share/cmake-3.7/Modules/FindPkgConfig.cmake:470 (message):
  pkg-config tool not found
Call Stack (most recent call first):
  /usr/local/share/cmake-3.7/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  lib/xpp/CMakeLists.txt:10 (pkg_check_modules)

-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.9", minimum required is "2.7") 
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- XCB[XCB]: Found component XCB
-- Found XCB_XCB: /usr/lib/x86_64-linux-gnu/libxcb.so  
-- XCB[ICCCM]: Found component ICCCM
-- Found XCB_ICCCM: /usr/lib/x86_64-linux-gnu/libxcb-icccm.so  
-- XCB[EWMH]: Found component EWMH
-- Found XCB_EWMH: /usr/lib/x86_64-linux-gnu/libxcb-ewmh.so  
-- XCB[UTIL]: Found component UTIL
-- Found XCB_UTIL: /usr/lib/x86_64-linux-gnu/libxcb-util.so  
-- XCB[IMAGE]: Found component IMAGE
-- Found XCB_IMAGE: /usr/lib/x86_64-linux-gnu/libxcb-image.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so  
-- Searching for xcbgen with python2
-- Found xcbgen in /usr/lib/python2.7/dist-packages
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- XCB[RANDR]: Found component RANDR
-- Found XCB_RANDR: /usr/lib/x86_64-linux-gnu/libxcb-randr.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so;/usr/lib/x86_64-linux-gnu/libxcb-randr.so  
-- xpp: including xcb proto randr.xml
-- xpp: including xcb proto xproto.xml
-- Found ALSA: /usr/lib/x86_64-linux-gnu/libasound.so (found version "1.0.28") 
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Found LibMPDClient: /usr/lib/libmpdclient.so  
-- Found Libiw: /usr/lib/x86_64-linux-gnu/libiw.so  
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Could not find jsoncpp>=1.7.7 -- building static lib...
-- JsonCpp Version: 1.7.7
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.9", minimum required is "2.6") 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
X11_Xft_LIB (ADVANCED)
    linked by target "polybar" in directory /home/jhome/.i3/polybar/src
    linked by target "unit_test.utils_math" in directory /home/jhome/.i3/polybar/tests
    linked by target "unit_test.utils_memory" in directory /home/jhome/.i3/polybar/tests
    linked by target "unit_test.utils_string" in directory /home/jhome/.i3/polybar/tests
    linked by target "unit_test.x11_color" in directory /home/jhome/.i3/polybar/tests
    linked by target "unit_test.components_command_line" in directory /home/jhome/.i3/polybar/tests
    linked by target "unit_test.components_di" in directory /home/jhome/.i3/polybar/tests
    linked by target "unit_test.utils_color" in directory /home/jhome/.i3/polybar/tests

-- Configuring incomplete, errors occurred!
See also "/home/jhome/.i3/polybar/build/CMakeFiles/CMakeOutput.log".
See also "/home/jhome/.i3/polybar/build/CMakeFiles/CMakeError.log".
** Failed to generate build... read output to get a hint of what went wrong

**Comment by Jayanth-kumar5566** [comment]
This is what I get. Any Ideas how to correct them. I have installed all the dependencies

**Comment by jaagr** [comment]
Hi. You need `pkg-config`
