### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by ar3s3ru** [jaagr/polybar#202]
Polybar CPU usage reaches 100% occasionally.
Configuration file [here](https://gist.github.com/ar3s3ru/9972d370c15907f3e6fc70e6302a942f)

Tried starting polybar from terminal; when having high CPU usage, I got this warn:
     ```warn: No suitable font found (character=65533)```

SIGKILL is the only signal that would terminate the process.

**Comment by ar3s3ru** [comment]
Doing some researches, it seems like module/xtitle should be responsible for said issue
The module is the same found on the "Custom scripts" section of the wiki

**Comment by jaagr** [comment]
It has been replaced by the new module `xwindow`

Replace it by:

~~~ dosini
[module/xwindow]
type = internal/xwindow
label-maxlen = 60
~~~

**Comment by jaagr** [comment]
Closing for now, please re-open if you notice any more issues.

**Comment by ar3s3ru** [comment]
It happens even without xtitle/xwindow module attached to the bar.
Received warn now is as follow:

```
ar3s3ru [~] → polybar top_bar
warn: No suitable font found (character=127)
```

**Comment by jaagr** [comment]
what version? `polybar -vv`

**Comment by ar3s3ru** [comment]
```
polybar 2.3.10-5-g16b7d09-git 

Features: +alsa +i3 +mpd +network 

Build type: Release
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -Wall -Wextra -Werror -O3 -pedantic -pedantic-errors -ffunction-sections -fdata-sections
Linker flags:  -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,--gc-sections

ALSA_SOUNDCARD              default
BSPWM_SOCKET_PATH           /tmp/bspwm_0_0-socket
BSPWM_STATUS_PREFIX         W
BUILDER_SPACE_TOKEN         %__
CONNECTION_TEST_IP          8.8.8.8
PATH_ADAPTER                /sys/class/power_supply/%adapter%
PATH_BACKLIGHT_MAX          /sys/class/backlight/%card%/max_brightness
PATH_BACKLIGHT_VAL          /sys/class/backlight/%card%/brightness
PATH_BATTERY                /sys/class/power_supply/%battery%
PATH_CPU_INFO               /proc/stat
PATH_MEMORY_INFO            /proc/meminfo
PATH_TEMPERATURE_INFO       /sys/class/thermal/thermal_zone%zone%/temp
```

**Comment by jaagr** [comment]
could you post the contents of `/home/ar3s3ru/.config/scripts/battery_time.py`

**Comment by xintron** [comment]
I seem to have the same issue. Tailing custom/script seems to cause a thread that uses 6-10% CPU per thread/script.

The scripts themselves are very lightweight, listening for DBus events and only send output when that happens (roughly every 2-5 seconds). Disabling my scripts results in barely any CPU usage at all.

Not sure if this should be reopened or if I should file a new issue.

**Comment by jaagr** [comment]
Could you link the script(s)?

**Comment by xintron** [comment]
One example that still reprocudes this:

```
[module/cputail]
type = custom/script
exec = tail -n1 -f /tmp/test.txt
tail = true
```

Then echo out `echo "foobar" > /tmp/test.txt` to update. It still uses ~7% CPU on one core when it's idle (no new text written to /tmp/test.txt). /tmp/test.txt is a fifo in this case (`mkfifo /tmp/test.txt`).

**Comment by jaagr** [comment]
The fd poll wasn't blocking so with no sleep interval set it would just hog the cpu... I'll fix that

**Comment by jaagr** [comment]
5773b08cf8709a2b8642f45b5e2f5560df332e22 should fix it

**Comment by xintron** [comment]
https://github.com/jaagr/polybar/commit/5773b08cf8709a2b8642f45b5e2f5560df332e22 indeed fixed it. Thanks for the quick fix. This should hopefully improve battery life as well (which I've noticed been a bit worse with polybar compared to taffybar, but there might be other variables in play as well though).

**Comment by jaagr** [comment]
@xintron yeah there are alot of improvements that can be made to improve that.. maybe we should create a battery-mode that limits the update events, etc
