### ISSUE TITLE
json_value.cpp error declaration

### ISSUE THREAD

**Issue by nullrndtx** [jaagr/polybar#203]
OS: Ubuntu 14.04 amd64
CMake version: 3.7.0
GCC version: 4.8.4

![Error](https://a.uguu.se/cbd326fmcnJA_error.png "Error")

**Comment by jaagr** [comment]
gcc 4.8 doesn't support c++14.. install a newer version of gcc o try clang

**Comment by nullrndtx** [comment]
is okay if i using musl-gcc ?

**Comment by jaagr** [comment]
yeah
