### ISSUE TITLE
xwindow

### ISSUE THREAD

**Issue by ostanovka777** [jaagr/polybar#205]
xwindow module uncorrect show russian title window in firefox  
![alt text](https://pp.vk.me/c626327/v626327184/4118f/hM_EP0HJhiE.jpg "Logo Title Text 1")

**Comment by jaagr** [comment]
Will push a fix

**Comment by jaagr** [comment]
d67515d should fix it, please verify

**Comment by ostanovka777** [comment]
cann't build after fix
![alt text](http://infoshield.pro/build.png)

**Comment by jaagr** [comment]
Should be fixed now

**Comment by ostanovka777** [comment]
Yeap, fixed
