### ISSUE TITLE
i3 and resize window

### ISSUE THREAD

**Issue by ostanovka777** [jaagr/polybar#206]
panel dont show when resize is active
![alt text](https://pp.vk.me/c626327/v626327184/411cf/V3qPEWJ40Kg.jpg)

**Comment by jaagr** [comment]
Not sure what you mean... does it disappear?

**Comment by ostanovka777** [comment]
No, doesnt disapperar. panel doesnt displayed resize mode

**Comment by jaagr** [comment]
oh.. yeah that's not implemented yet.. will add it soon

**Comment by ostanovka777** [comment]
Thanks)

**Comment by jaagr** [comment]
9cadb68 adds support for `format = <label-mode>`
