### ISSUE TITLE
Unicode problem in window title

### ISSUE THREAD

**Issue by delehef** [jaagr/polybar#210]
Using the `internal/xwindow` module, window titles using non-english characters (French accents, Cyrillic for instance) display erroneously.

**Comment by jaagr** [comment]
Are you using the latest version? d67515d should fix it

**Comment by jaagr** [comment]
Also make sure that you are loading a font that supports the characters. (warning will be printed otherwise)

**Comment by delehef** [comment]
Hmm, that's weird. I'm using either Terminus or DejaVu Sans Mono, and I know that both can display French & Cyrillic characters, as it works in my mpd custom script widget (cf. screenshot)
![unicode](https://cloud.githubusercontent.com/assets/1153808/20859679/6463d8c6-b965-11e6-8632-1c6c65b27c2c.png)

. However, I get the _Non suitable font found_ that you mention. But AFAIU, the characher #1744 mentioned in the error output is an [arabic character](http://unicode-table.com/fr/search/?q=1744), instead of being a cyrillic S (_С_).

```
warn: No suitable font found (character=1744)
warn: No suitable font found (character=1304)
warn: No suitable font found (character=1816)
warn: No suitable font found (character=2098)
warn: No suitable font found (character=47198)
warn: No suitable font found (character=26264)
warn: No suitable font found (character=1632)
warn: No suitable font found (character=1947)
warn: No suitable font found (character=1680)
```
![Uploading unicode.png…]()

**Comment by jaagr** [comment]
What version are you using? `polybar -v`

**Comment by delehef** [comment]
OK, nevermind, I thought I was on master and I wasn't.

Sorry for the incovenience.

**Comment by jaagr** [comment]
shit happens :-)
