### ISSUE TITLE
System tray remains visible on top of fullscreen apps

### ISSUE THREAD

**Issue by romovs** [jaagr/polybar#211]
![fullscreen](https://cloud.githubusercontent.com/assets/2727288/20835860/6720e880-b8a5-11e6-88f1-1b186fd59514.png)
That's mplayer in fullscreen mode behind the systray.
I have `wm-restack = i3` set. Tried to use compton compositor, but it didn't help.

[config](http://pastebin.com/HNByVpL6)

**Comment by kingkobra87** [comment]
I'm also having this problem in i3 since stable release 2.3.7-1 from the AUR. I don't recall this being an issue in version 2.3.5-1 or earlier.

**Comment by jaagr** [comment]
Might be related to d5587bf, will try to reproduce it myself

**Comment by jaagr** [comment]
22f3af9 fixes the issue, please verify

**Comment by romovs** [comment]
Fixed, thanks!
