### ISSUE TITLE
Mpd not working on polybar.

### ISSUE THREAD

**Issue by Sup3r-Us3r** [jaagr/polybar#213]
* Hello the polybar bar does not show the mpd like in that image.
> https://u.teknik.io/x32YI.png
-------------------------
Here is the mpd configuration in the file ~/.config/polybar/config

`Polybar`
![Polybar][screenshot1]

[screenshot1]:http://i.imgur.com/tm3SJdq.png

-------------------------
Here is my Mpd configuration

`Mpd`
![Mpd][screenshot2]

[screenshot2]:http://i.imgur.com/PrqjrQN.png

-------------------------

> I already installed the package "libmpdclient" and it did not solve the problem, and also compiled again and nothing.

**Comment by srvinii** [comment]
I'm also with this problem, he doesn't show nothing on mpd bar place.

**Comment by jaagr** [comment]
Is `mpd` listed in `modules-{left,center,right}` ?

**Comment by Sup3r-Us3r** [comment]
Sorry, I started using your bar today problem solved thank you.

**Comment by jaagr** [comment]
@Sup3r-Us3r I actually removed it from the example config a few days ago because there wasn't enough space for it on small displays. Will update the wiki to avoid confusion.
