### ISSUE TITLE
Error with scripts modules

### ISSUE THREAD

**Issue by jonathashenriques** [jaagr/polybar#214]
After the last update polybar shows "What(): Resource deadlock avoided" on custom scripts modules. And, i dont know why, but my pc starts freezing a lot now, when i start the bar.
Edit.: If i disable the scripts modules, the pc stops freezing.

> [settings]
 
[bar/Bar]
bottom = false
dock = false
wm-restack = i3
width = 100%
height = 24
padding-left = 3
padding-right = 1
module-margin-right = 2
modules-left = i3 Spotify
modules-center = Xwindow
modules-right = Wifi Volume Search Clock Shutdown
background = #00ffffff
foreground = #ffffff
tray-detached = true
tray-position = right
tray-offset-x = -266
tray-maxsize = 12
tray-padding = 22
font-0 = lemon-7,49262:syle=Regular;0
font-1 = -wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1;1
 
[module/i3]
type = internal/i3
label-focused = 
label-focused-padding = 2
label-unfocused = 
label-unfocused-padding = 2
label-unfocused-foreground = #4dffffff
label-urgent = 
label-urgent-padding = 2
label-urgent-foreground = #ffffff
label-visible = 
label-visible-padding = 2
label-visible-foreground = #4dffffff
 
[module/Spotify]
type = custom/script
exec = ~/.config/polybar/Scripts/Spotify/Spotify.sh
ellipsis = true
interval = 5
maxlen = 40
click-left = xdotool key super+z
click-right = xdotool key super+0
scroll-up = xdotool key super+0
scroll-down = xdotool key super+z
format-padding = 1
 
[module/Xwindow]
type = internal/xwindow
label-maxlen = 40
 
[module/Wifi]
type = internal/network
interface = wlp7s0
interval = 3
format-connected = <ramp-signal>
ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
format-connected-padding = 2
label-disconnected = 
format-disconnected-foreground = #4dffffff
format-disconnected-padding = 2
 
[module/Volume]
type = internal/volume
mapping = true
headphone-mixer = Headphone
headphone-id = 1
speaker-mixer = Speaker
format-volume = <ramp-volume>
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-3 = 
ramp-headphones-0 = 
ramp-headphones-1 = 
format-volume-padding = 1
label-muted = 
format-muted-foreground = #4dffffff
format-muted-padding = 1
 
[module/Search]
type = custom/script
exec = echo " "
click-right = ~/.config/polybar/Scripts/Search/Search.sh
format-padding = 1
 
[module/Clock]
type = internal/date
date = %a, %d %b | %H:%M
interval = 5
format-padding = 2
 
[module/Shutdown]
type = custom/script
exec = echo "   "
click-left = shutdown now
click-right = reboot
click-middle = xdotool key super+shift+e
format-padding = 1

**Comment by jaagr** [comment]
5f6d73a fixes this, please verify

**Comment by jonathashenriques** [comment]
This fixed the issue. Thank you very much !
