### ISSUE TITLE
Alsa volume showing different value

### ISSUE THREAD

**Issue by edgard** [jaagr/polybar#215]
Hey, another small one, it seems that the volume module is showing a different value from the one set.

For example, I have the volume set at 30% and it's showing 29% on the bar, something like an off-by-one at any volume.

https://u.teknik.io/QhEqN.png

**Comment by jaagr** [comment]
Are you using `mapped = true` ?

**Comment by edgard** [comment]
Nope, tried with with true and false and both shows a different volume.

```
[module/volume]
type                  = internal/volume
format-volume-padding = 1
format-muted-padding  = 1
format-volume         = <ramp-volume>  <label-volume>
label-volume          = %percentage%
label-muted           = 
ramp-volume-0         = 
ramp-volume-1         = 
ramp-volume-2         = 
```

**Comment by edgard** [comment]
Ugh, just saw #184, will close this in favor of that one. Same issue.
