### ISSUE TITLE
Xft fonts look stretched

### ISSUE THREAD

**Issue by d125q** [jaagr/polybar#220]
It it just me or do Xft fonts drawn by `polybar` look very stretched?

Look at a comparison of `polybar` and `xmobar`, both using `Cousine-8` as an Xft font:
![polybar](https://cloud.githubusercontent.com/assets/7765538/20865173/6439d84a-ba0b-11e6-993a-ff47b9b83153.png)
![xmobar](https://cloud.githubusercontent.com/assets/7765538/20865175/69f67c20-ba0b-11e6-9ca9-07f71d554aa6.png)

**Comment by jaagr** [comment]
could you paste your config and `xrdb -q`

**Comment by binaryplease** [comment]
@jaagr  Im having this issue too (or a similar one). 
This is the output of xrdb -q

```
Xft*dpi:	125.37
Xft*antialias:	true
Xft*hinting:	full
*.foreground:	#F8F8F2
*.background:	#282A36
*.cursorColor:	#5C6370
*.highlightColor:	#3A3F4B
*.color0:	#000000
*.color8:	#4D4D4D
*.color1:	#FF5555
*.color9:	#FF6E67
*.color2:	#50FA7B
*.color10:	#5AF78E
*.color3:	#F1FA8C
*.color11:	#F4F99D
*.color4:	#BD93F9
*.color12:	#CAA9FA
*.color5:	#FF79C6
*.color13:	#FF92D0
*.color6:	#8BE9FD
*.color14:	#9AEDFE
*.color7:	#BFBFBF
*.color15:	#E6E6E6
URxvt.saveLines:	10000
URxvt.scrollstyle:	rxvt
URxvt.termName:	xterm-256color
URxvt.urgentOnBell:	True
URxvt.cursorBlink:	True
URxvt.iso14755:	false
URxvt.iso14755_52:	false
URxvt*scrollWithBuffer:	true
URxvt*scrollTtyKeypress:	true
URxvt*scrollTtyOutput:	false
URxvt*secondaryScreen:	1
URxvt*secondaryScroll:	0
URxvt*.font:	-*-terminus-medium-*-*-*-14-*-*-*-*-*-*-*, xft:DejaVu Sans Mono:size=8, xft:Unifont:size=8
URxvt*.boldfont:	-*-terminus-bold-*-*-*-14-*-*-*-*-*-*-*, xft:DejaVu Sans Mono:size=8:style=bold, xft:Unifont:size=8:style=bold
URxvt*.italicfont:	-*-terminus-medium-*-*-*-14-*-*-*-*-*-*-*, xft:DejaVu Sans Mono:size=8:style=italic, xft:Unifont:size=8:style=italic
URxvt.internalBorder:	10
URxvt.scrollBar:	False
URxvt.keysym.Shift-Control-C:	perl:clipboard:copy
URxvt.keysym.Shift-Control-V:	perl:clipboard:paste
URxvt.clipboard.autocopy:	true
URxvt.copyCommand:	xclip -i -selection clipboard
URxvt.pasteCommand:	xclip -o -selection clipboard
URxvt.perl-ext-common:	default,matcher,clipboard,keyboard-select,resize-font
URxvt.matcher.button:	1
URxvt.urlLauncher:	xdg-open
URxvt.urlButton:	1
URxvt.underlineURLs:	True
rofi.fuzzy:	true
rofi.modi:	run,ssh,window
rofi.hide-scrollbar:	true
rofi.separator-style:	solid
rofi.font:	Roboto Mono 14
rofi.fullscreen:	true
rofi.lines:	3
rofi.padding:	400
rofi.eh:	2
rofi.color-enabled:	true
rofi.color-window:	#1e1f29, #1e1f29, #57c7ff
rofi.color-normal:	#1e1f29, #e2e4e5, #1e1f29, #4f4b59, #f1f1f0
rofi.color-active:	#1e1f29, #57c7ff, #1e1f29, #4f4b59, #57c7ff
rofi.color-urgent:	#1e1f29, #ff5c57, #1e1f29, #4f4b59, #ff5c57
Emacs.menuBar:	0
Emacs.toolBar:	0
Emacs.verticalScrollBars:	off
Emacs.FontBackend:	xft,x
Emacs.font:	Terminus:pixelsize=14
```

Polybar looks like this, which is definitely not right.
![image](https://user-images.githubusercontent.com/1719781/59374268-c0e7ef80-8d4b-11e9-84bd-5cda8c608b9b.png)

With the terminus bitmap font, everything is normal. I have set my xserver to 125.37 DPI

**Comment by Lomadriel** [comment]
If I'm not wrong the font on your screenshot looks like "DejaVu  Sans", in general this is the default font on many linux distributions, it signifies that polybar was unable to find "Terminus", I recommend you to verifies that your font is correctly loaded with this page:
https://github.com/polybar/polybar/wiki/Fonts

**Comment by patrick96** [comment]
Please don't necro post on 2.5 year old issues, open a a new one if you think it's a bug otherwise look at our [Support page](https://github.com/polybar/polybar/blob/master/SUPPORT.md) as suggested.

Polybar doesn't use Xft anymore to load any fonts, we use fontconfig, so your issue is definitely not the same.
