### ISSUE TITLE
Can't set bar-progress-empty to a single space

### ISSUE THREAD

**Issue by mrkgnao** [jaagr/polybar#221]
I tried `bar-progress-empty = " "`, but that didn't work. It just printed a bunch of raw `"` everywhere.

**Comment by jaagr** [comment]
that's an easter egg.

**Comment by mrkgnao** [comment]
:D

what if I'm ... allergic to, uh, egg protein?

**Comment by jaagr** [comment]
hehe, I'll have a look

**Comment by mrkgnao** [comment]
If it helps, I'm fairly sure I remember it working in `2.3.(8|9)`.

**Comment by jaagr** [comment]
think I broke it with d34263d but now it should apply to all text labels
