### ISSUE TITLE
Bars not loading fonts and color properly

### ISSUE THREAD

**Issue by Capuno** [jaagr/polybar#224]
This happened on 3 modules, this one for example is the volume module, with the unfilled space, with the same font and character that the filled, is working fine, but the filled one is not loading neither the monospaced font nor the color.

![scrot](http://pix.toile-libre.org/upload/original/1480885043.png)

the config:

![scrot2](http://pix.toile-libre.org/upload/original/1480885177.png)

*Its fine on older versions*

**Comment by jaagr** [comment]
Is it only on master or do you know what version that introduced the bug?

**Comment by jaagr** [comment]
1a48f82 should fix the bug

**Comment by Capuno** [comment]
I don't remember what version I used, I did a new clone for last one because I cant remember where I cloned last, #1a48f82 fixes it, thanks!
