### ISSUE TITLE
I do not get how to specifiy fonts for modules.

### ISSUE THREAD

**Issue by ErraticFox** [jaagr/polybar#225]
Hello, I have 
```
font-0 = Roboto:size=10:weight=regular
font-1 = fontawesome:size11:weight=regular
font-2 = tewi:pixelsize=9;0
```
and I'm trying to use `font-2` in my date module. 

I've read formatting and the example for specifiying dates on the Configuration page and the label example for fonts in formatting don't seem to connect and I'm a bit confused. I'm not even quite sure what `label-active = %token%` is suppose to be, but this is what I have so far.
```
[module/date]
type = internal/date
interval = 1.0
date = "   %I : %M   "
date-alt = %I : $M
format-background = ${c.r}

label-active = %token%
label-active-font = 3
```

What am I doing wrong?

**Comment by jaagr** [comment]
Hi

There are no `<label-active>` for the date module. And now when I looked at it I see that it doesn't use a label at all, so the only way to specify a font for it is to use the raw syntax tag (note that it requires double `%%` to not be treated as a date token):

~~~ dosini
[module/date]
...
date = %%{T3}%I : %M
...
~~~

But I will update the module and add a label.

**Comment by jaagr** [comment]
There, I've update the module. Now you can specify font:

~~~ dosini
[module/date]
type = internal/date
interval = 1

date = %Y-%m-%d
date-alt = %A %B, %Y

; optional
time = %H:%M
time-alt = %H:%M:%S

label = %date% %time%
label-font = 3
label-foreground = #9A32DB
~~~

**Comment by ErraticFox** [comment]
Sweet! Didn't expect a *fix* for this, would've been fine doing the raw syntax. Though I really appreciate the commit. Thanks! :)
