### ISSUE TITLE
Feature request: workspace scroll handling on whole bar

### ISSUE THREAD

**Issue by davewongillies** [jaagr/polybar#226]
Feel free to close this as you please but one feature I really miss from `i3status` is the ability to scroll through workspaces anywhere on the bar. With polybar its only in the small i3 widget which is a really small space to hit. Being able to do it anywhere on polybar would be amazing. Thanks

**Comment by jaagr** [comment]
Added section to the wiki, see https://github.com/jaagr/polybar/wiki/Module:-i3

**Comment by davewongillies** [comment]
I've built 2.3.11 and configured polybar as per the wiki. When I scroll over polybar nothing happens. I see this in the log output when I scroll over it:

```
warn: No matching input area found
warn: No matching input area found
warn: No matching input area found
```

**Comment by jaagr** [comment]
Could you post your config

**Comment by davewongillies** [comment]
https://gist.github.com/davewongillies/3ad75acdf117f781acac1c09ba431b2c

**Comment by jaagr** [comment]
Are you sure you are running the latest version? Check `polybar -v`

**Comment by davewongillies** [comment]
Oh nuts, I'm on 2.3.5. Fixing that now.

**Comment by davewongillies** [comment]
I've built with 2.3.11 and its all working now, thanks! :ok_hand:
