### ISSUE TITLE
Can't hide when using the fullscreen mode (bspwm)

### ISSUE THREAD

**Issue by Raptorneutron** [jaagr/polybar#232]
Hello, when I use the fullscreen mode the bar don't hide.
Here's a couple of screenshots:
![2016-12-08-194009_1600x900_scrot](https://cloud.githubusercontent.com/assets/23237379/21022797/32086a0a-bd7e-11e6-9b70-182458739ceb.png)

Without Fullscreen
![2016-12-08-194014_1600x900_scrot](https://cloud.githubusercontent.com/assets/23237379/21022798/3223d0a6-bd7e-11e6-8ac8-fdd2ee0e55e7.png)

With Fullscreen

The same at youtube videos and other stuff.

**Comment by jaagr** [comment]
Are you using `wm-restack = bspwm` ?

**Comment by Raptorneutron** [comment]
Nope, I just changed it and now the issue is solved.

Thanks
