### ISSUE TITLE
Compilation problem, directory "x"  does not contain a CMakeLists.txt file

### ISSUE THREAD

**Issue by Deomkan** [jaagr/polybar#234]
**That's the compilation problem that it appears on terminal:**
Checking for module 'fontconfig'
--   Found fontconfig, version 2.11.94
CMake Error at src/CMakeLists.txt:92 (add_subdirectory):
  The source directory
    /home/alex/Scaricati/polybar-master/lib/xpp

  does not contain a CMakeLists.txt file.

-- Found ALSA: /usr/lib/x86_64-linux-gnu/libasound.so (found version "1.1.0") 
-- Found LibMPDClient: /usr/lib/libmpdclient.so  
-- Found Libiw: /usr/lib/x86_64-linux-gnu/libiw.so  
CMake Error at src/CMakeLists.txt:128 (add_subdirectory):
  The source directory

    /home/alex/Scaricati/polybar-master/lib/i3ipcpp

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/home/alex/Scaricati/polybar-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/alex/Scaricati/polybar-master/build/CMakeFiles/CMakeError.log".
** Failed to generate build... read output to get a hint of what went wrong

**These are the logs:**
[CMakeError (copia 1).txt](https://github.com/jaagr/polybar/files/643067/CMakeError.copia.1.txt)
[CMakeOutput (copia 1).txt](https://github.com/jaagr/polybar/files/643068/CMakeOutput.copia.1.txt)

**Comment by jaagr** [comment]
You need to fetch the submodules `git submodule update --init --recursive`

**Comment by Deomkan** [comment]
Thank you it does work now!
