### ISSUE TITLE
Example config doesn't run...

### ISSUE THREAD

**Issue by SuperCuber** [jaagr/polybar#237]
I downloaded the example config from the examples folder. [Here](http://pastebin.com/k7H1Bd6K) it is for reference. Then I move it to the correct location and do "polybar example", and [here](http://pastebin.com/RTZghNyr) is the output...

**Comment by Ema0** [comment]
you need to replace `@MODULES_LEFT@` `@MODULES_CENTER@` and `@MODULES_RIGHT@` with the names of the modules you want to show (what you have between square brackets in the config file) in each section.
Example from the [wiki](https://github.com/jaagr/polybar/wiki/Configuration#bar-settings):
```
modules-left = cpu ram
modules-center = xwindow xbacklight
modules-right = ipc clock
```
If some of the module in the config file are:
```
[module/cpu]
...

[module/ram]

etc...
```

**Comment by jaagr** [comment]
@Ema0 is right, you need to replace the placeholders with values. This is normally done by the build process when generating the example configuration that should be installed at `/usr/share/examples/polybar/config` or `/usr/local/share/examples/polybar/config`
