### ISSUE TITLE
Compton gives shadow to tray

### ISSUE THREAD

**Issue by MrWhiteGoat** [jaagr/polybar#238]
https://gyazo.com/2d3f11ef2d0c65acacee58bc44ae425a

In compton.conf
`shadow-exclude = [
    "name = 'noshadow'",
    "name = 'polybar'",
    "class_g ?= 'Notify-osd'"
];`

**Comment by jonathashenriques** [comment]
Set:  shadow-exclude = [ "name = 'Polybar tray window'"];

**Comment by jaagr** [comment]
You could also launch compton with `--respect-prop-shadow` since polybar sets the atom that tells compton to ignore it.

**Comment by hschreck** [comment]
You can also use the "no-dock-shadow = true;" line in compton.conf, but I think @jaagr has the "more correct" solution.

**Comment by MrWhiteGoat** [comment]
@jonathashenriques's solution worked perfectly for me. I tried using @jaagr's one but it didn't work for me ;-;
