### ISSUE TITLE
sudo make install fails on FreeBSD

### ISSUE THREAD

**Issue by timlag1305** [jaagr/polybar#239]
Hi, there are several issues that I have run into which prevent me from building from source. I am using FreeBSD 11 with clang 3.8. I also tried using gcc6 but ran into similar issues.

```CMake
[  1%] Built target xpp
Scanning dependencies of target polybar
[  2%] Building CXX object bin/CMakeFiles/polybar.dir/adapters/alsa.cpp.o
In file included from <built-in>:350:
<command line>:1:9: error: macro name must be an identifier
#define -I/usr/local/include 1
        ^
In file included from /usr/home/tim/polybar/src/adapters/alsa.cpp:1:
/usr/home/tim/polybar/include/adapters/alsa.hpp:4:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^
2 errors generated.
*** Error code 1

Stop.
make[2]: stopped in /usr/home/tim/polybar/build
*** Error code 1

Stop.
make[1]: stopped in /usr/home/tim/polybar/build
*** Error code 1

Stop.
make: stopped in /usr/home/tim/polybar/build
```

I don't know how to fix the first error, but to fix the second, I change `#include <endian.h>`  to `#include <sys/endian.h>` in `include/adapters/alsa.hpp`

After making that change, the build output becomes:

```CMake
[  1%] Built target xpp
Scanning dependencies of target polybar
[  2%] Building CXX object bin/CMakeFiles/polybar.dir/adapters/alsa.cpp.o
In file included from <built-in>:350:
<command line>:1:9: error: macro name must be an identifier
#define -I/usr/local/include 1
        ^
In file included from /usr/home/tim/polybar/src/adapters/alsa.cpp:1:
In file included from /usr/home/tim/polybar/include/adapters/alsa.hpp:26:
/usr/local/include/alsa/pcm.h:597:19: error: zero size arrays are an extension
      [-Werror,-Wzero-length-array]
        unsigned int pos[0];    /**< channel position array */
                         ^
/usr/home/tim/polybar/src/adapters/alsa.cpp:247:16: error: use of undeclared identifier 'pow10'
  normalized = pow10((vol_total / chan_n - vol_max) / 6000.0);
               ^
/usr/home/tim/polybar/src/adapters/alsa.cpp:249:16: error: use of undeclared identifier 'pow10'
    min_norm = pow10((vol_min - vol_max) / 6000.0);
               ^
/usr/home/tim/polybar/src/adapters/alsa.cpp:296:16: error: use of undeclared identifier 'pow10'
    min_norm = pow10((vol_min - vol_max) / 6000.0);
               ^
5 errors generated.
*** Error code 1

Stop.
make[2]: stopped in /usr/home/tim/polybar/build
*** Error code 1

Stop.
make[1]: stopped in /usr/home/tim/polybar/build
*** Error code 1

Stop.
make: stopped in /usr/home/tim/polybar/build
```

**Comment by jaagr** [comment]
When I have the time I'll boot a live cd and try the build.

**Comment by Talanor** [comment]
I can confirm this happens to me too. Any update on that?

**Comment by benjiii** [comment]
I've got to linking stage by doing the following:
Run `build.sh` and disable unsupported stuff (e.g. git as bsd has no `inotify_<method>` syscalls) and stuff you don't want:

```
** Setting build options
** Include support for "internal/i3" (requires i3) ------------------- [Y/n]: n
** Include support for "internal/volume" (requires alsalib) ---------- [Y/n]: y
** Include support for "internal/network" (requires wireless_tools) -- [Y/n]: n
** Include support for "internal/mpd" (requires libmpdclient) -------- [Y/n]: n
** Include support for "internal/github" (requires libcurl) ---------- [Y/n]: n
** Build "polybar-msg" used to send ipc messages --------------------- [Y/n]: y
```

Adding an `#ifdef _FreeBSD_` for `sys/endian.h` statement.

Disabling `-Werror` and pedantic errors, I guess the author uses gcc and clang has different/additional warnings and errors.

Add the `_WITH_DPRINTF` define for dprintf, see https://reviews.freebsd.org/D6302 (I imagine this won't be an issue with FreeBSD 12.0-CURRENT.

----
Despite these changes though, and despite explicitly disabling `git` in the build.sh prompt, my build fails at linking:
CMakeFiles/polybar.dir/utils/inotify.cpp.o: In function `polybar::v3_0_4_git::inotify_watch::~inotify_watch()':
/home/ben/polybar/src/utils/inotify.cpp:19: undefined reference to `inotify_rm_watch'
CMakeFiles/polybar.dir/utils/inotify.cpp.o: In function `polybar::v3_0_4_git::inotify_watch::attach(int)':
/home/ben/polybar/src/utils/inotify.cpp:30: undefined reference to `inotify_init'
/home/ben/polybar/src/utils/inotify.cpp:33: undefined reference to `inotify_add_watch'
CMakeFiles/polybar.dir/utils/inotify.cpp.o: In function `polybar::v3_0_4_git::inotify_watch::remove(bool)':
/home/ben/polybar/src/utils/inotify.cpp:43: undefined reference to `inotify_rm_watch'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

I'm not really interested in forking this and maintaining a build for FreeBSD, hopefully this helps somebody who is.

**Comment by jaagr** [comment]
One possible solution would be to disable inotify modules and config reloading all together using a build flag.

**Comment by lebarondemerde** [comment]
Eventually [libinotify-kqueue](https://github.com/libinotify-kqueue/libinotify-kqueue) could work for that.

**Comment by lebarondemerde** [comment]
As reference, conky and owncloudclient rely on libinotify to work in FreeBSD.

**Those are the libinotify limitations:**

Libinotify functionality on FreeBSD is missing support for

  - detecting a file being moved into or out of a directory within the
    same filesystem
  - certain modifications to a symbolic link (rather than the
    file it points to.)

in addition to the known limitations on all platforms using kqueue(2)
where various open and close notifications are unimplemented.

This means the following regression tests will fail:

Directory notifications:
   IN_MOVED_FROM
   IN_MOVED_TO

Open/close notifications:
   IN_OPEN
   IN_CLOSE_NOWRITE
   IN_CLOSE_WRITE

Symbolic Link notifications:
   IN_DONT_FOLLOW
   IN_ATTRIB
   IN_MOVE_SELF
   IN_DELETE_SELF

Kernel patches to address the missing directory and symbolic link
notifications are available from:

https://github.com/libinotify-kqueue/libinotify-kqueue/tree/master/patches

**Comment by lebarondemerde** [comment]
For the eventually interested ones: [HERE](https://github.com/kylecook80/polybar-port) and [HERE](https://forums.freebsd.org/threads/62494/).

I am already using it!

**Comment by gregf** [comment]
@lebarondemerde Thank you so much for sharing, everything seems to be working except for the netspeed up/down due to the fact that they depend on wireless_tools which I believe is linux only.

**Comment by kylecook80** [comment]
Please let me know if there are any improvements I can make, or if we could potentially upstream the changes I made!

**Comment by patrick96** [comment]
It would be nice to integrate this into master. @kylecook80 can you draft a PR with the necessary changes? I barely know anything about BSD, but I'll try my hands on setting up a VM to compile polybar myself. Do you know if your patches will also work NetBSD or OpenBSD?

**Comment by lebarondemerde** [comment]
I do not know about NetBSD or OpenBSD, but almost certainly to work on DragonFlyBSD since it uses FreeBSD ports.

I say almost because sometimes the port need some minor adjusts to work in there.

**Comment by kylecook80** [comment]
I have opened a PR. I doubt my patches would be sufficient for NetBSD or OpenBSD, although some tweaking might get them working.
