### ISSUE TITLE
i3: Process not killed with WM_DELETE_WINDOW

### ISSUE THREAD

**Issue by jhnguye0** [jaagr/polybar#247]
I am using i3wm, and wanted to reload polybar on every configuration reload.
My i3 config file has the following setting to kill any cases of polybar before loading up a new one.

`exec_always --no-startup-id i3-msg '[class="Polybar"] kill'; polybar status`

This does the trick for removing the original bar display and adding a new one. The problem is I'll have runaway processes, with each polybar instance printing out:
`error: Error in X event loop: XCB_DRAWABLE (9)`
So they aren't being displayed, but my systemctl status will show all of the polybar processes still running.

I think this is because polybar doesn't support WM_DELETE_WINDOW protocol?

This is my xprop:
> WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_PID(CARDINAL) = 7906
_NET_WM_DESKTOP(CARDINAL) = 4294967295
_NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY, _NET_WM_STATE_ABOVE
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK
WM_CLASS(STRING) = "polybar", "Polybar"
WM_NAME(STRING) = "polybar-status_eDP1"
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 26, 0, 0, 0, 0, 0, 0, 1919, 0, 0
_NET_WM_STRUT(CARDINAL) = 0, 0, 26, 0

**Comment by jhnguye0** [comment]
Whoops, this could be fixed using the startup script given in the wiki.

**Comment by jaagr** [comment]
Yeah, it probably only kills the window but not the process. I'll fix so that it shuts down when the window gets destroyed, not much else the process can do without it anyway.
