### ISSUE TITLE
feature(bspwm) label-last-underline

### ISSUE THREAD

**Issue by quite** [jaagr/polybar#253]
I often switch between two desktops, and have a binding for switching to the last focused desktop. It would thus be neat if I could mark that desktop. (Perhaps also label-dimmed-last-underline, top be complete)

**Comment by d125q** [comment]
This, in my opinion, is a very specific use case.  For example, I have a binding that switched to the last non-empty focused desktop.  Would it make sense to include an underline for that as well?  Certainly not.

However, it would make sense to include something that underlines the desktops/monitors of a specific command...

**Comment by quite** [comment]
Ah. Well I didn't mean to specifically mark "last focused desktop" just because I have a binding for that. bspwm does maintain last focused desktop (per monitor), which can be found with `bspc query -D -d last.local` (or, omit `.local` for last focused desktop on all monitors). No matter how you navigate between desktops, there will be a last focused desktop. Do you mean that you would want to exclude empty desktops when finding the last focused desktop?

But, certainly one could consider tying a mark to the desktop returned by a custom bspc command, which I think is what you mean. Then I guess you'd use something like `bspc query -D -d last.occupied.local`.

**Comment by d125q** [comment]
> But, certainly one could consider tying a mark to the desktop returned by a custom bspc command, which I think is what you mean. Then I guess you'd use something like `bspc query -D -d last.occupied.local`.

Yes, that is precisely what I meant.

**Comment by jaagr** [comment]
Closing. I'll add a reference to this in #84
