### ISSUE TITLE
%percentage% per core

### ISSUE THREAD

**Issue by alexdreptu** [jaagr/polybar#256]
Is there any way to get cpu usage %percentage% and cpu temp per core?

**Comment by jaagr** [comment]
You could use `<ramp-coreload>`, for example:

~~~dosini
[module/cpu]
type = internal/cpu
format = <ramp-coreload>
ramp-coreload-0 = ▁
ramp-coreload-1 = ▂
ramp-coreload-2 = ▃
ramp-coreload-3 = ▄
ramp-coreload-4 = ▅
ramp-coreload-5 = ▆
ramp-coreload-6 = ▇
ramp-coreload-7 = █
~~~

**Comment by alexdreptu** [comment]
I'm sorry I meant %percentage% in numbers, I should have specified.

**Comment by jaagr** [comment]
Yes, now you can :-)

~~~ dosini
; Show load for all cores, e.g: 3% 5% 2% 0% 4% 0% 3% 0%
label = %percentage-cores%
 %percentage-cores% %percentage-core2% 
~~~

**Comment by alexdreptu** [comment]
Awesome thanks. Is there a token for core temperatures as well?

**Comment by jaagr** [comment]
No, there's no temp info in the cpu module at the moment

**Comment by alexdreptu** [comment]
Ups, I initially didn't see you just implemented this right now. Thank you for implementing it.

**Comment by jaagr** [comment]
np!
