### ISSUE TITLE
Keyboard flag

### ISSUE THREAD

**Issue by bpinto** [jaagr/polybar#257]
Hi, is is possible to customize what we display on the keyboard module? I was looking for something like this:

```
label-number-0 = "a unicode flag here"
label-number-1 = "another unicode flag here"
```

**Comment by jaagr** [comment]
Hi, that's not currently supported but it would be a nice feature.

**Comment by bpinto** [comment]
Thanks @jaagr 

You are really awesome, I'll close this as it's not an issue.
