### ISSUE TITLE
What is the "tray window" / "system tray" ? There's a config for it's positition, but what is it?

### ISSUE THREAD

**Issue by bryanbecker** [jaagr/polybar#258]
I'm guessing the "tray" is relying on integrating with some other software? Setting the position alone doesn't seem to do anything.

What is it?

**Comment by jaagr** [comment]
![tray](https://cloud.githubusercontent.com/assets/3697186/21375780/554a7696-c730-11e6-8a46-93cca06533f1.png)

**Comment by jaagr** [comment]
It enables support for tray icons. 
![tray](https://cloud.githubusercontent.com/assets/3697186/21375821/98fa0a3c-c730-11e6-84e9-937f4aa0bd84.png)

**Comment by bryanbecker** [comment]
How do I make them, then?  Is it done within polybar?

**Comment by jaagr** [comment]
No tray clients are embedded by applications that implement the feature.

**Comment by bryanbecker** [comment]
Got it, thank you.

So tray icons have a standard implementation that other software implements

**Comment by jaagr** [comment]
Yeah exactly, https://specifications.freedesktop.org/systemtray-spec/systemtray-spec-0.3.html
