### ISSUE TITLE
[SOLVED] Cannot open shared object file libjsoncpp.so 

### ISSUE THREAD

**Issue by PaNaVTEC** [jaagr/polybar#264]
Hi, I updated polybar from aur to the new version that you just pushed and I found this error while trying to load my usual bar: 

```$ polybar top
polybar: error while loading shared libraries: libjsoncpp.so.11: cannot open shared object file: No such file or directory
```
It seems that it does not found a library, I just installed from aur the package `extra/jsoncpp` and it works, maybe you want to add this package as a dependency? 

Thanks!

**Comment by jaagr** [comment]
Hi, it's listed as an optional dependency in the aur package as jsoncpp is only required when building with support for the i3 module

**Comment by Jezorko** [comment]
@jaagr um, how does it make it resolved? [i3 module](https://github.com/jaagr/polybar/wiki/Module:-i3) is one of the basic modules and there is no mention of jsoncpp dependency in the wiki.

**Comment by patrick96** [comment]
@Jezorko it's listed as a dependency for i3 in the Readme

**Comment by Soundtoxin** [comment]
I'm running into this issue recently while already having jsoncpp installed.

**Comment by PaNaVTEC** [comment]
I had the same problem with the last update and just reinstalling the
package solved it.

**Comment by Soundtoxin** [comment]
Yeah, works after doing so. Thanks.

**Comment by py-radicz** [comment]
creating a symlink with proper version in name works too

**Comment by patrick96** [comment]
> creating a symlink with proper version in name works too

Never do that! The two versions may be incompatible, that's why they have different names.
