### ISSUE TITLE
best way to create a simple click action button (lock button)

### ISSUE THREAD

**Issue by eoli3n** [jaagr/polybar#276]
Is there a way to create a clickable button to directly action something ?
My idea is to display a module which print a lock icon, which clicked directly launch the lock cmd.

I tried with script, but i dont think it works as i want, it launch periodic cmds (dont understand click part on the wiki)
I tried with menu module, but it seems impossible to have a direct action without browsing a submenu.

**Comment by zestyr** [comment]
You could use the [text module](https://github.com/jaagr/polybar/wiki/Module:-text), make the content your lock icon, and use the `click-left = ...` formatting to issue the lock command

**Comment by eoli3n** [comment]
thx
