### ISSUE TITLE
Github module: Empty notifications

### ISSUE THREAD

**Issue by bpinto** [jaagr/polybar#278]
I can't seem to customize the empty notifications on the new github module.

```
[module/github]
type = internal/github
token = "something"

label = "%notifications%"
format-prefix = ""
```

This setting above alone will not print anything to the bar which is nice as I would prefer to not display anything if I don't have any notification. But unless I misread the code, I should be reading '0'.

Changing the value of `empty-notifications` to anything doesn't make the value show on the bar either.

**Comment by bpinto** [comment]
Also related to the github module, is there a way I can use an environment variable value there? Ideally I would like to keep my polybar configuration public and using the token value from an environment variable would allow me to do that.

**Comment by jaagr** [comment]
@bpinto The config parameter `empty-notifications = true` would display the 0 count. This defaults to false.

**Comment by bpinto** [comment]
Thanks!

**Comment by eoli3n** [comment]
not running displaying entire the module if there isn't any notification seems better, no ?

**Comment by eoli3n** [comment]
it is not

![alt](http://ptpb.pw/FpoY.png)

**Comment by jaagr** [comment]
@eoli3n yes, or at least clear the label (which will hide it) to allow more stuff to be added other than `%notifications%`.. untli more tokens are implemented

**Comment by eoli3n** [comment]
I think i did'nt understand well your answer so,  
is there a way to hide the entire module when there isn't any notification ?

with 
```
empty-notifications = "true"
```
it displays `` 0``

with
```
;empty-notifications = "true"
```

it displays ![alt](http://ptpb.pw/FpoY.png)

**Comment by eoli3n** [comment]
actually, by setting ``format-underline``, ``format-prefix`` and ``format-prefix-foreground``, it's working without your commit :)

```
[module/github]
type = internal/github
token = ${env:GITHUB_API_TOKEN}

;label = "%{u#2aa198}%{F#5b} %{F-}%notifications%%{u-}"
label = "%notifications%"
label-prefix =
format-underline = #2aa198
format-prefix = " "
format-prefix-foreground = #5b
;empty-notifications = true
```

**Comment by jaagr** [comment]
@eoli3n yeah that's what i meant, but it felt like an unnecessary workaround
