### ISSUE TITLE
Bar doesn't display properly when used on 5K systems that use multiple video outputs to power the display

### ISSUE THREAD

**Issue by chrissnell** [jaagr/polybar#280]
I'm running a Dell 5K monitor which requires two DisplayPort connections to the GPU.  In my case, I'm actually using two GPUs with one connection to each.   GPU-0 powers the left half of the screen and GPU-1 powers the right.  i3 has an undocumented mode called `fake-outputs` that causes i3 to treat the two halves as one single 5120x2880 display.   When configured this way, a new window will automatically span both halves of the screen to give an effective full-screen window.  

I've tried several approaches to get polybar to span both halves of the screen:

1.  Run a single polybar with configuration as follows:
```
[bar/fullwidth]
width = 100%
height = 47
```
This results in a bar that only spans the left half of the screen.  Presumably, this is because polybar lacks the `fake-outputs` hack that i3 uses and cannot span two screens with one instance.

2.  Run two polybars, one for each half of the screen:
```
[bar/left]
monitor = GPU-0.DP-2
width = 100%
height = 47

[bar/left]
monitor = GPU-1.DP-2
width = 100%
height = 47
```
This works fine for `bar/left` but `bar/right` just results in a second polybar underneath `bar/left`.  In other words, it never displays any bar on the right half of the screen.

I've tried enabling debug output and I do see that polybar is *trying* to do the right thing with geometry:
```
* Bar geometry: 2560x49+2560+0
```
...but still, nothing will show on the right half of the screen (GPU-1).

**Comment by chrissnell** [comment]
Update:  I'm no longer using i3's `fake-outputs` and I'm now using the "Monitor" concept from RandR 1.5, which i3 supports in its [`next`](https://github.com/i3/i3/tree/next) branch.  This creates a single monitor pane out of two RandR outputs:

```
xrandr --screen 0 --output DP-0 --mode 2560x2880 --pos 0x0
xrandr --screen 0 --output DP-2 --mode 2560x2880 --pos 2560x0

xrandr --screen 0 --setmonitor DellUP2715K 5120/600x2880/340+0+0 DP-0,DP-2
```

However, polybar is still not able to display its content on the right side of the screen.  Oddly, it does show the panel apps on the right side, just not the polybar-specific stuff.

Here's a screenshot of what I'm seeing with this config:

```
[bar/full]
width = 100%
height = 27
offset-y = 0
```

![screenshot](http://i.imgur.com/0rvNbW8.jpg)

**Comment by jaagr** [comment]
You wrote that the second polybar is getting placed below the first one... this is done by i3 and you would need to use `override-redirect = true` if you want to set the size/position manually. Try it out and see if it might fix your problem.

**Comment by chrissnell** [comment]
OK, that got me a little closer.  I can get it to display properly now on the right side, which is great.   But, it's covering up the top of the windows now.  I did some digging and tried using `override-redirect = true` in combination with `wm-restack = i3` but that results in polybar being completely hidden behind the i3 windows.  I can only see polybar when I go to a screen with no windows.

**Comment by jaagr** [comment]
Yeah, but due to the way i3 handles status bars `override-redirect` is required to tell it not to resize/reposition it. You could try a work-around by running a second empty bar, for example:

~~~
[bar/top-dummy]
width = 1
height = ${bar/left.height}
modules-left = empty-space
background = 0

[module/empty-space]
type = custom/text
content = " " 
~~~

You might need to remove the `wm-restack` parameter so that the actual bar window gets on top of the dummy.. otherwise the dummy will receive the mouse clicks.

**Comment by chrissnell** [comment]
Yes!!!! That works!

In case somebody wants to get this working, here's what I used:

```
[bar/dummy]
width = 1
height = ${bar/right.height}
modules-left = empty-space
background = 0

[bar/right]
;; right half of screen
monitor = DP-2
width = 100%
height = 27
offset-x = 0
offset-y = 0
override-redirect = true

[bar/left]      
;  left half of monitor 
monitor = DP-0
width = 100%
height = 27
offset-x = 0
offset-y = 0
override-redirect = true
```

**Comment by chrissnell** [comment]
Do you want me to leave this issue open?   It would be awesome if polybar eventually supported the new RandR `Monitor` concept and could draw a bar across the entire workspace instead of the individual video outputs.   Happy to help test.

**Comment by jaagr** [comment]
You can leave it open and I will checkout the `Monitor` concept, haven't heard of it before.

**Comment by jaagr** [comment]
@chrissnell I've added support for XRandR monitors. Please try it out and check if it works for your setup...

**Comment by chrissnell** [comment]
Wow, awesome!    OK, it's not 100% there but really close.

First off, here's what happens when I run `polybar --list-monitors`:

```
$ polybar --list-monitors
Usage: polybar bar_name [OPTION...]

  -h, --help               Display this help and exit
  -v, --version            Display build details and exit
  -l, --log=LEVEL          Set the logging verbosity (default: WARNING)
                           LEVEL is one of: error, warning, info, trace
  -q, --quiet              Be quiet (will override -l)
  -c, --config=FILE        Path to the configuration file
  -r, --reload             Reload when the configuration has been modified
  -d, --dump=PARAM         Print value of PARAM in section [bar_name] and exit
  -m, --list-monitors      Print list of available monitors and exit
  -w, --print-wmname       Print the generated WM_NAME and exit
  -s, --stdout             Output data to stdout instead of drawing the X window
```

So I just took a guess based on the code and fetched my monitor name from `xrandr --listactivemonitors` and added that to my polybar config:

```
[bar/example]
monitor = DellUP2715K
width = 100%
height = 27
offset-x = 0
offset-y = 0
override-redirect = true
```

This produced a beautiful full-monitor bar but it was sitting on top of the i3 window decorations:

![screenshot](http://i.imgur.com/7kaHEYR.png)

So I added a dummy bar like we discussed above and that works:

![screenshot](http://i.imgur.com/wqaPjHI.png)

It would be totally awesome if there was a way to make i3 honor the spacing for polybar  (_NET_WM_STRUT_PARTIAL???) but I can easily work around it.  Just not out-of-the-box easy yet.

I sure appreciate you writing this so fast.  

Chris

**Comment by jaagr** [comment]
You have to pass the `<bar-name>` before `-m|--list-monitors` but I'm working on making the command flags position independant right now.

Polybar sets that atom but i3 doesn't seem to honor it straight off. I'm no i3 user myself so things might have changed since I last checked though.

**Comment by chrissnell** [comment]
OK, here's what --list-monitors shows me now:

```
$ polybar example --list-monitors
DP-2: 2560x2880+2560+0 (XRandR monitor)
DP-0: 2560x2880+0+0 (XRandR monitor)
DellUP2715K: 5120x2880+0+0
```

Could the DellUP2715K be labeled something like "Composite RandR monitor"?   

Out of curiosity, what window manager do you run?

**Comment by jaagr** [comment]
@chrissnell Actually, if you pull the latest source you will get the fix that swaps that.. The `XRandR monitor` should be on your last line.

I am using bspwm.

**Comment by chrissnell** [comment]
Excellent!  Just verified that `--list-monitors` works as expected.

Closing this bug.  If you ever need help testing something, I'm happy to help, just GH @mention me.

**Comment by jaagr** [comment]
Thanks.
