### ISSUE TITLE
Custom scripts prevents polybar from stopping gracefully

### ISSUE THREAD

**Issue by xintron** [jaagr/polybar#281]
I run two custom scripts in tail-mode which works as expected. The issues I'm having is when I terminate the bar with SIGTERM. Most of the times it tries to stop the shell commands and freezes. I've verified the commands and they both successfully handles SIGTERM.

To reproduce the problem:
 1. Use the example config as is.
 2. Add the following custom script (will probably work with a normal `tail -f` as well)
````
[module/log-tail]
type = custom/script
exec = journalctl -f -n0
label = %output:0:20:...%
tail = true
````

 3. Run polybar and stop it with `ctrl+c` after a second or two.

It should now be stuck with the following output (my module/battery is still updating though, guessing it's stopped later in the chain):

````
warn: Termination signal received, shutting down...
warn: module/log-tail: Stopping shell command
* module/log-tail: Stopping
* module/battery: Polling values (inotify fallback)
````

Most of the time a second SIGTERM will make polybar exit but on occasion I've had to stop it using a SIGKILL.

**Comment by jaagr** [comment]
acb9ed9 should fix the hangup... please verify

**Comment by xintron** [comment]
It's a lot better with that commit. Only happened once on ten tries. Will do a debug build tomorrow and check if I can reproduce the freeze.

**Comment by jaagr** [comment]
Found a few more issues with the module. I will reimplement the module because it's a mess at the moment. Would be best to split it into separate modules for timed/tailing commands.

**Comment by xintron** [comment]
With the ccddf05 commit I can't reproduce the problems anymore.
