### ISSUE TITLE
terminate called after throwing an instance of 'std::length_error'

### ISSUE THREAD

**Issue by rubik** [jaagr/polybar#282]
I just built polybar from master (18cf9df86cb2482f9b0a5e0ccf32fe989428a1ba), and I get this error message when starting the bar:

```
Launched the main bar ...
error: Disabling module wired (reason: Invalid network interface enp2s0)
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create
```

Last commit that I tested and was working was 24aba14541ea53425713ea08855244ab8ecf177e. I didn't check the later ones.

**Comment by mmedum** [comment]
I am hitting the same problem when running polybar example. After that "core dumped" kills the bar.

**Comment by eoli3n** [comment]
same here

**Comment by andy2mrqz** [comment]
I'm also having the same problem using the example polybar

**Comment by p4block** [comment]
Same thing here
