### ISSUE TITLE
Closed unused sockets

### ISSUE THREAD

**Issue by minijackson** [jaagr/polybar#283]
I'm under the impression that the i3 module does not close some opened files where it should.

Symptoms:

After running the bar for a while, the i3 workspaces module become unresponsive and when trying to change workspace with the mouse I get:
```
error: module/i3: Failed to get socket path: errno 24 (Too many open files)
```

and when I do `lsof -p <pid of polybar>` I get an uncanny number of opened UDP sockets.

By watching `lsof -p <pid of polybar> | tail`, it seems that a new file is opened every ~3sec

Any ideas ?

**Comment by jaagr** [comment]
Hi and thanks for reporting the issue. I would guess that it's related to the ipc library we use. There might have been a change to it that polybar haven't adopted. Will check it out once I've fixed a few other bugs.

**Comment by minijackson** [comment]
Great, thanks !

**Comment by jaagr** [comment]
I can't reproduce the issue. What version are you running? `polybar -vv`

**Comment by minijackson** [comment]
After a fresh pull, here's the version I'm using:

```
polybar 2.4.5-4-gccddf05 

Features: +alsa +curl +i3 +mpd +network 

Build type: Release
Compiler: /usr/bin/c++
Compiler flags:  -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors
Linker flags: 

ALSA_SOUNDCARD              default
BSPWM_SOCKET_PATH           /tmp/bspwm_0_0-socket
BSPWM_STATUS_PREFIX         W
BUILDER_SPACE_TOKEN         %__
CONNECTION_TEST_IP          8.8.8.8
PATH_ADAPTER                /sys/class/power_supply/%adapter%
PATH_BACKLIGHT_MAX          /sys/class/backlight/%card%/max_brightness
PATH_BACKLIGHT_VAL          /sys/class/backlight/%card%/brightness
PATH_BATTERY                /sys/class/power_supply/%battery%
PATH_CPU_INFO               /proc/stat
PATH_MEMORY_INFO            /proc/meminfo
PATH_TEMPERATURE_INFO       /sys/class/thermal/thermal_zone%zone%/temp
```

After some quick research, it seems that a file is opened permanently each time I see this line in the console:

```
module/wlan: Failed to query interface 'wlp2s0'
```

(which is also weird, because it is the right interface name, and I have wireless-tools installed)

Happy new year by the way.

**Comment by jaagr** [comment]
Looking at `src/adapters/net.cpp` I can see why... The socket doesn't get closed if the query fails. I'll patch it

**Comment by minijackson** [comment]
Seems fixed, many thanks !
