### ISSUE TITLE
Make it possible to specify monitor as comand-line-arg

### ISSUE THREAD

**Issue by phuhl** [jaagr/polybar#286]
Trying to build a setup with flexible monitors it turnes out that it whould be really nice to be able to specify the monitor as a command-line-argument.

Right now i have a lot of code like this:
     
     [bar/main_LVDS1]
     inherit = bar/main
     monitor = LVDS1
     
     [bar/main_LVDS-1]
     inherit = bar/main
     monitor = LVDS-1
     
     [bar/secondary_VGA1]
     inherit = bar/secondary
     monitor = VGA1
     
     [bar/secondary_VGA-1]
     inherit = bar/secondary
     monitor = VGA-1
     
     [bar/secondary_HDMI-1]
     inherit = bar/secondary
     monitor = HDMI-1
     
     [bar/secondary_HDMI1]
     inherit = bar/secondary
     monitor = HDMI1

My setup is like this:
- one bar for main (named main)
- one bar for each secondary monitor (named secondary)

It would be much nicer if i could say:

     polybar main -m VGA1
     polybar secondary -m HDMI1

**Comment by bpinto** [comment]
Could you use environment variables?

```
MONITOR=VGA1 polybar main
MONITOR=HDM1 polybar secondary
```

and then use it like so:

```
monitor = ${env:MONITOR}
```

**Comment by phuhl** [comment]
Good suggestion, works great, thanks.
