### ISSUE TITLE
Feature Request:  Allow config file to be split up (importing)

### ISSUE THREAD

**Issue by bryanbecker** [jaagr/polybar#287]
I ran into this issue playing with the github module as well as writing custom modules.

It would be nice to be able import other config files.  While letting the config be more modular, more importantly it lets us keep sensitive stuff out of source control (like API keys)

**Comment by bryanbecker** [comment]
```
[module/battery]
{import battery.conf}
```

or

```
[module/github]
token = {import secrets.githubtoken}
```

**Comment by jaagr** [comment]
~~~ dosini
[module/github]
token = ${file:/absolute/path/to/token}
~~~

**Comment by bryanbecker** [comment]
Welp, I meant to pots this a few days ago, and when I finally do, it turns out that not only you already had the feature, but it was just documented this morning in the wiki as well
