### ISSUE TITLE
Created a fork with new Reddit module and updated HTTP lib.  Have some questions about http lib and response parsing

### ISSUE THREAD

**Issue by bryanbecker** [jaagr/polybar#292]
I forked polybar to add a simple reddit module, meant to be a clone of the github one, but it quickly became more complicated than I planned, since reddit enforces oauth (you have to request a bearer token, then use that to make the actual request you want).

First things first, I think I'm in over my head in your code base, ha, so please excuse any major errors.

I think I added support to your http module for POST requests, along with authentication headers.

In order to test, I need to parse the output that your function is returning.  For github, you used:

```
while ((pos = content.find("\"unread\":true", pos + 1)) != string::npos) {
      notifications++;
    }
```

I'm not really sure what's going on her.  I guess you're essentially greping the occurrences of `"unread":`

I need to parse a response like:

```

{"access_token": "AOUFR5AiJjbLmtFGhgaz9fzLmrE", "token_type": "bearer", "expires_in": 3600, "scope": "*"}
```

Alternatively, could consider adding a lightweight json parser

EDIT:  actually it looks like you already have JSONCPP library... any reason you aren't using that in the github module?

**Comment by jaagr** [comment]
The main reason I didn't bother setting up a jsonlib was because I was just grabbing that count so it seemed a bit overkill. But like you said, `jsoncpp` is already required (if built with i3 support) so we could use that.
