### ISSUE TITLE
Bar doesn't redraw automatically when system tray updates

### ISSUE THREAD

**Issue by fj2** [jaagr/polybar#295]
The bar does not redraw after the system tray updates. So when the tray changes, it can overlap an adjacent module etc, or leave a gap if an item leaves the tray.

When a module triggers a redraw (eg, changing window in i3 module, or time changing in date module), modules next to the tray will be move to their proper location.

EDIT: An easy way to see this behaviour is to disable all modules other than date. Then open some application that adds an icon to the tray - the icon will overlap the modules. Click on the date module to make it display its alternative format, and it will jump to the correct location.

**Comment by fj2** [comment]
I tracked the issue down to bar.cpp line 326. The parse function is exiting here when the tray is updated, because the argument to the parse function has not changed since the last time it was called.

**Comment by jaagr** [comment]
@fj2 thanks for tracking down the causing line. I will patch it

**Comment by jaagr** [comment]
@fj2 The issue should be fixed as of the referenced commit. Please verify and close the issue.

**Comment by fj2** [comment]
Working now, thanks!
