### ISSUE TITLE
Odd Error

### ISSUE THREAD

**Issue by onurhaan** [jaagr/polybar#297]
Hello, I get this error when I try to run polybar. Any idea what causes it?

`error: basic_string::erase: __pos (which is 8) > this->size() (which is 7)`

**Comment by siftra** [comment]
Can confirm. If it matters, it occurs when I try to use the darkpixel theme. I do not run into this issue with the default config.

**Comment by jmml97** [comment]
This is happening to me now, was working fine...

**Comment by jaagr** [comment]
@jmml97 what version? `polybar -vv`

**Comment by siftra** [comment]
@jaagr I can't speak for jmml97 but the issue has been resolved on my side with the newest release. Thank you!

**Comment by jmml97** [comment]
@jaagr polybar 2.4.6. Read the commit you referenced at the top, it was something  to do with the battery indicator. To fix it, I unplugged the battery cord, reloaded polybar and plugged it again...

**Comment by jaagr** [comment]
@jmml97 the fix is in `2.4.7` so try updating your version

**Comment by jaagr** [comment]
Closing as this should be fixed by ef44202
