### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by roberoonska** [jaagr/polybar#301]
After typing `polybar example` I get the following error:
```
terminate called after throwing an instance of 'xpp::x::error::name'
  what():  XCB_NAME (15)
Aborted (core dumped)
```
Here is the output for my version:
```
polybar 2.4.6 

Features: +alsa +curl +i3 +mpd +network 

Build type: Release
Compiler: /usr/bin/c++
Compiler flags:  -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors
Linker flags: 

ALSA_SOUNDCARD              default
BSPWM_SOCKET_PATH           /tmp/bspwm_0_0-socket
BSPWM_STATUS_PREFIX         W
BUILDER_SPACE_TOKEN         %__
CONNECTION_TEST_IP          8.8.8.8
PATH_ADAPTER                /sys/class/power_supply/%adapter%
PATH_BACKLIGHT_MAX          /sys/class/backlight/%card%/max_brightness
PATH_BACKLIGHT_VAL          /sys/class/backlight/%card%/brightness
PATH_BATTERY                /sys/class/power_supply/%battery%
PATH_CPU_INFO               /proc/stat
PATH_MEMORY_INFO            /proc/meminfo
PATH_TEMPERATURE_INFO       /sys/class/thermal/thermal_zone%zone%/temp
```

**Comment by jaagr** [comment]
Could you try disabling modules and try to find the one causing the error?

**Comment by roberoonska** [comment]
I commented out all of the modules and the error still persists.

**Comment by roberoonska** [comment]
I commented out all modules and the error still persists. I get the error no matter which config I use.

**Comment by jaagr** [comment]
Could you try disabling the tray functionality (comment out the parameter `tray-position = right`) and see if it's caused by that

**Comment by roberoonska** [comment]
Doesn't seem to help.

**Comment by jaagr** [comment]
Can you launch with `polybar example -l info` and copy the output

**Comment by roberoonska** [comment]
Here is the output:
```
warn: No monitor specified, using "eDP1"
* Loaded monitor eDP1 (3200x1800+0+0)
terminate called after throwing an instance of 'xpp::x::error::name'
  what():  XCB_NAME (15)
Aborted (core dumped)
```

**Comment by jaagr** [comment]
Could you test if it persists with the latest release?

**Comment by roberoonska** [comment]
Issue still persists.

**Comment by jaagr** [comment]
Are you able to build the project manually? Then you can compile a debug build which will enable trace messages.

**Comment by roberoonska** [comment]
I don't think I know enough about this stuff to do that, sorry.

**Comment by jaagr** [comment]
How did you install polybar?

**Comment by roberoonska** [comment]
Sorry, I just saw your edits to your earlier comment. I followed your instructions which output:
```
warn: No monitor specified, using "eDP1"
error: Disabling module "bspwm" (reason: Could not find socket: /tmp/bspwm_0_0-socket)
error: Disabling module "eth" (reason: Invalid network interface "net0")
warn: Could not find glyph for 57967
warn: Could not find glyph for 57384
warn: Could not find glyph for 57382
warn: Could not find glyph for 57912
warn: Could not find glyph for 57547
warn: Could not find glyph for 57366
warn: Could not find glyph for 57612
```
The lines about glyphs then repeat that series of numbers indefinitely. Maybe that is just because I don't have the appropriate fonts installed?

**Comment by jaagr** [comment]
Yeah that's why... But you can just update the config and use a font that you have

**Comment by roberoonska** [comment]
Is that what is causing the original error?

**Comment by jaagr** [comment]
I don't think so.. Because now the bar starts right? Just that it looks odd without the fonts.

**Comment by roberoonska** [comment]
Nope, the issue still hasn't been resolved. It still puts out the same error as it did in the first place.

**Comment by jaagr** [comment]
Ok, can you launch the bar using `polybar example -l trace`

**Comment by roberoonska** [comment]
I reinstalled the debug version and the bar seems to load now! Not sure what changed. Is it okay to use the bar in debug mode?

**Comment by jaagr** [comment]
yeah, but it is probably slower.. try to compile a release build manually and see if it works..

~~~ sh
$ cd /path/to/polybar/source
$ mkdir build-release
$ cd build-release
$ cmake -DCMAKE_BUILD_TYPE=Release ..
$ make 
$ ./bin/polybar example
~~~
