### ISSUE TITLE
Broken mouse clicks

### ISSUE THREAD

**Issue by NBonaparte** [jaagr/polybar#302]
Output with trace log:
```
- bar: Received button press: 1 at pos(253, 7)
- Found matching input area
warn: Uncaught input event, forwarding to shell... (input: �)
* Executing shell command: �
- command: Waiting for pid 7513 to finish...
warn: command: Exited with failed status 127
```
Clicking on the bar results in the error above. On the latest commit, it appears for every clickable module (and also the fallback handlers), but on 2.4.6 only the bspwm and script modules don't work (on my setup at least).

Note: scrolling still works fine.

**Comment by zestyr** [comment]
bspwm doesn't work here either on 2.4.6, can't click nor use the scroll wheel to change workspaces.

**Comment by warmwaffles** [comment]
I am also suffering from the same issue as well.

**Comment by Deluxo** [comment]
Clicks are broken again, scrolling works well.
```
polybar 2.4.6 

Features: +alsa +curl -i3 +mpd +network 

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro

```

**Comment by NBonaparte** [comment]
Confirming that menu _execution commands_ don't work, while the main menu button works fine as said in the previous comment.

**Comment by ax333l** [comment]
For me clicks are working when the command is an installed applications (for example gsimplecal), but not if it's a file-script.
Output on click event for file-script: 
`warn: Uncaught input event, forwarding to shell... (input: )`
Output on click event for an app:
`warn: Uncaught input event, forwarding to shell... (input: gsimplecal)`

**Comment by jaagr** [comment]
Weird, the click handlers works fine on my build. Could you supply some information about the build (compiler, flags, etc) so I could try to reproduce the issue?

**Comment by ax333l** [comment]
I'm using the polybar-git package from AUR, didn't change anything.
`polybar 2.4.6-1-g4c4cf87-git 

Features: +alsa +curl +i3 +mpd +network`

**Comment by jaagr** [comment]
@ax333l could you show the output of `polybar -vv`

**Comment by ax333l** [comment]
```
polybar 2.4.6-1-g4c4cf87-git 

Features: +alsa +curl +i3 +mpd +network 

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro

ALSA_SOUNDCARD              default
BSPWM_SOCKET_PATH           /tmp/bspwm_0_0-socket
BSPWM_STATUS_PREFIX         W
BUILDER_SPACE_TOKEN         %__
CONNECTION_TEST_IP          8.8.8.8
PATH_ADAPTER                /sys/class/power_supply/%adapter%
PATH_BACKLIGHT_MAX          /sys/class/backlight/%card%/max_brightness
PATH_BACKLIGHT_VAL          /sys/class/backlight/%card%/brightness
PATH_BATTERY                /sys/class/power_supply/%battery%
PATH_CPU_INFO               /proc/stat
PATH_MEMORY_INFO            /proc/meminfo
PATH_TEMPERATURE_INFO       /sys/class/thermal/thermal_zone%zone%/temp
```

**Comment by jaagr** [comment]
and what compiler is `/usr/bin/c++` pointing to (`c++ -v`)?

**Comment by ax333l** [comment]
```
COLLECT_GCC=c++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc-multilib/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 6.2.1 20160830 (GCC) 
```

**Comment by ax333l** [comment]
Downgraded to last used version (2.3.11) and everything works just fine, gonna check now when it stops working.

**Comment by jaagr** [comment]
I'm pretty sure it's related to the event data structures.

**Comment by ax333l** [comment]
The scripts worked up to 2.3.13, no success on 2.4.0+, but I got them working by rewriting them, therefore fixed my issue, which turned out to be on my side. Sorry for taking your time.

**Comment by jaagr** [comment]
@ax333l would you mind sharing the one that didn't work plus the fix?

**Comment by ax333l** [comment]
So the previously working script was [shutdown menu](https://github.com/vivien/i3blocks-contrib/blob/master/shutdown_menu/shutdown_menu), I just took out the basic functionality (without zenity compatibility, confirmations etc) to a new script which looks like this:
```
#!/bin/bash
typeset -A menu
menu=(
[Shutdown]="systemctl poweroff"
[Reboot]="systemctl reboot"
[Hibernate]="systemctl hibernate"
[Suspend]="systemctl suspend"
[Halt]="systemctl halt"
[Lock]="${LOCKSCRIPT:-i3lock --color=${BG_COLOR#"#"}}"
[Logout]="i3-msg exit"
[Cancel]=""
)
menu_nrows=${#menu[@]}
select=$(printf '%s\n' "${!menu[@]}" | sort | rofi -dmenu -i -lines 8 -p "Menu:")
 ${menu[${select}]}
```

**Comment by zigarrre** [comment]
I can confirm this bug for the internal/bspwm module in 2.4.6. Clicking on desktops does nothing except printing: `warn: Uncaught input event, forwarding to shell... (input: )`. I've installed polybar via the `polybar` package from the AUR.

```
[zigarrre@desktop ~]% polybar -vv
polybar 2.4.6 

Features: +alsa +curl -i3 +mpd -network 

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=native -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro

ALSA_SOUNDCARD              default
BSPWM_SOCKET_PATH           /tmp/bspwm_0_0-socket
BSPWM_STATUS_PREFIX         W
BUILDER_SPACE_TOKEN         %__
CONNECTION_TEST_IP          8.8.8.8
PATH_ADAPTER                /sys/class/power_supply/%adapter%
PATH_BACKLIGHT_MAX          /sys/class/backlight/%card%/max_brightness
PATH_BACKLIGHT_VAL          /sys/class/backlight/%card%/brightness
PATH_BATTERY                /sys/class/power_supply/%battery%
PATH_CPU_INFO               /proc/stat
PATH_MEMORY_INFO            /proc/meminfo
PATH_TEMPERATURE_INFO       /sys/class/thermal/thermal_zone%zone%/temp
[zigarrre@desktop ~]% c++ -v     
Using built-in specs.
COLLECT_GCC=c++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc-multilib/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 6.2.1 20160830 (GCC)
```

**Comment by jaagr** [comment]
note: since it shows an empty string after `input: ` I would guess that the string containing the command isn't allocated on the heap when the signal gets emitted.

**Comment by jaagr** [comment]
Could someone confirm that it works using `2.4.5`?

**Comment by ax333l** [comment]
Installed 2.4.5, everything works just fine.

**Comment by bryanbecker** [comment]
`2.4.7` still not working for me.

As above, mpd buttons, xkeyboard,time all work.  Menu works in so far as drilling down, but the final menu action doesn't work (using the example power-bar menu script).  bspwm doesn't work at all

**Comment by NBonaparte** [comment]
@jaagr said he "will try to patch this tomorrow".

**Comment by bryanbecker** [comment]
Sorry, misread the above comments to mean `2.4.5` fixed the issue.  Missed the part about `2.4.6` introducing the issue

**Comment by ax333l** [comment]
Can confirm that it's working now on `2.4.8`.

**Comment by SageEx** [comment]
It's working again, thanks.
