### ISSUE TITLE
battery module catch wrong status ? core dump

### ISSUE THREAD

**Issue by eoli3n** [jaagr/polybar#303]
This morning without any apparent reason, module battery core dump the complete bar.

Here the conf

```
[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 98
time-format = "%H%{F#92}%M%{F-}"

label-discharging = %percentage% %time%

format-charging = <animation-charging> <label-charging>
format-charging-underline = #ffb52a

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-underline = ${self.format-charging-underline}

format-full-prefix = " "
format-full-prefix-foreground = ${colors.foreground-alt}
format-full-underline = ${self.format-charging-underline}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${colors.foreground-alt}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = ${colors.foreground-alt}
animation-charging-framerate = 750
```

The problem seems to be my charge status which is not catch correctly, my battery is old

```
# cat /sys/class/power_supply/BAT0/status     
Unknown
```

Maybe you need to catch that case, not execute the module if the status is not full|charging|discharging and print an error.

**Comment by NBonaparte** [comment]
My battery status becomes "Unknown" after it reaches ~95%, but the module still works fine... it might be something else.

**Comment by eoli3n** [comment]
On my other laptop, at 100%, status is "Full". I saw that there are lots of issue about that module, wait and see

**Comment by jaagr** [comment]
This should be fixed by ef44202 as the crash probably is related to the attempt past string end. Please confirm

**Comment by eoli3n** [comment]
Cannot test, battery status is "Full" for now, and I don't know how to reproduce "unknown"

**Comment by jaagr** [comment]
I'm pretty sure it's fixed. Let me know if it would happen again and I will reopen.

**Comment by eoli3n** [comment]
it's not

```
 userarch@arch-itect  ~  cat /sys/class/power_supply/BAT0/status 
Unknown
```
just crashed with
```
[1]    8777 floating point exception (core dumped)  polybar top
```

**Comment by jaagr** [comment]
@eoli3n Could you check the contents of the value files? 

~~~
$ cat /sys/class/power_supply/BAT0/{charge_now,charge_full,voltage_now,current_now}
~~~

**Comment by jaagr** [comment]
I will add some safety checks to the code

**Comment by eoli3n** [comment]
```
 userarch@arch-itect  ~  cat /sys/class/power_supply/BAT0/{charge_now,charge_full,voltage_now,current_now}
3091000
3271000
12235000
1000
```

**Comment by jaagr** [comment]
Are you able to reproduce it manually? If so, could you launch the bar with gdb and get the stacktrace?

**Comment by jaagr** [comment]
I was able to reproduce the exception when I hardcoded your values, so I won't need the stacktrace. Patch coming up.

**Comment by eoli3n** [comment]
it seems working, thx
