### ISSUE TITLE
label limiter formatting : wrong suffix print

### ISSUE THREAD

**Issue by eoli3n** [jaagr/polybar#305]
```
[module/xwindow]
type = internal/xwindow
label = "    %{F#5b5b5b}%{F-} %title:0:70:...%"
```
prints "...%" at the end of the line. Shoud'nt it be "..." only ?

![alt text](http://ptpb.pw/mJYZ.png)

```
NOTE: the length of the token includes suffixes appended internally (KB/s, %, etc.)
```
Maybe that's chrome suffix ? When i set 150 chars, there isn't anything

When i try 
```
vim longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglongstring
```
xwindow only prints "vim"

**Comment by jaagr** [comment]
You are correct, it should only be "..." I will have a look at the code.

I don't really understand your issue. Could you please explain the chrome and xwindow part?

**Comment by eoli3n** [comment]
I was wondering if "%" was added by chrome or polybar, in reference of your wiki quote.

![alt text](http://ptpb.pw/YFEp.png)

**Comment by jaagr** [comment]
It was added by polybar and it was a bug. I just pushed a patch that fixes it (see 3722ac1)

**Comment by eoli3n** [comment]
understood that :) and the vim part ? i will try later, thx

**Comment by jaagr** [comment]
The xwindow module uses the value that is set for the atom value

**Comment by eoli3n** [comment]
worked, thx
