### ISSUE TITLE
Add left/right click events for date

### ISSUE THREAD

**Issue by hiemanshu** [jaagr/polybar#306]
I want to be able to click the date and have it open a simple calendar (gsimplecal). The date module doesn't currently listen to events. I know I can use the custom module to do this, but I'd rather use the date module for this.

**Comment by d125q** [comment]
I think that every module should have custom click handlers rather than predefined ones...

**Comment by jaagr** [comment]
I think we should keep the predefined handlers but make it possible to override them with custom ones.

**Comment by jaagr** [comment]
Closing, duplicate of #273
