### ISSUE TITLE
Restarting i3-gaps breaks desktop updating.

### ISSUE THREAD

**Issue by CMMCD** [jaagr/polybar#307]
If you restart i3-gaps using $mod+shift+r the desktop display will stop updating.

**Comment by taylorthurlow** [comment]
Also experiencing this issue.

**Comment by jaagr** [comment]
For now I'd say restart the bar when restarting the WM.

**Comment by pascalwhoop** [comment]
so for the lazy: i3 that works for me


[exec_always](https://i3wm.org/docs/userguide.html#_automatically_starting_applications_on_i3_startup)
```
exec_always --no-startup-id killall polybar 2>/dev/null | true && polybar --reload pascalwhoop
```
the 2> hides the error message if no polybar exists (kind of redundant but clean), the `|true` avoids errors if no polybar started yet (at boot), the rest is explained in the link
