### ISSUE TITLE
Network module doesn't handle tun interface that doesnt exist on boot

### ISSUE THREAD

**Issue by JMare** [jaagr/polybar#309]
Hi,

I'm using polybar to display vpn status, my config for the module is here:
```
[module/ovpn]
type = internal/network
interface = tun0 
interval = 3.0

format-connected-padding = 1
format-disconnected-padding = 1

format-connected = <label-connected>
format-connected-underline = ${colors.white}
format-disconnected-underline = ${colors.gray}

label-connected =  
label-disconnected = 
label-disconnected-foreground = ${colors.gray}

```

While this works fine for my wlan and eth interfaces, the tun0 interface does not exist when polybar starts, so the module gets unloaded, and wont display even if the tun0 gets created later when the vpn connects.

It would be good if there was an option to set to keep trying the interface at $interval even if it does not exist when polybar starts, rather than killing the module.

**Comment by jaagr** [comment]
The network module will have to be updated after changing backend (see #277) so until then I'd say restart the bar after setting up the interface.

**Comment by jaagr** [comment]
Closing as this won't be fixed using the current network adapter
