### ISSUE TITLE
Polybar running with this config draws a ridiculous amount of battery power

### ISSUE THREAD

**Issue by mindstormer12** [jaagr/polybar#311]
I was told to submit a github issue about this, details on this [Reddit thread](https://www.reddit.com/r/unixporn/comments/5mtuax/polybar_using_ridiculous_amount_of_battery_power/) (hope you don't mind).

**Comment by NBonaparte** [comment]
Have you tried turning each module off individually and comparing the power?

**Comment by mindstormer12** [comment]
I just tested and the battery module in my config is the culprit--it is responsible for ~9-11 W of usage, which is by far the biggest resource usage from the modules tested. Without just this module in my config, my discharge rate is ~5 W.

**Comment by NBonaparte** [comment]
Why is your animation framerate 9999999999999999999999999?

**Comment by mindstormer12** [comment]
That was the issue... I used my friend's config and he trolled me... Sorry for wasting your time and I deleted the Reddit thread and am closing this "issue" -_-
