### ISSUE TITLE
[battery module] Average charge of two batteries

### ISSUE THREAD

**Issue by realcomplex** [jaagr/polybar#312]
Hey!

My laptop has two batteries (BAT0 and BAT1), and I would like the battery module in polybar to show the average charge of both. Is this possible?

Thanks in advance for the help, I'm really loving polybar!

**Comment by NBonaparte** [comment]
There's a pull request open which accomplishes exactly what you requested: #227.

**Comment by realcomplex** [comment]
Okay cool, I'll just wait for the pull request to get merged then.

**Comment by jaagr** [comment]
Hi, it's not supported by the built-in battery module but you could use a script module, for example:

~~~ dosini
[module/avg-battery]
type = custom/script
exec = "count=$(acpi -b | wc -l); sum=$(acpi -b | egrep -o '[0-9]{1,3}%' | tr -d '%' | xargs -I% echo -n '+%'); echo Avg capacity: $(( sum / count ))%" 
interval = 5
~~~

**Comment by realcomplex** [comment]
@jaagr: thank you, I'll use that for now!
