### ISSUE TITLE
Unable to display glyph

### ISSUE THREAD

**Issue by hg8** [jaagr/polybar#313]
Hello,

I am having trouble to make the example bar working properly. Each time I launch it I am getting warnings : 

> warn: Could not find glyph for 57967
> warn: Could not find glyph for 57384
> warn: Could not find glyph for 57382
> warn: Could not find glyph for 57366
> warn: Could not find glyph for 57612
> warn: Could not find glyph for 57967
> warn: Could not find glyph for 57384
> warn: Could not find glyph for 57382
> warn: Could not find glyph for 57366
> warn: Could not find glyph for 57612

and no glyphs are displayed.

I have installed `ttf-unifont` and `siji-git` : 

    $ pacaur -S ttf-unifont siji-git

    $ pacman -Qs siji            
        local/siji-git r21.95369af-1
            Iconic bitmap font based on stlarch with additional glyphs

    $ pacman -Qs ttf-unifont 
        local/ttf-unifont 9.0.06-2
            TrueType version of the GNU Unifont

Running `fc-match` give me : 
    
    $ fc-match fixed:size=10                      
    DejaVuSans.ttf: "DejaVu Sans" "Book"

    $ fc-match unifont:size=6                          
    Unifont.ttf: "Unifont" "Medium"

    $ fc-match siji:pixelsize=10
    DejaVuSans.ttf: "DejaVu Sans" "Book"

Seems like `siji` is not detected... What can be the problem here ? Thanks in advance for your help.

    $ polybar -v
    polybar 2.4.7 

    Features: +alsa +curl +i3 -mpd -network

**Comment by jaagr** [comment]
Your `siji` probably has another family name. Replace `font-<num> = siji...` in the polybar config by the result of this command:

~~~ sh
$ echo "$(fc-list : family | grep siji | tail -1):pixelsize=10"
~~~

**Comment by hg8** [comment]
Ok got it. Seems like I need to replace :  


    font-2 = siji:pixelsize=10;0

with : 

    font-2 = WunconSiji:pixelsize=10;0

**Comment by jaagr** [comment]
ah yeah, my grep is aliased to `grep -i` so didn't think about the case. Thanks man.

**Comment by chrissnell** [comment]
@jaagr do you think the wiki docs and example config could be updated to reflect this, or at least, a note about what to do if it doesn't work?  I've been trying to fix this for hours and couldn't figure out why it still didn't work even after installing siji.  I'm using Arch and noticed that I had Wuncon Siji like @hg8 .  I suspect that a lot of Arch users are hitting this snag.  Thanks!

**Comment by NBonaparte** [comment]
If you think it's important, I'd say just add it yourself (the wiki should be editable by everyone).

**Comment by nikolowry** [comment]
Is Siji fixed to pixelsize 10? I can't seem to get it to render at any other size.  I have a hidpi screen and the icons are barely visible.  Are there any other recommended glyph fonts?

**Comment by chrissnell** [comment]
It is.   It's a bitmap font and looks crappy on my HiDPI, too.   I would
like to use Font Awesome which--I believe--is vector.  I'm not sure how to
type the glyphs on the keyboard into the config file, though.

**Comment by hg8** [comment]
@chrissnell 

For Font Awesome, you can copy/paste glyph from here : http://fontawesome.io/cheatsheet/

**Comment by mk0lev** [comment]
Hey, I use Arch Linux, i3 with polybar and I encounter the same problem, that polybar just won't display the glyphs. They display in the terminal, so it's not a systemwide problem. 
The output of `fc-match` is
`NotoSans-Regular.ttc: "Noto Sans" "Regular"`
In polybar's config I have 
```
font-0 = fixed:pixelsize=12;1
font-1 = unifont:fontformat=truetype:size=10:antialias=false;0
font-2 = WunconSiji:pixelsize=12;1
```
What do I do wrong?

**Comment by darkin1** [comment]
In my case I needed to remove ` /etc/fonts/conf.d/70-no-bitmaps.conf `

thx for https://github.com/jaagr/polybar/issues/22#issuecomment-275254031

**Comment by sanguine8082** [comment]
Just to chime in, I had to set it to
`font-2 = Wuncon Siji:pixelsize=10;0`

**Comment by patrick96** [comment]
@lulivi that's not how you check the font. See the [Wiki](https://github.com/jaagr/polybar/wiki/Fonts#debugging-font-issues) for how to check, if the font loaded properly

**Comment by ws-jung** [comment]
Have you tried adding style?
Try it like this
```
font-1 = "Font Awesome 5 Free:size=14:antialias=true:style=Solid;0"
```

**Comment by fredcox** [comment]
I never see maybe more complicated this. Where are siji fonts and how to use siji fonts with polybar? It is one thing simple and you transform into storm.
