### ISSUE TITLE
Font icon with i3

### ISSUE THREAD

**Issue by ChoiZ** [jaagr/polybar#317]
I try to activate polybar icons in my bar without success.

I don't understand what I have to put in my i3 configuration actually:
```
set $w01 "1"
set $w02 "2"
set $w03 "3"
```

And my polybar i3 section:
```
[module/i3]
type = internal/i3
format = <label-state> <label-mode>
#index-sort = true
#wrapping-scroll = false
pin-workspaces = true
#strip-wsnumbers = false

ws-icon-0 = 1;
ws-icon-1 = 2;2: 
ws-icon-2 = 3;3: 

ws-icon-default = 

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}

label-focused = %icon%
label-focused-background = ${module/bspwm.label-focused-background}
label-focused-underline = ${module/bspwm.label-focused-underline}
label-focused-padding = ${module/bspwm.label-focused-padding}

label-unfocused = %icon%
label-unfocused-padding = ${module/bspwm.label-occupied-padding}

label-urgent = %icon%!
label-urgent-background = ${module/bspwm.label-urgent-background}
label-urgent-padding = ${module/bspwm.label-urgent-padding}

label-visible = %icon%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}
```

Do I have to activate strip-wsnumbers to true ?

My first workspace is for firefox $w01 in i3, so do I have to write:
```
ws-icon-0 = 1;
```
or 
```
ws-icon-0 = 
```
or 
```
ws-icon-0 = 1;1: 
```
?

Thanks for your help.

**Comment by jaagr** [comment]
Hi, use this command to get a template

~~~
$ i3-msg -t get_workspaces | jq '.[] | .name' | xargs -I% echo "ws-icon-N = %;insert-icon-here"
~~~

**Comment by eoli3n** [comment]
I use

```
[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
strip-wsnumbers = true
pin-workspaces = true

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}

label-focused = %name%
label-focused-background = ${module/bspwm.label-focused-background}
label-focused-underline = ${module/bspwm.label-focused-underline}
label-focused-padding = ${module/bspwm.label-focused-padding}

label-unfocused = %name%
label-unfocused-padding = ${module/bspwm.label-occupied-padding}

label-urgent = %name%!
label-urgent-background = ${module/bspwm.label-urgent-background}
label-urgent-padding = ${module/bspwm.label-urgent-padding}

label-visible = %name%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-7 = 8;
ws-icon-8 = 9;
ws-icon-9 = 10;
```
to get 

![alt](http://ptpb.pw/bFju.png)

**Comment by ChoiZ** [comment]
Thanks to @eoli3n dotfiles configuration I found my mistake.

`font-3 = FontAwesome:pixelsize=14;0` was missing in my configuration.

Thanks @jaagr and @eoli3n it's works perfectly (bye bye i3bar).

**Comment by undying-fish** [comment]
This isn't working for me. FontAwesome is loaded using the line @ChoiZ gave as their solution, but when I run with info logs I still get a lot of warnings about `unmatched character`s. My workspaces in i3 are named 0 through 9 with no additional characters and I've used @eoli3n's config up there verbatim. FontAwesome returns correctly with fc-match, too.

**Comment by eoli3n** [comment]
gisting your log file and config files will be more helpful
https://gist.github.com/

**Comment by C0reTex** [comment]
I got a similar issue. I post it here so maybe it helps someone.

When assigning icons to a workspace, you cannot set `ws-icon-9 = "9;"` without also assigning values to `ws-icon-[0-8]`. By skipping a `ws-icon-*` all following workspaces are displayed without icons.

Does **not** work:
```
ws-icon-3 = "4;"
ws-icon-4 = "5;"
```

**Works:**
```
ws-icon-0 = "1;"
ws-icon-1 = "2;"
ws-icon-2 = "3;"
ws-icon-3 = "4;"
ws-icon-4 = "5;"
```

**Comment by patrick96** [comment]
@C0reTex this is expected behaviour, `ws-icon-*` just represents a list of values (the order doesn't really matter here), since polybar can't know how long that list is, it just checks for consecutive numbers if `ws-icon-X` exists and as soon as it finds one that doesn't, it stops.
