### ISSUE TITLE
Segfault when not including `<label-discharging>` in `format-discharging`

### ISSUE THREAD

**Issue by adamransom** [jaagr/polybar#318]
Fairly simple as the title says, when setting:

```
format-discharging = <ramp-capacity>
```

for the battery module, I get a segfault when battery is in discharge mode.

_Note: I realise I can work around this by adding an empty `<label-discharging>`, but just pointing out the segfault :) It also seems that add empty labels adds extra white space that I'd rather not have!_

**Comment by jaagr** [comment]
Thanks for reporting. I'll patch it.

I'd recommend checkout out the latest release tag to avoid issues at the master branch.
