### ISSUE TITLE
labels in module/filesystem are 'gone'

### ISSUE THREAD

**Issue by Isotop7** [jaagr/polybar#321]
Hi, im using this conf for module/filesystem:

```
[module/filesystem]
type = internal/fs
interval = 60

mount-0 = /
mount-1 = /home
mount-2 = /drives/Daten

spacing = 4

label-mounted =    %mountpoint%: %percentage_used%
label-unmounted =    %mountpoint%: not mounted
label-unmounted-foreground = ${colors.red}
```

Even though i specified %mountpoint% the label is only consisting of '/'.

![2017-01-11-203716_615x34_scrot](https://cloud.githubusercontent.com/assets/8883656/21863446/c28788c0-d83d-11e6-8a87-aeed3677889a.png)

In 2.4.6 these were named according to the values in mount-[0-9].

**Comment by jaagr** [comment]
Hi, thanks for reporting. I'll patch it right away.
