### ISSUE TITLE
Fix visual glitch with long running command in ipc module

### ISSUE THREAD

**Issue by realcomplex** [jaagr/polybar#324]
Hey!

I had a slight issue with the ipc module of polybar. Basically, a command would grab some information about current playing song / pause status on a raspberry pi over the network, and because this is a network operation, there is a little bit of delay. During this delay, between when the module got a signal to update and when the command finished, the relevant section of polybar would go blank, resulting in a visual glitch.

I fix this by very slightly rewriting the ipc module, replacing these lines (110 - 114):
```
m_output.clear();

auto command = command_util::make_command(hook->command);
command->exec(false);
command->tail([this](string line) { m_output = line; });
```
with the following:
```
// m_output.clear();

auto command = command_util::make_command(hook->command);
command->exec(false);
command->tail([this](string line) { m_output.clear(); m_output = line; });
```
This just waits to clear the output until the command has actually finished running. Do you think you could make this change to polybar? I can't really think of any cases where this would be an undesirable change.

Thanks for your work on polybar, awesome!

**Comment by jaagr** [comment]
Hi.

Yeah there's really no need to clear it before anyway. I will patch it.
