### ISSUE TITLE
menu module : auto close at last choice

### ISSUE THREAD

**Issue by eoli3n** [jaagr/polybar#327]
I added to the default menu my session locker.
Problem is that it seems more logical to me to autoclose that menu when you choose one of last submenu item.

When i unlock my screen, the submenu is still open.

**Comment by jaagr** [comment]
Hm I actually added that a while ago. I'll have a look

**Comment by jaagr** [comment]
@eoli3n I added a force update after running input commands. Could you try with the latest source

**Comment by eoli3n** [comment]
not working with 
```
[module/powermenu]
type = custom/menu

label-open = 
label-open-foreground = #b63650
label-close =  cancel
label-close-foreground = ${colors.secondary}
label-separator = |
label-separator-foreground = ${colors.foreground-alt}

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2
menu-0-2 = log out
menu-0-2-exec = menu-open-3
menu-0-3 = 
menu-0-3-exec = ~/.i3/i3lock-fancy-multimonitor/lock

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = sudo reboot

menu-2-0 = power off
menu-2-0-exec = shutdown now
menu-2-1 = cancel
menu-2-1-exec = menu-open-0

menu-3-0 = log out
menu-3-0-exec = i3-msg exit
menu-3-1 = cancel
menu-3-1-exec = menu-open-0
```

**Comment by jaagr** [comment]
can you show me `~/.i3/i3lock-fancy-multimonitor/lock`

**Comment by eoli3n** [comment]
https://github.com/guimeira/i3lock-fancy-multimonitor/blob/master/lock

**Comment by eoli3n** [comment]
ah ok, i think i understand... process i3lock is holding the script, to rm image file after unlocking. But should it close after rm cmd ? it didn't

**Comment by zestyr** [comment]
Try `menu-0-3-exec = ~/.i3/i3lock-fancy-multimonitor/lock &`

**Comment by eoli3n** [comment]
Not working, even if i  change the line to 
```
menu-0-3-exec = echo toto
```

**Comment by jaagr** [comment]
Can you try with this patch and see if it fixes it

~~~ patch
diff --git a/src/modules/menu.cpp b/src/modules/menu.cpp
index 1879d8f..5935ae5 100644
--- a/src/modules/menu.cpp
+++ b/src/modules/menu.cpp
@@ -92,6 +92,7 @@ namespace modules {
           break;
         }
       }
+      broadcast();
       return false;
     }
 
~~~

**Comment by eoli3n** [comment]
fixed, thx again
