### ISSUE TITLE
feature request : app launcher module

### ISSUE THREAD

**Issue by eoli3n** [jaagr/polybar#328]
This might be cool to add an app launcher module. I think it's a huge project, but very usefull.
Would be cool to be able to recreate a full DE based on tilling WM like i3 or bspwm.

For now, i force my systray at top left of main display polybar, and use [menutray](https://aur.archlinux.org/packages/menutray/).

``.i3/config``
```
exec_always --no-startup-id $HOME/.config/polybar/launch.sh
exec --no-startup-id menutray -i
```

``.config/polybar/config``
```
[bar/top]
tray-position = left
tray-padding = 4
[bar/$all_other_bar]
tray-position = 
```

![alt text](http://ptpb.pw/h3Y1.png)

Limitations
* Systray cannot be duplicate
* Systray cannot be placed anywhere : will be fixed by https://github.com/jaagr/polybar/issues/314

**Comment by eoli3n** [comment]
That kind of app launcher are more usefull for me, because it list all .desktop files on the system, and gives you a clear view on what you have, not like rofi, i3-dmenu-desktop, albert... etc

**Comment by alekcacko** [comment]
I like to have module such like that too, Having a menu on systray have some limitations.

**Comment by CadaverLab** [comment]
could whiskermenu be used with polybar or is that tied to xfce-panel?

**Comment by NBonaparte** [comment]
@CadaverLab that's part of xfce-panel.

This feature request would probably require GTK or Qt to render the menus, which would bloat the dependencies.
Another option would be to render windows through xcb, which is more feasible but you won't get the same GTK/Qt theme.

**Comment by CadaverLab** [comment]
@NBonaparte how about something like [myGTKmenui](https://github.com/dumblob/mygtkmenui) then

**Comment by chris-marsh** [comment]
I've been messing about with this  method ...
`
[module/arch]

type = custom/text
content = "   "
click-left = pymenu.py
`

The menu is produced by a python script. I have a [copy in my repo](https://bitbucket.org/chris-marsh/dotfiles/src/acab5fde7f4f5a88a74795f21f8b9bf5a8b96412/bin/pymenu.py?at=master&fileviewer=file-view-default). I did not write the code and unfortunately i can't remember where I got it to give credit.

The script has gtk dependencies and will use GTK themes.

Screenshot ... [http://imgur.com/a/Z8Zy7](http://imgur.com/a/Z8Zy7)

**Comment by eoli3n** [comment]
It works well exept that it putted me all apps in a single "others" menu :)

![menu](http://ptpb.pw/N2mk.png)

**Comment by chris-marsh** [comment]
> It works well exept that it putted me all apps in a single "others" menu :)

I'm away from my own PC just now, but having a quick look at the script the problem might be to do with locale/language? It is hard coded to look for categories in English, eg "Network" and Utility" and the fallback category is "Other". You could try editing the categories.

**Comment by eoli3n** [comment]
Just found that, didn't test yet 
https://github.com/kernladung/californium

**Comment by chris-marsh** [comment]
I have just tried californium. DO NOT sudo make uninstall, it has just ran rm -rf /user 

I should have read the makefile....  A night of salvage and rebuilding for me.

**Comment by eoli3n** [comment]
... it sucks. did you open an issue ?

**Comment by chris-marsh** [comment]
> ... it sucks. did you open an issue ? you should, to prevent other problems with some users, we talk about this guy's projects on #archlinux-fr

Not yet, but I will. Anyway rather than repair my system it gave me the excuse to wipe and reinstall my system partition.

And .. linking back to my python script and the PolyBar launcher ... when I reinstalled mt system from base it was also putting all apps into "Other". A bit of research reminded me that I had previously installed [archlinux-xdg-menu](https://www.archlinux.org/packages/community/any/archlinux-xdg-menu/)' This populates the [xdg menu](https://wiki.archlinux.org/index.php/xdg-menu) structures and keeps them updated. Obviously thats an Arch package but I would guess there should be equivalents on other distros.

**Comment by jaagr** [comment]
Closing. I'll add a reference to this in #84

**Comment by oyren** [comment]
jgmenu and polybar work well together
