### ISSUE TITLE
Unwanted volume module behavior

### ISSUE THREAD

**Issue by zestyr** [jaagr/polybar#329]
When scrolling up/down to change volume, once you reach 0% or 100%, the volume module stops taking scroll events in that direction. IE. if I'm scrolling up, reach 100%, scroll up again, it'll pass the event to the bar's `scroll-up` event, which changes my workspace. This is very much unwanted behavior as I don't want to suddenly change workspace while changing my volume.

Another thing that annoys me a little bit is being unable to leave out the `%` suffix Not a big deal, but being able to configure the volume output prefix/suffix would be quite nice.

**Comment by jaagr** [comment]
I've been having this exact same issue but haven't gotten to fix it yet, but it will be fixed.

I guess we could just make the percentage sign the default suffix for those labels.

**Comment by jaagr** [comment]
If you are able to build the project manually you can test https://github.com/jaagr/polybar/tree/refactor-tokensuffix which removes the hard coded percentage signs for label tokens. There are probably more suffixes that could be moved out.

**Comment by zestyr** [comment]
Thanks for acting on this so quickly. I'll try building it right away.

**Comment by zestyr** [comment]
Seems like it works.
![pbar](https://cloud.githubusercontent.com/assets/9434921/21942621/21676c02-d9ce-11e6-9732-206c7d47e477.png)

**Comment by jaagr** [comment]
The change has been merge into master
