### ISSUE TITLE
i3 module refresh

### ISSUE THREAD

**Issue by eoli3n** [jaagr/polybar#333]
Maybe related to https://github.com/jaagr/polybar/issues/304

I setted a click event on wlan module 
```
label-connected = "%{A1:connman-gtk:}%essid%%{A}"
label-disconnected = "%{A1:connman-gtk:}%{A}"
```

in my ``.i3/config``, i have

```
set $tag10 "10:"
assign [class="Connman-gtk"] $tag10
```

If i'm not on this $tag10 workspace and i click on the module to run connman, it works
but i3 module focus the right workspace without updating the "workspace selector".

1° i'm on term workspace
![alt](http://ptpb.pw/2-eT.png)

2° i click on module : right workpace is focus but still showing term workspace in i3 module  
And then i3 module is completly frozen, switching workspace keep showing term workspace, until i close connman.

![alt](http://ptpb.pw/zFjE.png)

3° close connman window : i3 module refresh and show right workspace
![alt](http://ptpb.pw/ilPM.png)

**Comment by jaagr** [comment]
This is because you are blocking it when you run the command.

You need to append `&` to  the command to allow async execution. For example:

~~~ dosini
%{A1:myprogram &:}...%{A}
~~~

**Comment by eoli3n** [comment]
it doesn't fix it

**Comment by jaagr** [comment]
Can you post your full configuration
