### ISSUE TITLE
Extra space in between ramp and label

### ISSUE THREAD

**Issue by NBonaparte** [jaagr/polybar#337]
Since 2.5.0 or 2.5.1 an extra space appears between the volume ramp and the label.

**Comment by jaagr** [comment]
damn.. thought i found all

**Comment by NBonaparte** [comment]
```
[module/volume]
type = internal/volume
mapped = true
format-volume = <ramp-volume> <label-volume>
label-volume = %percentage:3%%
label-muted = MUTE
format-muted-prefix = " "
format-muted-prefix-foreground = ${colors.icon}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-foreground = ${colors.icon}
```
(Icons aren't appearing when I paste, but they are there...)

**Comment by jaagr** [comment]
It works for me fine for me..

- You're aware of the `:3` in the token right?
- Did you set `spacing` for the bar? If so, it is now changed to 0 by default and will be removed sometime...

**Comment by NBonaparte** [comment]
It was spacing.
