### ISSUE TITLE
Little delay when clicling on workspace number to change.

### ISSUE THREAD

**Issue by alekcacko** [jaagr/polybar#338]
When I click on workspace number there is a little delay on clicking to changethe workspace.

![Screenshot on workspace](https://s29.postimg.org/g3zwsx0br/2017_01_14_23_40_30_screenshot.png)

The first bar is i3bar, the second polybar.

I tested clicking on both, and i3bar is smoother than polybar.

EDIT: I also noticed this little delay when clicking on volume module to mute.

Is there a way to fix it or it is technical error with the implementation of polybar?

EDIT2: I am using Ubuntu 16.04, polybar version 2.5.0 -curl +i3 +mpd +all other

EDIT3: When scrolling on polybar to change workspace on polybar its super smooth :)

**Comment by eoli3n** [comment]
I have that issue too, seems faster with $mod+$tag keys

**Comment by jaagr** [comment]
Sounds like it might be the double click timer.

**Comment by alekcacko** [comment]
Thank you @jaagr

I am going to recompile your fix tomorow.

**Comment by eoli3n** [comment]
worked for me
