### ISSUE TITLE
Issue with dock option

### ISSUE THREAD

**Issue by jonathashenriques** [jaagr/polybar#340]
Is there a way to make polybar stay always below other windows with dock = true ? I've tried a lot and can't get it to work.

**Comment by jaagr** [comment]
What wm?

**Comment by jonathashenriques** [comment]
I'm using i3-gaps. Sorry!

**Comment by jaagr** [comment]
Works fine for me using:

~~~ dosini
[bar/top]
override-redirect = true
wm-restack = i3
~~~

**Comment by jonathashenriques** [comment]
Now it's working flawless ! Thank you so much !

**Comment by hldincher** [comment]
Still it doesnt work on me, i'm also using i3-gaps

**Comment by patrick96** [comment]
@hldincher This issue was opened when polybar was still on version 2.5.2. If you are still experiencing this, please open a new issue where you describe exactly what is happening vs. what you expect should be happening. Also provide some information about your setup (polybar version, full config)
