### ISSUE TITLE
bspwm: select workspaces to list

### ISSUE THREAD

**Issue by Tmplt** [jaagr/polybar#341]
I want to have a bar on each of my monitors, but there doesn't seem to be a way to specify which desktop workspaces should be read from. Could this be implemented?

**Comment by jaagr** [comment]
It's already possible to only show workspaces on the same monitor, see the wiki page, 

~~~ dosini
; Only show workspaces defined on the same output as the bar
; Default: true
pin-workspaces = true
~~~

**Comment by Tmplt** [comment]
I noticed that, but if I spawn two example-bars the bspwm part on both bars shows workspace info about the first monitor, instead of the second bar showing info about the workspaces on the second monitor.

**Comment by jaagr** [comment]
It uses the bars `monitor` parameter to determine what to show.

**Comment by jaagr** [comment]
Also make sure that your bspwm workspaces are named after the xrandr output/monitor.

**Comment by Tmplt** [comment]
Ah, that makes sense. I simply enumerated the monitors before. Cheers!
