### ISSUE TITLE
Filesystem module: Percentage free always reports zero

### ISSUE THREAD

**Issue by taylorthurlow** [jaagr/polybar#343]
It's properly detecting whether or not they are mounted (bogus entries report not mounted). However, for every mount point that DOES work, it's percentage free is always reported as 0.

Here's my config for the module:

    [module/filesystem]
    type = internal/fs
    interval = 25
    
    mount-0 = /
    
    label-mounted = %mountpoint%: %percentage_free%%
    format-mounted-underline = #b5bd68
    
    label-unmounted = %mountpoint%: not mounted
    label-unmounted-foreground = ${colors.foreground-alt}

I tried looking through the source but it doesn't look like a simple function call. I'm not getting any errors with `--log=info`.

	~> polybar -vv
	polybar 2.5.2

	Features: +alsa +curl +i3 -mpd +network

	X extensions: +xrandr (+monitors) -xrender -xdamage -xsync -xcomposite +xkb

	Build type: RelWithDebInfo
	Compiler: /usr/bin/c++
	Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors
	Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro

	ALSA_SOUNDCARD              default
	BSPWM_SOCKET_PATH           /tmp/bspwm_0_0-socket
	BSPWM_STATUS_PREFIX         W
	BUILDER_SPACE_TOKEN         %__
	CONNECTION_TEST_IP          8.8.8.8
	PATH_ADAPTER                /sys/class/power_supply/%adapter%
	PATH_BACKLIGHT_MAX          /sys/class/backlight/%card%/max_brightness
	PATH_BACKLIGHT_VAL          /sys/class/backlight/%card%/brightness
	PATH_BATTERY                /sys/class/power_supply/%battery%
	PATH_CPU_INFO               /proc/stat
	PATH_MEMORY_INFO            /proc/meminfo
	PATH_TEMPERATURE_INFO       /sys/class/thermal/thermal_zone%zone%/temp

**Comment by asyncial** [comment]
Same issue here with similar config.

**Comment by jaagr** [comment]
Always used `%percentage_used%` when testing the module, so it's been slipping by unnnoticed. Will fix it.

**Comment by taylorthurlow** [comment]
Hah, I didn't realize I had been using `percentage_free`. It does make more sense to do it the other way around doesn't it. I'll hold out until this gets pushed out onto the AUR and I'll report back.

**Comment by jaagr** [comment]
It's available if you install the git package `polybar-git`
