### ISSUE TITLE
Volume module doesn't react after headphones plugging in/out

### ISSUE THREAD

**Issue by khoacao96** [jaagr/polybar#347]
I'm having a little issue with the volume module

Before the headphones plug in, volume changes are still reflected on the module. But after the plug, the module doesn't react to the changes at all: the volume number doesn't increase, the bar doesn't move,etc.. Reloading the bar seems to fix the problem, but after the headphones unplugged, the module doesn't react again.

I also read on the wiki about the volume module config, which involves `headphone` and `headphone-id`, but I can't seem to get it work.

I'm new to GitHub, so I hope I can learn more from you guys. Thank you.

**Comment by jaagr** [comment]
Can you post the output of:

~~~ sh
$ amixer scontrols
$ amixer controls
~~~

**Comment by khoacao96** [comment]
Here:

`amixer scontrols`:

```
Simple mixer control 'Master',0
Simple mixer control 'Capture',0
```

`amixer controls`:

```
numid=4,iface=MIXER,name='Master Playback Switch'
numid=3,iface=MIXER,name='Master Playback Volume'
numid=2,iface=MIXER,name='Capture Switch'
numid=1,iface=MIXER,name='Capture Volume'
```

**Comment by jaagr** [comment]
You doesn't seem to have any handlers for the headphone jack, which means the headphone specific parts of the module won't work. Try removing the headphone parts from the config and see if it works.

**Comment by khoacao96** [comment]
Just removed all the headphone-related lines but the module still doesn't react after headphone plug/unplug. This is my current volume module:

```
[module/volume]
type = internal/volume

format-volume = <label-volume><bar-volume>

label-volume =
label-volume-foreground = ${root.foreground}

label-muted =  sound muted
label-muted-foreground = #55

bar-volume-width = 20
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = │
bar-volume-indicator-font = 2
bar-volume-indicator-foreground = #ff
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = #55
```

**Comment by jaagr** [comment]
Do you get any error/warning messages?

**Comment by khoacao96** [comment]
Are there any particular debugging steps? If the error appears right on-screen then I think I don't see any. It's like the module can't detect the headphone events because there's no seperate handlers for it. Increasing the volume for `Master` should have increase the headphone volume anyway, but apparently the module doesn't think so.

**Comment by jaagr** [comment]
The messages are printed to stderr, so you should see them in your terminal.

**Comment by khoacao96** [comment]
I pipe the messages to `error.log` here by running another instance of the bar:

```
polybar|warn:  No monitor specified, using "eDP-1"
polybar|warn:  The config parameter `bar/example.dock` is deprecated, use `bar/example.override-redirect` instead.
polybar|warn:  The config parameter `bar/example.border-bottom` is deprecated, use `bar/example.border-bottom-size` instead.
polybar|error: Disabling module "battery" (reason: No suitable way to get current capacity value)
polybar|warn:  Systray selection already managed (window=0x1400010)
polybar|warn:  Termination signal received, shutting down...
```

It seems like there's nothing related to the volume module.

**Comment by jaagr** [comment]
Could you run `$ alsactl monitor` and alter the volume with/without the headphones to see what events you get

**Comment by khoacao96** [comment]
Here:

`alsactl monitor` without headphones (increase volume then decrease):

```
card 1, #22 (2,0,0,Master Playback Volume,0) VALUE
card 1, #1 (2,0,0,Speaker Playback Volume,0) VALUE
card 1, #3 (2,0,0,Bass Speaker Playback Volume,0) VALUE
card 1, #1 (2,0,0,Speaker Playback Volume,0) VALUE
card 1, #3 (2,0,0,Bass Speaker Playback Volume,0) VALUE
card 1, #35 (2,0,0,PCM Playback Volume,0) VALUE
card 1, #1 (2,0,0,Speaker Playback Volume,0) VALUE
card 1, #35 (2,0,0,PCM Playback Volume,0) VALUE
card 1, #1 (2,0,0,Speaker Playback Volume,0) VALUE
card 1, #35 (2,0,0,PCM Playback Volume,0) VALUE
card 1, #22 (2,0,0,Master Playback Volume,0) VALUE
card 1, #1 (2,0,0,Speaker Playback Volume,0) VALUE
```

`alsactl monitor` with headphones (increase volume then decrease):

```
card 1, #22 (2,0,0,Master Playback Volume,0) VALUE
card 1, #5 (2,0,0,Headphone Playback Volume,0) VALUE
card 1, #35 (2,0,0,PCM Playback Volume,0) VALUE
card 1, #5 (2,0,0,Headphone Playback Volume,0) VALUE
card 1, #35 (2,0,0,PCM Playback Volume,0) VALUE
card 1, #5 (2,0,0,Headphone Playback Volume,0) VALUE
card 1, #35 (2,0,0,PCM Playback Volume,0) VALUE
card 1, #22 (2,0,0,Master Playback Volume,0) VALUE
card 1, #5 (2,0,0,Headphone Playback Volume,0) VALUE
card 1, #35 (2,0,0,PCM Playback Volume,0) VALUE
```

**Comment by jaagr** [comment]
And when you remove the headphones, do you get the same events as before? Check the id (`card 1, #<id>`)

**Comment by khoacao96** [comment]
Yes all id's are the same after plug/unplug.

**Comment by jaagr** [comment]
Do you have the script `alsa-info.sh` ? If so, please post the generated log created by running it.

**Comment by khoacao96** [comment]
Here's the log after running `alsa-info.sh`
[alsa-info.txt](https://github.com/jaagr/polybar/files/711431/alsa-info.txt)

**Comment by khoacao96** [comment]
@jaagr Just wanna update on the situation. I was able to create a custom module that reacts perfectly to the headphone events by combining with the `volume` script of i3blocks. The custom module & i3blocks' `volume` script is attached below:

```
[module/customvol]
type = custom/script
exec = ~/.config/i3blocks/volume 5 pulse
label = %output%
tail = true
interval = 0
```

~/.config/i3blocks/volume:

```

#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

# The second parameter overrides the mixer selection
# For PulseAudio users, use "pulse"
# For Jack/Jack2 users, use "jackplug"
# For ALSA users, you may use "default" for your primary card
# or you may use hw:# where # is the number of the card desired
MIXER="default"
[ -n "$(lsmod | grep pulse)" ] && MIXER="pulse"
[ -n "$(lsmod | grep jack)" ] && MIXER="jackplug"
MIXER="${2:-$MIXER}"

# The instance option sets the control to report and configure
# This defaults to the first control of your selected mixer
# For a list of the available, use `amixer -D $Your_Mixer scontrols`
SCONTROL="${BLOCK_INSTANCE:-$(amixer -D $MIXER scontrols |
                  sed -n "s/Simple mixer control '\([A-Za-z ]*\)',0/\1/p" |
                  head -n1
                )}"

# The first parameter sets the step to change the volume by (and units to display)
# This may be in in % or dB (eg. 5% or 3dB)
STEP="${1:-5%}"

#------------------------------------------------------------------------

capability() { # Return "Capture" if the device is a capture device
  amixer -D $MIXER get $SCONTROL |
    sed -n "s/  Capabilities:.*cvolume.*/Capture/p"
}

volume() {
  amixer -D $MIXER get $SCONTROL $(capability)
}

format() {
  perl_filter='if (/.*\[(\d+%)\] (\[(-?\d+.\d+dB)\] )?\[(on|off)\]/)'
  perl_filter+='{CORE::say $4 eq "off" ? "MUTE" : "'
  # If dB was selected, print that instead
  perl_filter+=$([[ $STEP = *dB ]] && echo '$3' || echo '$1')
  perl_filter+='"; exit}'
  perl -ne "$perl_filter"
}

#------------------------------------------------------------------------

case $BLOCK_BUTTON in
  1) pavucontrol ;;
  3) amixer -q sset Master toggle ;;  # right click, mute/unmute
  4) amixer -q sset Master 5%+ unmute ;; # scroll up, increase
  5) amixer -q sset Master 5%- unmute ;; # scroll down, decrease
esac

volume | format
```

Hope my information is useful to you.

**Comment by IzacCF** [comment]
Install the pavucontrol application and in your settings, select the exit option for the phones.

**Comment by khoacao96** [comment]
@IzacCF I can't find any exit option in the pavucontrol app. Can you be more specific?

**Comment by IzacCF** [comment]
In the "output devices" tab, do you have this option?

Here it is in Portuguese, it is unnecessary to send an application print.

**Comment by khoacao96** [comment]
There are only "Mute audio", "Lock channels together" and "Set as fallback" with the Advanced option being "Latency offset".

**Comment by IzacCF** [comment]
It's that?

https://community.linuxmint.com/img/screenshots/pavucontrol.png

Does your application have the "Output devices" tab?

**Comment by khoacao96** [comment]
Yes I do have the "Output Devices" tab in pavucontrol:

![2017-01-30-224903_1920x1080_scrot](https://cloud.githubusercontent.com/assets/17137267/22429840/a061406e-e73e-11e6-9013-b3d9e48f89e9.png)

Pretty sure I installed the correct application: [Link](https://www.archlinux.org/packages/extra/x86_64/pavucontrol/)
OS: Arch Linux 4.9.6-1 x64

**Comment by IzacCF** [comment]
If the headset works, but polybar can not control, I think there is an incompatibility.

And I apologize for my English.

**Comment by khoacao96** [comment]
Fixed. A reinstallation of the whole system fixed the issue.
...Nah, actually this is what I did on the new system (that I haven't done on the old):
Change the value of `defaults.ctl.card` and `defaults.pcm.card` from `0` to `1` then reboot. This makes `amixer scontrols` to output much more details:

```
Simple mixer control 'Master',0
Simple mixer control 'Headphone',0
Simple mixer control 'Speaker',0
Simple mixer control 'PCM',0
Simple mixer control 'Mic',0
Simple mixer control 'Mic Boost',0
Simple mixer control 'IEC958',0
Simple mixer control 'IEC958 Default PCM',0
Simple mixer control 'Capture',0
Simple mixer control 'Auto-Mute Mode',0
Simple mixer control 'Internal Mic',0
Simple mixer control 'Internal Mic Boost',0
Simple mixer control 'Loopback Mixing',0
```

And the volume module reacts to the headphone plugs again.
