### ISSUE TITLE
How to get sample config

### ISSUE THREAD

**Issue by sysads** [jaagr/polybar#348]
Hi

I recently installed the app on my Ubuntu 16.04 and install was OK. now I have no idea what the sample file should look like or what extension.

Anyone help show me how to download a sample file and install it?

I tried this commend from the doc but it complained about no config file.

$ install -Dm644 /usr/share/doc/polybar/config $HOME/.config/polybar/config 

Thanks

**Comment by alekcacko** [comment]
Hello. Polybar has a decent stock config file and it is zipped in directory /usr/share/doc/polybar/config.gz

So find that file and uncompress it where you wish(example to .config/polybar/config)

**Comment by sysads** [comment]
Hi and thansk for reply. I tried your suggestion by running following command:

$ sudo gzip -d /usr/share/doc/polybar/config.gz .config/polybar/config

but getting following error:

> gzip: .config/polybar/config.gz: No such file or directory

I checked but noticed that this path does not exist "**.config/polybar/config**"

**Comment by jaagr** [comment]
You can ensure it exists by running:

~~~ sh
$ mkdir -p ~/.config/polybar
~~~

**Comment by sysads** [comment]
OK guys I think I get it now. There was no config.gz file but just config file. I edited the file and noticed it was the config itself. So I created a new directory as suggested by @jaagr and coped the config file to the folder. Then I ran this command to start it but getting error:

command:
polybar ~/.config/polybar/config

Error:
Undefined bar

**Comment by jaagr** [comment]
See `polybar -h`

You don't need to specify config if it's the default one. Just run `polybar example`

**Comment by sysads** [comment]
sorry yes I just added example - Thanks
