### ISSUE TITLE
use shell env var in exec for custom/script module

### ISSUE THREAD

**Issue by eoli3n** [jaagr/polybar#350]
I added a module to check some information on a ssh srv.
polybar, even launched by my shell, seems not using its env vars.
To use my ssh cmd without passphrase, i did ssh-add, and then a var in zshrc target the socket file as
```
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
```
Normally, if that var is correctly set in zsh upprocess, every ssh goes without asking passphrase.

When i start polybar with this module, it asks me for passphrase with ``x11-ask-pass`` tool.
```
[module/neon-backupcheck]
type = custom/script
interval = 1200
format = <label>
label = "%output:0:100%"
format-prefix = " neon:dev/sdb "
format-prefix-foreground = #5b
exec = ssh root@neon df -h | grep /mnt/sdb | awk '{ print $5 }'
```

The module should not asks for the passphrase which already is in ssh-agent (``ssh-add -l``)
I think the module doesn't read the ``SSH_AUTH_SOCK``, maybe that's why it fails

I know how to get env values with ``${env:var}`` but how to tell to export it in ``exec``

I tried 

```
exec = export SSH_AUTH_SOCK=${env:SSH_AUTH_SOCK} ; ssh root@neon df -h | grep /mnt/sdb | awk '{ print $5 }'
```

In the module area in polybar i get 

![sdb](http://ptpb.pw/E-Do.png)

**Comment by eoli3n** [comment]
seems having same trouble with github module

```
[module/github]
type = internal/github
token = ${env:GITHUB_TOKEN}
```

If i let i3 starts polybar, github module doesn't work.
If i manually launch my polybar top, it works.

![img](http://ptpb.pw/Trtg.png)

**Comment by jaagr** [comment]
I don't think this issue is related to polybar. Make sure all your environment variables are set and available before launching polybar.

The `${env:NAME}` does not get replaced if part of a string.

**Comment by eoli3n** [comment]
you're right for github, var was badly set in tty's zsh. The second problem is at work, i will investigate more later. Thx

**Comment by eoli3n** [comment]
I confirm that $SSH_AUTH_SOCK is correctly set.

In tty1, ssh-add ssh root@srv works. Then startx, i3 launch polybar,  polybar ssh@srv, then it asks for adding passphrase to ssh agent... I tried to verify that the var is set by
```
exec = echo ${env:SSH_AUTH_SOCK}
```
but as you said, we can't resolv env vars inside a string.

**Comment by jaagr** [comment]
You can just use them with exec normally:

~~~ dosini
exec = echo $SSH_AUTH_SOCK
~~~

**Comment by eoli3n** [comment]
it was just a ``eval $(ssh-agent)`` doin shit in my xinitrc...
