### ISSUE TITLE
Workspace problems with multiple monitors

### ISSUE THREAD

**Issue by heems** [jaagr/polybar#352]
I currently have two monitors, each with a bar, that I launch using:

polybar config
```
[bar/main]
monitor = ${env:MONITOR}
...
```
launch.sh
```
MONITOR=eDP1 polybar main &
MONITOR=HDMI1 polybar main &
```

my bspwmrc monitor code is:
```
bspc monitor eDP1 -d I II III IV
bspc monitor HDMI1 -d V VI VII VIII IX
```

With bspwm + lemonbar, I have multiple workspaces on each screen, but in polybar I seem to have 7 workspaces on eDP1 and only one workspace on HDM1.  Workspace 1 seems to get assigned to HDMI1 and the rest are assigned to eDP1.  Everything else seems to be working great.  I can't figure out what the problem here is.

Thanks!

**Comment by jaagr** [comment]
Can you post the output of `bspc wm -g`

**Comment by heems** [comment]
Ah sorry, that command helped me realize the problem was with my bspwmrc file.  It's all good now.  Thank you!

**Comment by csterbenz** [comment]
I am having a similar issue. Can you explain what steps you took to solve this?
Thanks.
