### ISSUE TITLE
No built-in support for 'internal/network'

### ISSUE THREAD

**Issue by 9thScientist** [jaagr/polybar#354]
When I try to activate a module using internal/network it will give me the following error:
`error: Disabling module "wireless-network" (reason: No built-in support for 'internal/network')`.
module in question:
```
[module/wireless-network]
type = internal/network
interface = wlp3s0
interval = 3.0
```

I have wireless_tools instaled.

**Comment by jaagr** [comment]
`wireless_tools` needs to be installed when compiling polybar, so you probably just have to reubild it.

**Comment by 9thScientist** [comment]
That fix it, thank you.

**Comment by Maximilian73** [comment]
I have a problem. I use Gentoo. The package of Gentoo named wireless-tools instead wireless_tools. And I have (reason: No built-in support for 'internal/network')...

**Comment by patrick96** [comment]
@Maximilian73 polybar doesn't actually look for `wireless_tools` (or `wireless_tools` for that matter), it searches for `libiw.so` and `iwlib.h`, so make sure you have those files on your system and also that you built polybar after those files were installed.
