### ISSUE TITLE
Why does the systray behave so glitchy for me?

### ISSUE THREAD

**Issue by Icyphox** [jaagr/polybar#355]
![polybarissue](https://cloud.githubusercontent.com/assets/17672379/22073425/5336fbf2-ddcb-11e6-92cc-81e036e0fa73.png) 

This is what the Steam tray icon looks like for me. This happens for all my tray icons, DeadBeef, Banshee, etc. Could you please explain if I'm doing something wrong? All the systray settings are the default ones.

**Comment by jaagr** [comment]
Post your configuration. And what wm are you using?

**Comment by Icyphox** [comment]
Nevermind, found a fix for it. Apparently i3 doesn't allow the bar to have an `offset-y`, but it allows the systray to. I even enabled `override-redirect = true`, didn't work. So all I had to do was remove the margin.
