### ISSUE TITLE
Abort/Segfault on start

### ISSUE THREAD

**Issue by Mitame** [jaagr/polybar#356]
Aborting run: https://gist.github.com/Mitame/4ee8c7f7452e33af42c9bfb2e44cc37b
Segfaulting run: https://gist.github.com/Mitame/592f711b819676140469ae30420749bf
config: https://gist.github.com/Mitame/fd805c6df2d8a04ebe33a1d067dd1aee

Polybar fails to start consistently, either segfaulting or aborting. Don't believe I've changed anything to make this happen from when it was working. 

EDIT: The logs are from commit 9e3a7cf06c17175e649692908c957dfdc0a8fab7, though this is also present on the latest release (2.5.2 at time of writing).

**Comment by jaagr** [comment]
Hi, can you post the output of `xrdb -q`

**Comment by Mitame** [comment]
No output from `xrdb -q`

**Comment by Mitame** [comment]
-_- i'm a moron... let me edit config to remove those references

**Comment by Mitame** [comment]
OK, error was having xrdb references in the config without having xrdb configured with those properties. Could do with a clearer error though.

**Comment by jaagr** [comment]
It's supposed to default to an empty value.. I'll have a look

**Comment by Mitame** [comment]
I have the full coredump from `coredumpctl` if that's useful?

**Comment by jaagr** [comment]
Guess it's without debug symbols, but youmight as well add it

**Comment by Mitame** [comment]
Well, it's coredump from git with `-DCMAKE_RELEASE_TYPE=Debug` or whatever the correct one was. Linked anyway
[Abort dump](https://u.nya.is/jdryen.dump)
[Segfault dump](https://u.nya.is/objyoc.dump)

**Comment by jaagr** [comment]
Can't reproduce it.. will try a bit later on my arch machine.

**Comment by Mitame** [comment]
Can't really say exactly how to reproduce it. I deleted my `.Xresources` file because its colours were messing up some other stuff and so when I logged back in, polybar never appeared and this error was occurring. Fixed it by putting it back and loading it back in with `xrdb .Xresources` but able to reproduce by removing the file and logging back in to remove the configurations from xrdb.

Also, running `polybar main --dump=PARAM` with the parameter as something from xrdb with a fall-back causes the error as well, though this always seems to abort rather than segfault.

**Comment by jaagr** [comment]
I think 374ad65 might fix it

**Comment by Mitame** [comment]
Doesn't appear to have fixed it... (output)[https://gist.github.com/Mitame/55bf7c4366be47bb19a7134bce8f6427]

**Comment by jaagr** [comment]
The manager wasn't cached, i.e.. it got initialized every time a config reference was parsed. The last fix oughta fix it.

**Comment by Mitame** [comment]
Does appear to have fixed it either. [output](https://gist.github.com/Mitame/3962bfcba31b786c8787b99220d9fb2d)

**Comment by Mitame** [comment]
FYI, if you want any of the coredumps for any of these, just say because I have all of them around on my HDD just need to upload them somewhere.

**Comment by Mitame** [comment]
After a while working out how `gdb` worked and screaming at code even though i'm at fault, this seemed to fix the crashes: https://github.com/Mitame/polybar/commit/e38143d5f9f0e9364b7e97ee8f79fd16964f07f0
