### ISSUE TITLE
Semi transparency for bar background

### ISSUE THREAD

**Issue by Jackojc** [jaagr/polybar#361]
I'm trying to set the bar to black with transparency of about 75% using this #000000cc. This just gives me full transparency. If I set it to #cccccccc, It gives me semi transparency but it's tinted white (obviously). I'm not sure if this a bug or if I'm doing something wrong but I can't find it mentioned anywhere else and this seems the best place to ask.

**Comment by Qu4tro** [comment]
It's #ARGB and not #RGBA.

In your case, the solution is setting the color to #cc000000.

**Comment by Jackojc** [comment]
Yeah I actually figured it out this morning, Is there any particular reason for ARGB rather than RGBA? I would've thought RGBA was much more standard.

**Comment by Qu4tro** [comment]
I'm guessing it's your compositor. You need to add a rule to compton (or your compositor of choice) to exclude polybar.

**Comment by Nano-Sec** [comment]
Yeah there was a net wm sticky opacity rule i missed out. It's all good now.

**Comment by Lite5h4dow** [comment]
i have the opposite problem, every time i add a alpha value poly bar is replaced with a black background...

**Comment by patrick96** [comment]
@Lite5h4dow do you have a compositor running?
