### ISSUE TITLE
exec-if resulting in output Exit with failed status 1

### ISSUE THREAD

**Issue by crgnclsn** [jaagr/polybar#362]
Hello, love the software!

Currently running a custom Spotify now playing script but I am using an exec-if flag to determine whether or not to run the script. However, Polybar is outputting "warn: command: Exited with failed status 1" every time the exec-if command is run. Is this the intended behaviour? It is making very large log files as I am running the command once per second.

I am using exec-if = pgrep -x spotify

Cheers,
Craig

**Comment by jaagr** [comment]
Hi and thank you.

This was originally intended but it doesn't make any sense to log it as a warning when it's an expected behaviour. I will patch it.

**Comment by crgnclsn** [comment]
Working beautifully! Thank you.
