### ISSUE TITLE
Noto Emoji not displaying?

### ISSUE THREAD

**Issue by sphaugh** [jaagr/polybar#363]
I followed the steps to use Noto Emoji as the font for my workspace icons, but they are still not appearing. How can I fix this or figure out what's going wrong? Thanks.

**Comment by jaagr** [comment]
What steps did you follow?

**Comment by skystrife** [comment]
I can replicate this issue. It occurs for me when I attempt to use the following emoji: 🔇 (U+1F507). I've traced the problem down to parsing the configuration file.

Specifically, `parser::text()` refuses to emit any character that is larger than the size of a `uint16_t`. This emoji lies outside of that, so it instead writes `0xfffd` (the replacement character).

Why is `write_text_unicode` a `value_signal<write_text_unicode, uint16_t>`? I feel like you actually need the full `uint32_t` here to support all possible UTF codepoints, right?

**Comment by jaagr** [comment]
@skystrife 4-byte sequences aren't supported (goes beyond the sized integral type).. I'm almost done with the new implementation though, available on the `refactor-cairo` branch

**Comment by jaagr** [comment]
I've pushed the changes to the master branch, so please try it out.

**Comment by skystrife** [comment]
Yes, that seems to fix the issue.

Is it expected, though, that the new renderer makes fonts smaller than they were before? Using the same font settings, for example, produces

![font-sizes](https://cloud.githubusercontent.com/assets/1378336/22263062/c4e9a04e-e238-11e6-88e8-ee64ab091999.png)

Where the top one is the master branch and the bottom one is v2.5.2. (I can create a separate issue for this if you'd like, though, since the emoji now render properly for me.)

**Comment by jaagr** [comment]
No it's not intended but there's currently no scaling of point sizes. Will look into it.

**Comment by jaagr** [comment]
Could you post the output of 

~~~
$ xrdb -q | grep Xft
~~~

**Comment by skystrife** [comment]
No output (empty). This is all that's there:

```
$ xrdb -q
rofi.color-active:	#191a16, #ffb52a, #21211b, #33332b, #ffb52a
rofi.color-enabled:	true
rofi.color-normal:	#191a16, #dbdbd5, #21211b, #33332b, #dbdbd5
rofi.color-urgent:	#191a16, #f9266a, #21211b, #33332b, #f9266a
rofi.color-window:	#191a16, #002b37, #33332b
rofi.font:	Meslo LG M DZ 12
rofi.separator-style:	solid
```

**Comment by jaagr** [comment]
What about 

~~~
$ xdpyinfo | grep -B2 resolution
~~~

**Comment by skystrife** [comment]
```
$ xdpyinfo | grep -B2 resolution
screen #0:
  dimensions:    3120x1920 pixels (852x513 millimeters)
  resolution:    93x95 dots per inch
```

(I have two monitors, one rotated left.)

```
$ xrandr
$ xrandr
Screen 0: minimum 8 x 8, current 3120 x 1920, maximum 16384 x 16384
DVI-I-0 disconnected (normal left inverted right x axis y axis)
DVI-I-1 disconnected (normal left inverted right x axis y axis)
DVI-I-2 connected primary 1920x1200+0+0 (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1200     59.95*+
   1600x1200     60.00  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    72.81    59.94  
HDMI-0 disconnected (normal left inverted right x axis y axis)
DVI-I-3 connected 1200x1920+1920+0 left (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1200     59.95*+
   1920x1080     60.00  
   1680x1050     59.95  
   1600x1200     60.00  
   1280x1024     60.02  
   1280x960      60.00  
   1024x768      60.00  
   800x600       60.32  
   640x480       59.94  
```

**Comment by skystrife** [comment]
I think I see how to fix this... working on a patch.
