### ISSUE TITLE
Temperature module format-warn doesn't support <label> and low temperature

### ISSUE THREAD

**Issue by Calvein** [jaagr/polybar#364]
First off I'd like to thank you for polybar, that's an awesome peace of software and I'm really happy with it.

After making my shitty custom temperature module, I noticed that an internal one existed already, so I simply copy paste the [wiki section](https://github.com/jaagr/polybar/wiki/Module:-temperature) and I get this error:

```
error: Disabling module "temperature" (reason: <label> is not a valid format tag for "format-warn")
```

No big deal, I remove it and now it's working, the problem now is that it's showing only 20°C but when I run `sensors`, my CPU is at 64°C atm.
So I checked what the wiki says and I tried all the different thermal-zone and they're all at 20°C (except the last one that doesn't show anything).

stdout of `for i in /sys/class/thermal/thermal_zone*; do echo "$i: $(<$i/type)"; done
`:

```
/sys/class/thermal/thermal_zone0: INT3400 Thermal
/sys/class/thermal/thermal_zone1: TMEM
/sys/class/thermal/thermal_zone2: TSKN
/sys/class/thermal/thermal_zone3: TAMB
/sys/class/thermal/thermal_zone4: T_VR
/sys/class/thermal/thermal_zone5: TEFN
/sys/class/thermal/thermal_zone6: acpitz
/sys/class/thermal/thermal_zone7: x86_pkg_temp
```

stdout of `sensors`
```
coretemp-isa-0000
Adapter: ISA adapter
Physical id 0:  +62.0°C  (high = +87.0°C, crit = +105.0°C)
Core 0:         +62.0°C  (high = +87.0°C, crit = +105.0°C)
Core 1:         +58.0°C  (high = +87.0°C, crit = +105.0°C)

acpitz-virtual-0
Adapter: Virtual device
temp1:        +60.0°C  (crit = +108.0°C)

asus-isa-0000
Adapter: ISA adapter
cpu_fan:     3500 RPM
temp1:        +60.0°C  
```

**Comment by jaagr** [comment]
Hi and thanks for reporting the issue.

The example in the wiki was incorrect and I've fixed it.
