### ISSUE TITLE
mocp

### ISSUE THREAD

**Issue by IzacCF** [jaagr/polybar#366]
Hi!

Polybar is amazing!

Can there be support for the MOC player?

**Comment by jaagr** [comment]
Hi, and thanks.

I'm not familiar with the player but you can either write your own script module or submit a pull-request.

**Comment by IzacCF** [comment]
Hi, Michael.

I found a solution, just like Spotify does.

Look:

> [module/moc]`
> interval = 0.5
> type = custom/script
> exec = /home/zack/.i3/i3blocks/moc_title
> label = %output:0:100:...%
> format-prefix = "MOC     "
> label-close = "MOC   off"
> label-foreground = #0088CC
> format-underline = #2F343F
> format-foreground = ${colors.foreground}
> format-background = #2F343F

It works! :)

**Comment by jaagr** [comment]
Great! I'm closing this then

**Comment by DrDonkey** [comment]
@IzacCF I can't find the required script in my system i.e. `~/.i3/i3blocks/moc_title`.
