### ISSUE TITLE
ascii symbols do not appear on i3-workspace

### ISSUE THREAD

**Issue by oscarandrea** [jaagr/polybar#369]
I tried to insert these ASCII symbols but are not displayed as the name of the workspace 
config i3/polybar:
1)https://arin.ga/uN6HP5
2)https://arin.ga/2qgXVq

**Comment by BlackBeemo** [comment]
fc-list will give you a list of installed fonts
> fc-list | grep Siji
/usr/share/fonts/misc/siji.pcf: Wuncon Siji:style=Regular

Replace the font config from polybar with the proper name
> font-0 = Tamzen:pixelsize=12;0
> font-1 = FontAwesome:pixelsize=12;0
> font-2 = Wuncon Siji:pixelsize=12;0

Also check it you have those fonts installed, for arch it would be siji-git from AUR

**Comment by oscarandrea** [comment]
thanks for reply, I installed the fonts, but are not visible even from the text, is this normal?
http://imgur.com/zbz4efG

**Comment by BlackBeemo** [comment]
> thanks for reply, I installed the fonts, but are not visible even from the text, is this normal?
Maibe you still missing some fonts and check that you have the proper fonts loaded at wich ever program needs them.

**Comment by oscarandrea** [comment]
Now you see the symbols in the bar (wifi, battery, etc) but I would like to assign a symbol to each workspace, I tried but could not, explain to me how to do? thank you

**Comment by jaagr** [comment]
@oscarandrea, are you sure you are loading a font that can draw the symbols?

~~~ dosini
[bar/top]
font-0 = FontAwesome:pixelsize=14;0
~~~

~~~ dosini
[module/i3]
ws-icon-0 = term;
ws-icon-1 = web;
ws-icon-2 = media;
ws-icon-3 = code; 
ws-icon-4 = chat;
ws-icon-default =  
~~~

**Comment by oscarandrea** [comment]
@jaagr Now I installed the support beautiful font that you suggested, the editor vim you see the symbols on the workspace bar not seen, on the whole I i3 module inserted icon% do not know if it's okay, here's the entire setup:
https://paste.pound-python.org/show/YwCwyhIPxzYyzrNyGNjt/
 screenshot:
http://imgur.com/mQJRgSK
thanks

**Comment by jaagr** [comment]
Your font list is malformed. Replace it with this:

~~~ dosini
font-0 = fixed:pixelsize=10
font-1 = unifont:fontformat=truetype:size=6:heavy;-2
font-2 = siji:pixelsize=10
font-3 = FontAwesome:pixelsize=14;0
~~~

**Comment by oscarandrea** [comment]
@jaagr Now it is so, I do not understand why the correct workspace does not load the correct icon, the i3 is a config problem?
thank you
http://imgur.com/a/u2qhp

**Comment by jaagr** [comment]
No, it's because the labels doesn't match the i3 workspace names.

You can use this to create a list for the workspaces you have open:

~~~ sh
$ n=0; i3-msg -t get_workspaces | tr ',' '\n' | sed -nr 's/"name":"([^"]+)"/\1/p' | while read -r name; do echo "ws-icon-$((n++)) = \"${name};<insert-icon-here>\""; done
~~~

**Comment by oscarandrea** [comment]
@jaagr 
thanks,Now what do I do?
```
┌─[oscar@GentOscar] - [~] - [2017-01-26 06:33:29]
└─[0] <> n=0; i3-msg -t get_workspaces | tr ',' '\n' | sed -nr 's/"name":"([^"]+)"/\1/p' | while read -r name; do echo "ws-icon-$((n++)) = \"${name};<insert-icon-here>\""; done
ws-icon-0 = "1: term;<insert-icon-here>"
ws-icon-1 = "2: web;<insert-icon-here>"
ws-icon-2 = "3: media;<insert-icon-here>"
```

**Comment by jaagr** [comment]
Put it in your config

~~~ dosini
ws-icon-0 = 1: term;
ws-icon-1 = 2: web;
ws-icon-2 = 3: media;
~~~

**Comment by oscarandrea** [comment]
thank you! It works fine now!
before closing I make you one last question, if I want to enter in the future other icons from the pack fontawesome how should I do? just a copy paste right? from where I get the icons?
thank you

**Comment by jaagr** [comment]
You can copy/paste them from http://fontawesome.io/cheatsheet/

**Comment by oscarandrea** [comment]
thanks 👍
