### ISSUE TITLE
Inconsistent line-height

### ISSUE THREAD

**Issue by Calvein** [jaagr/polybar#372]
It looks like there is some issues with the line-height of some module, here some screenshots:

Hack:12
![image](https://cloud.githubusercontent.com/assets/243189/22262950/10441ae4-e273-11e6-9e5d-e44675255363.png)

Hack:12 with line at the top of each elements
![image](https://cloud.githubusercontent.com/assets/243189/22262978/275bba48-e273-11e6-9f91-1c814cf3b741.png)

---

Roboto:12
![image](https://cloud.githubusercontent.com/assets/243189/22263002/3c4206ba-e273-11e6-8359-e6f85e06b0d9.png)

Roboto:12 with line at the top of each elements
![image](https://cloud.githubusercontent.com/assets/243189/22263021/4e7183d8-e273-11e6-8518-b68cfb428cac.png)

Is there any workaround this issue or is this really just font related and has nothing to do with polybar ?

**Comment by taylorthurlow** [comment]
In your config, you can specify a vertical offset on a per-font basis. For example, in my config I have:

    font-0 = dina:pixelsize=10;0
    font-1 = unifont:size=6:heavy:fontformat=truetype;-2
    font-2 = wunconsiji:pixelsize=10;0

The `;-2` on the end of the definition for `font-1` specifies the pixel offset. Not necessarily an answer to your question but should be good enough for a workaround.

**Comment by Calvein** [comment]
Cheers, that's a good workaround, I did this for now:

```
[bar/master]
font-0 = Hack:size=12
; 1px lower for up/down
font-1 = Hack:size=12;1
; 2px lower for datetime
font-2 = Hack:size=12;2

[module/up-speed]
label-connected = %{T2}%upspeed:9%%{T-}

[module/time]
label = %{T3}%date% %time%%{T-}
```

**Comment by jaagr** [comment]
What version are you using?

**Comment by Calvein** [comment]
```
calvein @ ~[]
polybar -v
polybar 3.0.0-alpha

Features: +alsa +curl +i3 +mpd +network
```

**Comment by skystrife** [comment]
Similar problem here on master branch as well, but one where the offset workaround won't work since it's inconsistent within the same widget (mpd in my case):


![line-height-1](https://cloud.githubusercontent.com/assets/1378336/22266358/53e16b2c-e245-11e6-8bab-0d6243a56187.png)
![line-height-2](https://cloud.githubusercontent.com/assets/1378336/22266359/53e3d790-e245-11e6-99c2-5165876b3343.png)

Notice how the second song title is much higher than the first.

This is with only one font configured:

```ini
font-0 = Noto Sans:style=Regular:size=12
```

**Comment by skystrife** [comment]
The referenced commit solves the issue I was having. 👍
