### ISSUE TITLE
Workspace background misalignment

### ISSUE THREAD

**Issue by imr0** [jaagr/polybar#379]
Hi!

Since version 3.0 I suddenly started to see a weird misalignment issue with the background of the current i3 workspace indicator. The issue only exists if the bar has a border (in my case, I have a 14 px transparent border, and the misalignment seems to be exactly 14 pixels).

Here is a screenshot of the bar:
![screenshot](https://cloud.githubusercontent.com/assets/25355941/22312759/896aeaf6-e359-11e6-9f96-e036a567c7c9.jpg)

You can see how the the background (and the visible part) is misaligned, though the overline is displayed correctly.

**Comment by jaagr** [comment]
Could you update your version and see if the problem persists? Think I've fixed it.

**Comment by imr0** [comment]
Yes, thank you, the problem is gone!
