### ISSUE TITLE
libxcb-xrm-dev missing from dependencies list

### ISSUE THREAD

**Issue by rmhsilva** [jaagr/polybar#381]
Please add `libxcb-xrm-dev` to the list of dependencies on the wiki as it appears to be required for the standard build.

Thanks :)

**Comment by jaagr** [comment]
The wiki is editable by everyone for this exact reason :-)

It's not a required dependency by the way. Did it fail to build because it was missing?

**Comment by jaagr** [comment]
The referenced commit fixes a bug with setting the default value for `WITH_XRM`

**Comment by rmhsilva** [comment]
Aha, yep it was failing to build with the default options. Thanks!
