### ISSUE TITLE
polybar ignores tray-detached = true

### ISSUE THREAD

**Issue by artemisclyde** [jaagr/polybar#383]
I set tray-detached = true to prevent polybar from shifting its elements as stated in the wiki
```
; If true, the bar will not shift its
; contents when the tray changes
tray-detached = false
```
After the latest update, this doesn't work anymore as polybar shifts its elements regardless of this setting.

**Comment by jaagr** [comment]
Thanks for reporting it. Will fix the issue.

**Comment by artemisclyde** [comment]
Works again after update. Thanks a lot!
