### ISSUE TITLE
Gentoo build

### ISSUE THREAD

**Issue by bpinto** [jaagr/polybar#385]
Hey, first of all, thanks for the great tool! It's super well maintained!

We have been maintaining a gentoo build for [polybar](https://github.com/Dr-Terrible/ineluctable-overlay/tree/master/x11-misc/polybar) and I wanted to double check that the dependencies are accurate:

```
rdepend="media-libs/fontconfig
	x11-libs/cairo
	x11-libs/libx11
	x11-libs/libxcb[xkb?]
	x11-libs/libxft
	x11-libs/xcb-util-image
	x11-libs/xcb-util-wm
	x11-libs/xcb-util-xrm
	x11-proto/xcb-proto
	alsa? ( media-libs/alsa-lib )
	curl? ( net-misc/curl )
	i3? (
		>=dev-libs/jsoncpp-1.8.0
		dev-libs/libsigc++:2
	)
	mpd? ( media-libs/libmpdclient )
	wifi? ( net-wireless/wireless-tools )"
depend="dev-libs/boost[threads]"
```

I have removed the dependency to `media-libs/freetype` and added a dependency to `x11-libs/cairo` and `xcb-util-rxm` updating from 2.x to 3.x.

Do these make sense? Thanks!

P.S.: I'm updating to latest 3.0.2 as we speak.

**Comment by jaagr** [comment]
I'm not familiar with Gentoo's build system, but you could probably clean it up a bit:

~~~ diff
-rdepend="media-libs/fontconfig
+rdepend="
	x11-libs/cairo
-	x11-libs/libx11
-	x11-libs/libxcb[xkb?]
-	x11-libs/libxft
	x11-libs/xcb-util-image
	x11-libs/xcb-util-wm
	x11-libs/xcb-util-xrm
-	x11-proto/xcb-proto
	alsa? ( media-libs/alsa-lib )
	curl? ( net-misc/curl )
	i3? (
		>=dev-libs/jsoncpp-1.8.0
-		dev-libs/libsigc++:2
	)
	mpd? ( media-libs/libmpdclient )
	wifi? ( net-wireless/wireless-tools )"
-depend="dev-libs/boost[threads]"
+depend="${rdepend}
+  >=x11-proto/xcb-proto-1.12-r2"
~~~

**Comment by bpinto** [comment]
I thought we needed `libisgc++`?

I was confused with `dev-libs/boost` but I found a reference to it [here](https://github.com/jaagr/polybar/blob/7dedcf6526b85218a1e6ad8c9206b9c6c3fb82b3/contrib/polybar.xbps/template).

What about `xcb-proto`? Does it include all the other libs?

**Comment by jaagr** [comment]
Both `libsigc++` and `boost` was used in previous versions. The xbps template is old, `version=2.3.0`

**Comment by bpinto** [comment]
@jaagr Thank you so much! I have only started to use polybar recently and I have been reading all your commits since then so I just wanted to make sure that the dependency list was still accurate! You rock!
