### ISSUE TITLE
Using Polybar with Ionicons?

### ISSUE THREAD

**Issue by kneeki** [jaagr/polybar#386]
Is it possible to use Polybar with [Ionicons](http://ionicons.com/)? I can't find a guide for this anywhere. Here's what I got so far:

```
[bar/bot]
# ...
font-0 = SourceCodePro:size=10;0
font-1 = FontAwesome:size=10;0
font-2 = Ionicons:size=10;0
```

**Comment by kneeki** [comment]
It looks like
```
[bar/bot]
# ...
font-2 = ionicons:size=10;0
```
Works, but some icons I'm pasting from the [cheatsheet](file:///home/dave/Downloads/ionicons-2.0.1/cheatsheet.html) do not reflect what they are supposed to be. For example, The `ion-battery-charging` actually pastes a bullet:  in gedit. This bullet is also what appears in Polybar.

**Comment by skystrife** [comment]
Try specifying the font t9 use for the icon directly: https://github.com/jaagr/polybar/wiki/Fonts

**Comment by jaagr** [comment]
Yeah, you can use the font as long as it is available to fontconfig.

![2017-01-27-040847_162x61_scrot](https://cloud.githubusercontent.com/assets/3697186/22359321/71ff4a36-e446-11e6-9ac5-d7bc18bf7292.png)

**Comment by jaagr** [comment]
Yeah, the unicode character is most likely caught by a previous font in the fontlist. As @skystrife said, you would have to explicitly specify what font to use.

~~~ dosini
label-font = <font-index>
# or
label = %{T<font-index>}...%{T-}
~~~

**Comment by kneeki** [comment]
Perfect! Thank you!
