### ISSUE TITLE
dpi changed after upgrade

### ISSUE THREAD

**Issue by eoli3n** [jaagr/polybar#388]
now is like
![alt](https://ptpb.pw/Uy_O.png)

Should look like 
![alt](https://ptpb.pw/npmo.png)

```
font-0 = hack:pixelsize=12;1
font-1 = unifont:size=6:heavy:fontformat=truetype;-2
font-2 = siji:pixelsize=10;0
font-3 = FontAwesome:pixelsize=14;0
```

Did you change anything about DPI ?

**Comment by eoli3n** [comment]
Issue not present in that commit (before all dpi changes)
https://github.com/jaagr/polybar/commit/8d79b582ec3cf44c9dacbc319c47e0b94191b3ea

(but compositing seems broken)
![alt](https://ptpb.pw/j0kc.png)

**Comment by skystrife** [comment]
What's the actual DPI of your screen? Try running

```
xdpyinfo | grep -B2 resolution
```

You can configure the DPI in the bar configuration with

```
dpi = <integer>
```

The default is currently 96 without anything in the configuration file, which made things identical before and after the DPI scaling commits on my systems, but perhaps your screen isn't actually 96. You can try to use automatic detection using

```
dpi = -1
```

which should work provided `xdpyinfo` actually gives you correct measurements of your screen size, or just manually set it to a value that replicates what you had before (maybe try 72?).

**Comment by bardisty** [comment]
> The default is currently 96 without anything in the configuration file, which made things identical before and after the DPI scaling commits on my systems, but perhaps your screen isn't actually 96.

You might be on to something. My screen's DPI is 107 and fonts were much larger after the DPI commits. I had to adjust the `dpi` option to 76 to get them back down to the desired size.

> (but compositing seems broken)

If you're talking about your bottom bar not rendering fully, that should be fixed in 3.0.3.

**Comment by eoli3n** [comment]
My dpi was ``96x96`` **before** and **after** update, i didn't change anything about that.
But as said in my first post. Revert to https://github.com/jaagr/polybar/commit/8d79b582ec3cf44c9dacbc319c47e0b94191b3ea commit change the dpi of the bar without changing anything else.

Second problem is my font rendering, as you can see in my screenshots, the rendering of ``----|--`` bars ( backlight and volume ) changed. Now we see some space between ``-``

**Comment by eoli3n** [comment]
Changing the dpi in the bar configuration as said by @skystrife doesn't work.
Tried values ``-1`` ``-2`` ``-3`` ``-10`` ``-100`` without any changes.

**Comment by skystrife** [comment]
> My dpi was 96x96 before and after update, i didn't change anything about that.
But as said in my second post, revert to 8d79b58 commit change the dpi of the bar without changing anything else.

So before 3.0.0-alpha, the renderer was using Xft for the fonts. This was DPI-aware provided `Xft.dpi` was set in your `.Xresources` file. If no DPI was set, it defaulted to 96 DPI.

As of 3.0.0-alpha, the renderer was switched to Cairo. But before e7dc6b8bbbc94eb7d273a2e7730f445410a41214, this renderer did *not* attempt to do any DPI scaling at all. So if you had configured your fonts using v2.5.x and got them the size you wanted, when you upgraded to 3.0.0-alpha they were (likely) smaller than they were before. This was the case for me.

If, however, you configured your fonts the way you like in the period of time between the Cairo merge and my commit that added DPI scaling to the Cairo renderer (in other words, during the period that the Cairo renderer was making fonts too small), your fonts will likely display larger now. This is on purpose. Just set the DPI to something smaller like 72, or adjust your font size to compensate.

**Comment by skystrife** [comment]
> Changing the dpi in the bar configuration as said by @skystrife doesn't work.
Tried values -1 -2 -3 -10 -100 without any changes.

All negative values are going to be treated the same, so I'm not sure what you were expecting here.

I *think* the issue is not that the DPI is being calculated incorrectly. Rather, I think you set up your fonts in the period of time between when the new Cairo renderer was merged and when it became DPI-aware. In that small period of time, the "effective" DPI would have been 72. Try that value.

```
dpi = 72
```

**Comment by eoli3n** [comment]
Tried with ``dpi = 72``
This is how it render
![alt](https://ptpb.pw/7oy3.png)

Everything is top aligned... looks bad, please see 
![alt](https://ptpb.pw/npmo.png)

how to get it back to that

**Comment by skystrife** [comment]
Adjust your vertical offsets (the thing after the semicolon in your font definitions).

```ini
font-N = <fontconfig pattern>;<vertical offset>
```

Try larger/smaller numbers until things are where you want.

**Comment by eoli3n** [comment]
Cool, didn't know what was those values, did the trick.

Last thing is 

![alt](https://ptpb.pw/F10y.png)

**Comment by skystrife** [comment]
> Cool, didn't know what was those values, did the trick.

Great! Hopefully this won't need to be modified again in the future. Little changes like this were inevitable, though, with the renderer rewrite.

> Last thing is that there is some space between -

Have you already tried disabling antialiasing? See the last section on this page: https://github.com/jaagr/polybar/wiki/Fonts#anti-aliasing

**Comment by eoli3n** [comment]
I removed ``:heavy``, solved it. thx for helping
