### ISSUE TITLE
compton messes up panel in version 3.0.2

### ISSUE THREAD

**Issue by Vintodrimmer** [jaagr/polybar#389]
Good day. I have updated from version 2.5.something to the 3.0.2 and now my panel looks like this:

![compton with polybar](https://raw.githubusercontent.com/Vintodrimmer/docs/master/2017-01-28-12%3A18%3A22-screenshot.png)

If I turn compton off, it will look as it is supposed to, except parts that were transparent are now black.

![compton disabled](https://raw.githubusercontent.com/Vintodrimmer/docs/master/2017-01-28-12%3A23%3A18-screenshot.png)

I did not change compton or polybar configs in any way. If you need them, here they are:

[compton.conf](https://paste.pound-python.org/show/CGiejn1m1KHrKsR7fzkL/)

[new polybar config](https://paste.pound-python.org/show/t6Q6HRsw9VebivnHwUOo/) rewrote it to be easier to read and to look as intended. The problem still persists

Actually, it's not even compton. The problem exist even without it (black parts.)

**Comment by jaagr** [comment]
Hi, please update to `3.0.3`, this issue was fixed recently.

**Comment by Vintodrimmer** [comment]
Thanks. Guess I'll go bug guys from ineluctable overlay.
