### ISSUE TITLE
border-top-size issue

### ISSUE THREAD

**Issue by plastilint** [jaagr/polybar#390]
This is driving me nuts :scream: 

![21 12 01-shot](https://cloud.githubusercontent.com/assets/16851615/22398294/e8ab7b10-e59e-11e6-9dfd-1ae7c70b5466.png)

![21-13-07-shot_resized](https://cloud.githubusercontent.com/assets/16851615/22398301/02669b3e-e59f-11e6-8cc7-cc0e8e0613b5.png)

---------

That's how it looked like on 2.x.x :

![21 18 05-shot](https://cloud.githubusercontent.com/assets/16851615/22398328/626a85a4-e59f-11e6-8b1c-d1869020e426.png)

---------
[Config](http://pastebin.com/UBqsyadj)

**Comment by skystrife** [comment]
(For those of you like me who had to look a whole bunch of times before noticing what the problem is, notice how the border extension is a single pixel short.)

I assume you're running the latest v3.0.3?

**Comment by plastilint** [comment]
Yes, I'm running the latest version.

(it's more like 3 pixels short btw)

**Comment by jaagr** [comment]
@plastilint 9f1d9a1 should fix this, please verify and close if it's solved

**Comment by plastilint** [comment]
Yes, it's fixed now, thank you!
