### ISSUE TITLE
Windows Title with #Number makes polybar disappear

### ISSUE THREAD

**Issue by qgnox** [jaagr/polybar#393]
Version 3.0.3 , using Chrome or Firefox when it loads a url/page that in title has a #number the status bar disappear when using xwindow module , systray stays. log info shows : 

warn: Dropping unmatched character  (U+0002) 

http://imgur.com/ufyuu88l.png

Url/Page example : github.com/jaagr/polybar/issues/392

**Comment by jaagr** [comment]
It works fine for me. Can you post your config

**Comment by qgnox** [comment]
This is my config, tested with and without compton , and also deactivating i3 "for_window *** floating enable" same behaviour . with 2.5 version same config no problems. 

`;=====================================================
;
;   To learn more about how to configure Polybar
;   go to https://github.com/jaagr/polybar
;
;   The README contains alot of information
;
;=====================================================

[colors]
;background = #222
background = #586e75
background-alt = #444
foreground = #dfdfdf
;foreground-alt = #55
foreground-alt = #dfdfdf
primary = #ffb52a
secondary = #e60053
alert = #bd2c40

[global/wm]
margin-top = 0
margin-bottom = 1

[bar/example]
;monitor = ${env:MONITOR:HDMI-1}
width = 100%
;height = 27
height = 25
offset-x = 0
offset-y = 0

;background = ${xrdb:color9}
background = ${colors.background}
foreground = ${colors.foreground}

overline-size = 2
overline-color = #f00
underline-size = 2
underline-color = #00f

border-bottom-size = 2
border-bottom-color = #333

padding-left = 0
padding-right = 2
module-margin-left = 1
module-margin-right = 2

;font-0 = fixed:pixelsize=10
font-0 = xos4 Terminus:pixelsize=10
font-1 = unifont:fontformat=truetype:size=6:heavy;-2
;font-1 = Terminus:size=6:heavy;-2
font-2 = Wuncon Siji:pixelsize=10
;font-2 = FontAwesome:pixelsize=10 
modules-left = i3 xwindow
modules-center =  
modules-right = mpd backlight-acpi volume filesystem memory cpu wlan eth battery temperature date powermenu

tray-position = right
tray-padding = 2
;tray-transparent = true
;tray-background = #0063ff

;wm-restack = bspwm
;wm-restack = i3

;override-redirect = true

;scroll-up = bspwm-desknext
;scroll-down = bspwm-deskprev

;scroll-up = i3wm-wsnext
;scroll-down = i3wm-wsprev

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
label-layout = %{F#55}%{F-} %layout%
label-layout-underline = ${colors.secondary}
label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.secondary}

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /
;mount-1 = /home
;mount-2 = /invalid/mountpoint

label-mounted = %mountpoint%: %free%/%total%

label-unmounted = %mountpoint%: not mounted
label-unmounted-foreground = ${colors.foreground-alt}

[module/bspwm]
type = internal/bspwm

label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2

label-occupied = %index%
label-occupied-padding = 2

label-urgent = %index%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %index%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 2

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

label-mode-padding = 1
label-mode-foreground = #000
label-mode-background = ${colors.primary}

label-focused = %index%
label-focused-background = ${module/bspwm.label-focused-background}
label-focused-underline = ${module/bspwm.label-focused-underline}
label-focused-padding = ${module/bspwm.label-focused-padding}

label-unfocused = %index%
label-unfocused-padding = ${module/bspwm.label-occupied-padding}

label-urgent = %index%!
label-urgent-background = ${module/bspwm.label-urgent-background}
label-urgent-padding = ${module/bspwm.label-urgent-padding}

label-visible = %index%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

ws-icon-0 = 1;♚
ws-icon-1 = 2;♛
ws-icon-2 = 3;♜
ws-icon-3 = 4;♝
ws-icon-4 = 5;♞
ws-icon-default = ♟


[module/mpd]
type = internal/mpd

format-online =  <label-song>  <icon-prev> <icon-seekb> <icon-stop> <toggle> <icon-seekf> <icon-next>  <icon-repeat> <icon-random>

label-song-maxlen = 25
label-song-ellipsis = true

icon-prev = 
icon-seekb = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 
icon-seekf = 

icon-random = 
icon-repeat = 

toggle-on-foreground = ${colors.primary}
toggle-off-foreground = #66

[module/xbacklight]
type = internal/xbacklight

format = <label> <bar>
label = " "

bar-width = 10
bar-indicator = │
bar-indicator-foreground = #ff
bar-indicator-font = 2
bar-fill = ─
bar-fill-font = 2
bar-fill-foreground = #9f78e1
bar-empty = ─
bar-empty-font = 2
bar-empty-foreground = ${colors.foreground-alt}

[module/backlight-acpi]
inherit = module/xbacklight
type = internal/backlight
card = intel_backlight

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #f90000
label = %percentage:2%%

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #4bffdc
label = %percentage_used:2%%

[module/wlan]
type = internal/network
interface = wlp0s20u2u4
;
interval = 3.0
accumulate_stas = true

format-connected = <ramp-signal> <label-connected>
format-connected-underline = #9f78e1
format-disconnected-underline = ${self.format-connected-underline}

label-connected = %local_ip% %{F#0f0}%downspeed:9%%{F-} %{F#ff9900}%upspeed:9%%{F-} 
label-disconnected = %ifname% disconnected
label-disconnected-foreground = ${colors.foreground-alt}

ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
#ramp-signal-4 = 
#ramp-signal-5 =
ramp-signal-foreground = ${colors.foreground-alt}

[module/eth]
type = internal/network
interface =
interval = 3.0

format-connected-underline = #55aa55
format-connected-prefix = " "
format-connected-foreground-foreground = ${colors.foreground-alt}
label-connected = %local_ip%

format-disconnected-underline = ${self.format-connected-underline}
label-disconnected = %ifname% disconnected
label-disconnected-foreground = ${colors.foreground-alt}

[module/date]
type = internal/date
interval = 5

date =
date-alt = " %Y-%m-%d"

time = %H:%M
time-alt = %H:%M:%S

format-prefix = 
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #0a6cf5

label = %date% %time%

[module/volume]
type = internal/volume

format-volume = <label-volume> <bar-volume>
label-volume = " "
label-volume-foreground = ${root.foreground}

format-muted-prefix = " "
format-muted-foreground = ${colors.foreground-alt}
label-muted = sound muted

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = │
bar-volume-indicator-font = 2
bar-volume-indicator-foreground = #ff
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

[module/battery]
type = internal/battery
battery = BAT1
adapter = ADP1
full-at = 98

format-charging = <animation-charging> <label-charging>
format-charging-underline = #ffb52a

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-underline = ${self.format-charging-underline}

format-full-prefix = " "
format-full-prefix-foreground = ${colors.foreground-alt}
format-full-underline = ${self.format-charging-underline}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-foreground = ${colors.foreground-alt}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-foreground = ${colors.foreground-alt}
animation-charging-framerate = 750

[module/temperature]
type = internal/temperature
thermal-zone = 2
warn-temperature = 80

format = <ramp> <label>
format-underline = #f50a4d
format-warn = <ramp> <label-warn>
format-warn-underline = ${self.format-underline}

label = %temperature%
label-warn = %temperature%
label-warn-foreground = ${colors.secondary}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground-alt}

[module/powermenu]
type = custom/menu

format-spacing = 1

label-open =  
label-open-foreground = ${colors.secondary}
label-close =  cancel
label-close-foreground = ${colors.secondary}
label-separator = |
label-separator-foreground = ${colors.foreground-alt}

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = systemctl reboot

menu-2-0 = power off
menu-2-0-exec = systemctl poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0

; vim:ft=dosini
`

**Comment by filiphe** [comment]
Can reproduce with this config as well. However, polybar does not disappear but is emptied of all content instead.

```
;=====================================================
;
;   To learn more about how to configure Polybar
;   go to https://github.com/jaagr/polybar
;
;   The README contains alot of information
;
;=====================================================

[colors]
black = #1d2021
red=#cc241d
green=#98971a
yellow=#d79921
blue=#458588
magenta=#b16286
cyan=#689d6a
light_grey=#a89984
grey=#928374
bright_red=#fb4934
bright_green=#b8bb26
bright_yellow=#fabd2f
bright_blue=#83a598
bright_magenta=d3869b
bright_cyan=#8ec07c
white=#ebdbb2

background = ${colors.black}
background-alt = ${colors.grey}
foreground = ${colors.white}
foreground-alt = ${colors.light_grey}
primary = ${colors.bright_blue}
line = ${colors.yellow}
secondary = ${colors.cyan}
alert = ${colors.red}
urgent = ${colors.alert}

[global/wm]
margin-top = 5
margin-bottom = 5

[bar/primary]
monitor = ${env:MONITOR:DP-4}
width = 100%
height = 20
offset-x = 0
offset-y = 0
bottom = true

background = ${colors.background}
foreground = ${colors.foreground}

overline-size = 2
overline-color = #f00
underline-size = 2
underline-color = #00f

border-bottom = 2
border-bottom-color = #333

spacing = 1
padding-left = 0
padding-right = 2
module-margin-left = 1
module-margin-right = 2

font-0 = misc fixed:size=10:regular:antialias=false;0
font-1 = unifont:size=6:heavy:fontformat=truetype;-2
font-2 = wuncon siji:size=10

modules-left = ewmh
modules-center = xwindow 
modules-right = mpd volume cpu memory date powermenu

tray-position = right
tray-padding = 2

[module/ewmh]
type                            = internal/xworkspaces
pin-workspaces                  = false
enable-click                    = true
enable-scroll                   = false

icon-0                          = one;one
icon-1                          = two;two
icon-2                          = three;three
icon-3                          = four;four
icon-default                    = 

label-active                    = %icon%
label-active-underline          = ${colors.line}
label-active-padding            = 2

label-occupied                  = %icon%
label-occupied-underline        = ${colors.primary}
label-occupied-padding          = 2

label-empty                     = %icon%
label-empty-padding             = 2

label-urgent                    = %icon%
label-urgent-underline          = ${colors.urgent}
label-urgent-padding            = 2

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%

[module/mpd]
type = internal/mpd

format-online = <label-song>  <icon-prev> <icon-seekb> <icon-stop> <toggle> <icon-seekf> <icon-next>  <icon-repeat> <icon-random>
;format-online = <label-song>

label-song-maxlen = 100
label-song-ellipsis = true

icon-prev = 
icon-seekb = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 
icon-seekf = 

icon-random = 
icon-repeat = 

toggle-on-foreground = ${colors.yellow}
toggle-off-foreground = ${colors.grey}

[module/date]
type = internal/date
interval = 5

date = "%Y-%m-%d"
date-alt = "%Y-%m-%d"

time = "%H:%M "
time-alt = "%H:%M:%S "

format-prefix = 
format-prefix-foreground = ${colors.foreground-alt}
format-underline = ${colors.blue}

label = %time% %date%

[module/volume]
type = internal/volume

format-volume = <label-volume> <bar-volume>
label-volume = VOL
label-volume-foreground = ${root.foreground}

format-muted-prefix = " "
format-muted-foreground = ${colors.foreground-alt}
label-muted = sound muted

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = │
bar-volume-indicator-font = 2
bar-volume-indicator-foreground = #ff
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

[module/powermenu]
type = custom/menu

label-open =  power
label-open-foreground = ${colors.red}
label-close =  cancel
label-close-foreground = ${colors.red}
label-separator = |
label-separator-foreground = ${colors.foreground-alt}

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = reboot

menu-2-0 = power off
menu-2-0-exec = poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /
mount-1 = /home

; Available tokens:
;   %mountpoint%
;   %type%
;   %fsname%
;   %percentage_free%
;   %percentage_used%
;   %total%
;   %free%
;   %used%

label-mounted = %mountpoint%: %used% / %total%

label-unmounted = %mountpoint%: not mounted
label-unmounted-foreground = ${colors.foreground-alt}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = ${colors.red}
label = %percentage%

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = ${colors.green}
label = %percentage_used%

; vim:ft=dosini
```

**Comment by huntergoldstein** [comment]
I'm able to recreate this with a minimal config.
# Config
```dosini
[global/wm]
margin-top = 0
margin-bottom = 0

[bar/test]
monitor = ${env:MONITOR:eDP1}
width = 25%
modules-center = test
font-0 = Misc Termsyn;0
font-1 = Noto Sans CJK SC;0

[module/test]
type = internal/xwindow
label = %title:0:30:...%
```
The second font should be irrelevant.
# Version
```bash 
$ polybar -vv
polybar 3.0.3

Features: +alsa +curl +i3 +mpd +network

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro
```
# Log
https://gist.github.com/huntergoldstein/4c3b731f39b01dbc1515e5e6261eb472
After going to the URL linked above, I continually switch focus back and forth between my terminal and my instance of chromium.
# Video
https://youtu.be/mVn1M_9qb34

**Comment by qgnox** [comment]
Looks like is something with the bitmap fonts with some characters,  example "Tecnol**ó**gica' " as title in a Window , if in : font-0 I changed from "xos4 Terminus" to "Misc Fixed" font same error, but if I put a ttf font like Noto Sans it works ok.

**Comment by jeremyThibault** [comment]
Hi,
I get the same warning `warn: Dropping unmatched character (U+0002)`, and the bar content disappears. It happens when I visit https://github.com/thestinger/termite/blob/master/README.rst for example, but not when I visit #392.

The issue stops when removing the `label-maxlen` option or the `:0:30:...` part of the label.

I don't know if I can legally post my config here, but I stole it from `https://github.com/guisilvano/dotfiles` and modified it a bit.

Hope that helps :)

**Comment by apetresc** [comment]
Oh thank goodness you guys diagnosed it, I was going crazy trying to figure out what was causing this so intermittently, but now I can reproduce it 100% with @jeremyThibault and @huntergoldstein's links. I would paste my config but it's basically the same as everyone else's here, just wanted to express my relief.

I'm on the latest polybar 3.0.3 if that helps.

**Comment by qgnox** [comment]
3.0.4 Fix this issue , Thanks .

**Comment by hmohamad** [comment]
3.0.4 only fixes `label-maxlen`.
The `:0:30:...` notation still has this issue.

**Comment by qgnox** [comment]
@hmohamad yep you are right.

**Comment by jaagr** [comment]
Was able to reproduce the issue using the latest version. Will fix as soon as I get the time.

**Comment by hmohamad** [comment]
Actually I have to correct myself, even using `label-maxlen` polybar crashes with some very specific chars in the title. 
Example: https://docs.python.org/3/library/unittest.mock.html
(In this case its the em-dash)

**Comment by femtomatic** [comment]
Hi, I'm a little late to the show but came here for the same issue. In my case, the issue seems to be with accented characters in title bars, but not for every applications. For example, if I open a pdf with the é character in the filename (ex: tournée.pdf) with Okular, polybar will disappear, but if I open it with zathura, Evince, or even qpdfview the problem doesn't show. It's really odd.

I don't have any issues with the em-dash under Firefox, I can open the link from @hmohamad without problem.
I also tried a couple of different fonts (patched for powerline, unpatched, ttf...) and they all produce exactly the same result.
Removing the `:0:30:...` part from the label resolves the issue, but it's not really a viable solution...

I use polybar 3.0.4 from the AUR with i3-gaps. I hope all this info helps a bit.

**Comment by jaagr** [comment]
I haven't had time to fix this yet but I'm pretty sure it has something to do with the trim of non-ascii chars.

**Comment by sfiq** [comment]
It seems to be the case, I've noticed that everytime Japanese characters appear while having maxlen or 0:30, the bar would disappear.
At first I thought Firefox was the issue but it turns out MPD with maxlen was causing it too

**Comment by femtomatic** [comment]
Yep, after a few tests I think it's the trim of non-ascii characters and not the accents that are the problem. Okular adds an en dash + Okular after the name of the file in the title (ex:"file.pdf – Okular"), which is why it was the only pdf reader causing the problem. 

Same goes for websites, I had trouble with this site: http://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.f_regression.html 
but not this one: http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.ARDRegression.html#sklearn.linear_model.ARDRegression
The only difference is the position of the en dash in the title, I changed `label-maxlen` to 50 and the problem was resolved for this particular site.

I installed the git version of the package on AUR and unfortunately, the problem is still there after the latest commit (polybar-git 3.0.4.r2.g73faa18-1). I wish I was better at coding and had more time so I could provide some help...

**Comment by skystrife** [comment]
Can you post your config somewhere?

**Comment by femtomatic** [comment]
I haven't set up my dotfiles with github yet so here is a pastebin link for my config: http://pastebin.com/kQBJuMgQ
Note that I use a powerline patched font, but the effect is the same with other fonts such as Noto Sans.

My browser is firefox 51.0.1

**Comment by skystrife** [comment]
OK, interesting. I've got it repeating here too, but *only* via `label-maxlen = 40` now. If I use your previous `label = %title:0:40:...%` things are fine.

Looking into it more now...

**Comment by skystrife** [comment]
Aha! I missed a place where truncation is being performed. Going to switch that to use `utf8_truncate` as well. Patch inbound.

**Comment by femtomatic** [comment]
I updated this morning with the latest commit (polybar-git 3.0.4.r3.gbd8e748-1) and everything seems to work fine now.
Thanks  @skystrife!

**Comment by qgnox** [comment]
Thanks, for the fix .
