### ISSUE TITLE
systrays too bigs

### ISSUE THREAD

**Issue by rotsix** [jaagr/polybar#394]
Hi, as pictures speak lourder than words: https://ptpb.pw/h8SF.png

As you can see, icon is too big, and is cut.

Have you any idea how i can make it appears well ?

Here are my specs
archlinux armv7h 4.4.42-1-ARCH

polybar 2.5.2-1-g73df20d-git
Features: +alsa +curl +i3 +mpd +network
(compiling the new version)

Thx for your help.

**Comment by jaagr** [comment]
Try setting the client max size parameter

~~~ dosini
[bar/mybar]
tray-maxsize = 16
~~~

**Comment by rotsix** [comment]
I've already set, with tray-maxsize = 10 (same as font-size).
