### ISSUE TITLE
Incorrect Free Disk Space

### ISSUE THREAD

**Issue by qgnox** [jaagr/polybar#396]
Version 3.0.3

Shows 148GB free of 349GB

![screenshot_2017-01-29_17-32-07](https://cloud.githubusercontent.com/assets/1157328/22408565/170e9f3c-e649-11e6-8947-e6bebf01b623.png)

But by command line I have 130GB free of 349GB (ext4)

```
➜  ~ df -h /                                                                                                           
Filesystem      Size  Used Avail Use% Mounted on                                                                       
/dev/sda7       349G  202G  130G  61% /                                                                                
```
My config module : 

```
[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /
;mount-1 = /home
;mount-2 = /invalid/mountpoint

label-mounted = %mountpoint%: %free%/%total%

label-unmounted = %mountpoint%: not mounted
label-unmounted-foreground = ${colors.foreground-alt}
```

**Comment by jaagr** [comment]
This is because it shows the *free* disk space and not the *available* disk space. I will patch it though.

**Comment by jaagr** [comment]
@qgnox 82d360e should fix this, please verify and close the issue if it's solved

**Comment by qgnox** [comment]
Hi, 

![screenshot_2017-02-07_09-35-43](https://cloud.githubusercontent.com/assets/1157328/22695455/d8a3f75c-ed18-11e6-99d5-0dc1d0372449.png)

```
➜  ~ df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda7       349G  210G  122G  64% /
➜  ~ df /
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/sda7      365557000 219738832 127225864  64% /

```
127225864 * 1024 -> 121.33204 GB , looks like df -h is rounding up .  For me issue is closed . Thanks .
