### ISSUE TITLE
System's DPI is ignored

### ISSUE THREAD

**Issue by phuhl** [jaagr/polybar#398]
When using a hi-dpi display (also often called “retina display”) the fonts are all right (when using size instead of pixelsize) but all sizes like margins, height, underline-size, etc. are not adjusted.

To reproduce, use xrandr --dpi 192 and set Xft.dpi: 192 in ~/.Xresources

**Comment by hg8** [comment]
You can manually set the DPI in Polybar `config` file.

    dpi = 192

**Comment by phuhl** [comment]
Ah, missed that one. Still would be nice if it could detect it by getting the value from the xserver.

**Comment by hg8** [comment]
It was detected before... Not sure if kernel or Polybar update broke it recently.
What system are you using ?

**Comment by phuhl** [comment]
Hardware: Dell XPS 13 9360

Software: Arch x64, set up yesterday (so up to date) + bspwm (up to date as well) on xserver (of coures). 

What else do you need?

If it does detect DPI, then this might also be my mistake by setting it the wrong way. I set it by creating a file /etc/X11/xorg.conf.d/90-monitor.conf like this:

       Section "Monitor"
          Identifier "eDP-1"
          DisplaySize 346 194
       EndSection

**Comment by hg8** [comment]
You have the exact same hardware and software than me.
I have set the DPI in my `.xinitrc` : 
   xrandr --dpi 220

And it's not detected either. 

@jaagr will probably know where the problem come from. He always find a solution ;)

**Comment by skystrife** [comment]
```
dpi = -1
```

or

```
dpi = ${xrdb:Xft.dpi:-1}
```

in the bar configuration file don't work?

@jaagr maybe we should make -1 the default? I didn't in my PR because I wasn't certain how trustworthy the monitor measurements from X are. I would have actually used Xft.dpi as the default, but right now xrdb support is optional.

**Comment by phuhl** [comment]
@skystrife No, does not change anything

**Comment by phuhl** [comment]
Today another dpi-related problem occurred: Tray-icons are too small (well, the dpi-setting did not do anything at all i think). My fonts look all right because i did not use pixelsize but size like this `font-0 = fixed:size=9;0` what apparently makes it dpi-dependent or so. But still, the height of the bar (and stuff like that) have to be set manually (sucks for multiple-machine-setups) and the tray is too small without me knowing a fix, yet.

**Comment by jaagr** [comment]
The wiki describes all available tray options. Refer to it to see how to change the max size of the tray icons.

**Comment by phuhl** [comment]
Thank you for the quick response. If you mean the `tray-scale` option... it does not work for me. The tray area grows but the icon-size stays the same. That results in a huge gray rectangle with tiny icons within. If you wish i can attach a screenshot.

**Comment by UnicodeAlt255** [comment]
Yes the tray-scale option does not work. It leaves a blank space where the tray icons use to be.

**Comment by jaagr** [comment]
I meant `tray-maxsize`, but the application needs to support the defined size.

**Comment by jaagr** [comment]
I usually test the tray using this tool: https://github.com/elboulangero/gtk-status-icon-size-test

**Comment by UnicodeAlt255** [comment]
Wow, tray-maxsize works to scale up the tray icons. I set it to 1000 and now that fixed the one problem I had with polybar. Thanks.

**Comment by NBonaparte** [comment]
Closing as all issues appear to be fixed.

**Comment by Hubro** [comment]
> You can manually set the DPI in Polybar `config` file.
> 
> ```
> dpi = 192
> ```

Where do I set this? I've tried adding it to all sections in the example config and it's not making my bar any bigger. That option isn't mentioned anywhere in the wiki either, and when I google it all I find are Github issues.

```
$ polybar --version
polybar 3.2.0-56-g152125d

Features: +alsa +curl +i3 +mpd +network(wireless-tools) +pulseaudio +xkeyboard
```

**Comment by hg8** [comment]
> Where do I set this? 

Just put it in your bar section like this : 

```
[bar/top]
dpi = 220
[...]
```

See my config for an example : https://github.com/hg8/dotfiles/blob/master/.config/polybar/config#L12

**Comment by Hubro** [comment]
> > Where do I set this?
> 
> Just put it in your bar section like this :
> 
> ```
> [bar/top]
> dpi = 220
> [...]
> ```
> See my config for an example : https://github.com/hg8/dotfiles/blob/master/.config/polybar/config#L12

I see. So what does this setting do? In my case it doesn't appear to affect my bar in any way, I still have to increase the bar height and font sizes myself to get the bar bigger.

**Comment by patrick96** [comment]
The dpi setting only affects how fonts are rendered and it also only affects scalable fonts. If your characters don't come from scalable fonts then `dpi` won't do anything. You will also have to set the bar height yourself.

**Comment by srid** [comment]
> Wow, tray-maxsize works to scale up the tray icons. I set it to 1000 and now that fixed the one problem I had with polybar. Thanks.

@billop Does this still work for you? `tray-maxsize` has no effect whatsoever on my system (27" 5k monitor).

**Comment by billop** [comment]
> > Wow, tray-maxsize works to scale up the tray icons. I set it to 1000 and now that fixed the one problem I had with polybar. Thanks.
> 
> @billop Does this still work for you? `tray-maxsize` has no effect whatsoever on my system (27" 5k monitor).

sorry I've moved on to sway + waybar so I have no clue

**Comment by huwqchn** [comment]
> > Where do I set this?
> 
> Just put it in your bar section like this :
> 
> ```
> [bar/top]
> dpi = 220
> [...]
> ```
> 
> See my config for an example : https://github.com/hg8/dotfiles/blob/master/.config/polybar/config#L12

set dpi just scaling font, but not effect icon. how to make icon bigger
