### ISSUE TITLE
Github module causing polybar to terminate

### ISSUE THREAD

**Issue by bpinto** [jaagr/polybar#399]
```
terminate called after throwing an instance of 'polybar::v2_0_0::application_error'
  what():  Couldn't resolve host name
```

The github module requires an active internet connection but I don't have one when I am starting i3, so the bar is never displayed, I have to manually start it. An easier way to reproduce this is to run `nmcli r wifi off` (or ethernet) if you are using network manager.

```
polybar 3.0.3

Features: +alsa +curl +i3 -mpd +network

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm

Build type: Gentoo
Compiler: /usr/x86_64-pc-linux-gnu/gcc-bin/5.4.0/g++
Compiler flags: -O2 -pipe -mtune=native -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1 -Wl,--as-needed
```

P.S.: I'm on 3.0.3 but the error message says "polybar::v2_0_0"

**Comment by jaagr** [comment]
I'll patch this. The error message namespace mismatch has been fixed in the latest code (after 3.0.3)

**Comment by jaagr** [comment]
@bpinto 6fa2d39 should fix this, please verify and close if it's solved

**Comment by bpinto** [comment]
Confirming it's working with that commit. Thanks!
