### ISSUE TITLE
Array out of bounds(?) for battery module

### ISSUE THREAD

**Issue by schvabodka-man** [jaagr/polybar#400]
Hi there! I've installed polybar and running it but i've encountered a little problem. It seems that when i'm disconnectind my laptop from power and then connecting it again battery module stops with this

`module/battery: basic_string::erase: __pos (which is 8) > this->size() (which is 7)`

You can find my config file [here](https://github.com/schvabodka-man/Dotfiles/blob/master/.config/polybar/polybar.ini) My OS is Fedora 25.

**Comment by jaagr** [comment]
Hi, what version are you using? `polybar -vv`

**Comment by schvabodka-man** [comment]
`polybar 2.4.6 

Features: +alsa +curl +i3 +mpd +network 

Build type: Release
Compiler: /usr/bin/c++
Compiler flags:  -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors
Linker flags: 

ALSA_SOUNDCARD              default
BSPWM_SOCKET_PATH           /tmp/bspwm_0_0-socket
BSPWM_STATUS_PREFIX         W
BUILDER_SPACE_TOKEN         %__
CONNECTION_TEST_IP          8.8.8.8
PATH_ADAPTER                /sys/class/power_supply/%adapter%
PATH_BACKLIGHT_MAX          /sys/class/backlight/%card%/max_brightness
PATH_BACKLIGHT_VAL          /sys/class/backlight/%card%/brightness
PATH_BATTERY                /sys/class/power_supply/%battery%
PATH_CPU_INFO               /proc/stat
PATH_MEMORY_INFO            /proc/meminfo
PATH_TEMPERATURE_INFO       /sys/class/thermal/thermal_zone%zone%/temp
`

**Comment by jaagr** [comment]
Update to the latest version. This should be fixed.

**Comment by schvabodka-man** [comment]
Well, it seems that it's latest version on fedora copr repo. No newer packages

**Comment by jaagr** [comment]
I'd recommend asking the maintainer of that package to update it.
