### ISSUE TITLE
network downspeed dont go above 2MB/s

### ISSUE THREAD

**Issue by helionmelion** [jaagr/polybar#402]
My first post here, hello there! this polybar is awesome, im coming from i3blocks.

I would like to point this issue, could be a bug or a noob (me).
my wired internet is about 36Mbit/s max download rate (about 4.5MB/s) but the variable %downspeed% does not show above 2MB/s (using speedtest or similar sites). Could someone point if im missing something? thanks a lot

**Comment by jaagr** [comment]
Hi and thank you!

I'm currently rewriting all the network handling to drop the `wireless_tools` dependency, so I won't do any debugging/changes to the existing code.

**Comment by helionmelion** [comment]
thank you for response

**Comment by itamarx22** [comment]
There are problems with the %signal% aswell (just to point out)
Thanks for the care
