### ISSUE TITLE
I use fontawesome icons for workspaces but they have recently shifted up

### ISSUE THREAD

**Issue by japhir** [jaagr/polybar#403]
I use fontawesome icons from my [i3 config](https://github.com/japhir/ArchConfigs/blob/master/i3config), which are distilled with polybar through the `strip-wsnumbers = true` property in my [polybar config file](https://github.com/japhir/ArchConfigs/blob/master/polybarconfig).

With one of the recent updates my icons have all shifted up by a couple of pixels, placing them partly offscreen. Is this the intended behaviour?

**Comment by jaagr** [comment]
The font rendering was rewritten, so just update the vertical offset for the affected font.

**Comment by japhir** [comment]
cool! just updated my config with the help of the wiki and this fixed the issue!
