### ISSUE TITLE
Incorrect memory updating in WSL

### ISSUE THREAD

**Issue by Xyene** [jaagr/polybar#405]
On a Windows machine with 16GB of RAM running WSL, polybar seems to incorrectly parse out memory info.

![image](https://cloud.githubusercontent.com/assets/1403503/22523357/1f35170e-e88d-11e6-8c0f-674af223dfc9.png)

The module config for it is:

```ini
[module/memory]
type = internal/memory
interval = 2
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #4bffdc
label = RAM %gb_used%/%gb_free%
```

`/proc/meminfo`, which polybar uses, seems to display the correct information. Other tools (e.g. neofetch) are able to obtain an accurate measure of memory use.

```
$ cat /proc/meminfo
MemTotal:       16647124 kB
MemFree:         5969580 kB
Buffers:           34032 kB
Cached:           188576 kB
SwapCached:            0 kB
Active:           167556 kB
Inactive:         157876 kB
Active(anon):     103104 kB
Inactive(anon):    17440 kB
Active(file):      64452 kB
Inactive(file):   140436 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       4980736 kB
SwapFree:        4612092 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:        102824 kB
Mapped:            71404 kB
Shmem:             17720 kB
Slab:              13868 kB
SReclaimable:       6744 kB
SUnreclaim:         7124 kB
KernelStack:        2848 kB
PageTables:         2524 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      515524 kB
Committed_AS:    3450064 kB
VmallocTotal:     122880 kB
VmallocUsed:       21296 kB
VmallocChunk:      66044 kB
HardwareCorrupted:     0 kB
AnonHugePages:      2048 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       12280 kB
DirectMap4M:      897024 kB
```

I'm running the latest version from git.

```
$ polybar -version
polybar 3.0.3

Features: -alsa -curl +i3 -mpd -network
```

I think the issue is that polybar relies on the order in which `/proc/meminfo` reports data: it takes the first 3 numbers if finds, regardless of their label. On top of that, and `MemAvailable` not being implemented in WSL, so it ends up taking `Buffers` instead. A real Linux system reports the ordering:

```
$ cat /proc/meminfo
MemTotal:        4043492 kB
MemFree:          985192 kB
MemAvailable:    2197024 kB
```

The man page for `/proc/meminfo` doesn't (unless I'm missing it) guarantee an ordering for memory info to be consistent. Also, `MemAvailable` is only available since Linux 3.14, while WSL implements a 3.4 kernel.

Would it be within the scope of polybar to have it run (at least partially, e.g. have `gb_used` and `gb_total` functioning, if not `gb_free`) on older kernels, and by extension, WSL? Would be really cool to have this working 😁 

---

As a workaround, I've been using a custom script to read out meminfo.

```python
#!/usr/bin/python

parsed = {}
with open('/proc/meminfo') as meminfo:
        for line in meminfo:
                id, data = line.strip().split()[:2]
                parsed[id[:-1]] = int(data)

gb_total = parsed['MemTotal']

gb_used = (parsed['MemTotal'] + parsed['Shmem'] - parsed['MemFree'] -
           parsed['Buffers'] - parsed['Cached'] - parsed['SReclaimable'])

print '%.2f GB / %.2f GB' % (gb_used / 1048576.0, gb_total / 1048576.0)
```

```ini
[module/wsl-memory]
type = custom/script
interval = 2
exec = /home/xyene/readmeminfo.py
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #4bffdc
```

The output is a lot closer to what would be expected:

![image](https://cloud.githubusercontent.com/assets/1403503/22531084/dbeb02c2-e8ac-11e6-9864-17a809cafea3.png)

**Comment by jaagr** [comment]
Yeah this should be an easy fix. Short on time at the moment though.

**Comment by Xyene** [comment]
I have a fix that I've implemented locally, reading the fields appropriately and falling back on an approximation for available memory when `MemAvailable` doesn't exist. If you'd like, I can open a PR up with it.

**Comment by jaagr** [comment]
Yeah please do.
