### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Jedipottsy** [jaagr/polybar#408]
Hi,
Trying to compile on Centos7, using the gcc 5.3 software collection

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-4/root/usr/libexec/gcc/x86_64-redhat-linux/5.3.1/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-4/root/usr --mandir=/opt/rh/devtoolset-4/root/usr/share/man --infodir=/opt/rh/devtoolset-4/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --disable-libgcj --with-default-libstdcxx-abi=gcc4-compatible --with-isl=/builddir/build/BUILD/gcc-5.3.1-20160406/obj-x86_64-redhat-linux/isl-install --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 5.3.1 20160406 (Red Hat 5.3.1-6) (GCC)

./build.sh  -f
** Fetching submodules
** Removing existing build dir (-f)
** Setting build options
** Include support for "internal/i3" (requires i3) ------------------- [Y/n]: n
** Include support for "internal/volume" (requires alsalib) ---------- [Y/n]: y
** Include support for "internal/network" (requires wireless_tools) -- [Y/n]: n
** Include support for "internal/mpd" (requires libmpdclient) -------- [Y/n]: n
** Include support for "internal/github" (requires libcurl) ---------- [Y/n]: n
** Build "polybar-msg" used to send ipc messages --------------------- [Y/n]: y
** Using compiler: clang++/clang
** Executing cmake command
-- The C compiler identification is Clang 3.4.2
-- The CXX compiler identification is Clang 3.4.2
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type specified; using RelWithDebInfo
-- Using supported compiler Clang-3.4.2
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Checking for module 'cairo-fc'
--   Found cairo-fc, version 1.14.2
-- Checking for module 'alsa'
--   Found alsa, version 1.1.1
-- Checking for module 'xcb-xkb'
--   Found xcb-xkb, version 1.11
-- Checking for module 'xcb-randr'
--   Found xcb-randr, version 1.11
--  Build:
--    Type: RelWithDebInfo
--    CC: /usr/bin/clang  -O2 -g -DNDEBUG
--    CXX: /usr/bin/clang++  -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors -O2 -g -DNDEBUG
--    LD: /usr/bin/ld  
--  Targets:
--    polybar-msg
--    testsuite
--  Module supprt:
--    alsa
--    curl
--    i3
--    mpd
--    network
--  X extensions:
--    xcb-randr
--    xcb-randr (monitor support)
--    xcb-render
--    xcb-damage
--    xcb-sync
--    xcb-composite
--    xcb-xkb
--    xcb-xrm
-- Found font: fixed:pixelsize=10
-- Font not found: unifont:fontformat=truetype
-- Found font: siji:pixelsize=10
-- Checking for module 'xcb-proto'
--   Found xcb-proto, version 1.11
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.5", minimum required is "2.7") 
-- XCB[XCB]: Found component XCB
-- Found XCB_XCB: /usr/lib64/libxcb.so  
-- XCB[ICCCM]: Found component ICCCM
-- Found XCB_ICCCM: /usr/lib64/libxcb-icccm.so  
-- XCB[EWMH]: Found component EWMH
-- Found XCB_EWMH: /usr/lib64/libxcb-ewmh.so  
-- XCB[UTIL]: Found component UTIL
-- Found XCB_UTIL: /usr/lib64/libxcb-util.so  
-- XCB[IMAGE]: Found component IMAGE
-- Found XCB_IMAGE: /usr/lib64/libxcb-image.so  
-- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-icccm.so;/usr/lib64/libxcb-ewmh.so;/usr/lib64/libxcb-util.so;/usr/lib64/libxcb-image.so  
-- Searching for xcbgen with python2
-- Found xcbgen in /usr/lib/python2.7/site-packages
-- XCB[RANDR]: Found component RANDR
-- Found XCB_RANDR: /usr/lib64/libxcb-randr.so  
-- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-icccm.so;/usr/lib64/libxcb-ewmh.so;/usr/lib64/libxcb-util.so;/usr/lib64/libxcb-image.so;/usr/lib64/libxcb-randr.so  
-- XCB[XKB]: Found component XKB
-- Found XCB_XKB: /usr/lib64/libxcb-xkb.so  
-- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-icccm.so;/usr/lib64/libxcb-ewmh.so;/usr/lib64/libxcb-util.so;/usr/lib64/libxcb-image.so;/usr/lib64/libxcb-randr.so;/usr/lib64/libxcb-xkb.so  
-- xpp: including xcb proto randr.xml
-- xpp: including xcb proto xkb.xml
-- xpp: including xcb proto xproto.xml
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jedipottsy/.git/polybar/build
** Building project
Scanning dependencies of target xpp
[  1%] Linking CXX static library libxpp.a
list: size, ['red', 'green', 'blue']
list: size, ['red', 'green', 'blue']
[  1%] Built target xpp
Scanning dependencies of target polybar-msg
[  2%] Building CXX object bin/CMakeFiles/polybar-msg.dir/ipc.cpp.o
[  4%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/env.cpp.o
[  5%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/file.cpp.o
[  6%] Linking CXX executable polybar-msg
[  6%] Built target polybar-msg
Scanning dependencies of target polybar
[  8%] Building CXX object bin/CMakeFiles/polybar.dir/adapters/alsa/control.cpp.o
[  9%] Building CXX object bin/CMakeFiles/polybar.dir/adapters/alsa/mixer.cpp.o
[ 11%] Building CXX object bin/CMakeFiles/polybar.dir/cairo/utils.cpp.o
error: debug information for auto is not yet supported
error: debug information for auto is not yet supported
2 errors generated.
make[2]: *** [bin/CMakeFiles/polybar.dir/cairo/utils.cpp.o] Error 1
make[1]: *** [bin/CMakeFiles/polybar.dir/all] Error 2
make: *** [all] Error 2
** Failed to build project

**Comment by jaagr** [comment]
Use a more recent version of GCC or try clang.

**Comment by Jedipottsy** [comment]
fixed it, had to run it manually, not via the build script
