### ISSUE TITLE
Help a noob with polybar icons

### ISSUE THREAD

**Issue by caudy** [jaagr/polybar#409]
Hi, 

Im currently trying to setup icons on my polybar however im struggling to get them to actually work. 

so one example im trying is:

> [module/battery]
> type = internal/battery
> full-at = 98
> format-charging = %{T3}Battery <label-charging> %{T-}
> format-discharging = %{T3}Battery <label-discharging> %{T-}
> ;format-full = %{T3}Battery <label-full>
> label-charging-font = 3
> label-discharging-font = 3
> label-full =
> ;label-full-font = 3

and trying to add this icon to the left of the percentage:
![chrome_2017-02-02_21-34-20](https://cloud.githubusercontent.com/assets/13667325/22569450/7cad9a84-e98f-11e6-9a24-005af414c545.png)

"http://zavoloklom.github.io/material-design-iconic-font/cheatsheet.html"

i have installed the material icons font into /usr/shares/fonts 

im aiming to have my bar look like this when complete: 
![chrome_2017-02-02_21-31-40](https://cloud.githubusercontent.com/assets/13667325/22569381/40aa21d8-e98f-11e6-99e3-06265e1db6bc.png)

**Comment by bpinto** [comment]
@caudy Intesad of using `format-charging = %{T3}Battery %{T-}` You have to copy the battery icon from that link you shared: `format-charging = `

**Comment by caudy** [comment]
@bpinto is there any method to copy the icon from the hex code? as firefox isnt allowing me to copy the icon into the config? 

hex code is 
&#xE1A3;

**Comment by TristanWLB** [comment]
Piggybacking off of this thread because I'd rather not open a separate issue, is there a way to change the font for the custom/text module? I've got a font that uses 'b' to display a Triforce but I can't get the module to use the right font; I've tried label-font & content-font to no avail.

**Comment by bpinto** [comment]
@caudy I don't know, I have never used the hex code there. :(

**Comment by jaagr** [comment]
@TristanWLB Try using raw tags `%{T3}...%{T-}` where 3 is the font index + 1.

**Comment by beanaroo** [comment]
@caudy GNOME Character Map - `gucharmap` is useful for selecting and copying font characters. Most icon fonts use the Private Use Area.
![gucharmap](https://cloud.githubusercontent.com/assets/1748909/22623127/7f2ab4fa-ebb4-11e6-924e-b32c19b3e2ca.png)

**Comment by jaagr** [comment]
@beanaroo Nice tool, might be good to link it in the wiki.

**Comment by beanaroo** [comment]
@jaagr submitted https://github.com/jaagr/polybar/wiki/Fonts :smile:

**Comment by jaagr** [comment]
Nice!
