### ISSUE TITLE
Font alignement problem

### ISSUE THREAD

**Issue by Smatchcube** [jaagr/polybar#413]
Hi,
Today i have a problem with my font alignement, i think a screenshot is worth a thousand words : 
before : http://imgur.com/a/s5krS
after : http://imgur.com/a/zoEL6
As you can see, the font is not in the center of the bar and there is a stange invisible line : 
http://imgur.com/a/llFeC
http://imgur.com/a/yVTOj (the red color was added to show the invisible space)
My last update of polybar was yesterday, i think this is what cause this problem.
I will try to donwgrade to an older version, how can i do that with arch linux ?
My upgrade was : polybar (2.5.2-3 -> 3.0.3-1)
Thanks for the help !

**Comment by IzacCF** [comment]
Hi.

Could you put the date module here?
Or canlendario module, if so its configuration.

**Comment by Smatchcube** [comment]
The problem isn't only with my config (i tested with a config from intenet )


`;=====================================================
;
;   To learn more about how to configure Polybar
;   go to https://github.com/jaagr/polybar
;
;   The README contains alot of information
;
;=====================================================

[colors]
background = 1d1f21
background-alt = #444
foreground = #dfdfdf
foreground-alt = #55
primary = #ffb52a
secondary = #e60053
alert = #bd2c40

[global/wm]
margin-top = 5
margin-bottom = 5

[bar/example]
;monitor = ${env:MONITOR:HDMI-1}
width = 100%
height = 27
offset-x = 0
offset-y = 0

;background = ${xrdb:color9}
background = ${colors.background}
foreground = ${colors.foreground}

overline-size = 0
overline-color = #f00
underline-size = 0
underline-color = #00f

border-top-size = 2
border-top-color = ${module/bspwm.label-focused-background}

spacing = 1
padding-left = 2
padding-right = 2
module-margin-left = 1
module-margin-right = 2

;font-0 = fixed:pixelsize=10;0
font-0 = Roboto:size=9:weight=regular
;font-1 = unifont:size=6:heavy:fontformat=truetype;-2
font-1 = Material Icons:size=11
font-2 = siji:pixelsize=10;0

modules-left = powermenu i3 xwindow
modules-center = date
modules-right = volume eth
;backlight volume xkeyboard memory cpu wlan eth battery temperature

tray-position = right
tray-padding = 2
;tray-transparent = true
;tray-background = #0063ff

;wm-restack = bspwm
;wm-restack = i3

;override-redirect = true

;scroll-up = bspwm-desknext
;scroll-down = bspwm-deskprev

;scroll-up = i3wm-wsnext
;scroll-down = i3wm-wsprev

bottom = true

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-underline = ${colors.secondary}
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}

label-layout = %layout%

label-indicator-padding = 2
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.secondary}

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /
mount-1 = /home
mount-2 = /invalid/mountpoint

label-mounted = %mountpoint%: %percentage_free%

label-unmounted = %mountpoint%: not mounted
label-unmounted-foreground = ${colors.foreground-alt}

[module/bspwm]
type = internal/bspwm
ws-icon-default = x

label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2

label-occupied = %index%
label-occupied-padding = 2

label-urgent = %index%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %index%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 2

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}

#label-focused = %index%
label-focused = 
label-focused-background = ${module/bspwm.label-focused-background}
label-focused-underline = ${module/bspwm.label-focused-underline}
label-focused-padding = ${module/bspwm.label-focused-padding}

#label-unfocused = %index%
label-unfocused = 
label-unfocused-padding = ${module/bspwm.label-occupied-padding}

#label-urgent = %index%!
label-urgent = 
label-urgent-background = ${module/bspwm.label-urgent-background}
label-urgent-padding = ${module/bspwm.label-urgent-padding}

label-visible = %index%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

[module/mpd]
type = internal/mpd

format-online = <label-song>  <icon-prev> <icon-seekb> <icon-stop> <toggle> <icon-seekf> <icon-next>  <icon-repeat> <icon-random>

label-song-maxlen = 25
label-song-ellipsis = true

icon-prev = 
icon-seekb = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 
icon-seekf = 

icon-random = 
icon-repeat = 

toggle-on-foreground = ${colors.primary}
toggle-off-foreground = #66

[module/backlight]
type = internal/xbacklight

format = <label> <bar>
label = BL

bar-width = 10
bar-indicator = │
bar-indicator-foreground = #ff
bar-indicator-font = 2
bar-fill = ─
bar-fill-font = 2
bar-fill-foreground = #9f78e1
bar-empty = ─
bar-empty-font = 2
bar-empty-foreground = ${colors.foreground-alt}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #f90000
label = %percentage%

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #4bffdc
label = %percentage_used%

[module/wlan]
type = internal/network
interface = net1
interval = 3.0

format-connected = <ramp-signal> <label-connected>
format-connected-underline = #9f78e1
format-disconnected-underline = ${self.format-connected-underline}

label-connected = %essid%
label-disconnected = %ifname% disconnected
label-disconnected-foreground = ${colors.foreground-alt}

ramp-signal-0 =
ramp-signal-1 =
ramp-signal-2 =
ramp-signal-3 =
ramp-signal-4 =
ramp-signal-foreground = ${colors.foreground-alt}

[module/eth]
type = internal/network
interface = enp3s0
interval = 3.0

format-connected-underline = #55aa55
format-connected-prefix = ""
format-connected-foreground-foreground = ${colors.foreground-alt}
#label-connected = %local_ip%
label-connected = up
format-connected-offset = 15
format-disconnected-underline = ${self.format-connected-underline}
#label-disconnected = %ifname% disconnected
label-disconnected = disconnected !
label-disconnected-foreground = ${colors.foreground-alt}
format-disconnected-prefix = ""

[module/date]
type = internal/date
interval = 5


date =  " %A, %B %d     "
date-alt = " %c"

time = " %H:%M"
#time-alt = %H:%M:%S

#format-prefix = 
#format-prefix = 
format-prefix-foreground =
#format-underline = #0a6cf5
format-background = ${module/bspwm.label-focused-background}
format-padding = 5

label = %date% %time%

[module/volume]
type = internal/volume

#format-volume = <label-volume> <bar-volume>
label-volume =  %percentage%
label-volume-prefix = " "
label-volume-foreground = ${root.foreground}
format-volume = <ramp-volume> <label-volume>
ramp-volume-0 = 
ramp-volume-1 = 
format-volume-underline = #4bffdc





format-muted-prefix = " "
#format-muted-foreground = ${colors.foreground-alt}
label-muted = 

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = │
bar-volume-indicator-font = 2
bar-volume-indicator-foreground = #ff
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1
full-at = 98

format-charging = <animation-charging> <label-charging>
format-charging-underline = #ffb52a

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-underline = ${self.format-charging-underline}

format-full-prefix = " "
format-full-prefix-foreground = ${colors.foreground-alt}
format-full-underline = ${self.format-charging-underline}

ramp-capacity-0 =
ramp-capacity-1 =
ramp-capacity-2 =
ramp-capacity-foreground = ${colors.foreground-alt}

animation-charging-0 =
animation-charging-1 =
animation-charging-2 =
animation-charging-foreground = ${colors.foreground-alt}
animation-charging-framerate = 750

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60

format = <ramp> <label>
format-underline = #f50a4d
format-warn = <ramp> <label-warn>
format-warn-underline = ${self.format-underline}

label = %temperature%
label-warn = %temperature%
label-warn-foreground = ${colors.secondary}

ramp-0 =
ramp-1 =
ramp-2 =
ramp-foreground = ${colors.foreground-alt}

[module/powermenu]
type = custom/menu

label-open =  
label-open-foreground = #ffffff
label-close =  
label-close-foreground = #ffffff
label-separator = |
label-separator-foreground = ${colors.foreground-alt}
label-menu-exec = rofi -show run ; menu-open-0

menu-0-0 = 
menu-0-0-exec = i3lock -i /home/smatchcube/Pictures/portal.png
menu-0-1 = 
menu-0-1-exec = i3lock -i /home/smatchcube/Pictures/portal.png ; menu-open-0 ; systemctl suspend
menu-0-2 = 
menu-0-2-exec = menu-open-1
menu-0-3 = 
menu-0-3-exec = menu-open-2

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = confirm reboot
menu-1-1-exec = systemctl reboot

menu-2-0 = confirm power off
menu-2-0-exec = systemctl poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0

menu-3-0 = suspend
menu-3-0-exec = i3lock -i /home/smatchcube/Pictures/wood.png ; menu-close ; systemctl suspend
menu-3-1 = cancel
menu-3-1-exec = menu-open-0


; vim:ft=dosini
`

**Comment by IzacCF** [comment]
In module "[bar/example]", Insert the following lines and reset the polybar. See if it works.

;background transparent
background = #00000000

**Comment by Smatchcube** [comment]
it did't work
I'm sure the problem is from my upgrade yesterday from polybar 2.5.2-3 to polybar 3.0.3-1

**Comment by IzacCF** [comment]
My version is 3.0.3 and it works.
Weird....

**Comment by Smatchcube** [comment]
I reset the polybar config (from the polybar wiki and know i have this : http://imgur.com/a/1Dqwg
really weird

**Comment by Smatchcube** [comment]
I have the same bug with openbox so i think it's not a i3 problem.

**Comment by Smatchcube** [comment]
Here is my list of packages if it can help solve the problem : http://pastebin.com/raw/ZFVbNy7e

**Comment by Smatchcube** [comment]
I downgraded to 2.5.2 and it's work fine now.
Thanks for the help anyway. :+1:

**Comment by IzacCF** [comment]
![28 01 2017_10 52_screenshot](https://cloud.githubusercontent.com/assets/25287245/22619223/43ccad74-ead7-11e6-8230-07f1b79bd35d.png)

I love Polybar. :)

**Comment by jaagr** [comment]
Just change the vertical offset in your font declarations.
