### ISSUE TITLE
Race in xwindow token updating

### ISSUE THREAD

**Issue by Xyene** [jaagr/polybar#416]
Often when flicking through windows in i3 the xwindow display in polybar switches to "%title%". I made a gif of this below - it's usually a lot easier to reproduce, but I suspect recording the gif threw off the timings enough that it made it harder to record.

![polybar-race](https://cloud.githubusercontent.com/assets/1403503/22623287/3965d9f4-eb23-11e6-8f49-61bb3cc8b5af.gif)

I expect this likely affects all widgets, though by having lower update frequencies the issue is not visible.

I suppose the cause is the rendering occasionally happening after the call to `reset_tokens`, but before `replace_token`. I'm running a UHD-resolution display over the network, so latency probably exacerbates the problem. If this is indeed the issue, perhaps an atomic overload of `reset_tokens` that takes a mapping of token replacements could help?

Something like:
```cpp
m_label->reset_tokens({{"%title%", m_active ? m_active->title() : ""}});
```
...that performs the replacements on a temporary string before updating the label's `m_tokenized`.

I'm not overly familiar with the codebase though, so there might be an easier way to avoid the racing.

**Comment by jaagr** [comment]
I think the issue is related to all static modules because they don't lock the update mutex like the other modules do. A lock should be acquired prior to the updates.

**Comment by jaagr** [comment]
I wasn't able to reproduce the issue, but 384c12a should fix it. Please verify.

**Comment by Xyene** [comment]
Yes, that resolved it, titles no longer flicker. Thanks for the quick fix!
