### ISSUE TITLE
Void linux package

### ISSUE THREAD

**Issue by Vintodrimmer** [jaagr/polybar#417]
Hello there, can you please make a new template for Void?

It seems that `polybar` is not pulled, because `lemonbuddy` does not update to it during `xbps-install -Su`.

I think that making a new template for `lemonbuddy` that will show a message that it has been deprecated in favour of `polybar` and making `polybar` a different package altogether may fix the issue.

You can check the dialogue [here](https://github.com/voidlinux/void-packages/pull/5192#issuecomment-277514179)

**Comment by jaagr** [comment]
Do you have any experience with xbps yourself? If so, I'd gladly pass you the maintaining of the package. Getting responses from the Void repo managers is like waiting for a secret santa gift... might or might not arrive.

**Comment by Vintodrimmer** [comment]
Not yet, but there appears to be a guy currently in the dialogue that seems to be knowing what he's doing. Maybe he can do that.

**Comment by jaagr** [comment]
Closing because it's been merged.
