### ISSUE TITLE
Could NOT find PythonInterp

### ISSUE THREAD

**Issue by arivarton** [jaagr/polybar#419]
I get this error when running cmake (v3.7.2):
CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find PythonInterp: Found unsuitable version "1.4", but required
  is at least "2.7" (found /home/vidr/.pyenv/shims/python2.7)

Note that im using pyenv in combination with virtualenv.

This is my pyenv:
pyenv versions     
  system                                                            
  2.7
  2.7.13
  3.3.6
  3.3.6/envs/default
  3.4.0
  3.4.0/envs/puck
  3.4.5
  3.6.0
* default (set by /home/vidr/.pyenv/version)
  puck

**Comment by arivarton** [comment]
Uninstalled pyenv

**Comment by arivarton** [comment]
Look at my second post.

**Comment by pmatos** [comment]
Doh! @arivarton thanks!
