### ISSUE TITLE
Compton adding margin to polybar

### ISSUE THREAD

**Issue by arivarton** [jaagr/polybar#420]
This is my polybar before activating compton:
![beforecompton](https://cloud.githubusercontent.com/assets/13208468/22701804/ae3be9be-ed56-11e6-8949-f46f7d3f4ae5.png)

and after:
![aftercompton](https://cloud.githubusercontent.com/assets/13208468/22701837/bead830c-ed56-11e6-8b5b-37afd9a33eee.png)

There might be a completely obvious solution to this but i cant figure out why compton is adding that margin on the bar.

Polybar version: 3.0.4-1
Compton version: 0.1_beta2.83

**Comment by jaagr** [comment]
Are you maybe using a transparent border?

**Comment by arivarton** [comment]
This was the problem:
border-size = 4
border-color = #000000000

I had somehow set the color to 0*9, which made the border transparent..
