### ISSUE TITLE
module/wlan: Failed to query interface 'wlp6s0'

### ISSUE THREAD

**Issue by oquinena** [jaagr/polybar#422]
Hello!

I'm having some issues with displaying wlan info. It is configured as follows:

` [module/wlan] `
`  type = internal/network `
 ` interface = wlp6s0 `
`  interval = 3.0 `
  
`  format-connected = <label-connected> `
`  format-connected-underline = #9f78e1 `
`  format-disconnected-underline = ${self.format-connected-underline} `
  
`  label-connected = %essid% `
`  label-disconnected = %ifname% disconnected `
`  label-disconnected-foreground = ${colors.foreground-alt} `

ifconfig gives the following output so it is configured correctly as far as I can tell.

` wlp6s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500 `
`        inet 192.168.2.173  netmask 255.255.252.0  broadcast 192.168.3.255 `
`        inet6 fe80::ce3d:82ff:fef5:5c0d  prefixlen 64  scopeid 0x20<link> `

When starting polybar I get:
` warn: module/wlan: Failed to query interface 'wlp6s0' `
and the interface shows as disconnected..

**Comment by jaagr** [comment]
Hi, please see the comment at https://github.com/jaagr/polybar/issues/402

**Comment by oquinena** [comment]
Ahh, I see. Thanks for the reply!

**Comment by mrusme** [comment]
Subscribed to this issue as I'm also experiencing an inoperable wlan module with the latest version (3.0.4) on Gentoo. @jaagr any idea for a workaround meanwhile? Thank you. :-)

**Comment by mrusme** [comment]
Just found a temporary solution for this myself:

```ini
[module/wifi]
type = custom/script
interval = 60
exec = "nmcli d show wlp2s0 | grep 'GENERAL.CONNECTION' | awk '{ print $2 }'"
format-prefix = " "
format-prefix-foreground = ${colors.foreground}
```

This works, if you're using NetworkManager. 
@oquinena maybe this helps you as well.
