### ISSUE TITLE
Cannot compile polybar

### ISSUE THREAD

**Issue by AlessioDP** [jaagr/polybar#423]
I tried to compile polibar via setup.py.

After install all missing it fails on building:
http://pastebin.com/rwRuW5R9

Some info:
Debian jessie
Used Clang v3.5.0-10 to compile.

**Comment by jaagr** [comment]
I see that you are trying to compile old code so update the code base and try again

**Comment by AlessioDP** [comment]
Tested, same error.

I downloaded via git clone:
`git clone https://github.com/jaagr/polybar/`

Then `cd polybar/`, `sudo ./build.sg`

**Comment by jaagr** [comment]
what's the output of 

~~~
$ git describe --tags
~~~

**Comment by AlessioDP** [comment]
`3.0.4`

**Comment by jaagr** [comment]
While in the build folder, try running 

~~~
$ cmake -DWITH_XRANDR_MONITORS=0 ..
$ make
~~~

**Comment by AlessioDP** [comment]
I edited `build.sh` because i need all these parameters (to use clang else gcc).
Same error: http://pastebin.com/jJbE3qiV

code edited:
`cmake                                       \
    -DCMAKE_C_COMPILER="${cc}"                \
    -DCMAKE_CXX_COMPILER="${cxx}"             \
    -DENABLE_ALSA:BOOL="${enable_alsa}"       \
    -DENABLE_I3:BOOL="${enable_i3}"           \
    -DENABLE_MPD:BOOL="${enable_mpd}"         \
    -DENABLE_NETWORK:BOOL="${enable_network}" \
    -DENABLE_CURL:BOOL="${enable_curl}"       \
    -DBUILD_IPC_MSG:BOOL="${build_ipc_msg}"   \
    -DWITH_XRANDR_MONITORS=0                  \
    .. || msg_err "Failed to generate build... read output to get a hint of what went wrong"
`

**Comment by jaagr** [comment]
What version of clang are you using?

**Comment by AlessioDP** [comment]
`Debian clang version 3.5.0-10 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
Target: x86_64-pc-linux-gnu`

**Comment by jaagr** [comment]
Are there any more recent versions available for your distro? If so, I'd recommend upgrading and it should work fine.

**Comment by AlessioDP** [comment]
Everything is updated.
`Debian GNU/Linux 8.7 (jessie)`

**Comment by AlessioDP** [comment]
I updated gcc to latest version but I cannot compile:
```
$ cmake ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type specified; using RelWithDebInfo
CMake Error at cmake/common/utils.cmake:9 (message):
  Compiler not supported (Requires clang-3.4+ or gcc-5.1+)
Call Stack (most recent call first):
  cmake/01-core.cmake:47 (message_colored)
  CMakeLists.txt:15 (include)


-- Configuring incomplete, errors occurred!
See also "/home/adp/.i3/polybar/build/CMakeFiles/CMakeOutput.log".
```

Clang version: `3.5.0-10`
Gcc version: `6.3.0`

**Comment by jaagr** [comment]
The CXX compiler identification is GNU 4.9.2

Try to recreate the build folder

**Comment by AlessioDP** [comment]
Updated cxx too.
Same error: http://pastebin.com/jJbE3qiV

**Comment by jaagr** [comment]
> error: debug information for auto is not yet supported

This looks like a clang error. Are you sure gcc is being used?

**Comment by AlessioDP** [comment]
I edited build.sh removing clang support. (Forcing gcc use)
Now everything works :)

Conclusion:
1) Works only with gcc
2) Swap order of gcc with clang (Try to use gcc first)

**Comment by jaagr** [comment]
Clang works fine but you were using an old version. I use it myself as I prefer it to gcc

**Comment by QiangF** [comment]
@AlessioDP Can you please share your build.sh with gcc?

**Comment by AlessioDP** [comment]
@QiangF I just added:
```
cxx="g++"
cc="gcc"
```
before cmake (line 66)

**Comment by fifdick** [comment]
have the same problem...
with:
```
/tmp/polybar/build$ clang-3.8 --version
clang version 3.8.0-2ubuntu3~trusty5 (tags/RELEASE_380/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
and

```
/usr/bin/gcc-5 --version
gcc-5 (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by patrick96** [comment]
@fifdick Does compiling with gcc not work? If not, please open a new issue describing this issue and include the build log. Also consider upgrading your distro, 14.04 is end-of-life next april.
