### ISSUE TITLE
No matching input area found

### ISSUE THREAD

**Issue by nahson** [jaagr/polybar#427]
The following config
```
[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #f90000
label = "%percentage%"
click-left = "termite -e htop"
```
The click action does not work and results in `warn: No matching input area found (btn=1)`.
Clicking on other modules with internal click settings like `custom/menu` and `internal/date` works (but not using the `click-left` setting)

```
> polybar -v
polybar 3.0.4

Features: +alsa +curl +i3 +mpd +network
```

**Comment by jereksel** [comment]
Hi, AFAIK cpu module [doesn't support left click at all ](https://github.com/jaagr/polybar/blob/master/src/modules/cpu.cpp#L89), in opposite to [menu](https://github.com/jaagr/polybar/blob/826e125c803e955005edf88884bc5cc19ee1a93d/src/modules/menu.cpp#L60) and [date](https://github.com/jaagr/polybar/blob/e3a51b235a73b9da35a0d499d813be541fde15d8/src/modules/date.cpp#L74).

**Comment by jaagr** [comment]
For now you would need to use raw tags to add click handlers to modules that doens't support it. See the wiki for more details. For example:

~~~ dosini
[module/cpu]
...
label = %{A1:termite -e htop&:}CPU %percentage%%%{A}
...
~~~

**Comment by schaden-freude** [comment]
How do I format it to add both right click and left click (and possibly middle click & scroll events) to a module?

**Comment by jaagr** [comment]
`%{A1:command: A2:command: A3:command: A4:command: A5:command:}`
