### ISSUE TITLE
Can't load config file?

### ISSUE THREAD

**Issue by initzx** [jaagr/polybar#430]
I've been trying to load a custom config for polybar, but it doesn't seem to work.
![feb-14_11 20 13](https://cloud.githubusercontent.com/assets/22329742/22925082/bb170258-f2a7-11e6-90cd-05103af3dea4.png)
I am not sure if I am doing it correctly..

**Comment by alexanderdavidsen** [comment]
You need to specify which bar to run. 

Since you try to run polybar from the directory where the config is located, this should work
`polybar <barname>`.

**Comment by initzx** [comment]
![feb-14_15 05 43](https://cloud.githubusercontent.com/assets/22329742/22932186/333a8772-f2c7-11e6-85cd-271dcb411a7c.png)
i get an error when i try to do that

**Comment by israelss** [comment]
In config file, what's the bar name? That's the name you should provide to polybar. E.g., if you have in config file:
```
...
[bar/mybar]
...
```
You should invoke it like
`polybar mybar -c config`

**Comment by initzx** [comment]
ah, thank you. Do you have any dotfiles that i can use?

**Comment by israelss** [comment]
I'm procrastinating like hell to upload my dotfiles, but you can look at a very recent version of my polybar config [here](https://github.com/jaagr/polybar/issues/377#issue-203199686). :)
Please, note that I use some custom scripts, so if you want any of those, contact me through the [email](mailto:israel.santanna@gmail.com) in [my profile](https://github.com/israelss).
