### ISSUE TITLE
Custom pomodoro timer module

### ISSUE THREAD

**Issue by marco9333** [jaagr/polybar#431]
Recently I've started to use the "pomodoro" technique and I though that having a timer/indicator on the bar was the best. I've found a python script on  https://github.com/dattanchu/pymodoro that is suitable for bar printing so I've written a little module in my config to interface with that script. Left click starts/stops the timer, right click reduces the time in each interval and middle click increases it. Thought to share it, maybe someone can find this useful.

```
[module/pomodoro]
type = custom/script
; Use pomodoro glyphs in Nerd fonts
; exec = pymodoro --break-prefix " " --pomodoro-prefix " " --pomodoro  --empty  --break  --length 5
; Use default symbols
exec = pymodoro --length 5e
label = %output%
tail = true
interval = 0
; Start or reset the timer
click-left = if [ -e ~/.pomodoro_session ]; then rm ~/.pomodoro_session; else echo "25 5" ~/.pomodoro_session; fi
; Increase pomodoro time
click-right = echo "$((`cut .pomodoro_session -d ' ' -f 1`+5)) 5" > .pomodoro_session
; Reduce pomodoro time
click-middle = echo "$((`cut .pomodoro_session -d ' ' -f 1`-5)) 5" > .pomodoro_session
```

**Comment by israelss** [comment]
Cool! Have you considered include it on [User contributed modules section](https://github.com/jaagr/polybar/wiki/User-contributed-modules) of wiki?

**Comment by marco9333** [comment]
Now I see I can edit it directly. I'll do it 😄

**Comment by Traivok** [comment]
How do i set font for this?
I have nerd-fonts-complete installed, but the icons aren't visible.
