### ISSUE TITLE
xbacklight and battery module error

### ISSUE THREAD

**Issue by initzx** [jaagr/polybar#432]
Hello, I keep getting these two errors below
`error: module/xbacklight: Could not get data (err: XCB_NAME (15))`
`error: Disabling module "xbacklight" (reason: Not supported for "eDP-1")`
`error: Disabling module "battery" (reason: No suitable way to get current charge state)`

and the corresponding modules.
![feb-14_18 25 20](https://cloud.githubusercontent.com/assets/22329742/22940716/3802eddc-f2e3-11e6-983b-06252f762c3a.png)
![feb-14_18 25 53](https://cloud.githubusercontent.com/assets/22329742/22940723/3b9b71b2-f2e3-11e6-8b31-b33ba1805c9e.png)

**Comment by jaagr** [comment]
In short: your system is not supported. I'd recommend using custom script modules to get/set the data.

**Comment by initzx** [comment]
any idea on how i can make it work with polybar, than having to write a script?

**Comment by initzx** [comment]
UPDATE: The battery i've set the battery variable to was wrong! It was BAT1 instead of BAT0. Now i just need to fix the backlighting issue.

**Comment by jaagr** [comment]
For the backlight you could try the legacy module `internal/backlight` because xbacklight only works with some video drivers

**Comment by initzx** [comment]
ah ty, that fixed it :smile:

**Comment by PeterlitsZo** [comment]
> UPDATE: The battery i've set the battery variable to was wrong! It was BAT1 instead of BAT0. Now i just need to fix the backlighting issue.

I think it works: use `upower -e` and the output may have `battery_BATX`, then use `BATX` instead of `BAT0`
