### ISSUE TITLE
error: Disabling module "temperature"

### ISSUE THREAD

**Issue by oussoudreamer** [jaagr/polybar#437]
error: Disabling module "temperature" 
(reason: The file '**/sys/class/thermal/thermal_zone0/temp**' does not exist)
i don't have the temperature file** temp **instead i have it in "**/sys/devices/platform/coretemp.0/hwmon/hwmon0/temp2_input**"
and this is the output of the file (cat **temp2_input**):
**33000**

here is pictures
![2017-02-15-134923_1440x900_scrot](https://cloud.githubusercontent.com/assets/16356449/22973321/801dcb6a-f37d-11e6-8217-7930589851e4.png)
![2017-02-15-134930_1440x900_scrot](https://cloud.githubusercontent.com/assets/16356449/22973313/7a06b642-f37d-11e6-81d0-4d4cb7ca894e.png)

**Comment by jaagr** [comment]
I would recommend writing your own script module to report the temp value.

**Comment by oussoudreamer** [comment]
how to do that ?

**Comment by oussoudreamer** [comment]
**Fixed** 
https://github.com/jaagr/polybar/wiki/User-contributed-modules#per-core-temperatures
