### ISSUE TITLE
Bar freezes when script is executed

### ISSUE THREAD

**Issue by onurhaan** [jaagr/polybar#438]
Hi,
I have written a script that shows me how many updates I have and executes 'pacman -Syu' when I click on it. It works fine but when I click and continue with the update, the bar freezes, when the script is over it goes back to normal. How to fix this? Thanks.

**Comment by jaagr** [comment]
Add `&` after the click command

**Comment by onurhaan** [comment]
It worked. Thanks ! Great stuff by the way.

**Comment by jaagr** [comment]
Thanks
