### ISSUE TITLE
How to make font better visible on different backgrounds?

### ISSUE THREAD

**Issue by Trollwut** [jaagr/polybar#439]
Hi folks!

I love that bar. The only thing is, that I either have black or white font-color, depending on my wallpaper.

I use a transparent bar, so I would have to switch font-color, if the background isn't fitting to the font. Is there any possibility to make that font better read-able?

E.g. a black "shadow" or outline? Automatic coloring depending on the background?

**Comment by jaagr** [comment]
Experiment with the foreground color blending mode that can be changed like this:

~~~ dosini
[settings]
compositing-foreground = xor
~~~

A list of valid values can be found here: https://github.com/jaagr/polybar/blob/master/src/cairo/utils.cpp#L57

**Comment by Trollwut** [comment]
Either blending or something like an outline/shadow. :-)

It's not the biggest problem, as I can simply edit white wallpapers to have a transitioning to the top (where my bar is). Would just be a nice feature.

**Comment by jaagr** [comment]
In case you didn't know it's possible to make the bar have a gradient background that fades from a color to transparent.

**Comment by Trollwut** [comment]
Any example out there? So I don't have to edit my wallpapers in case of emergency. :-)

**Comment by jaagr** [comment]
Add this to your bar section and adjust the color code to match your background.

~~~ dosini
[bar/mybar]
background-0 = #ff555555
background-1 = #00555555
~~~

**Comment by Trollwut** [comment]
Works, thanks mate!

**Comment by NBonaparte** [comment]
Closing because the issue has been resolved.
