### ISSUE TITLE
Update colors based on script output

### ISSUE THREAD

**Issue by Fabianoshz** [jaagr/polybar#443]
I've created a script to show my Elasticbeanstalk environment status color, 2xx requests and 5xx requests, so far, so good, but, i would like to change the font color based on the status color instead of just printing it on the bar. 

This is how my bar is right now:
![screen_2017-02-17_11-02-35](https://cloud.githubusercontent.com/assets/14815404/23066325/25b3bf2e-f501-11e6-95e3-ea1c53c58b29.png)

I couldn't find any info about it here: https://github.com/jaagr/polybar/wiki/Module:-script

So, am i searching it wrong, or the bar don't have this function? If it don't, would be too much trouble to add it? I could easily return the color code, i could wrap the string with special characters too, maybe a tag to show the desired color, but this would help a lot!

Great software by the way, i'm really enjoying it!

**Comment by Fabianoshz** [comment]
OMG, i just found it!

Decided to see if someone else already tried this and found: https://github.com/jaagr/polybar/wiki/User-contributed-modules#redshift.

**Comment by TrakJohnson** [comment]
For future reference (link dead), you can put the colour (like [this](https://github.com/jaagr/polybar/wiki/Formatting#foreground-color-f)) tag in the string that the script echoes, just like you'd do in the config file.
