### ISSUE TITLE
Enhancement: radius-top / radius-bottom

### ISSUE THREAD

**Issue by mrusme** [jaagr/polybar#445]
It would be very cool to be able to set the radius for the top and/or bottom two corners individually. Something like:

```ini
radius-top = 5.0
radius-bottom = 0.0
```

**Comment by jaagr** [comment]
Hi @mrusme 

I've added individual value properties for top and bottom radius. To control both the `radius` parameter can be used.

**Comment by mrusme** [comment]
@jaagr you're awesome, thanks man! Going to test it this weekend. 👍
