### ISSUE TITLE
Can polybar draw borders/lines ?

### ISSUE THREAD

**Issue by neg-serg** [jaagr/polybar#451]
I've looking for polybar feature to separate polybar window from another. Is there some possibilities with it? For example with dzen2 you can to draw lines explicitly. 

Polybar, as I understanded, have similar feature as overline(?). Underline works best, does overline put some "tiny rectangle" at top when your bar at bottom. I mean global underline/powerline through all bar width. Is that possible? By the way yabar have this feature(borders, etc) but it's too buggy for now.

**Comment by neg-serg** [comment]
I've tried to emulate it with following snippet:
```
[bar/tiny]
bottom=true

width = 100%
height = 2

padding-left  = 0
padding-right = 0
module-margin-right = 0
module-margin-left  = 0

modules-left = hack
modules-center = hack
modules-right = hack

background = #ff287373
foreground = #ff287373
underline-size = 2
underline-color = ${colors.white}

font-0 = fixed

[module/hack]
type = custom/text
content = -----------------
````

But it's ugly, is there something more nice?

Or maybe you give me a hint how to make a patch for it?

**Comment by jaagr** [comment]
Use the border properties. Excerpt from the wiki:

~~~dosini
; Values applied to all borders
; Individual side values can be defined using:
;   border-{left,top,right,bottom}-size
;   border-{left,top,right,bottom}-color
border-size =
border-color =
~~~
