### ISSUE TITLE
Radius option to have round backgrounds in the i3 module?

### ISSUE THREAD

**Issue by Trollwut** [jaagr/polybar#453]
Hi folks!

Is there a possibility to have a roundes background on the workspace names of the i3 module?

E.g. to not have a rectangled background [like here](http://i.imgur.com/pmtHCzq.png), but a pill-shaped one?

**Comment by jaagr** [comment]
Hi, this is currently not supported.

**Comment by Trollwut** [comment]
Thanks for your response! :-)

**Comment by marciniuk** [comment]
Hey, any new news? Can it be done now? I hope so ;P
