### ISSUE TITLE
Consider network link state UNKNOWN as UP

### ISSUE THREAD

**Issue by qgnox** [jaagr/polybar#457]
Hi, this is a feature request, when I use usb modems / or tethering via usb the state of the interface appears  as UNKNOWN, even trying to put it up with "ip link set" doesnt change the state but the interface works : 

`enp0s20u1: <BROADCAST,MULTICAST,DYNAMIC,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
`

So maybe a property true/false for network module "unknown-as-up" could be useful.

**Comment by patrick96** [comment]
@NBonaparte are your changes ready for a PR?

**Comment by NBonaparte** [comment]
I think it is, haven't touched it in a while though.
