### ISSUE TITLE
System tray icons glitch

### ISSUE THREAD

**Issue by lundibundi** [jaagr/polybar#459]
When I restart i3-gaps with its internal restart command (i3-msg restart or appropriate) icons in tray of some apps seems to break, their background becomes black or filled with garbage (see screenshots). If I restart the apps the icons come back to normal. Apps on screenshots are [telegram](https://aur.archlinux.org/packages/telegram-desktop-bin/) and [copyq](https://aur.archlinux.org/packages/copyq/). Btw from what I know those 2 are QT apps while others are GTK ones, maybe this hepls somehow. 

![deepinscreenshot20170224115630](https://cloud.githubusercontent.com/assets/9109612/23299019/958c16d4-fa88-11e6-8763-a0af4bb7af1e.png)
![deepinscreenshot20170224115322](https://cloud.githubusercontent.com/assets/9109612/23299021/958debe4-fa88-11e6-8aee-edf25f5f4874.png)
![deepinscreenshot20170224115248](https://cloud.githubusercontent.com/assets/9109612/23299020/958daec2-fa88-11e6-9218-0ec5261cbe27.png)

My system: 
```
Linux zou 4.9.8-1-ARCH #1 SMP PREEMPT Mon Feb 6 12:59:40 CET 2017 x86_64 GNU/Linux
```
```
i3 version 4.13-91-gb03412df (2017-01-25, branch "gaps-next") © 2009 Michael Stapelberg and contributors
```
```
polybar 3.0.4
Features: +alsa +curl +i3 +mpd +network
```
[polybar config](https://github.com/lundibundi/dotfiles/blob/master/.config/polybar/config)

**Comment by IzacCF** [comment]
This is an i3 systray problem. This was already happening before using polybar, at least here.

**Comment by lundibundi** [comment]
@IzacCF yeah, thanks. I have just checked and it's the same with i3blocks.
