### ISSUE TITLE
Systray already managed 

### ISSUE THREAD

**Issue by MMR-Burhan** [jaagr/polybar#460]
When I run `polybar -c .config/polybar/config Bar --log=info`
I see 
`warn: Systray selection already managed (window=0x1000009)`
and no indicator icons.
How do I make that work?
`i3 gaps 4.13 && 4.9.11-1-ARCH`

**Comment by jereksel** [comment]
Are you using stock i3 bar along with polybar? There can be only 1 bar with systray.

**Comment by MMR-Burhan** [comment]
I was not using i3bar. But was using two polybars with tray . That was the reason.
