### ISSUE TITLE
No tray icon on i3

### ISSUE THREAD

**Issue by toketin** [jaagr/polybar#467]
Hi, i'm using since two days this great bar, i switched from i3status, but i've an issue since i can't get its tray working. I don't see any tray icon, on my config file i've set this options:

    tray-detached = false
    tray-position = right
    tray-padding = 2

What should i do in order to get it working?
P.s. I've added **status_command polybar Bar** on my .i3/config file in order to load Polybar on i3's startup.
Thanks!
Marco

**Comment by jaagr** [comment]
Hi.

Polybar doesn't work with i3bar, so replace the bar section with:

~~~
exec_always --no-startup-id polybar Bar
~~~

**Comment by toketin** [comment]
Ok thanks fixed it, great work for this bar man thanks!
