### ISSUE TITLE
Tray completely broken on openbox

### ISSUE THREAD

**Issue by jp1995** [jaagr/polybar#468]
Alright, I know openbox isn't officially supported, so if this problem is a direct result of that then feel free to close, I just thought I'd ask to be sure.

`error: Failed to setup tray client, removing... (XCB_WINDOW (3))`

This is what I get when I attempt to open an app that would go to the systray. Sometimes an app still has its icon displayed, but it's halfway out of the screen, or it draws over the module next to it. Other times, the icon gets drawn _on the opposite end of my other monitor._ 

I'm also using tint2 but I've disabled the systray there so it shouldn't conflict. 

I've just installed polybar and I've gone through the wiki but maybe I missed something obvious.

Thanks!

**Comment by jaagr** [comment]
I have no experience with openbox myself so not sure how I can help you debug it. Could you post the bar section of your polybar config?

**Comment by jp1995** [comment]
```
[bar/bar]
monitor = DVI-0
bottom = false
width = 1100
height = 25

enable-ipc = true

padding-left = 0
padding-right = 10
offset-x = 850
offset-y = 0

module-margin-right = 2
module-margin-left = 1

modules-right = volume mpd pkg temps weather clock

background = ${colors.background}
foreground = ${colors.foreground}

underline-size = 4
underline-color = ${colors.magenta}

tray-detached = true
tray-position = right
tray-offset-x = 0
tray-offset-y = 0
tray-maxsize = 16
tray-padding = 0

font-0 = "DejaVuSans:size=9;0"
font-1 = "FontAwesome:size=10;0"
font-2 = "Cousine:size=8;0"
font-3 = "Artwiz Lemon:size=10;0"
font-4 = "Roboto:size=4;0"
font-5 = "xos4 Terminus:size=10;0"
```

I've tried tray-detached = false and different tray positions but neither changed anything. I got the config file from a guy who runs bspwm so it's probably just openbox acting up. Not sure.

**Comment by jaagr** [comment]
Have you tried several apps with tray support or is it one specific?

> ...or it draws over the module next to it.
This is because you are using `tray-detached = true`. The property makes the bar skip space reservation.

**Comment by jp1995** [comment]
I've a handful of apps that I've tried. Dropbox, Skype, Steam, streamlink-twitch-gui, volumeicon. Gonna go step by step explaining what I load first and what happens. 

Dropbox gets loaded automatically on boot, but the icon is not displayed. Then I start Skype, and it gets drawn. ~~Half of the icon is outside the screen,~~ (this was my fault, regarding bar position) but after `tray-detached = false` it no longer draws over the previous module. Now suddenly dropbox is displayed, except it's in a rather undesireable location (see pic below). I launch volumeicon, it gets drawn fine next to skype. Steam gets drawn fine next to volumeicon. Dropbox still in the same place. Can't get streamlink-twitch-gui to get it's icon to show no matter what.

[Picture of my setup. ](https://i.imgur.com/EdZQ1iI.png) Ignore the white 1px line, it's an artifact from the screenshot tool. As you can see I'm using polybar alongside tint2, and the dropbox icon is on the far left.

If I put polybar on my other monitor (HDMI-0), the dropbox icon remains in the same position.

[When I close all the previously mentioned apps, then the dropbox icon moves all the way to the left](https://i.imgur.com/ScaYOpL.png)

This is so weird.

**Comment by jaagr** [comment]
What if you set the bar property:

~~~ dosini
override-redirect = true
~~~

**Comment by jp1995** [comment]
Um. I did try that before and nothing happened. Now it fixed everything though, thank you so much! 

As a quick side question, there's no way to put the tray between any given modules, is there?

**Comment by jaagr** [comment]
Great! Not yet, but I've started to move the tray functionality into a separate module.
