### ISSUE TITLE
empty modules & font config 

### ISSUE THREAD

**Issue by borysn** [jaagr/polybar#470]
I'm trying to setup polybar 3.0.4 with a font config as such...

```
font-0 = "Noto Sans:pixelsize=12;1"
font-1 = "Ionicons:pixelsize=12;0"
```

but it seems the only way my modules render is if i use the `fixed` font very specifically for `font-0`, but then ionicons still does not load. 

is this a known issue, or am i doing something wrong here? using `FC_DEBUG=1` everything seems to be going fine. running polybar with `--log=info` seems to be fine as well. the only warning i see is `moduel/wlan: Failed to query interface...`, but i know that's expected because of the transition away from `wireless_tools`

**Comment by jaagr** [comment]
What happens if you replace `pixelsize` with `size`?

**Comment by jaagr** [comment]
Other than that I would check the fontconfig env (usually `/etc/fonts/conf.d`)

**Comment by borysn** [comment]
@jaagr ahh yess, thank you. changing to size works just fine.

**Comment by jaagr** [comment]
Great! I'll try to remember to add that to the wiki. Tricky one to figure out.
