### ISSUE TITLE
Looking for astronaut pixel art wallpaper from screenshots in readme

### ISSUE THREAD

**Issue by Probotect0r** [jaagr/polybar#473]
Sorry, not an issue, but I have been looking everywhere for that Astronaut surfer wallpaper from the screen shots in the readme. If anyone has it, could you please point me to where I can get it? Thanks!

**Comment by RaySSharma** [comment]
I think this is the same one, but the colors are a little off: https://alpha.wallhaven.cc/wallpaper/278397

**Comment by Probotect0r** [comment]
Awesome thanks!
