### ISSUE TITLE
void template version bump

### ISSUE THREAD

**Issue by Vintodrimmer** [jaagr/polybar#476]
Good day.

Can you bump void template to the current version?

Also, if I want to do it myself, I need only to change the version in the template, right?
I'm not sure where to look for the appropriate `_xpp_version`. 

And one last question, it says that 

`srcpkgs/polybar/template: line 13: vopt_if: command not found`

Is it part of some package I should get?

**Comment by jaagr** [comment]
Hi

You would need to change the version and the sha256 hash (I usually just bump the version, try to package it and then copy the hash printed to stderr on failure). The xpp version that is used can be found in `.gitmodules`. 

The `vopt_if` command should be part of `xbps` unless they recently removed or changed it.

**Comment by Vintodrimmer** [comment]
Thanks, it worked!
