### ISSUE TITLE
Is there a way to center the text in polybar vertically?

### ISSUE THREAD

**Issue by hahuang65** [jaagr/polybar#478]
I removed all `underline`s from my configuration but it seems like polybar likes to leave space for underlining. Is there any way I can get my text to be centered vertically in the space?

**Comment by NBonaparte** [comment]
AFAIK the only way to do this is to define a vertical offset manually: `font-N = <fontconfig pattern>;<vertical offset>`.

**Comment by hahuang65** [comment]
Beautiful, works just fine for me!

**Comment by jeremejevs** [comment]
Would be nice if bar sides could have independent lines (e.g. i3 workspaces get underlines, while all the other modules don't).

**Comment by jaagr** [comment]
@jeremejevs that's already possible.

**Comment by jeremejevs** [comment]
@jaagr Do you mean simply commenting out all lines with `*-underline`? That's the thing, the text remains shifted, as if the line was still there but just transparent. [`fill_underline`](https://github.com/jaagr/polybar/blob/9a7258468079a95c8a59b342b07aa04dadefac60/src/components/renderer.cpp#L508) seems to ignore module-level `*-underline-size` and uses global underline size instead, unless I'm misinterpreting the code.

The desired result would be where I could have, say, workspace indicators on the left of my bar with underlines, and then the rest of the modules on the right of my bar without underlines, and all vertical spacings looking about right, without having to use a separate font configuration for one of the sides (though that's, admittedly, a very minor inconvenience).

**Comment by Hitomi98** [comment]
> AFAIK the only way to do this is to define a vertical offset manually: `font-N = <fontconfig pattern>;<vertical offset>`.

can you explain this? my current font config looks like this:
`font-0 = Monospace:style=Regular:size=10`
but it looks like this 
![image](https://user-images.githubusercontent.com/55341971/79031011-10649b00-7b6a-11ea-9ae8-46738daae051.png)
when active, I'd like to move the text down by a few pixels to center it

**Comment by patrick96** [comment]
@Hitomi98 

```
 font-0 = Monospace:style=Regular:size=10;2
```

**Comment by Pratham82** [comment]
Thanks @patrick96 I was also having issue with vertically aliging the text this solves it.

**Comment by ProgramAlchemist** [comment]
Thanks! "2" is the key

> @Hitomi98
> 
> ```
>  font-0 = Monospace:style=Regular:size=10;2
> ```
