### ISSUE TITLE
improve polybar launching

### ISSUE THREAD

**Issue by aleprovencio** [jaagr/polybar#479]
Hello, first of all thanks for your awesome project!

IMHO, I would like to propose a better way of launching polybar:

1) Sometimes I do WM-hopping between i3 and bspwm, so my `polybar/config` have both (i3 and bspwm) modules configured to show, just like the example config. However for it to detect correctly which WM I'm currently on (and which module to use), I have to launch polybar from the configuration file of each WM. As other apps, I think its more clever to call polybar from `xinitrc` so there's no need to have calls on both WM config files, but for that to happen, polybar would have to include some sort of auto-detection mechanism.

2) As polybar seems to avoid shellscripts for all its configuration, why does it encourage users to create a `launch.sh` script? I mean, wouldn't it be easier to have that logic already built-in?

**Comment by jaagr** [comment]
Hi and thank you!

Please submit a PR if you have an idea on how to improve the launch. The main reason for having the shellscript snippet in the wiki was because of the process killing. I rarely do any WM-hopping so I haven't seen the issue of it myself.

**Comment by jtpavlock** [comment]
I managed a workaround to launch in xinitrc by doing something like

> (sleep 10; $HOME/.config/polybar/launch) &

**Comment by Clyybber** [comment]
I think its better to include polybar in both wm config files, rather than reworking the launch process(which is atm pretty straigth forward and clean). Also it wouldnt be good practice to call polybar from xinitrc, since some WMs include a bar out of the box.
