### ISSUE TITLE
label-focused-underline not working

### ISSUE THREAD

**Issue by Capuno** [jaagr/polybar#480]
Was working in previous versions, can't tell what commit caused it

![image](https://cloud.githubusercontent.com/assets/18151803/23826577/e8f35fb8-069e-11e7-8ca9-030d6c3bd02c.png)

**Comment by jaagr** [comment]
I can't reproduce the issue. Could you post your full config

**Comment by Capuno** [comment]
https://hastebin.com/ocipaxeqov.bash

**Comment by jaagr** [comment]
Replace 

~~~ dosini
lineheight = 2
~~~

with

~~~ dosini
line-size = 2
~~~
