### ISSUE TITLE
error: module/mpd: Connection refused and no label is displayed on the bar

### ISSUE THREAD

**Issue by xPrzybyLx** [jaagr/polybar#485]
When mpd is not running (there is no such process) this message appears :

`error: module/mpd: Connection refused`

And nothing is displayed on the bar even when I have this defined in the config :

To my understanding this should display "Off" in the bar...

```
[module/mpd]
type = internal/mpd

host = 127.0.0.1
port = 6600
password = 
interval = 5
format-online =    <label-song>
label-song = %artist% - %title%
format-online-padding = 10
format-online-foreground = #44ffffff
label-offline = Off
format-offline-padding = 10
format-offline-foreground = #00ff0000
```

**Comment by hschreck** [comment]
Are you able to connect to MPD using other clients and the same settings?

**Comment by jaagr** [comment]
You would need to define the offline format that is used when there's no connection, like this:

~~~ dosini
format-offline = <label-offline>
~~~
