### ISSUE TITLE
Polybar is often completely invisble

### ISSUE THREAD

**Issue by rieje** [jaagr/polybar#486]
My polybar is often completely invisible, as seen [here](http://imgur.com/a/wlmjS). I'm not exactly sure what causes it to be completely invisible at times, but to temporarily fix it, I have to restart polybar. My [compton config](http://pastebin.com/564AxWEd). I'm using the latest version of polybar and compton on Arch and this problem has existed for nearly a month now (I haven't touched the posted compton config for ~1 month). `tray-transparent = true` is commented out in my polybar config.

**Comment by lyu** [comment]
Can confirm this. I am also using the latest release (3.0.4) on archlinux with bspwm, but without compton. The problem has been here for quite some time.

I believe that the xwindow module is the source of the problem, it some how crashes the display of the bar when some characters are displayed in a window's title. For example, this [link](https://gom.wikipedia.org/wiki/%E0%A4%85%E0%A4%AE%E0%A5%87%E0%A4%B0%E0%A4%BF%E0%A4%95%E0%A5%87%E0%A4%9A%E0%A5%80%E0%A4%82_%E0%A4%B8%E0%A4%82%E0%A4%AF%E0%A5%81%E0%A4%95%E0%A5%8D%E0%A4%A4_%E0%A4%B8%E0%A4%82%E0%A4%B8%E0%A5%8D%E0%A4%A5%E0%A4%BE%E0%A4%A8%E0%A4%BE) from wikipedia make my bar disappear immediately, although I have noto-fonts installed and firefox displays every character in this page correctly, and I have set polybar to also use the noto fonts. @rieje any chance you are also using the xwindow module? Can you test this?

**Comment by jaagr** [comment]
@Iyu do the process crash?

**Comment by lyu** [comment]
@jaagr nope

**Comment by skystrife** [comment]
Possible dupe of #393? Can you see if you can reproduce this with the most recent git version?

**Comment by lyu** [comment]
@skystrife Okay the latest git version does not have this problem, using either the`label-maxlen` option or the `:0:30:...` way. The characters in the title bar of the wikipedia page still does not show up and the error messages are still being printed to the console, but I guess I can live with that.

**Comment by skystrife** [comment]
Might need to directly specify the font that has that glyph from the Noto Sans collection. In this case I think it's "Noto Sans Devanagari". `polybar` doesn't do automatic font fallback, so if no font in your font list is found that contains a certain glyph, it just skips it.

**Comment by rieje** [comment]
From these comments, I just did some quick tests and when I have a Youtube video with a different language like Chinese as the title, the polybar became invisible. Otherwise, it's not invisible. I installed polybar-git from the AUR and it seems to fix it for me as far as transparency goes, but xwindow's title removes all the Chinese characters from the title.

**Comment by Plasticoo** [comment]
Same happens to me. And the problem must be in xwindow module.

To reproduce the problem I just need to open some music files in mpv, and select the next songs very fast to make the title change fast too.

**Comment by jaagr** [comment]
For users that still experience this issue, could you post the output of `polybar -v`

**Comment by Plasticoo** [comment]
Indeed!

Here is mine:

```
λ  ~ polybar -v
polybar 3.0.4

Features: +alsa +curl +i3 +mpd +network
```

**Comment by jaagr** [comment]
@Plasticoo thank you, could you post your polybar configuration?

**Comment by Plasticoo** [comment]
@jaagr Yes indeed!

Here: https://gist.github.com/Plasticoo/ee9c37b4e001be1459dce71031cf43a1

**Comment by jaagr** [comment]
@Plasticoo I'm not able to reproduce the issue. Is the process still running for you when it disappears?

**Comment by Plasticoo** [comment]
@jaagr Yes it is. The process still runs.

**Comment by jaagr** [comment]
@Plasticoo OK, I'll keep trying to reproduce it then.

**Comment by Plasticoo** [comment]
@jaagr Maybe you can tell me exactly how you're doing it. I find odd the fact that you cannot reproduce the issue with the directives I gave you.

**Comment by jaagr** [comment]
1. Installed the same fonts 
2. Copied your config
3. Copied a random mp3 and changed its tags to look like the examples you supplied
4. Launched mpv with the copies
5. Pressed the next/prev keys repeatedly.

**Comment by Plasticoo** [comment]
@jaagr Sorry for being late.

I went on my Linux machine and I can give you new information.

I tried 3 different scenarios.

1. Pressing next/prev keys repeatedly in a directory with music whose tags have normal characters. Polybar functioned normally.

2. Pressing next/prev keys repeatedly in a directory with music whose tags have normal characters, plus a song in there with special characters (japanese). Polybar functioned normally.

3. Pressing next/prev keys repeatedly in a directory full of music whose tags have all special characters. Polybar disappeared.

So maybe you should try with *multiple* mp3 files like that. I can actually give you the bandcamp link for the download of an album like that:

https://cvltvre.bandcamp.com/album/virtual-life

**Comment by jaagr** [comment]
@Plasticoo thanks, I'll try that out as soon as I get some time.

**Comment by jaagr** [comment]
@Plasticoo [this screencast](https://u.teknik.io/qJtfE.webm) shows your config on the external monitor (the upper area) while I keep changing songs from the album you linked... still can't get the bar to disappear.

Didn't bother to crop the recording so just ignore the other bloat.

**Comment by Plasticoo** [comment]
@jaagr Well, is there some way I can do a screencast like yours, so I can show you how exactly it happens?

**Comment by jaagr** [comment]
@Plasticoo [the script I'm using can be found here](http://twily.info/s/scripts/screencast)

**Comment by Plasticoo** [comment]
Well, I must start by apologizing. I tried that album that I sent the link to you. But did not work. Tried another one, and the problem persists, it is most likely a very strange character(?). The one i tried is:

https://cvltvre.bandcamp.com/album/upscale-loft

Also, here is [my screencast.](https://u.teknik.io/o06he.webm) (Sorry for the screen, I dunno why it recorded this way).

**Comment by jaagr** [comment]
@Plasticoo I just checked the git log and the issue should actually be fixed, but I just realized that I haven't created a new release tag since it was committed. Let me bump the version so that you can update polybar.

**Comment by jaagr** [comment]
@Plasticoo try updating the package (just created a new tag 4e2e2a7a5e0fe81669031ade0f60e1d379b6516d), sorry for the inconvenience

**Comment by Plasticoo** [comment]
@jaagr I updated, and I tried all the scenarios mentioned here in this issue and it seems fixed! At least for me, maybe the OP, @rieje, could say something about it too!

Thanks for your availability!

**Comment by jaagr** [comment]
@Plasticoo that's great! Props to @skystrife for fixing it. Please close the issue if it's resolved on your end @rieje.

**Comment by rieje** [comment]
@jaagr unfortunately, I still have this issue. See [screenshot](http://imgur.com/a/RzQ2I). To be clear, I'm not having the invisible bar anymore, but the xwindow title does not show the correct title.

**Comment by rieje** [comment]
I installed a Chinese font when I installed Arch because I had blocks with numbers shown instead on Firefox and that fixed it, so I don't think that's an issue. On terminal and other applications there isn't an issue with Chinese characters.

**Comment by TonCherAmi** [comment]
@rieje in my experience you need to explicitly specify that font in the config or it will not work.

**Comment by rieje** [comment]
@TonCherAmi In the polybar config? I installed the package wqy-microhei on Arch for the font. Then `fc-list | grep -i "wqy"` returned:

    /usr/share/fonts/wenquanyi/wqy-microhei/wqy-microhei.ttc: WenQuanYi Micro Hei,文泉驛微米黑,文泉驿微米黑:style=Regular
    /usr/share/fonts/wenquanyi/wqy-microhei/wqy-microhei.ttc: WenQuanYi Micro Hei Mono,文泉驛等寬微米黑,文泉驿等宽微米黑:style=Regular

so I think I think I'm supposed to use the setting for the polybar config:
    font-0 = WenQuanYi Micro Hei Mono Regular:pixelsize=9;3

But it didn't seem to change anything.

**Comment by TonCherAmi** [comment]
@rieje, try `font-0 = WenQuanYi Micro Hei Mono:pixelsize=9;3`. I believe `Regular` is not a part of the font's name.

**Comment by rieje** [comment]
@TonCherAmi That works! I thought `Regular` in `style=Regular` needed to be specified. Thanks a lot.

**Comment by Phundrak** [comment]
Hello, I’m bringing this thread back to life as I have about the same issue with Japanese characters, but it’s way more specific: I can reproduce the bug only if I launch music containing Japanese characters in mpd/ncmpcpp in uxterm, going to another window and then coming back. Sometimes the bug appears immediately. I tried doing the same with gnome-terminal, and polybar works fine as well as any other software, so I guess the issue is from uxterm’s output to the xwindow module specificaly. The output indicates it drops the unmatched U+0003 and U+0005 characters, though last time I tried to reproduce the error it only dropped the unmatched character U+0003.

Here is the output of `polybar -vv` : 
```
polybar 3.0.5-git

Features: +alsa +curl +i3 -mpd +network

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm

Build type: RelWithDebInfo
Compiler: /usr/bin/clang++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

[My config file](https://github.com/Phundrak/dotfiles/blob/5deb8c82ac36ca85c5c9f237149505490981f63a/.config/polybar/config) (you have also access to my other dotfiles through this link if you need to)

**Comment by patrick96** [comment]
Hi @Phundrak, please don't post on a thread that has been closed for over half a year. Open a new issue instead, there we'll be able to help you better.
When opening the new issue, please also provide the full polybar log when run with `-l info`
