### ISSUE TITLE
firefox notification crashes polybar

### ISSUE THREAD

**Issue by borysn** [jaagr/polybar#487]
Having a difficult time identifying an issue. When using firefox-51.0.2 (with pushbullet plugin) on my latest gentoo install, i now get a push count notification icon on polybar (just like the steam icon). Whenever this icon shows up polybar crashes. Well, after the icon is either just sitting there for a bit, or if i click the icon and try to clear the notifications. I'm assuming when it's just sitting there it has it's own timeout to clear the icon, so it crashes just like when clicking the icon and hitting clear notifications.

here's an info log output of the crash

```
(normal startup)
...
(normal run procedure)
...
polybar|info:  module/temperature: Rebuilding cache
polybar|info:  Redrawing bar window
polybar|info:  module/cmus: Invoking shell command: "zscroll "$(cat /home/p3pt/.tmp/now-playing)""
polybar|info:  module/wlan: Invoking shell command: "nmcli d show wlp0s26u1u3 | grep 'GENERAL.CONNECTION' | awk '{print $2}'"
...
(crash with push bullet notification in icon tray)

polybar|info:  Redraw tray container (id=0x3600005)
terminate called after throwing an instance of 'xpp::x::error::window'
  what():  XCB_WINDOW (3)
[1]+  Aborted                 (core dumped) polybar -l info -c .config/i3/polybar/topbar.ini topbar &> polybarlog
```

**Comment by jaagr** [comment]
This can be fixed by catching the exception in the tray manager.

**Comment by jaagr** [comment]
Could you verify if the referenced commit fixes the issue

**Comment by borysn** [comment]
@jaagr, the push bullet notification still crashes firefox

**Comment by borysn** [comment]
@jaagr i can try to be a little more useful here. let me see if i can get a debug environment up and running for polybar. that way i can just keep pushing myself notifications and try to figure this out. it's been some time since i've debugged a cpp app, but i should be able to figure it out lol

**Comment by jaagr** [comment]
Launch it using `gdb`

~~~ sh
$ gdb -ex run -args polybar mybar
~~~

and when it crashes, get the stack trace by typing `bt`

**Comment by borysn** [comment]
@jaagr 

alright, here's what I've found.

the specific error seems to be coming from `src/x11/connection.cpp` from the connection function. I'm not exactly sure what error to catch here though.

```
error=warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<xcb_generic_error_t*, void (*)(void*), std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
```

```
std::shared_ptr (count 2, weak 0) 0x8c1eb0, object=...)
    at /home/p3pt/.local/opt/polybar/lib/xpp/include/xpp/proto/../generic/error.hpp:24#14 xpp::generic::dispatch<polybar::v3_0_4_19_ge303f52::detail::connection_base<polybar::v3_0_4_19_ge303f52::connection&, xpp::randr::extension, xpp::xkb::extension> > (error=warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<xcb_generic_error_t*, void (*)(void*), std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<xcb_generic_error_t*, void (*)(void*), std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
```

**Comment by borysn** [comment]
@jaagr is it possible there are compiler flags for rtti missing? 
https://stackoverflow.com/questions/21411798/enabling-rtti-for-clang-tool

**Comment by borysn** [comment]
@jaagr i tried removing rtti support, added `-fno-rtti` to `01-core.cmake`. Just tossed it into the `SANITIZE` custom build type line for now (didn't know where else to put it), that allowed polybar to not crash, but it does not redraw after the icon is cleared (there's a gap between the screen edge and where the icon should be)

**Comment by jaagr** [comment]
@borysn what plugin are you using to get the pushbullet systray functionality? I installed the vendor firefox plugin but I don't get any systray notifications.

**Comment by borysn** [comment]
@jaagr, I'm just using the vendor plugin, https://addons.mozilla.org/en-us/firefox/addon/pushbullet/?src=ss

not exactly sure why i'm getting the notification, and i don't receive it on my laptop also running gentoo with ff 51.0.2.

**Comment by jaagr** [comment]
Could you click the icon when it shows up after running `$ xwininfo -children`

**Comment by borysn** [comment]
@jaagr, here's the output

```
xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x1000001 "polybar-topbar_HDMI-0"

  Root window id: 0x2a5 (the root window) "i3"
  Parent window id: 0xc000fe "[i3 con] container around 0x1e13ad0"
     0 children.
```

**Comment by borysn** [comment]
@jaagr, just to clarify, it seems i am now using ff 51.0.1-r1, looks like 51.0.2 was removed from the gentoo repo (doesn't make a difference tho, just for clarities sake)

**Comment by borysn** [comment]
@jaagr, sorry i misunderstood your last comment, here is the correct output...

```
xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x1000005 "Polybar tray window"

  Root window id: 0x2a5 (the root window) "i3"
  Parent window id: 0x2a5 (the root window) "i3"
     1 child:
     0x2600c84 "Notifications": ("notification-daemon" "Notification-daemon")  16x16+7+5  +1897+5
```

**Comment by jaagr** [comment]
@borysn thanks, unfortunately that didn't tell much but you could get some more information by reading the properties of the window using its ID, like so:

~~~ sh
# Replace with the current ID
$ xprop -id 0x2600c84
~~~

**Comment by borysn** [comment]
@jaagr here is the output 

```
_NET_WM_OPAQUE_REGION(CARDINAL) = 
XdndAware(ATOM) = BITMAP
GDK_TIMESTAMP_PROP(GDK_TIMESTAMP_PROP) = 0x61
_XEMBED_INFO(_XEMBED_INFO) = 0x1, 0x1
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 33555029, 33555030
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x2000254
WM_CLIENT_LEADER(WINDOW): window id # 0x2000001
_NET_WM_PID(CARDINAL) = 21900
WM_LOCALE_NAME(STRING) = "en_US.utf8"
WM_CLIENT_MACHINE(STRING) = "abnd"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 16 by 16
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "notification-daemon", "Notification-daemon"
WM_ICON_NAME(STRING) = "Notifications"
_NET_WM_ICON_NAME(UTF8_STRING) = "Notifications"
WM_NAME(STRING) = "Notifications"
_NET_WM_NAME(UTF8_STRING) = "Notifications"
```

**Comment by jaagr** [comment]
[Is it this daemon?](https://github.com/GNOME/notification-daemon)

I tried it out and I can't reproduce the issue :-/

**Comment by borysn** [comment]
yea, that's the daemon. 

i'm not sure why i can't reproduce the issue on my laptop. i'm building ff from source, so it's probably just a use flag that triggers the notification. 

i'll dig around a little bit more, and see if i can figure it out. otherwise maybe i'll look into the use flags a little more, and maybe it can be excluded.

**Comment by borysn** [comment]
@jaagr just to note, compiling without rtti support is not a good idea, because both `dynamic_cast` and `typeid` are in use. when properly setting `-fno-rtti` flag (not inside of santize lines), there are build errors. https://stackoverflow.com/questions/4486609/when-can-compiling-c-without-rtti-cause-problems

**Comment by jaagr** [comment]
@borysn `-fno-rtti` is not used. Where did you see it?

**Comment by borysn** [comment]
@jaagr, i added it to the compilation, just when i was playing around, i mentioned it in an earlier thread. sorry for the confusion there

**Comment by borysn** [comment]
@jaagr, when you were trying to reproduce the issue, did you push from a browser->browser or mobile app->browser? I noticed when i push browser->browser push bullet opens in a tab, when i push mobile app->browser i get the notification.

**Comment by jaagr** [comment]
I used the official Android app.

**Comment by borysn** [comment]
@jaagr, copy. yea I'm using the Android app & the plug-ins for chromium/chrome (both prepackaged from Debian), than ff from source. only issue with ff. 

I'm gonna close out the issue for now, I'll investigate a little more into the sys tray notification for Firefox.

my best guess right now is the issue will come to a system library that is at an incorrect version. 

thanks for the time, I'll update if I can get it right, or possibly reproduce the issue.

**Comment by borysn** [comment]
@jaagr, not exactly an update, but i have two new questions related to the issue.

1. noticed polybar no longer crashed when clearing the push notification icon. instead, i get `error: Failed to query _XEMBED_INFO, removing client... (XCB_WINDOW (3))`

2. when you were saying that the xprop debugging info wasn't enough, what were you looking for?

**Comment by jaagr** [comment]
> noticed polybar no longer crashed when clearing the push notification icon. instead, i get error: Failed to query _XEMBED_INFO, removing client... (XCB_WINDOW (3))

This means that the tray client is invalid (in respect to the XEMBED protocol).

> when you were saying that the xprop debugging info wasn't enough, what were you looking for?

I was just looking for some hints to determine what application spawned the client.

**Comment by borysn** [comment]
@jaagr, alright so that's probably not too useful for debugging here. i wonder if i'm possibly missing a library or a use flag.

does my module support for X look fine?

```
  Module support:
--    alsa
--    curl
--    i3
--    mpd
--    network
--  X extensions:
--    xcb-randr
--    xcb-randr (monitor support)
--    xcb-render
--    xcb-damage
--    xcb-sync
--    xcb-composite
--    xcb-xkb
--    xcb-xrm
```

**Comment by borysn** [comment]
@jaagr, i'm still not sure what's up with this. i actually finally got the laptop to reproduce the issue, though i'm not exactly sure how. i'm still assuming it's a use flag issue the triggers a library build without the proper rtti symbol support. 

i dropped notification daemon for now, and i'm just going to roll dunst until i can get through this.

update if you ever run into the issue lol, and i'll do the same if i get the courage to figure out what's going on with notification daemon.

anyway, great learning exercise for me, and thank you for bearing with me on this.

**Comment by aminb** [comment]
I just wanted to chime in and say that I've noticed that the icon for the `powermenu` module sometimes disappears and while I haven't yet pinned down the cause, I did just manage to capture an error message:

```
error: Failed to query _XEMBED_INFO, removing client... (XCB_WINDOW (3))
```

which is the same error as what @borysn mentioned a few comments above. For what it's worth, clicking on the empty area (where the power icon used to be) doesn't produce any output.

Version:
```
λ polybar --version
polybar 3.0.5

Features: +alsa +curl -i3 -mpd -network
```
