### ISSUE TITLE
module/date ignores my locale

### ISSUE THREAD

**Issue by x70b1** [jaagr/polybar#489]
Hi, 

it seems like polybar ignores the locale-settings. 
I found this but it should be fixed: https://github.com/jaagr/polybar/issues/74

`$ polybar -s bar-base`
`%{c}%{F#d1d1d1}Friday, 17.03.17 01:08%{F-}`

It is still english. 

`$ date "+%A"`
`Freitag`

This is german. Any ideas?

**Comment by jaagr** [comment]
Could you show the bar section of your config?

**Comment by x70b1** [comment]
Hi jaagr
I deleted the most settungs but this config shows the same wrong translation:

```
[bar/bar-base]
modules-center = date

[module/date]
type = internal/date
date = %A, %d.%m.%y
time = %H:%M
label = %date%  - %time%
```

I use the Arch version. Maybe not a problem in the upstream version? 
```
$ polybar -v
polybar 3.0.4
```

**Comment by x70b1** [comment]
Ah yes I have it. There is an option "locale" in the bar section which have to be set.
I thought polyar would inherit this from my system. But it seems not.

Thanks!
