### ISSUE TITLE
Asian characters crash Polybar

### ISSUE THREAD

**Issue by Deanamic** [jaagr/polybar#493]
Hello,  
I have seen that whenever I have asian letters on my screen Polybar would disappear.
I have tried changing the font but it didnt solve anything.
I haven't found any related issue so I opened this one.

**Comment by hariharan-m** [comment]
I have the same issue? How did you fix this?

**Comment by Deanamic** [comment]
I installed the required fonts and added them to the configfile. Make sure if you have multiple monitors to add it to every instance.
