### ISSUE TITLE
network module: option for traffic in bit/s

### ISSUE THREAD

**Issue by x70b1** [jaagr/polybar#494]
At the moment the network module seems to calculate byte/s values for the bandwith values.
It is more common to measure traffic in bit/s.

An option to configure this case would be awesome.

A token like %upspeed-bit% or %downspeed-bit% could be an idea. Otherwise an option in the basic setting of the network module?

**Comment by jaagr** [comment]
I rarely see download speed being measured in bits when it comes to user applications. I'm aware of the difference but to me it wouldn't serve any purpose - other than knowing the max speed.

I do however welcome a pull-request in case you want this implemented.

**Comment by jaagr** [comment]
I'm closing this as a won't fix.

**Comment by l4n1skyy** [comment]
i agree with x70b1, mbps would be great
