### ISSUE TITLE
Unable to put transparancy on colors imported from .Xresources

### ISSUE THREAD

**Issue by bbaserdem** [jaagr/polybar#497]
I'm using the line;
```
[colors]
background    = ${xrdb:URxvt.background:#1d1f21}
```
to pull colors from my .Xresources to polybar. However, I am unable to implement transparency this way. It would be much simpler if I could somehow remove the # character and put alpha channel information by hand, or adopt the .Xresources format (something like below)
```
[bar/mybar]
background [75]${colors.background}
```

**Comment by jaagr** [comment]
I've been thinking about adding post-processing functions to the config, such as `alpha(#rgb, 0.5)` and `invert(#rgb)`. Not at the top of my to-do list though. Also, I welcome pull-requests for new features.

**Comment by bbaserdem** [comment]
Thanks for the reply. For now, I'll establish a static color and if I learn how to do it I'll do a pull-request.

**Comment by FlorianFranzen** [comment]
Why not just add support for the urxvt rgba color format ```[aa]#rrggbb```, somewhat like @bbaserdem suggested:
```
[colors]
background    = ${xrdb:URxvt.background:#ffffff}

[bar/mybar]
background = [AA]${colors.background}
```
Alternatively string slicing could help.

For example if we add bash style slicing support, this would work (by removing the ```#``` in the front of the color string):
```
background = #aa${colors.background:1}
```
