### ISSUE TITLE
A font awesome icon does not work

### ISSUE THREAD

**Issue by rieje** [jaagr/polybar#498]
A font awesome icon "fa-music" from the [cheat sheet](http://fontawesome.io/cheatsheet/) does not work. When I paste it to the i3 config, it shows up as the music icon, but when I start polybar, it shows up like [this](http://imgur.com/a/YVswK). 

I submitted a Reddit thread on this topic and some users reported the same problem. It seems that at least some i3 status bar users don't have this issue. My other font awesome icons work flawlessly.

**Comment by beanaroo** [comment]
This isn't a polybar issue. You have a font conflict. Have a look at [the wiki](https://github.com/jaagr/polybar/wiki/Fonts#icon-fonts).

I believe I had this exact problem before and the culprit is `ttf-dejavu`. Right-click on the glyph in `gucharmap` to confirm.

**Comment by jaagr** [comment]
You could specify what font to use, see the wiki for more details.

**Comment by rieje** [comment]
I switched font-0 to font-1 and vice versa so FontAwesome is now font-0 and now it works, thank you.
