### ISSUE TITLE
Building from AUR: Missing required python module: xcbgen

### ISSUE THREAD

**Issue by UnicodeAlt255** [jaagr/polybar#502]
I was trying to rebuild polybar with pacaur because the network module wasn't working. For some reason, after I uninstalled polybar with pacman, and tried to reinstall with pacaur, I keep getting the same error that I'm missing xcbgen. Overall I cannot build polybar anymore.

so I tried `sudo pacman -S $(pacman -Ssq xcb)` (which installed Haskell and ghc lol) and tried building from github with build.sh but that failed. So I did `cmake ..` in polybar/build but that had the same result, where it says:

`CMake Error at lib/xpp/CMakeLists.txt:55 (message):
  Missing required python module: xcbgen`

**Comment by UnicodeAlt255** [comment]
I reinstalled my arch linux, and I think I may know the cause of my problems. When pacaur-ing polybar after a clean install, it failed initially because it required iwlib.h which is wireless-tools. When I looked at the packages that required wireless-tools I realized that my installation of i3-status or i3blocks must have provided that dependency, but messed it up for polybar. But I don't really know what's up with xcbgen.

**Comment by jaagr** [comment]
Hi, if I remember correctly the `xcbgen` python module on Arch required python 3.

**Comment by UnicodeAlt255** [comment]
I had python2, python3, and python3 from anaconda, but when installing the console showed that the installation looked for xcbgen in python2, python3, and python, but failed to do so for some reason. It did work after full system reinstall however.

**Comment by zlatin** [comment]
Uninstalling Anaconda resolved the same issue for me. I believe it will help someone else.
https://docs.anaconda.com/anaconda/install/uninstall for details

**Comment by boardfish** [comment]
Getting this problem too on Manjaro.

**Comment by patrick96** [comment]
@boardfish Do you have anaconda installed? If so, remove it, the python anaconda packages interfere with the ones polybar needs to build. If you don't have anaconda, please open a new issue where you document exactly what is not working and provide as much information as possible about the problem

**Comment by asoltysik** [comment]
Any idea how to fix that without uninstalling Anaconda?

**Comment by nath1as** [comment]
i had a similar problem on arch, 
and a reinstall of xcb-proto package fixed it

**Comment by boardfish** [comment]
Not sure if this has been logged elsewhere, but ensuring that `pyenv` uses the `system` Python rather than some virtual environment with `pyenv global system` should help. Do that, then reinstall `xcb-proto` and try installing `polybar` again.

**Comment by ethaligan** [comment]
I had to switch the local version to system using `pyenv local system`.
Thanks @boardfish for the advice!

**Comment by patrick96** [comment]
After some testing I have determined that on some setups it's virtually impossible to build polybar if anaconda is lingering in the `PATH`, I have rewritten the entry on the known issues page for instructions on how to build polybar without anaconda getting in the way: https://github.com/jaagr/polybar/wiki/Known-Issues#building-with-anaconda-installed

**Comment by sirusss** [comment]
I'm also having this issue when trying to build from AUR.

Tried @nath1as 's solution but got this:

```
 sirusss  ~  sudo pacman -R xcb-proto
[sudo] password for sirusss: 
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: libxcb: removing xcb-proto breaks dependency 'xcb-proto>=1.12'
 sirusss  ~  sudo pacman -R xcb-proto libxcb                                                                       1 
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: ffmpeg: removing libxcb breaks dependency 'libxcb'
:: libx11: removing libxcb breaks dependency 'libxcb'
:: libxkbcommon-x11: removing libxcb breaks dependency 'libxcb'
:: xcb-util: removing libxcb breaks dependency 'libxcb>=1.7'
:: xcb-util-cursor: removing libxcb breaks dependency 'libxcb'
:: xcb-util-image: removing libxcb breaks dependency 'libxcb>=1.7'
:: xcb-util-keysyms: removing libxcb breaks dependency 'libxcb>=1.7'
:: xcb-util-renderutil: removing libxcb breaks dependency 'libxcb>=1.7'
:: xcb-util-wm: removing libxcb breaks dependency 'libxcb>=1.7'
:: xorg-xlsatoms: removing libxcb breaks dependency 'libxcb'
:: xorg-xlsclients: removing libxcb breaks dependency 'libxcb'
:: xorg-xwininfo: removing libxcb breaks dependency 'libxcb'
```

And I need anaconda for development so unfortunately uninstalling it isn't an option for me. Hoping to try out polybar eventually!

**Comment by patrick96** [comment]
@sirusss Did you read the [link](https://github.com/jaagr/polybar/wiki/Known-Issues#building-with-anaconda-installed) I posted? It describes how to get polybar working with anaconda.

**Comment by sirusss** [comment]
Thanks for pointing that out, @patrick96 . I was able to build polybar after removing anaconda from $PATH. I'm assuming it's okay to add anaconda back to $PATH after the build/installation of polybar is complete?

**Comment by patrick96** [comment]
@sirusss exactly, otherwise you may not be able to use anaconda anymore. Removing those paths is supposed to be only temporary while building polybar. I have made this clearer in the wiki

**Comment by patrykwegrzyn** [comment]
conda deactivate on terminal window worked for me
