### ISSUE TITLE
scrolling through workspaces on multiple monitors

### ISSUE THREAD

**Issue by thamma** [jaagr/polybar#503]
I assume this is a bug. I'm running polybar v3.0.4 with the i3 module on i3wm v4.13.

# Reproduction:
Using two monitors, both running one instance of polybar, having their separate configs set up. I scroll the workspaces on the first polybar instance, then move to the other monitor to scroll through the workspaces on the second polybar instance.

# Expected behaviour:
When scrolling on the bar of one monitor, I expect the scrolling to only affect the (associated) workspaces of that monitor. Switching over to the other monitor should yield the same behaviour for that bar.

# Actual behaviour:
Scrolling on the first monitor works as expected. However if I move my cursor to the second monitor, hover the polybar and start scrolling, I'm scrolling through the workspaces of the first monitor. It appears that the second polybar doesn't become focused unless I manually click it. Clicking the bar before scrolling yields the expected behaviour.

Maybe I'm not setting up my two monitor setup correctly and should rather use some settings designed to be used with two monitors. Please hint me on that, if that's the case, as I couldn't find the proper settings using google and the wiki.

Best regards

**Comment by jaagr** [comment]
Hi and thanks for your well written issue. Did you try the module parameter `pin-workspaces = true`?

**Comment by TonCherAmi** [comment]
@jaagr hey, I can confirm this behavior, I also do have `pin-workspaces` set to `true` and that does not seem to resolve the issue.

**Comment by thamma** [comment]
Can confirm, `pin-workspaces` does not change the behaviour. I already used that.

**Comment by jaagr** [comment]
Then I'd also say it's a bug. Will have a look later.

**Comment by TonCherAmi** [comment]
@jaagr hey I almost finished working on the fix. I will open a PR soon I think.

**Comment by jaagr** [comment]
Great, then I'll let you finish that up.

**Comment by jaagr** [comment]
@TonCherAmi, could you also fix the bspwm and xworkspaces modules? I would guess that they have the same problem.

**Comment by TonCherAmi** [comment]
@jaagr I'm not sure to be honest, I've never dealt with bspwm. But I could check it out tomorrow I think.

**Comment by jaagr** [comment]
The scroll code should be pretty similar to the one used in the i3 module.

**Comment by TonCherAmi** [comment]
Yeah, it's just that I'll need to install and configure it in order to check it, might take some time.
Also, the problem in i3 module lies in the ipc command, so I'm not really sure that those modules have the same issue.

**Comment by jaagr** [comment]
I'll just note that the bspwm module works as intended as long as the `pin-workspaces` parameter is set to `true`. Currently testing the xworkspaces module.

**Comment by TonCherAmi** [comment]
Nice, that's good news.

By the way, I have a question regarding these two parameters: `scroll-up` and `scroll-down`, it seems that they're not implemented at all, neither in the i3 module nor in the bspwm one. Are they deprecated or yet to be implemented?

**Comment by jaagr** [comment]
`scroll-{up,down}` should be defined in the bar section and can be used to enable workspace scrolling on the whole bar. It can be used for any command actually...

**Comment by TonCherAmi** [comment]
Ah, that makes sense, thanks for the explanation.

**Comment by jaagr** [comment]
What version of `i3` are you running by the way? I just tested the scrolling and it works fine for me, using this configuration: 

~~~ dosini
[bar/top]
enable-ipc = true
monitor = ${env:MONITOR:eDP1}
width = 100%
height = 24

background = #222
foreground = #eee

line-color = #fba922
underline-size = 1
overline-size = 2

border-bottom-size = 2
border-bottom-color = #333

padding-left = 0
padding-right = 2
module-margin-left = 1
module-margin-right = 2

font-0 = dina:pixelsize=9;1
font-1 = siji:pixelsize=10;1
font-2 = unifont:size=6;1

modules-left = i3
modules-center =
modules-right =

[bar/bottom]
inherit = bar/top

enable-ipc = true
monitor = ${env:MONITOR:HDMI1}
bottom = true

underline-size = 1
overline-size = 2

modules-left = i3
modules-center =
modules-right =

[module/i3]
type = internal/i3
index-sort = true
pin-workspaces = true
wrapping-scroll = true

format = <label-state> <label-mode>

label-mode = %mode%
label-mode-padding = 2
label-mode-background = #e60053

label-focused = %index%
label-focused-background = #383838
label-focused-foreground = #fff
label-focused-overline = #f90
label-focused-underline = #f90
label-focused-padding = 2

label-unfocused = %index%
label-unfocused-padding = 2

label-urgent = %index%!
label-urgent-background = #bd2c40
label-urgent-padding = 2

label-visible = %index%
label-visible-padding = 2

; vim:ft=dosini
~~~

**Comment by TonCherAmi** [comment]
Okay, this configuration does not change the behavior for me.
My i3 version is `i3 version 4.13-non-git © 2009 Michael Stapelberg and contributors` with gaps.

Are you sure you are reproducing it correctly?

Try following these steps:
1. Set up two separate bars on two monitors both with the i3 module present, scrolling and pin-workspaces enabled.
2. Make sure to have at least two workspaces open on both monitors.
3. Focus one of workspaces on either monitor.
4. Move the mouse pointer to the bar located on the opposite monitor (with the **unfocused workspace**).
5. Scroll.

**Current behavior**: workspaces are scrolled on the monitor that you have previously focused a workspace on.

**Desired behavior**: workspaces are scrolled on the monitor where the bar you're scrolling is located.

My config in case it is needed: https://ptpb.pw/0E-I

**Comment by jaagr** [comment]
@TonCherAmi You're right, it probably worked because I accidentally focused the other workspace. I managed to reproduce the issue by following your steps.

**Comment by jaagr** [comment]
After following the steps, I was able to reproduce the bug using the bspwm module as well.

**Comment by TonCherAmi** [comment]
@jaagr got it, will check it out once I have some free time on my hands.

**Comment by jaagr** [comment]
One solution would be to manually keep track of the focused workspace on each display instead of using the bspwm modifier `.local`.

**Comment by TonCherAmi** [comment]
Can't we just take the same kind of approach as with the i3 module?

For example this fixes the issue for me:

```c++
string scrolldir;

if (cmd.compare(0, strlen(EVENT_SCROLL_UP), EVENT_SCROLL_UP) == 0) {
  scrolldir = m_revscroll ? "prev" : "next";
} else if (cmd.compare(0, strlen(EVENT_SCROLL_DOWN), EVENT_SCROLL_DOWN) == 0) {
  scrolldir = m_revscroll ? "next" : "prev";
} else {
  return false;
}

string modifier;

if (m_pinworkspaces) {
  modifier = ".local";
}

for (const auto& mon : m_monitors) {
  if (mon->name == m_bar.monitor->name && !mon->focused) {
    send_command("monitor -f " + mon->name, "Sending monitor focus command to ipc handler");
    break;
  }
}

send_command("desktop -f " + scrolldir + modifier, "Sending desktop " + scrolldir + " command to ipc handler");
```

**Comment by jaagr** [comment]
Yeah that looks like the appropriate way to do it.
