### ISSUE TITLE
Module/Script is still on the bar if there is no script output

### ISSUE THREAD

**Issue by x70b1** [jaagr/polybar#504]
I found out that the outdated output is still on the bar if there is no output in the script.

```
#!/bin/sh

updates=$(checkupdates | wc -l)

if [ "$updates" -gt 0 ]; then
    echo "  $updates"
fi
```

I checked for new packages and thought the module should be disappear if there are no new packages. But I was wrong. Actually I need to add `echo ""` to get this. 

```
...

if [ "$updates" -gt 0 ]; then
    echo "  $updates"
else
    echo ""
fi
```

I am not sure what the best is here. Maybe a fix to hide the module on the bar if there is no new output.

Otherwise a note in the Wiki/Script-Page would be enough so that nobody has this trouble again. I could add a line there?

**Comment by jaagr** [comment]
Hi, yeah please update the wiki.

**Comment by x70b1** [comment]
Ack. Added to the wiki.
