### ISSUE TITLE
Volume click mutes both master and headphone/speakers, but unmute does not.

### ISSUE THREAD

**Issue by Metamist** [jaagr/polybar#505]
### Reproduction:
Click the volume bar to mute, then try to unmute. 

### Expected behaviour:
When clicking the volume to mute, only the master channel should be muted. When unmuting, the master channel should be unmuted.

The headphone/speaker channels should be left alone.

### Actual behaviour:
When unmuting, alsamixer shows that only the master channel is unmuted, but not the headphone/speaker channels, leaving the audio muted completely until manually unmuting the headphone/speaker channels in alsamixer.

**Comment by beanaroo** [comment]
I noticed it this week too.

**Comment by jaagr** [comment]
Hi,

Are you defining `headphone-{mixer,id}` and/or `speaker-mixer` in your configuration?

**Comment by beanaroo** [comment]
Hi, Jaagr! Not in my case. I have updated the comment above.

**Comment by Metamist** [comment]
I managed to fix this by making sure pulseaudio was starting on boot (it was installed, just never started) by changing `/etc/pulse/client.conf` and changing
`autospawn = no`
to
`autospawn = yes`

**Comment by munyari** [comment]
FYI, this is a (known) bug with pulse audio and unrelated to polybar https://bugs.launchpad.net/ubuntu/+source/pulseaudio/+bug/878986

Also, pamixer seems to be largely redundant with pactl, which is packaged with pulse audio (on Arch Linux at least)

**Comment by NBonaparte** [comment]
Closing as this issue appears to be fixed.

**Comment by patrick-motard** [comment]
I have a very similar issue currently open in polybar as well https://github.com/jaagr/polybar/issues/900
