### ISSUE TITLE
Is there a way to change artists format for mpd module?

### ISSUE THREAD

**Issue by Doctah** [jaagr/polybar#511]
For example. Currently it displays as `name1;name2;name3`, is there a way to change it to say something like `name1, name2, name`? Or will I have to go under the hood for this?

**Comment by jaagr** [comment]
I guess you mean the `%artist%` token which is currently used to display the `artist` meta data tag. I haven't encountered a song with multiple artists so I haven't seen the use for any post-processing of the tags, but yeah this would need to be done "under the hood".

**Comment by Doctah** [comment]
Alright cool, thanks. I'll see what I can do about it myself then. Thanks.
