### ISSUE TITLE
polybar dies when restarting mopidy

### ISSUE THREAD

**Issue by d3rrial** [jaagr/polybar#512]
When I restart mopidy with
`systemctl restart mopidy`
polybar closes. I'm going to try to investigate the cause, but don't hold your breath...

In the meantime: Is anybody else experiencing this issue?

Edit: I'm using bspwm as WM and a 4.10.5-zen kernel if that helps any.

**Comment by jaagr** [comment]
#436 is probably related to this. Will try to reproduce.

**Comment by d3rrial** [comment]
Indeed it is. I looked through the issues but I missed that one for some reason...
