### ISSUE TITLE
Date module breaks padding-right of 2 or less

### ISSUE THREAD

**Issue by beanaroo** [jaagr/polybar#513]
When setting `padding-right = 2` or less, no effect:
![test](https://cloud.githubusercontent.com/assets/1748909/24577300/b20b73a2-1727-11e7-8bdc-def0c9ba28a9.png)

Padding of 3 or higher works as expected:
![test2](https://cloud.githubusercontent.com/assets/1748909/24577324/336269b0-1728-11e7-8d8d-f05c9fb301b5.png)

All padding works as expected when removing the date module from the right-most position.

Current config:
```
[module/date]
type = internal/date
interval = 5

date = %a %-e %b
time = %H:%M

label = %{T3}%{T-} %date% %{T3}%{T-} %time%
label-foreground = ${colors.blue}
```

Setting `time = "%H: %M "` (trailing space) results in space + padding to work.
Setting `padding-right = 0` with trailing space above, results in no space (like the first screenshot)

**Comment by patrick96** [comment]
It seems this one has slipped through the cracks. Is this still happening? I am not able to reproduce this on my end

**Comment by beanaroo** [comment]
I totally forgot about this. I've given this a test and it appears to have been resolved. Thanks for checking up on it!
