### ISSUE TITLE
I3 workspaces on relevant screen

### ISSUE THREAD

**Issue by obayemi** [jaagr/polybar#515]
I'm using i3 as my Wm and have been wanting to switch from i3bar for a while, and polybar seems like the best statusbar ever in almost all aspects, but would it be possible when using multiple monitors to have one bar for each output, with only the relevant workspaces on them like with original i3bar?

**Comment by jereksel** [comment]
I think you can use `pin-workspaces = true` for that: https://github.com/jaagr/polybar/wiki/Module:-i3

**Comment by obayemi** [comment]
oh! thanks I missed that one ^^"

**Comment by obayemi** [comment]
I made a simple for loop to spawn one bar on every output available, but only one bar have i3 workspaces on it... (not even allways on the same output)
```
for i in $(polybar -m | awk -F: '{print $1}'); do MONITOR=$i polybar example -c ~/.config/polybar/config & done
```

**Comment by jaagr** [comment]
@obayemi is i3 running when you launch polybar or when do you launch it?

**Comment by obayemi** [comment]
I launch it from a terminal inside a running i3 session

**Comment by jaagr** [comment]
> i3: Could not mkdir(/tmp/1000-runtime-dir/i3): File exists
> i3: Check permissions of $XDG_RUNTIME_DIR = '/tmp/1000-runtime-dir'

These messages come from the i3ipc lib. Did you follow them up?

**Comment by binaryplease** [comment]
I would also like to have the bar on multiple monitors (when connected) with only the relevant  i3 workspaces on each. 

What about the performance? Wouldn't launching two bars separately lead to all the commands running for each module running twice?

**Comment by obayemi** [comment]
ok, I really don't know how and why, but it works now. After a few system upgrades and some minor configuration changes in i3/dbus/other stuff, I retried and it works perfectly. It was definitely not a polybar issue. But I still don't know why it happened which is pretty annoying...
