### ISSUE TITLE
Feature request: make `volume-step` configurable

### ISSUE THREAD

**Issue by gillescastel** [jaagr/polybar#517]
Currently, the volume step is hardcoded to be 5 in polybar/src/modules/volume.cpp.

I think it'd be good if we could configure this number in the configuration file.

What do you think? Would this be of any use for someone else?

I'd be glad to make a pull request (though my experience with C++ is near zero.) 

In hindsight, I probably should've posted this [here](https://github.com/jaagr/polybar/issues/84).

**Comment by jaagr** [comment]
Sure, go ahead and make a pull-request for it if you'd like. It's a good way to start learning.
