### ISSUE TITLE
No built-in support to dereference ${xrdb:color1} references

### ISSUE THREAD

**Issue by LostMyAccount** [jaagr/polybar#519]
Getting this error message despite having `xcb-util-xrm-1.2-1.fc25.x86_64` and `xcb-util-xrm-devel-1.2-1.fc25.x86_64`installed.

I'm currently running `Polybar 3.0.5` on Fedora 25

**Comment by jaagr** [comment]
Did you install `xcb-util-xrm` after building polybar? If yes, then you need to rebuild polybar.

**Comment by LostMyAccount** [comment]
Ah yeah, my bad. New Fedora install and was installing other stuff. Thanks.
