### ISSUE TITLE
Tray icons don't scale up with HiDPI monitor and i3

### ISSUE THREAD

**Issue by Pacane** [jaagr/polybar#523]
I'm using polybar with i3, and I'm using a HiDPI monitor.

here's how it looks like

![picture](http://i.imgur.com/rzHnGUi.png)

I don't know if the issue is with polybar or i3 (my i3 config has no bar configuration in it)

I saw that there's a config in polybar called `tray-scale` however all it does is move the icons around and it doesn't make them bigger.

Here's what I see with `tray-scale = 2.0`

![image2](http://i.imgur.com/VGLwM7G.png)

**Comment by UnicodeAlt255** [comment]
github.com/jaagr/polybar/issues/398

**Comment by Pacane** [comment]
Thanks, that fixed it.

**Comment by Piliponful** [comment]
It doesn't work for me

**Comment by moraisaugusto** [comment]
Try to use these the following confs:

```
tray-scale = 1.0
tray-maxsize = 28
```


make sure you are using the right DPI/SCALE for GTK/QT.
