### ISSUE TITLE
MPD module output on stopped playback

### ISSUE THREAD

**Issue by TonCherAmi** [jaagr/polybar#524]
Hey,

I was wondering whether it is possible to customize the output of the MPD module for the case when playback is stopped, since as of now, at least for me, it looks quite ugly:
* Stopped
![stopped](https://cloud.githubusercontent.com/assets/13941584/24831170/5e658d34-1c9d-11e7-9cda-1b2ad00cfe21.png)

* Playing 
![playing](https://cloud.githubusercontent.com/assets/13941584/24831162/30fd953a-1c9d-11e7-976b-d1da8a4c8f1c.png)

As per wiki I couldn't find a straightforward way of doing it, so unless I'm missing something, I thought that perhaps we should address the matter somehow. For example in addition to `format-online` we could have state-specific format parameters.

My MPD config section just in case:
```
[module/mpd]
type = internal/mpd

host = 127.0.0.1
port = 6600

format-online = <icon-prev>  <icon-stop>   <label-song>   <icon-play> <icon-pause>  <icon-next>

icon-prev = 
icon-stop = 
icon-pause = 
icon-play = 
icon-next = 

label-song-maxlen = 50
label-song-ellipsis = true

format-offline = 

format-online-underline = #AA
format-online-padding = 1
```

**Comment by jaagr** [comment]
We could maybe add some more output formats, like `format-playing`, `format-stopped`, etc.

**Comment by TonCherAmi** [comment]
Yeah, that sums up what I had in mind quite well, will look into implementing this.

**Comment by kamek-pf** [comment]
In the same vein, it would be nice to have the ability to display something when the playlist is empty.
