### ISSUE TITLE
under-line

### ISSUE THREAD

**Issue by IzacCF** [jaagr/polybar#527]
How to configure this?

Under-line in module i3 is not centralized.

Look:

![under-line](https://cloud.githubusercontent.com/assets/25287245/24868776/7bc4b5e4-1de7-11e7-80f6-4840139903a3.png)

**Comment by jaagr** [comment]
Is it appearing like that for all of the three icons?

**Comment by IzacCF** [comment]
Hi, Michael.

Yes, but I only use under-line in the i3 module

**Comment by IzacCF** [comment]
Config [bar/top]:
------


[bar/top]
bottom = false
monitor = VGA-0
width = 100%
height = 27

modules-left = power i3
modules-center = date
modules-right = 

;background transparent
background = #00000000
;Flatabulous Theme
;background = #434343
;Arc Theme
;background = #2F343F

line-size = 1

;Traço acima no módulo
;overline-size = 0
;overline-color = #FF0000

;Traço abaixo no módulo
underline-size = 1
underline-color = #FF0000

;Traço abaixo em todo painel
;border-bottom-size = 1
;border-bottom-color = #BBBBBB

spacing = 1
padding-left = 1
padding-right = 1
module-margin-left = 1
module-margin-right = 1

;font-N = <fontconfig pattern>;<vertical offset>
font-0 = terminus:pixelsize=11;0
font-1 = unifont:size=8:heavy:fontformat=truetype;-2
font-2 = Wunconsiji:pixelsize=10;0
font-3 = FontAwesome:size=11;0
font-4 = IcoMoon:size=11;0

tray-position = right
tray-padding = 1
;tray-transparent = true
tray-detached = true

;scroll-up = i3wm-wsnext
;scroll-down = i3wm-wsprev
click-left = i3wm-wsnext
click-right = i3wm-wsprev
--------

**Comment by IzacCF** [comment]
polybar 3.0.5

Features: +alsa +curl +i3 +mpd +network
[1]+  Concluído              gvim ~/.config/polybar/config

**Comment by jaagr** [comment]
Could you show your configuration for the i3 module?

**Comment by IzacCF** [comment]
Ok:
-----

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
pin-workspaces = true
;wrapping-scroll = true
strip-wsnumbers = true

enable-click = true
;scroll-up = i3wm-wsnext
;scroll-down = i3wm-wsprev
click-left = i3wm-wsprev
click-right = i3wm-wsnext

label-mode-padding = 0
label-mode-foreground = #BBBBBB

;label-focused = 
;label-focused = 

label-indicator-padding = 0
label-indicator-background = #BBBBBB
label-indicator-underline = #FF0000

label-focused-foreground = #BBBBBB
label-focused-padding = 1
label-focused-underline = #FF0000

;label-unfocused = 
label-unfocused-foreground = #747474
label-unfocused-padding = 1

;label-visible = 
label-visible-foregroud = #888888
label-visible-padding = 1
label-visible-background = #BBBBBB
label-visible-underline = #FF0000

;label-urgent = 
;label-urgent = 
;label-urgent = 
;label-urgent = 
label-urgent-padding = 2
label-urgent-foreground = #FF0000

**Comment by jaagr** [comment]
Try with these changes:

~~~
format = <label-state> <label-mode>

label-focused = %name%
label-unfocused = %name%
label-visible = %name
label-urgent = %name%

label-mode = %mode%
~~~

**Comment by IzacCF** [comment]
"format = <label-state> <label-mode>" 
It was already so, but it did not appear above

Thanks, Michael.

![under-line2](https://cloud.githubusercontent.com/assets/25287245/24869733/909d9d0c-1dea-11e7-912b-ba23a7c2e6e2.png)

Fantastic! :)

**Comment by jaagr** [comment]
Great! 👍
