### ISSUE TITLE
Custom Module: Kernel version

### ISSUE THREAD

**Issue by d3rrial** [jaagr/polybar#528]
```
[module/kernel]
type = custom/script
exec = uname -r
tail = false
interval = 1024
```

uname is specified by POSIX, so it should run on pretty much any compliant unix system without any additional dependencies.

Displays the current version of your kernel (Mine says 4.10.9-zen+)
It's a super lame module, I know. Issue because I want to know if it's too lame or too trivial to be included in the user submitted modules wiki page

1024 was chosen at random.

On another note: Is there something like an "execute once" switch for custom scripts? This really doesn't need to be run on an interval, but it should still be run every time polybar is started...

**Comment by NBonaparte** [comment]
Added to the wiki page. Currently there is no execute once option.
