### ISSUE TITLE
unclosed action block with token as clickable text

### ISSUE THREAD

**Issue by varenspukis** [jaagr/polybar#530]
Example : `%{A1:rofi -show window:}%title%%{A}` in the xwindow module, I get : 

> Failed to parse contents (reason: unclosed action block(s))

 I think there is a problem on parsing the end of the action block and the token

**Comment by jaagr** [comment]
It works fine for me. Are you using the latest version of polybar?

**Comment by varenspukis** [comment]
Yes, 3.0.5 (`polybar -v`)

**Comment by varenspukis** [comment]
Ok weird I tested it this morning and it just worked fine, sorry for bothering you. It seems that i had a similar problem that #198
