### ISSUE TITLE
Feature request: DockBarX module

### ISSUE THREAD

**Issue by owcz** [jaagr/polybar#532]
Integrates [DockBarX](https://github.com/M7S/dockbarx) (a popular app dock) into the panel, similar to [its integration with xfce-panel](http://www.webupd8.org/2013/03/dockbarx-available-as-xfce-panel-plugin.html) via https://github.com/TiZ-EX1/xfce4-dockbarx-plugin

**Comment by jaagr** [comment]
Closing. I'll add a reference to this in #84

**Comment by ispeaknousa** [comment]
I think that this ticket should be reopend due to the fact that [the list of feature requests](https://github.com/jaagr/polybar/issues/84) has been closed.

**Comment by patrick96** [comment]
We're not going to implement this. It will probably cause just as much headache as the tray, add lots of dependencies and would be useful to only a handful of people
