### ISSUE TITLE
xworkspaces module with XMonad updating incorrectly

### ISSUE THREAD

**Issue by jamesbvaughan** [jaagr/polybar#535]
I'm running XMonad with desktopConfig and the polybar xworkspaces module.

The module displays a list of the names of all my workspaces, and highlights the name of the active workspace. It correctly updates which workspace name is highlighted when I move focus from one workspace to another, but when I move focus between windows within a workspace, it stops highlighting any of the workspace names until I switch to another workspace.

I think this might be related to #411 but I'm not sure.

**Comment by robertseaton** [comment]
Had the same issue. Applying the patch from #411 fixes it.

**Comment by jamesbvaughan** [comment]
@robertseaton Awesome, thanks!
