### ISSUE TITLE
MPD Module not displaying anything.

### ISSUE THREAD

**Issue by xeanto** [jaagr/polybar#536]
I took the MPD module config file from the space config, and then (tried to) make it display. I did put it in the  modules, but it is not displayed. It is connecting to the mpd server, as there is no error message on startup, but there is when i kill the mpd process. Here is my config:
`[~/.config/polybar]── - cat config
;=====================================================
;
;   To learn more about how to configure Polybar
;   go to https://github.com/jaagr/polybar
;
;   The README contains alot of information
;
;=====================================================

[global/wm]
margin-top = 5
margin-bottom = 5

[bar/bar1]
monitor = ${env:MONITOR:DP-5}
width = 100%
height = 25
offset-x = 0
offset-y = 5

bottom = true

background = #00000000
foreground = #888888

spacing = 1
padding-left = 4
padding-right = 4
module-margin-left = 1
module-margin-right = 2

font-0 = hack:pixelsize=12;1
font-1 = unifont:size=6:heavy:fontformat=truetype;-2
font-2 = siji:pixelsize=10;0
font-3 = FontAwesome:pixelsize=14;0

modules-left =
modules-center = i3 mpd
modules-right = 

tray-position = right
tray-padding = 0
tray-transparent = true

override-redirect = true

scroll-up = i3wm-wsnext
scroll-down = i3wm-wsprev

[bar/bar2]
monitor = ${env:MONITOR:HDMI-0}
width = 100%
height = 25
offset-x = 0
offset-y = 5

bottom = true
background = #00000000
foreground = #888888

spacing = 1
padding-left = 4
padding-right = 4
module-margin-left = 1
module-margin-right = 2

font-0 = hack:pixelsize=12;1
font-1 = unifont:size=6:heavy:fontformat=truetype;-2
font-2 = siji:pixelsize=10;0
font-3 = FontAwesome:pixelsize=14;0

modules-left = 
modules-center = i3 mpd
modules-right =

override-redirect = true

scroll-up = i3wm-wsnext
scroll-down = i3wm-wsprev

[bar/topbar1]
monitor = ${env:MONITOR:DP-5}
width = 100%
height = 25
offset-x = 0
offset-y = 5
padding-right = 2

background = #00000000
foreground = #888888

font-0 = Source Sans Pro:pixelsize=14;1
font-1 = unifont:size=6:heavy:fontformat=truetype;-2
font-2 = siji:pixelsize=10;0
font-3 = FontAwesome:pixelsize=14;0

modules-left =
modules-center = date
modules-right = wireless-network temperature cpu memory volume

override-redirect = true

[bar/topbar2]
monitor = ${env:MONITOR:HDMI-0}
width = 100%
height = 25
offset-x = 0
offset-y = 5
padding-right = 2

background = #00000000
foreground = #888888

font-0 = Source Sans Pro:pixelsize=14;1
font-1 = unifont:size=6:heavy:fontformat=truetype;-2
font-2 = siji:pixelsize=10;0
font-3 = FontAwesome:pixelsize=14;0

modules-left =
modules-center = date
modules-right = wireless-network temperature cpu memory volume

override-redirect = true

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = true
strip-wsnumbers = true
pin-workspaces = true

label-mode-padding = 5
label-mode-foreground = #ffffff

label-unfocused-foreground = #888888
label-unfocused-padding = 1

label-visible-foregroud = #888888
label-visible-padding = 1

label-focused-foreground = #ffffff
label-focused-padding = 1

label-urgent-padding = 1
ws-icon-0 = 
ws-icon-1 = 
ws-icon-2 = 
ws-icon-3 = 
ws-icon-4 = 
ws-icon-default = 
[module/date]
type = internal/date
interval = 1

date = "%d/%m/%y"
date-alt = " %d"

time = " %H:%M:%S"
time-alt =  %H:%M

label = %date% %time%

[module/volume]
type = internal/volume

format-volume = <label-volume> <bar-volume>
label-volume = ""
label-volume-foreground = ${root.foreground}
label-muted = muted

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = │
bar-volume-indicator-font = 2
bar-volume-indicator-foreground = #ff
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground =

[module/wireless-network]
type = internal/network
interface = enp0s31f6
interval = 0.25

;format-connected-underline = #0088CC
label-connected = [ :   %upspeed% | :   %downspeed% ]
;label-connected-foreground = #2aa198

;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = NET %ifname% disconnected
;label-disconnected-foreground = NET ${colors.foreground-alt}

;Required if <bar-progress> is used
bar-progress-width = 5
bar-progress-format = %{+u}%{+o}%fill%%{-u}%{-o}%indicator%%{+u}%{+o}%empty%%{-u}%{-o}
bar-progress-indicator = |
bar-progress-indicator-foreground = ${BAR.foreground}
bar-progress-indicator-font = 3
bar-progress-fill = █
bar-progress-fill-foreground = #5a5
bar-progress-fill-font = 3
bar-progress-empty = █
bar-progress-empty-foreground = #555
bar-progress-empty-font = 3

[module/memory]

type = internal/memory
label = %gb_used%/16 GB (%gb_free%)
label-padding = 10

[module/cpu]
type = internal/cpu
format = <label>
label = CPU %percentage%

[module/temperature]
type = internal/temperature
interval = 0.5
thermal-zone = 0
warn-temperature = 60
label = TEMP %temperature%
label-padding = 10

[module/mpd]
type = internal/mpd

host = ::1
port = 6600
interval = 1

format-online = <icon-prev> <icon-seekb> <icon-stop> <toggle> <icon-seekf> <icon-next> <icon-repeat> <icon-random> <label-time> <label-song>

label-song = %artist% - %title%
label-offline = ---
format-offline = <label-offline>
icon-prev = 
icon-seekb = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 
icon-seekf = 

icon-random = 
icon-repeat = 

toggle-on-foreground = #888888
toggle-off-foreground = #68

bar-progress-width = 45
bar-progress-format = %{A4:mpdseek+2: A5:mpdseek-2:}%fill%%indicator%%empty%%{A A}
bar-progress-indicator = |
bar-progress-indicator-foreground = #ff
bar-progress-indicator-font = 3
bar-progress-fill = ─
bar-progress-fill-foreground = #bb
bar-progress-fill-font = 3
bar-progress-empty = ─
bar-progress-empty-font = 3
bar-progress-empty-foreground = #44
`
I'm currently just at a loss, have been trying for days now to get this to work
Output from `polybar --log=info bar1`:
`* Loaded /home/alex/.config/polybar/config
* Environment var ${MONITOR} is undefined, using defined fallback value "DP-5"
* Loaded monitor DP-5 (1680x1050+1920+0)
* Bar geometry: 1680x25+1920+1020
* Starting application
* Starting module/i3
* Starting module/mpd
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=4)
* Configured DPI = 96x96
* Loaded font "hack:pixelsize=12" (name=Hack, offset=1, file=/home/alex/.local/share/fonts/Hack-Regular.ttf)
* Loaded font "unifont:size=6:heavy:fontformat=truetype" (name=Unifont, offset=-2, file=/usr/share/fonts/TTF/Unifont.ttf)
* Loaded font "siji:pixelsize=10" (name=DejaVu Sans, offset=0, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
* Loaded font "FontAwesome:pixelsize=14" (name=FontAwesome, offset=0, file=/home/alex/.fonts/fontawesome-webfont.ttf)
* Bar window: 0x1000001
* Activating tray manager
* Tray window: 0x1000005
* module/i3: Rebuilding cache
* module/mpd: Rebuilding cache
* module/mpd: Hiding module since queue is empty
* Redrawing bar window
* Notifying pending tray clients
* Processing docking request from 0x0a06212
* Processing docking request from 0x0600416
* Redrawing bar window
* Redrawing bar window
* Redraw tray container (id=0x1000005)
* Tray root pixmap (rootpmap=0x3400001, geom=3600x1080+0+0, tray=0x1000005, pmap=0x1000006, gc=0x1000007)
* Redraw tray container (id=0x1000005)
* Redraw tray container (id=0x1000005)
* Redraw tray container (id=0x1000005)
`

**Comment by TonCherAmi** [comment]
Hey, from what I can see your `format-online` parameter is not set to anything. You should try setting it to something like this:
```ini
format-online = <icon-prev> <icon-seekb> <icon-stop> <toggle> <icon-seekf> <icon-next>  <icon-repeat> <icon-random>  <bar-progress> <label-time>  <label-song>
```
To learn more about formats check out [this wiki page](https://github.com/jaagr/polybar/wiki/Formatting). For MPD specific formatting see [here](https://github.com/jaagr/polybar/wiki/Module:-mpd).

**Comment by xeanto** [comment]
I fixed it by turning MPD on while the bar was active, this activated the MPD module for some reason. After that, it worked fine no problems.
