### ISSUE TITLE
Polybar moves to wrong display when connecting a second display

### ISSUE THREAD

**Issue by zigarrre** [jaagr/polybar#542]
## Description

When attaching a second display (in my case via HDMI) the bar moves to it even though it is configured to be on the already connected display.

The second display is enabled/configured via xrandr:
```
xrandr --output HDMI1 --auto --left-of LVDS1
```

Expected behavior would be for the bar to stay on the display it's configured for via the `monitor` option.

When disabling the display via `xrandr --output HDMI1 --off` the bar moves back to the correct display.

## Config

```
[bar/test]
monitor = LVDS1
width = 100%
modules-center = test

[module/test]
type = custom/text
content = test
```

## Additional Information

I'm running Arch, using bspwm as WM and have installed polybar via the the `polybar` AUR package.

```
[zigarrre@t520 ~]% polybar -vv 
polybar 3.0.5

Features: +alsa +curl -i3 +mpd +network

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro
```

**Comment by jaagr** [comment]
You probably need to upgrade bspwm. The patches for this issue is not available in the latest release tag (0.9.2).

**Comment by zigarrre** [comment]
So you think it's a bug in bspwm? Could you please provide a link to the corresponding patch or issue?
I'll build bspwm from the master branch and test again.

**Comment by NBonaparte** [comment]
Closing, as 0.9.3 has been released for a while which has the required patches. Please reopen if this is not the case.
