### ISSUE TITLE
Little problem with I3 module

### ISSUE THREAD

**Issue by phineas0fog** [jaagr/polybar#546]
Hello Jaagr :)
In first, I congratulate you for the work because Polybar is very very very nice :D 
But I have a little problem with the I3 module... I have 3 screens connected to my pc, with a different workspace on each.
But the I3 module display this :
 ![](http://i.imgur.com/AnM85Hj.png)
There is a solution to hide the number and keep the icon only ?
There is I3 module's config : https://gist.github.com/phineas0fog/4e2abbffef17a486709beba2df6b4d22

Tjanls a lot :D

**Comment by TonCherAmi** [comment]
Hey, take a look at these options:
```ini
; Only show workspaces defined on the same output as the bar
;
; Useful if you want to show monitor specific workspaces
; on different bars
;
; Default: false
pin-workspaces = true

; This will split the workspace name on ':'
; Default: false
strip-wsnumbers = true
```

**Comment by phineas0fog** [comment]
Thanks but there is no effects... :///

**Comment by jaagr** [comment]
Hi and thanks. You haven't replaced the default value for `label-visible`. Fix:

~~~ dosini
label-visible = %icon%

**Comment by phineas0fog** [comment]
Oh thanks :D
