### ISSUE TITLE
Error installing polybar when doing 'sudo ./build.sh'

### ISSUE THREAD

**Issue by oreHGA** [jaagr/polybar#549]
When using the build script to install polybar, i get the following errors
Could you please help me out on how to fix this?

`Scanning dependencies of target polybar
[  9%] Building CXX object bin/CMakeFiles/polybar.dir/modules/fs.cpp.o
In file included from /home/og/polybar/src/modules/fs.cpp:4:
In file included from /home/og/polybar/include/drawtypes/label.hpp:4:
In file included from /home/og/polybar/include/components/config.hpp:13:
In file included from /home/og/polybar/include/x11/xresources.hpp:14:
In file included from /home/og/polybar/include/x11/connection.hpp:10:
In file included from /home/og/polybar/include/components/screen.hpp:7:
In file included from /home/og/polybar/include/x11/extensions/randr.hpp:10:
/home/og/polybar/lib/xpp/include/xpp/proto/randr.hpp:3026:42: error: use of
      undeclared identifier 'xcb_randr_get_monitors_reply'; did you mean
      'xcb_randr_get_providers_reply'?
                               **SIGNATURE(xcb_randr_get_monitors_reply),**
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                         xcb_randr_get_providers_reply
/home/og/polybar/lib/xpp/include/xpp/generic/signature.hpp:5:36: note: expanded from
      macro 'SIGNATURE'
  xpp::generic::signature<decltype(NAME), NAME>
                                   ^
/usr/include/xcb/randr.h:3390:1: note: 'xcb_randr_get_providers_reply' declared here
xcb_randr_get_providers_reply (xcb_connection_t                  *c  /**< */,
^
In file included from /home/og/polybar/src/modules/fs.cpp:4:
In file included from /home/og/polybar/include/drawtypes/label.hpp:4:
In file included from /home/og/polybar/include/components/config.hpp:13:
In file included from /home/og/polybar/include/x11/xresources.hpp:14:
In file included from /home/og/polybar/include/x11/connection.hpp:10:
In file included from /home/og/polybar/include/components/screen.hpp:7:
In file included from /home/og/polybar/include/x11/extensions/randr.hpp:10:
/home/og/polybar/lib/xpp/include/xpp/proto/randr.hpp:3026:42: error: use of
      undeclared identifier 'xcb_randr_get_monitors_reply'; did you mean
      'xcb_randr_get_providers_reply'?
                               **SIGNATURE(xcb_randr_get_monitors_reply),**
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                         xcb_randr_get_providers_reply
/home/og/polybar/lib/xpp/include/xpp/generic/signature.hpp:5:43: note: expanded from
      macro 'SIGNATURE'
  xpp::generic::signature<decltype(NAME), NAME>
                                          ^
/usr/include/xcb/randr.h:3390:1: note: 'xcb_randr_get_providers_reply' declared here
xcb_randr_get_providers_reply (xcb_connection_t                  *c  /**< */,

`

**Comment by jaagr** [comment]
What's the output of:

~~~ sh
$ pkg-config --print-provides xcb-randr
~~~

**Comment by oreHGA** [comment]
It returns 
`og@ogbuntu:~/polybar$ pkg-config --print-provides xcb-randr`
`xcb-randr = 1.11.1`

**Comment by jaagr** [comment]
@oreHGA You will need `xcb-randr>=1.12`. If you can't upgrade, you could fix the build by adding `-DWITH_XRANDR_MONITORS=0` to the argument list in `build.sh` (line 68-75)

**Comment by oreHGA** [comment]
Thanks for the tip, I just got the newer version of `xcb-randr>=1.12`  which fixes the earlier errors but now when i get to 95% it throws another error.
 
`[95%] Linking CXX executable polybar`
`/usr/local/lib/libxcb-shm.so.0: undefined reference to 'xcb_send_request_with_fds'`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`bin/CMakeFiles/polybar.dir/build.make:2029: recipe for target 'bin/polybar' failed`
`make[2]: *** [bin/polybar] Error 1`
`CMakeFiles/Makefile2:798: recipe for target 'bin/CMakeFiles/polybar.dir/all' failed`
`make[1]: *** [bin/CMakeFiles/polybar.dir/all] Error 2`
`Makefile:127: recipe for target 'all' failed`
`make: *** [all] Error 2`
`** Failed to build project`

**Comment by jaagr** [comment]
Hm. Did you manually build `libxcb` (since it's using the lib under `/usr/local`)?

**Comment by oreHGA** [comment]
Yeah I manually built `libxcb` so I could get version `1.12` of the `xcb-randr`.Is that why i'm getting the error?

**Comment by therockmandolinist** [comment]
I'm having this same issue at the moment.

**Comment by patrick96** [comment]
#463 describes how to manually upgrade xrandr to 1.12 and make it work with polybar.
Alternatively you can keep everything at 1.11 and downgrade xcb-proto to 1.11 as described [here](https://github.com/jaagr/polybar/issues/644#issuecomment-314916405)
