### ISSUE TITLE
Add "include" directive in config

### ISSUE THREAD

**Issue by kevlar1818** [jaagr/polybar#550]
My polybar config is nearly 300 lines long, and it's only growing in size. Includes would allow for smaller, more modular config files.

I understand that this was planned early on and then abandoned (see #4), but I'd like to revisit this. I think others may be just as interested in this as I am.

**Comment by jaagr** [comment]
This has already been implemented (see 874e6b0).

Excerpt from [the wiki](https://github.com/jaagr/polybar/wiki/Configuration): 

~~~ dosini
; File contents can be referenced using:
key = ${file:/absolute/file/path:fallback value}
~~~

**Comment by kevlar1818** [comment]
@jaagr That seems to only set individual config variables from the contents of other files. I'd like to include the contents of other files as part of my overall config (e.g. have all my modules in a "modules.conf").

**Comment by jaagr** [comment]
@kevlar1818 could you show an example on how to format it in an `.ini` file?

**Comment by kevlar1818** [comment]
I haven't really thought about it much, but maybe something like:

``` ini
[includes]
; files listed here are added to polybar's config
foo = "/path/to/foo.conf"
```

or

``` ini
[bar/mybar]
...
include = "/path/to/foo.conf"
; support for multiple includes?
include = "/path/to/bar.conf" 
```

**Comment by jaagr** [comment]
@kevlar1818 Hm, check the configuration section on the wiki (just updated). The current directive (`include-file = /path/...`) pretty much works like that.

**Comment by kevlar1818** [comment]
That it does! I either missed that in the wiki, or it wasn't documented until just now. (I know you just updated it. :smile:) I'll experiment with that, but I think it's safe to close this issue.

**Comment by jaagr** [comment]
@kevlar1818 you're right, I forgot to add the feature to the wiki after implementing it. Open a new issue if you encounter any problems with it.
