### ISSUE TITLE
Center module is off center when system tray is on the same bar

### ISSUE THREAD

**Issue by UnicodeAlt255** [jaagr/polybar#551]
In my setup, I have a time module at the center of my bar, but with the system tray on the right of this bar, the time gets pushed left, and with each new tray applet I open, the time module gets pushed more left.

**Comment by jaagr** [comment]
Try changing the value of the bar parameter `fixed-center` (default value is `true`)

**Comment by UnicodeAlt255** [comment]
Already tried that, setting that to false makes it worse.

**Comment by jaagr** [comment]
Could you show me some screenshots of the issue along with a description on how you expect it to behave.

**Comment by UnicodeAlt255** [comment]
![2017-04-26-123818_3840x2160_scrot](https://cloud.githubusercontent.com/assets/12755239/25453332/58049faa-2a7d-11e7-8be1-e77e31dddcda.png)

The time should be centered at the y-axis of that graph.

If I remove system tray it displays correctly:

![2017-04-26-124108_3840x2160_scrot](https://cloud.githubusercontent.com/assets/12755239/25453411/b4c47d1e-2a7d-11e7-90bf-380d88cc10f1.png)

**Comment by UnicodeAlt255** [comment]
With four tray apps:

![2017-04-26-124603_3840x2160_scrot](https://cloud.githubusercontent.com/assets/12755239/25453615/7be32e4a-2a7e-11e7-83fb-cf54aec69d5a.png)

**Comment by jaagr** [comment]
Try this patch:

~~~ diff
diff --git a/src/components/renderer.cpp b/src/components/renderer.cpp
index 964e882..ef34c25 100644
--- a/src/components/renderer.cpp
+++ b/src/components/renderer.cpp
@@ -399,6 +399,11 @@ double renderer::block_x(alignment a) const {
       if ((min_pos = block_w(alignment::LEFT))) {
         min_pos += BLOCK_GAP;
       }
+      if (m_rect.x > 0) {
+        base_pos -= (m_bar.size.w - m_rect.width) / 2.0;
+      } else {
+        base_pos += (m_bar.size.w - m_rect.width) / 2.0;
+      }
       return std::max(base_pos - block_w(a) / 2.0, min_pos);
     }
     case alignment::RIGHT: {
~~~

**Comment by UnicodeAlt255** [comment]
Excuse my ignorance, but how do I use that? I tried to copy that into a renderer.patch and use `patch`, but I got errors.

**Comment by jaagr** [comment]
Use `git apply <patchfile>`

**Comment by FuegoAliado** [comment]
Saw this was still open. Just wanted to mention that patch worked perfectly for me. Thanks.

**Comment by mpcsh** [comment]
This patch worked for me as well. Will it be merged?

**Comment by UnicodeAlt255** [comment]
I can't test this myself because I don't build from source and I'm too busy to figure it out. Based on @FuegoAliado and @mpcsh it seems to work. I hope this is included in an update.

**Comment by Taconut** [comment]
Hmmmm.... It's not working for me. The tray still pushing my centered clock module to the left every time I open something like VLC, etc.

**Comment by FuegoAliado** [comment]
@Taconut It's not an issue with the tray-position. My tray is on the right as well and does not shift regardless of how many notifications I have on the tray.
![2017-06-26-231330_1280x800_scrot](https://user-images.githubusercontent.com/21133680/27569385-4b0f3210-5ac5-11e7-994a-e8e84190fe9e.png)

**Comment by Taconut** [comment]
@FuegoAliado Well I tried both directions multiple times and I'm 100% positive it's only happening when the tray is on the right. I have absolutely no idea why our setups would be any different, but they are.

**Comment by jaagr** [comment]
@Taconut could you post the bar section of your config?

**Comment by jaagr** [comment]
And what version?

**Comment by Taconut** [comment]
My bar config is http://termbin.com/drul and my version is this repo's current HEAD with the commits in pull #426 cherry picked on top. The bar configuration listed works fine but when I change "left" to "right" it pushes the center module to the left when the tray is populated.
