### ISSUE TITLE
issues during cmake .. 

### ISSUE THREAD

**Issue by karambaq** [jaagr/polybar#552]
Some issues when I run cmake .. :
`
- No build type specified; using RelWithDebInfo
-- Using supported compiler GNU-5.4.0
--  Build:
--    Type: RelWithDebInfo
--    CC: /usr/bin/cc  -O2 -g -DNDEBUG
--    CXX: /usr/bin/c++  -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors -O2 -g -DNDEBUG
--    LD: /usr/bin/ld  
--  Targets:
--    polybar-msg
--    testsuite
--  Module support:
--    alsa
--    curl
--    i3
--    mpd
--    network
--  X extensions:
--    xcb-randr
--    xcb-randr (monitor support)
--    xcb-render
--    xcb-damage
--    xcb-sync
--    xcb-composite
--    xcb-xkb
--    xcb-xrm
-- Found font: fixed:pixelsize=10
-- Font not found: unifont:fontformat=truetype
-- Font not found: siji:pixelsize=10
-- XCB[XCB]: Found component XCB
-- XCB[ICCCM]: Found component ICCCM
-- XCB[EWMH]: Found component EWMH
-- XCB[UTIL]: Found component UTIL
-- XCB[IMAGE]: Found component IMAGE
-- Searching for xcbgen with python2
-- Searching for xcbgen with python3
-- Searching for xcbgen with python
CMake Error at lib/xpp/CMakeLists.txt:55 (message):
  Missing required python module: xcbgen

-- Configuring incomplete, errors occurred!
See also "/home/why/qcloud/polybar/build/CMakeFiles/CMakeOutput.log".
See also "/home/why/qcloud/polybar/build/CMakeFiles/CMakeError.log".
`

**Comment by jaagr** [comment]
Install `python` and `xcb-proto`

**Comment by karambaq** [comment]
Already.
I installed all requirements packages from here: https://github.com/jaagr/polybar/wiki/Compiling
I am Ubuntu 16.04 user btw.

**Comment by jaagr** [comment]
OK, the issue you are having is related to the build routine not finding the `xcbgen` python module. Since I'm no Ubuntu user I can't really tell you how to fix it. Someone else might be able to guide you though.

**Comment by skyplane1** [comment]
I'm having the exact same issue on ubuntu 16.04

**Comment by jaagr** [comment]
Do you have `python-xcbgen` installed?

**Comment by skyplane1** [comment]
Thank you so much, i installed the dependencies from the link @karambaq posted and that  worked for me.

**Comment by GuessWhoSamFoo** [comment]
Same error as above on 16.04 with `python-xcbgen` installed. I suspect an Ananconda installation of Python might be causing issues. I'll have to peek into the logs.

**Comment by jaagr** [comment]
@GuessWhoSamFoo you could apply this patch in `lib/xpp`:

~~~ diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3a87cc4..7f9b3f0 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -30,30 +30,7 @@ set(XPP_LIBRARIES
   ${XCB_UTIL_LIBRARY}
   ${XCB_IMAGE_LIBRARY})
 
-#
-# Loop through a hardcoded list of python executables to locate the python module "xcbgen"
-#
-foreach(CURRENT_EXECUTABLE python2 python3 python)
-  message(STATUS "Searching for xcbgen with " ${CURRENT_EXECUTABLE})
-
-  execute_process(COMMAND "${CURRENT_EXECUTABLE}" "-c"
-    "import re,xcbgen;print(re.compile('/xcbgen/__init__.py.*').sub('',xcbgen.__file__))"
-    RESULT_VARIABLE _xcbgen_status
-    OUTPUT_VARIABLE _xcbgen_location
-    ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
-
-  # When a shell script returns successfully its return code is 0
-  if(_xcbgen_status EQUAL 0)
-    set(PYTHON_XCBGEN "${_xcbgen_location}" CACHE STRING "Location of python module: xcbgen ")
-    message(STATUS "Found xcbgen in " ${PYTHON_XCBGEN})
-    break()
-  endif()
-
-endforeach(CURRENT_EXECUTABLE)
-
-if(NOT PYTHON_XCBGEN)
-  message(FATAL_ERROR "Missing required python module: xcbgen")
-endif()
+set(PYTHON_XCBGEN "/usr/lib/python2.7/dist-packages" CACHE STRING "Location of python module: xcbgen")
 
 #
 # Include XCB libs depending on what protos we build
~~~

**Comment by AndreasBackx** [comment]
@jaagr is the Python xcbgen module available on Pypi or is there any easy way to install this on Arch Linux? I'm getting the same error on AUR with `polybar` and `polybar-git`. Would love to be able to install this on one of my Python versions that are managed using pyenv.

**Comment by AndreasBackx** [comment]
Any update on this?

**Comment by AndreasBackx** [comment]
So here's how to get it to work on Arch Linux then. xcb-proto on AUR applies a Python 3.5 patch to make xcb-proto. Otherwise xcb-proto is written for Python 2. So you can remove the patch that is applied in the PKGBUILD and build/install the package thay way so lib/xpp works as it's not compatible with Python 3. Because I'm running pyenv I then had to move the installed folder `/usr/lib/python2.7/site-packages/xcbgen` to my pyenv Python 2.7.x folder `/home/user/.pyenv/versions/2.7.13/lib/python2.7`. Here's the PKGBUILD that I used:

I removed the source for the patch, its checksum, and the prepare function that applied the patch.

```bash
# $Id$
# Maintainer: Andreas Radke <andyrtr@archlinux.org>
# Contributor: Jan de Groot <jgc@archlinux.org>

pkgname=xcb-proto
pkgver=1.12
pkgrel=3
pkgdesc="XML-XCB protocol descriptions"
arch=(any)
url="https://xcb.freedesktop.org/"
license=('custom')
makedepends=('python' 'libxml2')
source=($url/dist/$pkgname-$pkgver.tar.bz2)
sha256sums=('5922aba4c664ab7899a29d92ea91a87aa4c1fc7eb5ee550325c3216c480a4906')

build() {
  cd $pkgname-$pkgver
  ./configure --prefix=/usr
  make
}

check() {
  cd $pkgname-$pkgver
  make -k check || /bin/true
}

package() {
  cd $pkgname-$pkgver
  make DESTDIR="$pkgdir" install
  install -m755 -d "$pkgdir/usr/share/licenses/$pkgname"
  install -m644 COPYING "$pkgdir/usr/share/licenses/$pkgname"
}
```

You can installl it with:
```bash
makepkg -Acsf
# I'm using pacaur, you can just replace it with pacman in this example.
pacaur -U xcb-proto-1.12-3-any.pkg.tar.xz
```

Then the polybar install works as it should. I personally faced #647 and so installed from latest.

**Comment by greysonp** [comment]
I've been having this same problem. I solved it by first force-uninstalling `xcb-proto`:

```bash
sudo pacman -Rdd xcb-proto
``` 

and then replacing it with the AUR package `xcb-proto-git`:

```bash
yaourt -S xcb-proto-git
```

I also was using pyenv and disabled it during debugging, but I don't know if that's necessary or not. I think the main thing was using the new xcb-proto-git. YMMV!

**Comment by xy124** [comment]
Works on ubuntu 18.04:
install all dependencies used the commands listet here: https://github.com/polybar/polybar/wiki/Compiling (e.g. use the copy paste version with apt below the tables)

**AND** do not forget to clone *recursively* to get the submodules! : 

```bash
git clone --recursive https://github.com/polybar/polybar
```

**Comment by mvrozanti** [comment]
This problem has resurfaced. It happened after a system update. I see a bunch of "possible" fixes. Which one is the actual one? Also, why download `xcb-proto-git` when there's `xcb-proto 1.13-2` on the official repositories?

**Comment by patrick96** [comment]
@mvrozanti Which problem exactly? There are a bunch of different one in this thread. Please open a new [build issue](https://github.com/polybar/polybar/issues/new?template=build.md)

**Comment by kenoss** [comment]
FYI, I also faced this problem.  I found that `pyenv` conceals system python and `pyenv local system` solves the problem in my case.

**Comment by DaKeiser** [comment]
If anyone is getting an error `E: Unable to locate package python-xcbgen`, I looked over [here](https://github.com/polybar/polybar/wiki/Compiling#dependencies-1). `sudo apt-get install python3-xcbgen` is a better and a recommended workaround
