### ISSUE TITLE
Temperature module reporting negative numbers at high temps.

### ISSUE THREAD

**Issue by Shippage** [jaagr/polybar#553]
This issue seems to hard to reproduce, but seems to be caused from high temps. I think it's around >78C that my temp goes negative.

My temp module is only slightly modified, but here's the script:
```
[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 65

format = <label>
format-underline = ${colors.accent-color}
format-warn = <label-warn>
format-warn-underline = ${colors.red}

format-padding = 1
format-warn-padidng = 1

label = %temperature%
label-warn = %temperature%

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = #55
```

Also I took a screenshot of it happening:
http://i.imgur.com/JGoI6mP.png

**Comment by x70b1** [comment]
I had sometimes 92 °C here. There is no problem. 
You could check this:

`cat /sys/class/thermal/thermal_zone0/temp`

What is the output?

**Comment by jaagr** [comment]
You could use this command to check the values that the polybar temperature module reads:

~~~ sh
$ cat /sys/class/thermal/thermal_zone*/temp | awk '{ printf "%.0f°C\n", $1/1000 }'
~~~

**Comment by Shippage** [comment]
Waited till I went negative again and got this as an output:

```
zack@shippage:~$ cat /sys/class/thermal/thermal_zone*/temp | awk '{ printf "%.0f°C\n", $1/1000 }'
-50°C
41°C
83°C
```

**Comment by x70b1** [comment]
This means the value is already a wrong at your system. 
A workaround could be to use another sensor. What kind of sensor is your `thermal_zone0`?

Btw. There is a typo mistake at you config. It should be `padding`:
`format-warn-padidng = 1`

**Comment by Shippage** [comment]
Thanks for spotting that, my config is still a work in progress. I'm not sure how to check what my sensor is. If it's a hardware problem, I'm running a Macbook Pro early 2016. If it's a software issue, then I'm running stock Ubuntu 16.10, and I haven't touched anything to do with the thermal zone that I know of.

**Comment by x70b1** [comment]
Yes, at this point the problem is not at polybar. The value is already wrong.
This means we can't help you a lot here.

But you could try a newer kernel version. Maybe there is something broken in your version.
