### ISSUE TITLE
An option to duplicate on all monitors

### ISSUE THREAD

**Issue by rakanalh** [jaagr/polybar#555]
Hello @jaagr,

Since polybar is able to detect connected monitors, it would be great if it can have an option to duplicate polybar on all available monitors. At the moment, i am using autorander postswitch script to do so, but it doesn't work 99% of the time. I was unable to figure out why it doesn't launch polybar when a new monitor is connected/disconnected. Here's my postswitch script:
```
#!/usr/bin/env sh
killall -q polybar
while pgrep -x polybar >/dev/null; do sleep 1; done

unset MONITOR
polybar Main &
polybar HDMI &

```

Thanks

**Comment by rosshadden** [comment]
Yeah I don't have the same name/number of monitors attached to my multiple computers, so it's really weird to me to launch a bar per-monitor.  I just found polybar today and really like the concept, so for now I guess I'll try to write a script that makes it work on all of my setups.

**Comment by arkhan** [comment]
I have this to launch polybar on a laptop and on a desktop computer:

```bash
#!/bin/sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

# Launch bar1 and bar2
DISPLAY1="$(xrandr -q | grep 'eDP1\|VGA-1' | cut -d ' ' -f1)"
[[ ! -z "$DISPLAY1" ]] && MONITOR="$DISPLAY1" polybar top1 &

DISPLAY2="$(xrandr -q | grep 'HDMI1\|DVI-I-1' | cut -d ' ' -f1)"
[[ ! -z $DISPLAY2 ]] && MONITOR=$DISPLAY2 polybar top2 &

echo "Bars launched..."
```

**Comment by rakanalh** [comment]
@arkhan i have the same script... Do you run this script manually? or how does your system detect multiple monitors? i use autorandr which has it's own issues so that doesn't work for me so i think it would be nice if polybar can autodetect a new monitor and duplicate itself depending on the config option.

**Comment by rosshadden** [comment]
I'm doing [this](https://github.com/jaagr/polybar/issues/515#issuecomment-291182433), which works great and automatically creates a polybar on each output.

**Comment by madnight** [comment]
i think polybar should be displayed on all screens by default, since the default usage with a multiple monitor setup is multiple workspaces (i3/bspwm) and you want to know which workspace you are on regardless of the monitor your looking at, however it should still be possible to explicitly specify one or more monitors, to disable polybar on all others

**Comment by binaryplease** [comment]
@rosshadden 
> 'm doing a modified version of this, which works great and automatically creates a polybar on each output.

How do you handle plugging/unplugging of monitors? The script you posted works, but would need to be run every time a monitor is plugged or unplugged, right?

**Comment by rakanalh** [comment]
@binaryplease i am using autorandr for that. But you would notice an issue that the script will be executed multiple times so you'll see polybar come and go but then stops and the bar is shown.

**Comment by rosshadden** [comment]
@binaryplease yes I run it a lot. Haven't automated it yet. 🤣

**Comment by zhou13** [comment]
Running multiple instance is still memory-consuming.  I am looking forward to this feature.

**Comment by r04r** [comment]
Does anyone have a solution that works properly when plugging/removing monitors? I often add a monitor or two using HDMI and would like Polybar to show on each of these outputs. Ideally only showing i3 workspaces that actually are on that output (pin-workspaces=true).

**Comment by binaryplease** [comment]
Any progress on this?

**Comment by patrick96** [comment]
No. We're pretty swamped over here

**Comment by NBonaparte** [comment]
This would be pretty messy to implement if workspace/xwindow modules are used which are specific to the current desktop. We would have to copy the rest of the modules, but keep a separate instance of these ones running to produce different outputs.

**Comment by patrick96** [comment]
I thought, we could just pipe the builder output to multiple renderers and have multiple bars like this, but @NBonaparte is of course right, this would break the xworkspace, xwindow, i3, and bspwm modules. So polybar would have to basically just start multiple instances of itself (which is what a launch script does).

Polybar was never designed to run multiple bars in a single instance, anything requested in this thread would require a major revamp of basically everything in polybar (except maybe for the module code itself). Also part with detecting monitor changes will be just as buggy as anything you can come up with in a bash script. I don't think we will implement this, at least not in the current state polybar is in.
What you should do, is use a startup script that shows polybar on all connected monitors (and kills all old polybar instances) and run that script everytime the monitor configuration changes.
