### ISSUE TITLE
Align text vertically

### ISSUE THREAD

**Issue by rawsh** [jaagr/polybar#556]
I recently switched to polybar after previously using lemonbar, and the one issue I have is that text is higher up on the bar than with other applications. (e.g. for dmenu the text is lower than the bar when I have the same height).

Is there any top padding option I can use to align the text?

**Comment by jaagr** [comment]
The [Fonts wiki page](https://github.com/jaagr/polybar/wiki/Fonts) explains how you can set the vertical offset. For example:

~~~ dosini
# Will move the tamsyn glyphs down 2 pixels
font-0 = Tamsyn:pixelsize=12;2
~~~

**Comment by rawsh** [comment]
@jaagr ok, cool. Thanks!
