### ISSUE TITLE
Displaying the current time in a different time zone

### ISSUE THREAD

**Issue by suprj** [jaagr/polybar#557]
Does anyone know how to do this in polybar? I want to display the current time in my time zone as well as the current time in another time zone.

In bash, the current time from a different time zone can be displayed with:

`TZ=Asia/Singapore date`

**Comment by jaagr** [comment]
You could use the `custom/script` module for this. For example:

~~~ dosini
[module/tz]
type = custom/script
exec = TZ=Asia/Singapore date +"Singapore: %H:%M"
interval = 30
~~~

**Comment by suprj** [comment]
Thank you! Worked like a charm

**Comment by thebitstick** [comment]
Sorry to open this back up, but is there a way of getting date-alt like function out of the script module?  
I want to be able to multiple timezones on my bar and I'm unsure of how to do it with script or the date modules.

**Comment by jaagr** [comment]
@thebitstick do you want to cycle through the time zones when clicking or what do you mean?

**Comment by thebitstick** [comment]
@jaagr either cycling when clicking or automatically after an interval

**Comment by squigglezworth** [comment]
It would be great to have a TZ setting for the date module

**Comment by patrick96** [comment]
@squigglezworth please open a new issue for this feature request.
@thebitstick you could use the `click-left` setting in the script module to somehow send information or toggle a state that the script that prints the date in a certain timezone can read and set the timezone accordingly

**Comment by thebitstick** [comment]
@patrick96 it's not enough to toggle, I need more than two timezones and they should be automatic
I had this functionality with py3status for i3bar

**Comment by patrick96** [comment]
@thebitstick what do you mean by automatic? With `click-left` you can call any script so you can implement any functionality you want, including multiple timezones, you just need to somehow send information from the click-script to the script that displays the time

**Comment by thebitstick** [comment]
Automatic as in it switches without needing to press anything.
Like a slideshow.

**Comment by patrick96** [comment]
You can easily do that in a script
```bash
i=0
while true; do
# Figure out the timezone from the index
...
date
i=$((i+1))
sleep 5
done
```

**Comment by squigglezworth** [comment]
@patrick96 This one and #596, for starters, are both related to the feature I want. 

Funnily, #596 references this one and is closed, even though that's exactly the feature I want.

**Comment by patrick96** [comment]
@squigglezworth I didn't know about #596, I'll reopen it and we will start tracking that feature request over there.
I just didn't want to track a feature request inside an issue that is already resolved with a workaround
