### ISSUE TITLE
How to insert spacing?

### ISSUE THREAD

**Issue by felixsanz** [jaagr/polybar#559]
My config is this:

```
modules-left = i3
modules-center = date weather
modules-right = wireless-network cpu memory temperature pavolume backlight battery powermenu
```

I have icons at the first of every module. Because of that, the modules "date" and "wireless-network" appear with their icon cut in half, because the icon is the first thing in the modules-center and in the modules-right.

How i can create a bigger separation there or add blank spacing before that icons?

Here is a picture showing the error:

http://i.imgur.com/EzJ3dei.png

**Comment by felixsanz** [comment]
format-NAME-padding = N
format-NAME-margin  = N
format-NAME-spacing = N

**Comment by jaagr** [comment]
You can also do:

~~~ dosini
[bar/mybar] 
# Spaces before and after each module 
module-margin = N
~~~

**Comment by felixsanz** [comment]
@jaagr module-margin is what i had at first. But the result was the image above
