### ISSUE TITLE
Feature request: Referencing current ramp & more

### ISSUE THREAD

**Issue by palmenros** [jaagr/polybar#560]
Sometimes I need to reference the current ramp from a label, for example, in my battery or wireless module, I want both my percentage and ramp icon to be of the same color, but placeholders do not work in ramps, so an option would be to add a way to reference the current ramp (or conditional formatting). I also miss a way to replace the default functionality of volume module, and a way to have a general alt option, like date-alt. The last think I would want to know is if there is a way to send via IPC a request to update a module,  so there is no need for intervals. Thanks.

**Comment by jaagr** [comment]
Closing. I'll add a reference to this in #84
