### ISSUE TITLE
Reload running polybar instance in-place

### ISSUE THREAD

**Issue by Jezorko** [jaagr/polybar#563]
i3 has a [nice feature](https://i3wm.org/docs/userguide.html#_reloading_restarting_exiting) of reloading it's config without killing / launching it back.
It would be nice to have the same functionality with polybar, so it won't [blink](http://i.imgur.com/7vHia2c.gif) while being reconfigured. (:

EDIT: similar to [this](https://github.com/jaagr/polybar/issues/84#issuecomment-253964985), but a command-line parameter instead of a signal.

**Comment by zxvfxwing** [comment]
+1 a must have

**Comment by FireAntJoe** [comment]
Any idea if anyone is working on this?

**Comment by gabrielsimoes** [comment]
I don't see a problem with killing it and launching again... I have a script that does this (kills if exists and launches polybar) and I execute it at i3 startup with exec_always, so that everytime I reload i3 polybar also reloads.

**Comment by Jezorko** [comment]
@gabrielsimoes I'm doing the same thing (kill and start again), but I don't think scripting out every missing functionality is a way to go...

**Comment by Deomkan** [comment]
I think it is a work in progres [issue 17](https://github.com/jaagr/polybar/issues/17)

**Comment by Jezorko** [comment]
@Deomkan the issue you've linked to is marked as closed but it is still present in version 3.0.5

**Comment by Deomkan** [comment]
There is this command: 
`polybar -r bar`
You have to launch polybar in that way, and every time config file is changed, bar will reaload automatically

**Comment by Jezorko** [comment]
@Deomkan How did I miss it :O
My apologies!

**Comment by Jezorko** [comment]
I'd like to reopen this issue for a slightly different reason.
Let's say the configuration contains `.Xresources` references, example [here](https://github.com/Jezorko/dotfiles/blob/e19319f1e25b64475bb3f51c52d4247f091f0ac9/.config/polybar/config#L25).
If the resource is changed in the `.Xresources` file, polybar does not reload its' config. It means it has to be restarted manually.

I'd like to be able to send a signal or perhaps run polybar with some parameter that would send a signal to currently running instance so it knows the config should be reloaded.

**Comment by patrick96** [comment]
You can issue the command `polybar-msg cmd restart`, which will restart all the bars. So you can call the command whenver you change the `.Xresources` file.
You'll need to enable ipc in the bar though:
```dosini
enable-ipc = true
```

**Comment by Jezorko** [comment]
@patrick96 it works, thank you!
