### ISSUE TITLE
FontAwesome icons not displaying in i3 module

### ISSUE THREAD

**Issue by arkostin** [jaagr/polybar#565]
Hi, here's the relevant part of my polybar config:
`ws-icon-0 = 1;`
`ws-icon-1 = 2;`

Here's the relevant part of my i3 config:
`set $ws1 "1"`
`set $ws2 "2"`
`bindsym $mod+1 workspace $ws1`
`bindsym $mod+2 workspace $ws2 `
`bindsym $mod+Shift+1 move container to workspace $ws1`
`bindsym $mod+Shift+2 move container to workspace $ws2`

FontAwesome declaration in polybar config:
`font-0 = Roboto:pixelsize=12;1`
`font-1 = FontAwesome:pixelsize=10;0`
`font-2 = System San Francisco Display:size=10;2`

[Full .config](https://github.com/arkostin/.config)
Polybar still only displays the numbers [1-10] fro workspaces, any help?

**Comment by jaagr** [comment]
~~~ dosini
label-focused = %icon%
label-unfocused = %icon%
label-visible = %icon%
label-urgent = %icon%
~~~

**Comment by arkostin** [comment]
Works, thanks!
