### ISSUE TITLE
stty standard input inappropriate ioctl for device

### ISSUE THREAD

**Issue by madnight** [jaagr/polybar#566]
I simply try this example from the wiki
```
[module/vpn]
type = custom/script
exec = echo vpn
exec-if = pgrep -x openvpn
interval = 5
format-underline = #268bd2
format-prefix = "🖧 "
format-prefix-foreground = #5b
```
(openvpn is running) i can also try only echo without exec-if always the same error
but also any other custom script fails with the message:
`stty standard input inappropriate ioctl for device`

![](https://i.imgur.com/Yj63MoY.png)
![](https://i.imgur.com/ZXvDE47.png)

**Comment by madnight** [comment]
okay 2 hours later ...
i changed my login shell with `chsh` from zsh to bash and now it works ...

**Comment by jaagr** [comment]
I'm using zsh myself and I have no issues with it.

Do you have any `stty` commands in `.zshrc`? Anyway, I wouldn't say this is an issue with polybar.

**Comment by madnight** [comment]
hmm but non-interactive shells (zsh running a single command) shouldnt load .zshrc as far as i know, otherwise a non-interactive shell would also load left and right prompts, auto completion ... and many more stuff that isnt needed. 

Maybe you should check if polybar use a interactive shell for custom command execution.

**Comment by jaagr** [comment]
Yeah but child processes inherit the environment. The commands are executed using `$SHELL -c <command>`

**Comment by madnight** [comment]
okay thx, maybe you could even force sh, so instead of `$SHELL -c` using `/bin/sh -c`. Every sensible environment has /bin/sh (even when its a symlink). I dont think that you have to support every shell on the planet : )

**Comment by jaagr** [comment]
`SHELL=/bin/sh polybar ...` would give you the same behavior. Just use a wrapper to avoid having to type it out.

**Comment by madnight** [comment]
Jup, but no wrapper needed with conkys solution: https://github.com/brndnmtthws/conky/blob/master/src/exec.cc#L98

This also avoids other confusing default shell related errors in the future for other users.

**Comment by jaagr** [comment]
Yeah but I said earlier, use it for now. A fix won't be available until I get some free time.

**Comment by madnight** [comment]
yes sir : ) however polybar is the best bar i used so far!
