### ISSUE TITLE
12 Hour Clock

### ISSUE THREAD

**Issue by Hacksaurus** [jaagr/polybar#571]
Hello!
I have a simple request and that is, how to make a 12 hour clock in polybar?
What I want is that it shows the the time in 12 hour format and then shows either AM or PM.

Thanks for any help!

**Comment by arkhan** [comment]
Try 

%I:%M %p

**Comment by Hacksaurus** [comment]
Thank you! It works, but I now whenever I show my date-alt I cannot go back and see my normal date? Is this a bug?

**Comment by Hacksaurus** [comment]
![image](https://cloud.githubusercontent.com/assets/24832107/25880463/5df962fa-34ec-11e7-9cb5-d057c168400c.png)
This is what happens...

**Comment by jaagr** [comment]
All format tags need to be written like `%%{...}` and I see that you've missed that on a few places so that's probably what's causing the issue.

**Comment by Hacksaurus** [comment]
This is what I have right now... but this does not work...
```vim
[module/date]
type = internal/date
date =    %%{F#99} %m/%d/%Y %%{F-}  %%{F#fff} %I:%M%p%{F-}
date-alt =    %%{F#fff} %A, %B %d, %Y %%{F-} %%{F#fff} %I:%M%p%{F#666} %%{F#fba922}%S%%{F-}
```
However this works:
```vim
[module/date]
type = internal/date
date =    %%{F#99} %m/%d/%Y %%{F-}  %%{F#fff} %I:%M%p%{F-}
date-alt =    %%{F#fff} %A, %B %d, %Y %%{F-} %%{F#fff} %I:%M%p %{F#666} %%{F#fba922}%S%%{F-}
```
All I have done is add a space between %p and %{F#666} in the third line, but this makes a real weird space after the PM in this gif...
![weird space](https://cloud.githubusercontent.com/assets/24832107/25928635/27dcee46-35b2-11e7-9d79-51bd0e7569b4.gif)



How do I fix this?

**Comment by Hacksaurus** [comment]
NVM I figured it out!
Closing Thread!

**Comment by jaagr** [comment]
Please post the solution in case someone else is having the same issue.

**Comment by Hacksaurus** [comment]
Huh It doesn't seem to work now... Can check if what is wrong with this:
```vim
[module/date]
type = internal/date
date =    %%{F#99} %m/%d/%Y %%{F-} %%{F#fff} %I:%M %p%{F-}
date-alt =    %%{F#fff} %A, %B %d, %Y %%{F-} %%{F#fff} %I:%M %p%{F#666}%%{F-} %%{F#fba922}%S%%{F-}
```

**Comment by jaagr** [comment]
Replace `%{F-} ` with `%%{F-} ` at the end of `date`

**Comment by Hacksaurus** [comment]
No dice...

**Comment by Hacksaurus** [comment]
Ok, I'll try your fix when I go home...

**Comment by jaagr** [comment]
You can actually just remove `%{F#666}` from `date-alt` since there's a reset tag right after it.

**Comment by Hacksaurus** [comment]
Wait seriously?... That's what ```vim
%%{F#fba922}%S%%{F-}
```
does?.... Why do you have that in your space config then?... 
This is the date module in your space config...
```vim
[module/date]
type = internal/date
date =    %%{F#99}%Y-%m-%d%%{F-}  %%{F#fff}%H:%M%%{F-}
date-alt = %%{F#fff}%A, %d %B %Y  %%{F#fff}%H:%M%%{F#666}:%%{F#fba922}%S%%{F-}
```

**Comment by jaagr** [comment]
You don't seem to read my comments. You're still using `%{F-}` in there.

**Comment by jaagr** [comment]
Just checked the polybar config in my space theme and it's nothing wrong with its date module.

**Comment by Hacksaurus** [comment]
When I try to use the space config I cannot go back to the regular date... And when I do the very last one ```%%{F-}```, it doesn't work... If I do ```%{F-}```, it works every time. So I just decided to make it all ```%{F-}```...

**Comment by Hacksaurus** [comment]
Ok I think this data module has a bug. Whenever I fix it, reboots it works... But then the next day, it doesn't work! I've tried your solution, it works, but it whenever I go to date-alt there is a % sign at the end of the text. So I've edited to that it looks like this:
```vim
date =    %%{F#99}%m/%d/%Y %%{F-} %%{F#fff}%I:%M %p %%{F-}
date-alt =    %%{F#fff}%A, %B %d, %Y %%{F-} %%{F#fff}%I:%M %p %%{F-}
```
It worked perfectly fine, but I checked it today... and it doesn't work! Is this being affected by AM or PM? I have no idea.

**Comment by Hacksaurus** [comment]
This is super weird:
if the time is currently AM this configuration works:
```vim
[module/date]
type = internal/date
date =    %%{F#99} %m/%d/%Y %{F-} %%{F#fff} %I:%M %p %{F-}
date-alt =    %%{F#fff} %A, %B %d, %Y %{F-} %%{F#fff} %I:%M %p %{F-}
```
If the time is currently PM this configuration works:
```vim
[module/date]
type = internal/date
date =    %%{F#99}%m/%d/%Y %%{F-} %%{F#fff}%I:%M %p %%{F-}
date-alt =    %%{F#fff}%A, %B %d, %Y %%{F-} %%{F#fff}%I:%M %p %%{F-}
```
I have no idea why this is the case... @jaagr I think there is a bug here...

**Comment by Hacksaurus** [comment]
Now the first configuration works for AM and PM! I really have no idea how this is working....

**Comment by jaagr** [comment]
I will have a look at it once I have some time.

**Comment by Hacksaurus** [comment]
Thank you! I was going sort of frustrated with this... Sorry if I posted a little too much!

**Comment by jaagr** [comment]
@Hacksaurus could you try this module config:

~~~ dosini
[module/date]
type = internal/date
format-prefix = "   "
label = %{F#99}%date%%{F-}   %{F#fff}%time%%{F-}
date = %m/%d/%Y
date-alt = %A, %B %d, %Y
time = %I:%M %p
time-alt = ${self.time}
~~~

**Comment by Hacksaurus** [comment]
Ok I will try that when I get home... Right now the first configuration is working perfectly fine...

**Comment by Hacksaurus** [comment]
It seems to be working! Thank you!
Closing thread!

**Comment by 3301n** [comment]
> This is what happens...
> ![revert back to normal date](https://cloud.githubusercontent.com/assets/24832107/25880486/83a6This is what happens...
![revert back to normal date](https://cloud.githubusercontent.com/assets/24832107/25880486/83a63866-34ec-11e7-9e6d-511f3200b936.gif)3866-34ec-11e7-9e6d-511f3200b936.gif)

Can you provide your dotfile so that i can make the polybar like yours?

**Comment by TheBabu** [comment]
My github has my dotfiles linked https://github.com/TheBabu/Dotfiles

**Comment by KDSGYT** [comment]
> Try
> 
> %I:%M %p
> 
> http://www.cplusplus.com/reference/ctime/strftime/

This seems to be the right solution
