### ISSUE TITLE
Incorrect pulse audio volume level

### ISSUE THREAD

**Issue by mpcsh** [jaagr/polybar#573]
Hey,

I'm just using plain ol' pulseaudio. I've included a table of true volumes mapped to volumes displayed in polybar.

| true volume | polybar volume |
| --------------- | --------------------- |
| 0% | 0% |
| 5% | 0% |
| 10% | 8% |
| 15% | 24% |
| 20% | 35% |
| 25% | 44% |
| 30% | 51% |
| 35% | 58% |
| 40% | 63% |
| 45% | 67% |
| 50% | 72% |
| 55% | 75% |
| 60% | 79% |
| 65% | 82% |
| 70% | 86% |
| 75% | 88% |
| 80% | 90% |
| 85% | 93% |
| 90% | 95% |
| 95% | 97% |
| 100% | 100% |

As you can see, the bar is way off. Setting `mapping = true` doesn't do anything. What gives?

**Comment by mpcsh** [comment]
Fixed it by installing `pulseaudio-alsa`. Might want to double-check the wiki...

**Comment by rosshadden** [comment]
I have `pulseaudio-alsa` installed but still get this problem.  I've had it installed for over a year, so it was definitely present while building. =\

I'm going to try the user-contributed pulseaudio module.
