### ISSUE TITLE
Cannot use internal/fs: "name not valid"

### ISSUE THREAD

**Issue by benjaminshafii** [jaagr/polybar#574]
Hey I'm getting an error when trying to use `internal/fs`
Polybar version:
```
/bin/polybar --version
polybar 3.0.5-10-g5c41e3d

Features: +alsa +curl +i3 +mpd +network
````
The error:
```
error: Failed to get contents for "module/filesystem" (err: locale::facet::_S_create_c_locale name not valid)
error: Failed to get contents for "module/filesystem" (err: locale::facet::_S_create_c_locale name not valid)
error: Invalid _XEMBED_INFO for window 0x400040f
```
the last line is probably unrelated as I do get that error even when I'm not loading the module but I'm providing it to have maximum context.

This happening even though I stripped most of the options from the module
```
[module/filesystem]
type = internal/fs

; Mountpoints to display
mount-0 = /
```

**Comment by jaagr** [comment]
Hi. Could you paste the output of:

~~~ sh
$ locale
~~~

**Comment by benjaminshafii** [comment]
Here it is
```
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by jaagr** [comment]
Do you use the `locale` property in your polybar configuration?

**Comment by benjaminshafii** [comment]
I do! tI works if I change it!
I was using de_DE.UTF-8 locale in the config while my system was configured with en_US.UTF-8
would you mind giving me some insights as to why this happened?

**Comment by jaagr** [comment]
You need to generate the libc locale before using it in polybar. I don't know what system you are using but for example in Ubuntu you would run `locale-gen de_DE.UTF-8`
