### ISSUE TITLE
Void octoxbps-notifier not showing updates

### ISSUE THREAD

**Issue by mrneilypops** [jaagr/polybar#577]
I have a problem getting octoxbps-notifier to show updates in polybar on openbox (by changing to colour red).
I have tried different time intervals,manual check and delaying octoxbps-notifier at start up.
_Interestingly, if I update from the terminal, while the updates are being downloaded and applied the notifier turns red as expected and then back to green as expected at the end of the update._
sudo xbps-install -Syu

octoxbps-notifier works OK on my Void xfce box with xfce4-panel.

Any ideas welcome.
Could we have a module for octoxbps-notifier?

**Comment by jaagr** [comment]
Are you trying to have a polybar module that shows if there are xbps package updates available? Could you show me the relevant part in your config?

**Comment by mrneilypops** [comment]
Hi Michael,

No, This is the notifier that appears in the system module from 
octoxbps-notifier;

https://github.com/aarnt/octoxbps/tree/master/notifier/octoxbps-notifier

A dedicated polybar module would be nice...

Regards,

Neil

**Comment by jaagr** [comment]
So the application shows an icon in the systray? I will have to try the application once I get some free time on my hands to see what the issue is.

**Comment by mrneilypops** [comment]
Yes, however it only appears to indicate correctly during a manual 'sudo 
xbps-install -Syu'

**Comment by jaagr** [comment]
@mrneilypops The systray icon appears for me. I don't really see how this is an issue with polybar.

**Comment by mrneilypops** [comment]
Hi Michael,

Yes!

The systray icon appears in polybar but it is not indicating that 
updates are available...at least on openbox wm on Void linux.

The systray icon works perfectly on xcfe desktop with xfce4 panel...on 
Void linux.

Any thoughts why the systray icon might not be functioning on openbox?

Regards,

Neil

**Comment by mrneilypops** [comment]
Small note. Vpnd works in polybar on openbox and displays updates.
https://forum.voidlinux.eu/t/vpnd-void-package-notifier/2667

**Comment by patrick96** [comment]
Does the systray icon work on xfce desktop using polybar?
