### ISSUE TITLE
With headphone-mixer set, non-headphone volume always displays as muted

### ISSUE THREAD

**Issue by noctuid** [jaagr/polybar#578]
`amixer -c 0 scontrols` output:

```
Simple mixer control 'Master',0
Simple mixer control 'Headphone',0
Simple mixer control 'Speaker',0
Simple mixer control 'PCM',0
Simple mixer control 'Mic',0
Simple mixer control 'Mic Boost',0
Simple mixer control 'Beep',0
Simple mixer control 'Capture',0
Simple mixer control 'Auto-Mute Mode',0
Simple mixer control 'Internal Mic Boost',0
Simple mixer control 'Loopback Mixing',0
```
`amixer -c 0 controls` output:
```
numid=17,iface=CARD,name='Headphone Jack'
numid=16,iface=CARD,name='Internal Mic Phantom Jack'
numid=15,iface=CARD,name='Mic Jack'
numid=18,iface=CARD,name='Speaker Phantom Jack'
numid=14,iface=MIXER,name='Master Playback Switch'
numid=13,iface=MIXER,name='Master Playback Volume'
numid=2,iface=MIXER,name='Headphone Playback Switch'
numid=1,iface=MIXER,name='Headphone Playback Volume'
numid=23,iface=MIXER,name='PCM Playback Volume'
numid=11,iface=MIXER,name='Mic Boost Volume'
numid=7,iface=MIXER,name='Mic Playback Switch'
numid=6,iface=MIXER,name='Mic Playback Volume'
numid=10,iface=MIXER,name='Capture Switch'
numid=9,iface=MIXER,name='Capture Volume'
numid=5,iface=MIXER,name='Loopback Mixing'
numid=8,iface=MIXER,name='Auto-Mute Mode'
numid=20,iface=MIXER,name='Beep Playback Switch'
numid=19,iface=MIXER,name='Beep Playback Volume'
numid=12,iface=MIXER,name='Internal Mic Boost Volume'
numid=4,iface=MIXER,name='Speaker Playback Switch'
numid=3,iface=MIXER,name='Speaker Playback Volume'
numid=22,iface=PCM,name='Capture Channel Map'
numid=21,iface=PCM,name='Playback Channel Map'
```

Config:
```
type = internal/volume
master-soundcard = hw:0
speaker-soundcard = hw:0
headphone-soundcard = hw:0
speaker-mixer = Speaker
headphone-mixer = Headphone
headphone-id = 3
```

Is the id supposed to be the relative order within the `iface=CARD` entries? If I set the `headphone-id` to 3 (or 1 or 2), it will work as expected when I have headphones plugged in, but when the headphones are not plugged in, it will always use `format-muted` and always show the volume as 0%. If I set `headphone-id` to 4, it will always use `format-muted` but the percentage will be correct if the volume is not muted (otherwise it will be 0). No higher IDs work (e.g. `error: Disabling module "volume" (reason: Could not find control with id 17)`).

**Comment by jaagr** [comment]
`headphone-id` should be the `numid` of the ctrl used to determine if the headphones are plugged in or not. In your case I'd say it's `17` or `18`. Could you post the output generated by `alsa-info.sh`?

**Comment by noctuid** [comment]
I get the same error if I try `18` for `headphone-id` as with `17`. [Here](http://www.alsa-project.org/db/?f=e34ba1fa8863bf5b2c0e9447821fcb93113f93d4) is the output.

**Comment by jaagr** [comment]
I see that you are running pulseaudio, which isn't officially supported by the volume module (will add a note about it in the wiki). I have no experience with it so I can't really help you.
