### ISSUE TITLE
No example config file

### ISSUE THREAD

**Issue by alecjstew** [jaagr/polybar#580]
I followed the installation/compiling steps and got polybar all installed. However, when I run
`$ install -Dm644 /usr/share/doc/polybar/config $HOME/.config/polybar/config`
I get the following error:
`install: cannot stat '/usr/share/doc/polybar/config': No such file or directory`
Where can I find the example configuration file?

**Comment by alecjstew** [comment]
I read through the README  too fast. Solve my problem!

**Comment by emme1444** [comment]
How could that've solved your problem? When they do the same thing? I really want to know. I've been searching for hours now! I can't get hold of that default config file. There really is no way to get `/usr/share/doc/polybar/config` file to appear. 

Please help me!

**Comment by patrick96** [comment]
@emme1444 As stated on the [main wiki page](https://github.com/jaagr/polybar/wiki), the sample config is either in `/usr/local/share/doc/polybar/config` or `/usr/share/doc/polybar/config` after you have installed polybar.
