### ISSUE TITLE
Basic help about polybar and fonts (Ubuntu 14.04)

### ISSUE THREAD

**Issue by alecive** [jaagr/polybar#582]
Hello,

I've been trying to use polybar but I have issues with its functioning. Specifically, I don't understand how to make fonts work. I downloaded the default config for the [space](https://github.com/jaagr/dots/tree/master/.local/etc/themer/themes/space) theme, and I am currently using the following fonts (where `Termynus` has been replaced by `SourceCodePro`):

```
font-0 = NotoSans-Regular:size=8;0
font-1 = unifont:size=6;-3
font-2 = FontAwesome:size=8;-2
font-3 = NotoSans-Regular:size=8;-1
font-4 = MaterialDesignIcons:size=10;-1
font-5 = SourceCodePro:size=10;0
```

I think I managed to install them all; as you can see here `fc-match` finds them:

```
(~/.config/bspwm) (master) 
[alecive@malakim]$ fc-match NotoSans-Regular:size=8;
NotoSans-Regular.ttf: "Noto Sans" "Regular"

(~/.config/bspwm) (master) 
[alecive@malakim]$ fc-match unifont:size=6;
unifont.ttf: "unifont" "Medium"

(~/.config/bspwm) (master) 
[alecive@malakim]$ fc-match FontAwesome:size=8;
FontAwesome.otf: "FontAwesome" "Regular"

(~/.config/bspwm) (master) 
[alecive@malakim]$ fc-match MaterialDesignIcons:size=10;
materialdesignicons-webfont.ttf: "Material Design Icons" "Regular"

(~/.config/bspwm) (master) 
[alecive@malakim]$ fc-match SourceCodePro:size=10;
SourceCodePro-Medium.ttf: "Source Code Pro" "Medium"
```

Now, when running polybar, I have the following output:

```
[alecive@malakim]$ ./polybar.sh 
warn: The config parameter `module/bspwm.label-active` is deprecated, use `module/bspwm.label-focused and label-dimmed-focused` instead.
warn: ${BAR.key} is deprecated. Use ${root.key} instead
error: Undefined bar: external_bottom
error: Disabling module "mpd" (reason: No built-in support for 'internal/mpd')
error: Disabling module "volume" (reason: Cannot find simple element)
error: Disabling module "wireless-network" (reason: No built-in support for 'internal/network')
error: Disabling module "wired-network" (reason: No built-in support for 'internal/network')
error: Disabling module "battery" (reason: No suitable way to get current capacity value)
warn: Dropping unmatched character  (U+f26c)
warn: Dropping unmatched character  (U+f26c)
warn: Dropping unmatched character  (U+f26c)
warn: Dropping unmatched character  (U+f26c)
warn: Dropping unmatched character  (U+e8ac)
warn: Dropping unmatched character  (U+e1ac)
warn: Dropping unmatched character  (U+e924)
warn: Dropping unmatched character  (U+f26c)
```

Please disregard the errors, let's just focus on the "Dropping unmatched character" warnings. Anyway, as you can imagine, most of the panel(s) is gone. Which is fine since most of the modules are disabled. My questions at this point are:

  1. Why do I still have the "Dropping .." warning? Since all the fonts are there, shouldn't they disappear?
  2. How can I understand where these fonts are called from?

Thank you in advance for any help!

**Comment by jaagr** [comment]
Hi,

1. Yeah they should, but the fonts that you have installed might be different (version, etc) from the ones I used when creating the theme.
2. You could copy the unicode symbol from the log message and search for it in your configuration.

**Comment by patrick96** [comment]
The icons `U+e8ac`, `U+e1ac` and `U+e924` is from the material icons font which you don't have listed here. `U+f26c` is in both FontAwesome and MaterialDesignIcons so it seems strange that this one is not recognized. I am not on Ubuntu so my code points may be different than yours, you should use `gucharmap` (See [Wiki](https://github.com/jaagr/polybar/wiki/Fonts) for more details) to figure out the codepoints on your system

@jaagr Does polybar give a warning if a font is not found?

**Comment by alecive** [comment]
> @jaagr Does polybar give a warning if a font is not found?

As far as I know, no. This is the main issue: the user does not really know if the fonts are loaded properly, or if something is missing.

**Comment by patrick96** [comment]
If you run `polybar -l info BAR`, it will tell you what fonts it loaded, it is possible that if the font name is not exactly right, it will just load the default font.

**Comment by patrick96** [comment]
I think we can close this. There is enough information on the [Wiki](https://github.com/jaagr/polybar/wiki/Fonts) to solve problems like this. There are also more than enough closed font issues
