### ISSUE TITLE
Possible to pass values defined in config file to custom/script?

### ISSUE THREAD

**Issue by olmokramer** [jaagr/polybar#585]
I'm writing a `custom/script` that reverses the fore/background colors on a *part of* its `%output%`, so I'd like to pass the colors I defined in the config file to that script, e.g.
```ini
[module/my-module]
type = custom/script
exec = /path/to/my/script.sh ${colors.foreground} ${colors.background}
```
so that I can use these colors in the script `/path/to/my/script.sh`, but bash gives me an error: `/bin/bash: ${colors.foreground}: bad substitution`. Is there a way to pass the colors to the script?

Another way to solve this (and that may be nice to have in general) is to have another formatting specifier that swaps the fore- and background colors, like the `%{R}` from [lemonbar](https://github.com/LemonBoy/bar).

**Comment by olmokramer** [comment]
Aaand... I find a solution right after I post the answer, but it's not very neat... I can use the `--dump` cli option to query the fore/background color from within the script. Only problem is that I don't necessarily *know* from within the script which bar to query, so I set up an extra bar with the correct colors:

```ini
; ~/.config/polybar/config
[bar/colorsbar]
background = ${colors.background}
foreground = ${colors.foreground}

[bar/my-bar]
modules-right = my-module

[module/my-module]
type = custom/script
exec = ~/.config/polybar/my-script.sh
```

Then I can query the colors from within my script:
```sh
#!/bin/sh
# ~/.config/polybar/my-script.sh
fg_color=$(polybar --dump=foreground colorsbar)
bg_color=$(polybar --dump=background colorsbar)

echo "%{B$fg_color F$bg_color}abc%{B- F-}def"
```
The above script will output `abc` with reversed colors, then `def` with the regular colors. I hope you can see why this feels a bit dirty (but hey, it works!)...

**Comment by jaagr** [comment]
Hi, the `%{R}` tag is already supported but I noticed that it wasn't in the wiki. The in-string references has been requested before and I agree that it would be a nice feature to have.

**Comment by olmokramer** [comment]
D'oh why didn't I check if `%{R}` actually worked! Thanks!

**Comment by olmokramer** [comment]
Although it works okay in my case, I've found some unexpected (to me) behavior of the `%{R}` specifier. Consider
```ini
[module/test]
type = internal/xwindow
format-foreground = #fff
format-background = #000
format = A %{B#f00 F#0f0} B %{R} C %{R} D %{B- F-} E
```
This is the actual output I get with the above: ![polybar](https://cloud.githubusercontent.com/assets/3612514/26159645/6d57c1ea-3b1f-11e7-903f-2ad1f0237196.png) (the purple/white are my default back/foreground), while I expected it to produce ![polybar](https://cloud.githubusercontent.com/assets/3612514/26160172/d16dc67e-3b20-11e7-992f-5f7b24e6322a.png) in this case. It seems like `%{R}` is equivalent to `%{B${root.foreground} F${root.background}}` instead of the *current* fore/background.

**Comment by jaagr** [comment]
I'd consider it a bug. Will have a look at it.

**Comment by olmokramer** [comment]
Awesome, thanks! And you're totally right about my expectations, the `E` should indeed have a black background. 0bd8f1f seems to have fixed it.

**Comment by shtanton** [comment]
Is it still impossible to pass a variable to a script i.e.
`exec ~/something.sh ${my.data}`

**Comment by patrick96** [comment]
@shtanton Yes, still impossible. See #954. I'm working on fixing this with #1237
