### ISSUE TITLE
Specific non-interaction with polybar, xdotool and openbox

### ISSUE THREAD

**Issue by Azphreal** [jaagr/polybar#592]
I'm really not sure what to call this. I'm getting a niche issue where something here won't work with the rest, and it's frustrating the hell out of me.

I have a hotkey in openbox's config to open its menu on CTRL+SHIFT+m.

`xdotool key ctrl+shift+m` opens this menu. The physical keypress also opens it.  
`click-right = xdotool key ctrl+shift+m` in polybar does not open this menu.  
`click-right = xdotool key super+a` in polybar *does* toggle my drop-down terminal, as expected. So it doesn't seem to be an issue with `xdotool`.

A script containing just `xdotool key ctrl+shift+m` has the same result: running the script opens the menu, running the script through polybar does not.

Here's the kicker.

Running `xdotool click 3` (simulating a right click) with the mouse hovered over the bar, with  
`click-right = xdotool key ctrl+shift+m` *does* open the menu.

Left clicking the bar with
`click-left = xdotool click 3` and  
`click-right = xdotool key ctrl+shift+m` does *not* work.

Sorry if this isn't actually polybar's fault.

**Comment by jaagr** [comment]
Hm not really sure what might causing this. Could you try using `click-left = sleep 1; xdotool click 3`

**Comment by Azphreal** [comment]
That one works. It also works with a smaller delay like 0.05. That works for me, and it's as good as instant, so I might just go with that.
