### ISSUE TITLE
Use Boost.DI and Boost.Signals2?

### ISSUE THREAD

**Issue by bennofs** [jaagr/polybar#593]
Currently, there is quite a bit of template heavy code with not much documentation for supporting signals. Also, all the `::make` functions seem to be implementing dependency injection manually, for which one could use [Boost.DI](https://github.com/boost-experimental/di). 

Would you be open to that? Or do we want to avoid a dependency as large as Boost? I think it could make the code base more understandable by using existing, documented techniques instead of rolling our own. But at the same time, maybe it is just overkill for the needs of polybar?

**Comment by jaagr** [comment]
@bennofs I was actually using **Boost.DI** before, but replaced it with the plain `::make` functions when dropping dependencies. Can't remember the main reason for dropping it, but I guess it felt a bit overkill for this simple use-case. I'm open for changes however.

**Comment by bennofs** [comment]
I think you are right that this is overkill. Now having worked with the code base a little bit more, it's actually quite understandable the way it is right now. Most of the template heavy stuff actually seems to come from xpp.
