### ISSUE TITLE
double-width font characters diplayed incorrectly

### ISSUE THREAD

**Issue by N4d4** [jaagr/polybar#601]
I'm trying to use some characters from [powerline-extra-symbol](https://github.com/ryanoasis/powerline-extra-symbols) as suffixe and prefixe for the time module

![polybar](https://cloud.githubusercontent.com/assets/19915501/26680783/f27d4702-46da-11e7-92a3-2461693f964c.png)

As you can see from the screenshot they're shown cut in half
How can i fix this?

this is my config
```
[module/time]
type = internal/date
time = %H:%M
time-alt = %H:%M:%S
label =  %time%
	
format-prefix = 
format-prefix-foreground = ${colors.background-alt}
format-prefix-background = ${colors.background}

format = "  <label> "
format-background = ${colors.background-alt}
	
format-suffix = 
format-suffix-foreground = ${colors.background-alt}
format-suffix-background = ${colors.background}

```

**Comment by NBonaparte** [comment]
Seems to be a font issue. This occurs in other applications as well, so there's not really anything we can do about this. The glyph has a set height which is less than the height of the bar, so this happens.
