### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by TheAnonymousSpy** [jaagr/polybar#609]
Hello Jaagr.
I'm running Arch linux with i3-gaps and i wanted to install your awesome statusbar, but i ran in this error:
[error.txt](https://github.com/jaagr/polybar/files/1055289/error.txt)
I also tried to install this on my other machine running Antergos + i3wm

Please help me

**Comment by x70b1** [comment]
At the moment there are problems with the new gcc version in Arch.
See:   https://github.com/jaagr/polybar/issues/572

**Comment by jaagr** [comment]
Hi, the `PKGBUILD` have been updated to use clang until the gcc issues have been fixed so you should be able to build it now.
