### ISSUE TITLE
Error with nerd-fonts

### ISSUE THREAD

**Issue by phineas0fog** [jaagr/polybar#610]
Hello,
With the new version of "nerd-font-complete", I have a problem with polybar... I don't know if the problem comes from polybar or the font...
There is the problem :
 
[after update](http://i.imgur.com/8GjDYfr.png)
[before update](http://i.imgur.com/sVyjbTa.png)

Obvisouly, what I want is the look BEFORE the upgrade...
Thanks a lot :D

**Comment by jaagr** [comment]
I doubt that the issue is caused by polybar. It looks like the glyph you use as the block separator was changed in the font. You could view the glyph of the font using a tool like `gucharmap` (see https://wiki.gnome.org/action/show/Apps/Gucharmap).
