### ISSUE TITLE
Error with multiple monitor on bspwm module

### ISSUE THREAD

**Issue by mr-mbello** [jaagr/polybar#614]
I've had this issue for a while, with multiple monitors when using polybar. 
In bspwm module, when the active workspace is the attached monitor, polybar sort of just renders the hex codes and formatting as characters. Tried pinworkspaces and a few other tweeks with the config but it doesnt seem to fix the issue. 
Heres an image

![2017-06-11-185146_1920x2160_scrot](https://user-images.githubusercontent.com/17212680/27013238-f5c2a4d4-4ed7-11e7-9c22-74d1a56029f1.png)

I have a strange feeling i'm missing something really simple because i havent seen this anywhere else
Thanks for your help

**Comment by jaagr** [comment]
Can you post your config? It looks like you got something wrong with the syntax tags.

**Comment by mr-mbello** [comment]
This is my current bspwm module at bar/top

[bar/top]
monitor = LVDS-0
width = 99%
height = 24
clickareas = 35
offset-y = 5
offset-x = 10

background = ${xrdb:background}
foreground = ${xrdb:foreground}
underline-color = ${bar/top.background}

spacing = 2
underline-size = 2
padding-right = 4
padding-left = 4
module-margin-left = 0
module-margin-right = 4

font-0 = Terminess:size=8;0
font-1 = MaterialIcons:size=9;0
font-2 = FontAwesome:size=8;0

modules-left = xwindow 
modules-center = bspwm

And My bspwm module:

[module/bspwm]
type = internal/bspwm
ws-icon-default = 
format = <label-state> <label-mode>
label-dimmed-underline = %{bar/top.background}
label-active = %icon%
label-active-foreground = #fff
label-active-background = ${bar/top.background} 
label-active-underline = #c9665e
label-active-padding = 4
label-occupied = %icon%
label-occupied-foreground = #ddffffff
label-occupied-underline = ${bar/top.background}
label-occupied-font = 4
label-occupied-padding = 4
label-urgent = %icon%
label-urgent-foreground = #000000
label-urgent-background = #bd2c40
label-urgent-padding = 4
label-empty = %icon%
label-empty-foreground = #55
label-empty-padding = 4
label-monocle = 
label-monocle-underline = ${module/bspwm.label-active-underline}
label-monocle-background = ${module/bspwm.label-active-background}
label-monocle-padding = 2
label-locked = î¢
label-locked-foreground = #bd2c40
label-locked-underline = ${module/bspwm.label-monocle-underline}
label-locked-padding = ${module/bspwm.label-monocle-padding}

I know i probably still have some stuff stuc from the lemonbuddy days

**Comment by jaagr** [comment]
`label-dimmed-underline` does not use the correct tag format

**Comment by mr-mbello** [comment]
Thank you! I should've seen that.
