### ISSUE TITLE
Build errors (XCB_EWMH)

### ISSUE THREAD

**Issue by monoflo** [jaagr/polybar#619]
I could appreciate a little help building polybar. Issue #463 seems to be the most similar to what I am experiencing.

<hr>

**`$ cmake ..`**

-- No build type specified; using RelWithDebInfo

-- Using supported compiler GNU-6.3.0

--  Build:

--    Type: RelWithDebInfo

--    CC: /usr/bin/cc  -O2 -g -DNDEBUG

--    CXX: /usr/bin/c++  -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors -O2 -g -DNDEBUG

--    LD: /usr/bin/ld  

--  Targets:

--    polybar-msg

--    testsuite

--  Module support:

--    alsa

--    curl

--    i3

--    mpd

--    network

--  X extensions:

--    xcb-randr

--    xcb-randr (monitor support)

--    xcb-render

--    xcb-damage

--    xcb-sync

--    xcb-composite

--    xcb-xkb

--    xcb-xrm

-- Found font: fixed:pixelsize=10

-- Font not found: unifont:fontformat=truetype

-- Font not found: siji:pixelsize=10

-- XCB[XCB]: Found component XCB

-- XCB[ICCCM]: Found component ICCCM

-- Could NOT find XCB_EWMH (missing:  XCB_EWMH_LIBRARY XCB_EWMH_INCLUDE_DIR) 

-- XCB[UTIL]: Found component UTIL

-- XCB[IMAGE]: Found component IMAGE

CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):

  Could NOT find XCB (missing: XCB_EWMH_FOUND)

Call Stack (most recent call first):

  /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)

  lib/xpp/cmake/FindXCB.cmake:245 (find_package_handle_standard_args)

  lib/xpp/CMakeLists.txt:13 (find_package)

-- Configuring incomplete, errors occurred!

See also "/home/ryan/Desktop/polybar/build/CMakeFiles/CMakeOutput.log".

See also "/home/ryan/Desktop/polybar/build/CMakeFiles/CMakeError.log".

<hr>

**`$ cat CMakeFiles/CMakeError.log`**

Determining if the pthread_create exist failed with the following output:

Change Dir: /home/ryan/Desktop/polybar/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_16a3b/fast"

/usr/bin/make -f CMakeFiles/cmTC16a3b.dir/build.make CMakeFiles/cmTC16a3b.dir/build

make[1]: Entering directory '/home/ryan/Desktop/polybar/build/CMakeFiles/CMakeTmp'

Building C object CMakeFiles/cmTC_16a3b.dir/CheckSymbolExists.c.o

/usr/bin/cc     -o CMakeFiles/cmTC_16a3b.dir/CheckSymbolExists.c.o   -c /home/ryan/Desktop/polybar/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c

Linking C executable cmTC_16a3b

/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_16a3b.dir/link.txt --verbose=1

/usr/bin/cc       CMakeFiles/cmTC16a3b.dir/CheckSymbolExists.c.o  -o cmTC16a3b -rdynamic 

CMakeFiles/cmTC_16a3b.dir/CheckSymbolExists.c.o: In function `main':

CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'

collect2: error: ld returned 1 exit status

CMakeFiles/cmTC16a3b.dir/build.make:97: recipe for target 'cmTC16a3b' failed

make[1]: *** [cmTC_16a3b] Error 1

make[1]: Leaving directory '/home/ryan/Desktop/polybar/build/CMakeFiles/CMakeTmp'

Makefile:126: recipe for target 'cmTC_16a3b/fast' failed

make: *** [cmTC_16a3b/fast] Error 2

File /home/ryan/Desktop/polybar/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:

/* */

include <pthread.h>

int main(int argc, char** argv)

{

  (void)argv;

ifndef pthread_create

  return ((int*)(&pthread_create))[argc];

else

  (void)argc;

  return 0;

endif

}

<hr>

**`$ apt show libxcb-ewmh2 | head -n 5`**

Package: libxcb-ewmh2

Version: 0.4.1-1ubuntu1

Priority: extra

Section: libs

Source: xcb-util-wm

**Comment by kpan2034** [comment]
I was facing a simliar issue.
I did the following:

`sudo apt-get install libxcb-ewmh-dev`

Build seems to work fine after that.

**Comment by monoflo** [comment]
Tried that, but what worked for me was:

    sudo apt install python-xcbgen

I then ran into other build errors outside the scope of this thread.
