### ISSUE TITLE
Add information on using font icons

### ISSUE THREAD

**Issue by lobachevzky** [jaagr/polybar#620]
I'm a little new to linux and I have figured this much out: to add a font icon to my config, I need to

1. download the font
2. list the font under the main config hearer, for example
```
[bar/mybar]
font-0 = FontAwesome:size=14:antialias=true;3
```
3. copy and paste the icon from some source on the web into the config file.

This works fine as long as you have a place where you can copy and paste the font. For example, Font Awesome provides a very helpful little [cheatsheet](http://fontawesome.io/cheatsheet/). However, if such a cheat sheet does not exist, as in the case of [Material Icons](http://google.github.io/material-design-icons/), things become more difficult.

My specific question is how to get those Material Icons into my config. My broader suggestion is to perhaps include some information on how to do this in your wiki, or at least a pointer to a web resource that provides more general instructions on how this works.

**Comment by bartkmq** [comment]
Look at the last paragraph in the wiki page 'Fonts':
> GNOME Character Map - gucharmap - is a convenient utility for browsing selected fonts. Filter View > > By Unicode Block + Show only glyphs from this font and navigate to Private Use Area.

This tool lets you copy the individual chars from your font.
![bildschirmfoto vom 2017-06-28 16-56-04](https://user-images.githubusercontent.com/25273823/27643944-baae16d2-5c22-11e7-9135-22c4c28fc80a.png)

**Comment by patrick96** [comment]
Yes gucharmap is the go-to tool for that :)

Also you can figure out the exact fontname that you need like this:
```
fc-list | grep -i <font>
```
Where `<font>` is part of the name of the font you are searching for. For example, if I run `fc-list | grep -i awesome`, I get this:
```
/usr/share/fonts/TTF/fontawesome-webfont.ttf: FontAwesome:style=Regular
```

Everything after the path and before the first colon is the name that you put into the polybar config.

**Comment by lobachevzky** [comment]
Hmm... I must be missing something. When i do that, all the fonts are blank:
![image](https://user-images.githubusercontent.com/10344742/27671958-9841b048-5c4c-11e7-8103-d7fd5733e63e.png)

**Comment by patrick96** [comment]
I think for FontAwesome you'll need to scroll down a bit for the first items to show up

**Comment by lobachevzky** [comment]
That's it! I got it. Thank you.
