### ISSUE TITLE
Installing On Ubuntu 16.04 lts

### ISSUE THREAD

**Issue by BenderFendor** [jaagr/polybar#621]
Im trying to install polybar but Im getting this message

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 polybar : Depends: libstdc++6 (>= 6) but 5.4.0-6ubuntu1~16.04.4 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by patrick96** [comment]
Since you are installing polybar from a repository, someone has already successfully compiled polybar. This is an issue with either your system (see the note about broken packages) or an issue with the packager not listing dependencies properly.
