### ISSUE TITLE
Volume module. Incorrect values at low volume. Alsa.

### ISSUE THREAD

**Issue by Vintodrimmer** [jaagr/polybar#625]
Good day!

 Closer the sound to zero, bigger is the error in the bar's reported value.

```
Alsa: 0  1 2   4    5   7   9   12 15 19 23 27 33 39 47 56 66 78 92 100
Bar:  0  5 10 16  21 27 32 37 43 48 54 58 64 70 75 81 86 91 97 100
```

Is there some error on my part, maybe?

My [module/volume] is
```
type = internal/volume
master-mixer = Master
speaker-mixer = Speaker
headphone-mixer = Headphone
headphone-id = 8
format-volume = VOL: <label-volume>
label-muted = *sound muted*
```

I change the volume by manipulating the `Master' mixer.

![screenshot](https://raw.githubusercontent.com/Vintodrimmer/docs/master/2017-06-29-18%3A47%3A19-screenshot.png)

**Comment by patrick96** [comment]
I have noticed the same thing. I think this is because the volume bar is not a linear scale. When changing the volume with the arrow keys, on the top left the `dB gain` will change by 0.75 but `dB` is on a logarithmic scale, so that might be the cause of that.

**Comment by Vintodrimmer** [comment]
Thank you!

No, I don't use pulseaudio and I change the volume, using `amixer sset -c 0 Master 5%-` and `amixer sset -c 0 Master 5%+`.

Setting `mapped = true` has fixed the problem!
