### ISSUE TITLE
stop with compton

### ISSUE THREAD

**Issue by rotsix** [jaagr/polybar#626]
Hi,

I've recently switched to compton (from xcompmgr), and now, polybar stop without any reason.
As I already had some issues, i made a log file (polybar top &> polybar.log), and nothing fancy appears.

Here is some informations:

polybar --version: polybar 3.0.5-2-gd19b610
polybar.conf: https://ptpb.pw/dpOf
compton.conf: https://ptpb.pw/3Jpn.conf

Any idea ?
Feel free to ask me anything.

Regards

**Comment by patrick96** [comment]
Can you post the contents of the log file.
When executing `polybar top` does the command return or is the bar just not visible?

**Comment by rotsix** [comment]
As i said, nothing fancy in my (logs)[https://ptpb.pw/ZNOm]

when launching `polybar top`, it launch the bar, it's visible. But sometimes it stops without any reason..

**Comment by patrick96** [comment]
Alright that is really strange

I have been running your config (with compton) on my machine and have not seen this behaviour. Normally polybar prints a message when shutting down (unless SIGKILL is used). Do you have any script that accidentally runs and kills the bar?

Also can you provide me with the logs using the log level `info` and the compton output?

**Comment by rotsix** [comment]
Pretty weird, but got no problem tonight.

logs:
[polybar][https://ptpb.pw/LT1M.log)
[compton](https://ptpb.pw/uLQB) (on startup)

**Comment by patrick96** [comment]
To be honest, I have no idea what the problem is here. I also get the `BadWindow` error with compton so that should be nothing to worry about.

Maybe @jaagr can shed some light on this, or maybe suggest a few ways to track down what could be causing this.

**Comment by rotsix** [comment]
Mh, still no problem tonight, if nothing appears for 2 days, i will close
