### ISSUE TITLE
Gnome-shell takes systray selection from polybar

### ISSUE THREAD

**Issue by bartkmq** [jaagr/polybar#627]
I'm using polybar together with Gnome and noticed that gnome-shell seems to be stealing the systray selection when it starts, preventing polybar to continue to display the sysbar icons.
Is there a way for me to config polybar so that it keeps the selection (or steals it back)?
Thanks

**Comment by jaagr** [comment]
Can't you just disable it in the shell config?

**Comment by bartkmq** [comment]
Gnome-shell does not seem to have an option to disable the systray. I solved the problem by patching the source.

If anyone else has the same problem, just remove the following lines and recompile: [gnome-shell](https://github.com/GNOME/gnome-shell/blob/master/js/ui/legacyTray.js#L109-L112)
