### ISSUE TITLE
how can I specify the font which my custom/script module will use

### ISSUE THREAD

**Issue by ninrod** [jaagr/polybar#629]
Hi, and thanks so much for the program @jaagr 

I'm perusing many examples of custom/scripts in the wiki, in the section "user contributed modules". And I know that the user can define a "font array" for later referencing and use. 

I did not find though, how, in my custom/script module definition, would I tell polybar to use a specific font from that array (ex: nerd-fonts vs material vs font-awesome).

thanks in advance

**Comment by patrick96** [comment]
On the [Fonts Wiki Page](https://github.com/jaagr/polybar/wiki/Fonts) it is described how you can force a certain font to be used.

You can probably specify `label-font` or `format-font` in the module and if that doesn't work, you can wrap the output of the module in `%{TX}...%{T-}` where X is the index of the font (Note: The index here is 1-based, so if you wanted to use the font specified as `font-2 = ...` use 3)

**Comment by ninrod** [comment]
thank you very much, will try that.
