### ISSUE TITLE
Polybar runs from cli, not from i3-startup

### ISSUE THREAD

**Issue by cj360** [jaagr/polybar#630]
[Polybar config & launch are here](https://github.com/cj360/dotfiles/tree/master/.config/polybar) and [i3 config here](https://github.com/cj360/dotfiles/blob/master/.config/i3/config).

I don't see any errors from polybar when I run the launch script from termite, but it doesn't run with i3 as it should. Could it be something in poly's config is failing to launch when i3 tries to run it?

**Comment by patrick96** [comment]
Is the launch script actually executed when you start i3? If so can you pipe the output of the script to a log file when started via i3. You best do that like this:

```
{
...
} > /path/to/file.log
```

**Comment by cj360** [comment]
Closing for now as I don't see an error from i3 in staring the bar/polybar config, and there is no problem reverting to an older version of my config.
