### ISSUE TITLE
Making ramp-volume stay in place

### ISSUE THREAD

**Issue by omrisim210** [jaagr/polybar#636]
As you can see in the picture, the volume module's ramp-volume moves as the text in the label changes.  
Is it possible to just have it in one place?
![image](https://user-images.githubusercontent.com/13455401/27983709-aeb5b37a-63cb-11e7-88c0-24373f73f311.png)

**Comment by patrick96** [comment]
I'm assuming your volume module looks something like this:
```dosini
...
format-volume = <ramp-volume> <label-volume>
label-volume = %percentage%%
ramp-volume-0 = 🔈
ramp-volume-1 = 🔉
ramp-volume-2 = 🔊
...
```
For the `%percentage%` token a min width can be set like this: `%percentage:3%`

This behavious is described in the [Formatting Wiki](https://github.com/jaagr/polybar/wiki/Formatting).
