### ISSUE TITLE
internal/mpd module: format-paused has no effect

### ISSUE THREAD

**Issue by realcomplex** [jaagr/polybar#637]
Hey! I am using the mpd module of polybar, and I would like the colour of the song on the bar to change from blue to red when I pause mpd. So the relevant portion of my config looks like this:

```
format-online = <label-song>
format-online-background = #0000ff
format-paused = <label-song>
format-paused-background = #ff0000
format-playing = ${self.format-online}
format-stopped = ""
```

But this doesn't work.

**Expected:** the background of the current song is blue when mpd is playing, and red when mpd is paused.
**Actual behaviour:** the background of the current song is blue regardless of the state of mpd.

**Comment by patrick96** [comment]
That feature was introduced in 5c41e3d045e9e6380e631b15c767abe6e0b54baf which is not part of any release yet. If you need that functionality, you'll need to compile against that or any later commit

**Comment by realcomplex** [comment]
Okay thanks, I'll just wait until it gets added to the latest release then :) Great feature anyway, now I'll be able to switch from a custom module that does this to the built-in one!
