### ISSUE TITLE
Battery module support for execution of commands[notification at full, hibernate at low]

### ISSUE THREAD

**Issue by hiteshpaul** [jaagr/polybar#638]
First for all, thanks for the awesome bar! really loved it.

While customizing the bar, I couldn't find the option to execute command on battery full or low -battery.
What I am trying to achieve is this:

execute a command at `full-at` for instance run a `send-notify` command with custom message(The reason for this is most of the time I work on full screen applications, so I "miss" to see the color change!)

Secondly, execute a command when battery level is below a particular thresh for example, say a value of `low-at'. I want to execute a command to hibernate my laptop.

Probably, this can be achieved through `custom/script` if I am not mistaken, however, shouldn't this functionality be in the default battery module itself? It would be efficient I guess.

**Comment by patrick96** [comment]
This is not something polybar can or should be able to do. 
You should look into udev rules to run a script whenever the battery charge changes.

I use the following rule for hibernating when at 5% or lower
```
SUBSYSTEM=="power_supply", ATTR{status}=="Discharging", ATTR{capacity}=="[0-5]", RUN+="/usr/bin/systemctl hibernate"
```

If you really wanted to use polybar for this, you could use a `custom/script` that periodically checks the battery levels and acts accordingly, but you could just as well run that script outside of polybar.

**Comment by hiteshpaul** [comment]
Thanks for the answer @patrick96 I did not know about udev rule before. Regarding notification at full charge, I will try to run a `custom/script` at regular intervals to send notification.
