### ISSUE TITLE
Turning the whole bar into red as a capslock indicator

### ISSUE THREAD

**Issue by amosbird** [jaagr/polybar#640]
Hi, is it possible to achieve this?

**Comment by patrick96** [comment]
There is an [xkeyboard](https://github.com/jaagr/polybar/wiki/Module:-xkeyboard) module that can tell you when you have caps lock turned on.

If you really wanted to turn the whole bar red, you could do something with dynamic reloading as described in #635. Set the background color to red and reload. But for that you'll need to figure out how to run a script everytime caps lock is toggled
