### ISSUE TITLE
Volume is off by 1 percent.

### ISSUE THREAD

**Issue by ddeklerk** [jaagr/polybar#641]
Using pulseaudio and pulseaudio-alsa. Compared to what pavucontrol or i3blocks display the volume level is off by 1 or 2 percent.

Up to 52% of real volume it displays 1 percent lower, 53% and 54% both display as 52%, 59% and 60% both display as 58%, then 61% jumps to 60%.

**Comment by patrick96** [comment]
This is because you are using pulseaudio
Polybar only has native support for alsa, with pulseaudio-alsa it works but there are some discrepancies. If you really want the same values, you'll need the [pavolume custom module](https://github.com/jaagr/polybar/wiki/User-contributed-modules#pulseaudio-volume) or something along those lines

**Comment by ddeklerk** [comment]
My problem with the pavolume module is that it does not update immediately as I change the volume. And I'm not sure if you can display a bar with it.

**Comment by patrick96** [comment]
You can change the interval on the module so that it updates more frequently. You can display a bar in a custom script, but you'll have to do most of the legwork because you'll need to calculate the width of the sections and everything.

**Comment by ddeklerk** [comment]
That script does work better than the one in the wiki in the sense that it updates as I change the volume. But there are a few problems. It seems to me like there are two functions missing. Those are `getFg` and `getBg`. When I had the module set up in the bar, it was flashing an error whenever I change the volume. And sure enough, running the script in the terminal gives me a command not found on those two, on lines 171, 173, and 174. Another problem is that it does not indicate whether the sound is muted.

Do keep in mind that I'm quite new to shell scripting in general. I'm not against learning, though.

**Comment by patrick96** [comment]
Yes the script is missing a few things, that are defined in other files. Just put the following after the second line of the script to get you started and remove the `load` function as well as any reference to it:
~~~bash
# Prints the lemonbar foreground code with the given color
getFg() {
    echo -e "%{F$*}"
}

# Prints the lemonbar background code with the given color
getBg() {
    echo -e "%{B$*}"
}

export VOLUME0="$(echo -e "\uE04E")" # 
export VOLUME1="$(echo -e "\uE04D")" # 
export VOLUME2="$(echo -e "\uE050")" # 
# Number of different volume icons are present
export VOLUME_RAMP_NUM=3
export VOLUME_MUTED="$(echo -e "\uE04F")" # 

# Black
export COLOR0="#282A2E"
export COLOR8="#373B41"

# Red
export COLOR1="#A54242"
export COLOR9="#CC6666"

# Green
export COLOR2="#8C9440"
export COLOR10="#B5BD68"

# Yellow
export COLOR3="#DE935F"
export COLOR11="#F0C674"

# Blue
export COLOR4="#5F819D"
export COLOR12="#81A2BE"

# Magenta
export COLOR5="#85678F"
export COLOR13="#B294BB"

# Cyan
export COLOR6="#5E8D87"
export COLOR14="#8ABEB7"

# White
export COLOR7="#707880"
export COLOR15="#C5C8C6"
~~~

This is of course using my own theme, so you'll probably want to change the colors and even the icons.
The script actually should indicate if the sound is muted by showing the `$VOLUME_MUTED` icon and graying out the text

**Comment by ddeklerk** [comment]
Thanks. Now it works properly. I'll have a look around the script and see what it does so I can make my own version with my own theme.
