### ISSUE TITLE
FontAwesome Icons Not Displaying

### ISSUE THREAD

**Issue by FireAntJoe** [jaagr/polybar#642]
So I have font awesome installed ttf-font-awesome. I copied the icon to my config(the power button) but when I load my polybar it displays nothing. Here is my current config https://gist.github.com/FireAntJoe/34377cd0e5eef964f1a5a532af4b9e57

**Comment by x70b1** [comment]
The first thing I can see is that your `font-0 = "FontAwesome:pixelsize=12;0"` is not a part of a bar. Place it under `[bar/example]`.

**Comment by FireAntJoe** [comment]
Thank you I did that and it fixed it my bad.
