### ISSUE TITLE
No tray icon. Got a lot "error: Failed to reconfigure tray clients (XCB_VALUE (2))"

### ISSUE THREAD

**Issue by qqldd** [jaagr/polybar#643]
I am running ubuntu 1404 with i3. I compiled my own gcc-6 and go with system libxcb-1.10.

After I opened "remmina", I cannot see the tray icon. From the terminal I got a lot error "error: Failed to reconfigure tray clients (XCB_VALUE (2))". 

Any ideas on this? Is this because some dependencies are old?

**Comment by patrick96** [comment]
Does this only happen with the `remmina` tray icon or with any tray icon?
Also, do you have any other systray program running?

**Comment by qqldd** [comment]
I only have fcitx in the system tray. The fcitx is more complicate. If I keep fcitx open, it shows:
```
error: Invalid _XEMBED_INFO for window 0x1600014
```

If I kill fcitx, it shows
```
error: Failed to reconfigure tray clients (XCB_VALUE (2))
```

This issue https://github.com/jaagr/polybar/issues/377 has the first error. I tried VLC, it is exactly the same as fcitx.

A screent shot:
![2017-07-11-150941_898x16_scrot](https://user-images.githubusercontent.com/233128/28093179-0a229abc-664b-11e7-814a-29035bd082a5.png)

And bar config section inside [bar/top]
```
tray-detached		= false
tray-position		= right
tray-offset-x		= 0
tray-offset-y		= 0
tray-maxsize		= 0
tray-padding		= 0
tray-scale		= 1
tray-background 	= ${colors.t1}
```

**Comment by qqldd** [comment]
I have update the system  libxcb-1.10 to  libxcb-1.12 still got the same error..

**Comment by qqldd** [comment]
I find it may be due to my configuration. I changed the tray part to
`
tray-position = right
tray-padding = 2
`
Then it works fine now. Even I still got the  `error: Invalid _XEMBED_INFO for window 0x1600014`

I will close this issue for now.

**Comment by patrick96** [comment]
Oh, I totally missed this, it seems that `tray-maxsize = 0` causes this

**Comment by qqldd** [comment]
@patrick96 Oh, thanks! Now I know which part causes the problem :+1:
