### ISSUE TITLE
module/powermenu: Cannot open unexisting menu level

### ISSUE THREAD

**Issue by Dobbie03** [jaagr/polybar#645]
I'm using Arch Linux and have installed the Git version of polybar, is there something I am missing in my config?  When I click the power button I get this error:

`warn: module/powermenu: Cannot open unexisting menu level '1342171104'`

This is my config:
https://pastebin.com/ZCsZWAhs

**Comment by patrick96** [comment]
The menu indices start at zero. You'll need to define `menu-0-0` etc

**Comment by mrneilypops** [comment]
Hi Dobbie03,
I think you have all actions defined under one index.
Here is my powermenu;

`
menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = sudo reboot

menu-2-0 = power off
menu-2-0-exec = sudo poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0`

You see that each action has a defined index;
reboot=0
cancel=1
power off =2

You just need to follow the same rules.

**Comment by Dobbie03** [comment]
Got it thanks chaps.

Closing this one.
