### ISSUE TITLE
Install dependency libs on Ubuntu when install polybar

### ISSUE THREAD

**Issue by giangm9** [jaagr/polybar#650]
Since getdeb died, here is my command to install dependency libraries to build polybar from source 
```
sudo apt-get install python-xcbgen linxcb-ewmh-dev libxcb-icccm4-dev libxcb1-dev \
xcb-proto libxcb-util-dev libxcb-image0-dev libxcb-randr0-dev ibxcb-xkb-dev \
libalsaplayer-dev wireless-tools libcurlpp-dev  libcairo2-dev
```
Please write a script to install these libs or write the command in the Install section of the README file.

**Comment by patrick96** [comment]
Which version of Ubuntu is this for?

**Comment by patrick96** [comment]
There are already instructions on the [Wiki](https://github.com/jaagr/polybar/wiki/Compiling), most of the packages you listed are also listed there.
The only differences are `wireless-tools`, `libcurlpp-dev` and `libalsaplayer-dev`.

I have checked those packages on Ubuntu 17.04 and it seems they are not really necessary

`wireless-tools` only provides a few executables but no header files that polybar uses. The package to use is `libiw-dev` which provides the proper header files and also has the same dependencies as `wireless-tools`

As for `libcurlpp-dev`, I don't see how polybar uses this. Polybar uses the the standard curl headers provided by `libcurl4-openssl-dev`. The same goes for `libalsaplayer-dev`.

As already mentioned, those checks were made on Ubuntu 17.04, so it is possible that on other versions those three packages are actually needed, can you check if you are still able to compile without those thre packages.
