### ISSUE TITLE
Change KeyLock indicator String

### ISSUE THREAD

**Issue by i3wm** [jaagr/polybar#654]
Currently, the string for KeyLocks are too large for the bar, i.e, CapsLock, NumLock, etc. It takes too much space and also results in misalignment of center modules. Is it possible to change that to something smaller like C for CapsLock, 1 for NumLock, etc. 

If you could kindly tell as to where to make the changes in source file so as to reflect the above results, it would be a great help. Thank you.

**Comment by patrick96** [comment]
The [`src/modules/xkeyboard.cpp`](https://github.com/jaagr/polybar/blob/master/src/modules/xkeyboard.cpp) puts those names onto the bar on lines [63](https://github.com/jaagr/polybar/blob/master/src/modules/xkeyboard.cpp#L63) and [71](https://github.com/jaagr/polybar/blob/master/src/modules/xkeyboard.cpp#L71). Just replace the last argument of `replace_token` with whatever string you want to show.

**Comment by i3wm** [comment]
@patrick96 - Man, I had been trying that for the last few times. I was editing the same lines but it didn't work. Now, suddenly it started working. Since I was using `makepkg` and was manually cloning the git, I think that was the reason. Once I `sed` the lines in `PKGBUILD`, everything worked. Thanks man.
