### ISSUE TITLE
module/powermenu question 

### ISSUE THREAD

**Issue by icf20** [jaagr/polybar#655]
i got this

```
[module/powermenu]
type = custom/menu

format-foreground = ${colors.xcolor7}
format-background = ${colors.xcolor0}


label-open = "¿?"
label-open-font = 4
label-close = ""
label-close-foreground = ${colors.lime}
label-separator = " / "
label-separator-foreground = ${colors.xcolor1}


; reboot
menu-0-1 = 
menu-0-1-exec = systemctl reboot
menu-0-1-foreground = ${colors.salmon}
; shutdown
menu-0-0 = "  "
menu-0-0-exec = systemctl poweroff
menu-0-0-foreground = ${colors.salmon}
```

the problem i have is to move the label-close in the same place like label-open because in case of a miss click i get a power off

**Comment by patrick96** [comment]
Do you have the powermenu as part of `modules-center` or `modules-right`? If so, the thing you are experiencing is that the items on the menu are added to the right of the `label-open`/`label-close` and thus the `label-close` appears to be shifted to the left.
Is that about right?

To avoid this problem, I have simply put the `powermenu` in `modules-left`.

There is probably no way to consistently fix this issue. One idea would be to add an option to the `menu` module to tell it to either add the items to the right or to the left of the `label-close`. This still falls short, if with all the menu items shown, the bar is too large to fit and thus some things (possibly including the closing label) are moved around. Also I don't know how it would behave, if it was part of `modules-center`

**Comment by icf20** [comment]
> Do you have the powermenu as part of modules-center or modules-right?  

is on modules-right

>  If so, the thing you are experiencing is that the items on the menu are added to the right of the label-open/label-close and thus the label-close appears to be shifted to the left.
Is that about right?

correct 

> To avoid this problem, I have simply put the powermenu in modules-left

sadly that would mode the menu on the opposite part of polybar

**Comment by patrick96** [comment]
Yes the menu would be on the other side of the bar, but this is currently the only way to fix this.

I am currently working on that `menu` option I talked about, but no promises

**Comment by icf20** [comment]
i will add a confirmation via submenu and problem avoided

**Comment by patrick96** [comment]
That's a good idea too
It's probably a good idea in general
