### ISSUE TITLE
Module: xkeyboard Allow to show keyboard model variant

### ISSUE THREAD

**Issue by binaryplease** [jaagr/polybar#660]
Hello

I use both the default and the colemak variant of the us model and switch a lot between them. Polybar just shows "us" it would be nice to be able to show "us (qwerty)" or "us (colemak)" depending on the variant that is active.

I use this to set the layouts:

```
setxkbmap -layout us,us -variant colemak, -option grp:alt_shift_toggle      
```

If there already is a way to set this up let me know.

**Comment by patrick96** [comment]
`label-layout = %name%`

**Comment by echoStorms** [comment]
Hi

I was trying to figure this out today as well.

`label-layout = %name%`

This is the only solution I could find, but it writes out *English (US)* and *English (Colemak)*. Marginally longer than your requested solution.
I myself was looking for something like *us* and *colemak*.

**Comment by NBonaparte** [comment]
Duplicate of #316.
