### ISSUE TITLE
Allow clicking at x=0

### ISSUE THREAD

**Issue by jfrankenau** [jaagr/polybar#661]
I have set my bar width to 100% and defined a clickable area spanning the whole bar. However when I click in the leftmost corner the click is not registered. If I move my cursor one pixel to the right it works.

**Comment by patrick96** [comment]
Can you give me the output of the polybar when you start it with `-l info`

**Comment by patrick96** [comment]
Can confirm.
Debugging this a little, polybar definitely receives the click and warns me that there is `No matching input area found`. So definitely a polybar bug

**Comment by patrick96** [comment]
Fixed the issue in #663
