### ISSUE TITLE
Looking for this config sample

### ISSUE THREAD

**Issue by Dobbie03** [jaagr/polybar#665]
Is this sample config file available?

http://i.imgur.com/TY5a5r9.png

**Comment by patrick96** [comment]
This was from back when this project was still named lemonbuddy. There probably is a config in and old version of jaagr's [dotfile](https://github.com/jaagr/dots), but it will most likely not work out of the box

**Comment by Dobbie03** [comment]
That's a shame.  Thanks for the info. Closing this one.
