### ISSUE TITLE
Add user contributed module?

### ISSUE THREAD

**Issue by jaredwelsh** [jaagr/polybar#667]
Hello, I wrote some python code that will allow for users to view their load average and current load.  I was wondering how I would go about adding this to user contributed modules? I poked around and counldn't seem to find any guidelines for who to contact or formatting specifics.  Thank you

**Comment by kajzersoze** [comment]
Click on Edit ?

**Comment by jaredwelsh** [comment]
is everyone allowed to contribute without any qa?

**Comment by patrick96** [comment]
The wiki is currently open for contributions by anyone, so you should be good.
As for formatting, just look at how the other user contributed modules do it, and be sure to add your section to the TOC.
