### ISSUE TITLE
Polybar fails to build

### ISSUE THREAD

**Issue by FireAntJoe** [jaagr/polybar#669]
`[  1%] Built target xpp

[  2%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o
In file included from /home/meep/polybar/lib/i3ipcpp/src/ipc.cpp:9:0:
/home/meep/polybar/lib/i3ipcpp/include/i3ipc++/ipc-util.hpp:147:57: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 std::shared_ptr<buf_t>   i3_recv(const int32_t  sockfd) throw (invalid_header_error, eof_error);
                                                         ^~~~~
In file included from /home/meep/polybar/lib/i3ipcpp/src/ipc.cpp:9:0:
/home/meep/polybar/lib/i3ipcpp/include/i3ipc++/ipc-util.hpp:163:131: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 ientMessageType  type, const std::string&  payload = std::string()) throw (invalid_header_error, eof_error);
                                                                     ^~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [lib/i3ipcpp/CMakeFiles/i3ipc++.dir/build.make:63: lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:458: lib/i3ipcpp/CMakeFiles/i3ipc++.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`
Been trying for a few days to build this and I cannot.

**Comment by i3wm** [comment]
Are you building from the latest git?

**Comment by patrick96** [comment]
Formatting please. No one can read this. Also what's your cmake output?

**Comment by FireAntJoe** [comment]
I am building from the latest polybar-git. I am not sure what my cmake output is because I do not know how to get it.

**Comment by patrick96** [comment]
From you mentioning polybar-git, I'm assuming you're using Arch and trying to install from the AUR. Can you post the output of `makepkg -sr`, this should contain all the info needed. Also can you do it once without exporting those variables and once with exporting them

**Comment by FireAntJoe** [comment]
So run 
`yaourt -S polybar-git makepkg -sr`
with and without those additions to the build got it.

**Comment by patrick96** [comment]
No that won't work. Didn't know you were using yaourt
Just run `yaourt -S polybar-git` with and w/o those additions

**Comment by FireAntJoe** [comment]
I will when I get home from work tonight? Can I pipe these results into a file? If it is possible let me know.

**Comment by patrick96** [comment]
Since yaourt is interactive, writing the output to a file may be difficult.
Maybe something like `yaourt -S polybar-git | tee build.log` will work.
Otherwise just copy the output from the terminal

**Comment by FireAntJoe** [comment]
I will try that thank you

**Comment by Krakn** [comment]
Is your system completely up to date?

**Comment by FireAntJoe** [comment]
Yes my system is completely up to date

**Comment by Vanclief** [comment]
I had the same problem on Arch, was solved updating the clang version.

**Comment by FireAntJoe** [comment]
I reinstalled clang just to check and it did nothing.

**Comment by FireAntJoe** [comment]
I rebooted and reset my build and everything went well. You can close this now.

**Comment by patrick96** [comment]
You and jaagr are the only ones that can close this
