### ISSUE TITLE
Tray placement off

### ISSUE THREAD

**Issue by ecly** [jaagr/polybar#671]
I have a problem with the tray that I've been unable to fix myself. Below is how the placement of my bar ends up looking.

![meme](https://user-images.githubusercontent.com/8410422/28494307-86ee9a22-6f2a-11e7-9bec-89e953ee0d10.png)

As you can see it gets shoved about half of the bar's height downwards.

The configuration of my tray is the following:
```
tray-detached = false
tray-position = right
tray-offset-x = 0
tray-offset-y = 0
tray-maxsize = 16
tray-padding = 0
tray-scale = 1
```

**Comment by patrick96** [comment]
Can you post your whole config?

**Comment by ecly** [comment]
[config](https://github.com/ecly/dotfiles/blob/master/.config/polybar/config)
[launch](https://github.com/ecly/dotfiles/blob/master/.config/polybar/launch.sh)

**Comment by patrick96** [comment]
It is possible that the right icon takes up too much vertical space. What program is that icon from?

**Comment by ecly** [comment]
That's from Enpass the password manager!

**Comment by ecly** [comment]
I'm actually gonna be unable to access the computer with the problem for about a week, so unless there's a definite answer, we might put the issue on hold till I and can try to the suggestions?

**Comment by patrick96** [comment]
I can reproduce this now on my machine using i3 and with any tray icon, not just enpass

**Comment by patrick96** [comment]
The issue is with `offset-y=1%` and i3.
i3 seems to reposition the bar but the bar draws the tray differently, so the tray actually appears where it is supposed to but the bar appears somewhere else.

To stop i3 from repositioning the bar, add the following to your bar config
```dosini
override-redirect = false
```

**Comment by ecly** [comment]
That's awesome! I'm gonna give that a shot as soon as I get the chance! Thanks a ton! I'll assume that it does the trick for me so I'll close this for now! Again, thank you!
