### ISSUE TITLE
border-left causes center module to shift

### ISSUE THREAD

**Issue by xythrez** [jaagr/polybar#672]
Creating a bar with a left border of n pixels causes the center module to shift left the by the same amount (with fixed-center = true). This only seems to occur on the left border, which can be triggered by both border-left-size and border-size.

[Configuration used](https://pastebin.com/0tpdAtFz)
[Screenshot](https://imgur.com/a/VM0nI)

As shown above, the modules i3 and date are both shifted to the left, replacing them with single character modules (e.g brightness) also has the same effect

**Comment by patrick96** [comment]
This behaviour does not appear in the latest release but only if you built against the HEAD of this repo. So downgrading to the latest release v3.0.5 will fix this. I'm tracking down the offending commit now

**Comment by patrick96** [comment]
The issue has been introduced in 389bae266976bdb35efcfc18d0bd0aa978fa5702, which was a fix for #551. The logic applied there does not seem to work when there is any border on the left side. I'm working on a fix.

**Comment by patrick96** [comment]
I have submitted a pull-request in #673 to address this issue, can you try it out and tell me if it works

**Comment by xythrez** [comment]
Yep, its working correctly now.
