### ISSUE TITLE
sudo make install fails on Fedora 26

### ISSUE THREAD

**Issue by benjy1232** [jaagr/polybar#681]
When I attempt to build polybar this error appears when I do a sudo make install.

/home/benjy/i3 Stuff/polybar/lib/i3ipcpp/include/i3ipc++/ipc-util.hpp:147:57: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 std::shared_ptr<buf_t>   i3_recv(const int32_t  sockfd) throw (invalid_header_error, eof_error);
                                                         ^~~~~
In file included from /home/benjy/i3 Stuff/polybar/lib/i3ipcpp/src/ipc.cpp:9:0:
/home/benjy/i3 Stuff/polybar/lib/i3ipcpp/include/i3ipc++/ipc-util.hpp:163:131: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 std::shared_ptr<buf_t>  i3_msg(const int32_t  sockfd, const ClientMessageType  type, const std::string&  payload = std::string()) throw (invalid_header_error, eof_error);
                                                                                                                                   ^~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [lib/i3ipcpp/CMakeFiles/i3ipc++.dir/build.make:63: lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:458: lib/i3ipcpp/CMakeFiles/i3ipc++.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by patrick96** [comment]
I get this too when compiling with `gcc`. Install `clang` and try to use 
```bash
cmake -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" ..
```

@jaagr i3ipcpp already removed those deprecated features in https://github.com/drmgc/i3ipcpp/commit/fbc7ee916516ae708f0410fe886186234235a688, can we update the submodule?

**Comment by andyrichardson** [comment]
Installed polybar on FC25 and upgraded to FC26 recently - no issues here.

Sounds like you haven't called `cmake` before trying to install. Here are the installation instructions from the readme:

```
$ git clone --branch 3.0.5 --recursive https://github.com/jaagr/polybar
$ mkdir polybar/build
$ cd polybar/build
$ cmake ..
$ sudo make install
```

**Comment by B-bar** [comment]
I also using Fedora 26, and `make` fails in another place of code.
Here is part of the error log:
````
[  2%] Building CXX object lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_reader.cpp.o
/home/xxx/.bld.d/polybar/lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/json_reader.cpp: メンバ関数 ‘bool Json::OurReader::readToken(Json::OurReader::Token&)’ 内:
/home/xxx/.bld.d/polybar/lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/json_reader.cpp:1230:5: エラー: this statement may fall through [-Werror=implicit-fallthrough=]
     if (features_.allowSingleQuotes_) {
     ^~
/home/xxx/.bld.d/polybar/lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/json_reader.cpp:1240:3: 備考: here
   case '/':
   ^~~~
cc1plus: all warnings being treated as errors
make[2]: *** [lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/build.make:63: lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_reader.cpp.o] エラー 1
````

After I rewrote `lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/json_reader.cpp` like that;
````diff
--- ./json_reader.cpp.org	2017-08-03 11:26:43.061746506 +0900
+++ ./json_reader.cpp	2017-08-03 11:25:23.468435293 +0900
@@ -1228,10 +1228,12 @@
     break;
   case '\'':
     if (features_.allowSingleQuotes_) {
-    token.type_ = tokenString;
-    ok = readStringSingleQuote();
-    break;
-    } // else continue
+		token.type_ = tokenString;
+		ok = readStringSingleQuote();
+		break;
+	} else {
+		[[fallthrough]]; // for GCC 7.x
+	}
   case '/':
     token.type_ = tokenComment;
     ok = readComment();
````
`make` went well.
But I don't know is this the right way to solve this error.
Would you give me some advice, please.
(I refer to [this page](https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/ "-Wimplicit-fallthrough in GCC 7 – RHD Blog"))

**Comment by patrick96** [comment]
@B-bar this is the same issue as #668, the solution is the same I mentioned before: Use clang

**Comment by B-bar** [comment]
@patrick96 Thanks you. I'll use clang.

**Comment by patrick96** [comment]
The GCC issue is tracked in #572

**Comment by ThomasJunk** [comment]
clang does it!
