### ISSUE TITLE
Modules in 'absolute' centre?

### ISSUE THREAD

**Issue by OJFord** [jaagr/polybar#683]
`modules-center` seems to place modules in the centre of the space between the rightmost left module, and leftmost right module.

Is there any way to change this behaviour, so that `modules-center` are centred about the 'screen centre'?  It's particularly jarring on laptops with centred web cams.

I have tried `fixed-center = true`, but it seems to have no affect:  my centre module (date)  shifts left as more items appear in the (right aligned) systray.

**Comment by patrick96** [comment]
Duplicate of #551, this should be fixed if you compile against HEAD.
If that still doesn't fix it, check out #672

**Comment by OJFord** [comment]
Oh, thanks, and sorry I didn't spot the duplicate. Looks like that's been committed for a while, any chance of a release soon?

**Comment by patrick96** [comment]
A release isn't planned yet, there are still some things to figure out

**Comment by OJFord** [comment]
No worries, I found and switched to using `polybar-git` from AUR. Thanks again for the pointer, working great from master. :+1:
