### ISSUE TITLE
Polybar not displaying text color properly

### ISSUE THREAD

**Issue by deaddragon404** [jaagr/polybar#684]
I have never had a problem with this config until i reinstalled polybar 2 days ago now it wont display text color properly 
![screenshot2](https://user-images.githubusercontent.com/30742885/28997218-f7bde976-79c3-11e7-935c-038f653bcb0b.png)

**Comment by patrick96** [comment]
This is a known issue as reported in #666 and #639.

This does not occur in the latest stable release 3.0.5, so downgrading to that will fix this

**Comment by deaddragon404** [comment]
Thank you that fixed it

**Comment by patrick96** [comment]
This issue will be tracked in #639
