### ISSUE TITLE
Regional Indicator Symbols are displayed incorrectly

### ISSUE THREAD

**Issue by xiamaz** [jaagr/polybar#686]
I am trying to build an IBUS applet, which displays the corresponding country flag. But currently the flag symbols are drawn as single letters. I have tried both the Noto Emoji font and the EmojiOne font and both do not seem to work. E.g 🇩🇪 is shown as D E (as the single letter representation).

Sidenote: Regional Indicator Symbols ([Wikipedia](https://en.wikipedia.org/wiki/Regional_Indicator_Symbol)) are represented by two unicode characters.

**Comment by patrick96** [comment]
I don't know that much about font rendering, but I think this is an issue with cairo, which doesn't support such fancy text rendering. Adding support for that would require rewriting the entire rendering part of polybar, which is something that probably will not happen anytime soon, sorry.

While researching this, I have found that the emojis are rendered way too big for me, would you mind posting your config so I can see what you did differently?

**Comment by NBonaparte** [comment]
We'll have to switch to Pango as the font backend for this to work, which is on the roadmap (see #84).

**Comment by MeisterTea** [comment]
It's been a while since then, can you give us some highlight on the pango integration ? Is there an issue regarding this ?

**Comment by patrick96** [comment]
There hasn't been any work done on it, as far as I'm aware. It's not really a priority.
