### ISSUE TITLE
Maxing out brightness causes some red text

### ISSUE THREAD

**Issue by Hacksaurus** [jaagr/polybar#687]
I just have a slight problem with the brightness module.
Whenever I max out my brightness (Full 100), some of my other text on my bar red for some sort of reason.
I am using `polybar-git`.
Here is what it looks like, it seems like it only affects a certain fonts...
![screenshot_2017-08-06_12-18-39](https://user-images.githubusercontent.com/24832107/29006664-1a16bb52-7aa9-11e7-8c35-31f1495d3c4d.png)

Thanks for any help!

**Comment by patrick96** [comment]
This issue is already addressed in #684 and #666.

TL;DR Use the `polybar` package

**Comment by Hacksaurus** [comment]
Has the standard polybar package been fixed to comply with the newer curl version?

Closing this thread.

**Comment by patrick96** [comment]
Well the fix for the curl issue is not in any release yet so the 3.0.5 release will not compile with the newer curl version, you'll have to apply commit https://github.com/jaagr/polybar/commit/d35abc7620c8f06618b4708d9a969dfa2f309e96 yourself.

**Comment by Hacksaurus** [comment]
Got it! Thank you for your help!

**Comment by Hacksaurus** [comment]
Actually, how to edit those changes in to the polybar files? I tried editing the http.cpp file in pacaur, and then reinstalled it , but the files just got reverted to its previous state...

**Comment by Hacksaurus** [comment]
Actually, I found a cheeky way of applying the change, when the http.cpp file was built, I quickly remove the line from the file, and continue letting it compile! But I still would like to know how to properly apply that commit. XD

**Comment by patrick96** [comment]
First let `makepkg` fail then go and remove that one header line and run `makepkg` again with the `-e` flag, which will prevent `makepkg` from updating the sources.

**Comment by Hacksaurus** [comment]
Ah thank you, will take that into consideration when I have to do something like this in the future!

Thank you for the help!
