### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Sup3r-Us3r** [jaagr/polybar#689]
**I'm having trouble installing Polybar, even following the installation guide, or installing through AUR.**

![image](https://scontent-gru2-1.xx.fbcdn.net/v/t31.0-8/20776382_1943568139249775_4412180695729354478_o.jpg?oh=7b6e9b681f6c8a93738160d8a66afb7d&oe=59F88579)

**Comment by cesard11** [comment]
This seems to be a duplicate of [#633](https://github.com/jaagr/polybar/issues/633)

Try installing i3 (not i3-gaps) and run it again, then install i3-gaps again. Check for other possible solutions before you try this one

**Comment by patrick96** [comment]
If that doesn't work, compile with clang instead of gcc

**Comment by patrick96** [comment]
The GCC issue is tracked in #572

**Comment by patrick96** [comment]
The GCC issue is tracked in #572
