### ISSUE TITLE
can you help me jaagr

### ISSUE THREAD

**Issue by tjw0lf** [jaagr/polybar#690]
I want your space polybar how do i do this i have tried and can't do this

**Comment by Eibx** [comment]
Here's the repo for it.

https://github.com/jaagr/dots/tree/master/.local/etc/themer/themes/space

Here's the polybar config
https://github.com/jaagr/dots/blob/master/.local/etc/themer/themes/space/polybar

In case you still can't get it to work. Tell us what you've tried and what you get, a screenshot would also help.

**Comment by tjw0lf** [comment]
Ok thank you Eibx. Awesome help. I will get back to you with more info

**Comment by tjw0lf** [comment]
it doesn't show up right. I installed all the fonts. and changed the Mointor to mine HDMI-0 I'm running openbox.

error: Disabling module "mpd" (reason: No built-in support for 'internal/mpd')
error: Disabling module "volume" (reason: Cannot find simple element)
error: module/backlight: Could not get data (err: XCB_NAME (15))
error: Disabling module "backlight" (reason: Not supported for "HDMI-0")
error: Disabling module "wireless-network" (reason: Invalid network interface "net1")
error: Disabling module "wired-network" (reason: Invalid network interface "net0")
error: Disabling module "battery" (reason: No suitable way to get current charge state)

**Comment by Eibx** [comment]
**error: Disabling module "mpd" (reason: No built-in support for 'internal/mpd')**
I think you need `libmpdclient` for it to work.

**error: Disabling module "volume" (reason: Cannot find simple element)**
Try taking a look here: https://github.com/jaagr/polybar/issues/491

**error: module/backlight: Could not get data (err: XCB_NAME (15))**
Try chaning `internal/xbacklight` to the legacy `internal/backlight` [on line 52](https://github.com/jaagr/dots/blob/master/.local/etc/themer/themes/space/polybar#L52).
You might have to remove this sections if it's not supported on your system.

**error: Disabling module "wireless-network" (reason: Invalid network interface "net1")**
**error: Disabling module "wired-network" (reason: Invalid network interface "net0")**
I think you just have to change your interface names. Try running `ifconfig` and see what options you have. For the most part `wired-network` is `eth0` and `wired'network` is `wlan0` - you should change the names [here](https://github.com/jaagr/dots/blob/master/.local/etc/themer/themes/space/polybar#L279) and [here](https://github.com/jaagr/dots/blob/master/.local/etc/themer/themes/space/polybar#L256)

**error: Disabling module "battery" (reason: No suitable way to get current charge state)**
I'm not sure about this one, if you're on desktop I think you should just remove it. It's done by removing from [line 70](https://github.com/jaagr/dots/blob/master/.local/etc/themer/themes/space/polybar#L70) to [line 100](https://github.com/jaagr/dots/blob/master/.local/etc/themer/themes/space/polybar#L100) and removing `battery` from [this list](https://github.com/jaagr/dots/blob/master/.local/etc/themer/themes/space/polybar#L22).

Hope this helps.

**Comment by tjw0lf** [comment]
Thanks for your quick reply awesome support. Eibx Thank you. 
I did open another ticket just for mpd here https://github.com/jaagr/polybar/issues/697#issuecomment-322393837

i did install this is installed libmpdclient. But i think i installed it after will post more in my other ticket take a look

The other stuff i will follow steps and get back to you
