### ISSUE TITLE
Polybar does not update volume module when using Bluetooth headset

### ISSUE THREAD

**Issue by Hacksaurus** [jaagr/polybar#693]
Whenever I use my bluetooth headset, I noticed that the volume rocker does not update accordingly. But it does this when I use my normal wired headphones. 

Thanks for any help!

**Comment by patrick96** [comment]
Yeah getting the right volume display is a hassle.
I'm assuming you are using the built-in volume module
Your bluetooth headset driver probably registered a new sound card but polybar just displays the values for the default (this works for the wired headphones because they use the same soundcard).
You'll have set the proper soundcard in the config, you can see all available cards in `/proc/asound/cards`, for me the headphones have id `0`, so you'd have to set `hw:0` as the card name.
You can list the mixers for the card using `amixer -c 0 scontrols` and you can find the `headphone-id` by calling `amixer -c 0 controls`.
Since you can only specify `headphone-id` once, you either have to choose which headphones you want to display or you have to have two separate modules, one specifically for the bluetooth headset and one for the rest.

If you are using pulseaudio, I'd recommend using the [`pavolume`](https://github.com/jaagr/polybar/wiki/User-contributed-modules#pulseaudio-volume) user-contributed module. For me, it always displays the proper volume, but it may take some setup.

**Comment by Hacksaurus** [comment]
Hm, I think what you are thinking about is that polybar NEVER shows the correct volume... But in my case it does... but only AFTER you restart polybar, and the headset is considered the "Master" option, whenever I check in in amixer or alsamixer... So I'm not so sure what to do about this...

**Comment by patrick96** [comment]
You probably have your soundcards set to `default` and when you switch to the headset, the headset soundcard becomes the default. polybar doesn't notice this because it only sets up its soundcards when it starts and doesn't reload them. This is also why the correct volume is displayed after it restarts.

The way I described above should also work for this case or you could just restart the bar everytime you use the bluetooth headset

**Comment by Hacksaurus** [comment]
@patrick96 Alright that sounds good.. But I am still sort of confused on how to add my headphone id to polybar... For starters I dont' know what mixer is my headphones... This is the out output of `amixer -c 0 scontrols`:

```
Simple mixer control 'Master',0
Simple mixer control 'Headphone',0
Simple mixer control 'Speaker',0
Simple mixer control 'PCM',0
Simple mixer control 'Mic Boost',0
Simple mixer control 'IEC958',0
Simple mixer control 'IEC958',1
Simple mixer control 'IEC958',2
Simple mixer control 'IEC958',3
Simple mixer control 'IEC958',4
Simple mixer control 'Capture',0
Simple mixer control 'Auto-Mute Mode',0
Simple mixer control 'Loopback Mixing',0
```
And `amixer -c 0 scontrols`:

```
numid=41,iface=CARD,name='HDMI/DP,pcm=10 Jack'
numid=17,iface=CARD,name='HDMI/DP,pcm=3 Jack'
numid=23,iface=CARD,name='HDMI/DP,pcm=7 Jack'
numid=29,iface=CARD,name='HDMI/DP,pcm=8 Jack'
numid=35,iface=CARD,name='HDMI/DP,pcm=9 Jack'
numid=13,iface=CARD,name='Headphone Jack'
numid=12,iface=CARD,name='Mic Phantom Jack'
numid=14,iface=CARD,name='Speaker Phantom Jack'
numid=11,iface=MIXER,name='Master Playback Switch'
numid=10,iface=MIXER,name='Master Playback Volume'
numid=2,iface=MIXER,name='Headphone Playback Switch'
numid=1,iface=MIXER,name='Headphone Playback Volume'
numid=52,iface=MIXER,name='PCM Playback Volume'
numid=9,iface=MIXER,name='Mic Boost Volume'
numid=8,iface=MIXER,name='Capture Switch'
numid=7,iface=MIXER,name='Capture Volume'
numid=5,iface=MIXER,name='Loopback Mixing'
numid=18,iface=MIXER,name='IEC958 Playback Con Mask'
numid=24,iface=MIXER,name='IEC958 Playback Con Mask',index=1
numid=30,iface=MIXER,name='IEC958 Playback Con Mask',index=2
numid=36,iface=MIXER,name='IEC958 Playback Con Mask',index=3
numid=42,iface=MIXER,name='IEC958 Playback Con Mask',index=4
numid=19,iface=MIXER,name='IEC958 Playback Pro Mask'
numid=25,iface=MIXER,name='IEC958 Playback Pro Mask',index=1
numid=31,iface=MIXER,name='IEC958 Playback Pro Mask',index=2
numid=37,iface=MIXER,name='IEC958 Playback Pro Mask',index=3
numid=43,iface=MIXER,name='IEC958 Playback Pro Mask',index=4
numid=20,iface=MIXER,name='IEC958 Playback Default'
numid=26,iface=MIXER,name='IEC958 Playback Default',index=1
numid=32,iface=MIXER,name='IEC958 Playback Default',index=2
numid=38,iface=MIXER,name='IEC958 Playback Default',index=3
numid=44,iface=MIXER,name='IEC958 Playback Default',index=4
numid=21,iface=MIXER,name='IEC958 Playback Switch'
numid=27,iface=MIXER,name='IEC958 Playback Switch',index=1
numid=33,iface=MIXER,name='IEC958 Playback Switch',index=2
numid=39,iface=MIXER,name='IEC958 Playback Switch',index=3
numid=45,iface=MIXER,name='IEC958 Playback Switch',index=4
numid=6,iface=MIXER,name='Auto-Mute Mode'
numid=4,iface=MIXER,name='Speaker Playback Switch'
numid=3,iface=MIXER,name='Speaker Playback Volume'
numid=16,iface=PCM,name='Capture Channel Map'
numid=15,iface=PCM,name='Playback Channel Map'
numid=22,iface=PCM,name='ELD',device=3
numid=47,iface=PCM,name='Playback Channel Map',device=3
numid=28,iface=PCM,name='ELD',device=7
numid=48,iface=PCM,name='Playback Channel Map',device=7
numid=34,iface=PCM,name='ELD',device=8
numid=49,iface=PCM,name='Playback Channel Map',device=8
numid=40,iface=PCM,name='ELD',device=9
numid=50,iface=PCM,name='Playback Channel Map',device=9
numid=46,iface=PCM,name='ELD',device=10
numid=51,iface=PCM,name='Playback Channel Map',device=10
```
How do I figure out what mixer is my bluetooth headphones?

**Comment by patrick96** [comment]
It looks like that is the output for your internal soundcard. Can you give
me the contents of `/proc/asound/cards/` and then the output of those
commands again with the number for the headphone soundcard

**Comment by Hacksaurus** [comment]
This is what the cards file has:
```
 0 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xef128000 irq 129
```

Not exactly sure what this output means...

**Comment by Hacksaurus** [comment]
@patrick96 Do you have any idea what to do know with this info?

**Comment by patrick96** [comment]
I'll have to look into this later, as I'm going on vacation

**Comment by Hacksaurus** [comment]
Alright, I'll check with you later!

Thank you for your help!

**Comment by Hacksaurus** [comment]
Hey, I attempted to tackle this issue once more with a fresh mind and still don't understand how to do this...

If you are still on vacation, you can simply ignore this.
Thanks for the help so far!

**Comment by patrick96** [comment]
I'm not totally sure what's happening.
Your `/proc/asound/cards/` only contains a single entry, so the bluetooth headset operates through the internal soundcard. So probably the bluetooth headset takes over the master mixer once it is connected but polybar only recognizes this after a restart.
Can you post your current volume module and the output of `amixer -c 0 scontrols` and `amixer -c 0 controls` once with the bluetooth headset connected and enabled and once with the headset not connected at all.

**Comment by Hacksaurus** [comment]
I tested multiple times and achieved the same results... there have no changes in either of those commands:
This is what `amixer -c 0 scontrols && amixer -c 0 controls` give me when the bluetooth headset is connected and not connected...
```
Simple mixer control 'Master',0
Simple mixer control 'Headphone',0
Simple mixer control 'Speaker',0
Simple mixer control 'PCM',0
Simple mixer control 'Mic Boost',0
Simple mixer control 'IEC958',0
Simple mixer control 'IEC958',1
Simple mixer control 'IEC958',2
Simple mixer control 'IEC958',3
Simple mixer control 'IEC958',4
Simple mixer control 'Capture',0
Simple mixer control 'Auto-Mute Mode',0
Simple mixer control 'Loopback Mixing',0
numid=41,iface=CARD,name='HDMI/DP,pcm=10 Jack'
numid=17,iface=CARD,name='HDMI/DP,pcm=3 Jack'
numid=23,iface=CARD,name='HDMI/DP,pcm=7 Jack'
numid=29,iface=CARD,name='HDMI/DP,pcm=8 Jack'
numid=35,iface=CARD,name='HDMI/DP,pcm=9 Jack'
numid=13,iface=CARD,name='Headphone Jack'
numid=12,iface=CARD,name='Mic Phantom Jack'
numid=14,iface=CARD,name='Speaker Phantom Jack'
numid=11,iface=MIXER,name='Master Playback Switch'
numid=10,iface=MIXER,name='Master Playback Volume'
numid=2,iface=MIXER,name='Headphone Playback Switch'
numid=1,iface=MIXER,name='Headphone Playback Volume'
numid=52,iface=MIXER,name='PCM Playback Volume'
numid=9,iface=MIXER,name='Mic Boost Volume'
numid=8,iface=MIXER,name='Capture Switch'
numid=7,iface=MIXER,name='Capture Volume'
numid=5,iface=MIXER,name='Loopback Mixing'
numid=18,iface=MIXER,name='IEC958 Playback Con Mask'
numid=24,iface=MIXER,name='IEC958 Playback Con Mask',index=1
numid=30,iface=MIXER,name='IEC958 Playback Con Mask',index=2
numid=36,iface=MIXER,name='IEC958 Playback Con Mask',index=3
numid=42,iface=MIXER,name='IEC958 Playback Con Mask',index=4
numid=19,iface=MIXER,name='IEC958 Playback Pro Mask'
numid=25,iface=MIXER,name='IEC958 Playback Pro Mask',index=1
numid=31,iface=MIXER,name='IEC958 Playback Pro Mask',index=2
numid=37,iface=MIXER,name='IEC958 Playback Pro Mask',index=3
numid=43,iface=MIXER,name='IEC958 Playback Pro Mask',index=4
numid=20,iface=MIXER,name='IEC958 Playback Default'
numid=26,iface=MIXER,name='IEC958 Playback Default',index=1
numid=32,iface=MIXER,name='IEC958 Playback Default',index=2
numid=38,iface=MIXER,name='IEC958 Playback Default',index=3
numid=44,iface=MIXER,name='IEC958 Playback Default',index=4
numid=21,iface=MIXER,name='IEC958 Playback Switch'
numid=27,iface=MIXER,name='IEC958 Playback Switch',index=1
numid=33,iface=MIXER,name='IEC958 Playback Switch',index=2
numid=39,iface=MIXER,name='IEC958 Playback Switch',index=3
numid=45,iface=MIXER,name='IEC958 Playback Switch',index=4
numid=6,iface=MIXER,name='Auto-Mute Mode'
numid=4,iface=MIXER,name='Speaker Playback Switch'
numid=3,iface=MIXER,name='Speaker Playback Volume'
numid=16,iface=PCM,name='Capture Channel Map'
numid=15,iface=PCM,name='Playback Channel Map'
numid=22,iface=PCM,name='ELD',device=3
numid=47,iface=PCM,name='Playback Channel Map',device=3
numid=28,iface=PCM,name='ELD',device=7
numid=48,iface=PCM,name='Playback Channel Map',device=7
numid=34,iface=PCM,name='ELD',device=8
numid=49,iface=PCM,name='Playback Channel Map',device=8
numid=40,iface=PCM,name='ELD',device=9
numid=50,iface=PCM,name='Playback Channel Map',device=9
numid=46,iface=PCM,name='ELD',device=10
numid=51,iface=PCM,name='Playback Channel Map',device=10
```

**Comment by patrick96** [comment]
I don't know if this is solvable with the `volume` module. If you don't use your bluetooth headset that often, you could manually reload the bar everytime you connect or disconnect it. The only other option I can offer is using the [`pavolume`](https://github.com/jaagr/polybar/wiki/User-contributed-modules#pulseaudio-volume) user contributed module, but that will only work, if you are using the PulseAudio sound system.

@NBonaparte maybe you have another idea what's going on here

**Comment by Hacksaurus** [comment]
I think I might use the `pavulume` module you have mentioned, I do use the Pulse Audio System... definitely check it out!

**Comment by patrick96** [comment]
For pulseaudio the pavolume module is the best option. The internal volume module can't really handle anything more sophisticated than speakers and wired headphones

**Comment by Hacksaurus** [comment]
The pavolume works perfectly!
I won't really use it though because it seems sluggish even if I put the interval quite low...
Thank you for your help!

Closing issue!

**Comment by patrick96** [comment]
@Hacksaurus I have updated the pavolume script with a `--listen` argument which makes it update immediately if there has been a volume or device change.

**Comment by Hacksaurus** [comment]
Cool! I might use it now...
But I might have to change the output function a bit so it seems like the normal volume script, where there are different levels of the icon...
Thank you!
