### ISSUE TITLE
Only update systemtray

### ISSUE THREAD

**Issue by Hacksaurus** [jaagr/polybar#694]
Hello, This isn't really an issue, but more of a question.
I set up my i3 config so that I can quickly restart my polybar. But I was also wondering if there is a command where I can also quickly restart just my systemtray, because the only main reason I restart my polybar is so that I can align the items on my systemtray. (Since there is no current workaround his, since this is an i3 issue)

**Comment by ecly** [comment]
Out of curiousity. What do you mean with align the items in your system tray? My tray breaks in the form of going black when I reload my i3 config, in which case I indeed restart polybar. Is it the same issue just perceived different?

**Comment by Hacksaurus** [comment]
My tray does that *sometimes*, but what happens most of the time (especially if they are autostart things) is that it some of the icons sort of misalign...

**Comment by Hacksaurus** [comment]
Now that I think about it, it seems like my bluetooth is the one that misaligned the most... Hm, I wonder if other people have this problem...

**Comment by ecly** [comment]
@Hacksaurus I can see what you mean in terms of horizontal gap between icons (only to the right of bluetooth), although I think it looks better in the 'after restarting' photo. With my limited eyesight I can't tell, is there no chance that it just looks different depending on the adjacent icons, and doesn't actually cause excess gap?

**Comment by Hacksaurus** [comment]
That's probably true, and the the may cause for this misalignment is the blueman icon itself, I'm currently researching into this.... Closing this because it doesn't seem like a polybar issue.... But please feel free to give me some solutions!
