### ISSUE TITLE
Need help with setting polybar

### ISSUE THREAD

**Issue by Mauladen** [jaagr/polybar#695]
Good afternoon, found your wonderful polybar and it works perfectly :) Then took the existing config and everything is configured as I need, but after I applied it there was one problem, I have icons with text are not in the middle, and went up a bit though, such problems the person was not and it was all wonderful.

Here is a screenshot of how it should be and as I have
P.S. I have not changed anything

As it should be:
![Imgur](https://i.imgur.com/af63kkn.png)

As I have:
![Imgur](https://i.imgur.com/Jy2XeIz.png)

As you can see I have the elements have gone up a bit and I want to fix font it does not depend on, I tried

**Comment by NBonaparte** [comment]
See https://github.com/jaagr/polybar/wiki/Fonts. More specifically, look at this line: `font-N = <fontconfig pattern>;<vertical offset>` and fiddle with the vertical offset for the icon font.

**Comment by Mauladen** [comment]
Read the documentation, but did not reach the fonts 
Thank you very much for your help, and I need to be careful
