### ISSUE TITLE
mpd help

### ISSUE THREAD

**Issue by tjw0lf** [jaagr/polybar#697]
error: Disabling module "mpd" (reason: No built-in support for 'internal/mpd')

**Comment by patrick96** [comment]
You didn't compile polybar with support for mpd, you most likely didn't have `libmpdclient` installed when compiling.

**Comment by tjw0lf** [comment]
yeah i think i installed that after libmpdclient. But i didn't compile polybar i installed the polybar.git through pamac on Arch. so should i build it instead or reinstall polybar.git through pamac again.

Thank you for your fast reply patrick96

**Comment by patrick96** [comment]
Reinstalling through pamac should be enough. Just make sure to clean the
build directory before you do that, otherwise it's possible that you just
reinstall the version you compiled before

**Comment by tjw0lf** [comment]
OK thank you this fixed it for me. I didn't clean the build dir anyways its fixed. How would i do that just so i know for next time

**Comment by patrick96** [comment]
I'm not familiar with pamac, but it will clone the polybar.git aur repo somewhere on your hard drive. Just deleting that repo will force it to redownload the whole thing again.

**Comment by praton1729** [comment]
libmpdclient has now been replaced by libmpdclient2, Does polybar have support that?
