### ISSUE TITLE
help with creating launchers on polybar

### ISSUE THREAD

**Issue by tjw0lf** [jaagr/polybar#699]
I found a polybar config to work with somebody shared. I fixed couple things on it. This was supposed to be for bswpn but it works great in openbox also.

[bar/top]
monitor = ${env:MONITOR:HDMI-0}
width = 100%
height = 35 
offset-x = 0
offset-y = -1 
;bottom = true

background = #5a000000
foreground = #eee

underline-size = 2
underline-color = #eee

spacing = 1
padding-left = 0
padding-right = 0
module-margin-left = 0 
module-margin-right = 0

font-0 = Noto Sans:pixelsize=13;0
font-1 = FontAwesome:size=10;-2
font-2 = siji:pixelsize=10;0

modules-left = xwindow
modules-center = 
modules-right = volume mpd date powermenu

;tray-position = right
;tray-padding = 2
;tray-background = #66333333

;wm-restack = bspwm

scroll-up = bspwm-desknext
scroll-down = bspwm-deskprev

; MODULES

right here i thought these where the launchers that added them to polybar. somebody can help me Thank you 

[module/workspaces]
type = internal/xworkspaces
enable-click = true
enable-scroll = true
Additional formatting

icon-0 = web;
icon-1 = term;
icon-2 = chat;
icon-3 = code;
icon-4 = music;
icon-default = 

label-monitor = %name%
format = <label-state> <label-mode>

label-focused = %icon%
label-focused-background = #88000000
label-focused-underline= #ddd
label-focused-padding = 4

label-occupied = %icon%
label-occupied-padding = 4

label-urgent = %icon%
label-urgent-padding = 4

label-empty = %icon%
label-empty-foreground = #44ffffff
label-empty-padding = 4

[module/xwindow]
type = internal/xwindow
label = %title:0:120:...%
label-padding = 4

[module/date]
type = internal/date

; Seconds to sleep between updates
interval = 1.0

; See "man date" for details on how to format the date string
; NOTE: if you want to use syntax tags here you need to use %%{...}
date = %a %b %d, 

; Optional time format
time = %H:%M

; if `date-alt` or `time-alt` is defined, clicking
; the module will toggle between formats
date-alt = %A, %d %B %Y
time-alt = %H:%M:%S

label = %date% %time%
format =    <label>
;format-background = #ddffffff
format-background = #88000000
;format-foreground = #333
format-padding = 3

[module/padding]
type = custom/text
content = 	 
content-foreground = #00000000
content-background = #55000000

[module/backlight]
type = internal/backlight

card = intel_backlight
enable-scroll = true

format = <ramp> <label>
label = %percentage%

ramp-0 = 🌕
ramp-1 = 🌔
ramp-2 = 🌓
ramp-3 = 🌒
ramp-4 = 🌑

[module/volume]
type = internal/volume

format-volume = <ramp-volume>  <label-volume>
format-muted = <label-muted>
label-volume = %percentage%
label-muted =   muted
label-muted-foreground = #aaa
format-volume-padding = 3
format-muted-padding = 3

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-headphones-0 = 

[module/powermenu]
type = custom/menu

label-open =   
;label-open-background = #dd0000
;label-open-foreground = #fff
label-close = cancel
;label-close-background = #dd0000
;label-close-foreground = #fff
label-open-padding = 4 
label-close-padding = 3 

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2
menu-0-0-padding = 3
menu-0-1-padding = 3

menu-1-0 = reboot?  
menu-1-0-exec = sudo reboot
menu-1-0-padding = 3

menu-2-0 = power off?  
menu-2-0-exec = sudo poweroff
menu-2-0-padding = 3

[module/network]
type = internal/network
interface = enp8s0

; Seconds to sleep between updates
; Default: 1
interval = 3.0

; Test connectivity every Nth update
; A value of 0 disables the feature
; NOTE: Experimental (needs more testing)
; Default: 0
;ping-interval = 3

; @deprecated: Define min width using token specifiers (%downspeed:min% and %upspeed:min%)
; Minimum output width of upload/download rate
; Default: 3
udspeed-minwidth = 5

; Accumulate values from all interfaces
; when querying for up/downspeed rate
; Default: false
accumulate-stats = true

[module/mpd]
type = internal/mpd

host = 127.0.0.1
port = 6600
interval = 1

format-online =    <label-song>

label-song = %artist% - %title%
label-offline = ---
format-offline = 
icon-prev = 
icon-seekb = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 
icon-seekf = 

icon-random = 
icon-repeat = 

toggle-on-foreground = #888888
toggle-off-foreground = #68

bar-progress-width = 45
bar-progress-format = %{A4:mpdseek+2: A5:mpdseek-2:}%fill%%indicator%%empty%%{A A}
bar-progress-indicator = |
bar-progress-indicator-foreground = #ff
bar-progress-indicator-font = 3
bar-progress-fill = ─
bar-progress-fill-foreground = #bb
bar-progress-fill-font = 3
bar-progress-empty = ─
bar-progress-empty-font = 3
bar-progress-empty-foreground = #44

**Comment by patrick96** [comment]
Sorry, I may have overlooked something, but is there a problem with this config? From your description it seems that it works just fine.

**Comment by tjw0lf** [comment]
right here i thought these where the launchers that added them to polybar. somebody can help me. I wanted web browser on polybar few others and workspaces i thought this was it but they don't show on polybar


Thank you

[module/workspaces]
type = internal/xworkspaces
enable-click = true
enable-scroll = true
Additional formatting

icon-0 = web;
icon-1 = term;
icon-2 = chat;
icon-3 = code;
icon-4 = music;
icon-default = 

**Comment by patrick96** [comment]
No, those are the workspaces, also sometimes called virtual desktops, that your window manager provides, this module will show you which workspace you are currently on.

If you want something like a launcher, have a look at the [menu](https://github.com/jaagr/polybar/wiki/Module:-menu) module

**Comment by tjw0lf** [comment]
OK then what are those icons for because i don't see them pop up at all. I did copy this into me config but nothing still showed

[module/menu-apps]
type = custom/menu

; "menu-LEVEL-N" has the same properties as "label-NAME" with
; the additional "exec" property
;
; Available exec commands:
;   menu-open-LEVEL
;   menu-close
; Other commands will be executed using "/usr/bin/env sh -c $COMMAND"

menu-0-0 = Browsers
menu-0-0-exec = menu-open-1
menu-0-2 = Multimedia
menu-0-2-exec = menu-open-2

menu-1-0 = Firefox
menu-1-0-exec = firefox &
menu-1-1 = Chromium
menu-1-1-exec = chromium &

menu-2-0 = Gimp
menu-2-0-exec = gimp &
menu-2-1 = Scrot
menu-2-1-exec = scrot &

**Comment by patrick96** [comment]
Did you add `menu-apps` to the list of displayed modules?
There should be `menu-apps` written somewhere on your bar, if you click it, it will show two options: "Browsers" and "Multimedia", clicking one of those will display you more options.

**Comment by tjw0lf** [comment]
yeah see i added it to the config but its not showing up

[bar/top]
monitor = ${env:MONITOR:HDMI-0}
width = 100%
height = 35 
offset-x = 0
offset-y = -1 
;bottom = true

background = #5a000000
foreground = #eee

underline-size = 2
underline-color = #eee

spacing = 1
padding-left = 0
padding-right = 0
module-margin-left = 0 
module-margin-right = 0

font-0 = Noto Sans:pixelsize=13;0
font-1 = FontAwesome:size=10;-2
font-2 = siji:pixelsize=10;0

modules-left = xwindow
modules-center = 
modules-right = volume mpd date powermenu

;tray-position = right
;tray-padding = 2
;tray-background = #66333333

;wm-restack = bspwm

scroll-up = bspwm-desknext
scroll-down = bspwm-deskprev

; MODULES

[module/workspaces]
type = internal/xworkspaces
enable-click = true
enable-scroll = true
Additional formatting

icon-0 = web;
icon-1 = term;
icon-2 = chat;
icon-3 = code;
icon-4 = music;
icon-default = 

label-monitor = %name%
format = <label-state> <label-mode>

label-focused = %icon%
label-focused-background = #88000000
label-focused-underline= #ddd
label-focused-padding = 4

label-occupied = %icon%
label-occupied-padding = 4

label-urgent = %icon%
label-urgent-padding = 4

label-empty = %icon%
label-empty-foreground = #44ffffff
label-empty-padding = 4

[module/menu-apps]
type = custom/menu

; "menu-LEVEL-N" has the same properties as "label-NAME" with
; the additional "exec" property
;
; Available exec commands:
;   menu-open-LEVEL
;   menu-close
; Other commands will be executed using "/usr/bin/env sh -c $COMMAND"

menu-0-0 = Browsers
menu-0-0-exec = menu-open-1
menu-0-2 = Multimedia
menu-0-2-exec = menu-open-2

menu-1-0 = Firefox
menu-1-0-exec = firefox &
menu-1-1 = Chromium
menu-1-1-exec = chromium &

menu-2-0 = Gimp
menu-2-0-exec = gimp &
menu-2-1 = Scrot
menu-2-1-exec = scrot &

[module/xwindow]
type = internal/xwindow
label = %title:0:120:...%
label-padding = 4

[module/date]
type = internal/date

; Seconds to sleep between updates
interval = 1.0

; See "man date" for details on how to format the date string
; NOTE: if you want to use syntax tags here you need to use %%{...}
date = %a %b %d, 

; Optional time format
time = %H:%M

; if `date-alt` or `time-alt` is defined, clicking
; the module will toggle between formats
date-alt = %A, %d %B %Y
time-alt = %H:%M:%S

label = %date% %time%
format =    <label>
;format-background = #ddffffff
format-background = #88000000
;format-foreground = #333
format-padding = 3

[module/padding]
type = custom/text
content = 	 
content-foreground = #00000000
content-background = #55000000

[module/backlight]
type = internal/backlight

card = intel_backlight
enable-scroll = true

format = <ramp> <label>
label = %percentage%

ramp-0 = 🌕
ramp-1 = 🌔
ramp-2 = 🌓
ramp-3 = 🌒
ramp-4 = 🌑

[module/volume]
type = internal/volume

format-volume = <ramp-volume>  <label-volume>
format-muted = <label-muted>
label-volume = %percentage%
label-muted =   muted
label-muted-foreground = #aaa
format-volume-padding = 3
format-muted-padding = 3

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-headphones-0 = 


[module/powermenu]
type = custom/menu

label-open =   
;label-open-background = #dd0000
;label-open-foreground = #fff
label-close = cancel
;label-close-background = #dd0000
;label-close-foreground = #fff
label-open-padding = 4 
label-close-padding = 3 

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2
menu-0-0-padding = 3
menu-0-1-padding = 3

menu-1-0 = reboot?  
menu-1-0-exec = sudo reboot
menu-1-0-padding = 3

menu-2-0 = power off?  
menu-2-0-exec = sudo poweroff
menu-2-0-padding = 3

[module/network]
type = internal/network
interface = enp8s0

; Seconds to sleep between updates
; Default: 1
interval = 3.0

; Test connectivity every Nth update
; A value of 0 disables the feature
; NOTE: Experimental (needs more testing)
; Default: 0
;ping-interval = 3

; @deprecated: Define min width using token specifiers (%downspeed:min% and %upspeed:min%)
; Minimum output width of upload/download rate
; Default: 3
udspeed-minwidth = 5

; Accumulate values from all interfaces
; when querying for up/downspeed rate
; Default: false
accumulate-stats = true

[module/mpd]
type = internal/mpd

host = 127.0.0.1
port = 6600
interval = 1

format-online =    <label-song>

label-song = %artist% - %title%
label-offline = ---
format-offline = 
icon-prev = 
icon-seekb = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 
icon-seekf = 

icon-random = 
icon-repeat = 

toggle-on-foreground = #888888
toggle-off-foreground = #68

bar-progress-width = 45
bar-progress-format = %{A4:mpdseek+2: A5:mpdseek-2:}%fill%%indicator%%empty%%{A A}
bar-progress-indicator = |
bar-progress-indicator-foreground = #ff
bar-progress-indicator-font = 3
bar-progress-fill = ─
bar-progress-fill-foreground = #bb
bar-progress-fill-font = 3
bar-progress-empty = ─
bar-progress-empty-font = 3
bar-progress-empty-foreground = #44

**Comment by patrick96** [comment]
No you have to list all modules you want to be displayed in either `modules-left`, `modules-center` or `modules-right`.
Also you can only have one `menu` module per bar, there is already the `powermenu` module in there, so you'll need to remove that.

**Comment by tjw0lf** [comment]
What do you mean can you show me so i see? Also i like that power menu so is there a way to add browser too and stuff

**Comment by tjw0lf** [comment]
OK i got you patrick96 Thank you
