### ISSUE TITLE
`tput: No value for $TERM and `.... when trying to run custom script

### ISSUE THREAD

**Issue by guyfedwards** [jaagr/polybar#703]
I am trying to add the package updates script but am just seeing `tput: No value for $TERM and ` in polybar? 

polybar/config
```
[module/pkg]
type = custom/script
label = "%output:0:30%"
interval = 1200
format = <label>
format-underline = #dc322f

exec = ~/.config/polybar/pkg.sh
exec-if = "ping -q -w 2 -c 1 176.34.135.167 > /dev/null"
```

polybar/pkg.sh
```
#!/bin/bash

pac=$(checkupdates | wc -l)
aur=$(yaourt -Qqu -a | wc -l)



echo "$pac $aur" >> ~/tmp.log
check=$((pac + aur))
echo " $check" >> ~/tmp.log
if [[ "$check" != "0" ]]
then
    echo "$pac $aur"
fi
```

**Comment by patrick96** [comment]
You didn't set the `$TERM` variable in your terminal when starting polybar. `yaourt` relies on `tput` which in turn relies on `$TERM` being set. You should export the apropriate TERM variable in your terminal.

Normally your terminal should do that for you, either correct that in your terminal settings or export it manually in your `.bashrc` (or whatever config file your shell uses)

**Comment by guyfedwards** [comment]
That is set if I run polybar from the terminal but it gets launched in i3 config using `exec_always --no-startup-id ~/.config/polybar/start`. Whats the best way to have the variable set when that command is called within i3

**Comment by patrick96** [comment]
How is i3 started?
Generally the `TERM` variable should be set when you log in but it seems like it isn't. So either something is actively unsetting `TERM` or something else is not behaving as it should. You could add something like
```bash
if [ -z "$TERM]; then
  export TERM=xterm
fi
```
to your `/etc/profile` to maybe fix this.

**Comment by wbollock** [comment]
I know this is nearly 4 years old and I'm necroing, but had the same problem with special/colored text in a custom script. 

Added `export TERM=xterm` to /etc/profile, .xinitrc, .zshrc, .bashrc, my Terminator config, and to the custom scripts themselves and couldn't get anything working.

Also, the syntax is a little wrong for the if statement:

```
if [ -z "$TERM" ]; then
  export TERM=xterm
fi
```
