### ISSUE TITLE
polybar not printing certain utf8 symbols

### ISSUE THREAD

**Issue by gregf** [jaagr/polybar#705]
I'm unable to print \U266a in polybar. I use the same font on my console and polybar. When I print it on the console it displays properly.

```
printf "\U266a"
♪
```

I see the following output from polybar

```
polybar|warn:  Dropping unmatched character ♪ (U+266a)
```

The font is a patched copy of bitstreamverasansmono with nerdfont complete You can find the font [here](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/BitstreamVeraSansMono/Regular/complete)

If I use the same font in i3blocks it prints fine.

**Comment by patrick96** [comment]
What is the output when you run polybar with `-l info`?

It is possible that polybar does not recognize the font and just loads the default one.

**Comment by gregf** [comment]
I managed to fix it with a fallback font. I think it was working on the console because I had the fallback font set.
