### ISSUE TITLE
Fixed width i3 module workspaces

### ISSUE THREAD

**Issue by edasaki** [jaagr/polybar#707]
Is it possible to force a size for all of the workspaces? I am using roman numerals like I II III etc. for my workspaces, and as a result each of them has a slightly different size.

For example,

![](http://i.imgur.com/oPs2cnD.png)

vs (the much thinner)

![](http://i.imgur.com/nJu1l20.png)

I'd like to be able to make them all the same width, not sure if I'm missing a config or if it isn't possible right now.

Edit: So I just realized there's a min-width option for tokens so I can have like %name:10%, but is there any way to center this?

**Comment by patrick96** [comment]
It may be possible to just define the icons for the workspaces as `"  I   "`, `"  II  "` and so on, like this you should be able to have fixed width while also having the text centered (more or less)
