### ISSUE TITLE
percentage_used incorrect

### ISSUE THREAD

**Issue by chasebolt** [jaagr/polybar#710]
I am expecting to see 3% used but instead polybar is displaying 7%.

```
$ df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       458G  9.9G  425G   3% /
```

```
[module/filesystem]
type = internal/fs
mount-0 = /
format-mounted = DISK   <label-mounted>
label-mounted = %mountpoint%: %used%/%total% (%percentage_used%%)
```

![2017_08_24-11 47 05](https://user-images.githubusercontent.com/1222984/29683104-199803d0-88c2-11e7-8c84-45746ad4a637.png)

**Comment by NBonaparte** [comment]
This may be caused by the differences in the way `df` calculates usage. It doesn't take into account the reserved space (5%). Please check if f1dfb60 fixes this, and reopen if it doesn't.
