### ISSUE TITLE
[Multimonitor] Laptop screen not detected when cloning to external display

### ISSUE THREAD

**Issue by mhham** [jaagr/polybar#711]
I am cloning my laptop display (eDP1) to an external HDMI display (HDMI2) using `xrandr` :
```
xrandr --output eDP1 --auto --output HDMI2 --auto --same-as eDP1
```
My polybar is configured with:
```
monitor = eDP1
monitor-fallback = HDMI2
monitor-strict = false
```
I get the following error messages when launching the bar:
```
warn: Monitor "eDP1" not found, reverting to fallback "HDMI2"
error: Disabling module "xbacklight" (reason: No matching output found for "eDP1", stopping module...)
```
This does not happen when I only use the laptop screen alone (eDP1) or both screen in a non cloned mode (`xrandr --output HDMI2 --mode 1920x1080 --pos 0x0 --rotate normal --output eDP1 --primary --mode 1920x1080 --pos 2072x0 --rotate normal`)

**Comment by NBonaparte** [comment]
Possibly related to #499?
