### ISSUE TITLE
always on top w/ openbox

### ISSUE THREAD

**Issue by sphaugh** [jaagr/polybar#713]
Is there any hope for `wm-restack` in openbox? It's really frustrating on a single monitor. Love polybar with i3 though :)

**Comment by NBonaparte** [comment]
Duplicate of #425.

**Comment by patrick96** [comment]
Is the whole bar above fullscreen windows? If so try to set `override-redirect = false`

**Comment by sphaugh** [comment]
It works with `override-redirect = false`, I'll go ahead and close this :)
Thanks!
