### ISSUE TITLE
How to add i3 mode to bar (eg resize or any custom modes)

### ISSUE THREAD

**Issue by JarrColl** [jaagr/polybar#714]
I have looked through the i3 module page and didn't find anything to get it working.

**Comment by 0rdy** [comment]
Do you want something like the following screenshot?
![i3](https://user-images.githubusercontent.com/9018005/29810134-5d058ed8-8ca7-11e7-8172-a0653167e0b7.png)
If so, check out available tags in the i3 module page. To display your current mode after i3 workspaces you can use the following setting:
```ini
[module/i3]
...
format = <label-state> <label-mode>
```

**Comment by JarrColl** [comment]
thats exactly what i'm looking for, thanks.
