### ISSUE TITLE
CMus Module Issue

### ISSUE THREAD

**Issue by AravK** [jaagr/polybar#715]
[cmus-sh-new.zip](https://github.com/jaagr/polybar/files/1254330/cmus-sh-new.zip)
I know it's user contributed, but I found an issue.
When CMus is not playing music, errors occur. I've made a slightly more complex but easier to edit version. It's a drop-in replacement for the old script.

**Comment by NBonaparte** [comment]
Feel free to put in the wiki, as it is editable by everyone.

**Comment by DrDonkey** [comment]
@ghost How to use this?

**Comment by patrick96** [comment]
@DrDonkey There is no built-in cmus support for polybar you can write your own cmus module using the [script module](https://github.com/jaagr/polybar/wiki/Module:-script). There is already a cmus script over at [polybar-scripts](https://github.com/x70b1/polybar-scripts/tree/master/polybar-scripts/player-cmus), don't know if it works though.

**Comment by DrDonkey** [comment]
It did work thank you so much.
