### ISSUE TITLE
Nothing works on Gentoo

### ISSUE THREAD

**Issue by letFunny** [jaagr/polybar#716]
I have installed i3-gaps + compton and polybar. It has succesfully installed with no errors and i have applied the default conf, it displays but it does not work.
![cropped_bar](https://user-images.githubusercontent.com/24965409/29752587-4674421e-8b61-11e7-93d7-21a036ee3e31.png)
This is the output of polybar -vv:
```
polybar 3.0.5-26-g2d1e3c2

Features: +alsa +curl +i3 +mpd -network

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm

Build type: RelWithDebInfo
Compiler: /usr/bin/clang++
Compiler flags:  -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors -Wno-error=parentheses-equality
Linker flags: 
```

**Comment by kajzersoze** [comment]
Running fine here on gentoo.

What do you mean by "it displays but it does not work" ?

**Comment by letFunny** [comment]
As you can see in the image the whole bar is messed up. Plus when i click on an icon nothing happens.

**Comment by kajzersoze** [comment]
Ah ok (I missed the image, thought that was just a black line for some reason)
Anyway, can't help you with that problem, I can provide my polybar -vv, maybe it says something.
I see some differences.

```
polybar 3.0.5

Features: +alsa -curl +i3 -mpd +network

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm

Build type: Release
Compiler: /usr/bin/x86_64-pc-linux-gnu-g++
Compiler flags: -march=native -O2 -pipe -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1 -Wl,--as-needed
```
