### ISSUE TITLE
Relative file paths, or environment variable interpolation in absolute paths

### ISSUE THREAD

**Issue by OJFord** [jaagr/polybar#719]
In providing, for example, the token for `internal/github`, it would be really helpful to be able to do something like:
```ini
    token = ${file:.githubtoken}  ; relative to config file
```
or like:
```ini
    token = ${file:$XDG_CONFIG_HOME/polybar/.githubtoken}
```

Not even `~` is expanded, so at present I've had to hard-code both my home directory and XDG config directory, so it's not at all portable.

(The reason I'm not using `${env:...}` is that I'd then have to set the environment variable before i3 launches, which isn't really where I want it.)

**Comment by Mange** [comment]
Related (but not the same): #603
