### ISSUE TITLE
there's problem here?

### ISSUE THREAD

**Issue by tjw0lf** [jaagr/polybar#722]
I have asked 3 people for help and got help they all use polybar and i installed all the fonts required. But i'm still getting these. And its not showing up right at all. Just these. Please somebody help me.

warn: Dropping unmatched character ─ (U+2500)
warn: Dropping unmatched character ➤ (U+27a4)

here's the config

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;                  Icon Collection                    ;;;;;;;
;;;;;;     ♟ ♞ ♝ ♜ ♛ ♚                  ;;;;;;;
;;;;;;       ─ │                     ;;;;;;;
;;;;;;                           ;;;;;;;
;;;;;;                            ;;;;;;;
;;;;;;                     ↵      ;;;;;;;
;;;;;;        ⚡✓ ✘  🌞                ;;;;;;;
;;;;;;            ➤ ─              ;;;;;;;
;;;;;;      🔥 👌                ;;;;;;;
;;;;;;             ○ ●              ;;;;;;;
;;;;;;      
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;         Fonts you may want                       ;;;;;;;;
;;;;;;;;      --- ttf-font-awesome                        ;;;;;;;;
;;;;;;;;      --- ttf-material-icons                      ;;;;;;;;
;;;;;;;;      --- ttf-fira-code                           ;;;;;;;;
;;;;;;;;      --- nerd-fonts-complete                     ;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;             Colours
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[colors]
background = #111111
foreground = #D1D1D1
white      = #D1D1D1
yellow     = #ffcb6b
urgent     = #B33232
blue       = #4E88CF
lightblue  = #5DD5FF
darkblue   = #4D66C3
f-alt      = #111111
b-alt      = #111111
arc        = #484852
dupe       = #111111
dark       = #000000

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;              Bars
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[settings]
throttle-output = 5
throttle-output-for = 10
throttle-input-for = 30
compositing-background = over
compositing-foreground = source
compositing-overline = over
compositing-underline = over
compositing-border = over

[bar/bar1]
monitor =
width = 100%
height = 24
offset-x = 0
offset-y = 0
fixed-center = true
border-bottom-size = 0
border-bottom-color = ${colors.background}
border-top-size = 0
border-top-color = ${colors.background}
background = ${colors.background}
foreground = ${colors.foreground}
font-0 = Ubuntu Nerd Font:size=10:antialias=false;2
font-1 = FontAwesome:pixelsize=12:antialias=false;2
font-2 = MaterialIcons:size=10:antialias=false;2
font-3 = Fira Sans:size=12:weight=regular;2
font-4 = Futura:size=7:weight=Light;2
font-6 = Futura:size=10:weight=Light;2
font-7 = Futura:size=10:weight=Light;2

modules-left = workspaces rofi menu skippy
modules-center =
modules-right = volume compton memory cpu temp time

module-margin = 1
padding-right = 0
padding-left = 0
bottom = false
underline-size = 2
tray-position = center
tray-padding = 10
tray-background = ${colors.background}
tray-offset-x = 5%
tray-offset-y = 0

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;              Modules
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/rofi]
type = custom/script
exec = echo " "
click-left = rofi-apps
label-foreground = ${colors.foreground}
label-background = ${colors.b-alt}

[module/skippy]
type = custom/script
exec = echo "  "
click-left = skippy-xd --toggle-window-picker
label-foreground = ${colors.foreground}
label-background = ${colors.b-alt}

[module/temp]
type = internal/temperature
thermal-zone = 0
warn-temp = 70
format = <label>
format-padding = 0
label-foreground = ${colors.foreground}
label-background = ${colors.b-alt}
label-warn-foreground = ${colors.urgent}
label = "   %temperature% "
label-warn = "   %temperature% "

[module/eth]
type = internal/network
interface = eno1
interval = 1
label-connected = "  "
label-connected-foreground = ${colors.foreground}
label-connected-background = ${colors.b-alt}
label-disconnected = "  "
label-disconnected-foreground = ${colors.foreground}
label-disconnected-background = ${colors.b-alt}

[module/mem]
type = internal/memory
format = <label>
format-padding = 1
format-background = ${colors.b-alt}
format-foreground = ${colors.foreground}
label =  %percentage_used%%
bar-used-width = 12
bar-used-indicator = 
bar-used-indicator-foreground = ${colors.foreground}
bar-used-fill = 
bar-used-fill-foreground = ${colors.foreground}
bar-used-empty = 
bar-used-empty-foreground = ${colors.dark}

[module/memory]
type = internal/memory
interval = 3
format = <label>
format-prefix = "  "
format-prefix-foreground = ${colors.foreground}
label = %{A1:termite --geometry=400x300 --exec=htop &:}%percentage_used%%%{A}

[module/cpu]
type = internal/cpu
interval = 1
format-prefix = "  "
format-prefix-foreground = ${colors.foreground}
label = %{A1:termite --geometry=400x300 --exec=htop &:}%percentage%%%{A}

[module/coreuse]
type = internal/cpu
interval = 1
format = <label>
format-background = ${colors.b-alt}
format-prefix = ""
format-prefix-padding = 1
format-prefix-foreground = ${colors.foreground}
label = %percentage%%
ramp-coreload-0 = %{F#81817F}▂%{F-}
ramp-coreload-1 = %{F#81817F}▃%{F-}
ramp-coreload-2 = %{F#D1D1D0}▄%{F-}
ramp-coreload-3 = %{F#D1D1D0}▅%{F-}
ramp-coreload-4 = %{F#D1D1D0}▆%{F-}
ramp-coreload-5 = %{F#FFFFFF}▇%{F-}
ramp-coreload-6 = %{F#FFFFFF}█%{F-}

[module/time]
type = internal/date
interval = 5
label-foreground = ${colors.foreground}
date-alt = " %Y-%m-%d"
time = "%H:%M "
time-alt = "%H:%M:%S "
format-prefix = " "
format-prefix-foreground = ${colors.foreground}
label = %date% %time%

[module/music]
type                  = internal/mpd
label-song            = %artist% - %title%
label-song-maxlen     = 65
format-online = <icon-prev><icon-stop><toggle><icon-next><icon-random><label-song><bar-progress>
label-song-foreground = ${colors.foreground}
format-background = ${colors.b-alt}
label-song-background = ${colors.b-alt}
icon-pause-background = ${colors.b-alt}
icon-play-background  = ${colors.b-alt}
icon-stop-background = ${colors.b-alt}
icon-prev-background = ${colors.b-alt}
icon-next-background = ${colors.b-alt}
icon-random-background = ${colors.b-alt}
icon-pause-foreground = ${self.label-song-foreground}
icon-stop-foreground = ${self.label-song-foreground}
icon-play-foreground  = ${self.label-song-foreground}
label-song-padding = 1
icon-prev  = " "
icon-stop  = " "
icon-pause = " ─ "
icon-play  = "  "
icon-next  = ""
icon-random = "  "
toggle-off-foreground = ${colors.foreground}
toggle-on-foreground  = ${colors.dark}
bar-progress-width = 20
bar-progress-indicator = 
bar-progress-fill = 
bar-progress-empty = 
bar-progress-empty-foreground = ${colors.dark}
bar-progress-empty-background = ${colors.b-alt}
bar-progress-fill-foreground = ${colors.foreground}
bar-progress-fill-background = ${colors.b-alt}
bar-progress-indicator-foreground = ${colors.foreground}
bar-progress-indicator-background = ${colors.b-alt}

[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /
label-mounted =  %mountpoint%:%percentage_used%%
label-mounted-foreground = ${colors.blue}
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.blue}

[module/volume]
type = internal/volume
master-mixer = Master
format-volume = <label-volume><bar-volume>
label-volume = "  "
label-volume-foreground = ${colors.foreground}
label-volume-background = ${colors.b-alt}
format-muted-prefix = "  "
format-muted-foreground = ${colors.foreground}
format-muted-background = ${colors.b-alt}
label-muted = sound muted
bar-volume-width = 15
bar-volume-foreground-0 = ${colors.foreground}
bar-volume-gradient = true
bar-volume-indicator = "➤"
bar-volume-indicator-foreground = ${colors.blue}
bar-volume-indicator-backround = ${colors.b-alt}
bar-volume-fill-background = ${colors.b-alt}
bar-volume-fill-foreground = ${colors.blue}
bar-volume-fill = "─"
bar-volume-empty = "─"
bar-volume-empty-foreground = ${colors.foreground}
bar-volume-empty-background = ${colors.b-alt}

[module/pkg]
type = custom/script
label-foreground = ${colors.foreground}
label-background = ${colors.b-alt}
exec = ~/.config/polybar/scripts/pkg.sh
click-left = ~/.config/polybar/scripts/update.sh
click-right = ~/.config/polybar/scripts/aur-update.sh
label-padding = 0
interval = 60

[module/compton]
type = custom/script
label-background = ${colors.b-alt}
exec = ~/.config/polybar/scripts/compton.sh
click-left = ~/.config/polybar/scripts/compton-toggle.sh
click-right = ~/.config/polybar/scripts/compton-toggle.sh
interval = 2
label-padding = 1

[module/trash]
interval = 1
type = custom/script
exec = ~/.config/polybar/scripts/trash
format-prefix = "  "
format-prefix-foreground = ${colors.foreground}
format-background = ${colors.b-alt}
click-right = rm -rf ~/.local/share/Trash/files/*
click-left = exo-open --launch FileManager ~/.local/share/Trash/files

[module/menu]
type = custom/menu
format-spacing = 1
format-background = ${colors.b-alt}
label-open = "   "
label-open-foreground = ${colors.foreground}
label-open-background = ${colors.b-alt}
label-close = "   "
label-close-foreground = ${colors.urgent}
label-separator = "│"
label-separator-foreground = ${colors.background}
# Top level
menu-0-0 = "  "
menu-0-0-exec = menu-open-1
menu-0-1 = "  "
menu-0-1-exec = menu-open-2
menu-0-2 = "   "
menu-0-2-exec = menu-open-3
# 1
menu-1-0 = "  "
menu-1-0-exec = exo-open --launch WebBrowser
menu-1-1 = "  "
menu-1-1-exec = exo-open --launch TerminalEmulator
menu-1-2 = "  "
menu-1-2-exec = exo-open --launch FileManager
menu-1-3 = "   "
menu-1-3-exec = geany &
# 2
menu-2-0 = "  "
menu-2-0-exec = deadbeef &
menu-2-1 = "  "
menu-2-1-exec = termite --geometry=600x500 --exec=pacli &
menu-2-2 = "  "
menu-2-2-exec = xfce4-appearance-settings &
menu-2-3 = "   "
menu-2-3-exec = scrot 'ArchLabs_%Y-%m-%d-%S_$wx$h.png' -e 'mv $f $$(xdg-user-dir PICTURES) ; gpicview $$(xdg-user-dir PICTURES)/$f' &
# 3
menu-3-0 = "  "
menu-3-0-exec = slimlock
menu-3-1 = "  "
menu-3-1-exec = openbox --exit
menu-3-2 = "  "
menu-3-2-exec = systemctl reboot
menu-3-3 = "   "
menu-3-3-exec = systemctl poweroff

[module/title]
type = custom/script
interval = 1
label = %output%
label-maxlen = 65
exec = echo "$(xtitle)"
format = <label>
format-background = ${colors.b-alt}
format-prefix = "  "
format-prefix-foreground = ${colors.foreground}
format-padding = 3

[module/workspaces]
type = internal/xworkspaces
enable-click = true
enable-scroll = true
format-padding = 1
Additional formatting
icon-0 = 1;
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;
icon-4 = 5;
icon-5 = 6;
icon-6 = 7;
icon-7 = 8;
icon-8 = 9;
icon-9 = 10;
;icon-default = 

format = <label-state>
label-monitor = %name%

label-active = " %icon% %name% "
label-active-foreground = ${colors.blue}
label-active-background = ${colors.background}
label-active-underline = ${colors.blue}

label-occupied = " %icon% %name% "
label-occupied-underline = ${colors.blue}
label-occupied-background = ${colors.background}
label-occupied-foreground = ${colors.foreground}

label-urgent = " %icon% %name% "
label-urgent-foreground = ${colors.urgent}
label-urgent-background = ${colors.background}
label-urgent-underline = ${colors.urgent}

label-empty = " %icon% %name% "
label-empty-foreground = ${colors.foreground}

**Comment by NBonaparte** [comment]
Which font(s) are the unmatched characters supposed to be from?

Alternatively, you could also find replacements for them from the fonts that you have already in the config.

**Comment by tjw0lf** [comment]
i guess from these. 
font-0 = Ubuntu Nerd Font:size=10:antialias=false;2
font-1 = FontAwesome:pixelsize=12:antialias=false;2
font-2 = MaterialIcons:size=10:antialias=false;2
font-3 = Fira Sans:size=12:weight=regular;2

But idk. i have all the font installed so how can i figure this out.

**Comment by NBonaparte** [comment]
Try installing `gucharmap`, switching to each font (top left drop down menu), and search (Ctrl-F) for each character. Then hold down right click and see which font it shows. If none of them show the original font, then you need to add that specific font to your config.

**Comment by patrick96** [comment]
Also check, if all the fonts are properly loaded by running polybar with `-l info`

**Comment by johnabs** [comment]
Hey guys, I'm also having some trouble here, even after adding siji to the config etc. I know that in its place polybar is loading DejaVu Sans, even though I'm specificed siji in the setup, and can see all the dropped characters in my terminal properly (so the font is definitely installed). Could I get some help? I'm still learning at all of this :/

**Comment by patrick96** [comment]
On some systems "siji" is called "Wuncon Siji".
Use `fc-list | grep siji` to find the name on your system

**Comment by johnabs** [comment]
That is actually what fixed my issue. Turns out I mis-spelled Wuncon...But one more question (assuming you don't mind me asking in this thread. if you do, I'll delete it), I can readily see my dropbox applet, but not my nm-applet, any thoughts on this one? Maybe I need more padding on the tray? I'm not sure.
