### ISSUE TITLE
Polybar dropping unmatched characters

### ISSUE THREAD

**Issue by leggettc13** [jaagr/polybar#726]
Polybar keeps dropping unmatched characters while it runs. I have run ```polybar -l info example``` and it shows that the fonts I have specified are loading properly. I am currently using a slightly modified version of the example configuration, all I did was remove some modules that I wasn't using. I have tried adding font awesome to the configuration file, but that hasn't worked either.

font portion of config file
```

font-0 = fixed:pixelsize=10;1
font-1 = unifont:fontformat=truetype:size=8:antialias=false;0
font-2 = siji:pixelsize=10;1
font-3 = FontAwesome:pixelsize=13

```

I am running Arch Linux with i3-gaps Window Manager
Does anyone have a fix?

**Comment by NBonaparte** [comment]
Did you try using gucharmap?

**Comment by patrick96** [comment]
Are you sure that all fonts are loaded properly? On arch `siji` has to be specified as `Wuncon Siji`. Can you post the output of `polybar -l info example`

**Comment by leggettc13** [comment]
It was the siji font. I thought it was loading properly but I think it was loading DejaVu instead. Replacing it with WunconSiji fixed it. Thanks.
