### ISSUE TITLE
Can't use environment variables from .bashrc

### ISSUE THREAD

**Issue by kofkof01** [jaagr/polybar#728]
I can't use environment variables from my `.bashrc` file. As a test I'm trying to display one in the date module:

```
$ grep MONITOR_RIGHT ~/.bashrc
export MONITOR_RIGHT="HDMI-2"
$ echo $MONITOR_RIGHT
HDMI-2
$ grep MONITOR_RIGHT ~/.config/polybar/config 
date = ${env:MONITOR_RIGHT:fallback}
```
Only the fallback displays.

If I ask for env vars not declared in `.bashrc`, it works, e.g. `${env:USER:fallback}` displays my username.

Installed version: 3.0.5 on Debian Buster from GetDeb zesty repository

**Comment by patrick96** [comment]
How do you start polybar? If you start it in the same shell where you just verified that `$MONITOR_RIGHT` has the right value, does it still only display the fallback?

**Comment by kofkof01** [comment]
> How do you start polybar?

With the following line in i3's config file:

    exec_always --no-startup-id "killall polybar; polybar -r default"

> If you start it in the same shell where you just verified that $MONITOR_RIGHT has the right value, does it still only display the fallback?

Nope, the env var displays correctly. It looks like my problem has more to do with i3 than polybar, then... Sorry about that, but thanks anyway for your help, Patrick.
