### ISSUE TITLE
Weather error line 15

### ISSUE THREAD

**Issue by picarda** [jaagr/polybar#730]
This is line 15:
print("%s, %i °%s" % (info, temp, unit_key))

I'm missing something here?

Thanks

**Comment by NBonaparte** [comment]
Do you get an error from running it? I'm unsure as to what the question is here, sorry.

**Comment by picarda** [comment]
Yes I do have an error when I run it...
It show the path of the weather script then add the number 15.

**Comment by patrick96** [comment]
Could you give us a little more information. What is the exact error? I'm assuming you are using the user contributed weather module, so can you give us the output of that script if you run it inside a terminal and not polybar.

**Comment by natebwangsut** [comment]
I think this issue has been fixed on wiki.

I believe what caused the error is that if the returned HTTP request code is not OK,  
then something else might be returned along the line.

See also: [comparison of `b74908` and the previous one](https://github.com/jaagr/polybar/wiki/User-contributed-modules/_compare/74e1db93f4173b0a0706998d701c85d6dc5a609b...b74908f944782f1a9f43aa8a7480e325e6cfb763).

**Comment by patrick96** [comment]
@natebwangsut The code on the wiki has been changed but didn't yet fix the issue, it just spits out another message now if the HTTP status code is not 200. I have now changed it to output an error message if the request fails.
Closing this.

**Comment by natebwangsut** [comment]
@patrick96 That just fixes the error if the code is not 200.
I guess it's safe to assume that the data would be in the expected format.

You can also do this
```python
try:
    # HTTP CODE = OK
    if REQ.status_code == 200:
        CURRENT = REQ.json()["weather"][0]["description"].capitalize()
        TEMP = int(float(REQ.json()["main"]["temp"]))
        print("{}, {} °{}".format(CURRENT, TEMP, UNIT_KEY))
    else:
        print("Error: BAD HTTP STATUS CODE " + str(REQ.status_code))
except (ValueError, IOError):
    print("Error: Unable print the data")
```

Anyways, good job!

**Comment by patrick96** [comment]
Yes we can do that too. Feel free to add this to the wiki page as well. Thanks!
