### ISSUE TITLE
Modules not displaying correctly or at all

### ISSUE THREAD

**Issue by Alkeryn** [jaagr/polybar#731]
So for exemple mpd buttons are missing or powermenu don't show 
here is a screen
![image](https://user-images.githubusercontent.com/11599075/30148769-2d8bbbfa-93a5-11e7-949f-2c7569ca5794.png)
I'm running arch linux 
and my WM is bspwm

**Comment by Alkeryn** [comment]
also here is my config file
;=====================================================
;						     |
;   To learn more about how to configure Polybar     |
;   go to https://github.com/jaagr/polybar	     |
;						     |
;   The README contains alot of information	     |
;						     |
;=====================================================
[bar/bar]
#bottom = false

tray-transparent = true 
;monitor = ${env:MONITOR:HDMI-1}

;override-redirect = true
wm-restack = bspwm

width = 100%
height = 27
radius = 0.0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2 2 
line-color = #f00
;border-size = 0 
;border-color = #ccff0000

padding-left = 0
padding-right = 0

module-margin-left = 1
module-margin-right = 2

font-0 = fixed:pixelsize=10;1
font-1 = unifont:fontformat=truetype:size=8:antialias=false;0
font-2 = siji:pixelsize=10;1

modules-left = bspwm 
modules-center = xwindow
modules-right = filesystem mpd volume xkeyboard memory temperature cpu powermenu date

tray-position = right
tray-padding = 5
tray-background = #ccffffff

[colors]
;background = ${xrdb:color0:#222}
background = #70100000
background-alt = #444
;foreground = ${xrdb:color7:#222}
foreground = #dfdfdf
foreground-alt = #f55
primary = #00ffff
secondary = #e60053
alert = #bd2c40

[modules/xmenu]
menu-0 = item 1;command
menu-0-0 = sub-item 1.1;command
menu-0-1 = sub-item 1.2;command
menu-0-2 = sub-item 1.3;command
menu-1 = item 2;command
menu-1-0 = sub-item 2.1;command
menu-1-1 = sub-item 2.2;command

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-prefix-underline = ${colors.secondary}

label-layout = %layout%
label-layout-underline = ${colors.secondary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.secondary}

[module/filesystem]
type = internal/fs
interval = 30

mount-0 = /home

label-mounted = %{F#0a81f5}%mountpoint%%{F-}: %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.foreground-alt}

[module/bspwm]
type = internal/bspwm

label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2

label-occupied = %index%
label-occupied-padding = 2

label-urgent = %index%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %index%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 2
bspwm.label-urgent-padding}

[module/mpd]
type = internal/mpd
interval = 2
format-online = <label-song>  <icon-prev> <icon-stop> <toggle> <icon-next>
label-song = 𝄞 %artist% - %title%
icon-play = ⏵
icon-pause = ⏸
icon-stop = ⏹
icon-prev = ⏮
icon-next = ⏭
icon-seekb = ⏪
icon-seekf = ⏩
icon-random = 🔀
icon-repeat = 🔁
icon-repeatone = 🔂
label-song-maxlen = 25
label-song-ellipsis = true

[module/cpu]
type = internal/cpu
interval = 5
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #f90000
label = %percentage%%

[module/memory]
type = internal/memory
interval = 5
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #4bffdc
label = %percentage_used%%

[module/wlan]
type = internal/network
interface = net1
interval = 3.0

format-connected = <ramp-signal> <label-connected>
format-connected-underline = #9f78e1
label-connected = %essid%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
ramp-signal-foreground = ${colors.foreground-alt}

[module/eth]
type = internal/network
interface = net0
interval = 3.0

format-connected-underline = #55aa55
format-connected-prefix = " "
format-connected-prefix-foreground = ${colors.foreground-alt}
label-connected = %local_ip%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

[module/date]
type = internal/date
interval = 1

date = " %Y-%m-%d"
date-alt = " %Y-%m-%d"

time = %H:%M:%S
time-alt = %H:%M:%S

format-prefix = 
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #00ffff

label = %date% %time%

[module/volume]
type = internal/volume
format-volume = <label-volume> <bar-volume>
label-volume = VOL
label-volume-foreground = ${root.foreground}

format-muted-prefix = " "
format-muted-foreground = ${colors.foreground-alt}
label-muted = sound muted

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60
interval = 15
format = <ramp> <label>
format-underline = #00ffff
format-warn = <ramp> <label-warn>
format-warn-underline = ${self.format-underline}

label = %temperature%
label-warn = %temperature%
label-warn-foreground = ${colors.secondary}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground-alt}

[module/powermenu]
type = custom/menu

format-spacing = 1

label-open = 
label-open-foreground = ${colors.secondary}
label-close =  cancel
label-close-foreground = ${colors.secondary}
label-separator = |
label-separator-foreground = ${colors.foreground-alt}

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = sudo reboot

menu-2-0 = power off
menu-2-0-exec = sudo poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
compositing-foreground = source
;compositing-border = over

[global/wm]
margin-top = 0
margin-bottom = 0

; vim:ft=dosini

**Comment by Alkeryn** [comment]
And maybe if that help i have a dual screen and polybar is on my left screen
main screen is the right one

**Comment by NBonaparte** [comment]
What is the output of polybar when you run it?

**Comment by Alkeryn** [comment]
![image](https://user-images.githubusercontent.com/11599075/30152634-05cd01f0-93b4-11e7-8083-d63babe273f2.png)
Also it spam my logs so when i do a journalctl -n it is spamed by polybar dropping unmatched character

**Comment by patrick96** [comment]
The mpd modules isn't showing because your `format-online` is empty.
I think the powermenu is actually displayed but because the icon for `label-open` is dropped, you only see the spacing between the `cpu` and `date` module. You'll need to fix your fonts first, check the [Font Wiki](https://github.com/jaagr/polybar/wiki/Fonts#freetype-fonts) for instructions on how to check which fonts actually got loaded successfully

**Comment by Alkeryn** [comment]
Weird it might be a paste error because it is in my config file 
![image](https://user-images.githubusercontent.com/11599075/30201315-9da1abae-947a-11e7-8b05-291511dd0575.png)

**Comment by Alkeryn** [comment]
And the module is still not showing 
though that's weird because it didn't paste while it is in the file

**Comment by Alkeryn** [comment]
Nah it is githube that isn't showing it because my format-online isn't empty
but when i post it on github it disapear, weird
maybe an encoding issue

**Comment by Alkeryn** [comment]
So not the issue isn't because format-online isn't there because it is
github is erasing that line for some reason though

**Comment by Alkeryn** [comment]
useless to paste since github erase some parts :/

**Comment by patrick96** [comment]
Maybe you can paste inside code tags, just add \`\`\` one line before and after the paste

**Comment by Alkeryn** [comment]
```
;=====================================================
;						     |
;   To learn more about how to configure Polybar     |
;   go to https://github.com/jaagr/polybar	     |
;						     |
;   The README contains alot of information	     |
;						     |
;=====================================================
[bar/bar]
#bottom = false

tray-transparent = true 
;monitor = ${env:MONITOR:HDMI-1}

;override-redirect = true
wm-restack = bspwm

width = 100%
height = 27
radius = 0.0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2 2 
line-color = #f00
;border-size = 0 
;border-color = #ccff0000

padding-left = 0<
padding-right = 0

module-margin-left = 1
module-margin-right = 2

font-0 = fixed:pixelsize=10;1
font-1 = unifont:fontformat=truetype:size=8:antialias=false;0
font-2 = WunconSiji:pixelsize=10;1
font-3 = FontAwesome:pixelsize=14;0


modules-left = bspwm 
modules-center = xwindow
modules-right = filesystem mpd volume xkeyboard memory temperature cpu powermenu date

tray-position = right
tray-padding = 5
tray-background = #ccffffff

[colors]
;background = ${xrdb:color0:#222}
background = #70100000
background-alt = #444
;foreground = ${xrdb:color7:#222}
foreground = #dfdfdf
foreground-alt = #f55
primary = #00ffff
secondary = #e60053
alert = #bd2c40

[modules/xmenu]
menu-0 = item 1;command
menu-0-0 = sub-item 1.1;command
menu-0-1 = sub-item 1.2;command
menu-0-2 = sub-item 1.3;command
menu-1 = item 2;command
menu-1-0 = sub-item 2.1;command
menu-1-1 = sub-item 2.2;command

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-prefix-underline = ${colors.secondary}

label-layout = %layout%
label-layout-underline = ${colors.secondary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.secondary}

[module/filesystem]
type = internal/fs
interval = 30

mount-0 = /home

label-mounted = %{F#0a81f5}%mountpoint%%{F-}: %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.foreground-alt}

[module/bspwm]
type = internal/bspwm

label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2

label-occupied = %index%
label-occupied-padding = 2

label-urgent = %index%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %index%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 2
bspwm.label-urgent-padding}

[module/mpd]
type = internal/mpd
interval = 2
format-online = <label-song> <icon-prev> <icon-stop> <toggle> <icon-next>
label-song = 𝄞 %artist% - %title%
icon-play = ⏵
icon-pause = ⏸
icon-stop = ⏹
icon-prev = ⏮
icon-next = ⏭
icon-seekb = ⏪
icon-seekf = ⏩
icon-random = 🔀
icon-repeat = 🔁
icon-repeatone = 🔂
label-song-maxlen = 25
label-song-ellipsis = true

[module/cpu]
type = internal/cpu
interval = 5
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #f90000
label = %percentage%%

[module/memory]
type = internal/memory
interval = 5
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #4bffdc
label = %percentage_used%%

[module/wlan]
type = internal/network
interface = net1
interval = 3.0

format-connected = <ramp-signal> <label-connected>
format-connected-underline = #9f78e1
label-connected = %essid%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
ramp-signal-foreground = ${colors.foreground-alt}

[module/eth]
type = internal/network
interface = net0
interval = 3.0

format-connected-underline = #55aa55
format-connected-prefix = " "
format-connected-prefix-foreground = ${colors.foreground-alt}
label-connected = %local_ip%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

[module/date]
type = internal/date
interval = 1

date = " %Y-%m-%d"
date-alt = " %Y-%m-%d"

time = %H:%M:%S
time-alt = %H:%M:%S

format-prefix = 
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #00ffff

label = %date% %time%

[module/volume]
type = internal/volume
format-volume = <label-volume> <bar-volume>
label-volume = VOL
label-volume-foreground = ${root.foreground}

format-muted-prefix = " "
format-muted-foreground = ${colors.foreground-alt}
label-muted = sound muted

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60
interval = 15
format = <ramp> <label>
format-underline = #00ffff
format-warn = <ramp> <label-warn>
format-warn-underline = ${self.format-underline}

label = %temperature%
label-warn = %temperature%
label-warn-foreground = ${colors.secondary}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground-alt}

[module/powermenu]
type = custom/menu

format-spacing = 1

label-open = 
label-open-foreground = ${colors.secondary}
label-close =  cancel
label-close-foreground = ${colors.secondary}
label-separator = |
label-separator-foreground = ${colors.foreground-alt}

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = sudo reboot

menu-2-0 = power off
menu-2-0-exec = sudo poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
compositing-foreground = source
;compositing-border = over

[global/wm]
margin-top = 0
margin-bottom = 0

; vim:ft=dosini
```

**Comment by Alkeryn** [comment]
Yup that work

**Comment by Alkeryn** [comment]
also when running polybar bar -l info 
```
* Loaded font "fixed:pixelsize=10" (name=DejaVu Sans, offset=1, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
* Loaded font "Unifont:fontformat=truetype:size=8:antialias=false" (name=DejaVu Sans, offset=0, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
* Loaded font "WunconSiji:pixelsize=10" (name=Wuncon Siji, offset=1, file=/usr/share/fonts/misc/siji.pcf)
* Loaded font "FontAwesome:pixelsize=14" (name=FontAwesome, offset=0, file=/home/alkeryn/.local/share/fonts/fontawesome-webfont.ttf)
```

**Comment by Alkeryn** [comment]
So i got two font missing
finding siji font fixed a part of the issue
had to rename it WunconSiji
but i think it is just a font issue now

**Comment by patrick96** [comment]
Yeah seems like you just need to find the fonts now.
You can `grep` over `fc-list` to find the name of the fonts in your system

**Comment by Alkeryn** [comment]
Though i don't have any font to replace "fixed" or "unifont"
so i don't really know what to do ^^

**Comment by patrick96** [comment]
You could just install those fonts.

**Comment by Alkeryn** [comment]
Yeah but i don't find them that's the issue xD

**Comment by Alkeryn** [comment]
Well now it work better but mpd module still not showing 
and i still get unmatched font for it 
i don't know what font work with it though :/
![image](https://user-images.githubusercontent.com/11599075/30213078-c2e93652-94a7-11e7-9aa4-701233ca2c82.png)

**Comment by patrick96** [comment]
Your best option probably is to use icons fot the mpd module that are
provided by the fonts you have. You can use gucharmap to find icons for a
specific font, read the Font Wiki page on how to do that.
