### ISSUE TITLE
Wireless module unable to query interface

### ISSUE THREAD

**Issue by daedreth** [jaagr/polybar#732]
Upon launching the bar, the wireless module is not shown at all.

The message I get is `warn: module/wlan: Failed to query interface 'wlp3s0'`.

Here is the output of ifconfig, as you can see the device is there and enabled.
```
enp0s25: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 00:21:cc:b9:ef:8c  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xf2500000-f2520000  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 4  bytes 272 (272.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4  bytes 272 (272.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp3s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.159  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::2541:f931:7866:45c3  prefixlen 64  scopeid 0x20<link>
        ether 60:d8:19:cb:4a:8e  txqueuelen 1000  (Ethernet)
        RX packets 108775  bytes 157656795 (150.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 58038  bytes 5522692 (5.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

The module is configured as such:
```
[module/wlan]
type = internal/network
interface = wlp3s0
interval = 3.0

format-connected = <ramp-signal>
format-connected-underline = #9f78e1
label-connected = %essid%

format-disconnected =

ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
ramp-signal-foreground = ${colors.foreground-alt}
```

Also, wireless_tools are installed and working.

**Comment by patrick96** [comment]
Does this also happen, if you create a module for the ethernet interface?

**Comment by daedreth** [comment]
Just verified that this is not the case, the ethernet interface is queried properly.

**Comment by patrick96** [comment]
This is very strange, the piece of code that actually prints that error message is only called if a certain function fails and that function always queries all interfaces
What version of polybar are you using?

**Comment by daedreth** [comment]
```
polybat --version

polybar 3.0.5
Features: +alsa -curl -i3 -mpd +network
```

**Comment by patrick96** [comment]
This is not making it easier, you should still get the error for both or neither module.
Can you run the following program for me and post the output.
`main.c`:
```c
#include <stdio.h>
#include <sys/types.h>
#include <errno.h>
#include <string.h>
#include <ifaddrs.h>

void print(struct ifaddrs* ifaddr) {
    printf("ifa_name : %s\n", ifaddr->ifa_name);
    printf("ifa_flags: %d\n", ifaddr->ifa_flags);
    printf("ifa_addr : %d\n", ifaddr->ifa_addr->sa_family);
    printf("sa_data  : %s\n", ifaddr->ifa_addr->sa_data);
    printf("ifa_data : %X\n", ifaddr->ifa_data);
    puts("---");
}

int main(int argc, char *argv[])
{
    struct ifaddrs* ifaddr;
    int res = getifaddrs(&ifaddr);
    printf("%d\n", res);

    if(res == -1) {
        printf("Error: %s\n", strerror(errno));
        return -1;
    }

    for (struct ifaddrs* ifa = ifaddr; ifa != NULL; ifa = ifa->ifa_next) {
        print(ifa);
    }
    return 0;
}
```
```bash
gcc -g -o main main.c
./main
```

**Comment by daedreth** [comment]
```
0
ifa_name : lo
ifa_flags: 65609
ifa_addr : 17
sa_data  : 
ifa_data : 603DA8
---
ifa_name : enp0s25
ifa_flags: 4099
ifa_addr : 17
sa_data  : 
ifa_data : 603E08
---
ifa_name : tunl0
ifa_flags: 128
ifa_addr : 17
sa_data  : 
ifa_data : 603E68
---
ifa_name : wlp3s0
ifa_flags: 69699
ifa_addr : 17
sa_data  : 
ifa_data : 603EC8
---
ifa_name : lo
ifa_flags: 65609
ifa_addr : 2
sa_data  : 
ifa_data : 0
---
ifa_name : wlp3s0
ifa_flags: 69699
ifa_addr : 2
sa_data  : 
ifa_data : 0
---
ifa_name : wlp3s0
ifa_flags: 69699
ifa_addr : 2
sa_data  : 
ifa_data : 0
---
ifa_name : lo
ifa_flags: 65609
ifa_addr : 10
sa_data  : 
ifa_data : 0
---
ifa_name : wlp3s0
ifa_flags: 69699
ifa_addr : 10
sa_data  : 
ifa_data : 0
---
```

There you go!

**Comment by patrick96** [comment]
@NBonaparte I think I need your help here, my cpp isn't that good:
Polybar only warns about `Failed to query interface` in [`network.cpp#85`](https://github.com/jaagr/polybar/blob/3.0.5/src/modules/network.cpp#L85) and only if [`network::query`](https://github.com/jaagr/polybar/blob/3.0.5/src/adapters/net.cpp#L60) returns false, which it only does in [`net.cpp#63`](https://github.com/jaagr/polybar/blob/3.0.5/src/adapters/net.cpp#L63).
The `getifaddrs` call isn't dependent on the interface, so it's strange that it only fails for the wireless interface, and the output of the program I posted, shows that `getifaddrs` works fine. Is there any other way that `query` can return false or am I missing something else?

**Comment by NBonaparte** [comment]
The function called is actually [`wireless_network::query`](https://github.com/jaagr/polybar/blob/3.0.5/src/adapters/net.cpp#L268) for wireless networks, and [`wired_network::query`](https://github.com/jaagr/polybar/blob/3.0.5/src/adapters/net.cpp#L206) for wired networks. This would mean that the function fails at [`net.cpp#273`](https://github.com/jaagr/polybar/blob/3.0.5/src/adapters/net.cpp#L273) or at [`net.cpp#280`](https://github.com/jaagr/polybar/blob/3.0.5/src/adapters/net.cpp#L280).

**Comment by daedreth** [comment]
@NBonaparte I may have to paddle back, this may not be an issue with polybar.

iwconfig gives me `no wireless extensions.` next to my wireless interface.

**Comment by NBonaparte** [comment]
That must mean that your wireless driver is not supported by `wireless-tools`. In [this comment](https://github.com/jaagr/polybar/issues/402#issuecomment-277996759) jaagr said he was doing a rewrite of the network backend to support iw/nl80211, which is supposed to be the replacement for `wireless-tools` and should support all drivers. Currently, the only solution is to wait until those changes are merged, and use a workaround for now.

You might be able to write a script that does the equivalent of the module by parsing sysfs files in `/sys/class/net/wlp3s0`.

**Comment by pgeorgiev98** [comment]
I know this is and old issue, but I had the exact same problem and it turned out that I compiled my kernel without `CONFIG_CFG80211_WEXT` (Wireless extensions compatibility). After enabling it both `polybar` and `iwconfig` worked perfectly. You can generally check if your kernel is compiled with wireless extensions compatibility enabled by running `grep CONFIG_CFG80211_WEXT /boot/config-your-kernel-verision`. I Hope this helps

**Comment by A** [comment]
@pgeorgiev98 man, thank you for this, after recompile kernel with this option, all works for me

**Comment by patrick96** [comment]
This doesn't seem to be a polybar issue anymore. I will close this.
