### ISSUE TITLE
Battery doesn't update

### ISSUE THREAD

**Issue by quentinGeeraert** [jaagr/polybar#734]
Hello, I use Polybar but my battery doesn't update automatically, however if I refill polybar my battery is update : 

my config : 
````
[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1
full-at = 98

format-charging = <animation-charging> <label-charging>
format-charging-underline = #ffb52a

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-underline = ${self.format-charging-underline}

format-full-prefix = " "
format-full-prefix-foreground = ${colors.foreground-alt}
format-full-underline = ${self.format-charging-underline}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-foreground = ${colors.foreground-alt}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-foreground = ${colors.foreground-alt}
animation-charging-framerate = 1
poll-interval = 0

label-charging = Charging : %percentage%%
label-discharging = Discharging : %percentage%%
label-full = Fully charged
````

I have the polybar 2.5.2 version with Ubuntu 17.04

**Comment by NBonaparte** [comment]
Could you use a more up-to-date version and test again?

**Comment by quentinGeeraert** [comment]
I use the 2.5.2 version and I test to up my version but my version remains at 2.5.2. From what I see, it seems to be resolved, can it be a bad installation the first time?

**Comment by patrick96** [comment]
It could have been a temporary glitch but since it happened in an older version, we'll not look into it.
You can get a newer version for polybar [here](https://repology.org/metapackage/polybar/versions)
