### ISSUE TITLE
Dual monitor setup not displaying bar despite proper output.

### ISSUE THREAD

**Issue by johnabs** [jaagr/polybar#738]
Hey, I hope you're not too busy at the moment, as I love your work and am really looking forward to getting it up and running on my own machine; however, I've hit a slight snag. I'm attempting to run two copies of the bar, one on each monitor, but I have been unable to do so. I can get a bar to display on one. Monitor at a time, but if I try to initialize 2, only one shows up, prioritizing my left (I believe not main monitor, named HDMI - 2). I was using the example config file provided, but I will like it, along with the outputs of polybar -m. Thank you so much for your time, and if you need anymore information, please let me know and I'll get back to you ASAP. 

Sincerely,

JohnABS

polybar -m output: 
HDMI-3: 1920x1080+1920+0
HDMI-2: 1920x1080_0+0

[config file](https://github.com/jaagr/polybar/files/1290451/config.txt)

**Comment by patrick96** [comment]
What command do you use to start the bars? Can you post the output of those commands

**Comment by johnabs** [comment]
the only command I've been running to test initially was "polybar example", the output is a crapload of unmatched characters (speaking of which, what font is included in this example config so I can install it? xD) and a seemingly well-configured bar., but only one of them.

**Comment by patrick96** [comment]
Well you definitely need to run both `polybar example` AND `polybar example2`, if that still doesn't work, please paste the whole output of both commands
The fonts are `xorg-fonts-misc`, `unifont` and `siji`. If you use arch you will need to rename "fixed" to "Misc Fixed" and "siji" to "Wuncon Siji"

**Comment by johnabs** [comment]
That would definitely be my issue (and that fixed it), thank you so much for the help, sorry I didn't realize that sooner q.q
