### ISSUE TITLE
Polybar on login: it won't appear until I refresh i3.

### ISSUE THREAD

**Issue by johnabs** [jaagr/polybar#740]
I've noticed when I start my machine polybar won't appear until I do a manual refresh of i3-gaps after I log in. I am unsure as to why this is the case. I used the script provided in the wiki, along with the command recommended in the i3gaps config file. I even tried adding the script to my .xinitrc to run after i3 was finished loading. Any ideas? I'll include a copy of the script and my gaps config, as well as the polybar config. Any help would be greatly appreciated.

Sincerely,

JohnABS

P.S. Sorry I'm posting on rather trivial topics, I'm kinda new to all of this, and to Github in general. Thank you for your patience.

[i3config](https://github.com/jaagr/polybar/files/1292280/i3config.txt)
[polybarconfig](https://github.com/jaagr/polybar/files/1292279/config.txt)
[poly.sh](https://github.com/jaagr/polybar/files/1292282/poly.txt)

**Comment by philipmvitale** [comment]
Hey! I had the same issue and used this workaround that someone else with the same problem had. Add the following line to .xinitrc, placing it right before exec i3 like so:
```
(sleep 5; ~/scripts/polybar.sh) & 
exec i3
```

You can play around with the sleep length based on how fast your system starts i3. I use the same startup script provided by the wiki. Not sure if this is the best solution but it works!

**Comment by skystrife** [comment]
I have `i3` start the bars for me directly with the following in `~/.config/i3/config`:

```
exec_always --no-startup-id $polybar
```

for an appropriately defined `$polybar` launch script.

**Comment by pauldotknopf** [comment]
I'm seeing this as well.

In order for polybar to see the monitors, I have to delay it's start a little bit.

**~/.config/i3/config**
```
exec_always --no-startup-id "$HOME/.config/i3/startup"
```

**~/.config/i3/startup**
```
#!/usr/bin/env bash
killall polybar
(sleep 2; polybar example -r) &
```
