### ISSUE TITLE
Problems in build - jsoncpp 1.8.3

### ISSUE THREAD

**Issue by ademirtc** [jaagr/polybar#741]
I have problems with a new installation (build from github):

```
@  polybar/build   tags/3.0.5  sudo make install 
[  1%] Built target xpp
[  2%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o
/home/marks/Installers/polybar/lib/i3ipcpp/src/ipc.cpp: In lambda function:
/home/marks/Installers/polybar/lib/i3ipcpp/src/ipc.cpp:25:17: error: ‘Reader’ is deprecated: Use CharReader and CharReaderBuilder instead [-Werror=deprecated-declarations]
   Json::Reader  reader; \
                 ^
/home/marks/Installers/polybar/lib/i3ipcpp/src/ipc.cpp:280:4: note: in expansion of macro ‘IPC_JSON_READ’
    IPC_JSON_READ(root);
    ^~~~~~~~~~~~~
In file included from /usr/include/json/json.h:11:0,
                 from /home/marks/Installers/polybar/lib/i3ipcpp/src/ipc.cpp:6:
/usr/include/json/reader.h:35:83: note: declared here
 P_DEPRECATED("Use CharReader and CharReaderBuilder instead") JSON_API Reader ...{
                                                                       ^~~~~
```
Version of jsoncpp: 
```
✘  @  Installers/polybar  pacman -Si jsoncpp 
Repository      : apps
Name            : jsoncpp
Version         : 1.8.3-1
Description     : A JSON C++ library
Architecture    : x86_64
URL             : https://github.com/open-source-parsers/jsoncpp
```

**Comment by patrick96** [comment]
I'll look into this. Where did you get jsoncpp 1.8.3 from?

**Comment by ademirtc** [comment]
hi, jsoncpp from 

http://kaosx.tk/packages/index.php?act=show&subdir=apps&sortby=date&file=jsoncpp-1.8.3-1-x86_64.pkg.tar.xz

https://github.com/KaOSx/apps/blob/master/jsoncpp/PKGBUILD

**Comment by dinotheextinct** [comment]
I have a very similiar problem with jsoncpp 1.8.2.
``[  2%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o
/home/dino/Downloads/polybar/lib/i3ipcpp/src/ipc.cpp:280:4: error: 'Reader' is deprecated: Use CharReader and CharReaderBuilder instead [-Werror,-Wdeprecated-declarations]
                        IPC_JSON_READ(root);
                        ^
/home/dino/Downloads/polybar/lib/i3ipcpp/src/ipc.cpp:25:9: note: expanded from macro 'IPC_JSON_READ'
                Json::Reader  reader; \
                      ^
/usr/include/json/reader.h:35:83: note: 'Reader' has been explicitly marked deprecated here
class JSONCPP_DEPRECATED("Use CharReader and CharReaderBuilder instead") JSON_API Reader {
                                                                                  ^

**Comment by pierg75** [comment]
I actually have the same problem but funny enough I only get this when trying to build a rpm.
If I manually compile it (using build.sh) it works. If I build it with rpmbuild I get the same error.

**Comment by avindra** [comment]
The problem is the use of `Json::Reader` on this line in `i3ipcpp`:

https://github.com/jaagr/i3ipcpp/blob/727da35ebf9e170b0dfb4db85c6a50836b2ca662/src/ipc.cpp#L25

You can see that this is deprecated upstream:

https://github.com/open-source-parsers/jsoncpp/blob/42a161fc80b32cc63c1a3e7ab1c9ed588a83edaa/include/json/reader.h#L30-L35

SUSE also has problems compiling polybar because it will fail builds that use deprecated items by default.

**Comment by patrick96** [comment]
Thanks for digging into this. I have played around with it a little and got some code that compiles, not sure whether it works as it should though.
Gonna open a PR over at [`jaagr/i3ipcpp`](https://github.com/jaagr/i3ipcpp) shortly, though I don't have write access over there, so I'm not sure how long this will take.

**Comment by szorfein** [comment]
thx you, this patch served me for install polybar on gentoo.

**Comment by patrick96** [comment]
Good to know that it works on other systems.
Are you using the i3 module with polybar?

**Comment by szorfein** [comment]
yes with i3ipcpp, i have enhance an ebuild found on another repo (dr terrible), the [ebuild](https://github.com/szorfein/ninjatools/blob/master/x11-misc/polybar/polybar-3.0.6_pre20171018.ebuild) and [patch](https://github.com/szorfein/ninjatools/blob/master/x11-misc/polybar/files/ipc-cpp.patch)

**Comment by patrick96** [comment]
Seems like jsoncpp 1.8.3 has hit the arch repos. I'll try to do some more testing on my end and merge https://github.com/jaagr/i3ipcpp/pull/4 ASAP.

**Comment by patrick96** [comment]
Before you compile, either update the i3ipcpp submodule to point to the `reader_deprecated` branch in [this](https://github.com/patrick96/i3ipcpp/tree/reader_deprecated) repository or go into the `i3ipcpp` submodule and apply [this](https://github.com/jaagr/i3ipcpp/pull/4.patch) patch.
