### ISSUE TITLE
Filesystem module displaying incorrect values

### ISSUE THREAD

**Issue by drewma2k** [jaagr/polybar#743]
Hello, 

For some reason the filesystem module of polybar is showing that the '/' mount has a total size of 1.97GB and current used space of 851MB. This is with the default config (other than adding tags to display the total and used values). On the other hand, here is the output of df -h for that mountpoint:

`/dev/dm-0       158G  8.9G  142G   6% /`

**Comment by skystrife** [comment]
Does a682d2af91881fa775e265520f7f820cb71dc707 fix things for you?

**Comment by drewma2k** [comment]
No, same issue, and now that more drive space is being used the %used% config option displays 16777216.00 TB.

**Comment by Soulthym** [comment]
Upping this issue since I have a similar problem, the default filesystem module displays 100% all the time while I actually have 
```$ df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       227G  6.4G  209G   3% /```
Note: I am running polybar on a 32 bit system, and installed from the AUR

**Comment by patrick96** [comment]
Just noticed, `16777216.00 TB` converted to bytes is exactly `2^64`. So we likely have some integer underflow/overflow or signed/unsigned weirdness.

**Comment by Soulthym** [comment]
I'm gonna try using du directly and give feedback on this

**Comment by Soulthym** [comment]
Got a clean result using free, then system crashed. It's some other issue but I can't check again until I fix my system
Which command is using polybar to get that value?

**Comment by Soulthym** [comment]
It's totally unrelated, just me messing up playing with my initrd.
I'll try some commands related to these and see if bytes_used and bytes_free should return correct values on this particular system. I really believe it's caused by 32bit-system int underflowing

**Comment by patrick96** [comment]
Maybe the problem is [here](https://github.com/jaagr/polybar/blob/master/include/modules/fs.hpp#L20). On 32-bit those take 8 bytes while the entries from `statvfs` use 4 bytes on a 32-bit machine. Maybe try changing those `unsigned long long` to `unsigned long int`

**Comment by Soulthym** [comment]
I'm gonna do that, although I never really compiled it by hand (using Archlinux 32-bit repos atm, will edit those out while re-compiling)
Results will come in a couple days.
Thanks for your help!

**Comment by patrick96** [comment]
Compiling by hand is not that difficult. Have a look at the `PKGBUILD` for the `polybar-git` package it basically lists all the build steps.

**Comment by Soulthym** [comment]
Alright so this "kinda" worked
I now have a constant 168.42MB displayed, while I know there is at least 13Gb used on my system (given by `df -h`)

**Comment by patrick96** [comment]
@Soulthym is `168.42MB` the figure given by polybar for the used space? What did you change?

**Comment by Soulthym** [comment]
@patrick96
It's the figure given by polybar for used space exactly.
I changed the four `unsigned long long` to `unsigned long int` as you referenced four days ago

**Comment by patrick96** [comment]
Were you able to figure out where polybar does a wrong calculation?

Could you also try to change [this line](https://github.com/jaagr/polybar/blob/master/src/modules/fs.cpp#L101) to

```cpp
 mount->bytes_free = buffer.f_frsize * buffer.f_bfree;
```

and try if it displays the correct values?

**Comment by Soulthym** [comment]
Nope I couldn't figure out what caused this.
Alright imma try this one, it just takes like 6 hours to compile so I'll post the result tomorrow

**Comment by patrick96** [comment]
@Soulthym How many cores do you have on your machine? Instead of `make` try running `make -j$(nproc)`, that will increase the build speed by fully using your CPU. Warning: Your computer will be sloooow during that.

**Comment by Soulthym** [comment]
No hope for this, it's a single core machine, 1Gb RAM. One of the first "netbooks" available with Windows 7 starter... X)
Its already hella slow while doing anything, im gonna switch to something lighter than polybar on this setup when this bug is fixed, I just don't want this bug to stay x)

**Comment by patrick96** [comment]
Oh damn. I appreciate you helping use here :)

**Comment by Soulthym** [comment]
Should I try both modifications at the same time? Or just the second?
Btw I changed it from `%used%` to `%free%`, it displays 2.35Gb, instead for 226Gb (with the first modifications, long to int)

**Comment by Soulthym** [comment]
`df -hT /` returns:
```
Filesystem Type Size   Used   Avail Use%  
/dev/sda1  ext4  227G 203G  203G   6%```

**Comment by patrick96** [comment]
Both at the same time preferably. When you compile multiple times without each time clearing everything it should only compile the changed files, which should be a lot faster, if that works, it would be interesting to see the effects of only the second modification.

Also, can you then report the values for all three tokens (`label-mounted = %total% %free% %used%`)

**Comment by Soulthym** [comment]
Here are all the results:
Mountpoint : /
no modifications:
Total: 2.06Gb
Free: 2.25Gb
Used: 271.52Mb

mod 1:
Unsigned long long => unsigned long int:
https://github.com/jaagr/polybar/blob/master/include/modules/fs.hpp#L20
Total: 2.06Gb
Free: 2.35Gb
Used: 168.98Mb

mod2:
`mount->bytes_free = buffer.f_bsize * buffer.f_bfree; `
to
`mount->bytes_free = buffer.f_frsize * buffer.f_bfree;`
https://github.com/jaagr/polybar/blob/master/src/modules/fs.cpp#L101
Total: 2.06Gb
Free: 2.25Gb
Used: 271.33Mb

mod2+1
Total: 2.06Gb
Free: 2.25Gb
Used: 271.12Mb

NB: I thought this was due to the small screen but since i compiled from source, somehow the desktop "counter" came back? sounds great i thought it was a whole other issue but it seems to be solved :)

**Comment by patrick96** [comment]
You don't need both packages, there were no changes to the filesystem module between `polybar` and `polybar-git`

> `/dev/sda1  ext4 227G   203G   203G    6%`

This output for `free` looks weird, you have as much free space as is used

**Comment by Soulthym** [comment]
I'm gonna have to give up, the machine doesn't start up anymore, probably the hardware broke somehow, I'm suspecting the hard drive given its age.
If you wanna try to fix it, I was using a Manjaro 32 install, quite standard packages.
I believe their repos are based on Archlinux 32bit ones

**Comment by patrick96** [comment]
Oh damn. RIP

I will nevertheless make a PR with the changes I proposed since the calculations we do are actually wrong (it just doesn't give the wrong results on most systems). I think setting up a 32-bit system for this is too much effort.

**Comment by notok** [comment]
Sorry for commenting on closed issue.

I also faced the same problem on 32bit machine.
And after some investigation, I believe this issue is an overflow issue.

Focusing on [this line](https://github.com/jaagr/polybar/blob/master/src/modules/fs.cpp#L100), on 32 bit machines, the types of each variables are as follows.

```
// mount->bytes_total = buffer.f_frsize * buffer.f_blocks;
<8byte(64bit) unsigned> = <4byte(32bit) unsigned> * <4byte(32bit) unsigned>
```

So, right hand member becomes 4byte unsigned value, and it immediately overflows if the calculated product is over 4GiB(`2^32`bytes).
Then, the incorrect value is stored in 8byte unsigned value.


Please check my PR(#1699). I added casting before they're multiplied.
(I'm not so familiar with C++ syntax, please tell me if there's better way to write.)

Tested on Fedora29 i386 and x86_64 machine.
