### ISSUE TITLE
Date module is limited to 63 chars

### ISSUE THREAD

**Issue by Lemmmy** [jaagr/polybar#744]
The string `date = AAAAAAAAAABBBBBBBBBBCCCCCCCCCCDDDDDDDDDDEEEEEEEEEEFFFFFFFFFFGGGGGGGGGGHHHHHHHHHHIIIIIIIIII` renders `AAAAAAAAAABBBBBBBBBBCCCCCCCCCCDDDDDDDDDDEEEEEEEEEEFFFFFFFFFFGGG` - this does not seem to be a limitation of `date`, as running `date +AAAAAAAAAABBBBBBBBBBCCCCCCCCCCDDDDDDDDDDEEEEEEEEEEFFFFFFFFFFGGGGGGGGGGHHHHHHHHHHIIIIIIIIII` outputs the exact input string.

This prevents me from using a date string like `%Y%%{F#5c6370}-%%{F-}%m%%{F#5c6370}-%%{F-}%d %H%%{F#5c6370}:%%{F-}%M%%{F#5c6370}:%%{F-}%S`.

**Comment by Lemmmy** [comment]
Culprit code seems to be at [modules/date.cpp#L45](https://github.com/jaagr/polybar/blob/e3a51b235a73b9da35a0d499d813be541fde15d8/src/modules/date.cpp#L45)

**Comment by patrick96** [comment]
I don't see a sensible way to make `strftime` work with an arbitrary date or time string. The solutions I've found are just increasing the buffer size until `strftime` stops returning zero.
I'll open a PR that just takes the length of the date string, multiplies it by 10, clamps that value between 64 and 1024 and uses it as the length of the buffer.
