### ISSUE TITLE
Highlight a specific keyboard layout

### ISSUE THREAD

**Issue by cryptomaniac512** [jaagr/polybar#747]
Is it possible to implement the highlighting of the current layout with color?
For example red color highlighting if current layout is `ru`.

**Comment by patrick96** [comment]
No, there is no conditional formatting, you can only highlight all the layouts with the same color. You would have to use a script module for that (`setxkbmap -query` could be useful here).

**Comment by cryptomaniac512** [comment]
Maybe you could implement this? :) I think this is a very handy feature

if use a script to display the layout, it may not be trivial to implement the highlight when CapsLock is on as it is now

**Comment by patrick96** [comment]
You could use an `xkeyboard` module to just display the indicators and a script to display the layout.
I don't think implementing conditional formatting is a good idea, I think it is way out of scope of what polybar is supposed to do
