### ISSUE TITLE
polybar update (arch linux)

### ISSUE THREAD

**Issue by helionmelion** [jaagr/polybar#748]
unable to update polybar in arch linux without previously setting 

`git config --global user.name`
and/or
`git config --global user.email`

after setting these, it worked normally.
![screenshot 2017-09-13 08 14 20](https://user-images.githubusercontent.com/25272493/30374607-eca412b6-985b-11e7-9a1f-cc3146898e3b.png)

**Comment by patrick96** [comment]
Thanks for reporting, I'll fix this shortly
