### ISSUE TITLE
stop working without any reason

### ISSUE THREAD

**Issue by eoli3n** [jaagr/polybar#749]
Hi,
My 2 top polybars (i launch 3 bars) on two screen stop working without any log.
How to debug it ?

Here my complete configuration -> https://github.com/eoli3n/dotfiles/tree/master/.config/polybar

I need to relaunch my i3 config every 5 min to get polybar working. The problem started maybe 2 month ago.

**Comment by eoli3n** [comment]
The bottom one stays alive

**Comment by patrick96** [comment]
Redirect the output of the three bar launches in `launch.sh` to log files and post that on here.

**Comment by patrick96** [comment]
Also try to remove the github module, this may be related to #754

**Comment by eoli3n** [comment]
it is, "solved" by removing github module, thx

**Comment by patrick96** [comment]
Alright I think this is a duplicate of #754. On that issue, using `polybar-git` "fixed" the issue (the bar stopped crashing, just the github module disappeared).

**Comment by eoli3n** [comment]
I already use ``polybar-git`` and it crashed

**Comment by patrick96** [comment]
Hmm, strange. What return code does polybar return?
