### ISSUE TITLE
 #include "proto/x.hpp" error on exherbo

### ISSUE THREAD

**Issue by fedelodo** [jaagr/polybar#750]
Hi, I'm trying to compile polybar on exherbo, i've compiled all the dependencies, cmake .. runs succesfull but when i run make i get this:

```
[  1%] Built target xpp
[  3%] Building CXX object bin/CMakeFiles/polybar.dir/components/bar.cpp.o
In file included from /home/federico/polybar/include/x11/types.hpp:3:0,
                 from /home/federico/polybar/include/components/bar.hpp:12,
                 from /home/federico/polybar/src/components/bar.cpp:3:
/home/federico/polybar/lib/xpp/include/xpp/event.hpp:9:23: fatal error: proto/x.hpp: No such file or directory
 #include "proto/x.hpp"
             ^
compilation terminated.
```

**Comment by patrick96** [comment]
What version of polybar are you compiling?
What is the output of cmake?

**Comment by fedelodo** [comment]
I'm trying to compile 3.0.5 version. [Here](https://pastebin.com/B3hFQ0u3) is my cmake output.

**Comment by skystrife** [comment]
Have you checked out the submodules as well? You can get them with a

```bash
git submodule update --init --recursive
```

**Comment by fedelodo** [comment]
I tried to clone the repo again and checked the submodules but i keep getting the same result.

**Comment by skystrife** [comment]
Hm. You're missing

```
-- xpp: including xcb proto xproto.xml
```

in your `cmake` output... What is in the folder `/usr/share/xcb`?

I assume you're missing some package that provdes `/usr/share/xcb/xproto.xml`. I'm unfamiliar with your particular distribution, but maybe the `xproto` package has this?

**Comment by fedelodo** [comment]
if I run ` ls /usr/share/xcb/` ([ here](https://pastebin.com/Rn1AZcDD) is the output) `/usr/share/xcb/xproto.xml` is present.

**Comment by skystrife** [comment]
Strange. Can you apply the following patch to `lib/xpp/CMakeLists.txt` and re-run `cmake` in a clean build directory and give me the full output?

For some reason it's not finding those `.xml` files it would seem...

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3a87cc4..273d20a 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -129,11 +129,15 @@ if(NOT XCBPROTO_PREFIX)
 endif()
 file(GLOB PROTO_LIST_RAW RELATIVE ${XCBPROTO_PREFIX}/share/xcb ${XCBPROTO_PREFIX}/share/xcb/*.xml)
 
+message(STATUS "${PROJECT_NAME}: PREFIX: ${XCBPROTO_PREFIX}")
+message(STATUS "${PROJECT_NAME}: PROTO_LIST_RAW: ${PROTO_LIST_RAW}")
+
 #
 # Filter glob
 #
 foreach(PROTO_RAW ${PROTO_LIST_RAW})
   string(REGEX REPLACE "(^xf86vidmode.xml|^ge.xml|.xml)\$" "" PROTO ${PROTO_RAW})
+  message(STATUS "${PROJECT_NAME}: looking for proto ${PROTO}...")
   if(PROTO AND ";${XCB_PROTOS};" MATCHES ";${PROTO};")
     message(STATUS "${PROJECT_NAME}: including xcb proto ${PROTO_RAW}")
     set(PROTO_LIST ${PROTO_LIST} ${PROTO})
```

**Comment by fedelodo** [comment]
[here](https://pastebin.com/nhbqt5Lt) is the full cmake output

**Comment by skystrife** [comment]
Alright, that prefix doesn't look right to me. Interesting.

What are the contents of `/usr/lib/pkgconfig/xcb-proto.pc`?

I suspect that you might be able to get things working with a `-DXCBPROTO_PREFIX=/usr` in your `cmake` call, but I'm not 100% sure.

**Comment by fedelodo** [comment]
```
prefix=/usr/x86_64-pc-linux-gnu
exec_prefix=${prefix}
datarootdir=/usr/share
datadir=/usr/share
libdir=/usr/x86_64-pc-linux-gnu/lib
xcbincludedir=${datadir}/xcb
pythondir=${prefix}/lib/python3.6/site-packages

Name: XCB Proto
Description: X protocol descriptions for XCB
Version: 1.12
```
maybe I should use  -DXCBPROTO_PREFIX=/usr/x86_64-pc-linux-gnu i think that the problem is that by default exherbo is configured for cross compiling, maybe the prefix are different.

**Comment by fedelodo** [comment]
It worked. I should write an exheres for this.

**Comment by skystrife** [comment]
It worked with which prefix, (1) `-DXCBPROTO_PREFIX=/usr` or (2) `-DXCBPROTO_PREFIX=/usr/x86_64-pc-linux-gnu`?

(2) should be equivalent to what it was doing before when it wasn't working (as I assume the folder `/usr/x86_64-pc-linux-gnu/share/xcb/` is either empty or non-existent), whereas (1) is what I *think* it should be based on the fact that the files that the xpp library is looking for are there.

If `-DXCBPROTO_PREFIX=/usr` is what worked, then I think I might be able to use [`pkg_get_variable()`](https://cmake.org/cmake/help/v3.4/module/FindPkgConfig.html?highlight=pkg_get_variable#command:pkg_get_variable) to get the data directory from `xcbincludedir` in the package config (if `cmake >= 3.4` is detected, anyway).

On my system, this is what my pkgconfig looks like for `xcb-proto`:

```
prefix=/usr
exec_prefix=${prefix}
datarootdir=${prefix}/share
datadir=${datarootdir}
libdir=${exec_prefix}/lib
xcbincludedir=${datadir}/xcb
pythondir=${prefix}/lib/python3.6/site-packages

Name: XCB Proto
Description: X protocol descriptions for XCB
Version: 1.12
```

Right now, `xpp` is looking for the files in `$prefix/share/xcb`; I think it might be better to look in `$xcbincludedir` directly (when possible; `cmake >= 3.4`) as that would (I think) be the correct path on your system as well as mine.

**Comment by fedelodo** [comment]
it worked using `-DXCBPROTO_PREFIX=/usr/x86_64-pc-linux-gnu`, I don't know why without it it doesn't work.

**Comment by patrick96** [comment]
It absolutely doesn't make any sense to me that `-DXCBPROTO_PREFIX=/usr/x86_64-pc-linux-gnu` would work. Setting this variable manually shouldn't change anything, since it is already being set by the `xcb-proto.pc`. What does your cmake output when using both `-DXCBPROTO_PREFIX=/usr/x86_64-pc-linux-gnu` and the patch @skystrife posted [above](https://github.com/jaagr/polybar/issues/750#issuecomment-329622531)?

I'll try to adapt the cmake file to use the `xcbincludedir` property to load the xml files.

**Comment by patrick96** [comment]
@fedelodo Can you please use https://github.com/jaagr/xpp/pull/12 in the xpp submodule and see if cmake **without** `-DXCBPROTO_PREFIX=/usr/x86_64-pc-linux-gnu` in a clean build directory works properly now.

You can use the the PR in the xpp submodule by doing the following inside the polybar git repo:
```bash
cd lib/xpp
git remote add patrick96 git@github.com:patrick96/xpp.git
git fetch patrick96
git checkout patrick96/xcbincludedir
```

**Comment by DanySpin97** [comment]
Another Exherbo user here.

I've tried `patrick96/xcbincludedir` (after rebasing to the latest upstream version) and it works.
