### ISSUE TITLE
i3 module Switching to workspace 1 creates new workspace 1

### ISSUE THREAD

**Issue by AichP** [jaagr/polybar#755]
Hello, since day one I have a problem using polybar with i3 workspaces.

Heres a quick [gif](https://media.giphy.com/media/xT9IgOu2eZZ3FGeYjC/giphy.gif) of the issue. 

So basically whenever I want to switch to workspace 1 via $mod+1 instead of opening the workspace 1 get another workspace titeled 1 right next to it.

I've had a more complex configuration, but have since then gone back to default i3 config and somewhat default i3 module for polybar to narrow down the issue. 

i3 config:

```
# switch to workspace
bindsym $mod+1 workspace 1 
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace 1; workspace 1
bindsym $mod+Shift+2 move container to workspace 2; workspace 2
bindsym $mod+Shift+3 move container to workspace 3; workspace 3
bindsym $mod+Shift+4 move container to workspace 4; workspace 4
bindsym $mod+Shift+5 move container to workspace 5; workspace 5
bindsym $mod+Shift+6 move container to workspace 6; workspace 6
bindsym $mod+Shift+7 move container to workspace 7; workspace 7
bindsym $mod+Shift+8 move container to workspace 8; workspace 8
bindsym $mod+Shift+9 move container to workspace 9; workspace 9
bindsym $mod+Shift+0 move container to workspace 10; worskpace 10
```
polybar config:

```
[module/i3]
type = internal/i3
pin-workspaces = true
enable-scroll = true
wrapping-scroll = true
format = <label-state> <label-mode>

label-mode = %mode% 
label-mode-padding = 2
label-mode-background = #e60053

label-focused = %index%  
label-focused-foreground = ${colors.primary}
label-focused-padding = 4

label-unfocused = %index%
label-unfocused-padding = 4

label-visible = %index%
label-visible-foreground = ${colors.primary}
label-visible-padding = 4

label-urgent = %index%
label-urgent-foreground = #bd2c40
label-urgent-padding = 4
```

im currently on:
```
polybar 3.0.5-git

Features: +alsa +curl +i3 -mpd +network
```

Non of the log options gives any valuable information about this issue.

When I add lables to the i3 module, polybar, instead of naming the new worspace 1, gives it the sepcified default label.

Any ideas? Thanks in advance! (btw. polybar - best bar!)

**Comment by patrick96** [comment]
Does this only happen with polybar or does it happen with `i3status` too?

**Comment by AichP** [comment]
Yes the issue persists with the i3status bar. - So polybar is most likley not the issue. Therefore it can be closed.

Nontehless:
I just figured out that the issue only occurs with the workspace thats openend when booting the machine.
For some reason this "starting" workspace does not play by the rules. When I close and reopen workspace 1 everything works fine.

**Comment by patrick96** [comment]
This looks like something that should be filed with the i3 guys.
Closing this, as it has nothing to do with polybar

**Comment by aeroslubis** [comment]
I found the problem happens because there is a space after "bindsym $mod+1 workspace 1 " it should be "bindsym $mod+1 workspace 1" with no space after 1.
