### ISSUE TITLE
Problem with sudo make install

### ISSUE THREAD

**Issue by zarMarco** [jaagr/polybar#756]
Hi, I try to install polybar on my arch. When I do sudo make install, into correct folder I have any error
`─[saul@archBook] - [~/polybar/build] - [2017-09-16 09:08:10]
└─[2] <git:(4e2e2a7 4e2e2a7) > sudo make install
[  1%] Linking CXX static library libxpp.a
Traceback (most recent call last):
  File "/home/saul/polybar/lib/xpp/generators/cpp_client.py", line 3163, in <module>
    from xcbgen.state import Module
  File "/usr/lib/python3.6/site-packages/xcbgen/state.py", line 7, in <module>
    from xcbgen import matcher
  File "/usr/lib/python3.6/site-packages/xcbgen/matcher.py", line 12, in <module>
    from xcbgen.xtypes import *
  File "/usr/lib/python3.6/site-packages/xcbgen/xtypes.py", line 1221, in <module>
    class EventStruct(Union):
  File "/usr/lib/python3.6/site-packages/xcbgen/xtypes.py", line 1239, in EventStruct
    out = __main__.output['eventstruct']
KeyError: 'eventstruct'
make[2]: *** [lib/xpp/CMakeFiles/xpp.dir/build.make:70: lib/xpp/libxpp.a] Error 1
make[1]: *** [CMakeFiles/Makefile2:385: lib/xpp/CMakeFiles/xpp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`

**Comment by patrick96** [comment]
What is the output of the following commands:
```bash
pacman -Qi xcb-proto
grep -rni "output\[" /usr/lib/python3.6/site-packages/xcbgen/
```
```

**Comment by zarMarco** [comment]
hi, this is output `┌─[root@archBook] - [/home/saul] - [2017-09-16 10:32:35]
└─[0] <> pacman -Qi xcb-proto
grep -rni "output\[" /usr/lib/python3.6/site-packages/xcbgen/
errore: impossibile trovare il pacchetto 'xcb-proto'
/usr/lib/python3.6/site-packages/xcbgen/state.py:74:    open = __main__.output['open']
/usr/lib/python3.6/site-packages/xcbgen/state.py:75:    close = __main__.output['close']
/usr/lib/python3.6/site-packages/xcbgen/xtypes.py:205:    out = __main__.output['simple']
/usr/lib/python3.6/site-packages/xcbgen/xtypes.py:232:    out = __main__.output['simple']
/usr/lib/python3.6/site-packages/xcbgen/xtypes.py:270:    out = __main__.output['enum']
/usr/lib/python3.6/site-packages/xcbgen/xtypes.py:977:    out = __main__.output['struct']
/usr/lib/python3.6/site-packages/xcbgen/xtypes.py:988:    out = __main__.output['union']
/usr/lib/python3.6/site-packages/xcbgen/xtypes.py:1186:    out = __main__.output['request']
/usr/lib/python3.6/site-packages/xcbgen/xtypes.py:1239:    out = __main__.output['eventstruct']
/usr/lib/python3.6/site-packages/xcbgen/xtypes.py:1328:    out = __main__.output['event']
/usr/lib/python3.6/site-packages/xcbgen/xtypes.py:1359:    out = __main__.output['error']
`
I've installed xcb-proto-git

**Comment by patrick96** [comment]
It looks like `xcb-proto-git` is totally out of date. Installing `xcb-proto` should fix the build errors.
I'm closing this, please reopen if the error still occurs.
