### ISSUE TITLE
Problem with sudo make install

### ISSUE THREAD

**Issue by zarMarco** [jaagr/polybar#757]
Hi, I've tried to install polybar on my arch. I've installed xcb-proto instead of xcb-proto-git.
This is output `┌─[saul@archBook] - [~/polybar/build] - [2017-09-16 10:41:13]
└─[0] <git:(4e2e2a7 4e2e2a7) > sudo make install
Scanning dependencies of target xpp
[  1%] Linking CXX static library libxpp.a
list: size, ['red', 'green', 'blue']
list: size, ['red', 'green', 'blue']
[  1%] Built target xpp
Scanning dependencies of target i3ipc++
[  2%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o
In file included from /home/saul/polybar/lib/i3ipcpp/src/ipc.cpp:9:0:
/home/saul/polybar/lib/i3ipcpp/include/i3ipc++/ipc-util.hpp:147:57: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 std::shared_ptr<buf_t>   i3_recv(const int32_t  sockfd) throw (invalid_header_error, eof_error);
                                                         ^~~~~
In file included from /home/saul/polybar/lib/i3ipcpp/src/ipc.cpp:9:0:
/home/saul/polybar/lib/i3ipcpp/include/i3ipc++/ipc-util.hpp:163:131: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 Type  type, const std::string&  payload = std::string()) throw (invalid_header_error, eof_error);
                                                          ^~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [lib/i3ipcpp/CMakeFiles/i3ipc++.dir/build.make:63: lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:440: lib/i3ipcpp/CMakeFiles/i3ipc++.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`

**Comment by patrick96** [comment]
When compiling polybar 3.0.5, you'll need to run
```
cmake -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" ..
```
instead of just `cmake ..`

**Comment by zarMarco** [comment]
thaks
