### ISSUE TITLE
Modules gradient issue

### ISSUE THREAD

**Issue by flameshikari** [jaagr/polybar#759]
My bar have gradient with two colors. When I used version _3.0.5_ bar looked like this:
![Old](https://image.ibb.co/eJbaTk/image.png)

But after aur-git update to version _3.0.5-44-ga682d2a_ I got this:
![New](https://image.ibb.co/bVGEM5/2017_09_17_015242_1365x26_scrot.png)

Modules has no gradients now. I read the wiki, but there is nothing about it and I tried some combinations with _format-background_ etc. Any help, please? Should I use one color for the bar?

P. S. Sorry about my English, it isn't my primary language.

**Comment by patrick96** [comment]
There is some color weirdness in the latest commits, the issue is tracked in #639.
To confirm that this is actually the issue, could you post the output, when you run polybar with the `-s` option (for both versions)

**Comment by flameshikari** [comment]
**Version 3.0.5**:
`%{l}%{A5:i3wm-wsprev: A4:i3wm-wsnext: A1:i3wm-wsfocus-1:}  %{A A A}  %{A1:thunar / &:A3:terminator --working-directory / &: F#38A1E3} %{F#252229}140%{F- A A F-}  %{A1:thunar ~ &:A3:terminator --working-directory ~ &: F#38A1E3} %{F#252229}343%{F- A A F-}  %{F#38A1E3} %{F- A1:terminator -x htop &:}42%{A}  %{F#38A1E3} %{F- A1:terminator -x htop &:}19%{A}  %{F#38A1E3} %{F- A1:~/.config/polybar/output.sh --battery:}100%{A}%{c}%{A1:~/.config/polybar/output.sh --date:}03:07:16%{A}%{r}%{A1:volmute: A4:volup: A5:voldown: F#38A1E3} %{F-}61%{A A A}  %{F#38A1E3}%{F-} %{A1:~/.config/polybar/output.sh --interfaces &:A3:terminator -x nmtui &:}192.168.0.47%{A A}  %{A1:xkblayout-state set +1 &: F#38A1E3} %{F#252229}	0%{A F-}  %{A1:~/.config/polybar/output.sh --dropbox-notification &:A3:thunar ~/Downloads/Dropbox &: F#38A1E3} %{F#252229}R%{A A F-}  %{F#38A1E3} %{F#252229}1%{F-}  %{A1:xkblayout-state set +1 &: F#252229}EN%{F#D81A1C A F-}`

**Version 3.0.5-44-ga682d2a**:
`%{l}%{A5:i3wm-wsprev: A4:i3wm-wsnext: A1:i3wm-wsfocus-1:}  %{A A A}  %{A1:thunar / &:A3:terminator --working-directory / &: F#38A1E3} %{F#252229}140%{F- A A F-}  %{A1:thunar ~ &:A3:terminator --working-directory ~ &: F#38A1E3} %{F#252229}343%{F- A A F-}  %{F#38A1E3} %{F- A1:terminator -x htop &:}41%{A}  %{F#38A1E3} %{F- A1:terminator -x htop &:}22%{A}  %{F#38A1E3} %{F- A1:~/.config/polybar/output.sh --battery:}100%{A}%{c}%{A1:~/.config/polybar/output.sh --date:}03:05:38%{A}%{r}%{A1:volmute: A4:volup: A5:voldown: F#38A1E3} %{F-}61%{A A A}  %{F#38A1E3}%{F-} %{A1:~/.config/polybar/output.sh --interfaces &:A3:terminator -x nmtui &:}192.168.0.47%{A A}  %{A1:xkblayout-state set +1 &: F#38A1E3} %{F#252229}	0%{A F-}  %{A1:~/.config/polybar/output.sh --dropbox-notification &:A3:thunar ~/Downloads/Dropbox &: F#38A1E3} %{F#252229}R%{A A F-}  %{F#38A1E3} %{F#252229}1%{F-}  %{A1:xkblayout-state set +1 &: F#252229}EN%{F#D81A1C A F-}`

See no difference.

**Comment by patrick96** [comment]
Yeah I don't see any either.
I think I have tracked down the issue. Can you locally revert commit https://github.com/jaagr/polybar/commit/0bd8f1f69a8dfdb2f2800a6612c8acb7e6c86ed2 and recompile and test if that fixes it.

**Comment by flameshikari** [comment]
Sorry for delay. I just did read some manuals about git, because I'm not so friendly with it. I reverted commit as you said, recompiled it and it works fine now:

![Nice](https://image.ibb.co/mzeFDk/2017_09_17_052516_1365x129_scrot.png)

What's now?

**Comment by patrick96** [comment]
Now, we have figured out what the problem is. That commit you reverted sets the background color when rendering a module to the bar background and doesn't consider a gradient [here](https://github.com/jaagr/polybar/commit/0bd8f1f69a8dfdb2f2800a6612c8acb7e6c86ed2#diff-543075e5874c51140b59304a24b67c78R208).

I will try to fix this as soon as we merge #729 as it also messes with the colors.

**Comment by flameshikari** [comment]
OK! Thanks for help by the way!

**Comment by NBonaparte** [comment]
@patrick96 Any updates on a fix? Just wanted to know if you've started working on it, because as it stands, this is the only issue left on the 3.1.0 milestone.

**Comment by patrick96** [comment]
Sorry, I forgot about this. I think we can release version 3.1.0 without this fix and just schedule it for 3.2.0, it isn't really a critical bug

**Comment by TonCherAmi** [comment]
@patrick96 hey, I seem to have managed to fix this, do you mind if I submit a PR?

**Comment by patrick96** [comment]
@TonCherAmi Yes! Please do.
