### ISSUE TITLE
problem with make

### ISSUE THREAD

**Issue by Wabri** [jaagr/polybar#761]
I install all the dependency to install polybar (cmake cmake-data libcairo2-dev libxcb1-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-randr0-dev libxcb-util0-dev libxcb-xkb-dev pkg-config python-xcbgen xcb-proto libxcb-xrm-dev i3-wm libasound2-dev libmpdclient-dev libiw-dev libcurl4-openssl-dev), but when I install with make i get this error 

![polybar](https://user-images.githubusercontent.com/12409541/30524457-641337a0-9bf4-11e7-92af-d99c46be218b.png)

I can't find what are missing, I think is a problem of xcb library or there is a bug in your make file.

**Comment by patrick96** [comment]
Please see, if this fixes your issue:
https://github.com/jaagr/polybar/wiki/Compiling#version-mismatch-between-xcb-proto-and-libxcb-randr0-dev

**Comment by Wabri** [comment]
it works

thank you so much
