### ISSUE TITLE
error: Disabling module "wlan" (reason: No built-in support for 'internal/network')

### ISSUE THREAD

**Issue by ZakharH** [jaagr/polybar#764]
brand new arch install, install `polybar` and `wireless_tools` but  i still get this error

    error: Disabling module "wlan" (reason: No built-in support for 'internal/network')

This is my config:
```
[module/wlan]
type = internal/network
interface = wlp6s0
interval = 3.0
label-connected = %essid%
format-connected = <ramp-signal>  <label-connected>
format-connected-underline = #98A424
format-connected-padding = 3
format-disconnected ="  Not Connected"
format-disconnected-underline = ${colors.color4}
ramp-signal-0 = 
ramp-signal-0-foreground = ${colors.fg}
ramp-signal-1 = 
ramp-signal-1-foreground = ${colors.fg}
ramp-signal-2 = 
ramp-signal-2-foreground = ${colors.fg}
ramp-signal-3 = 
ramp-signal-3-foreground = ${colors.fg}
ramp-signal-4 = 
ramp-signal-4-foreground = ${colors.fg}
```

**Comment by patrick96** [comment]
Did you install wireless_tools before you compiled polybar?

**Comment by ZakharH** [comment]
Originally I did not, but after installing `wireless-tools` I did recompile polybar

**Comment by ZakharH** [comment]
Solved issue. Reason it did not work earlier is probably I did not reboot in between installing wireless tools and recompiling polybar.
