### ISSUE TITLE
BSPWM Multiple monitor workspace label

### ISSUE THREAD

**Issue by Bl4ckb0ne** [jaagr/polybar#768]
Hi,

I have a current setup of two monitors with BSPWM. Each monitor has 5 workspaces, defined as such in my `bspwmrc`

```
bspc monitor DVI-I-1 -d 6 7 8 9 0
bspc monitor HDMI-0 -d 1 2 3 4 5
```
HDMI-0 is on the left, DVI-I-1 is on the right.

In my polybar config file, I have two bars, `left` and `right`. Each bar has its own bspwm module, like this 
```
[bar/left]
monitor = ${env:MONITOR:HDMI-0}
modules-right = bspwm-l
wm-restack = bspwm

[bar/right]
monitor = ${env:MONITOR:DVI-I-1}
modules-left = bspwm-r
wm-restack = bspwm
```

But on the rendering, the name of the workspaces are not displayed correctly 
![](https://sr.ht/Mq6n.png)

Is it possible to redefine the name outputed? And is this a bug?

**Comment by patrick96** [comment]
Hi, I doubt this is a bug. I suspect in your bpwm modules definition, you use the `%index%` token for `label-*`. This will print the index of the desktop on the current monitor. You probably want ot use the `%name%` token.

**Comment by Bl4ckb0ne** [comment]
It was indeed!
Thanks for the hint.

**Comment by Bl4ckb0ne** [comment]
Shouldn't `%name%` be the default config though?

**Comment by patrick96** [comment]
The default is `%icon%  %name%` for all the `label-X` settings (except for `label-monitor`).
The sample config that comes with polybar uses `%index%` though, but that one is just there to kind of show you what's available
