### ISSUE TITLE
Toggle through labels

### ISSUE THREAD

**Issue by diskotechjam** [jaagr/polybar#769]
I currently have a simple mpc module which displays the title of the currently playing song. I would like to be able click the module and toggle through a list of different information about the current song. For example, the module would display the title of the song, clicking would then display the artist, clicking again would display the album, clicking again would display the next song, etc. 

Is such a feature currently available in polybar?

**Comment by patrick96** [comment]
When you say your are using s "simple mpc module" are you talking about the [`mpd module`](https://github.com/jaagr/polybar/wiki/Module:-mpd) or a script module?

If you are using the built-in mpd module this is not possible and I don't think that's a feature we'll add.
If you are using a script to display the info, this is certainly possible, you can define click handlers for your script module that send information to the script that displays the info (polybar even supplies a `%counter%` token), either by writing to some other file or through a pipe or socket.
