### ISSUE TITLE
How can I add custom click-handler on date module?

### ISSUE THREAD

**Issue by karambaq** [jaagr/polybar#775]
I wrote script that show a calendar, how can I edit date module to do that?

**Comment by patrick96** [comment]
There is no built-in handler on the date module. However there is an [action format tag](https://github.com/jaagr/polybar/wiki/Formatting#action-a) which you can use as part of the `label` or `format`:
```dosini
format =%{A1:launch-calendar.sh:} 🕓 <label> %{A}
```
