### ISSUE TITLE
Problems with multiple bars

### ISSUE THREAD

**Issue by schaden-freude** [jaagr/polybar#778]
Consider the following scenario:

I have a primary bar `polybar primary`. I have a module in this bar, clicking on which it launches a new bar, `polybar secondary &`, i.e launches the bar in the background. If I don't have any clickable area defined in the secondary bar, and click on anywhere on the secondary bar, the secondary bar is killed/exits.

This problem doesn't appear if I don't launch the bar in the background. However, if I don't launch the secondary bar as a background process, I can't interact(click) with the primary bar while the secondary bar is displayed.

**Comment by patrick96** [comment]
Have a look at #770 for how to start background processes from polybar without them automatically being killed.

**Comment by schaden-freude** [comment]
Thanks for the response. 

The `nohup` and `setsid` methods work for me.
