### ISSUE TITLE
Switch format in network module like the date module?

### ISSUE THREAD

**Issue by Drakota** [jaagr/polybar#781]
In the date module, you can specify a `date-alt` or `time-alt` when the date is clicked to switch between format. I want to do something similar, but with the network module so I'm able to click the module and get my IP. My current label is label-connected = %essid% and I would like something like label-connected-alt = %local_ip%
Thanks.

**Comment by NBonaparte** [comment]
This is not currently possible with the network module. However, you could build something similar with the ipc module using scripts instead.
