### ISSUE TITLE
Reload without restarting polybar

### ISSUE THREAD

**Issue by Lindenk** [jaagr/polybar#787]
Hello!

Currently when polybar reloads, it kills itself completely and reopens. This causes polybar to disappear, my window manager to resize everything, then again, and finally polybar reappears. Even though this all happens in less than half a second, it's still pretty jarring, especially if the config file is updated automatically (to adjust colors/icons/etc).

Although this is a fairly trivial request, it would give polybar the ability to be much more ascetically pleasing with some fancy configurations. An alternitive request would be a way to update modules/bars with polybar already running (and without it completely reloading itself). 

For extra credit, being able to define an easing function for said changes would be amazing.

I'd be happy to put some work into it if anyone else would like this feature too.

**Comment by patrick96** [comment]
While it would be nice for the bar to be able to automatically reload without restarting, this would require major code changes and probably a total rewrite of how the bar is created. This is far from trivial. And the thing with the easing function is probably far from impossible.

I don't think this is something, we'll takle in the near future, maybe if/when we need to rewrite parts of polybar anyways.

**Comment by Chinggis6** [comment]
i do `pkill -USR1 polybar` to reload `polybar`.

i applied this signal from what I read in the manual page of `dunst`, and it worked.

**Comment by salman-abedin** [comment]
From my experience, you can set the interval to 0 on the module itself then sleep on your script to achieve the effect you are after.
