### ISSUE TITLE
How to setting fonts siji ?

### ISSUE THREAD

**Issue by incognitto** [jaagr/polybar#790]
Hello everyone,
well, i am trying configure my polybar with fonts siji on first time, I searched for configs in google to get an idea of how they work, but in all settings the siji fonts are copied and pasted, ie I need to copy and paste in my configuration, I thought it would just be the icone code would work, I would like the pacman icon, but I can not find it anywhere and put the icon code in the config does not work. 

![2017-10-04-23 30 25-screenshot](https://user-images.githubusercontent.com/30783071/31208585-58883988-a95c-11e7-973b-638a1b6477d5.png)

Thank you in advance

**Comment by patrick96** [comment]
I don't think polybar supports just adding the icon code directly. What I do is, I have a script that "converts" the icon code to the actual icon and sets it inside an environment variable, like this:
```bash
export ICON_HDD="$(echo -e "\uF0A0")"
```
Where `F0A0` is the icon code for whatever icon you want to use.
If you run this before starting polybar, you can now use that icon like this:
```dosini
label-xyz = ${env:ICON_HDD}
```
**Note: ** `label-xyz = Before${env:ICON_HDD}After` will not work, the variable reference has to be the only thing there, so you may need to define the whole content of the label inside a shell script using env variables.

As for finding the pacman icon, check the Font page on the wiki on how to use `gucharmap` to look for icons inside a font.

**Comment by NBonaparte** [comment]
Can't you just run `echo -e \u<code>`, copy the outputted glyph from the terminal, and paste it in the config?

**Comment by incognitto** [comment]
@patrick96 Thanks man, "gucharmap" solved my problem
@NBonaparte not working with your advise, but thank for your help.

Closing this issue
