### ISSUE TITLE
bspwm- how to make focused workspace not change colors? 

### ISSUE THREAD

**Issue by Brett99** [jaagr/polybar#791]
Currently the bspwm module has support for changing the colors of each item based on whether or not they have windows in them. It also changes the color for focused desktops.

How can I make it so that if I am focused on an empty workspace, it's icon is still the empty color? I don't want to change the colors of the foreground at all when moving around, only change the underline. I currently can only get it to do this, or not change colors at all. 

Is this possible?

**Comment by patrick96** [comment]
If I understand you right, you want the `label-focused-foreground` to be whatever the foreground was before you focued on that workspace?

I don't know if this will work, but what happens, if you totally remove the `label-focused-foreground` setting?

**Comment by Brett99** [comment]
You are correct. I want only the underline to indicate which desktop has focus, and the colors to always only indicate whether the desktop is empty or not. 

Removing the `label-focused-foreground` line does not seem to do the trick. It seems to just set `label-focused-foreground` to white.

**Comment by patrick96** [comment]
Can you post your entire config, so that I can play around with this, once I get the time?
But it seems like this is not possible right now

**Comment by Brett99** [comment]
I'm just using the stock config currently with some of the modules removed

**Comment by 100gamma** [comment]
Is there any update on this?
