### ISSUE TITLE
Non-padded dates stopped working

### ISSUE THREAD

**Issue by elomatreb** [jaagr/polybar#792]
Hi - I apologize if this is user error, but I have a problem I can't seem to get fixed. I updated my polybar recently and the escape sequences in my date module for non-padded (no leading 0) days and months stopped working, and are output verbatim.

My date module is configured like so:
```INI
[module/date]
type = internal/date
interval = 1

date = "%-d.%-m."
date-alt = "%A, %-d.%-m.%Y"

time = %H:%M
time-alt = %H:%M:%S

label = " %date% %time% "
```
However, this is how the module appears:

![rwehtfgvujk](https://user-images.githubusercontent.com/3387265/31290646-80eb7576-aacd-11e7-80b8-70ce1d7015ed.png)

According to [the docs](https://github.com/jaagr/polybar/wiki/Module:-date#basic-settings), the syntax is like the date command. However, it works like it used to/how I'd expect:
```
$ date +%-d.%-m.
6.10.
```
My polybar version (installed from the AUR package):
```
$ polybar --version
polybar 3.0.5-72-gcaeb8dd

Features: +alsa +curl +i3 -mpd +network
```

Thank you for any help.

**Comment by NBonaparte** [comment]
We recently switched to `std::put_time()` from `strftime` in #745 because of string length issues. Looks like it doesn't actually support flags in front of format specifiers.

**Comment by patrick96** [comment]
I have updated the wiki with a link to http://en.cppreference.com/w/cpp/io/manip/put_time which lists all tokens accepted by `std::put_time()` and thus also accepted by polybar. Unfortunately I haven't found a way for the numbers not to be padded

**Comment by elomatreb** [comment]
There is a space-padded version of the day of the month (`%e`) at least, I guess this will have to do. Thank you for the help.
