### ISSUE TITLE
Custom script output only appears after script finishes with `tail = true`

### ISSUE THREAD

**Issue by euclio** [jaagr/polybar#793]
I've written a simple python script:

```python
import time
for i in range(3):
    print(i)
    time.sleep(1)
```

and saved it as `~/.config/polybar/log`. I also added

```
[module/log]
type = custom/script
exec = python ~/.config/polybar/log
tail = true
```

to my polybar config.

However, `0` only appears in the bar after the script finishes. I would expect the output to appear as it is generated (`0`, `1`, `2` every second). Am I misunderstanding how tail is supposed to work?

**Comment by patrick96** [comment]
I haven't tried this, but try using `python -u`

**Comment by euclio** [comment]
Aha! That was it. Thank you!

**Comment by tomasz13nocon** [comment]
I spent hours trying to track this down. My script was not showing half the time, then it seemed to update at random intervals.

Can this be added to the docs? [Here](https://github.com/polybar/polybar/wiki/Module:-script) would be a good place to mention this.

It seems to happen when the main python thread blocks at any point.

**Comment by patrick96** [comment]
@tomasz13nocon Done: https://github.com/polybar/polybar/wiki/Module:-script
