### ISSUE TITLE
Time Module error.

### ISSUE THREAD

**Issue by Clyybber** [jaagr/polybar#795]
My time and date doesn't display anymore
`error: Disabling module "time" (reason: locale::facet::_S_create_c_locale name not valid)`
It happened after i updated the AUR polybar-git version.
Here's the output of `locale`
```LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
I also tried to export LC_ALL before starting polybar but that didn't help.
I'm really lost on this one.

EDIT: I had `locale = de_DE.UTF-8` in my config. Changing it to en_US.UTF-8 solved it. Makes sense.

**Comment by patrick96** [comment]
Please also post your polybar config. This may be because the value you have set for `locale` in the polybar config is not valid.

**Comment by Clyybber** [comment]
Thank you! I updated the issue and will close this.
