### ISSUE TITLE
two volume modules - is it possible?

### ISSUE THREAD

**Issue by helionmelion** [jaagr/polybar#796]
I have a working volume control module (master sink) and would like to add a second one for another sink but without success. Is it possible?

**Comment by patrick96** [comment]
I'm assuming by sink you mean mixer because I don't think alsa has sinks
But that should be possible. You can do this by defining a new module
```dosini
[module/volume2]
type = internal/volume

master-mixer = NAME_OF_YOUR_OTHER_MIXER
...
```

**Comment by helionmelion** [comment]
sorry, didnt myself clear. I meant to add a volume control for another card. For instance, one volume control for usb audio and another for HDMI audio. In my currently configuration, it is working for default output device (fallback) and usb audio. So I realized I have to point the cards but didnt figure out how to do that.

`[module/volume]
type = internal/volume

; Name of the master mixer
; Default: Master
master-mixer = Master

format-volume = <label-volume> <bar-volume>
label-volume =  VOL %percentage%%
label-volume-foreground = ${root.foreground}

format-muted-prefix = " "
format-muted-foreground = ${colors.foreground-alt}
label-muted = sound muted

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}`

**Comment by NBonaparte** [comment]
You could use `master-soundcard = hw:N`, with `N` coming from whichever output you want from `aplay --list-devices` (just the card number).

**Comment by helionmelion** [comment]
thanks for your response.
tried 
> master-soundcard = hw:N 
but seems only working with hw:0
other number than 0, volume bar simple vanishes.

my results from `aplay --list-devices
![screenshot 2017-10-09 15 40 28](https://user-images.githubusercontent.com/25272493/31353272-4347e1e0-ad08-11e7-927a-836685f1150c.png)
`

**Comment by NBonaparte** [comment]
What is the output of polybar when the module disappears?

Also, what is the output of `amixer -c N scontrols` (for all `N` you want)?

**Comment by helionmelion** [comment]
output of polybar:
`error: Disabling module "volume" (reason: Cannot find simple element)`
![screenshot 2017-10-09 18 39 36](https://user-images.githubusercontent.com/25272493/31359724-8fc78d72-ad21-11e7-83c6-ae372f2f0035.png)
(in this instance, used `master-soundcard = hw:2`)

output of `amixer -c N scontrols` (N=0, 1 and 2)
![screenshot 2017-10-09 18 44 23](https://user-images.githubusercontent.com/25272493/31359832-10bc61fa-ad22-11e7-9770-7c9095836f55.png)
![screenshot 2017-10-09 18 45 08](https://user-images.githubusercontent.com/25272493/31359833-10be8980-ad22-11e7-94fe-2c0c46558570.png)

**Comment by helionmelion** [comment]
wait! using this config:
`[module/volume]
master-mixer = Speaker
master-soundcard = hw:1`
and
`[module/volume2]
master-mixer = IEC958
master-soundcard = hw:2`
it works!!!

but two new issue arrives: 

1. if you click on one volume control, cannot focus on the other :/

**Comment by patrick96** [comment]
What do you mean that you can't focus on the other?

If this is default alsa behaviour, you can use `alsamixer` and try to change the volume for that mixer on that card there. If it behaves the same as polybar then this is an alsa thing

**Comment by helionmelion** [comment]
I meant with two volume modules in same bar, seems it is possible to interact with the first module from left to right. The other became unavailable to any action. Could it be a bug?

> If this is default alsa behaviour, you can use alsamixer and try to change the volume for that mixer on that card there. If it behaves the same as polybar then this is an alsa thing

Indeed, alsamixer does not have volume controls for HDMI audio (IEC958). So, the only funcionality of a HDMI volume module in the bar is to mute it. Currently I use pulseaudio which can control volume of HDMI so, seems it was a mistakenly thinking since beginning, alsa is not pulseaudio!

**Comment by patrick96** [comment]
> I meant with two volume modules in same bar, seems it is possible to interact with the first module from left to right. The other became unavailable to any action. Could it be a bug?

If you have any of the two modules on the bar on their own, do they work normally?
Is it always the left one that works and the right one that doesn't, even if you switch them?
This is definitely not intended behaviour, the two modules should not interfere with each other.

> Indeed, alsamixer does not have volume controls for HDMI audio (IEC958). So, the only funcionality of a HDMI volume module in the bar is to mute it. Currently I use pulseaudio which can control volume of HDMI so, seems it was a mistakenly thinking since beginning, alsa is not pulseaudio!

If `alsamixer` does not have volume controls, then this is expected.
Since you use pulseaudio, I would recommend you use the User-contributed [`pavolume`](https://github.com/jaagr/polybar/wiki/User-contributed-modules#pulseaudio-volume) module or check out the pending pull request #779 which adds a dedicated pulseaudio module

**Comment by helionmelion** [comment]
> If you have any of the two modules on the bar on their own, do they work normally?
Is it always the left one that works and the right one that doesn't, even if you switch them?
This is definitely not intended behaviour, the two modules should not interfere with each other.

It works - I created a bottom bar and put the volume control on it.

> If alsamixer does not have volume controls, then this is expected.
Since you use pulseaudio, I would recommend you use the User-contributed pavolume module or check out the pending pull request #779 which adds a dedicated pulseaudio module

Deal. Thanks.

Strangely, after updating kernel today, the sound card number was swapped. So I had to modify the hw:N in volume modules. 

Thank your for your patience.

**Comment by patrick96** [comment]
> Is it always the left one that works and the right one that doesn't, even if you switch them?
This is definitely not intended behaviour, the two modules should not interfere with each other.

Can you try these out as well, it will be hard for me to troubleshoot otherwise.

**Comment by helionmelion** [comment]
>> Is it always the left one that works and the right one that doesn't, even if you switch them?
>>This is definitely not intended behaviour, the two modules should not interfere with each other.

>Can you try these out as well, it will be hard for me to troubleshoot otherwise.

yes, switch'em and its always the right module that does not work, always stuck. Glad if this info can help.

**Comment by patrick96** [comment]
I'll try to reproduce this on my end. What distribution and version of that distro are you using?

**Comment by helionmelion** [comment]
> I'll try to reproduce this on my end. What distribution and version of that distro are you using?
OS: arch linux x86_64
kernel: 4.13.7-1-arch
