### ISSUE TITLE
Build failure on latest commit

### ISSUE THREAD

**Issue by TheGag96** [jaagr/polybar#797]
Just pulled and tried to rebuild today, and I got [some errors](https://pastebin.com/drcF9MqP). 

Setup:

* Ubuntu 17.04, 64-bit
* GCC 6.3.0 20170406
* All modules enabled

Has this been happening for others? Thanks.

**Comment by patrick96** [comment]
Yes this is happening on ubuntu because of an xrandr version mismatch.
There are instructions for this on the Compiling page on the wiki
