### ISSUE TITLE
Nerd Fonts icons not displaying

### ISSUE THREAD

**Issue by masterfink** [jaagr/polybar#798]
I have searched through exisiting issues but I still cannot get a special icons (like fontawesome) to display in Polybar. I can see them just fine if I use i3blocks or something else. I have copied them straight to the config file using the Gnome Character Map. Any ideas? Attached is my configuration (I only added the .txt so that I could upload it. The original file is in the default location ~/.config/polybar/config)
[config.txt](https://github.com/jaagr/polybar/files/1370190/config.txt)

**Comment by patrick96** [comment]
Whats is the output of the bar when you run it with `-l info`?
Also did you check the "Show only glyphs from this font" in gucharmap before copying the icons?

**Comment by masterfink** [comment]
The output is below. And yes I did the "Show only glyphs from this font". 
warn: No monitor specified, using "LVDS1"
* Loaded monitor LVDS1 (1600x900+0+0)
* Bar geometry: 1600x35+0+0
* Starting application
* Starting module/i3
* Starting module/filesystem
* Starting module/xbacklight
* Starting module/volume
* Starting module/xkeyboard
* Starting module/memory
* Starting module/cpu
* Starting module/wlan
* Starting module/wlanip
* Starting module/eth
* Starting module/battery
* Starting module/temperature
* Starting module/date
* Starting module/powermenu
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=11)
* Configured DPI = 96x96
* Loaded font ""DejaVuSansMono Nerd Font Mono":pixelsize=10" (name=DejaVu Sans, offset=1, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
* Loaded font "FontAwesome:pixelsize=10" (name=DejaVu Sans, offset=1, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
* Bar window: 0x1000003
* Activating tray manager
* Tray window: 0x100000a
warn: Systray selection already managed (window=0x0c0000a)
* Deactivating tray manager
* module/i3: Rebuilding cache
* module/filesystem: Rebuilding cache
* module/xbacklight: Rebuilding cache
* module/volume: Rebuilding cache
* module/xkeyboard: Rebuilding cache
* module/memory: Rebuilding cache
* module/cpu: Rebuilding cache
* module/wlan: Rebuilding cache
* module/wlanip: Rebuilding cache
* module/eth: Rebuilding cache
* module/battery: Rebuilding cache
* module/temperature: Rebuilding cache
* module/date: Rebuilding cache
* module/powermenu: Rebuilding cache
* Redrawing bar window
warn: Dropping unmatched character  (U+f17c)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e21a)
warn: Dropping unmatched character  (U+e619)
warn: Dropping unmatched character  (U+e21a)
warn: Dropping unmatched character  (U+e23a)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
* Redrawing bar window
warn: Dropping unmatched character  (U+f17c)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e21a)
warn: Dropping unmatched character  (U+e619)
warn: Dropping unmatched character  (U+e21a)
warn: Dropping unmatched character  (U+e23a)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
* module/temperature: Rebuilding cache
* module/memory: Rebuilding cache
* module/cpu: Rebuilding cache
* module/temperature: Rebuilding cache
* Redrawing bar window
warn: Dropping unmatched character  (U+f17c)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e21a)
warn: Dropping unmatched character  (U+e619)
warn: Dropping unmatched character  (U+e21a)
warn: Dropping unmatched character  (U+e23a)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
* module/wlan: Rebuilding cache
* module/wlanip: Rebuilding cache
* module/eth: Rebuilding cache
* module/temperature: Rebuilding cache
* Redrawing bar window
warn: Dropping unmatched character  (U+f17c)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e21a)
warn: Dropping unmatched character  (U+e619)
warn: Dropping unmatched character  (U+e21a)
warn: Dropping unmatched character  (U+e23a)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
* module/memory: Rebuilding cache
* module/cpu: Rebuilding cache
* module/temperature: Rebuilding cache
* Redrawing bar window
warn: Dropping unmatched character  (U+f17c)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e21a)
warn: Dropping unmatched character  (U+e619)
warn: Dropping unmatched character  (U+e21a)
warn: Dropping unmatched character  (U+e23a)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
* module/temperature: Rebuilding cache
* module/battery: Polling values (inotify fallback)
* module/memory: Rebuilding cache
* module/cpu: Rebuilding cache
* module/wlan: Rebuilding cache
* module/wlanip: Rebuilding cache
* module/eth: Rebuilding cache
* module/temperature: Rebuilding cache
* Redrawing bar window
warn: Dropping unmatched character  (U+f17c)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e21a)
warn: Dropping unmatched character  (U+e619)
warn: Dropping unmatched character  (U+e21a)
warn: Dropping unmatched character  (U+e23a)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
* module/temperature: Rebuilding cache
* module/memory: Rebuilding cache
* module/cpu: Rebuilding cache
* module/temperature: Rebuilding cache
* module/wlan: Rebuilding cache
* module/wlanip: Rebuilding cache
* module/eth: Rebuilding cache
* module/temperature: Rebuilding cache
* Redrawing bar window
warn: Dropping unmatched character  (U+f17c)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e21a)
warn: Dropping unmatched character  (U+e619)
warn: Dropping unmatched character  (U+e21a)
warn: Dropping unmatched character  (U+e23a)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
warn: Termination signal received, shutting down...
* module/i3: Disconnecting from socket
* module/i3: Stopping
* Deconstruction of module/i3 took 0 ms.
* module/filesystem: Stopping
* Deconstruction of module/filesystem took 0 ms.
* module/xbacklight: Stopping
* Deconstruction of module/xbacklight took 0 ms.
* module/volume: Stopping
* Deconstruction of module/volume took 0 ms.
* module/xkeyboard: Stopping
* Deconstruction of module/xkeyboard took 0 ms.
* module/memory: Stopping
* Deconstruction of module/memory took 0 ms.
* module/cpu: Stopping
* Deconstruction of module/cpu took 0 ms.
* module/wlan: Stopping
* Deconstruction of module/wlan took 0 ms.
* module/wlanip: Stopping
* Deconstruction of module/wlanip took 0 ms.
* module/eth: Stopping
* Deconstruction of module/eth took 0 ms.
* module/battery: Stopping
* Deconstruction of module/battery took 91 ms.
* module/temperature: Stopping
* Deconstruction of module/temperature took 0 ms.
* module/date: Stopping
* Deconstruction of module/date took 0 ms.
* module/powermenu: Stopping
* Deconstruction of module/powermenu took 0 ms.
* Waiting for spawned processes to end
* Reached end of application...

**Comment by patrick96** [comment]
This line tells you that for the "FontAwesome" font "DejaVu" was loaded:
```
Loaded font "FontAwesome:pixelsize=10" (name=DejaVu Sans, offset=1, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
```

It seems you either don't have FontAwesome installed, or it is named differently on your system. You can probably find it like this:
```bash
fc-list | grep -i awesome
```

**Comment by masterfink** [comment]
All of my glyphs are being pulled from DejaVu Nerd Fonts, I just threw in the Font Awesome part to see if it'd make a difference. Even just using DejaVu Nerd Fonts I cannot see glyphs.

**Comment by masterfink** [comment]
Hey guys, I though that Nerd Fonts included all of font awesome, but after I installed ttf-font-awesome from the AUR it works flawlessly now. I hope this helps someone in the future. Thanks!

**Comment by duganchen** [comment]
This uses only NERD fonts (v2.0.0) and should be paste-ready.

    font-0 = RobotoMono Nerd Font:pixelsize=10;1

    [module/xwindow]
    format-prefix = " "

    [module/mpd]
    icon-prev = 
    icon-stop = 
    icon-play = 
    icon-pause = 
    icon-next = 

    [module/cpu]
    format-prefix = " "

    [module/memory]
    format-prefix = " "

    [module/wlan]
    ramp-signal-0 = 
    ramp-signal-1 = 
    ramp-signal-2 = 
    ramp-signal-3 = 
    ramp-signal-4 = 

    [module/eth]
    format-connected-prefix = " "

    [module/date]
    format-prefix = 

    [module/volume]
    format-muted-prefix = " "

    [module/battery]
    format-full-prefix = " "
    ramp-capacity-0 = 
    ramp-capacity-1 = 
    ramp-capacity-2 = 
    animation-charging-0 = 
    animation-charging-1 = 
    animation-charging-2 = 

    [module/temperature]
    ramp-0 = 
    ramp-1 = 
    ramp-2  =

    [module/powermenu]
    label-open = 
    label-close =  cancel

**Comment by defxsec** [comment]
Buenas, estoy tratando de colocar un icono de Nerd Fonts a la polybar en anterior ocasiones solo era de copiar el icono y ponerlo en el archivo de configuración y funcionaba pero ahora no.
![imagen](https://github.com/polybar/polybar/assets/109879632/38723852-1fea-4ccc-8492-d142e3258697)
![imagen](https://github.com/polybar/polybar/assets/109879632/272a5cd0-0f5f-41f8-bb21-326ac504faff)
