### ISSUE TITLE
debian 9 + empty polybar

### ISSUE THREAD

**Issue by dripfeeder** [jaagr/polybar#808]
Hello. debian 9. Collected on the manual, but there is an empty panel. Config is standard. I thought that the standard panel is empty, but on the arch, it is installed with all the elements. Please tell me what I'm doing wrong.
screenshot - https://ibb.co/goQFAm

**Comment by dector** [comment]
@dripfeeder Have you fixed this? What was the solution? I have the same issue now.

**Comment by dector** [comment]
My problem was solved after commenting this line:
```
; font-0 = fixed:pixelsize=10;1
```

**Comment by dector** [comment]
And enabling siji font:
```
sudo mv /etc/fonts/conf.d/70-no-bitmaps.conf /etc/fonts/conf.d/70-no-bitmaps.conf.old
fc-cache -fv
```

[Stolen solution from reddit](https://www.reddit.com/r/unixporn/comments/5iw9cx/anyone_using_polybar/dcabiav/)
