### ISSUE TITLE
polybar-msg restart very slow

### ISSUE THREAD

**Issue by wpovell** [jaagr/polybar#813]
When I run `polybar cmd restart` it can take several seconds to restart, anyone know why this is/if it can be fixed? I've found killing polybar and restarting ends up being faster.

**Comment by patrick96** [comment]
It can be that polybar has to wait for the scripts called from the script modules to finish and that is why it takes this long to restart.
When executing `polybar-msg cmd restart`, does it take a long time to stop the bar or for it to come back?

**Comment by wpovell** [comment]
Ah that makes sense. It takes a bit to restart, but comes back quickly once it closes.
