### ISSUE TITLE
warn: "toggle" is not a valid ipc command

### ISSUE THREAD

**Issue by agauniyal** [jaagr/polybar#820]
```
polybar-msg cmd toggle
polybar-msg: Successfully wrote "cmd:toggle" to "/tmp/polybar_mqueue.29438"
```

```
enable-ipc = true
```

😕

**Comment by agauniyal** [comment]
quit works.

**Comment by agauniyal** [comment]
quit works but toggle/show/hide don't. is it something to do with bspwm?

**Comment by patrick96** [comment]
If you look at the output of `polybar` itself on the terminal you will see a message like this:
```
toggle is not a valid ipc command
```
This happens because these features are not in a release yet and you are most likely using polybar `3.0.5`. If you want those features, compile polybar against `master` in this repository

**Comment by agauniyal** [comment]
Yeah I was installing via AUR package 😅

**Comment by patrick96** [comment]
You can install `polybar-git` to always get the latest features (and bugs) ;)
