### ISSUE TITLE
Sticky polybar with bspwm

### ISSUE THREAD

**Issue by agauniyal** [jaagr/polybar#821]
I don't want polybar taking permanent space for itself so I set -
```
override-redirect = true
wm-restack = bspwm
```
in its config file. But I still want it to stay on top of all windows. I tried executing -
```
$ bspc rule -a polybar state=sticky
```
but that did nothing. What should I do next?

**Comment by agauniyal** [comment]
If it sound a bit confusing, what I want is full screen applications but polybar should be at bottom *over* those applications. I've set it translucent so I can see through it as well.

**Comment by patrick96** [comment]
I think `wm-restack = bspwm` causes the bar to NOT be drawn over fullscreen windows. If you remove it, it might work.

**Comment by agauniyal** [comment]
It's not working automatically but if I `pkill polybar` and then launch it manually then it works 😕

**Comment by agauniyal** [comment]
```
[colors]
background = #8a000000
background-alt = #444
foreground = #eee
foreground-alt = #555
primary = #ffb52a
secondary = #e60053
alert = #bd2c40


[bar/example]
width = 100%
height = 25
offset-x = 0
offset-y = 0
underline-size = 0
bottom = true
enable-ipc = true
background = #8a000000
foreground = #eee
line-size = 0
border-size = 0
padding-left = 5
padding-right = 5
module-margin-left = 1
module-margin-right = 2
override-redirect = true

font-0 = Noto Sans:size=8;2
font-1 = FontAwesome:size=8;2

modules-left = date battery
modules-center =
modules-right = volume wlan eth memory cpu temperature


[module/battery]
type = internal/battery
battery = BAT1
adapter = ACAD
full-at = 99
poll-interval = 10

format-charging = <animation-charging>  <label-charging>
format-discharging = <ramp-capacity>  <label-discharging>
format-full = <ramp-capacity>  <label-full>
label-charging = %percentage%
label-discharging = %percentage%
label-full = %percentage%
format-charging-padding = 3
format-discharging-padding = 3
format-full-padding = 3

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750


[module/cpu]
type = internal/cpu
label =   %percentage%%

[module/memory]
type = internal/memory
label =   %percentage_used%%


[module/wlan]
type = internal/network
interface = wlp2s0
interval = 3
format-connected = <label-connected>
label-connected =   %essid% [%signal%] %downspeed:9%


[module/eth]
type = internal/network
interface = enp1s0
interval = 3
label-connected =   %local_ip%


[module/date]
type = internal/date
interval = 60
date = " %Y-%m-%d"
time = %H:%M
label = %date% %time%


[module/volume]
type = internal/volume
format-volume = <ramp-volume>  <label-volume>
format-muted = <label-muted>
label-volume = %percentage%
label-muted =   muted
label-muted-foreground = #aaa
format-volume-padding = 3
format-muted-padding = 3
ramp-volume-0 = 
ramp-headphones-0 = 


[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60
format = <label>
format-warn = <label-warn>
label =  %temperature%
label-warn =  %temperature%
label-warn-foreground = #e60053

[settings]
screenchange-reload = true
```

**Comment by agauniyal** [comment]
```
#! /bin/sh

sxhkd &
compton &

bspc config border_width        1
bspc config window_gap         12
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config history_aware_focus true
bspc config focus_follows_pointer true

bspc config auto_alternate true
bspc config auto_cancel true

bspc config normal_border_color "#2b2b2b"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#121212"
bspc config presel_border_color "#050505"
bspc config urgent_border_color "#010101"

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

bspc rule -a Gnome-terminal state=floating focus=on
bspc rule -a Zeal state=floating focus=on
bspc rule -a qBittorrent state=floating
bspc rule -a nautilus state=floating focus=on
bspc rule -a polybar state=sticky

bspc monitor -d I II III IV

~/.config/polybar/launch.sh
```

**Comment by agauniyal** [comment]
```
dbus-update-activation-environment --all
xrandr --dpi 100
xsetroot -cursor_name left_ptr
setxkbmap -option caps:escape
export _JAVA_AWT_WM_NONREPARENTING=1
redshift &
sh ~/.fehbg &
exec bspwm
```

**Comment by agauniyal** [comment]
```
#!/usr/bin/env sh

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar example &
```

**Comment by agauniyal** [comment]
Should I post anything else than polybar `config`, `bspwmrc`, `.xinitrc` and contents of `launch.json`?

**Comment by patrick96** [comment]
Try setting `override-redirect` to false

**Comment by agauniyal** [comment]
With
```
override-redirect = true
wm-restack = bspwm
```
and
```
override-redirect = true
```
The result is same that polybar doesn't takes space for itself but hides behind other windows(which are not even full screen, eg. floating). I don't want it to hide here, should be at top.

With
```
override-redirect = false
wm-restack = bspwm
```
and
```
override-redirect = false
```
it takes space for itself and doesn't let other windows take that space(even after it exits) which I don't want.

**Comment by patrick96** [comment]
According to the `bspc` manpage there is no `sticky` state, only a `sticky` mode. Try
```
bspc rule -a polybar sticky=on
```

**Comment by agauniyal** [comment]
Oops, corrected that but it has exactly same behavior for all 4 cases :(

**Comment by agauniyal** [comment]
Here's a screenshot of what I want -
![2017-10-28-190437_1366x768_scrot](https://user-images.githubusercontent.com/7630575/32134810-94e6444c-bc12-11e7-9361-eb43b325f8e4.png) and it's working well if I kill and manually launch the bar. so close man 😆

**Comment by neeasade** [comment]
> it's working well if I kill and manually launch the bar

try prefixing your launch command with `setsid `

**Comment by agauniyal** [comment]
@neeasade thanks 👍  but it doesn't work as well :(

**Comment by msteen** [comment]
Just some ideas:

I am using the `bspwm` loop example, such that I can reset not only my rules, but e.g. my settings as well, but this caused my programs started in my `bspwmrc` script to also be killed, to prevent this I had to do:
`( setsid <your_command> & )`. See [this comment](https://superuser.com/questions/172043/how-do-i-fork-a-process-that-doesnt-die-when-shell-exits#172476) for an explanation.

You could also try using `xdo`, e.g. `xdo raise -N polybar` or something like this:
```
for wid in $(xdo id -n root); do
  xdo below -N polybar -t $wid
done
```

**Comment by agauniyal** [comment]
@msteen my polybar (started from bspwmrc) is not getting killed. It's just that it doesn't follows the rules when started from inside it or something weird is happening that I don't understand. I'm currently launching the bar manually after each reboot since I really want this thing to work. I'll try `xdo` thing 👍 thanks!

**Comment by msteen** [comment]
@agauniyal I know, I just mentioned it because @neeasade thought it might be relevant and for me just doing `setsid` was not enough to get the behavior I wanted in that context.

It does not follow the rules because docks are [not managed](https://github.com/baskerville/bspwm/blob/49caeb8ce8efdb0f4e82f52bc98b327b6049d776/src/rule.c#L196) by `bspwm`, of which polybar is one, so the rules do not apply.

My above example doing `xdo below ...` was wrong, since I just checked, I am calling it with `above` with the result of my bar always being visible, except when windows are in fullscreen. I just tested it with `xdo raise` and then it will overlap the fullscreen windows, which is the behavior you want, right? The best way to call `xdo` for your bar is within the external rules, e.g. with a script like this:
```
#!/usr/bin/env bash

wid=$1
class=$2
instance=$3

if [[ "$instance" == polybar ]]; then
  # For my lemonbar calling raise is enough, but if not, you might also have to run this:
  # xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $wid
  xdo raise $wid
fi
```
Others also use a sleep loop to get the window id of the bar, but I prefer to use external rules instead of polling for it to be ready.

**Comment by samurosales** [comment]
> @agauniyal I know, I just mentioned it because @neeasade thought it might be relevant and for me just doing `setsid` was not enough to get the behavior I wanted in that context.
> 
> It does not follow the rules because docks are [not managed](https://github.com/baskerville/bspwm/blob/49caeb8ce8efdb0f4e82f52bc98b327b6049d776/src/rule.c#L196) by `bspwm`, of which polybar is one, so the rules do not apply.
> 
> My above example doing `xdo below ...` was wrong, since I just checked, I am calling it with `above` with the result of my bar always being visible, except when windows are in fullscreen. I just tested it with `xdo raise` and then it will overlap the fullscreen windows, which is the behavior you want, right? The best way to call `xdo` for your bar is within the external rules, e.g. with a script like this:
> 
> ```
> #!/usr/bin/env bash
> 
> wid=$1
> class=$2
> instance=$3
> 
> if [[ "$instance" == polybar ]]; then
>   # For my lemonbar calling raise is enough, but if not, you might also have to run this:
>   # xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $wid
>   xdo raise $wid
> fi
> ```
> 
> Others also use a sleep loop to get the window id of the bar, but I prefer to use external rules instead of polling for it to be ready.

hi, I'm trying to do the same, but I am new to this, where should i use this script?
its on .bashrc or launch.sh, sorry if my question is too stupid but as i already told, I'm a noob.

**Comment by msteen** [comment]
@samurosales You should look at the `external_rules_command` global setting. So you should set it to point to a script containing the snippet. Good luck!

**Comment by victornecromancer** [comment]
@msteen  I'm with the same problem, tried `xdo raise` and it finally worked. Thanks a lot man, you are my hero xd
