### ISSUE TITLE
Sway workspaces module

### ISSUE THREAD

**Issue by spjz** [jaagr/polybar#827]
I'm unable to find any info about getting Polybar to recognise the [Sway](https://wiki.archlinux.org/index.php/Sway) workspaces due to an incompatibility with the i3 module.

```sh: i3: command not found error: Disabling module "i3" (reason: Could not find socket: <empty>)```

**Comment by spjz** [comment]
Thanks for the response! This results in another error, but I may be able to solve it:

```error: module/i3: Failed to parse reply on "GET_WORKSPACES": root expected to be an array```

Seems swaysmg -s $SWAYSOCK get_workspaces returns a json encoded list of workspaces and their statuses, but using this as the i3 script returns another error (because the sway socket is undefined):

```error: Disabling module "i3" (reason: Could not find socket: [
   {
     "success": false,
     "input": "get_workspaces",
     "error": "Unknown\/invalid command"
   }```

You can identify the socket while sway is running with sway --get-socketpath, but substituting this in the place of $SWAYSOCK produces the same error.

**Comment by spjz** [comment]
Getting closer, I've found that if in ```/usr/local/bin/i3``` you put:

```swaymsg --socket $(sway --get-socketpath) -t get_workspaces ```

You get the response:

```
error: Disabling module "i3" (reason: Could not find socket: [
   {
     "id": 2,
     "name": "1",
     "rect": {
       "x": 0,
       "y": 0,
       "width": 800,
       "height": 480
     },
     "visible": true,
     "border": "none",
     "window_rect": {
       "x": 0,
       "y": 0,
       "width": 0,
       "height": 0
     },
     "deco_rect": {
       "x": 0,
       "y": 0,
       "width": 0,
       "height": 0
     },
     "geometry": {
       "x": 0,
       "y": 0,
       "width": 0,
       "height": 0
     },
     "percent": null,
     "window": -1,
     "urgent": false,
     "current_border_width": 0,
     "num": 1,
     "output": "WLC-1",
     "type": "workspace",
     "layout": "splith",
     "focused": true
   }
 ]
)

```

**Comment by rvc-2011** [comment]
In a way, partially [not 100% as in i3 module] achieved.
i created 2 shell scripts [one for active workspace, another for total focusedworkscapce] by calling command swaymsg -t get_workspaces | grep name & | grep focused

i then created 2 modules for active and focused workspaces and used the output from the script to display. only issue is the (hidden) wokspaces + active workspace is all shown in the focused and hence i used active workspace to highlight current workspace. may be a temperary arrangement done, but then it just works and suffices my requirement. looking for a "sway" module in polybar !
preview of my screenshot is here => https://www.dropbox.com/s/nyw8e06wop14xn0/swayPRN.png?dl=0

**Comment by mattlyons0** [comment]
@rvc-2011 would you be willing to post some of your dotfiles (and the sway scripts you wrote)? I really like how you themed polybar to work nicely with gaps.

(I noticed you have a dotfiles repo but it seems out of date based on what you have in the screenshot)

**Comment by patrick96** [comment]
Polybar only uses the `i3` executable to figure out where the i3 socket is, after that all communication is done via that socket, so it doesn't make sense to somehow fix the `get_workspaces` issue by changing the executable. The solution jaagr proposed works. The `Failed to parse reply on "GET_WORKSPACES": root expected to be an array` error means that sway doesn't seem to be a true drop-in replacement for i3, since it doesn't behave the same way when interacted with via the socket.

I'm going to close this, since this is not really a polybar issue.
