### ISSUE TITLE
Polybar restart loses tray icons

### ISSUE THREAD

**Issue by spurgelaurels** [jaagr/polybar#828]
When restarting polybar to take on a new config or colour scheme, the tray icons vanish.  Restarting the tray services themselves replaces the icons, but this is a cumbersome workaround.  

Apps that have vanished:  slack, nm-applet, remmina.  No other apps tested.
The processes are still running, polybar just loses track of them.

**Comment by jaagr** [comment]
How are you restarting polybar?

**Comment by spurgelaurels** [comment]
killall

**Comment by Lourens-Rich** [comment]
Example:
![screenshot_2017-11-02_22-18-30](https://user-images.githubusercontent.com/22860367/32345540-8d1f8716-c01b-11e7-87bc-7969df1a8b2f.png)
For restart and launch polybar using this script:
```
#!/usr/bin/env sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch bar1 and bar2
polybar example &
```

**Comment by spurgelaurels** [comment]
That did it!  I'm going to guess that whatever is handling the list of apps in the tray still thinks the old process is using them, and doesn't let the new process take over.
