### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by Skinderfire** [jaagr/polybar#830]
[benjamin@benjamin-pc build]$ sudo make install
Scanning dependencies of target xpp
[  1%] Linking CXX static library libxpp.a
list: size, ['red', 'green', 'blue']
list: size, ['red', 'green', 'blue']
[  1%] Built target xpp
Scanning dependencies of target i3ipc++
[  2%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o
In file included from /home/benjamin/polybar/lib/i3ipcpp/src/ipc.cpp:9:0:
/home/benjamin/polybar/lib/i3ipcpp/include/i3ipc++/ipc-util.hpp:147:57: error: les spécifications dynamiques d'exceptions sont dépréciées en C++11 [-Werror=deprecated]
 std::shared_ptr<buf_t>   i3_recv(const int32_t  sockfd) throw (invalid_header_error, eof_error);
                                                         ^~~~~
In file included from /home/benjamin/polybar/lib/i3ipcpp/src/ipc.cpp:9:0:
/home/benjamin/polybar/lib/i3ipcpp/include/i3ipc++/ipc-util.hpp:163:131: error: les spécifications dynamiques d'exceptions sont dépréciées en C++11 [-Werror=deprecated]
 fd, const ClientMessageType  type, const std::string&  payload = std::string()) throw (invalid_header_error, eof_error);
                                                                                 ^~~~~
cc1plus : tous les avertissements sont traités comme des erreurs
make[2]: *** [lib/i3ipcpp/CMakeFiles/i3ipc++.dir/build.make:63: lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:440: lib/i3ipcpp/CMakeFiles/i3ipc++.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by patrick96** [comment]
Try to compile with clang. See the end of the Compiling page on the wiki for instructions:
https://github.com/jaagr/polybar/wiki/Compiling

**Comment by Skinderfire** [comment]
Thank you, it works !
