### ISSUE TITLE
polybar not installing in freshly installed manjaro i3

### ISSUE THREAD

**Issue by shahules** [jaagr/polybar#832]
i used yaourt package manager to install polybar and it gives the below errors;
```
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build polybar
can you please help
```

**Comment by patrick96** [comment]
Is this the only output you get when you try to build it?
Can you try to built it without `yaourt`, using `makepkg` and post the output of that?

**Comment by shahules** [comment]
i tried  using cmake and steps shown in this page
https://github.com/jaagr/polybar
but i gets below  errors;
[  1%] Built target xpp
[  2%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o
In file included from /home/shahules786/polybar/lib/i3ipcpp/src/ipc.cpp:9:0:
/home/shahules786/polybar/lib/i3ipcpp/include/i3ipc++/ipc-util.hpp:147:57: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 std::shared_ptr<buf_t>   i3_recv(const int32_t  sockfd) throw (invalid_header_error, eof_error);
                                                         ^~~~~
In file included from /home/shahules786/polybar/lib/i3ipcpp/src/ipc.cpp:9:0:
/home/shahules786/polybar/lib/i3ipcpp/include/i3ipc++/ipc-util.hpp:163:131: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 tMessageType  type, const std::string&  payload = std::string()) throw (invalid_header_error, eof_error);
                                                                  ^~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [lib/i3ipcpp/CMakeFiles/i3ipc++.dir/build.make:63: lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:440: lib/i3ipcpp/CMakeFiles/i3ipc++.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by shahules** [comment]
i tried  using cmake and steps shown in this page
https://github.com/jaagr/polybar
but i gets below  errors;
[  1%] Built target xpp
[  2%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o
In file included from /home/shahules786/polybar/lib/i3ipcpp/src/ipc.cpp:9:0:
/home/shahules786/polybar/lib/i3ipcpp/include/i3ipc++/ipc-util.hpp:147:57: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 std::shared_ptr<buf_t>   i3_recv(const int32_t  sockfd) throw (invalid_header_error, eof_error);
                                                         ^~~~~
In file included from /home/shahules786/polybar/lib/i3ipcpp/src/ipc.cpp:9:0:
/home/shahules786/polybar/lib/i3ipcpp/include/i3ipc++/ipc-util.hpp:163:131: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 tMessageType  type, const std::string&  payload = std::string()) throw (invalid_header_error, eof_error);
                                                                  ^~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [lib/i3ipcpp/CMakeFiles/i3ipc++.dir/build.make:63: lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:440: lib/i3ipcpp/CMakeFiles/i3ipc++.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by patrick96** [comment]
This is a know issue when compiling version 3.0.5, either use `polybar-git` or compile with `clang`.
To compile with clang, either install clang and run yaourt again (you may have to clean the yaourt cache for polybar) or install clang and install it manually with
```
cmake -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" ..
```

**Comment by shahules** [comment]
can you please tell me how to clean my polybar cache and reinstall polybar.Am not very familiar with this.

**Comment by patrick96** [comment]
Hmm, it seems, with yaourt you don’t need to clean the cache, you can just install `clang` and the install polybar using yaourt

**Comment by shahules** [comment]
i tried to install `clang` using `yaourt`,but it shows that the package is already installed in my system.

**Comment by patrick96** [comment]
Okey, it seems installing through yaourt does not work for you. You'll have to compile it yourself, for that follow the instructions [here](https://github.com/jaagr/polybar/wiki/Compiling#building), but use
```bash
cmake -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" ..
```
instead of just `cmake ..`.

**Comment by shahules** [comment]
Thank you 😊
