### ISSUE TITLE
What kind of alsa?

### ISSUE THREAD

**Issue by i-panov** [jaagr/polybar#833]
I'm trying to install a polybar with i3wm under linux mint. But at assembly writes that the library of an `alsa` is not found. What is this library and how to install it? I could not find her anywhere.

P.S. It would be nice to list all dependencies in readme. So you don't have to figure it out yourself.

**Comment by patrick96** [comment]
All that information is already available on the [Wiki](https://github.com/jaagr/polybar/wiki/Compiling)
