### ISSUE TITLE
xbacklight does not set the correct output

### ISSUE THREAD

**Issue by He-Ro** [jaagr/polybar#834]
Hello I have been having issues with the module `xbacklight`. When I have only my laptop screen and no additional monitor connected, then it works as expected.
But even then I get the message `No monitor specified, using "eDP1"`, even though I have this line `monitor = eDP1` in my config under the `xbacklight` section.
Now when I connect a external monitor the `xbacklight` module does not show up because it is picking `HDMI2` as the output and for that output I cannot change the backlight.
So it seems like there is a problem with my configuration, my laptop, the xbacklight module's handling of the output or the documentation of xbacklight in the wiki.

I saw #712 and thus included some information, that was also requested there:
[config](https://ptpb.pw/cpLG)
Before plugging in external monitor: [log](https://ptpb.pw/pdir)
After plugging in external monitor and configuring it with xrandr: [log](https://ptpb.pw/H-ki)

**Comment by patrick96** [comment]
It seems like you mixed some things up. The  `output` settings is supposed to be in the xbacklight section and the `monitor` and `monitor-strict` settings are supposed to be in the bar section

**Comment by He-Ro** [comment]
Wow, I must have played around with the config too much. But now I see even stranger behaviour:
When I do not have an external monitor plugged in I get a working bar at first: [log](https://ptpb.pw/jnpX).
Then I terminate the polybar command, plug in my external monitor and run the following command `xrandr --output HDMI2 --auto --output eDP1 --auto --right-of HDMI2 --primary`. Now I run polybar again, and it works as expected, the bar only gets shown on my laptop monitor and not on the external monitor and the backlight value is correct as well ([log](https://ptpb.pw/N7X9)). Then again I terminate polybar and then I issue the following command `xrandr --output HDMI2 --off --output VIRTUAL1 --off --output eDP1 --auto`. After that I try to run polybar again, but now it terminates with the following [log](https://ptpb.pw/j6WI).
[config](https://ptpb.pw/TioL)

**Comment by He-Ro** [comment]
Okay I think I found the culprit, `xrandr --prop` shows the following after having the external monitor enabled and disabled several times:
```
Screen 0: minimum 8 x 8, current 3840 x 1080, maximum 32767 x 32767
eDP1 connected primary 1920x1080+1920+0 (normal left inverted right x axis y axis) 310mm x 170mm
	EDID: 
		00ffffffffffff000daeb11400000000
		0c190104951f117802ff359255529529
		25505400000001010101010101010101
		010101010101b43b804a71383440503c
		680034ad10000018000000fe004e3134
		304843452d4541410a20000000fe0043
		4d4e0a202020202020202020000000fe
		004e3134304843452d4541410a2000a2
	scaling mode: Full aspect 
		supported: Full, Center, Full aspect
	Broadcast RGB: Automatic 
		supported: Automatic, Full, Limited 16:235
	audio: auto 
		supported: force-dvi, off, auto, on
	link-status: Good 
		supported: Good, Bad
   1920x1080     60.01*+
   1400x1050     59.98  
   1600x900      60.00  
   1280x1024     60.02  
   1280x960      60.00  
   1368x768      60.00  
   1280x720      60.00  
   1024x768      60.00  
   1024x576      60.00  
   960x540       60.00  
   800x600       60.32    56.25  
   864x486       60.00  
   640x480       59.94  
   720x405       60.00  
   640x360       60.00  
DP1 disconnected (normal left inverted right x axis y axis)
	Broadcast RGB: Automatic 
		supported: Automatic, Full, Limited 16:235
	audio: auto 
		supported: force-dvi, off, auto, on
	link-status: Good 
		supported: Good, Bad
DP2 disconnected (normal left inverted right x axis y axis)
	Broadcast RGB: Automatic 
		supported: Automatic, Full, Limited 16:235
	audio: auto 
		supported: force-dvi, off, auto, on
	link-status: Good 
		supported: Good, Bad
HDMI1 disconnected (normal left inverted right x axis y axis)
	aspect ratio: Automatic 
		supported: Automatic, 4:3, 16:9
	Broadcast RGB: Automatic 
		supported: Automatic, Full, Limited 16:235
	audio: auto 
		supported: force-dvi, off, auto, on
	link-status: Good 
		supported: Good, Bad
HDMI2 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 530mm x 300mm
	EDID: 
		00ffffffffffff004c2d3a0a35323330
		2417010380351e782af711a3564f9e28
		0f5054bfef80714f81c0810081809500
		a9c0b3000101023a801871382d40582c
		4500132b2100001e011d007251d01e20
		6e285500132b2100001e000000fd0032
		4b1e5111000a202020202020000000fc
		00533234433335300a20202020200118
		02031af14690041f1303122309070783
		01000066030c00100080011d00bc52d0
		1e20b8285540132b2100001e8c0ad090
		204031200c405500132b210000188c0a
		d08a20e02d10103e9600132b21000018
		00000000000000000000000000000000
		00000000000000000000000000000000
		00000000000000000000000000000099
	aspect ratio: Automatic 
		supported: Automatic, 4:3, 16:9
	Broadcast RGB: Automatic 
		supported: Automatic, Full, Limited 16:235
	audio: auto 
		supported: force-dvi, off, auto, on
	link-status: Good 
		supported: Good, Bad
   1920x1080     60.00*+  50.00    59.94  
   1680x1050     59.88  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1440x900      59.90  
   1280x800      59.91  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    72.81    66.67    60.00    59.94  
   720x400       70.08  
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```
Notice, that `Backlight` is missing from the properties of `eDP1`. So I am guessing, that `polybar` relies on this. Do you know where I can report this?

OS: Arch Linux
Laptop: Lenovo ThinkPad T460

**Comment by He-Ro** [comment]
It seems to be an Xorg error, so I am closing this.
```
[   107.453] (II) intel(0): switch to mode 1920x1080@60.0 on eDP1 using pipe 0, position (0, 0), rotation normal, reflection none
[   108.503] (EE) intel(0): Failed to set backlight intel_backlight for output eDP1, disabling
```
