### ISSUE TITLE
xinerama support?

### ISSUE THREAD

**Issue by madnight** [jaagr/polybar#835]
```
xrandr 
RandR extension missing

polybar --list-monitors
zsh: segmentation fault (core dumped)  polybar --list-monitors
```

**Comment by NBonaparte** [comment]
What is the question? Are you requesting xinerama support or simply whether if it is supported?

**Comment by madnight** [comment]
I want to know wether it is supported or if there is a workaround to get polybar working without xrandr

**Comment by patrick96** [comment]
Sorry for the late response. There is no xinerama support in polybar. There is also no way around the randr extension
