### ISSUE TITLE
Mixing different module types

### ISSUE THREAD

**Issue by throwup** [jaagr/polybar#838]
Is there any way to mix different types of modules into one module?
I would like to use the functionality of, for example, module/network, but also add extras with module/script.

I am able to reproduce the functionality of the network module with custom scripting, so this is in no way an pressing issue, however I still would like to know if something like this is possible.

**Comment by NBonaparte** [comment]
No, this is not possible.

**Comment by throwup** [comment]
Ok, thats good to hear. 
So I suppose full custom shell scripting via module/script would be the correct option, right?

**Comment by NBonaparte** [comment]
Yeah, that is the only way to do it.

**Comment by throwup** [comment]
Great, thanks for the quick replies!
