### ISSUE TITLE
bspwm, mpd and font issue

### ISSUE THREAD

**Issue by Genesis131** [jaagr/polybar#843]
Hi,

First of all, please excuse my English it's not my mother tongue.

I just installed Arch and polybar but when I start the example bar I have this : 

> error: Disabling module "bspwm" (reason: Could not find socket: /tmp/bspwm_0_0-socket)
error: module/mpd: Connection refused
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e19c)
warn: Dropping unmatched character  (U+e23a)
warn: Dropping unmatched character  (U+e0cb)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
>

Could anyone help me ? :) 

Thanks

**Comment by NBonaparte** [comment]
I'm guessing you're not running bspwm and mpd, so you can remove those modules from the config. You don't have the default icon font (Siji) installed, so install it, or remove/replace the characters.

**Comment by Genesis131** [comment]
Well thanks it worked ! I changed the icon font because Siji wouldn't work and I disabled the modules.
Thanks a lot !
