### ISSUE TITLE
i3 workspace icons not aligned

### ISSUE THREAD

**Issue by Fenwick17** [jaagr/polybar#847]
As part of my polybar I have a section for my workspaces, I am using `pin-workspaces` to keep them unique to each monitor. 
However I have noticed that the number inside is off center, and seems to be a bit to the right and cant figure out what the cause of this is.
https://github.com/Fenwick17/dotfiles/blob/master/polybar/config
I have tried different fonts but all have the same issue.
An [image](https://imgur.com/a/TyLGk) of the issue

**Comment by patrick96** [comment]
This is because the default label for the workspaces is `%icon% %name%`, and because you did not define the icons, the label now has an extra space on the left. You can solve this by setting following in your i3 module:
```dosini
label-focused = %name%
label-unfocused = %name%
label-visible = %name%
label-urgent = %name%
```
