### ISSUE TITLE
missing  curlbuild.h when building with build.sh

### ISSUE THREAD

**Issue by Simbaclaws** [jaagr/polybar#848]
I'm getting the same error as #698 
Has the issue with curlbuild.h been fixed in the build.sh script aswell? 

Because I'm using that to build with all the options.

**Comment by patrick96** [comment]
Yes, if you use the latest commit and not version 3.0.5, the build.sh script will work.

**Comment by Simbaclaws** [comment]
Sorry my bad, I didn't notice I was branching off 3.0.5
