### ISSUE TITLE
Droping unmatched characters

### ISSUE THREAD

**Issue by koxu1996** [jaagr/polybar#849]
At first, sorry for creating yet another issue about glyphicons, but it's really look like there is a problem with polybar. When I run it, there are any icons and there is a lot of warnings:

```
...
* Loaded font "Hack:fontformat=truetype:size=12" (name=Hack, offset=1, file=/usr/share/fonts/TTF/Hack-Regular.ttf)
* Loaded font "FontAwesome:fontformat=truetype:size=13" (name=FontAwesome, offset=0, file=/usr/share/fonts/TTF/fontawesome-webfont.ttf)
...
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e19c)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e19c)
warn: Dropping unmatched character  (U+e016)
...

```

This is my font configuration:

```
font-0 = Hack:fontformat=truetype:size=12;1
font-1 = FontAwesome:fontformat=truetype:size=13;0
```

_fc-match_ output for these fonts:

```
$ fc-match Hack
Hack-Regular.ttf: "Hack" "Regular"
$ fc-match FontAwesome
fontawesome-webfont.ttf: "FontAwesome" "Regular"
```

### Additional informations
Polybar: 3.0.5
OS: Arch Linux x64

**Comment by patrick96** [comment]
The characters that you are using in your bar, are characters that are not provided by the fonts you specified. That's why that warning appears.
Please see the wiki page on [`gucharmap`](https://github.com/jaagr/polybar/wiki/Fonts#gnome-character-map) for information on how to locate glyphicons for the fonts you specified.

**Comment by koxu1996** [comment]
I used gucharmap to copy 'bug' character:
[img](https://i.imgur.com/C6x45FI.png)

Then inserted it under cpu module
```
[module/cpu]
format-prefix = ""
...
```

After running polybar there is no icon:
[img](https://i.imgur.com/3BPHm4t.png)
And warning with new character appear:
warn: Dropping unmatched character  (U+e269)

**Comment by patrick96** [comment]
Did you select `View` > `Show only glyphs from this font`? The only "bug" character in FontAwesome is at `U+F188`

**Comment by koxu1996** [comment]
My bad, I didn't select it. After choosing correct "bug" icon, it appeared :) Thank you for help :+1: 
BTW I think example config was not working for me, because I disabled bitmap fonts and there was characters from Siji, which is bitmap one.
