### ISSUE TITLE
font-size error in xwindows

### ISSUE THREAD

**Issue by sansroman** [jaagr/polybar#850]
when title have some chinese characters,font size too small.why? Is my system config error or i3wm config error?

left-top:
![2017-11-17-143853_1920x1080_scrot](https://user-images.githubusercontent.com/17476682/32933910-e528eaa2-cba5-11e7-8ca4-0f518f7846e9.png)

my config
```
font-0 = WenQuanYi Zen Hei Mono:pixelsize=12;3
font-1 = unifont:size=6:heavy:fontformat=truetype;-2
font-2 = siji:pixelsize=10;0
font-3 = FontAwesome:pixelsize=14;0


 [module/xwindow]
type = internal/xwindow
label = "   %{F#5b5b5b}%{F-} %title:0:70:...%"
```

**Comment by patrick96** [comment]
I'm assuming that `WenQuanYi Zen Hei Mono` is providing the chinese characters. Try to increase the `pixelsize` value and mabye also add the `size` attribute to the font specifier and play around with it

**Comment by sansroman** [comment]
thanks a lot.
