### ISSUE TITLE
New release - 3.0.6?

### ISSUE THREAD

**Issue by andir** [jaagr/polybar#856]
Whats the plan on having another release?

Looking at the diff since the last release (https://github.com/jaagr/polybar/compare/3.0.5...master) there have been quite a few bug fixes that would nicely fit into another release. :-)

Also, NixOS is currently working on switching to gcc7 (https://github.com/NixOS/nixpkgs/issues/31747) where polybar currently fails building due to missing patches in the latest version.

**Comment by patrick96** [comment]
As you can see the [3.1.0 Milestone](https://github.com/jaagr/polybar/milestone/1) is actually done. We just haven't come around to drafting a PR with all the changes required to finish a release. I'll try to open up a PR today with some initial things, just to get the ball roling.
