### ISSUE TITLE
bar apperance

### ISSUE THREAD

**Issue by INTRCPTR** [jaagr/polybar#859]
Hi just starting off by complimenting you on such a great piece of software. Now i'm using i3wm-gaps. I pulled your example config of dracula. The colors are right on, but what i'm having trouble is having my bar thinner then the modules which would give the special look of my modules standing out. Maybe it's a i3wm thing, not sure. My bar is all the same height. Any info that you guys need I will supply. hope to hear soon, thanks
![poly1](https://user-images.githubusercontent.com/29486373/33226649-8799c6e6-d158-11e7-8afb-c336ffdbf6fc.png)

**Comment by NBonaparte** [comment]
Try playing around with vertical offset in the font properties:
```
; font-N = <fontconfig pattern>;<vertical offset>
```
(see https://github.com/jaagr/polybar/wiki/Fonts for more info)

**Comment by patrick96** [comment]
Can you point us to where you got that config

**Comment by INTRCPTR** [comment]
https://github.com/jaagr/dots/tree/master/.local/etc/themer/themes
the example is dracula, I have tried playing with the offset except the only i can get to happen is my text goes too far down and is not displayed.

**Comment by patrick96** [comment]
It seems someone else asked this question as well in #949. The answer I gave over there was that this was probably done with a second slimmer bar that was placed underneath.
