### ISSUE TITLE
Change output on click

### ISSUE THREAD

**Issue by tobiasbrummer** [jaagr/polybar#864]
Hi, 
I'm trying to set up a script to get both my batterys in on module. As far as I can tell the script is working as intended but I'm not able to switch the output on click. I'd like to have three states, one default for both batterys and two for the batterys alone which I can activate per click. Isn't it possible to change the output per click? I attached the script and the module code.
Thanks in advcane.
Tobias

Battery script

```
#!/usr/bin/env bash

# Batteriedaten per tlp-stat abfragen

function bat0_charge {
        sudo tlp-stat -b | head -n 21 | tail -1 | tr -d -c "[:digit:],." | cut -f
 1 -d "%" | tr . ,
}

function bat0_charge_for_total {
        sudo tlp-stat -b | head -n 21 | tail -1 | tr -d -c "[:digit:],." | cut -f
 1 -d "%"
}

function bat0_status {
        sudo tlp-stat -b | head -n 15 | tail -1 | cut -f 2 -d "=" | sed "s/ //g"
}

function bat1_charge {
        sudo tlp-stat -b | head -n 38 | tail -1 | tr -d -c "[:digit:],." | cut -f
 1 -d "%" | tr . ,
}

function bat1_charge_for_total {
        sudo tlp-stat -b | head -n 38 | tail -1 | tr -d -c "[:digit:],." | cut -f
 1 -d "%"
}

function bat1_status {
        sudo tlp-stat -b | head -n 32 | tail -1 | cut -f 2 -d "=" | sed "s/ //g"
}

# Berechnung Batteriestand
function total_charge {
        bc -l <<< "scale=4; ($(bat0_charge_for_total)+$(bat1_charge_for_total))/2
" | tr . ,
}

# Konvertierung Batteriestand

function total_charge_convert {
        printf "%.*f\n" 0 $(total_charge)
}

# Farbdefinitionen

if [ $(bat0_status) = 'Charging' ]
then
        bat0_color='#519f50'
elif [ $(bat0_status) = 'Discharging' ]
then
        bat0_color='#da4939'
else
        bat0_color='#e6e6e6'
fi

if [ $(bat1_status) = 'Charging' ]
then
        bat1_color='#519f50'
elif [ $(bat1_status) = 'Discharging' ]
then
        bat1_color='#da4939'
else
        bat1_color='#e6e6e6'
fi


if [ $(bat0_status) = 'Charging' ] || [ $(bat1_status) = 'Charging' ]
then
        total_color='#519f50'
elif [ $(bat0_status) = 'Discharging' ] || [ $(bat1_status) = 'Discharging' ]
then
        total_color='#da4939'
else
        total_color='#e6e6e6'
fi
# Reaktion auf CLI Parameter

case "$1" in
        --bat0)
                (echo "%{F$bat0_color}BAT0 "; printf "%.*f\n" 0 $(bat0_charge); e
cho "%%{F-}") | tr -d "\n"

                ;;
        --bat1)
                (echo "%{F$bat1_color}BAT1 "; printf "%.*f\n" 0 $(bat1_charge); e
cho "%%{F-}") | tr -d "\n"
                ;;
        *)
                if [ $(total_charge_convert) -lt 10 ]
                then
                        (echo "%{F#3a3a3a}B%{F-}%{O3}%{F#181818}00%{F-}%{F$total_
color}"; printf "%.*f\n" 0 $(total_charge); echo "%%{F-}") | tr -d "\n"
                elif [ $(total_charge_convert) -lt 100 ]
                then
                        (echo "%{F#3a3a3a}B%{F-}%{O3}%{F#181819}0%{F-}%{F$total_c
olor}"; printf "%.*f\n" 0 $(total_charge); echo "%%{F-}") | tr -d "\n"
                else
                        (echo "%{F#3a3a3a}B%{F-}%{O3}%{F$total_color}"; printf "%
.*f\n" 0 $(total_charge); echo "%%{F-}") | tr -d "\n"
                fi
                ;;
esac
```

Module code
```
[module/battery]
type = custom/script
exec = ~/.config/polybar/bat.sh
format = <label>
interval = 30

label = %output%
label-foreground = ${colors.foreground}

click-left = ~/.config/polybar/bat.sh
click-middle = ~/.config/polybar/bat.sh --bat0
click-right = ~/.config/polybar/bat.sh --bat1
```

**Comment by TheSupport101** [comment]
Hello. One way I can think of to go around that issue is to have a variable for the state. Let's say STATE=0, somewhere at the top. On the --bat0 case you'd have a sed that changed STATE=0 to STATE=1 and somewhere else on the script there'd be an if statement evaluating the value of STATE. If STATE is 1, whatever output you defined for case --bat0 would run. If it's 0, the default output would appear and if it's 2 the --bat1 output would.

The click actions and the associated cases would simply change the value of STATE, and on the next run (every 30 seconds by your config) the output would depend on whether STATE is 0, 1 or 2.

I hope this isn't too convoluted, I used a similar approach on [this](https://github.com/TheSupport101/music_plugin/blob/master/music.sh) small script I use. It worked for me, but do tell me if there's a better way to toggle an output.

**Comment by patrick96** [comment]
Polybar will not change the output of the module when click on it, it will only execute the `click-*` command and not do anything with its output. If you want to change which battery is displayed when you click, you will need to somehow preserve that information, I would recommend writing it into a file that the script then reads.

**Comment by qqldd** [comment]
I think this is mission feature. There are two issues about this: #720 #786

**Comment by patrick96** [comment]
The feature request in #786 wants to rerun the `exec` command everytime the module is clicked. But it seems like #720 isn't actually a duplicate. I'll go ahead and reopen #720 and close this one in favor lf that.
