### ISSUE TITLE
 gtk-youtube-viewer

### ISSUE THREAD

**Issue by medioman** [jaagr/polybar#865]
Hello,
I installed gtk-youtube-viewer, can I add it to the polybar panel?
How to modify modules.conf and config.
Thanks for your help

**Comment by patrick96** [comment]
What do you mean by "add it to the polybar"? You can do pretty much anything with a custom [script](https://github.com/jaagr/polybar/wiki/Module:-script) module, as long as youtube-viewer allows you to collect information using a script.

**Comment by medioman** [comment]
hello, 
thank you for having responded to me.
I say I'm not good with the scripts, I installed the above mentioned program, I would like to add a key in the openbox bar with polybar to start the program from the bar.
I hope I explained

**Comment by patrick96** [comment]
For that you can use either the [text](https://github.com/jaagr/polybar/wiki/Module:-text) module with `click-left` set to the program name or use the [menu](https://github.com/jaagr/polybar/wiki/Module:-menu) module with a single menu entry. If you only need to start a single application, I'd recommend the text module.

**Comment by medioman** [comment]
thank @patrick96 
solved
