### ISSUE TITLE
network module signal strengh

### ISSUE THREAD

**Issue by pasau** [jaagr/polybar#866]
Hi, i want to see the wifi signal strength on my polybar configuration. When i use %signal% in the formatting i get just a number, around 80. I was expecting something in dBm.

From `iw dev wlp4s0 scan`, i get -50 dBm for my network wifi. Is there a way to display a signal in dBm?

**Comment by NBonaparte** [comment]
The signal strength is calculated by the percentage function
https://github.com/jaagr/polybar/blob/038fea8e362b72007d6211b20a0019ffce731b83/include/adapters/net.hpp#L34-L39
where `val` and `max` are as follows:
https://github.com/jaagr/polybar/blob/038fea8e362b72007d6211b20a0019ffce731b83/src/adapters/net.cpp#L376-L383
As shown by the comment above, it should be possible to obtain the value in dBm. However, we have plans to migrate the network backend from `wireless_tools`, so all network development is essentially frozen.
