### ISSUE TITLE
Disabling module "wired-network" (reason: No built-in support for 'internal/network')

### ISSUE THREAD

**Issue by maarteNNNN** [jaagr/polybar#869]
I'm getting this error and it's probably short of a package but a google search couldn't give me any answer.

> error: Disabling module "wired-network" (reason: No built-in support for 'internal/network')
error: Disabling module "wired-network" (reason: No built-in support for 'internal/network')

This is my ip link info (I altered to xx:xx:xx:xx:xx:xx)

> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp0s25: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default 
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff

OS: Arch Linux

**Comment by NBonaparte** [comment]
Is `wireless_tools` installed?

**Comment by maarteNNNN** [comment]
@NBonaparte I installed the package to see if there's a difference but there isn't. The connection is wired though.

I'm using dhcpcd which has problems during start up with a startjob. Could it be related to this package?

Thanks in advance!

**Comment by NBonaparte** [comment]
Since you didn't have it installed, try rebuilding polybar because it checks for the package at compile time.

**Comment by maarteNNNN** [comment]
@NBonaparte That did the trick!

Thank you very much!
