### ISSUE TITLE
Missing shared library

### ISSUE THREAD

**Issue by AHaymond** [jaagr/polybar#873]
This issue came up approximately one year ago (see [#264](https://github.com/jaagr/polybar/issues/264)).

I just ran an update and I am seeing the exact same error. 

`polybar: error while loading shared libraries: libjsoncpp.so.11: cannot open shared object file: No such file or directory`

libjsoncpp.so is available in `/usr/lib/` 

I am confused why this error is showing up.

**Comment by AvnSgt** [comment]
Please (see #871), as this is a duplicate of an issue we are already tracking.

**Comment by AHaymond** [comment]
I recomplied polybar and that fixed my issue.
