### ISSUE TITLE
Tray not transparent

### ISSUE THREAD

**Issue by alexozer** [jaagr/polybar#879]
[Here's my dotfiles](https://github.com/alexozer/dotfiles). I'm using Arch Linux with BSPWM, compton, and some Xfce components.

[Polybar config](https://gist.github.com/alexozer/c14426ff05c53f5907e8c99b3bee82b5).

Although I have transparency set for the tray:

```ini
tray-position = right
tray-maxsize = 24
tray-transparent = true
tray-background = #00000000
```

The tray still appears solid black for me:

![panel](https://user-images.githubusercontent.com/2074322/33529837-095360ce-d844-11e7-8cc9-84a0a6283681.png)

I also get these errors:

```
➜  ~ polybar top
warn: No monitor specified, using "eDP1"
error: Failed to get root pixmap for tray background (realloc=1)
error: Failed to get root pixmap for tray background (realloc=1)
error: Failed to get root pixmap for tray background (realloc=1)
error: Failed to get root pixmap for tray background (realloc=1)
```

**Comment by gpakosz** [comment]
Here, running manjaro i3 + polybar-git

![image](https://user-images.githubusercontent.com/553208/36939908-462965c0-1f39-11e8-8207-f60a679ed9f0.png)

```
tray-transparent = false
tray-background = #b2000000
```

I get no error when launching polybar.

**Comment by gpakosz** [comment]
Seems to work for me 👌

**Comment by patrick96** [comment]
Awesome!
