### ISSUE TITLE
Format-Action weird behavior

### ISSUE THREAD

**Issue by julio-b** [jaagr/polybar#887]
I tried to use format-action so i can send a notification when i click on the battery module. Using the following minimal configuration:  
```dosini
[bar/test]
modules-right = battery

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
time-format = %H:%M
format-charging = <label-charging>
format-discharging = <label-discharging>
label-charging =  %{A1:notify-send -u low "Remaining battery time \: %time%":} %percentage%%%{A}
label-discharging = %{A1:notify-send -u low "Remaining battery time \:  %time%":} %percentage%%%{A}

; vim:ft=dosini
```
polybar fails with this error:  
`error: Failed to parse contents (reason: Unrecognized token '3')`
 
[Action commands](https://github.com/jaagr/polybar/wiki/Formatting#action-a) are defined this way:
`%{A<button-index><colon><command><colon>}<inner-text>%{A}`
If for example i use this command: 
`%{A1:notify-send "%time%":} text %{A}` 
the time token is replaced by its actual value: 
`%{A1:notify-send "01:33":} text %{A}` 
The problem appears in [src/components/parser.cpp:parse_action_cmd](https://github.com/jaagr/polybar/blob/17f1f19012e486bbdd82be8093b620a4e098de37/src/components/parser.cpp#L233-L251). As we can see, the only way to use a colon as part of the command is to escape it with a backslash(\\:), it doesn't handle quoted strings at all.  There's no way to escape colon character inside %time% token. I am aware that i can change time-format to something like %H\\:%M, but i believe it would be better and more flexible if the parser ignored all colons characters between double quotes.

**Comment by patrick96** [comment]
This is a difficult issue to solve.
If the parser would ignore anything inside quotes, it would mean that the double quote character cannot be used alone as part of the text on the bar without possibly compromising the action tags that follow. I think adding the backslash to the `time-format` is the only way to solve this for now. The only case where that wouldn't work is when the token inside the action command is also used elsewhere in the label but that is just a limitation that polybar has right now.
I really can't think of a way to solve this properly without breaking something else, can you think of something?

**Comment by julio-b** [comment]
Yes i didn't thought about it. You're absolutely right, double-quotes wouldn't solve this.
Actually, for that case i opened this issue. I wanted to use "%time%" as label-discharging, and "%{A1:notify-send %time%:} %percentage% %{A}" as label-charging.
The only real solution i can think of is to replace tokkens after parsing. But this issue alone does not deserve such a big change in the source code.
Thanks anyway!

**Comment by patrick96** [comment]
Going to close this.
There's really no way to "fix" this. Replacing the tokens after parsing is not possible because after the intermediate lemonbar-style string is generated, it is totally decoupled from the modules, there would be no way to figure out from which module a token is from.
