### ISSUE TITLE
Can't get polybar to display the bar once, when using xrandr --same-as function

### ISSUE THREAD

**Issue by CableSleeve** [jaagr/polybar#888]
I am using the following script file,

```
#!/usr/bin/env sh

# Terminate already running bar instances
killall -q polybar

# Wait until processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

# Launch polybar (depending on multiple monitors or not)
if type "xrandr"; then
	for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
		MONITOR=$m polybar --reload top &
		MONITOR=$m polybar --reload bottom &
	done
else
	polybar top &
	polybar bottom &
fi

```

I also want to keep the functionality of a normal multiple monitor setup.

Help would be appreciated!

**Comment by NBonaparte** [comment]
So, if I'm understanding this correctly, you want to display polybar only once while mirroring the display?
What happens when you try to do so?

**Comment by CableSleeve** [comment]
If I am not duplicating the screen to another screen , but extending it then I get the bar to display correctly. But when I try duplicating (mirroring) it displays the bar twice which is wrong, since it only needs to be displayed once.

**Comment by patrick96** [comment]
You start polybar once for every connected monitor, if you mirror the monitor with xrandr, then xrandr will still show both monitors as connected. So your script will still start polybar twice regardless of how the monitors are configured as long as both are connected. This is not an issue with polybar but with your script

**Comment by CableSleeve** [comment]
Oké, since this isn't a polybar related issue, this thread can be closed. However I would like some help implementing something like this, because my scripting knowledge is very limited.

**Comment by patrick96** [comment]
I don't really have the time to go into this, but you'll somehow need to figure out from the output of xrandr, when the monitors are mirrored and when they are not. Try to look at the differences of the output of the `xrandr` command when you duplicate the screen and when you are extending it
