### ISSUE TITLE
Date module not working

### ISSUE THREAD

**Issue by EternalZenith** [jaagr/polybar#889]
With the most recent update to polybar, I cannot seem to get the date module to function. When launching polybar, I get: 

`error: Disabling module "date" (reason: locale::facet::_S_create_c_locale name not valid)`

All I can find on the error is that it is an issue with locale settings, but on my system the local seems to be set correctly. ( "LANG=en_US.UTF-8")

This only appeared with the 3.1.0 update, which I cannot revert from due to the library error the previous versions have on Arch.

**Comment by abstrakct** [comment]
I get the same error. Arch Linux here as well. I just updated my system, including polybar.

**Comment by NBonaparte** [comment]
What is the output of `locale`?

**Comment by patrick96** [comment]
Also what is the `locale` setting in your config?

**Comment by EternalZenith** [comment]
Aha, figured it out. My locale was set as en_US.UTF-8 everywhere but in the config for polybar, which was set to UTF-16. Changing the locale to use UTF-8 in the config fixed it.
Thanks for the pointer to look at the config's setting.
