### ISSUE TITLE
Wrong date format after recent update

### ISSUE THREAD

**Issue by kartongsaft** [jaagr/polybar#893]
Hello!

Updated to the latest version today and noticed that my date syntax don't work anymore.

I have `date = %-d/%-m` in my config file, which produce `5/12`, but after update, the same date syntax outputs `%-d/%-m`.

**Comment by patrick96** [comment]
With the newest version the date module changed a little, see the [release notes](https://github.com/jaagr/polybar/releases/tag/3.1.0) for more info as well as #792. All possible tokens are listed [here](http://en.cppreference.com/w/cpp/io/manip/put_time)
