### ISSUE TITLE
transparent bar

### ISSUE THREAD

**Issue by alfredagni** [jaagr/polybar#896]
Hello everybody, 
i'm having a problem with bar transparency. when i set transparent as #00...... i see just black bar (or no bar). I don't have problems if i set a non-transparent color as background. 

I think the problem is that when bar is active, wallpaper "leave" space for bar, so the background color by deafult is black.

manjaro xfce4

**Comment by RorixRebel** [comment]
can you paste your configuration for the background here?

**Comment by alfredagni** [comment]
I already resolved, i had to use Compton as compositor. Ty
