### ISSUE TITLE
Default modules not working

### ISSUE THREAD

**Issue by navdeepio** [jaagr/polybar#903]
A lot of modules, like powermenu, music etc are not working with my nascent polybar setup.. is there a way to debug it?

I'm using archlinux/bspwm!

**Comment by patrick96** [comment]
The first step is to look at the output of the polybar command, if any of the modules you defined are not working at all, it should show you a warning or an error. You can also increase the log level (see the man page for that), if the default log level does not give you enough information.

Also what's a "nascent setup"?

**Comment by patrick96** [comment]
Can you post the output of the polybar command as well as the output of `polybar -vvv`
So you are using the config that came with polybar?

**Comment by navdeepio** [comment]
polybar 3.1.0

Features: +alsa +curl -i3 -mpd +network

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now


> So you are using the config that came with polybar?

yes

**Comment by patrick96** [comment]
And what is the output when you actually run the bar? (Preferably with the `-l info` flag)

**Comment by navdeepio** [comment]
warn: No monitor specified, using "eDP1"
* Loaded monitor eDP1 (1920x1080+0+0)
* Bar geometry: 1920x35+0+0
error: Disabling module "eth" (reason: Invalid network interface "tun0")
* Starting application
* Starting module/bspwm
* Starting module/music
* Starting module/powermenu
* module/music: Invoking shell command: "~/.config/polybar/mpris.sh"
* module/bspwm: Parsing socket data: MeDP1:OI:fII:fIII:fIV:fV:fVI:fVII:oVIII:oIX:oX:LT:TT:G
* Starting module/xbacklight
* Starting module/volume
* Starting module/memory
* Starting module/cpu
* Starting module/wlan
* Starting module/battery
* Starting module/temperature
* Starting module/date
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=12)
* Configured DPI = 96x96
* Loaded font "fixed:pixelsize=10" (name=Noto Sans, offset=1, file=/usr/share/fonts/noto/NotoSans-Regular.ttc)
* Loaded font "unifont:fontformat=truetype:size=8:antialias=false" (name=Noto Sans, offset=0, file=/usr/share/fonts/noto/NotoSans-Regular.ttc)
* Loaded font "siji:pixelsize=10" (name=Noto Sans, offset=1, file=/usr/share/fonts/noto/NotoSans-Regular.ttc)
* Bar window: 0x0e00003
* Successfully restacked bar window
* Activating tray manager
* Tray window: 0x0e0000a
* module/bspwm: Rebuilding cache
* module/music: Rebuilding cache
* module/powermenu: Rebuilding cache
* module/xbacklight: Rebuilding cache
* module/volume: Rebuilding cache
* module/memory: Rebuilding cache
* module/cpu: Rebuilding cache
* module/wlan: Rebuilding cache
* module/battery: Rebuilding cache
* module/temperature: Rebuilding cache
* module/date: Rebuilding cache
* Redrawing bar window
warn: Dropping unmatched character  (U+e10c)
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e21a)
warn: Dropping unmatched character  (U+e238)
warn: Dropping unmatched character  (U+e0ca)
warn: Dropping unmatched character  (U+e016)
* module/temperature: Rebuilding cache
* Notifying pending tray clients
* Processing docking request from 0x180004f
* Processing docking request from 0x140005c
* Processing docking request from 0x0c0001c
* Redrawing bar window
warn: Dropping unmatched character  (U+e10c)
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e21a)
warn: Dropping unmatched character  (U+e238)
warn: Dropping unmatched character  (U+e0ca)

**Comment by patrick96** [comment]
Well I see a few issues here:

- Your network module is not working because you have specified an invalid network interface
- Your music module is not the one in the default config, but a script most likely from the user-contributed modules page. To debug this you'll need to debug the script itself, it most likely does not have anything to do with polybar
- You have a lot of unmatched characters, this means it could look like some modules are not showing up, but in reality they work but just output an empty string because the icons they display are not found. The reason for this is that the fonts specified in the config are not found on your system, either they're not installed or they are found under a (slightly) different name, check the [Font](https://github.com/jaagr/polybar/wiki/Fonts) wiki page for this.
