### ISSUE TITLE
build error: Could NOT find XCB

### ISSUE THREAD

**Issue by Troyciv** [jaagr/polybar#908]
I'm trying to compile polybar on a ubuntu 16.04 machine. I couldn't find the following packages in the repositories: xcb-util-image, xcb-util-wm, xcb-util-xrm

As expected I ran into errors:

    CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
    Could NOT find XCB (missing: XCB_ICCCM_FOUND XCB_EWMH_FOUND XCB_UTIL_FOUND
    XCB_IMAGE_FOUND)
    Call Stack (most recent call first):
    /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388   
    (_FPHSA_FAILURE_MESSAGE)
    lib/xpp/cmake/FindXCB.cmake:245 (find_package_handle_standard_args)
    lib/xpp/CMakeLists.txt:13 (find_package)

I don't know which package it is looking for. XBC itself is installed.
    
    $ apt list xcb
    xcb/xenial,now 2.4-4.3 amd64 [installed]

Does anybody know how the dependencies are named in 16.04?

**Comment by patrick96** [comment]
The [Compiling](https://github.com/jaagr/polybar/wiki/Compiling) Wiki page should have the proper names for the ubuntu packages

**Comment by Troyciv** [comment]
perfect, thank you
