### ISSUE TITLE
Network modules not showing up

### ISSUE THREAD

**Issue by hhiru** [jaagr/polybar#909]
At first I tried networkmanager to handle my wifi but then I switched to wicd. Maybe there is a conflict between some dependencies remained from the first networkmanager installation but I'm quite sure I removed everthing..

> $ ip link
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
> 2: enp0s25: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN mode DEFAULT group default qlen 1000
>     link/ether 00:1f:16:24:59:13 brd ff:ff:ff:ff:ff:ff
> 3: wls1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DORMANT group default qlen 1000
>     link/ether 00:1e:65:62:32:88 brd ff:ff:ff:ff:ff:ff

```
[module/wired-network]
type = internal/network
interface = enp0s25
interval = 0.5
format-disconnected = <label-disconnected>
format-connected = <label-connected>
label-connected = %local_ip%
label-disconnected =

[module/wireless-network]
type = internal/network
interface = wls1
interval = 3.0
udspeed-minwidth = 0
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-connected =  %essid%
label-connected-foreground = #eefafafa
label-disconnected = 
label-disconnected-foreground = #66ffffff

[bar/mybar]
#override-redirect = true
bottom = false
fixed-center = true
width = 100%
height = 30
offset-x = 0
offset-y = 0
background = ${colors.background}
foreground = ${colors.foreground}
radius = 0.0
line-size = 0
border-size = 0
padding = 0
padding-right = 1
module-margin = 0
module-margin-left = 1
font-0 = DejaVu Sans Mono:size=12;2
font-1 = FontAwesome:size=12;2
font-2 = Material Icons:size=14;4
font-3 = HanaMinA:antialias=false,size=12;2
modules-left = i3
modules-center = time
modules-right = wired-network wireless-network volume battery
```

> polybar 3.1.0
> 
> Features: +alsa +curl +i3 -mpd -network

![image](https://user-images.githubusercontent.com/11262717/34072404-3eb7ae9e-e287-11e7-8f2f-d046f788f256.png)

**Comment by patrick96** [comment]
If you look at the output of the polybar command, you'll probably see an error telling you that polybar wasn't compiled with network support, that's also what the -network in `polybar -v` is telling you.
You need to have wireless_tools installed before compiling polybar

**Comment by hhiru** [comment]
It worked! I installed wireless_tools and recompiled polybar. Thank you :)
