### ISSUE TITLE
Compilation issue in vagrant box Archlinux

### ISSUE THREAD

**Issue by eoli3n** [jaagr/polybar#912]
Hi,
Here log file : https://gist.github.com/eoli3n/a825a8f6f33f80f3212d8c8926bcf735
Here the PKGBUILD : https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=polybar-git

# Step to reproduce

1° Install vagrant and virtualbox
2° Create vagrant file
```
mkdir vagrant-test
cat <<\EOF > vagrant-test/Vagrantfile
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "terrywang/archlinux"
  config.vm.provision "shell", inline: <<-SHELL
    # Upgrade to latest
    pacman -Syu --noconfirm
  SHELL

  $script = <<-SCRIPT
  yaourt -S polybar-git --noconfirm
  SCRIPT

  config.vm.provision "shell", inline: $script, privileged: false
end
EOF
```
3° Then run it
```
cd vagrant-test
vagrant up
```

# Manual install

To launch a shell on the vm
```
vagrant ssh
```
When i run manually
```
git clone --branch 3.1.0 --recursive https://github.com/jaagr/polybar
mkdir polybar/build
cd polybar/build
cmake ..
sudo make install
```
It works... what differ ?

Another question, why there isn't any polybar package in community ?

**Comment by NBonaparte** [comment]
Your VM does not have enough RAM, try increasing it. 

To move a package from the AUR to the community repo, we would need to get a Trusted User to maintain it: https://wiki.archlinux.org/index.php/AUR_Trusted_User_Guidelines#Rules_for_Packages_Entering_the_.5Bcommunity.5D_Repo

**Comment by eoli3n** [comment]
Worked with
```
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
```
Thx !
