### ISSUE TITLE
mpd plugin shows wrong elapsed time

### ISSUE THREAD

**Issue by evgfilim1** [jaagr/polybar#915]
### Steps to reproduce:

0. Install and configure mpd, set up polybar to use mpd plugin with `<label-time>` in `format-online` (as shown below), then run `polybar main`:
```ini
[bar/main]
font-0 = Noto Sans:pixelsize=11;1
# FontAwesome is needed to display "" symbol
font-1 = FontAwesome:pixelsize=11;1
modules-center = mpd

[module/mpd]
type = internal/mpd
format-online = %{F#6b6b6b}[<label-time>]%{F-}  <label-song>
```
1. Start playing music from mpd
2. Suspend your PC (for example, run `systemctl suspend` in terminal)
3. Wait for ~10 minutes, then turn on your PC

### Expected behaviour:
mpd plugin shows normal elapsed time

### Actual behaviour:
![22-12-2017_08-12-39](https://user-images.githubusercontent.com/17182159/34305596-c2c9c608-e760-11e7-832e-827d38c68ea2.png)

**UPD.** This happens not only after waking up, see https://github.com/jaagr/polybar/issues/915#issuecomment-353900462

**Comment by patrick96** [comment]
I just noticed the same thing after rebooting the PC. Can you check that this only happens in polybar by also running
```bash
while true; do mpc status | awk 'NR==2'; sleep 2; done
```
while reproducing this (it prints the current song time continuously to the screen).

**Comment by evgfilim1** [comment]
@patrick96 Yes, this happens only in polybar.

![23-12-2017_05-31-33](https://user-images.githubusercontent.com/17182159/34315522-a6e81538-e7a2-11e7-9652-1c347b3b8499.png)

**Comment by evgfilim1** [comment]
Also, when I start the first track in my mpd playlist and press "Back", the track starts from the beginning, but the time on the bar doesn't. I think it's related to this bug.
![26-12-2017_06-17-10](https://user-images.githubusercontent.com/17182159/34344168-6d8a7362-ea04-11e7-935d-8324061fffef.png)

**Comment by patrick96** [comment]
Just opened a PR with a fix. I was able to reproduce this on my system and the patch fixes it for me, please try it out and tell me if it works for you too

**Comment by evgfilim1** [comment]
@patrick96 Yes, it works for me too.
