### ISSUE TITLE
cmake fails on openSuse Leap 42.3

### ISSUE THREAD

**Issue by domsch1988** [jaagr/polybar#920]
I can't get this to compile under openSuse. I installed all needed dependencys. Output

```
-- No build type specified; using RelWithDebInfo
-- Using supported compiler Clang-3.8.0
--  Build:
--    Type: RelWithDebInfo
--    CC: /usr/bin/cc  -O2 -g -DNDEBUG
--    CXX: /usr/bin/clang++  -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors -Wno-error=parentheses-equality -O2 -g -DNDEBUG
--    LD: /usr/bin/ld  
--  Targets:
-- [X]   polybar-msg
-- [ ]   testsuite
--  Module support:
-- [X]   alsa
-- [X]   curl
-- [X]   i3
-- [ ]   mpd
-- [X]   network
--  X extensions:
-- [X]   xcb-randr
-- [ ]   xcb-randr (monitor support)
-- [ ]   xcb-render
-- [ ]   xcb-damage
-- [ ]   xcb-sync
-- [ ]   xcb-composite
-- [X]   xcb-xkb
-- [ ]   xcb-xrm
-- [X]   xcb-cursor
-- Found font: efont fixed:pixelsize=10
-- Font not found: unifont:fontformat=truetype
-- Font not found: siji:pixelsize=10
CMake Error at lib/CMakeLists.txt:33 (add_subdirectory):
  The source directory

    /home/dschlack/polybar/lib/xpp

  does not contain a CMakeLists.txt file.


CMake Error at lib/CMakeLists.txt:41 (add_subdirectory):
  The source directory

    /home/dschlack/polybar/lib/i3ipcpp

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "/home/dschlack/polybar/build/CMakeFiles/CMakeOutput.log".
See also "/home/dschlack/polybar/build/CMakeFiles/CMakeError.log".
```
Output.log and Error.log are attached.
[CMakeError.log](https://github.com/jaagr/polybar/files/1588565/CMakeError.log)
[CMakeOutput.log](https://github.com/jaagr/polybar/files/1588566/CMakeOutput.log)

Any help on this would be highly appreciated.

**Comment by NBonaparte** [comment]
Did you clone recursively?

**Comment by patrick96** [comment]
> Did you clone recursively?

No definitely not.

Either do a fresh clone with the `--recursive` flag or run `git submodule update --init --recursive
` inside the repo

**Comment by domsch1988** [comment]
So, with syncing resursively (don't know how i missed that) cmake completes successfully. now i'm getting errors on make install:
`[  1%] Built target xpp
[  2%] Building CXX object lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_reader.cpp.o
In file included from /home/dschlack/polybar/lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/json_reader.cpp:7:
In file included from /home/dschlack/polybar/lib/i3ipcpp/libs/jsoncpp-1.7.7/include/json/assertions.h:10:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/4.8/../../../../include/c++/4.8/sstream:38:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/4.8/../../../../include/c++/4.8/istream:38:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/4.8/../../../../include/c++/4.8/ios:42:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/4.8/../../../../include/c++/4.8/bits/ios_base.h:41:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/4.8/../../../../include/c++/4.8/bits/locale_classes.h:40:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/4.8/../../../../include/c++/4.8/string:52:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/4.8/../../../../include/c++/4.8/bits/basic_string.h:2815:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/4.8/../../../../include/c++/4.8/ext/string_conversions.h:43:
/usr/bin/../lib64/gcc/x86_64-suse-linux/4.8/../../../../include/c++/4.8/cstdio:120:11: error: no member
      named 'gets' in the global namespace
  using ::gets;
        ~~^
1 error generated.
lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/build.make:62: recipe for target 'lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_reader.cpp.o' failed
make[2]: *** [lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_reader.cpp.o] Error 1
CMakeFiles/Makefile2:559: recipe for target 'lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/all' failed
make[1]: *** [lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by patrick96** [comment]
Polybar requires `gcc` version 5.1 and up, while you compile with clang, it still somehow uses `gcc` 4.8 libraries where there seems to be some kind of bug (see https://github.com/docopt/docopt.cpp/issues/50).

Check out [this](https://stackoverflow.com/questions/24342312/clang-seems-to-use-the-gcc-libraries) StackOverflow question, the answer may help you resolve the issue
