### ISSUE TITLE
text center

### ISSUE THREAD

**Issue by Skinderfire** [jaagr/polybar#922]
Is it possible to center the text vertically?
![screenshot](https://user-images.githubusercontent.com/33296271/34396635-d74e359e-eb6d-11e7-87cb-6bad71cd3d61.png)

**Comment by TonCherAmi** [comment]
As per [wiki](https://github.com/jaagr/polybar/wiki/Fonts) you can specify vertical offset: `font-N = <fontconfig pattern>;<vertical offset>`
e.g: `font-0 = "Roboto:size=11:weight=bold;2"`

**Comment by Skinderfire** [comment]
It was simple :) thanks
