### ISSUE TITLE
Font Awesome 5

### ISSUE THREAD

**Issue by Kakashiiiiy** [jaagr/polybar#924]
I just updated ttf font awesome from 4 to 5 and now I can not see the icons anymore. 

Someone with the same issue or a solution?
I already copied the new "Icons" into the conf file.

**Comment by eadwu** [comment]
Works for me. What I did was

    font-n = Font Awesome 5 Free:pixelsize=10;3
    font-n = Font Awesome 5 Free Solid:pixelsize=10;3
    font-n = Font Awesome 5 Brands:pixelsize=10;3

If that isn't enough, try using the `%{Tn} ... %{T-}` tags

**Comment by patrick96** [comment]
As @eadwu mentioned, you may need to update your font specifiers. They can be quite different depending on your system, make sure to check with `fc-match`, if they match, see the [Font](https://github.com/jaagr/polybar/wiki/Fonts) Wiki page for more info.

**Comment by helionmelion** [comment]
`fc-match awesome
DejaVuSans.ttf: "DejaVu Sans" "Book"`

**Comment by patrick96** [comment]
Yeah seems you have specified the wrong name. Look through `fc-list` to find the proper name for FontAwesome on your system

**Comment by helionmelion** [comment]
`Yeah seems you have specified the wrong name. Look through fc-list to find the proper name for FontAwesome on your system`

yeah!!! it works!!! this is my working config: 

> font-0 = fixed:pixelsize=8:weight=bold;0
font-1 = unifont:fontformat=truetype:size=8:weight=bold:antialias=false;0
font-2 = "Wuncon siji:pixelsize=8;1"
**font-3 = "Font Awesome 5 Free:style=Regular:pixelsize=8;1"
font-4 = "Font Awesome 5 Free:style=Solid:pixelsize=8;1"
font-5 = "Font Awesome 5 Brands:pixelsize=8;1"**

**Comment by Kakashiiiiy** [comment]
Yeah Thanks it works but why did they split the font?...

**Comment by helionmelion** [comment]
yes I think so, check this:
![awesome](https://user-images.githubusercontent.com/25272493/34423318-44f7d976-ec02-11e7-8448-915e51c9cf9a.jpg)

**Comment by patrick96** [comment]
I have no idea why they split it. We are not involved in the development of FontAwesome, you'd have to ask them.

**Comment by x70b1** [comment]
They want sell theit fonts now. The free icons in version 5 contains solid icons only. But the solid icons doesn't look awesome.

If you want regular and light icons you have to buy a license. 

The best way is to use font-awesome 4. In Arch Linux is already a package in AUR for this: [ttf-font-awesome-4/](https://aur.archlinux.org/packages/ttf-font-awesome-4/).

**Comment by helionmelion** [comment]
maybe if there are some alternatives to awesome?
