### ISSUE TITLE
Font Awesome 5 icons don't work

### ISSUE THREAD

**Issue by filalex77** [jaagr/polybar#925]
Recently Arch's `ttf-font-awesome` package got updated to version 5. That update broke all of my FA icons in polybar.

Icons from FA4 worked when I pasted the glyphs directly from their [cheatsheet](http://fontawesome.io/cheatsheet). With FA5, neither copypasted glyphs nor icon codes work.

For now I managed to get this working by installing [FA4 from AUR](https://aur.archlinux.org/packages/ttf-font-awesome-4), but still - why don't FA5 icons work?
(sorry if it's a problem with FA, not with polybar)

**Comment by TonCherAmi** [comment]
See #924

**Comment by patrick96** [comment]
Use `gucharmap` to find the new glyphs and see the already mentioned issue for how to fix the font specifiers.
This is not a polybar issue, so I'm closing this.
