### ISSUE TITLE
Active workspae highlighting broken in xmonad?

### ISSUE THREAD

**Issue by sagotsky** [jaagr/polybar#927]
I'm using xmonad on arch.  My ewmh module is using internal/xworkspaces.  I've set an active background and foreground.  When I switch workspace, the active styles show up in polybar, but disappear a moment later.  I have no idea why or even where to being debugging this.  I haven't had this problem on other WMs.  Any hints?

**Comment by patrick96** [comment]
Does it always disappear directly after switching workspaces or only after switching windows in the new workspace? Might be the same as #535
What version of polybar are you running? Also are there any warnings in the console when you run polybar?

**Comment by sagotsky** [comment]
TY for the quick reply :-)

I assumed I was on the latest.  Turns out it was 3.0.5.  3.1.0 fixed that.
Sorry for bothering you.
