### ISSUE TITLE
internal/battery module calculates power consumption incorrectly

### ISSUE THREAD

**Issue by MatthewLavine** [jaagr/polybar#928]
I was comparing the functionality of i3status and polybar and noticed that the battery consumption wattage calculation was wildly different between the applications.

See here (i3status on top, polybar underneath):
![battery](https://user-images.githubusercontent.com/2528763/34447784-f44a8178-ec9b-11e7-9d23-a9c129916aa0.png)

Based on these numbers I believe that i3status is showing the correct output and polybar is incorrect. 

Checking into the module sources, here is where polybar attempts to get the current battery power usage: https://github.com/jaagr/polybar/blob/master/src/modules/battery.cpp#L61

Note that it sets m_frate  to "current_now" or "power_now", whichever exists. The problem is that these two files can contain different units. As outlined in i3status's battery module, "on some systems POWER_SUPPLY_POWER_NOW does not exist, but actually it is the same as POWER_SUPPLY_CURRENT_NOW but with μWh as unit instead of μAh"

https://github.com/i3/i3status/blob/master/src/print_battery_info.c#L152

Based on this I think polybar's module needs some extra complicated logic to perform the necessary conversions. If power_now exists, then it's value can be used (with an order of magnitude conversion) instead of calculating current usage based on (incorrect) voltage and current.

I'm a Go programmer myself otherwise I'd send a PR; but I can take a crack at it if no one else has any cycles :)

**Comment by MatthewLavine** [comment]
Attached is a small naive patch that produces correct output on my machine. This patch assumes m_frate is power_now; a proper patch for this should take into account if m_frate is current_now or power_now and perform the relevant calculations if necessary.

[batfix.patch.txt](https://github.com/jaagr/polybar/files/1594881/batfix.patch.txt)

**Comment by ostap-tymchenko** [comment]
hey, im just starting out with using pollybar, how would someone display consumption? these are the two ways i tried and they didnt seem to work

```
...
format-charging = <animation-charging> <label-charging> + <label-consumption>
format-discharging = <ramp-capacity> <label-discharging> + <label-consumption>

label-charging-padding = 1
label-discharging-padding = 1
label-charging =  %percentage%%
label-discharging =  %percentage%%
+ label-consumption =  %consumption%%
...
```

_[the pluses are whats added to the default battery module, basic and additional]_
https://github.com/polybar/polybar/wiki/Module:-battery

```
[module/consumption]
type = internal/battery
label-consumption =  %consumption%
format-charging = <consumption>

```
