### ISSUE TITLE
Workspace-Seperator for i3 module

### ISSUE THREAD

**Issue by DoktorL** [jaagr/polybar#929]
Is there any possibility of having a seperator between the shown worspaces?
Adding the desired character into each label is possible, but i'd like the seperator to have a different color than the workspace icon.

Basically i want to replicate the style of the seperators between the modules on the right side for the seperators between the workspaces on the left side: https://imgur.com/a/Vbqil

**Comment by patrick96** [comment]
No, this is currently not possible. If you want it to have a different color, you can use [Formatting Tags](https://github.com/jaagr/polybar/wiki/Formatting#foreground-color-f) like `%{F#FF0000}\%{F-}` and add it to the labels. However, if your labels have a background or underline color set, then that color will also appear for the separator, so it is not optimal.

I will look into what it would take to implement a separator feature into the module.
