### ISSUE TITLE
Font Awesome Dropping unmatched character

### ISSUE THREAD

**Issue by MatthewLavine** [jaagr/polybar#930]
I'm attempting to get font awesome icons working on my polybar but no matter what I do, i just get polybar logs full of: "warn: Dropping unmatched character".

Polybar version info:
```
$ polybar -vvvv
polybar 3.1.0-git

Features: -alsa +curl +i3 -mpd +network

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/g++
Compiler flags:  -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: 
```

I've installed font awesome:
```
$ ls /usr/share/fonts/opentype/fontawesome 
Font Awesome 5 Brands-Regular-400.otf  Font Awesome 5 Free-Regular-400.otf  Font Awesome 5 Free-Solid-900.otf
```
And rebuilt the cache and fc-list shows them:
```
$ fc-list | grep Awesome
/usr/share/fonts/opentype/fontawesome/Font Awesome 5 Free-Solid-900.otf: Font Awesome 5 Free,Font Awesome 5 Free Solid:style=Solid,Book
/usr/share/fonts/opentype/fontawesome/Font Awesome 5 Free-Regular-400.otf: Font Awesome 5 Free,Font Awesome 5 Free Regular:style=Regular
/usr/share/fonts/opentype/fontawesome/Font Awesome 5 Brands-Regular-400.otf: Font Awesome 5 Brands,Font Awesome 5 Brands Regular:style=Regular
```

The font declarations from my ~/.config/polybar/config:
```
font-0 = SourceCodeProSemiBold:size=10;0
font-1 = "Font Awesome 5 Free,Font Awesome 5 Free Regular:pixelsize=14"
```

And an fc-match on that font string:
```
$ fc-match "Font Awesome 5 Free,Font Awesome 5 Free Regular:pixelsize=14"
Font Awesome 5 Free-Regular-400.otf: "Font Awesome 5 Free" "Regular"
```

Here is the output of "FC_DEBUG=1 polybar <mybar>":  https://pastebin.com/raw/s2rPDPJW

This looks, to me, that polybar is picking up font awesome properly, so i'm not sure why it then drops all the characters that I know exist in that font.

Any help is greatly appreciated, I love polybar! :)

**Comment by Clyybber** [comment]
I too get this problem now.

**Comment by patrick96** [comment]
Did your icons work before and now after the update they don't?
Also try to add all three fonts seperately as shown in #924

**Comment by MatthewLavine** [comment]
I only started using polybar yesterday, so I'm not sure about pre-update. 

Good call! Listing the fonts separately as #924 shows fixes my issue; I can now see all icons as expected.

Thanks!

**Comment by lhanson** [comment]
I'm not using Font Awesome, but I'm seeing similar issues. In my case, using the default config, I need to specify both `Wuncon siji` and `Unifont` separately in order for all characters to display, even though I have them both aliased to `monospace` in my fontconfig. I must be missing something, but I assumed fontconfig would handle the fallback when glyphs aren't found?

**Comment by patrick96** [comment]
The only fallback polybar has, are the fonts you specified in the config. You can use the `-l info` argument when starting polybar to see which fonts it actually loads.
Also is it even possible to alias to fonts to the same font? How would fontconfig know from which font to pull the glyphs?

**Comment by patrick96** [comment]
@lhanson That seems like quite a niche feature to me as most people already have enough problems getting the fonts to work inside polybar, I doubt changing their fontconfig settings will be easier and we certainly don't also want to play tech support for fc related issues. From digging into the relevant code a bit, I have also not found a way to implement this without some big font rendering rewrites, otherwise this would of course be a nice addition ;)

**Comment by Twix53791** [comment]
I just share it my recent experience, as it could help some noobies like me. I got the same error trying to use an icon from weather icons (nerd fonts). I was trying the unicode got from the nerd site (https://www.nerdfonts.com/cheat-sheet?set=nf-weather-), but in fact, on my computer the code was different, as I simply saw in Libbre Office Writer, which display properly all my icons...
