### ISSUE TITLE
Font Awesome 5 fonts not loading together

### ISSUE THREAD

**Issue by Deluxo** [jaagr/polybar#933]
Here are the fonts I want to use in polybar:
```
font0 = xos4 terminus:size=12:weight=normal;1
font1 = FontAwesome5Brands:style=Solid:size=11;2
font2 = FontAwesome5Free:style=Solid:size=11;2
```

polybar -l info config:
```
* Eventqueue worker (thread-id=8)
* Configured DPI = 96x96
* Loaded font "xos4 terminus:size=12:weight=normal" (name=xos4 Terminus, offset=1, file=/usr/share/fonts/misc/ter-x12n.pcf.gz)
* Loaded font "FontAwesome5Brands:style=Solid:size=11" (name=Font Awesome 5 Brands, offset=2, file=/usr/share/fonts/OTF/Font Awesome 5 Brands-Regular-400.otf)
* Bar window: 0x3600001
* Successfully restacked bar window
* Activating tray manager
* Tray window: 0x3600005
```

If i switch `font1` with `font2`, i get the other one working, and the other not.

```
polybar --version
polybar 3.1.0
Features: +alsa +curl -i3 -mpd +network
```

**Comment by patrick96** [comment]
> font0 = xos4 terminus:size=12:weight=normal;1
font1 = FontAwesome5Brands:style=Solid:size=11;2
font2 = FontAwesome5Free:style=Solid:size=11;2

Is this in your config exactly like this? Because if so, this shouldn't work at all, the proper keys for the fonts should be `font-0`, `font-1` and `font-2`. Your log seems to suggest that polybar thinks you have only specified two fonts in your config. Please try to use those keys for specifying the fonts and if that doesn't work, post the whole contents of the `[bar/config]` section of your polybar config file.

**Comment by jonathanio** [comment]
I'm seeing issues with Font Awesome 5 fonts too. Polybar works fine using the following configuration targeting the older Font Awesome set (specifially from the `awesome-termainl-fonts` package):

```font-0 = Iosevka Term:size=10:antialias=true
font-1 = FontAwesome:size=10:antialias=true```

However, if I change it to:

```font-0 = Iosevka Term:size=10:antialias=true
font-1 = FontAwesome 5 Free:size=10:antialias=true```

The font loads correctly:

```* Loaded font "Iosevka Term:size=10:antialias=true" (name=Iosevka Term, offset=0, file=/usr/share/fonts/TTF/iosevka-term-regular.ttf)
* Loaded font "FontAwesome 5 Free:size=10:antialias=true" (name=Font Awesome 5 Free, offset=0, file=/usr/share/fonts/OTF/Font Awesome 5 Free-Regular-400.otf)```

However, none of the characters from Font Awesome 5 display. I just get:

```warn: Dropping unmatched character  (U+f028)    
warn: Dropping unmatched character  (U+f068)
warn: Dropping unmatched character  (U+f068)
warn: Dropping unmatched character  (U+f068)
warn: Dropping unmatched character  (U+f068)
warn: Dropping unmatched character  (U+f068)
warn: Dropping unmatched character  (U+f068)
warn: Dropping unmatched character  (U+f068)
warn: Dropping unmatched character  (U+f142) 
```

As it cycles over the widgets on refresh.

**Comment by patrick96** [comment]
@jonathanio See #924

**Comment by jonathanio** [comment]
@patrick96,

Apologies. Although for anyone following, for reference, that it appears as though the glyphs in _Font Awesome 5 Free_ are **not** in the _Regular_ style but in the _Solid_. Once changed to that it works fine. I'm now using:

```
font-0 = Iosevka Term:size=10:antialias=true
font-1 = Font Awesome 5 Free:size=10:antialias=true:style=Solid
```

That is working as expected. Thanks.

**Comment by Deluxo** [comment]
Again, The issue is the combination of
FontAwesome5Brands:style=Solid:size=11;2
AND
FontAwesome5Free:style=Solid:size=11;2.

Of course fonts are loaded, and yes. My excerpt IS with `style=Solid`.
Also, my config DOES load with my config, and font keys with a '-' sign crashes polybar.

**Comment by Deluxo** [comment]
Also, sorry for confusion. font0, font1 are only `vars`.
Actually the font settings look like this:
```
font-0 = ${vars.font0}
font-1 = ${vars.font1}
```
