### ISSUE TITLE
yaourt -S polybar-git  no build module network

### ISSUE THREAD

**Issue by yadex** [jaagr/polybar#940]
40%] Building CXX object bin/CMakeFiles/polybar.dir/modules/battery.cpp.o
[ 41%] Building CXX object bin/CMakeFiles/polybar.dir/modules/bspwm.cpp.o
[ 42%] Building CXX object bin/CMakeFiles/polybar.dir/modules/counter.cpp.o
[ 44%] Building CXX object bin/CMakeFiles/polybar.dir/modules/cpu.cpp.o
[ 45%] Building CXX object bin/CMakeFiles/polybar.dir/modules/date.cpp.o
[ 46%] Building CXX object bin/CMakeFiles/polybar.dir/modules/fs.cpp.o
[ 47%] Building CXX object bin/CMakeFiles/polybar.dir/modules/github.cpp.o
[ 48%] Building CXX object bin/CMakeFiles/polybar.dir/modules/i3.cpp.o
[ 50%] Building CXX object bin/CMakeFiles/polybar.dir/modules/ipc.cpp.o
[ 51%] Building CXX object bin/CMakeFiles/polybar.dir/modules/memory.cpp.o
[ 52%] Building CXX object bin/CMakeFiles/polybar.dir/modules/menu.cpp.o
[ 53%] Building CXX object bin/CMakeFiles/polybar.dir/modules/meta/base.cpp.o
[ 54%] Building CXX object bin/CMakeFiles/polybar.dir/modules/mpd.cpp.o
[ 55%] Building CXX object bin/CMakeFiles/polybar.dir/modules/script.cpp.o
[ 57%] Building CXX object bin/CMakeFiles/polybar.dir/modules/systray.cpp.o
[ 58%] Building CXX object bin/CMakeFiles/polybar.dir/modules/temperature.cpp.o
[ 59%] Building CXX object bin/CMakeFiles/polybar.dir/modules/text.cpp.o
[ 60%] Building CXX object bin/CMakeFiles/polybar.dir/modules/volume.cpp.o
[ 61%] Building CXX object bin/CMakeFiles/polybar.dir/modules/xbacklight.cpp.o

**Comment by patrick96** [comment]
Please post the whole output

**Comment by yadex** [comment]
-- The C compiler identification is GNU 7.2.1
-- The CXX compiler identification is GNU 7.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type specified; using RelWithDebInfo
-- Using supported compiler GNU-7.2.1
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Checking for module 'cairo-fc'
--   Found cairo-fc, version 1.15.10
-- Checking for module 'alsa'
--   Found alsa, version 1.1.5
-- Checking for module 'libcurl'
--   Found libcurl, version 7.57.0
-- Checking for module 'libmpdclient'
--   Found libmpdclient, version 2.11
-- Checking for module 'xcb-xkb'
--   Found xcb-xkb, version 1.12
-- Checking for module 'xcb-randr'
--   Found xcb-randr, version 1.12
-- Checking for module 'xcb-randr>=1.12'
--   Found xcb-randr, version 1.12
-- Checking for module 'xcb-xrm'
--   Found xcb-xrm, version 1.2
-- Checking for module 'xcb-cursor'
--   Found xcb-cursor, version 0.1.3
--  Build:
--    Type: RelWithDebInfo
--    CC: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -O2 -g -DNDEBUG
--    CXX: /usr/bin/c++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors -O2 -g -DNDEBUG
--    LD: /usr/bin/ld -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
--  Targets:
-- [X]   polybar-msg
-- [ ]   testsuite
--  Module support:
-- [X]   alsa
-- [X]   curl
-- [X]   i3
-- [X]   mpd
-- [ ]   network
--  X extensions:
-- [X]   xcb-randr
-- [X]   xcb-randr (monitor support)
-- [ ]   xcb-render
-- [ ]   xcb-damage
-- [ ]   xcb-sync
-- [ ]   xcb-composite
-- [X]   xcb-xkb
-- [X]   xcb-xrm
-- [X]   xcb-cursor
-- Found font: misc fixed:pixelsize=10
-- Font not found: unifont:fontformat=truetype
-- Font not found: siji:pixelsize=10
-- Checking for module 'xcb-proto'
--   Found xcb-proto, version 1.12
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.14", minimum required is "2.7") 
-- XCB[XCB]: Found component XCB
-- Found XCB_XCB: /usr/lib/libxcb.so  
-- XCB[ICCCM]: Found component ICCCM
-- Found XCB_ICCCM: /usr/lib/libxcb-icccm.so  
-- XCB[EWMH]: Found component EWMH
-- Found XCB_EWMH: /usr/lib/libxcb-ewmh.so  
-- XCB[UTIL]: Found component UTIL
-- Found XCB_UTIL: /usr/lib/libxcb-util.so  
-- XCB[IMAGE]: Found component IMAGE
-- Found XCB_IMAGE: /usr/lib/libxcb-image.so  
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so  
-- Searching for xcbgen with python2
-- Searching for xcbgen with python3
-- Found xcbgen in /usr/lib/python3.6/site-packages
-- XCB[RANDR]: Found component RANDR
-- Found XCB_RANDR: /usr/lib/libxcb-randr.so  
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so;/usr/lib/libxcb-randr.so  
-- XCB[XKB]: Found component XKB
-- Found XCB_XKB: /usr/lib/libxcb-xkb.so  
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so;/usr/lib/libxcb-randr.so;/usr/lib/libxcb-xkb.so  
-- xpp: including xcb proto randr.xml
-- xpp: including xcb proto xkb.xml
-- xpp: including xcb proto xproto.xml
-- Checking for module 'jsoncpp>=1.7.7'
--   Found jsoncpp, version 1.8.3
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/yaourt-tmp-shire/aur-polybar-git/src/polybar/build
Scanning dependencies of target xpp
[  1%] Linking CXX static library libxpp.a
list: size, ['red', 'green', 'blue']
list: size, ['red', 'green', 'blue']
[  1%] Built target xpp
Scanning dependencies of target i3ipc++
[  2%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o
[  3%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc-util.cpp.o
[  4%] Linking CXX static library libi3ipc++.a
[  4%] Built target i3ipc++
Scanning dependencies of target polybar-msg
[  5%] Building CXX object bin/CMakeFiles/polybar-msg.dir/ipc.cpp.o
[  7%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/env.cpp.o
[  8%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/file.cpp.o
[  9%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/string.cpp.o
[ 10%] Linking CXX executable polybar-msg
[ 10%] Built target polybar-msg
Scanning dependencies of target polybar
[ 11%] Building CXX object bin/CMakeFiles/polybar.dir/adapters/alsa/control.cpp.o
[ 13%] Building CXX object bin/CMakeFiles/polybar.dir/adapters/alsa/mixer.cpp.o
[ 14%] Building CXX object bin/CMakeFiles/polybar.dir/adapters/mpd.cpp.o
[ 15%] Building CXX object bin/CMakeFiles/polybar.dir/cairo/utils.cpp.o
[ 16%] Building CXX object bin/CMakeFiles/polybar.dir/components/bar.cpp.o
[ 17%] Building CXX object bin/CMakeFiles/polybar.dir/components/builder.cpp.o
[ 19%] Building CXX object bin/CMakeFiles/polybar.dir/components/command_line.cpp.o
[ 20%] Building CXX object bin/CMakeFiles/polybar.dir/components/config.cpp.o
[ 21%] Building CXX object bin/CMakeFiles/polybar.dir/components/controller.cpp.o
[ 22%] Building CXX object bin/CMakeFiles/polybar.dir/components/ipc.cpp.o
[ 23%] Building CXX object bin/CMakeFiles/polybar.dir/components/logger.cpp.o
[ 25%] Building CXX object bin/CMakeFiles/polybar.dir/components/parser.cpp.o
[ 26%] Building CXX object bin/CMakeFiles/polybar.dir/components/renderer.cpp.o
[ 27%] Building CXX object bin/CMakeFiles/polybar.dir/components/screen.cpp.o
[ 28%] Building CXX object bin/CMakeFiles/polybar.dir/components/taskqueue.cpp.o
[ 29%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/animation.cpp.o
[ 30%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/iconset.cpp.o
[ 32%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/label.cpp.o
[ 33%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/progressbar.cpp.o
[ 34%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/ramp.cpp.o
[ 35%] Building CXX object bin/CMakeFiles/polybar.dir/events/signal_emitter.cpp.o
[ 36%] Building CXX object bin/CMakeFiles/polybar.dir/events/signal_receiver.cpp.o
[ 38%] Building CXX object bin/CMakeFiles/polybar.dir/main.cpp.o
[ 39%] Building CXX object bin/CMakeFiles/polybar.dir/modules/backlight.cpp.o
[ 40%] Building CXX object bin/CMakeFiles/polybar.dir/modules/battery.cpp.o
[ 41%] Building CXX object bin/CMakeFiles/polybar.dir/modules/bspwm.cpp.o
[ 42%] Building CXX object bin/CMakeFiles/polybar.dir/modules/counter.cpp.o
[ 44%] Building CXX object bin/CMakeFiles/polybar.dir/modules/cpu.cpp.o
[ 45%] Building CXX object bin/CMakeFiles/polybar.dir/modules/date.cpp.o
[ 46%] Building CXX object bin/CMakeFiles/polybar.dir/modules/fs.cpp.o
[ 47%] Building CXX object bin/CMakeFiles/polybar.dir/modules/github.cpp.o
[ 48%] Building CXX object bin/CMakeFiles/polybar.dir/modules/i3.cpp.o
[ 50%] Building CXX object bin/CMakeFiles/polybar.dir/modules/ipc.cpp.o
[ 51%] Building CXX object bin/CMakeFiles/polybar.dir/modules/memory.cpp.o
[ 52%] Building CXX object bin/CMakeFiles/polybar.dir/modules/menu.cpp.o
[ 53%] Building CXX object bin/CMakeFiles/polybar.dir/modules/meta/base.cpp.o
[ 54%] Building CXX object bin/CMakeFiles/polybar.dir/modules/mpd.cpp.o
[ 55%] Building CXX object bin/CMakeFiles/polybar.dir/modules/script.cpp.o
[ 57%] Building CXX object bin/CMakeFiles/polybar.dir/modules/systray.cpp.o
[ 58%] Building CXX object bin/CMakeFiles/polybar.dir/modules/temperature.cpp.o
[ 59%] Building CXX object bin/CMakeFiles/polybar.dir/modules/text.cpp.o
[ 60%] Building CXX object bin/CMakeFiles/polybar.dir/modules/volume.cpp.o
[ 61%] Building CXX object bin/CMakeFiles/polybar.dir/modules/xbacklight.cpp.o
[ 63%] Building CXX object bin/CMakeFiles/polybar.dir/modules/xkeyboard.cpp.o
[ 64%] Building CXX object bin/CMakeFiles/polybar.dir/modules/xwindow.cpp.o
[ 65%] Building CXX object bin/CMakeFiles/polybar.dir/modules/xworkspaces.cpp.o
[ 66%] Building CXX object bin/CMakeFiles/polybar.dir/utils/bspwm.cpp.o
[ 67%] Building CXX object bin/CMakeFiles/polybar.dir/utils/command.cpp.o
[ 69%] Building CXX object bin/CMakeFiles/polybar.dir/utils/concurrency.cpp.o
[ 70%] Building CXX object bin/CMakeFiles/polybar.dir/utils/env.cpp.o
[ 71%] Building CXX object bin/CMakeFiles/polybar.dir/utils/factory.cpp.o
[ 72%] Building CXX object bin/CMakeFiles/polybar.dir/utils/file.cpp.o
[ 73%] Building CXX object bin/CMakeFiles/polybar.dir/utils/http.cpp.o
[ 75%] Building CXX object bin/CMakeFiles/polybar.dir/utils/i3.cpp.o
[ 76%] Building CXX object bin/CMakeFiles/polybar.dir/utils/inotify.cpp.o
[ 77%] Building CXX object bin/CMakeFiles/polybar.dir/utils/io.cpp.o
[ 78%] Building CXX object bin/CMakeFiles/polybar.dir/utils/process.cpp.o
[ 79%] Building CXX object bin/CMakeFiles/polybar.dir/utils/socket.cpp.o
[ 80%] Building CXX object bin/CMakeFiles/polybar.dir/utils/string.cpp.o
[ 82%] Building CXX object bin/CMakeFiles/polybar.dir/utils/throttle.cpp.o
[ 83%] Building CXX object bin/CMakeFiles/polybar.dir/x11/atoms.cpp.o
[ 84%] Building CXX object bin/CMakeFiles/polybar.dir/x11/connection.cpp.o
[ 85%] Building CXX object bin/CMakeFiles/polybar.dir/x11/cursor.cpp.o
[ 86%] Building CXX object bin/CMakeFiles/polybar.dir/x11/ewmh.cpp.o
[ 88%] Building CXX object bin/CMakeFiles/polybar.dir/x11/extensions/randr.cpp.o
[ 89%] Building CXX object bin/CMakeFiles/polybar.dir/x11/extensions/xkb.cpp.o
[ 90%] Building CXX object bin/CMakeFiles/polybar.dir/x11/icccm.cpp.o
[ 91%] Building CXX object bin/CMakeFiles/polybar.dir/x11/registry.cpp.o
[ 92%] Building CXX object bin/CMakeFiles/polybar.dir/x11/tray_client.cpp.o
[ 94%] Building CXX object bin/CMakeFiles/polybar.dir/x11/tray_manager.cpp.o
[ 95%] Building CXX object bin/CMakeFiles/polybar.dir/x11/window.cpp.o
[ 96%] Building CXX object bin/CMakeFiles/polybar.dir/x11/winspec.cpp.o
[ 97%] Building CXX object bin/CMakeFiles/polybar.dir/x11/xembed.cpp.o
[ 98%] Building CXX object bin/CMakeFiles/polybar.dir/x11/xresources.cpp.o
[100%] Linking CXX executable polybar
[100%] Built target polybar

**Comment by yadex** [comment]
no  Targets network

**Comment by patrick96** [comment]
You need to have `wireless_tools` installed before you install polybar for the network module to work

**Comment by yadex** [comment]
thanks
