### ISSUE TITLE
Icons sometimes displayed in bottom right

### ISSUE THREAD

**Issue by Brett99** [jaagr/polybar#947]
When I have `polybar` running and I launch certain programs (so far Discord, Slack, and VLC), I get a small icon in the bottom right for the program. It only appears when polybar is running, and it shifts polybar over a little bit to make room. 

How can I make it so that these are not displayed?

**Comment by patrick96** [comment]
This is the system tray. You can disable it by removing the `tray-position` setting from your config or setting it to an empty string.
