### ISSUE TITLE
Click github module to open notifications

### ISSUE THREAD

**Issue by dieggsy** [jaagr/polybar#948]
I noticed I'm not able to specify `click-left` for the `internal/github` module. It would be nice if left clicking it opened the browser at `https://github.com/notifications`. (I achieve a similar effect in a reddit notifications module with `click-left = xdg-open [url]`)

**Comment by patrick96** [comment]
You can use [Formatting Tags](https://github.com/jaagr/polybar/wiki/Formatting#action-a), to achieve the same functionality. Using something like the following should probably work (notice the backslash before the colon):
```dosini
format = %{A1:xdg-open https\://github.com/notifications:}<label>%{A}
```

**Comment by dieggsy** [comment]
@patrick96 hmm, thanks for the suggestion. I'll test this, though I also had `format-prefix = [font-awesome github icon]`, and with the format tags the icon now shows even if notifications are empty.

**Comment by dieggsy** [comment]
I've resorted to adding the icon to the `label` itself. Will test/close as soon as I get another github notification :) (shame there's no 'mark as unread')

**Comment by patrick96** [comment]
Ping

**Comment by dieggsy** [comment]
Great, this seems resolved then. Thanks!

**Comment by patrick96** [comment]
Great!
