### ISSUE TITLE
[Question] How to achieve modules thicker than bar?

### ISSUE THREAD

**Issue by dieggsy** [jaagr/polybar#949]
I'm referring to the screenshot with the ghost. I found https://github.com/jaagr/dots/blob/master/.local/etc/themer/themes/dracula/polybar but can't really tell how that effect is achieved.

**Comment by patrick96** [comment]
I don't think you can make modules larger than the actual bar. If I recall correctly, this was done with two bars, one that is a little thinner and provides the background and the other that has all the modules as well as a fully transparent background so that the two bars appear as one

**Comment by dieggsy** [comment]
That makes sense. Thanks.
