### ISSUE TITLE
Strangely displaced tray

### ISSUE THREAD

**Issue by bertalanp99** [jaagr/polybar#957]
I've been working on configuring Polybar to my liking. It's truly awesome. However, I recently ran into a problem. My tray gets displaced vertically, like this:

![screenshot](https://user-images.githubusercontent.com/22181548/34957547-5bc69586-fa2e-11e7-8d29-7aace151b38b.png)

What caues this? [Here](https://gist.github.com/bertalanp99/7c82923edc823dee2921d77208638e06) is my entire config (I suppose it contains lots of stupid things, I only got started)

Thanks in advance for any help!

**Comment by bluetiki** [comment]
comment out 
`border-size = 3`
and that should fix your issue.  Also, starting the bar with -r will force the bar to reload after you save a new config so you can play around with settings easily and quickly.

**Comment by bertalanp99** [comment]
Thanks for your reply! Unfortunately, commenting out `border-size = 3` did not help :/

![screenshot](https://user-images.githubusercontent.com/22181548/34990026-e301518a-fac4-11e7-8ede-26e15a5d2f4c.png)

**Comment by patrick96** [comment]
Try adding 
```dosini
override-redirect = true
wm-restack = i3
```
to the bar section.

I think the tray is its own window and it is possible that i3 shifts it around for whatever reason.

**Comment by bertalanp99** [comment]
Thanks for your suggestion! With the two lines added, starting Polybar doesn't make the bar appear. It's just gone... However, I found out that I had a y offset option set. I commented that and now my tray is actually on the bar, but it covers the bar. Like this:

![screenshot](https://user-images.githubusercontent.com/22181548/35014715-027d1ba0-fb12-11e7-8353-db4ffa6a7278.png)

**Comment by NBonaparte** [comment]
That issue is being tracked in #591 so I will close this. We have a new tray in the works so this might not be fixed until the overhaul is finished.
