### ISSUE TITLE
Removing compiled Polyba

### ISSUE THREAD

**Issue by NCC1976** [jaagr/polybar#959]
Hello,
I've installed it via sudo make install . sudo make uninstall issue the following error:
make: *** No rule to make target 'uninstall'.  Stop.
Please advise what to do !
BR

**Comment by patrick96** [comment]
Did you run `sudo make uninstall` inside the build folder, where you ran `sudo make install`?
On my system there is an uninstall target.

If you truly don't have the uninstall target, you should have an `install_manifest.txt` file inside your build folder, it contains the full paths of all the files that were installed. The way to uninstall provided on the [cmake wiki](https://cmake.org/Wiki/CMake_FAQ#Can_I_do_.22make_uninstall.22_with_CMake.3F), is to run `sudo xargs rm < install_manifest.txt`, just make sure, the `install_manifest.txt` contains only files that you really want to delete.

**Comment by NCC1976** [comment]
Thanks a lot for the quick answer ! I was about to close the issue. I did a mistake, I did not run the command in the build folder.
It's OK now
