### ISSUE TITLE
Have ramps for labeles (RAM Module)

### ISSUE THREAD

**Issue by Hacksaurus** [jaagr/polybar#961]
Hello,
I was wondering if there is any any to implement ramps to labels in polybar, because I notice that there are such things for other things such as bars and capacity levels. But no such thing for labels. Specifically for the RAM module you can add ramps to bar to adjust the coloring when you RAM increases.
My idea for having ramps for labels is that after a certain percentage of RAM you can change the color of the lettering.

**Comment by patrick96** [comment]
We have recently implemented ramps for the memory module, so now you are able to do this.
If you want to also change the color of the text, you can use a little workaround, by using the ramp to set the foreground color format tags that then color the text depending on which ramp level is used:
```dosini
[module/memory]
type = internal/memory
interval = 2
format = <ramp-used> <label> 
label = %percentage_used%%

ramp-used-0 = %{F#00FF00}
ramp-used-1 = %{F#FFAA00}
ramp-used-2 = %{F#FF0000}
```

**Comment by Hacksaurus** [comment]
@patrick96 Cool! Should I see these changes apply to the AUR packge `polybar-git`?

**Comment by patrick96** [comment]
Yeah, they should be in the `polybar-git` package

**Comment by Hacksaurus** [comment]
Perfectomundo!

**Comment by Hacksaurus** [comment]
@patrick96 Also another quick question, is there a way to setup the exact percentages when the ramp changes?

**Comment by Hacksaurus** [comment]
```
146 ramp-used-0 = %{F#ccffffff}
147 ramp-used-1 = %{F#ccffffff}
148 ramp-used-2 = %{F#ccffffff}
149 ramp-used-3 = %{F#fba922}
150 ramp-used-4 = %{F#fb5555}
151 ramp-used-5 = %{F#ff5555}
```

Doing this kinda of works it is green at until 50% then it is is yellow, but at 70% it is red... I honestly don't care about the red color tbh tho... But might as well ask anyways... for future reference...

**Comment by patrick96** [comment]
No there's not, the steps between the levels are equally spaced. But you can add more and more levels to control the granularity. If you want to change at 50 and 75 percent, you can use 4 levels with the first two levels being green and then one yellow and one red
