### ISSUE TITLE
Can't run due to dependency error 

### ISSUE THREAD

**Issue by pcbailey** [jaagr/polybar#963]
I just upgraded to Fedora 27 and am having the same issue described in [#871](https://github.com/jaagr/polybar/issues/871). I reinstalled polybar from the latest tagged release (3.1.0), but still get the error **polybar: error while loading shared libraries: libjsoncpp.so.11: cannot open shared object file: No such file or directory** when attempting to run it. 

I confirmed that the latest jsoncpp-devel package is installed. I see in other issues that the matter is considered closed, so I feel like I'm missing something. Any assistance would be greatly appreciated.

**Comment by patrick96** [comment]
Hmm the general issue was that polybar needed to be recompiled, because the name of the jsoncpp library changed. Did you recompile polybar after upgrading or did you just copy the executable that you had compiled before?

**Comment by pcbailey** [comment]
I recompiled, and just to be certain, I updated and recompiled again before opening this issue.

**Comment by patrick96** [comment]
Hmm that's strange, for some reason polybar still compiles against some old libjsoncpp file, because the new one (at least for me) is called `libjsoncpp.so.19`. This may be because when compiling, you have some environment variable set that makes the compiler link another libjsoncpp file.

What is the output of `pkg-config --debug --modversion jsoncpp`?

You could try to go into the directory of your `libjsoncpp.so.19` file (most likely `/usr/lib`, otherwise check the filelist of the package) and symlink it to `libjsoncpp.so.11`

**Comment by pcbailey** [comment]
I apologize for the delayed response. The output you requested is below. The symlink did the trick. It's working properly now. Thanks! Going back to the old i3bar was painful! 

If you think this may be an issue beyond just me, I'm happy to help troubleshoot it in any way I can. Otherwise, you can close the issue whenever you're ready.

`libpkgconf/dependency.c:80 [pkgconf_dependency_addraw]: added dependency [jsoncpp] to list @0x7ffd3793b7b8
libpkgconf/pkg.c:1437 [pkgconf_pkg_traverse]: virtual:world: level 2000
libpkgconf/pkg.c:1452 [pkgconf_pkg_traverse]: virtual:world: walking requires list
libpkgconf/pkg.c:1233 [pkgconf_pkg_verify_dependency]: trying to verify dependency: jsoncpp
libpkgconf/pkg.c:649 [pkgconf_pkg_find]: looking for: jsoncpp
libpkgconf/cache.c:61 [pkgconf_cache_lookup]: miss: jsoncpp
libpkgconf/pkg.c:488 [pkgconf_pkg_try_specific_path]: trying path: /usr/lib64/pkgconfig for jsoncpp
libpkgconf/pkg.c:501 [pkgconf_pkg_try_specific_path]: found: /usr/lib64/pkgconfig/jsoncpp.pc
libpkgconf/pkg.c:300 [pkgconf_pkg_new_from_file]: /usr/lib64/pkgconfig/jsoncpp.pc:1 > [libdir=/usr/lib64]
libpkgconf/pkg.c:300 [pkgconf_pkg_new_from_file]: /usr/lib64/pkgconfig/jsoncpp.pc:2 > [includedir=/usr/include]
libpkgconf/pkg.c:300 [pkgconf_pkg_new_from_file]: /usr/lib64/pkgconfig/jsoncpp.pc:3 > []
libpkgconf/pkg.c:300 [pkgconf_pkg_new_from_file]: /usr/lib64/pkgconfig/jsoncpp.pc:4 > [Name: jsoncpp]
libpkgconf/pkg.c:300 [pkgconf_pkg_new_from_file]: /usr/lib64/pkgconfig/jsoncpp.pc:5 > [Description: A C++ library for interacting with JSON]
libpkgconf/pkg.c:300 [pkgconf_pkg_new_from_file]: /usr/lib64/pkgconfig/jsoncpp.pc:6 > [Version: 1.8.3]
libpkgconf/pkg.c:300 [pkgconf_pkg_new_from_file]: /usr/lib64/pkgconfig/jsoncpp.pc:7 > [URL: https://github.com/open-source-parsers/jsoncpp]
libpkgconf/pkg.c:300 [pkgconf_pkg_new_from_file]: /usr/lib64/pkgconfig/jsoncpp.pc:8 > [Libs: -L${libdir} -ljsoncpp]
libpkgconf/fragment.c:146 [pkgconf_fragment_add]: added fragment {L, '/usr/lib64'} to list @0x5631c5cc5878
libpkgconf/fragment.c:146 [pkgconf_fragment_add]: added fragment {l, 'jsoncpp'} to list @0x5631c5cc5878
libpkgconf/pkg.c:300 [pkgconf_pkg_new_from_file]: /usr/lib64/pkgconfig/jsoncpp.pc:9 > [Cflags: -I${includedir}]
libpkgconf/fragment.c:146 [pkgconf_fragment_add]: added fragment {I, '/usr/include'} to list @0x5631c5cc58a8
libpkgconf/dependency.c:80 [pkgconf_dependency_addraw]: added dependency [jsoncpp = 1.8.3] to list @0x5631c5cc5920
libpkgconf/cache.c:86 [pkgconf_cache_add]: added @0x5631c5cc5820 to cache
libpkgconf/pkg.c:1437 [pkgconf_pkg_traverse]: jsoncpp: level 1999
libpkgconf/pkg.c:1452 [pkgconf_pkg_traverse]: jsoncpp: walking requires list
libpkgconf/dependency.c:80 [pkgconf_dependency_addraw]: added dependency [jsoncpp] to list @0x7ffd3793b7b8
libpkgconf/pkg.c:1437 [pkgconf_pkg_traverse]: virtual:world: level 2000
libpkgconf/pkg.c:1452 [pkgconf_pkg_traverse]: virtual:world: walking requires list
libpkgconf/pkg.c:1233 [pkgconf_pkg_verify_dependency]: trying to verify dependency: jsoncpp
libpkgconf/pkg.c:649 [pkgconf_pkg_find]: looking for: jsoncpp
libpkgconf/cache.c:56 [pkgconf_cache_lookup]: found: jsoncpp @0x5631c5cc5820
libpkgconf/pkg.c:681 [pkgconf_pkg_find]: jsoncpp is cached
libpkgconf/pkg.c:1437 [pkgconf_pkg_traverse]: jsoncpp: level 1999
libpkgconf/pkg.c:1452 [pkgconf_pkg_traverse]: jsoncpp: walking requires list
libpkgconf/pkg.c:1233 [pkgconf_pkg_verify_dependency]: trying to verify dependency: jsoncpp
libpkgconf/pkg.c:649 [pkgconf_pkg_find]: looking for: jsoncpp
libpkgconf/cache.c:56 [pkgconf_cache_lookup]: found: jsoncpp @0x5631c5cc5820
libpkgconf/pkg.c:681 [pkgconf_pkg_find]: jsoncpp is cached
1.8.3
libpkgconf/cache.c:106 [pkgconf_cache_remove]: removed @0x5631c5cc5820 from cache
libpkgconf/client.c:129 [pkgconf_client_deinit]: deinit @0x5631c4b91720
libpkgconf/cache.c:135 [pkgconf_cache_free]: cleared package cache`

**Comment by patrick96** [comment]
pkg-config definitely finds the proper jsoncpp version on your system. It seems that polybar for some reason compiles against another libjsoncpp file. I think we can close this, as it's probably just some weird configuration

**Comment by patrick96** [comment]
Alright, have a look at #1455. The actual issue seems to be that you most likely have two separate polybar executables on your system, and the outdated one is the one that is picked up by your shell.
