### ISSUE TITLE
Openbox - Missing icons for specific workspaces [xworkspaces module]

### ISSUE THREAD

**Issue by hhiru** [jaagr/polybar#964]
![image](https://user-images.githubusercontent.com/11262717/35117863-456536f8-fc90-11e7-9c80-797efa9c308c.png)

Is this intended? Can I only use one type of icon with openbox?

**Comment by patrick96** [comment]
The value of the `icon-*` parameters have to be `NAME;icon`, where `NAME` is the name of the workspace as defined in openbox and `icon` is simply the icon you want to set for it.
You can run `xprop -root _NET_DESKTOP_NAMES` to get a list of the workspace names that you need to use.
The `icon-*` parameters basically associate a workspace name with an icon.

**Comment by hhiru** [comment]
I see, thanks for clarifying the correct usage. I was confused by the default values in the wiki. Now it works!
