### ISSUE TITLE
[SOLVED] Cannot run Steam from Polybar

### ISSUE THREAD

**Issue by sistematico** [jaagr/polybar#969]
polybar 3.1.0-5-ge3c4498

  Features: +alsa +curl +i3 +mpd +network

Polybar config: http://ix.io/EqZ

  [lucas@majestic ~]:$ cat /usr/share/applications/steam.desktop | grep -m1 Exec
  Exec=/usr/bin/steam-runtime %U

Steam don't launch from Polybar, but launch from Rofi.

Thank you.

**Comment by patrick96** [comment]
Try to use the same exec command as in the steam.desktop file

**Comment by sistematico** [comment]
Thank you @patrick96 

Working now:
  menu-0-6-exec = /usr/bin/steam > /dev/null 2> /dev/null &
