### ISSUE TITLE
Icon not loading properly in BAT module

### ISSUE THREAD

**Issue by cthulhuvamp696** [jaagr/polybar#970]
I was previously using Font Awesome before they changed their font to multiple packages. I Followed the info in Issue #924 to resolve the display issues. But now i cannot get my BAT module ramp-capacity to display the appropriate information. 

I have it set up to look like the Zelda Life bar with hearts as the "Capacity" indicator:

like this :  83%.

I noticed in the font that the Full heart is part of "Font Awesome 5 Free:style=Solid" but the Empty one is part of "Font Awesome 5 Free:style=Regular"

I currently have it set up to load fonts as follows : 
   font-0 = "Font Awesome 5 Free:style=Solid:pixelsize=8;1"
   font-1 = "Font Awesome 5 Free:style=Regular:pixelsize=8;1"
   font-2 = "Font Awesome 5 Brands:pixelsize=8;1"
   font-3 = DevaVu Sans Mono:pixelsize=8;1

The hearts show as all full even when the ramp goes down. But if i change the order of them to load Regular before solid, they show up all empty.This is, im assuming, is due to FA being seperated into different packages.

Question i have is do i need to use another font package to get the information to show the way i want it, or is there a solution to make polybar pull the required information for the font types? Such as use the "Solid" for the full hearts, and "Regular" for the empty. 

Any assistance would be greatly appreciated.

**Comment by patrick96** [comment]
I see what you mean. It is the same icon but it is hollow in the `Regular` font and filled in in the `Solid` font.
There are two things you can do, either you use the `-font` label parameter to tell the label to use a certain font or use the `%{T}` font tag, if you need more granular control.
Both of these approaches are described on the [Wiki](https://github.com/jaagr/polybar/wiki/Fonts) (note that you need to use the font index+1)

**Comment by cthulhuvamp696** [comment]
So i don't know if i'm doing this correctly but i have this in my config and it is not working.

ramp-capacity-0 = %{T2}%{T-}
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = %{T2}%{T-}

**Comment by patrick96** [comment]
Can you post the exact config, this should be working

**Comment by cthulhuvamp696** [comment]
here is the link to my polybar config( sorry its not very well done i'm still learning)

https://github.com/cthulhuvamp696/dotfiles/blob/master/polybar/config

**Comment by patrick96** [comment]
The config you posted doesn't use any font tags. Please post the config where you tried to use the font tags and which didn't work.

**Comment by cthulhuvamp696** [comment]
Sorry about that, I have updated my repo, you should now be able to see my current config.

**Comment by patrick96** [comment]
In your config you use `%{T1}` tags, since the the font tags are 1-indexed, this refers to font-0 and is pretty much useless. Use `%{T2}...%{T-}` where you want the hollow hearts and no tags where you want the full hearts.

**Comment by cthulhuvamp696** [comment]
I have update the information and battery is at roughly 80% and is still not showing the appropriate Icons. My Repo has been updated to the most recent changes. Thank you for trying to help me solve this.

**Comment by cthulhuvamp696** [comment]
Disregard. It is working as intended. User error (forgot to reload the bar...) @patrick96 Thank you for helping me on this.
