### ISSUE TITLE
Maxlen ignored - mpd

### ISSUE THREAD

**Issue by leewdch** [jaagr/polybar#971]
I tried setting both label-maxlen and specific label lengths but they are ignored..

ncmpcpp 0.8.1
mpd 0.20.15

![image](https://user-images.githubusercontent.com/11262717/35198441-53ce0d4e-feef-11e7-8cd9-1117290f13c7.png)

**Comment by patrick96** [comment]
There is no `label-online`, try to use `label-song-maxlen` instead. But it's strange that the `%title:0:10%` token doesn't work. Can you post your whole configuration so that I can try to reproduce this on my end.

**Comment by hhiru** [comment]
here's  the whole config http://paste.debian.net/hidden/65ef2936/

**Comment by patrick96** [comment]
Yes the `-maxlen` option counts all characters, it can't differentiate between format tags and plain text.
I am now able to reproduce this, it seems not the format tags are the problem but the fact that you use the same token twice. From my testing I think polybar just takes the min and maxlen properties of the first time the token appears and uses it for all other occurences as well.

In the following two versions, the first one makes both tokens only display at most three characters and in the second variant, both tokens are displayed in full.
```dosini
label-song = %title:0:3% %title% 
label-song = %title% %title:0:3% 
```
