### ISSUE TITLE
How to compile polybar with pulseaudio support? (in PKGBUILD)

### ISSUE THREAD

**Issue by egeesin** [jaagr/polybar#977]
I tried to look every page/issue but I couldn't find any solution. How do I configure build in PKGBUILD?
I already tried to add "``-DENABLE_PULSEAUDIO="ON"``" at each one highlighted lines below and it didn't work.
```sh
...
build() {
  cd "${pkgname}/build" || exit 1
  cmake -DCMAKE_INSTALL_PREFIX=/usr       ..
  cmake --build      .              ^^^^^
}               ^^^^
...
```
- [``trizen -S polybar`` output](http://ix.io/EMB)
- [libpulse & alsa related packages I have](http://ix.io/EMF)

**Comment by patrick96** [comment]
Pulseaudio support is not inside any release yet. You'll need to use `polybar-git`, as long as you have the dependencies installed (`pulseaudio` should be enough), polybar should now compile with pulseaudio support.

**Comment by beanaroo** [comment]
Thanks for mentioning! I happened to be having the same confusion. I have added to the note in the wiki, if that's okay.
.

**Comment by patrick96** [comment]
@beanaroo Yeah, I was just about to do that but then I saw you already did. Thanks 😄
