### ISSUE TITLE
Polybar displaying second screen's bar below primary bar

### ISSUE THREAD

**Issue by Try431** [jaagr/polybar#980]
My `launch.sh` is as follows:

    # Terminate already running bar instances
    killall -q polybar

    # Wait until the processes have been shut down
    while pgrep -x polybar >/dev/null; do sleep 1; done
    
    if type "xrandr"; then
        for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
           MONITOR=$m polybar example &
        done
    else
        polybar --reload example &
    fi

However, despite detecting my second monitor, the second bar is populating beneath my main bar.

![selection_003](https://user-images.githubusercontent.com/25510761/35486441-f597b354-0422-11e8-96e3-37568abcdaab.png)

Anyone have any similar issues? I've tried manually setting the monitors on individual lines in `launch.sh`, but I get the same result.

Version: polybar 3.0.5
Relevant config: 

    [bar/example]
    monitor = ${env:MONITOR:}

Posts already looked at:
[#299](https://github.com/jaagr/polybar/issues/299)
[#763](https://github.com/jaagr/polybar/issues/763)
[#555](https://github.com/jaagr/polybar/issues/555)

**Comment by patrick96** [comment]
Can you run the bar with `-l info` and post the whole output here. Please also post the output of `xrandr --query | grep " connected" | cut -d" " -f1`

**Comment by Try431** [comment]
Output of `xrandr --query | grep " connected" | cut -d" " -f1`:

    LVDS-1-1
    HDMI-1-1

Output of `polybar -l info example`:

    * Loaded /home/isaac/.config/polybar/config
    * Environment var reference ${MONITOR} found (value=LVDS-1-1)
    * Loaded monitor LVDS-1-1 (1920x1080+1920+0)
    warn: The config parameter `bar/example.border-top` is deprecated, use `bar/example.border-top-size` instead.
    * Bar geometry: 1920x41+1920+-3
    * Starting application
    * Starting module/i3
    * Starting module/date
    * Starting module/wireless-network
    * Starting module/cpu
    * Starting module/memory
    * Starting module/filesystem
    * Starting module/filesystem2
    * Starting module/temperature
    * Starting module/pavolume
    * Starting module/backlight
    * Starting module/battery
    * Starting module/powermenu
    * Eventqueue worker (thread-id=8)
    * Entering event loop (thread-id=1)
    * module/pavolume: Invoking shell command: "~/scripts/pavolume.sh"
    * Configured DPI = 96x96
    * Loaded font "FontAwesome:pixelsize=11" (name=FontAwesome, offset=0, file=/usr/share/fonts/opentype/font-awesome/FontAwesome.otf)
    * Loaded font "PragmataPro Nerd Font:pixelsize=11" (name=DejaVu Sans, offset=0, file=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf)
    * Bar window: 0x3400001
    warn: Alpha support for the systray is limited. See the wiki for more details.
    * Activating tray manager
    * Tray window: 0x3400005
    warn: Systray selection already managed (window=0x1400005)
    * Deactivating tray manager
    * module/i3: Rebuilding cache
    * module/date: Rebuilding cache
    * module/wireless-network: Rebuilding cache
    * module/cpu: Rebuilding cache
    * module/memory: Rebuilding cache
    * module/filesystem: Rebuilding cache
    * module/filesystem2: Rebuilding cache
    * module/temperature: Rebuilding cache
    * module/pavolume: Rebuilding cache
    * module/backlight: Rebuilding cache
    * module/battery: Rebuilding cache
    * module/powermenu: Rebuilding cache
    * Redrawing bar window
    * Redrawing bar window
    * module/date: Rebuilding cache
    * module/wireless-network: Rebuilding cache
    * module/cpu: Rebuilding cache
    * module/memory: Rebuilding cache
    * module/temperature: Rebuilding cache
    * Redrawing bar window
    * module/pavolume: Invoking shell command: "~/scripts/pavolume.sh"
    * module/date: Rebuilding cache
    * module/wireless-network: Rebuilding cache
    * module/cpu: Rebuilding cache
    * module/memory: Rebuilding cache
    * module/temperature: Rebuilding cache
    * Redrawing bar window


Note that I've tried with and without having MONITOR defined as an env variable.

**Comment by patrick96** [comment]
Can you add `-l info` to your `launch.sh` and post the output. I want to make sure polybar actually tries to load on the right monitors.

What WM are you using?

**Comment by Try431** [comment]
I'm using i3wm with i3-gaps on Ubuntu 16.04.3 LTS
Polybar does try to load on the right monitors:

    xrandr is /usr/bin/xrandr
    Bars launched...
    * Loaded /home/isaac/.config/polybar/config
    * Loaded /home/isaac/.config/polybar/config
    * Environment var reference ${MONITOR} found (value=HDMI-1-1)
    * Loaded monitor HDMI-1-1 (1920x1080+0+0)
    warn: The config parameter `bar/example.border-top` is deprecated, use `bar/example.border-top-size` instead.
    * Bar geometry: 1920x41+0+-3
    * Environment var reference ${MONITOR} found (value=LVDS-1-1)
    * Loaded monitor LVDS-1-1 (1920x1080+1920+0)
    warn: The config parameter `bar/example.border-top` is deprecated, use `bar/example.border-top-size` instead.
    * Bar geometry: 1920x41+1920+-3
    * Starting application
    * Starting module/i3
    * Starting module/date
    * Starting module/wireless-network
    * Starting module/cpu
    * Starting module/memory
    * Starting module/filesystem
    * Starting module/filesystem2
    * Starting module/temperature
    * Starting module/pavolume
    * Starting module/backlight
    * Starting module/battery
    * module/pavolume: Invoking shell command: "~/scripts/pavolume.sh"
    * Starting module/powermenu
    * Entering event loop (thread-id=1)
    * Eventqueue worker (thread-id=12)
    * Configured DPI = 96x96
    * Loaded font "FontAwesome:pixelsize=11" (name=FontAwesome, offset=0, file=/usr/share/fonts/opentype/font-awesome/FontAwesome.otf)
    * Loaded font "PragmataPro Nerd Font:pixelsize=11" (name=DejaVu Sans, offset=0, file=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf)
    * Bar window: 0x3200001
    warn: Alpha support for the systray is limited. See the wiki for more details.
    * Activating tray manager
    * Tray window: 0x3200005
    * module/i3: Rebuilding cache
    * module/date: Rebuilding cache
    * module/wireless-network: Rebuilding cache
    * module/cpu: Rebuilding cache
    * module/memory: Rebuilding cache
    * module/filesystem: Rebuilding cache
    * module/filesystem2: Rebuilding cache
    * module/temperature: Rebuilding cache
    * module/pavolume: Rebuilding cache
    * module/backlight: Rebuilding cache
    * module/battery: Rebuilding cache
    * module/powermenu: Rebuilding cache
    * Redrawing bar window
    * Starting application
    * Starting module/i3
    * Starting module/date
    * Starting module/wireless-network
    * Starting module/cpu
    * Starting module/memory
    * Starting module/filesystem
    * Starting module/filesystem2
    * Starting module/temperature
    * Starting module/pavolume
    * Starting module/backlight
    * Starting module/battery
    * Starting module/powermenu
    * Entering event loop (thread-id=1)
    * Eventqueue worker (thread-id=7)
    * module/pavolume: Invoking shell command: "~/scripts/pavolume.sh"
    * Configured DPI = 96x96
    * module/backlight: Rebuilding cache
    * Loaded font "FontAwesome:pixelsize=11" (name=FontAwesome, offset=0, file=/usr/share/fonts/opentype/font-awesome/FontAwesome.otf)
    * Loaded font "PragmataPro Nerd Font:pixelsize=11" (name=DejaVu Sans, offset=0, file=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf)
    * Bar window: 0x1400001
    warn: Alpha support for the systray is limited. See the wiki for more details.
    * Activating tray manager
    * Tray window: 0x1400005
    warn: Systray selection already managed (window=0x3200005)
    * Deactivating tray manager
    * module/i3: Rebuilding cache
    * module/date: Rebuilding cache
    * module/wireless-network: Rebuilding cache
    * module/cpu: Rebuilding cache
    * module/memory: Rebuilding cache
    * module/filesystem: Rebuilding cache
    * module/filesystem2: Rebuilding cache
    * module/temperature: Rebuilding cache
    * module/pavolume: Rebuilding cache
    * module/backlight: Rebuilding cache
    * module/battery: Rebuilding cache
    * module/powermenu: Rebuilding cache
    * Redrawing bar window
    * Redrawing bar window
    * module/date: Rebuilding cache
    * module/wireless-network: Rebuilding cache
    * module/cpu: Rebuilding cache
    * module/memory: Rebuilding cache
    * module/temperature: Rebuilding cache
    * Redrawing bar window
    * module/pavolume: Invoking shell command: "~/scripts/pavolume.sh"
    * Notifying pending tray clients
    * Processing docking request from 0x22000ae
    * Redraw tray container (id=0x3200005)
    * Redrawing bar window
    * Tray root pixmap (rootpmap=0x1800001, geom=1920x1080+0+0, tray=0x3200005, pmap=0x3200006, gc=0x3200007)
    error: Failed to get slice of root pixmap (XCB_MATCH (8))
    * Redraw tray container (id=0x3200005)
    * Redraw tray container (id=0x3200005)
    * module/date: Rebuilding cache
    * module/wireless-network: Rebuilding cache
    * module/cpu: Rebuilding cache
    * module/memory: Rebuilding cache
    * module/temperature: Rebuilding cache
    * Redrawing bar window
    * module/pavolume: Invoking shell command: "~/scripts/pavolume.sh"
    * module/date: Rebuilding cache
    * module/wireless-network: Rebuilding cache
    * module/cpu: Rebuilding cache
    * module/memory: Rebuilding cache
    * module/temperature: Rebuilding cache
    * Redrawing bar window

But unfortunately, the HDMI-1-1 bar is still populated on the LVDS-1-1 screen.

**Comment by NBonaparte** [comment]
If you load each of them independently, do they work?
It looks like they have correct geometry (LVDS is offset by 1920px) from the output, but you should also check this using xprop (`xprop` then click on the bar and look at the strut values).

I also saw you're on 3.0.5; try updating to the latest version or use the git version, which has a native Pulseaudio module so you don't have to use `pavolume.sh`.

**Comment by Try431** [comment]
@NBonaparte  Upon upgrading to version 3.1.0, I get the following error when running `launch.sh`

`error: Disabling module "pulseaudio" (reason: Unknown module: internal/pulseaudio)`

My new pulseaudio config section, following format from [Pulseaudio config link](https://github.com/jaagr/polybar/wiki/Module:-pulseaudio)

    [module/pulseaudio]
    type = internal/pulseaudio
    
    sink = alsa_output.pci-0000_00_1b.0.analog-stereo
    ;interval = 1
    
    ;format-padding = 2
    format-volume = <ramp-volume> <label-volume>
    
    ramp-volume-0 = 🔈
    ramp-volume-1 = 🔉
    ramp-volume-2 = 🔊


As far as running them independently, I've tried that before but to no avail. Manually setting the `MONITOR` env variable to `HDMI-1-1`, verifying that it's properly connected via `xrandr`, the correct bar populates (i.e., the workspaces are correct), but still on the primary monitor (i.e., `LVDS-1-1`)

When attempting to run polybar while a second monitor is connected, I also get the following error:

`error: Failed to get slice of root pixmap (XCB_MATCH (8))`

This results in the tray not being transparent, which seems to have some history (#879)

**Comment by NBonaparte** [comment]
The module was added after the 3.1.0 release, so you'll only get it if you're using the latest commit from master.

Do you have `override-redirect = true` and `wm-restack = i3` in your config? 
I'm guessing that i3 is forcing the bar to move somehow, because the strut geometry is correct.

**Comment by Try431** [comment]
I removed polybar and rebuilt from source yesterday, making sure I was using the 3.1.0 git branch. I'll try again today.

This is the entirety of my polybar config: https://pastebin.com/jxRzdwz0

**Comment by NBonaparte** [comment]
Try adding `override-redirect = true` and`wm-restack = i3` to the bar options.

**Comment by Try431** [comment]
So the `override-redirect = true` does populate the bar on the second monitor correctly; however, it results in the bar overlapping with programs (i.e., applications no longer seem to know the bar is there):

![selection_005](https://user-images.githubusercontent.com/25510761/35745391-02ac2f9c-07f8-11e8-821b-dd6aad56e8f6.png)


![selection_006](https://user-images.githubusercontent.com/25510761/35745450-2bfe91fa-07f8-11e8-8b8a-f0ecdced3f66.png)

With `wm-restack = i3`, the bar stays above applications; otherwise, applications over the bar (as I'm sure is the intent).

**Comment by NBonaparte** [comment]
Sorry for the delay; AFAIK one way I've seen this resolved is by creating a dummy i3bar or something similar which has the same size and location as polybar. This is due to i3 being quite finicky with handling status bars (this same issue occurs with non-full length bars).

**Comment by patrick96** [comment]
Since `override-redirect` fixes this, this seems to be another quirky way i3 positions DOCK windows.

**Comment by Try431** [comment]
Just wanted to leave an update on this ticket. I never really got around to ironing this out, but today decided to tackle it again and I've finally found a solution that works perfectly for my setup. Figured I should post here in case some other person stumbles upon this with a similar issue (which in my research, seems to be quite common).

As discussed above, setting `override-redirect = true` and `wm-restack = i3` did address the issue of polybar appearing on the wrong monitors, but that didn't quite work for me because i3 then didn't know to allocate space for it. What I ended up doing is modifying my i3-gaps settings to create space at the top for the bar (`gaps top`), and I commented out smart-gaps so that single-window workspaces would have that space as well.

_I should note that the [other common workaround](https://github.com/polybar/polybar/wiki/Known-Issues#override-redirect-in-i3) is to create a dummy transparent polybar that takes up the same length as one's primary bar, but without the `override-redirect` or `wm-restack` settings so that i3 knows to allocate space for it. I already used i3-gaps, so I found that solution much simpler and cleaner_
````
### i3-gaps config ###

# Disabling windows for i3-gaps
for_window [class="^.*"] border pixel 1

gaps inner 13
#smart_gaps on
gaps top 25
gaps left -11
gaps right -11
gaps bottom -12


# Colors
# class                 border  backgr. text    indicator
client.focused          #BEBEBE #BEBEBE #2D2D2D #BEBEBE
client.focused_inactive #2d2d2d #2d2d2d #dcdcdc #484e50
client.unfocused        #808080 #808080 #dcdcdc #808080
client.urgent           #2D2D2D #2D2D2D #dcdcdc #900000
````

You'll also see that I forced the left, right, and bottom edges of the windows out to create more space.

So, this addressed the issues for any non-transparent windows (text editors, browsers, etc.), but I really like working with transparent terminals, and when going fullscreen in one of those, I could still see my polybar through the transparent window, and it muddled the text in the terminal. Luckily, polybar has a [feature](https://github.com/polybar/polybar/wiki/Module:-ipc) wherein you can send commands to the bar if you have `enable-ipc = true` set in your [bar/<name>] settings. **Note - you don't have to actually need to have a separate module, that's only for if you want to interact with said module via ipc messages**

Now that my bar can take message, I tweaked my fullscreen bindsym to also toggle hiding the polybar: `bindsym $mod+f fullscreen; exec polybar-msg cmd toggle`

And now we're good! On a multi-monitor setup, both bars are in their correct positions and are properly hidden away by both non- and fully-transparent windows.
