### ISSUE TITLE
formatting syntax in i3 workspace names should be ignored

### ISSUE THREAD

**Issue by Nervengift** [jaagr/polybar#984]
My i3wm + polybar setup uses `strip-wsnumbers = true` to set a sorting order for my static workspaces (e.g. browser, music,...).

Since I still want to see numbers for "dynamic" workspaces (mapped to mod+0..9), these end up being named e.g. `1:1:stuff` (shown as `1:stuff` in the bar).

This worked well with i3bar but in polybar this seems to be interpreted as some kind of format syntax? E.g. `1:1:rust` will make the whole i3 module right-aligned, `1:1:R...` will result in inverted foreground and background. All format codes from the [Formatting wiki page](https://github.com/jaagr/polybar/wiki/Formatting) seem to work.

If the first letter of the actual name is no format code, the whole bar will be empty and I get 
```error: Failed to parse contents (reason: Unrecognized token 'b')```

This does not happen with "normal" workspace names like `1:rust`.

Is this an undocumented format code syntax? Regardless of that it should probably not be interpreted in workspace names?

(the obvious workaround is to have workspaces named like `1:1.rust` instead but still…)

**Comment by patrick96** [comment]
This is a *very* peculiar behaviour and defnitely not intended ;)

Try to run the bar with the `-s` option and post the output (this makes polybar output the text, with the format tags, to the terminal).

Can you also post your config (i3 and polybar) so that I can try to reproduce this on my system and track down the problem.

**Comment by Nervengift** [comment]
**output line** from `polybar -s primary` with a `6:6:r` workspace (-> all workspaces beginning from 6 are on the right instead of left):

`%{l}%{A5:i3wm-wsprev: A4:i3wm-wsnext: A1:i3wm-wsfocus-5\:5:obst:} 5:obst %{A A1:i3wm-wsfocus-6\:6:r: u#ffb52a +u B#ffb52a F#222} 6:r %{B- F- -u A A1:i3wm-wsfocus-11\::}  %{A A1:i3wm-wsfocus-12\::}  %{A A1:i3wm-wsfocus-14\::}  %{A A A u-}%{r}%{u#0a6cf5 +u F#555}%{F- u#0a6cf5 A1:datetoggle:} 12:07%{A -u u-} `

(seems like the `:` are not escaped correctly in the `%{A` block?)

condensed **polybar** config: [config](https://github.com/jaagr/polybar/files/1689071/polybarconfig.txt)

There's not really something specific to this in my **i3 config** (and it's rather hard to boil down), but you should be able to reproduce by simply typing `i3-msg rename workspace to 1:1:r` for example
