### ISSUE TITLE
battery module crashing

### ISSUE THREAD

**Issue by rangerlatham** [jaagr/polybar#985]
using version 3.1.0-38-g2a056d5, the battery module fails to load, and the stderr output is:
 
error: module/battery: std::bad_alloc
warn: Stopping 'module/battery'...

this is my config for the module: 

[module/battery]
type=internal/battery
label-discharging =  %percentage%%
full-at=99
battery=BAT0

this issue does not arise when using the binary shipped by my distro, (void linux), however that version does not seem to be built with pulseaudio support. 

has anyone else experienced this issue? any ideas on a solution?

**Comment by mattyrc** [comment]
I'm also seeing this on Arch with version 3.1.0-39-g26abd0f.
