### ISSUE TITLE
error while loading shared libraries: libjsoncpp.so.19:

### ISSUE THREAD

**Issue by ovess** [jaagr/polybar#987]
polybar: error while loading shared libraries: libjsoncpp.so.19: cannot open shared object file: No such file or directory

Seems to be a recurrent problem?

**Comment by ovess** [comment]
ok, syslinked libjsoncpp.so.20 to libjsoncpp.so.19. Now it works.

**Comment by patrick96** [comment]
Or recompile polybar. The jsoncpp project seems to be changing the SONAME on every patch release, which means you have to recompile polybar basically everytime you update jsoncpp
