### ISSUE TITLE
make dependency to libjsoncpp more stable

### ISSUE THREAD

**Issue by x70b1** [jaagr/polybar#994]
Everytime when there is an update for libjsoncpp it breaks Polybar:

```
polybar: error while loading shared libraries: libjsoncpp.so.19: cannot open shared object file: No such file or directory
```

To resolve this polybar has to be rebuild. That is okay. 
But it would be better if doesn't happen. Maybe there is a more stable way for this?

**Comment by patrick96** [comment]
I don't think there is a way to achieve this. The `SONAME` of the libray changes on every update, indicating that the new version is possibly not compatible with code built for older versions, although it is most of the times.

**Comment by x70b1** [comment]
Yes, okay. Then this behavior is intended. Thanks!
