### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by smaakmaker** [jaagr/polybar#996]
All of a suden, I can't run polybar anymore. It happenend when I was editing my i3 config, and reloaded my i3 session. I really doubt that caused it though, all I did was change my font. Now when I try to run polybar it prints the following:

> polybar: libjsoncpp.so.19: cannot open shared object file: No such file or directory

Now, I know there was a similar issue a while back, which was fixed by installing the jsoncpp package, but I have that one installed, updated and all. It also doesn't work when I try to run polybar without any modules specified. 
Does anyone have any idea how to fix this? I ran out of possible solutions an hour ago.

**Comment by patrick96** [comment]
See [Known-Issues](https://github.com/jaagr/polybar/wiki/Known-Issues)
